import { ListeningTestData } from "./listening-tests-data";

const VOICES = {
  roger: "CwhRBWXzGAHq8TQ4Fs17",
  sarah: "EXAVITQu4vr4xnSDxMaL",
  george: "JBFqnCBsd6RMkjVDRZzb",
  laura: "FGY2WhTYpPnrIDTdsKH5",
  charlie: "IKne3meq5aSn9XLyUdCD",
  alice: "Xb7hH8MSUJpSbSDYk0k2",
  brian: "nPczCjzI2devNBz1zQrb",
};

export const LISTENING_TEST_2: ListeningTestData = {
  id: 2,
  title: "Listening Test 2",
  totalQuestions: 40,
  timeLimit: 40,
  sections: [
    // ─── SECTION 1: Everyday Conversation ───
    {
      sectionNumber: 1,
      title: "Hotel Reservation Enquiry",
      description: "A conversation between a hotel receptionist and a guest making a reservation.",
      context: "You will hear a conversation between a receptionist at a hotel and a man who wants to book a room. First, you have some time to look at questions 1 to 10.",
      dialogue: [
        { speaker: "Receptionist", voiceId: VOICES.sarah, text: "Good afternoon, the Grand Oak Hotel. How may I help you?" },
        { speaker: "Man", voiceId: VOICES.roger, text: "Hello, I'd like to make a reservation for next month, please. My name is Robert Williamson." },
        { speaker: "Receptionist", voiceId: VOICES.sarah, text: "Of course, Mr Williamson. Could you spell your surname for me?" },
        { speaker: "Man", voiceId: VOICES.roger, text: "Yes, it's W-I-L-L-I-A-M-S-O-N." },
        { speaker: "Receptionist", voiceId: VOICES.sarah, text: "Thank you. And when would you like to check in?" },
        { speaker: "Man", voiceId: VOICES.roger, text: "On the twenty-third of April. And I'll be staying for five nights, so checking out on the twenty-eighth." },
        { speaker: "Receptionist", voiceId: VOICES.sarah, text: "The twenty-third to the twenty-eighth of April. Let me check availability. We have three room types available. A standard double room at eighty-five pounds per night, a superior room at one hundred and twenty pounds, and a suite at two hundred and ten pounds." },
        { speaker: "Man", voiceId: VOICES.roger, text: "I think the superior room would be perfect. Does that include breakfast?" },
        { speaker: "Receptionist", voiceId: VOICES.sarah, text: "Yes, continental breakfast is included. Full English breakfast is available at an additional twelve pounds per person per day." },
        { speaker: "Man", voiceId: VOICES.roger, text: "I'll go with the continental, that's fine. And is there parking available at the hotel?" },
        { speaker: "Receptionist", voiceId: VOICES.sarah, text: "Yes, we have an underground car park. It's eight pounds per day for hotel guests, or you can use the public car park on Elm Street which is free but it's about a ten-minute walk." },
        { speaker: "Man", voiceId: VOICES.roger, text: "I'll use the hotel car park, thanks. Could I also arrange an airport transfer? I'm arriving at Gatwick at half past two in the afternoon." },
        { speaker: "Receptionist", voiceId: VOICES.sarah, text: "Certainly. Our shuttle service from Gatwick costs thirty-five pounds per person one way. The journey takes approximately forty-five minutes depending on traffic. Shall I book that for your arrival?" },
        { speaker: "Man", voiceId: VOICES.roger, text: "Yes, please. And one more thing — do you have a swimming pool or gym?" },
        { speaker: "Receptionist", voiceId: VOICES.sarah, text: "We have both. The pool is open from six a.m. to nine p.m., and the fitness centre is open twenty-four hours. Both are complimentary for hotel guests. We also have a spa which offers treatments from forty pounds." },
        { speaker: "Man", voiceId: VOICES.roger, text: "Wonderful. Could I get a contact email for any further questions?" },
        { speaker: "Receptionist", voiceId: VOICES.sarah, text: "Of course, it's reservations at grandoak dot co dot uk." },
      ],
      questions: [
        { number: 1, type: "fill_blank", text: "Guest's full name:", correctAnswer: "Robert Williamson", explanation: "He says his name is Robert Williamson." },
        { number: 2, type: "fill_blank", text: "Check-in date:", correctAnswer: "23 April", explanation: "He wants to check in on the twenty-third of April." },
        { number: 3, type: "fill_blank", text: "Number of nights:", correctAnswer: "5", explanation: "Staying for five nights." },
        { number: 4, type: "fill_blank", text: "Cost of superior room per night: £_______", correctAnswer: "120", explanation: "Superior room at one hundred and twenty pounds." },
        { number: 5, type: "fill_blank", text: "Cost of hotel parking per day: £_______", correctAnswer: "8", explanation: "Eight pounds per day for hotel guests." },
        { number: 6, type: "short_answer", text: "What time does the guest's flight arrive at Gatwick?", correctAnswer: "2:30", explanation: "Arriving at half past two in the afternoon." },
        { number: 7, type: "short_answer", text: "How long does the airport shuttle take?", correctAnswer: "45 minutes", explanation: "Approximately forty-five minutes." },
        { number: 8, type: "short_answer", text: "What are the pool opening hours?", correctAnswer: "6am to 9pm", explanation: "Open from six a.m. to nine p.m." },
        { number: 9, type: "mcq", text: "Which room type does the guest choose?", options: ["A Standard double", "B Superior", "C Suite"], correctAnswer: "B", explanation: "He says the superior room would be perfect." },
        { number: 10, type: "mcq", text: "What type of breakfast is included in the room rate?", options: ["A No breakfast", "B Continental breakfast", "C Full English breakfast"], correctAnswer: "B", explanation: "Continental breakfast is included." },
      ],
    },

    // ─── SECTION 2: Informative Monologue ───
    {
      sectionNumber: 2,
      title: "Welcome to Harborview Museum",
      description: "A museum guide giving information about the exhibits and facilities to a group of visitors.",
      context: "You will hear a museum guide talking to a group of visitors. First, you have some time to look at questions 11 to 20.",
      dialogue: [
        { speaker: "Guide", voiceId: VOICES.george, text: "Welcome, everyone, to the Harborview Museum of Natural History. I'm Janet Collins, your guide for today. Before we start the tour, let me give you some essential information about the museum and what you'll see today." },
        { speaker: "Guide", voiceId: VOICES.george, text: "The museum was founded in eighteen ninety-five by Sir Edmund Crawford, a renowned Victorian naturalist. The current building was designed by the architect Thomas Langley and opened to the public in nineteen oh three. It was extensively renovated in two thousand and nineteen at a cost of fourteen million pounds." },
        { speaker: "Guide", voiceId: VOICES.george, text: "We're arranged over four floors. The ground floor, where we are now, houses the main reception, the gift shop, and our permanent marine life exhibition. This is our most popular exhibit, featuring a seventeen-metre model of a blue whale suspended from the ceiling." },
        { speaker: "Guide", voiceId: VOICES.george, text: "On the first floor, you'll find our geological collection, which includes over thirty-five thousand mineral and rock specimens from around the world. There's also an interactive earthquake simulator which is particularly popular with younger visitors." },
        { speaker: "Guide", voiceId: VOICES.george, text: "The second floor is dedicated to our dinosaur gallery. This is home to the museum's most prized exhibit — a nearly complete Tyrannosaurus rex skeleton discovered in Montana in nineteen ninety-two. We also have a hands-on fossil laboratory where you can try your hand at cleaning real fossils." },
        { speaker: "Guide", voiceId: VOICES.george, text: "The third floor houses our temporary exhibition space. Currently, we're showing 'Life in the Ice Age', which runs until the thirty-first of March. This exhibition features reconstructions of Ice Age animals including a woolly mammoth and a sabre-toothed tiger." },
        { speaker: "Guide", voiceId: VOICES.george, text: "Now, regarding facilities. The café is located on the ground floor next to the gift shop. It serves hot and cold meals from ten in the morning until four thirty in the afternoon. There are also vending machines on each floor near the lift. The museum closes at five thirty, with last admission at four forty-five." },
        { speaker: "Guide", voiceId: VOICES.george, text: "For families, we offer activity sheets for children aged five to twelve, which are available free of charge from reception. There's also a dedicated children's discovery zone on the first floor with hands-on experiments and craft activities." },
      ],
      questions: [
        { number: 11, type: "mcq", text: "When was the museum founded?", options: ["A 1893", "B 1895", "C 1903"], correctAnswer: "B", explanation: "Founded in eighteen ninety-five." },
        { number: 12, type: "mcq", text: "How much did the 2019 renovation cost?", options: ["A £4 million", "B £14 million", "C £40 million"], correctAnswer: "B", explanation: "Fourteen million pounds." },
        { number: 13, type: "mcq", text: "What is the museum's most popular exhibit?", options: ["A The dinosaur gallery", "B The earthquake simulator", "C The marine life exhibition"], correctAnswer: "C", explanation: "The permanent marine life exhibition is described as most popular." },
        { number: 14, type: "mcq", text: "When was the T. rex skeleton discovered?", options: ["A 1990", "B 1992", "C 1995"], correctAnswer: "B", explanation: "Discovered in Montana in nineteen ninety-two." },
        { number: 15, type: "sentence_completion", text: "The blue whale model is _______ metres long.", correctAnswer: "17", explanation: "A seventeen-metre model of a blue whale." },
        { number: 16, type: "sentence_completion", text: "The geological collection has over _______ specimens.", correctAnswer: "35000", explanation: "Over thirty-five thousand mineral and rock specimens." },
        { number: 17, type: "sentence_completion", text: "The museum closes at _______.", correctAnswer: "5:30", explanation: "The museum closes at five thirty." },
        { number: 18, type: "map_labeling", text: "The café is located on which floor?", options: ["A Ground floor", "B First floor", "C Second floor", "D Third floor"], correctAnswer: "A", explanation: "The café is located on the ground floor." },
        { number: 19, type: "map_labeling", text: "The dinosaur gallery is on which floor?", options: ["A Ground floor", "B First floor", "C Second floor", "D Third floor"], correctAnswer: "C", explanation: "The second floor is dedicated to our dinosaur gallery." },
        { number: 20, type: "map_labeling", text: "The temporary exhibition is on which floor?", options: ["A Ground floor", "B First floor", "C Second floor", "D Third floor"], correctAnswer: "D", explanation: "The third floor houses our temporary exhibition space." },
      ],
    },

    // ─── SECTION 3: Academic Discussion ───
    {
      sectionNumber: 3,
      title: "Renewable Energy Research Assignment",
      description: "Two university students and their tutor discussing a research assignment on renewable energy sources.",
      context: "You will hear a discussion between two students and their tutor about a research project. First, you have some time to look at questions 21 to 30.",
      dialogue: [
        { speaker: "Tutor", voiceId: VOICES.brian, text: "Right, James and Priya, let's discuss your progress on the renewable energy assignment. You've been looking at different energy sources, haven't you? James, you were focusing on wind energy?" },
        { speaker: "James", voiceId: VOICES.charlie, text: "Yes, that's right. I've been researching offshore wind farms, particularly the developments in the North Sea. The UK currently has the largest offshore wind capacity in the world, generating about forty per cent of its electricity from wind in peak periods." },
        { speaker: "Priya", voiceId: VOICES.laura, text: "That's impressive. I've been looking at solar energy, specifically the advances in photovoltaic cell efficiency. The latest panels can convert about twenty-two per cent of sunlight into electricity, compared to just six per cent when they were first commercially available in the nineteen fifties." },
        { speaker: "Tutor", voiceId: VOICES.brian, text: "Good, good. Now, how are you planning to structure the report? Remember, it needs to be between eight thousand and ten thousand words." },
        { speaker: "James", voiceId: VOICES.charlie, text: "We thought we'd divide it into five main chapters. The first chapter will cover the history and background of renewable energy. Then I'll write chapters two and three on wind energy — one on technology and one on case studies." },
        { speaker: "Priya", voiceId: VOICES.laura, text: "And I'll handle chapters four and five on solar energy. Chapter four will be the technical aspects, and chapter five will look at the economic viability and government subsidies in different countries." },
        { speaker: "Tutor", voiceId: VOICES.brian, text: "That sounds well-organised. Have you considered including a comparative analysis? It would strengthen your conclusion to compare the cost per kilowatt hour of different renewable sources." },
        { speaker: "James", voiceId: VOICES.charlie, text: "That's a good point. I found some data showing that offshore wind currently costs about forty-eight pounds per megawatt hour, while onshore wind is cheaper at around forty-one pounds. Solar has come down dramatically to about thirty-seven pounds per megawatt hour." },
        { speaker: "Priya", voiceId: VOICES.laura, text: "Actually, I read a report from the International Renewable Energy Agency that projects solar costs will fall by a further twenty-five per cent by twenty thirty. The main driver is improvements in manufacturing processes in China, which produces about seventy-five per cent of the world's solar panels." },
        { speaker: "Tutor", voiceId: VOICES.brian, text: "Excellent research, both of you. One thing I'd suggest is including a section on energy storage, since that's really the key challenge for all intermittent renewable sources. Battery technology has improved enormously — lithium-ion battery costs have fallen by about ninety per cent since twenty ten." },
        { speaker: "James", voiceId: VOICES.charlie, text: "That's actually something I wanted to ask about. There's been a lot of news about solid-state batteries. Do you think they'll replace lithium-ion in the next decade?" },
        { speaker: "Tutor", voiceId: VOICES.brian, text: "It's certainly possible. Toyota has announced plans to introduce solid-state batteries in their vehicles by twenty twenty-seven. The main advantages are faster charging, greater energy density, and improved safety. But the manufacturing costs are still very high." },
      ],
      questions: [
        { number: 21, type: "matching", text: "James is researching:", matchOptions: ["A Solar energy", "B Wind energy", "C Battery technology", "D Nuclear energy"], correctAnswer: "B", explanation: "James was focusing on wind energy." },
        { number: 22, type: "matching", text: "Priya is researching:", matchOptions: ["A Solar energy", "B Wind energy", "C Battery technology", "D Nuclear energy"], correctAnswer: "A", explanation: "Priya has been looking at solar energy." },
        { number: 23, type: "matching", text: "Who suggested including a section on energy storage?", matchOptions: ["A James", "B Priya", "C The tutor", "D An external researcher"], correctAnswer: "C", explanation: "The tutor suggested including a section on energy storage." },
        { number: 24, type: "matching", text: "The cheapest renewable energy source per megawatt hour is:", matchOptions: ["A Offshore wind", "B Onshore wind", "C Solar", "D Nuclear"], correctAnswer: "C", explanation: "Solar is about thirty-seven pounds per megawatt hour." },
        { number: 25, type: "fill_blank", text: "The report must be between 8,000 and _______ words.", correctAnswer: "10000", explanation: "Between eight thousand and ten thousand words." },
        { number: 26, type: "fill_blank", text: "Modern solar panels convert about _______ per cent of sunlight.", correctAnswer: "22", explanation: "About twenty-two per cent." },
        { number: 27, type: "fill_blank", text: "China produces about _______ per cent of the world's solar panels.", correctAnswer: "75", explanation: "About seventy-five per cent." },
        { number: 28, type: "mcq", text: "How much has the cost of lithium-ion batteries fallen since 2010?", options: ["A About 70%", "B About 80%", "C About 90%"], correctAnswer: "C", explanation: "Costs have fallen by about ninety per cent since twenty ten." },
        { number: 29, type: "mcq", text: "When does Toyota plan to introduce solid-state batteries?", options: ["A 2025", "B 2027", "C 2030"], correctAnswer: "B", explanation: "Toyota plans to introduce them by twenty twenty-seven." },
        { number: 30, type: "mcq", text: "How many chapters will the report have?", options: ["A 4", "B 5", "C 6"], correctAnswer: "B", explanation: "They planned five main chapters." },
      ],
    },

    // ─── SECTION 4: Academic Lecture ───
    {
      sectionNumber: 4,
      title: "The Psychology of Decision Making",
      description: "A university lecture on cognitive biases and how they affect human decision-making processes.",
      context: "You will hear a lecture about decision-making psychology. First, you have some time to look at questions 31 to 40.",
      dialogue: [
        { speaker: "Lecturer", voiceId: VOICES.brian, text: "Today's lecture focuses on the fascinating field of decision-making psychology. Despite believing ourselves to be rational beings, human beings are remarkably susceptible to cognitive biases — systematic errors in thinking that affect our judgments and decisions. Research by Daniel Kahneman, who won the Nobel Prize in Economics in two thousand and two, has revolutionised our understanding of these processes." },
        { speaker: "Lecturer", voiceId: VOICES.brian, text: "The first bias I want to discuss is known as the anchoring effect. This refers to our tendency to rely too heavily on the first piece of information we encounter. In a classic experiment, researchers asked participants to spin a wheel that landed on either ten or sixty-five. They were then asked to estimate what percentage of African countries belonged to the United Nations. Those who spun ten guessed around twenty-five per cent, while those who spun sixty-five estimated around forty-five per cent. The random number had no logical connection, yet it significantly influenced their answers." },
        { speaker: "Lecturer", voiceId: VOICES.brian, text: "Another important bias is the availability heuristic. This is where people assess the likelihood of events based on how easily examples come to mind. After a plane crash receives extensive media coverage, for instance, many people overestimate the risk of flying, even though statistically, flying remains approximately seventy times safer than driving per mile travelled." },
        { speaker: "Lecturer", voiceId: VOICES.brian, text: "Loss aversion is perhaps one of the most powerful biases. Research shows that the psychological pain of losing something is approximately twice as powerful as the pleasure of gaining the same thing. This explains why investors often hold onto losing stocks far too long — they're reluctant to crystallise a loss, even when selling would be the rational choice." },
        { speaker: "Lecturer", voiceId: VOICES.brian, text: "The sunk cost fallacy is closely related. This occurs when people continue investing in a failing project because of the resources already committed, rather than making decisions based on future prospects. A common example is sitting through a terrible film simply because you've paid for the ticket. The rational decision would be to leave and use your time more productively." },
        { speaker: "Lecturer", voiceId: VOICES.brian, text: "Confirmation bias is another critical area. Studies have shown that people actively seek information that confirms their existing beliefs and dismiss evidence that contradicts them. In the age of social media, this has been amplified by algorithm-driven content curation, creating what researchers call filter bubbles or echo chambers." },
        { speaker: "Lecturer", voiceId: VOICES.brian, text: "Now, what can be done about these biases? Research from the University of Pennsylvania suggests that simply being aware of biases reduces their impact by approximately thirty per cent. Organisations are increasingly using structured decision-making frameworks, checklists, and diverse teams to counteract individual biases. Some companies have even appointed chief decision scientists to oversee important strategic choices." },
      ],
      questions: [
        { number: 31, type: "mcq", text: "When did Daniel Kahneman win the Nobel Prize?", options: ["A 2000", "B 2002", "C 2004"], correctAnswer: "B", explanation: "Nobel Prize in Economics in two thousand and two." },
        { number: 32, type: "mcq", text: "In the anchoring experiment, what numbers appeared on the wheel?", options: ["A 10 and 50", "B 10 and 65", "C 15 and 65"], correctAnswer: "B", explanation: "A wheel that landed on either ten or sixty-five." },
        { number: 33, type: "mcq", text: "According to the lecturer, flying is approximately how many times safer than driving?", options: ["A 50 times", "B 60 times", "C 70 times"], correctAnswer: "C", explanation: "Approximately seventy times safer than driving." },
        { number: 34, type: "sentence_completion", text: "The pain of losing is approximately _______ times as powerful as the pleasure of gaining.", correctAnswer: "2", explanation: "Approximately twice as powerful." },
        { number: 35, type: "sentence_completion", text: "Algorithm-driven content curation creates _______ bubbles.", correctAnswer: "filter", explanation: "Creating what researchers call filter bubbles." },
        { number: 36, type: "sentence_completion", text: "Awareness of biases reduces their impact by about _______ per cent.", correctAnswer: "30", explanation: "Reduces their impact by approximately thirty per cent." },
        { number: 37, type: "sentence_completion", text: "The research on bias awareness came from the University of _______.", correctAnswer: "Pennsylvania", explanation: "Research from the University of Pennsylvania." },
        { number: 38, type: "summary_completion", text: "In the anchoring experiment, those who spun 10 guessed about _______ per cent.", correctAnswer: "25", explanation: "Those who spun ten guessed around twenty-five per cent." },
        { number: 39, type: "summary_completion", text: "People continue investing in failing projects due to the _______ cost fallacy.", correctAnswer: "sunk", explanation: "The sunk cost fallacy." },
        { number: 40, type: "summary_completion", text: "Some companies have appointed chief _______ scientists.", correctAnswer: "decision", explanation: "Chief decision scientists." },
      ],
    },
  ],
};
