import { ListeningTestData } from "./listening-tests-data";

const VOICES = {
  roger: "CwhRBWXzGAHq8TQ4Fs17",
  sarah: "EXAVITQu4vr4xnSDxMaL",
  george: "JBFqnCBsd6RMkjVDRZzb",
  laura: "FGY2WhTYpPnrIDTdsKH5",
  charlie: "IKne3meq5aSn9XLyUdCD",
  alice: "Xb7hH8MSUJpSbSDYk0k2",
  brian: "nPczCjzI2devNBz1zQrb",
};

export const LISTENING_TEST_5: ListeningTestData = {
  id: 5,
  title: "Listening Test 5",
  totalQuestions: 40,
  timeLimit: 40,
  sections: [
    // ─── SECTION 1: Everyday Conversation ───
    {
      sectionNumber: 1,
      title: "Childcare Centre Enrolment",
      description: "A conversation between a childcare centre administrator and a parent enrolling their child.",
      context: "You will hear a conversation between an administrator and a parent at a childcare centre. First, you have some time to look at questions 1 to 10.",
      dialogue: [
        { speaker: "Administrator", voiceId: VOICES.sarah, text: "Good morning, Sunnydale Childcare Centre. How can I help you?" },
        { speaker: "Father", voiceId: VOICES.roger, text: "Hello, I'd like to enrol my daughter. My name is Michael Crawford." },
        { speaker: "Administrator", voiceId: VOICES.sarah, text: "Of course, Mr Crawford. What's your daughter's name and date of birth?" },
        { speaker: "Father", voiceId: VOICES.roger, text: "Her name is Emily Crawford. She was born on the twenty-fifth of August, twenty twenty-two." },
        { speaker: "Administrator", voiceId: VOICES.sarah, text: "So she's three years old. Perfect, she'd be in our Explorers group. And your home address?" },
        { speaker: "Father", voiceId: VOICES.roger, text: "It's 78 Riverside Crescent, that's R-I-V-E-R-S-I-D-E Crescent. Canterbury. Postcode CT2 8PJ." },
        { speaker: "Administrator", voiceId: VOICES.sarah, text: "And a contact number for emergencies?" },
        { speaker: "Father", voiceId: VOICES.roger, text: "My mobile is 07712 583946. And my wife's number is 07856 294103." },
        { speaker: "Administrator", voiceId: VOICES.sarah, text: "Thank you. Now, we offer full-day sessions from seven thirty in the morning until six in the evening, or half-day sessions either from seven thirty to one, or from one to six. The full-day rate is fifty-five pounds per day, and half days are thirty-two pounds." },
        { speaker: "Father", voiceId: VOICES.roger, text: "We'd need full days, probably three days a week — Monday, Wednesday, and Friday." },
        { speaker: "Administrator", voiceId: VOICES.sarah, text: "That's fine. We do offer a discount for three or more days — it drops to fifty pounds per day, so that would be one hundred and fifty pounds per week. Meals are included in the price. We serve a morning snack, lunch, an afternoon snack, and an early tea." },
        { speaker: "Father", voiceId: VOICES.roger, text: "That's very reasonable. Does Emily have any allergies? Well, she's allergic to peanuts. We carry an EpiPen for her." },
        { speaker: "Administrator", voiceId: VOICES.sarah, text: "Thank you for letting us know. We're a nut-free facility, but we'll make a special note on her file. All our staff are trained in allergy management and first aid. We have a qualified nurse on-site from nine until three every day." },
        { speaker: "Father", voiceId: VOICES.roger, text: "That's reassuring. When could she start?" },
        { speaker: "Administrator", voiceId: VOICES.sarah, text: "We have spaces available from the first of next month. We'd suggest a settling-in period of three days where you can stay with her for the first hour each morning. There's no charge for the settling-in days." },
      ],
      questions: [
        { number: 1, type: "fill_blank", text: "Child's full name:", correctAnswer: "Emily Crawford", explanation: "Her name is Emily Crawford." },
        { number: 2, type: "fill_blank", text: "Child's date of birth:", correctAnswer: "25 August 2022", explanation: "Born on the twenty-fifth of August, twenty twenty-two." },
        { number: 3, type: "fill_blank", text: "Address: 78 _______ Crescent", correctAnswer: "Riverside", explanation: "78 Riverside Crescent." },
        { number: 4, type: "fill_blank", text: "Postcode:", correctAnswer: "CT2 8PJ", explanation: "CT2 8PJ." },
        { number: 5, type: "fill_blank", text: "Father's mobile:", correctAnswer: "07712 583946", explanation: "07712 583946." },
        { number: 6, type: "short_answer", text: "What is the full-day discounted rate per day?", correctAnswer: "50", explanation: "Drops to fifty pounds per day." },
        { number: 7, type: "short_answer", text: "What allergy does Emily have?", correctAnswer: "peanuts", explanation: "She's allergic to peanuts." },
        { number: 8, type: "short_answer", text: "How many settling-in days are offered?", correctAnswer: "3", explanation: "A settling-in period of three days." },
        { number: 9, type: "mcq", text: "Which group will Emily be in?", options: ["A Discoverers", "B Explorers", "C Adventurers"], correctAnswer: "B", explanation: "She'd be in the Explorers group." },
        { number: 10, type: "mcq", text: "Which days does the father want?", options: ["A Mon, Tue, Wed", "B Mon, Wed, Fri", "C Tue, Thu, Fri"], correctAnswer: "B", explanation: "Monday, Wednesday, and Friday." },
      ],
    },

    // ─── SECTION 2: Informative Monologue ───
    {
      sectionNumber: 2,
      title: "National Park Visitor Information",
      description: "A park ranger giving information to visitors at the entrance of a national park.",
      context: "You will hear a park ranger giving information to visitors. First, you have some time to look at questions 11 to 20.",
      dialogue: [
        { speaker: "Ranger", voiceId: VOICES.george, text: "Good morning, and welcome to Lakeland National Park. I'm Ranger Williams, and before you head out onto the trails, I'd like to give you some important information about the park and its facilities." },
        { speaker: "Ranger", voiceId: VOICES.george, text: "Lakeland National Park covers an area of approximately twenty-three hundred square kilometres, making it one of the largest national parks in the country. It was established in nineteen fifty-one and receives approximately sixteen million visitors per year." },
        { speaker: "Ranger", voiceId: VOICES.george, text: "We have five main walking trails of varying difficulty. Trail one, the Lakeside Path, is our easiest route at three point five kilometres. It's suitable for wheelchairs and pushchairs and takes about forty-five minutes. Trail two, the Woodland Circuit, is seven kilometres and takes approximately two hours. This is a moderate walk through ancient oak woodland." },
        { speaker: "Ranger", voiceId: VOICES.george, text: "Trail three, the Ridge Walk, is twelve kilometres and is graded as challenging. Allow four to five hours for this route. You'll climb to an altitude of about eight hundred and fifty metres, so please ensure you have appropriate footwear, waterproof clothing, and plenty of water. Trail four is our most demanding route — the Summit Trek at nineteen kilometres. This should only be attempted by experienced hikers and requires a full day." },
        { speaker: "Ranger", voiceId: VOICES.george, text: "Trail five is a new nature photography trail we opened last spring. It's eight kilometres long and takes about three hours. It passes through three different habitats — wetland, woodland, and alpine meadow — and we've installed twenty-four observation points with information boards about the wildlife you might see." },
        { speaker: "Ranger", voiceId: VOICES.george, text: "In terms of wildlife, the park is home to over two hundred and thirty bird species, including golden eagles, peregrine falcons, and red kites. We also have a population of about three hundred red deer, which are best viewed in the early morning or late afternoon. Last year, we successfully reintroduced beavers to the park — we now have seven family groups along the river." },
        { speaker: "Ranger", voiceId: VOICES.george, text: "For facilities, the visitor centre here has a café open from eight thirty to five, toilets, and a well-stocked shop selling maps, guides, and outdoor equipment. There are also picnic areas at the start of trails one, two, and five, and wild camping is permitted above the four hundred and fifty metre line, but please register at the visitor centre first." },
        { speaker: "Ranger", voiceId: VOICES.george, text: "One final safety note — mobile phone reception is unreliable above six hundred metres, so please inform someone of your planned route before setting out. Emergency mountain rescue can be reached by calling nine nine nine and asking for mountain rescue." },
      ],
      questions: [
        { number: 11, type: "mcq", text: "How large is Lakeland National Park?", options: ["A 1,800 sq km", "B 2,300 sq km", "C 2,800 sq km"], correctAnswer: "B", explanation: "Approximately twenty-three hundred square kilometres." },
        { number: 12, type: "mcq", text: "When was the park established?", options: ["A 1949", "B 1951", "C 1955"], correctAnswer: "B", explanation: "Established in nineteen fifty-one." },
        { number: 13, type: "mcq", text: "How many observation points are on Trail 5?", options: ["A 18", "B 21", "C 24"], correctAnswer: "C", explanation: "Twenty-four observation points." },
        { number: 14, type: "mcq", text: "How many beaver family groups are in the park?", options: ["A 5", "B 7", "C 9"], correctAnswer: "B", explanation: "Seven family groups." },
        { number: 15, type: "sentence_completion", text: "The park receives approximately _______ million visitors annually.", correctAnswer: "16", explanation: "Approximately sixteen million visitors." },
        { number: 16, type: "sentence_completion", text: "Trail 3 climbs to approximately _______ metres altitude.", correctAnswer: "850", explanation: "About eight hundred and fifty metres." },
        { number: 17, type: "sentence_completion", text: "The park has over _______ bird species.", correctAnswer: "230", explanation: "Over two hundred and thirty bird species." },
        { number: 18, type: "map_labeling", text: "The easiest trail (Trail 1) is:", options: ["A 3.5 km", "B 7 km", "C 8 km", "D 12 km"], correctAnswer: "A", explanation: "Three point five kilometres." },
        { number: 19, type: "map_labeling", text: "The most demanding trail (Trail 4) is:", options: ["A 12 km", "B 15 km", "C 19 km", "D 24 km"], correctAnswer: "C", explanation: "Nineteen kilometres." },
        { number: 20, type: "map_labeling", text: "Wild camping is permitted above:", options: ["A 350 metres", "B 400 metres", "C 450 metres", "D 500 metres"], correctAnswer: "C", explanation: "Above the four hundred and fifty metre line." },
      ],
    },

    // ─── SECTION 3: Academic Discussion ───
    {
      sectionNumber: 3,
      title: "Public Health Campaign Evaluation",
      description: "Three public health students reviewing a campaign to promote healthy eating in schools.",
      context: "You will hear three students discussing their evaluation of a public health campaign. First, you have some time to look at questions 21 to 30.",
      dialogue: [
        { speaker: "Dr Khan", voiceId: VOICES.brian, text: "Right, let's discuss your evaluation of the Healthy Schools programme. This campaign ran in twenty-five primary schools across three local authorities over the past academic year. Hannah, could you start with an overview of the results?" },
        { speaker: "Hannah", voiceId: VOICES.laura, text: "Yes, Dr Khan. Overall, the results have been very encouraging. Fruit and vegetable consumption among participating children increased by an average of twenty-seven per cent. Perhaps more significantly, the proportion of children choosing a school-provided lunch instead of packed lunches rose from forty-three per cent to sixty-one per cent." },
        { speaker: "Ben", voiceId: VOICES.charlie, text: "I focused on the physical activity component. Schools that participated introduced a minimum of thirty minutes of additional daily exercise beyond normal PE lessons. We measured BMI — body mass index — at the start and end of the programme, and found an average reduction of zero point four points across all age groups." },
        { speaker: "Dr Khan", voiceId: VOICES.brian, text: "That's a meaningful change. What about the educational component, Rachel?" },
        { speaker: "Rachel", voiceId: VOICES.alice, text: "The nutrition education workshops were held weekly and were designed around practical cooking skills. Children learned to prepare eight different healthy meals during the year. Teacher feedback was overwhelmingly positive — ninety-two per cent rated the programme as good or excellent. The most popular sessions were the ones where children got to design their own recipes." },
        { speaker: "Hannah", voiceId: VOICES.laura, text: "One interesting finding was the knock-on effect on families. We surveyed parents at the end of the programme, and sixty-eight per cent reported that their children's eating habits had improved at home as well. Thirty-five per cent of families said they were cooking from scratch more often." },
        { speaker: "Ben", voiceId: VOICES.charlie, text: "There were challenges, though. The main one was cost. The programme cost approximately eighteen thousand pounds per school for the year. Some schools found it difficult to allocate time in an already crowded curriculum. And three schools dropped out during the year due to staffing issues." },
        { speaker: "Rachel", voiceId: VOICES.alice, text: "The other significant challenge was the variation between schools. Schools in more deprived areas showed greater improvements — up to thirty-five per cent increase in fruit and vegetable consumption — compared to about fifteen per cent in more affluent areas. This suggests the programme has the most impact where it's most needed." },
        { speaker: "Dr Khan", voiceId: VOICES.brian, text: "Excellent analysis. What are your recommendations for the future?" },
        { speaker: "Hannah", voiceId: VOICES.laura, text: "We're recommending that the programme be extended to secondary schools, with modified content for older students. We also suggest a three-year commitment rather than one year, as behaviour change research shows that sustained intervention over thirty-six months leads to permanent habit formation in about seventy per cent of participants." },
      ],
      questions: [
        { number: 21, type: "matching", text: "Hannah evaluated:", matchOptions: ["A Physical activity component", "B Nutrition and diet changes", "C Education workshops", "D Cost analysis"], correctAnswer: "B", explanation: "Hannah reported on fruit, vegetable consumption and lunch choices." },
        { number: 22, type: "matching", text: "Ben evaluated:", matchOptions: ["A Physical activity component", "B Nutrition outcomes", "C Education workshops", "D Parent surveys"], correctAnswer: "A", explanation: "Ben focused on the physical activity component." },
        { number: 23, type: "matching", text: "Rachel evaluated:", matchOptions: ["A Physical activity", "B Diet changes", "C Education workshops", "D Cost analysis"], correctAnswer: "C", explanation: "Rachel covered the nutrition education workshops." },
        { number: 24, type: "matching", text: "How many schools participated?", matchOptions: ["A 20", "B 25", "C 30", "D 35"], correctAnswer: "B", explanation: "Twenty-five primary schools." },
        { number: 25, type: "fill_blank", text: "Fruit and vegetable consumption increased by _______ per cent.", correctAnswer: "27", explanation: "Increased by an average of twenty-seven per cent." },
        { number: 26, type: "fill_blank", text: "Children choosing school lunches rose from 43% to _______ per cent.", correctAnswer: "61", explanation: "Rose to sixty-one per cent." },
        { number: 27, type: "fill_blank", text: "The programme cost approximately £_______ per school.", correctAnswer: "18000", explanation: "Approximately eighteen thousand pounds per school." },
        { number: 28, type: "mcq", text: "What percentage of teachers rated the programme positively?", options: ["A 82%", "B 88%", "C 92%"], correctAnswer: "C", explanation: "Ninety-two per cent rated it good or excellent." },
        { number: 29, type: "mcq", text: "How many schools dropped out during the year?", options: ["A 2", "B 3", "C 5"], correctAnswer: "B", explanation: "Three schools dropped out." },
        { number: 30, type: "mcq", text: "Sustained intervention should last how many months for permanent change?", options: ["A 24 months", "B 30 months", "C 36 months"], correctAnswer: "C", explanation: "Thirty-six months for permanent habit formation." },
      ],
    },

    // ─── SECTION 4: Academic Lecture ───
    {
      sectionNumber: 4,
      title: "Artificial Intelligence in Healthcare",
      description: "A university lecture on how artificial intelligence is transforming medical diagnosis and treatment.",
      context: "You will hear a lecture about AI in healthcare. First, you have some time to look at questions 31 to 40.",
      dialogue: [
        { speaker: "Lecturer", voiceId: VOICES.brian, text: "Good morning. Today we're examining one of the most exciting and rapidly evolving applications of artificial intelligence — its use in healthcare. The global AI in healthcare market was valued at approximately fifteen billion dollars in twenty twenty-three and is projected to exceed one hundred and eighty billion by twenty thirty, representing extraordinary growth." },
        { speaker: "Lecturer", voiceId: VOICES.brian, text: "One of the most advanced applications is in medical imaging. AI systems can now analyse X-rays, MRI scans, and CT scans with remarkable accuracy. A landmark study published in Nature in twenty twenty showed that Google's DeepMind AI could detect breast cancer from mammograms with a false positive rate five point seven per cent lower than human radiologists, while also reducing false negatives by nine point four per cent." },
        { speaker: "Lecturer", voiceId: VOICES.brian, text: "In dermatology, AI has shown particularly impressive results. Stanford University developed a system in twenty seventeen that could identify skin cancer from photographs with the same accuracy as board-certified dermatologists. The system was trained on approximately one hundred and thirty thousand clinical images representing over two thousand different diseases." },
        { speaker: "Lecturer", voiceId: VOICES.brian, text: "Drug discovery is another area being revolutionised by AI. Traditional drug development takes an average of twelve years from initial research to market approval, at an average cost of approximately two point six billion dollars. AI can dramatically accelerate this process. In twenty twenty, a company called Insilico Medicine used AI to identify a potential drug target and design a molecule in just forty-six days — a process that would traditionally take four to five years." },
        { speaker: "Lecturer", voiceId: VOICES.brian, text: "AI is also transforming patient monitoring. Wearable devices equipped with AI algorithms can continuously monitor vital signs and detect abnormalities. The Apple Watch, for example, has been shown to detect atrial fibrillation — an irregular heart rhythm — with a sensitivity of approximately ninety-eight per cent. Early detection of this condition is crucial because atrial fibrillation increases the risk of stroke by approximately five times." },
        { speaker: "Lecturer", voiceId: VOICES.brian, text: "However, there are significant challenges. The most prominent is the issue of bias in AI systems. If an AI model is trained predominantly on data from one demographic group, it may perform poorly for others. A study at MIT found that a widely used commercial AI system for analysing skin conditions had an error rate of thirty-four per cent for dark-skinned patients, compared to just twelve per cent for light-skinned patients." },
        { speaker: "Lecturer", voiceId: VOICES.brian, text: "Privacy and data security represent another major concern. Healthcare data is among the most sensitive personal information, and any AI system requires vast amounts of patient data for training. The European Union's General Data Protection Regulation, or GDPR, and similar legislation worldwide have created strict frameworks for data usage. Many researchers argue that federated learning — where AI models are trained across multiple institutions without sharing raw data — offers the most promising solution to this challenge." },
      ],
      questions: [
        { number: 31, type: "mcq", text: "What is the projected AI healthcare market value by 2030?", options: ["A Over $120 billion", "B Over $150 billion", "C Over $180 billion"], correctAnswer: "C", explanation: "Projected to exceed one hundred and eighty billion." },
        { number: 32, type: "mcq", text: "By how much did DeepMind reduce false positive rates?", options: ["A 3.7%", "B 5.7%", "C 7.7%"], correctAnswer: "B", explanation: "Five point seven per cent lower." },
        { number: 33, type: "mcq", text: "How long does traditional drug development take on average?", options: ["A 8 years", "B 10 years", "C 12 years"], correctAnswer: "C", explanation: "An average of twelve years." },
        { number: 34, type: "sentence_completion", text: "Stanford's skin cancer AI was trained on _______ thousand clinical images.", correctAnswer: "130", explanation: "Approximately one hundred and thirty thousand." },
        { number: 35, type: "sentence_completion", text: "Insilico Medicine designed a drug molecule in _______ days using AI.", correctAnswer: "46", explanation: "Just forty-six days." },
        { number: 36, type: "sentence_completion", text: "Apple Watch detects atrial fibrillation with _______ per cent sensitivity.", correctAnswer: "98", explanation: "Approximately ninety-eight per cent." },
        { number: 37, type: "sentence_completion", text: "Atrial fibrillation increases stroke risk by approximately _______ times.", correctAnswer: "5", explanation: "Approximately five times." },
        { number: 38, type: "summary_completion", text: "AI error rate for dark-skinned patients was _______ per cent.", correctAnswer: "34", explanation: "Thirty-four per cent for dark-skinned patients." },
        { number: 39, type: "summary_completion", text: "Traditional drug development costs approximately $_______ billion.", correctAnswer: "2.6", explanation: "Approximately two point six billion dollars." },
        { number: 40, type: "summary_completion", text: "_______ learning trains AI across institutions without sharing raw data.", correctAnswer: "federated", explanation: "Federated learning." },
      ],
    },
  ],
};
