import { ListeningTestData } from "./listening-tests-data";

const VOICES = {
  roger: "CwhRBWXzGAHq8TQ4Fs17",
  sarah: "EXAVITQu4vr4xnSDxMaL",
  george: "JBFqnCBsd6RMkjVDRZzb",
  laura: "FGY2WhTYpPnrIDTdsKH5",
  charlie: "IKne3meq5aSn9XLyUdCD",
  alice: "Xb7hH8MSUJpSbSDYk0k2",
  brian: "nPczCjzI2devNBz1zQrb",
};

export const LISTENING_TEST_4: ListeningTestData = {
  id: 4,
  title: "Listening Test 4",
  totalQuestions: 40,
  timeLimit: 40,
  sections: [
    // ─── SECTION 1: Everyday Conversation ───
    {
      sectionNumber: 1,
      title: "Car Insurance Enquiry",
      description: "A conversation between an insurance agent and a customer arranging car insurance.",
      context: "You will hear a conversation between an insurance agent and a man who wants to arrange car insurance. First, you have some time to look at questions 1 to 10.",
      dialogue: [
        { speaker: "Agent", voiceId: VOICES.sarah, text: "Good morning, Brightside Insurance. My name is Helen. How can I help you today?" },
        { speaker: "Man", voiceId: VOICES.roger, text: "Hello, I've just bought a new car and I need to arrange insurance. My name is David Thompson." },
        { speaker: "Agent", voiceId: VOICES.sarah, text: "Certainly, Mr Thompson. Let me take some details. What's your date of birth?" },
        { speaker: "Man", voiceId: VOICES.roger, text: "It's the nineteenth of July, nineteen eighty-five." },
        { speaker: "Agent", voiceId: VOICES.sarah, text: "And your address?" },
        { speaker: "Man", voiceId: VOICES.roger, text: "It's 156 Oakfield Road, that's O-A-K-F-I-E-L-D. Bristol. The postcode is BS8 4QN." },
        { speaker: "Agent", voiceId: VOICES.sarah, text: "Thank you. Now, can you tell me about the vehicle? What make and model is it?" },
        { speaker: "Man", voiceId: VOICES.roger, text: "It's a Toyota Corolla, the twenty twenty-four model. I bought it brand new from the dealership last week." },
        { speaker: "Agent", voiceId: VOICES.sarah, text: "And the registration number?" },
        { speaker: "Man", voiceId: VOICES.roger, text: "It's LK24 DFH." },
        { speaker: "Agent", voiceId: VOICES.sarah, text: "How many years have you been driving?" },
        { speaker: "Man", voiceId: VOICES.roger, text: "Fourteen years. I passed my test in twenty ten. And I've had no accidents or claims in the last eight years." },
        { speaker: "Agent", voiceId: VOICES.sarah, text: "Excellent, that gives you a significant no-claims discount. We have three levels of cover. Third-party only at twenty-two pounds per month, third-party fire and theft at thirty-one pounds, and fully comprehensive at forty-seven pounds per month. Given it's a new car, I'd recommend the comprehensive cover." },
        { speaker: "Man", voiceId: VOICES.roger, text: "Yes, I think comprehensive would be best. What does the excess look like?" },
        { speaker: "Agent", voiceId: VOICES.sarah, text: "The standard excess is three hundred and fifty pounds, but you can reduce your monthly premium by choosing a voluntary excess of five hundred pounds, which would bring the monthly payment down to thirty-nine pounds." },
        { speaker: "Man", voiceId: VOICES.roger, text: "I'll go with the higher excess, please. The lower monthly cost is better for me. And is breakdown cover included?" },
        { speaker: "Agent", voiceId: VOICES.sarah, text: "No, that's an optional extra at six pounds ninety-nine per month. It covers roadside assistance, home start, and national recovery. I'd recommend it, especially for longer journeys." },
        { speaker: "Man", voiceId: VOICES.roger, text: "Yes, add that on, please." },
      ],
      questions: [
        { number: 1, type: "fill_blank", text: "Customer's full name:", correctAnswer: "David Thompson", explanation: "He says his name is David Thompson." },
        { number: 2, type: "fill_blank", text: "Date of birth:", correctAnswer: "19 July 1985", explanation: "Nineteenth of July, nineteen eighty-five." },
        { number: 3, type: "fill_blank", text: "Address: 156 _______ Road", correctAnswer: "Oakfield", explanation: "156 Oakfield Road." },
        { number: 4, type: "fill_blank", text: "Postcode:", correctAnswer: "BS8 4QN", explanation: "The postcode is BS8 4QN." },
        { number: 5, type: "fill_blank", text: "Car registration:", correctAnswer: "LK24 DFH", explanation: "Registration is LK24 DFH." },
        { number: 6, type: "short_answer", text: "How many years has the customer been driving?", correctAnswer: "14", explanation: "Fourteen years." },
        { number: 7, type: "short_answer", text: "How many years since his last insurance claim?", correctAnswer: "8", explanation: "No claims in the last eight years." },
        { number: 8, type: "short_answer", text: "What is the cost of breakdown cover per month?", correctAnswer: "6.99", explanation: "Six pounds ninety-nine per month." },
        { number: 9, type: "mcq", text: "Which insurance level does the customer choose?", options: ["A Third-party only", "B Third-party fire and theft", "C Fully comprehensive"], correctAnswer: "C", explanation: "Comprehensive would be best." },
        { number: 10, type: "mcq", text: "What voluntary excess does the customer choose?", options: ["A £350", "B £500", "C £750"], correctAnswer: "B", explanation: "Voluntary excess of five hundred pounds." },
      ],
    },

    // ─── SECTION 2: Informative Monologue ───
    {
      sectionNumber: 2,
      title: "Community Centre Facilities and Events",
      description: "A community centre manager giving information to new residents about available facilities.",
      context: "You will hear a community centre manager talking about the centre's facilities and activities. First, you have some time to look at questions 11 to 20.",
      dialogue: [
        { speaker: "Manager", voiceId: VOICES.george, text: "Hello, everyone, and welcome to the Westfield Community Centre open day. I'm Mark Richardson, the centre manager, and I'd like to tell you about what we offer here." },
        { speaker: "Manager", voiceId: VOICES.george, text: "The centre was built in two thousand and five and has been serving the local community for nearly twenty years. We had a major extension added in twenty eighteen, which cost one point eight million pounds and doubled our floor space to about three thousand square metres." },
        { speaker: "Manager", voiceId: VOICES.george, text: "On the ground floor, we have our main hall, which can seat up to two hundred and fifty people for events. This is also where we hold our weekly film screenings every Friday evening. Films start at seven thirty, and admission is just three pounds fifty per person. We also have a fully equipped kitchen available for hire." },
        { speaker: "Manager", voiceId: VOICES.george, text: "Moving through to the left wing, you'll find the children's area, which includes an indoor soft play zone for children under five, and a homework club that runs every weekday from three thirty to five thirty. The homework club is staffed by qualified teaching assistants and is completely free of charge." },
        { speaker: "Manager", voiceId: VOICES.george, text: "On the first floor, we have four meeting rooms of various sizes, which can be hired by local businesses and community groups. The largest room holds sixty people and costs twenty-five pounds per hour. We also have a computer suite with twenty workstations, offering free internet access and basic IT training courses on Wednesday mornings." },
        { speaker: "Manager", voiceId: VOICES.george, text: "For our older residents, we run a popular lunch club every Tuesday. A two-course meal costs just four pounds fifty, and we provide a free minibus service from six pickup points around the local area. Last month, we served over one hundred and forty meals at the Tuesday club." },
        { speaker: "Manager", voiceId: VOICES.george, text: "In terms of regular activities, we offer art classes on Monday afternoons, a gardening club that meets the first Saturday of each month, a mother and toddler group on Thursday mornings, and a book club on the second Wednesday of every month. There's also a men's shed workshop in the garden area, open three days a week." },
        { speaker: "Manager", voiceId: VOICES.george, text: "We're also very proud of our environmental initiatives. We installed seventy-two solar panels on the roof last year, which now provide about forty per cent of the building's electricity. We have a community vegetable garden behind the building that's maintained by volunteers, and all our catering uses locally sourced ingredients where possible." },
      ],
      questions: [
        { number: 11, type: "mcq", text: "When was the community centre originally built?", options: ["A 2003", "B 2005", "C 2008"], correctAnswer: "B", explanation: "Built in two thousand and five." },
        { number: 12, type: "mcq", text: "How much did the extension cost?", options: ["A £1.2 million", "B £1.5 million", "C £1.8 million"], correctAnswer: "C", explanation: "One point eight million pounds." },
        { number: 13, type: "mcq", text: "How much does the Friday film screening cost per person?", options: ["A £2.50", "B £3.50", "C £4.50"], correctAnswer: "B", explanation: "Three pounds fifty per person." },
        { number: 14, type: "mcq", text: "How many solar panels were installed?", options: ["A 52", "B 62", "C 72"], correctAnswer: "C", explanation: "Seventy-two solar panels." },
        { number: 15, type: "sentence_completion", text: "The main hall can seat up to _______ people.", correctAnswer: "250", explanation: "Up to two hundred and fifty people." },
        { number: 16, type: "sentence_completion", text: "The centre's floor space is about _______ square metres.", correctAnswer: "3000", explanation: "About three thousand square metres." },
        { number: 17, type: "sentence_completion", text: "Last month, the Tuesday lunch club served _______ meals.", correctAnswer: "140", explanation: "Over one hundred and forty meals." },
        { number: 18, type: "map_labeling", text: "The children's area is in the:", options: ["A Right wing", "B Left wing", "C First floor", "D Garden area"], correctAnswer: "B", explanation: "Moving through to the left wing." },
        { number: 19, type: "map_labeling", text: "The computer suite is on the:", options: ["A Ground floor", "B First floor", "C Garden area", "D Basement"], correctAnswer: "B", explanation: "On the first floor." },
        { number: 20, type: "map_labeling", text: "The men's shed workshop is in the:", options: ["A Left wing", "B Right wing", "C First floor", "D Garden area"], correctAnswer: "D", explanation: "A men's shed workshop in the garden area." },
      ],
    },

    // ─── SECTION 3: Academic Discussion ───
    {
      sectionNumber: 3,
      title: "Architecture and Sustainable Design",
      description: "Two architecture students discussing their final-year project on sustainable building design.",
      context: "You will hear two architecture students and their professor discussing a project. First, you have some time to look at questions 21 to 30.",
      dialogue: [
        { speaker: "Professor", voiceId: VOICES.brian, text: "Right, Sophie and Marcus, I'd like to hear about your progress on the sustainable housing project. You're designing an eco-friendly residential complex, correct?" },
        { speaker: "Sophie", voiceId: VOICES.laura, text: "Yes, Professor Chen. We've designed a forty-unit residential complex using passive house standards. The key principle is to minimise energy consumption through excellent insulation, airtight construction, and heat recovery ventilation." },
        { speaker: "Marcus", voiceId: VOICES.charlie, text: "We've been particularly focused on the materials. Our plan uses cross-laminated timber for the main structure instead of concrete. Timber construction produces approximately seventy-five per cent less carbon emissions during manufacturing compared to concrete. It's also lighter, which means we can build on sites with weaker ground conditions." },
        { speaker: "Professor", voiceId: VOICES.brian, text: "That's an excellent choice. What about energy generation on-site?" },
        { speaker: "Sophie", voiceId: VOICES.laura, text: "Each unit will have solar panels on the roof generating about four kilowatts of power. We've also incorporated a shared ground-source heat pump system, which will provide heating and hot water. The combined effect means the buildings should achieve near-zero energy consumption — potentially saving residents around one thousand two hundred pounds per year in energy bills." },
        { speaker: "Marcus", voiceId: VOICES.charlie, text: "We've also designed a rainwater harvesting system that collects water from the roofs and stores it in underground tanks with a total capacity of fifty thousand litres. This water would be used for toilet flushing, garden irrigation, and car washing, reducing mains water consumption by about thirty per cent." },
        { speaker: "Professor", voiceId: VOICES.brian, text: "Very thorough. What about the communal spaces?" },
        { speaker: "Sophie", voiceId: VOICES.laura, text: "We've included a shared community garden of about eight hundred square metres, a bicycle storage facility with spaces for one hundred and twenty bikes, and a car-sharing hub with six electric vehicles. The aim is to reduce car ownership — our target is to have no more than zero point five cars per household." },
        { speaker: "Marcus", voiceId: VOICES.charlie, text: "We also looked at biodiversity. The green roofs will be planted with native wildflower species to support pollinators. We're including bat boxes and swift nesting bricks in the design, and there'll be a wildlife corridor connecting the site to the local park, which is about three hundred metres away." },
        { speaker: "Professor", voiceId: VOICES.brian, text: "I'm impressed with the breadth of your thinking. Have you done a cost analysis? Sustainable buildings are often perceived as more expensive." },
        { speaker: "Marcus", voiceId: VOICES.charlie, text: "Yes, our analysis shows the construction cost is about fifteen per cent higher than conventional building. However, when you factor in the reduced running costs over twenty-five years, residents would actually save approximately twenty thousand pounds over that period." },
      ],
      questions: [
        { number: 21, type: "matching", text: "Sophie's main focus area:", matchOptions: ["A Building materials", "B Energy systems and passive design", "C Biodiversity features", "D Cost analysis"], correctAnswer: "B", explanation: "Sophie focused on passive house standards and energy generation." },
        { number: 22, type: "matching", text: "Marcus's main focus area:", matchOptions: ["A Energy generation", "B Community spaces", "C Materials and biodiversity", "D Water systems"], correctAnswer: "C", explanation: "Marcus focused on materials (timber) and biodiversity." },
        { number: 23, type: "matching", text: "Timber produces how much less carbon than concrete?", matchOptions: ["A 50% less", "B 65% less", "C 75% less", "D 85% less"], correctAnswer: "C", explanation: "Approximately seventy-five per cent less." },
        { number: 24, type: "matching", text: "The residential complex contains how many units?", matchOptions: ["A 30 units", "B 40 units", "C 50 units", "D 60 units"], correctAnswer: "B", explanation: "A forty-unit residential complex." },
        { number: 25, type: "fill_blank", text: "Each unit's solar panels generate about _______ kilowatts.", correctAnswer: "4", explanation: "About four kilowatts of power." },
        { number: 26, type: "fill_blank", text: "Rainwater storage capacity: _______ litres.", correctAnswer: "50000", explanation: "Total capacity of fifty thousand litres." },
        { number: 27, type: "fill_blank", text: "Bicycle storage has spaces for _______ bikes.", correctAnswer: "120", explanation: "Spaces for one hundred and twenty bikes." },
        { number: 28, type: "mcq", text: "How much can residents save per year on energy?", options: ["A About £800", "B About £1,200", "C About £1,600"], correctAnswer: "B", explanation: "About one thousand two hundred pounds per year." },
        { number: 29, type: "mcq", text: "How much higher is sustainable construction cost?", options: ["A About 10%", "B About 15%", "C About 20%"], correctAnswer: "B", explanation: "About fifteen per cent higher." },
        { number: 30, type: "mcq", text: "The community garden is approximately how large?", options: ["A 500 sq metres", "B 800 sq metres", "C 1,000 sq metres"], correctAnswer: "B", explanation: "About eight hundred square metres." },
      ],
    },

    // ─── SECTION 4: Academic Lecture ───
    {
      sectionNumber: 4,
      title: "The Evolution of Written Language",
      description: "A university lecture on the development of writing systems throughout human history.",
      context: "You will hear a lecture about the evolution of written language. First, you have some time to look at questions 31 to 40.",
      dialogue: [
        { speaker: "Lecturer", voiceId: VOICES.brian, text: "Good afternoon. Today I want to take you on a journey through the evolution of written language — one of humanity's greatest achievements. Writing emerged independently in at least four locations around the world, and each system tells us something profound about the societies that created it." },
        { speaker: "Lecturer", voiceId: VOICES.brian, text: "The earliest known writing system is Sumerian cuneiform, which developed in Mesopotamia around thirty-four hundred BCE. Initially, it was used purely for accounting — recording quantities of goods like grain and livestock. The earliest tablets, found at the ancient city of Uruk in modern-day Iraq, contain lists of commodities and their quantities. It wasn't until about twenty-six hundred BCE that cuneiform began to be used for literature and historical records." },
        { speaker: "Lecturer", voiceId: VOICES.brian, text: "Egyptian hieroglyphics emerged independently around thirty-two hundred BCE. Unlike cuneiform, hieroglyphics served a primarily ceremonial and religious function from the very beginning. The system used approximately seven hundred symbols in the classical period, though this number eventually grew to over five thousand by the Ptolemaic period." },
        { speaker: "Lecturer", voiceId: VOICES.brian, text: "The Chinese writing system, which developed around twelve hundred BCE during the Shang dynasty, is the oldest writing system still in use today. Modern Chinese uses approximately three thousand characters for everyday communication, though educated adults typically know between six and eight thousand characters. A comprehensive Chinese dictionary may contain over fifty thousand entries." },
        { speaker: "Lecturer", voiceId: VOICES.brian, text: "The development of alphabetic writing was revolutionary. The first true alphabet is generally attributed to the Phoenicians, around ten fifty BCE. Their alphabet contained just twenty-two letters, all consonants. The Greeks later adapted this system, around eight hundred BCE, crucially adding vowels for the first time. Our modern English alphabet of twenty-six letters is a direct descendant of this Greek innovation." },
        { speaker: "Lecturer", voiceId: VOICES.brian, text: "The invention of the printing press by Johannes Gutenberg around fourteen forty was perhaps the single most important development in the history of writing. Before the printing press, books had to be copied by hand, and a single book could cost the equivalent of a year's wages. By fifteen hundred, just sixty years after Gutenberg's invention, there were an estimated twenty million printed volumes in Europe." },
        { speaker: "Lecturer", voiceId: VOICES.brian, text: "Today, we're arguably experiencing a transformation of similar magnitude with digital communication. The average person now writes approximately five times more words per day than they did twenty years ago, largely through emails, text messages, and social media. Some linguists worry that this is degrading language quality, but others argue it represents a natural and healthy evolution of how we communicate." },
      ],
      questions: [
        { number: 31, type: "mcq", text: "When did Sumerian cuneiform first develop?", options: ["A Around 3800 BCE", "B Around 3400 BCE", "C Around 3000 BCE"], correctAnswer: "B", explanation: "Around thirty-four hundred BCE." },
        { number: 32, type: "mcq", text: "Where were the earliest cuneiform tablets found?", options: ["A Babylon", "B Uruk", "C Nineveh"], correctAnswer: "B", explanation: "Found at the ancient city of Uruk." },
        { number: 33, type: "mcq", text: "How many letters were in the Phoenician alphabet?", options: ["A 20", "B 22", "C 24"], correctAnswer: "B", explanation: "Twenty-two letters, all consonants." },
        { number: 34, type: "sentence_completion", text: "Egyptian hieroglyphics used about _______ symbols in the classical period.", correctAnswer: "700", explanation: "Approximately seven hundred symbols." },
        { number: 35, type: "sentence_completion", text: "Modern Chinese uses approximately _______ characters for everyday communication.", correctAnswer: "3000", explanation: "Approximately three thousand characters." },
        { number: 36, type: "sentence_completion", text: "Gutenberg invented the printing press around the year _______.", correctAnswer: "1440", explanation: "Around fourteen forty." },
        { number: 37, type: "sentence_completion", text: "By 1500, Europe had an estimated _______ million printed volumes.", correctAnswer: "20", explanation: "An estimated twenty million printed volumes." },
        { number: 38, type: "summary_completion", text: "The Greeks added _______ to the Phoenician alphabet.", correctAnswer: "vowels", explanation: "Crucially adding vowels for the first time." },
        { number: 39, type: "summary_completion", text: "People today write approximately _______ times more words per day than 20 years ago.", correctAnswer: "5", explanation: "Approximately five times more words per day." },
        { number: 40, type: "summary_completion", text: "The Chinese writing system developed during the _______ dynasty.", correctAnswer: "Shang", explanation: "During the Shang dynasty." },
      ],
    },
  ],
};
