import { ListeningTestData } from "./listening-tests-data";

const VOICES = {
  roger: "CwhRBWXzGAHq8TQ4Fs17",
  sarah: "EXAVITQu4vr4xnSDxMaL",
  george: "JBFqnCBsd6RMkjVDRZzb",
  laura: "FGY2WhTYpPnrIDTdsKH5",
  charlie: "IKne3meq5aSn9XLyUdCD",
  alice: "Xb7hH8MSUJpSbSDYk0k2",
  brian: "nPczCjzI2devNBz1zQrb",
};

export const LISTENING_TEST_3: ListeningTestData = {
  id: 3,
  title: "Listening Test 3",
  totalQuestions: 40,
  timeLimit: 40,
  sections: [
    // ─── SECTION 1: Everyday Conversation ───
    {
      sectionNumber: 1,
      title: "Gym Membership Registration",
      description: "A conversation between a gym receptionist and a woman signing up for membership.",
      context: "You will hear a conversation between a receptionist at a fitness centre and a woman who wants to join. First, you have some time to look at questions 1 to 10.",
      dialogue: [
        { speaker: "Receptionist", voiceId: VOICES.roger, text: "Good morning, welcome to FitLife Fitness Centre. How can I help you?" },
        { speaker: "Woman", voiceId: VOICES.sarah, text: "Hi, I'm interested in joining the gym. I've recently moved to the area and I'm looking for somewhere to exercise regularly." },
        { speaker: "Receptionist", voiceId: VOICES.roger, text: "Great, I'd be happy to help. Let me take some details first. Could I have your full name, please?" },
        { speaker: "Woman", voiceId: VOICES.sarah, text: "Yes, it's Catherine Blackwood." },
        { speaker: "Receptionist", voiceId: VOICES.roger, text: "Catherine Blackwood. And your date of birth?" },
        { speaker: "Woman", voiceId: VOICES.sarah, text: "The sixth of November, nineteen ninety-one." },
        { speaker: "Receptionist", voiceId: VOICES.roger, text: "And your address?" },
        { speaker: "Woman", voiceId: VOICES.sarah, text: "It's 23 Maple Drive, that's M-A-P-L-E Drive. The postcode is SW9 2JR." },
        { speaker: "Receptionist", voiceId: VOICES.roger, text: "And a contact number?" },
        { speaker: "Woman", voiceId: VOICES.sarah, text: "My mobile is 07923 461058." },
        { speaker: "Receptionist", voiceId: VOICES.roger, text: "Now, we have three membership options. The basic plan is twenty-nine pounds per month and gives you access to the gym floor and changing rooms only. The premium plan is forty-five pounds per month and includes all classes, the swimming pool, and the sauna. And the platinum plan at sixty-five pounds includes everything plus personal training sessions — two per month." },
        { speaker: "Woman", voiceId: VOICES.sarah, text: "I think the premium plan would suit me best. I really enjoy group fitness classes, especially yoga and spinning." },
        { speaker: "Receptionist", voiceId: VOICES.roger, text: "Excellent choice. The yoga classes run every Tuesday and Thursday evening at seven o'clock, and spinning is on Monday, Wednesday, and Friday mornings at six thirty. There's also a Saturday morning session at nine." },
        { speaker: "Woman", voiceId: VOICES.sarah, text: "The Tuesday and Thursday yoga sessions sound perfect. How long is the minimum contract?" },
        { speaker: "Receptionist", voiceId: VOICES.roger, text: "The minimum contract is three months. After that, you can cancel with thirty days' notice. We also offer a seven-day free trial if you'd like to try before committing." },
        { speaker: "Woman", voiceId: VOICES.sarah, text: "Oh, a free trial would be great. When can I start?" },
        { speaker: "Receptionist", voiceId: VOICES.roger, text: "You can start tomorrow if you like. Just bring a photo ID and some trainers. We'll provide you with a towel and a locker key." },
      ],
      questions: [
        { number: 1, type: "fill_blank", text: "Full name of the new member:", correctAnswer: "Catherine Blackwood", explanation: "She says her name is Catherine Blackwood." },
        { number: 2, type: "fill_blank", text: "Date of birth:", correctAnswer: "6 November 1991", explanation: "The sixth of November, nineteen ninety-one." },
        { number: 3, type: "fill_blank", text: "Address: 23 _______ Drive", correctAnswer: "Maple", explanation: "23 Maple Drive." },
        { number: 4, type: "fill_blank", text: "Postcode:", correctAnswer: "SW9 2JR", explanation: "The postcode is SW9 2JR." },
        { number: 5, type: "fill_blank", text: "Contact number:", correctAnswer: "07923 461058", explanation: "Mobile is 07923 461058." },
        { number: 6, type: "short_answer", text: "How much does the premium membership cost per month?", correctAnswer: "45", explanation: "Forty-five pounds per month." },
        { number: 7, type: "short_answer", text: "What time do Tuesday yoga classes start?", correctAnswer: "7", explanation: "Seven o'clock." },
        { number: 8, type: "short_answer", text: "What is the minimum contract length?", correctAnswer: "3 months", explanation: "The minimum contract is three months." },
        { number: 9, type: "mcq", text: "Which membership plan does the woman choose?", options: ["A Basic", "B Premium", "C Platinum"], correctAnswer: "B", explanation: "She says the premium plan would suit her best." },
        { number: 10, type: "mcq", text: "How long is the free trial period?", options: ["A 3 days", "B 7 days", "C 14 days"], correctAnswer: "B", explanation: "A seven-day free trial." },
      ],
    },

    // ─── SECTION 2: Informative Monologue ───
    {
      sectionNumber: 2,
      title: "City Bus Tour Information",
      description: "A tour guide giving information about a hop-on hop-off city bus tour to passengers.",
      context: "You will hear a tour guide explaining the bus tour route and key attractions. First, you have some time to look at questions 11 to 20.",
      dialogue: [
        { speaker: "Guide", voiceId: VOICES.george, text: "Good morning, everyone, and welcome aboard the Edinburgh Explorer Bus Tour. My name is Douglas, and I'll be providing commentary as we travel around some of the city's most famous landmarks. The complete circuit takes approximately ninety minutes, but of course you can hop on and hop off at any of our fifteen stops throughout the day." },
        { speaker: "Guide", voiceId: VOICES.george, text: "Your ticket is valid for twenty-four hours from the time of first use. We operate from nine in the morning until six in the evening, with buses departing every twenty minutes from each stop. During July and August, we extend our hours until eight p.m." },
        { speaker: "Guide", voiceId: VOICES.george, text: "Our first stop will be Edinburgh Castle, one of the most visited tourist attractions in Scotland. The castle sits on top of Castle Rock, which is an extinct volcanic plug estimated to be around three hundred and forty million years old. The castle itself dates back to the twelfth century, though there's evidence of human settlement on the rock going back to the second century." },
        { speaker: "Guide", voiceId: VOICES.george, text: "Stop number two is the Royal Mile, the historic main street that connects Edinburgh Castle to the Palace of Holyroodhouse. The Royal Mile is actually approximately one mile and one hundred and seven yards long. Along the way, you'll find St Giles' Cathedral, which dates from the fourteenth century." },
        { speaker: "Guide", voiceId: VOICES.george, text: "Our third stop takes us to the Scottish National Museum. Admission is free, and the museum houses over twelve million items in its collection. The most popular exhibit is Dolly the Sheep — the first mammal cloned from an adult cell, created in nineteen ninety-six at the Roslin Institute just outside Edinburgh." },
        { speaker: "Guide", voiceId: VOICES.george, text: "Stop four is Calton Hill, which offers some of the best panoramic views of the city. The climb to the top takes about ten minutes and is well worth the effort. At the summit, you'll find the National Monument, which was designed to resemble the Parthenon in Athens but was never completed due to lack of funding. It's sometimes called Edinburgh's Disgrace for this reason." },
        { speaker: "Guide", voiceId: VOICES.george, text: "If you're interested in literature, stop seven takes you to the Writers' Museum, dedicated to three of Scotland's greatest literary figures: Robert Burns, Sir Walter Scott, and Robert Louis Stevenson. It's housed in a seventeenth-century building called Lady Stair's House." },
        { speaker: "Guide", voiceId: VOICES.george, text: "Now, a few practical points. If you need to buy souvenirs, the best shopping area is around Princes Street, which is stop number nine. Public toilets are available at stops one, five, and twelve. And if you're looking for a good pub lunch, I'd particularly recommend the pubs around the Grassmarket area, which is stop number six." },
      ],
      questions: [
        { number: 11, type: "mcq", text: "How long does the complete bus circuit take?", options: ["A 60 minutes", "B 90 minutes", "C 120 minutes"], correctAnswer: "B", explanation: "Approximately ninety minutes." },
        { number: 12, type: "mcq", text: "How often do buses depart from each stop?", options: ["A Every 10 minutes", "B Every 15 minutes", "C Every 20 minutes"], correctAnswer: "C", explanation: "Buses departing every twenty minutes." },
        { number: 13, type: "mcq", text: "Castle Rock is estimated to be how old?", options: ["A 240 million years", "B 340 million years", "C 440 million years"], correctAnswer: "B", explanation: "Around three hundred and forty million years old." },
        { number: 14, type: "mcq", text: "When was Dolly the Sheep cloned?", options: ["A 1994", "B 1996", "C 1998"], correctAnswer: "B", explanation: "Created in nineteen ninety-six." },
        { number: 15, type: "sentence_completion", text: "The tour ticket is valid for _______ hours.", correctAnswer: "24", explanation: "Valid for twenty-four hours." },
        { number: 16, type: "sentence_completion", text: "The Scottish National Museum has over _______ million items.", correctAnswer: "12", explanation: "Over twelve million items." },
        { number: 17, type: "sentence_completion", text: "Climbing Calton Hill takes about _______ minutes.", correctAnswer: "10", explanation: "About ten minutes." },
        { number: 18, type: "map_labeling", text: "The best shopping area is at stop number:", options: ["A Stop 6", "B Stop 7", "C Stop 9", "D Stop 12"], correctAnswer: "C", explanation: "Around Princes Street, which is stop number nine." },
        { number: 19, type: "map_labeling", text: "Pub lunches are recommended at stop number:", options: ["A Stop 4", "B Stop 6", "C Stop 9", "D Stop 11"], correctAnswer: "B", explanation: "Grassmarket area, which is stop number six." },
        { number: 20, type: "map_labeling", text: "The Writers' Museum is at stop number:", options: ["A Stop 5", "B Stop 6", "C Stop 7", "D Stop 8"], correctAnswer: "C", explanation: "Stop seven takes you to the Writers' Museum." },
      ],
    },

    // ─── SECTION 3: Academic Discussion ───
    {
      sectionNumber: 3,
      title: "Marine Biology Field Study Planning",
      description: "Three students and their supervisor discussing plans for a marine biology field study.",
      context: "You will hear three students discussing a field study with their supervisor. First, you have some time to look at questions 21 to 30.",
      dialogue: [
        { speaker: "Dr Mitchell", voiceId: VOICES.brian, text: "Right, so let's finalise the plans for our coastal ecology field study next month. We'll be based at the Plymouth Marine Station for two weeks. Emma, have you sorted out the equipment list?" },
        { speaker: "Emma", voiceId: VOICES.laura, text: "Yes, I have. We need underwater cameras, water sampling kits, pH meters, and temperature probes. The station has most of the lab equipment we'll need, but we'll need to bring our own recording devices for the dolphin acoustic study." },
        { speaker: "Tom", voiceId: VOICES.charlie, text: "I've been in contact with the local fishermen's association. They've agreed to take us out on their boats three times during our stay, which will be really useful for the deep-water sampling. Each trip will cost us about two hundred and fifty pounds." },
        { speaker: "Dr Mitchell", voiceId: VOICES.brian, text: "That's excellent, Tom. What about the diving schedule? Sarah, you were organising that?" },
        { speaker: "Sarah", voiceId: VOICES.alice, text: "Yes, I've booked us six diving sessions. We'll dive in pairs, and each dive will last approximately forty-five minutes. The water temperature at this time of year should be around twelve degrees, so we'll need full wetsuits. I've also arranged for a safety boat to accompany us on each dive." },
        { speaker: "Dr Mitchell", voiceId: VOICES.brian, text: "Good. Now, let's talk about the research objectives. We have three main areas. First, mapping the seagrass beds along the coastline. Second, surveying the fish population diversity. And third, the dolphin behaviour study." },
        { speaker: "Emma", voiceId: VOICES.laura, text: "For the seagrass mapping, I've developed a grid system. We'll divide the study area into one hundred squares, each measuring fifty metres by fifty metres. We'll survey each square using a combination of diving observation and drone photography." },
        { speaker: "Tom", voiceId: VOICES.charlie, text: "For the fish survey, I'm planning to use a combination of visual census during our dives and underwater camera traps. Last year's study identified sixty-three species in the area. I'm expecting we might find between seventy and eighty this time because of the expanded survey area." },
        { speaker: "Sarah", voiceId: VOICES.alice, text: "The dolphin study is probably the most complex part. There's a pod of about eighteen bottlenose dolphins that regularly visits the bay. I want to record their vocalisations and correlate them with specific behaviours — feeding, socialising, travelling. We'll use hydrophones positioned at four locations around the bay." },
        { speaker: "Dr Mitchell", voiceId: VOICES.brian, text: "Sounds like you've all done excellent preparation. One more thing — we need to submit our findings to the Marine Conservation Society within eight weeks of returning. So let's make sure we keep detailed field notes throughout." },
      ],
      questions: [
        { number: 21, type: "matching", text: "Emma is responsible for:", matchOptions: ["A Fish population survey", "B Seagrass bed mapping", "C Dolphin behaviour study", "D Boat arrangements"], correctAnswer: "B", explanation: "Emma developed the grid system for seagrass mapping." },
        { number: 22, type: "matching", text: "Tom is responsible for:", matchOptions: ["A Fish population survey", "B Seagrass bed mapping", "C Dolphin behaviour study", "D Boat arrangements"], correctAnswer: "A", explanation: "Tom is planning the fish survey." },
        { number: 23, type: "matching", text: "Sarah is responsible for:", matchOptions: ["A Fish population survey", "B Seagrass bed mapping", "C Dolphin behaviour study", "D Boat arrangements"], correctAnswer: "C", explanation: "Sarah handles the dolphin study." },
        { number: 24, type: "matching", text: "The field study will be based at:", matchOptions: ["A Brighton Marine Lab", "B Plymouth Marine Station", "C Cornwall Research Centre", "D Southampton Oceanography"], correctAnswer: "B", explanation: "Based at the Plymouth Marine Station." },
        { number: 25, type: "fill_blank", text: "Each boat trip costs approximately £_______.", correctAnswer: "250", explanation: "About two hundred and fifty pounds." },
        { number: 26, type: "fill_blank", text: "Each dive will last approximately _______ minutes.", correctAnswer: "45", explanation: "Approximately forty-five minutes." },
        { number: 27, type: "fill_blank", text: "The study area is divided into _______ squares.", correctAnswer: "100", explanation: "One hundred squares." },
        { number: 28, type: "mcq", text: "How many dolphin species regularly visit the bay?", options: ["A 12 bottlenose dolphins", "B 18 bottlenose dolphins", "C 24 bottlenose dolphins"], correctAnswer: "B", explanation: "A pod of about eighteen bottlenose dolphins." },
        { number: 29, type: "mcq", text: "How many hydrophones will be used?", options: ["A 2", "B 3", "C 4"], correctAnswer: "C", explanation: "Hydrophones positioned at four locations." },
        { number: 30, type: "mcq", text: "When must findings be submitted after returning?", options: ["A Within 4 weeks", "B Within 8 weeks", "C Within 12 weeks"], correctAnswer: "B", explanation: "Within eight weeks of returning." },
      ],
    },

    // ─── SECTION 4: Academic Lecture ───
    {
      sectionNumber: 4,
      title: "The Science of Sleep",
      description: "A university lecture on sleep research, sleep stages, and the impact of sleep deprivation.",
      context: "You will hear a lecture about the science of sleep. First, you have some time to look at questions 31 to 40.",
      dialogue: [
        { speaker: "Lecturer", voiceId: VOICES.brian, text: "Good morning. Today we're going to explore one of the most fundamental aspects of human biology — sleep. Despite spending roughly a third of our lives asleep, sleep remains one of the most mysterious and misunderstood areas of neuroscience. The average adult needs between seven and nine hours of sleep per night, yet studies show that approximately thirty-five per cent of adults in the UK regularly get less than the recommended amount." },
        { speaker: "Lecturer", voiceId: VOICES.brian, text: "Sleep occurs in cycles lasting approximately ninety minutes each. A full night's sleep typically consists of four to six such cycles. Each cycle comprises several stages. The first two stages are light sleep, where body temperature drops and heart rate slows. Stage three is deep sleep, also called slow-wave sleep, which is crucial for physical restoration and immune function." },
        { speaker: "Lecturer", voiceId: VOICES.brian, text: "The fourth stage is REM sleep — Rapid Eye Movement sleep. This is when most dreaming occurs. During REM sleep, brain activity increases to levels similar to wakefulness, but the body is essentially paralysed. This paralysis is thought to prevent us from acting out our dreams. REM sleep makes up about twenty to twenty-five per cent of total sleep time in adults." },
        { speaker: "Lecturer", voiceId: VOICES.brian, text: "The role of sleep in memory consolidation has been extensively studied. Research at Harvard Medical School demonstrated that students who slept for eight hours after learning a new skill performed forty per cent better the following day than those who stayed awake. The process appears to involve the transfer of memories from the hippocampus, where they're initially stored, to the neocortex for long-term storage." },
        { speaker: "Lecturer", voiceId: VOICES.brian, text: "Sleep deprivation has alarming consequences. After just twenty-four hours without sleep, cognitive performance drops to a level equivalent to having a blood alcohol concentration of zero point one per cent — well above the legal driving limit. Chronic sleep deprivation has been linked to a forty-eight per cent increased risk of heart disease and a thirty-six per cent increased risk of colorectal cancer." },
        { speaker: "Lecturer", voiceId: VOICES.brian, text: "One of the most significant recent discoveries relates to the glymphatic system, a waste-clearance mechanism in the brain that's primarily active during sleep. This system removes toxic proteins, including beta-amyloid, which is associated with Alzheimer's disease. Studies show the glymphatic system is approximately sixty per cent more active during sleep than during wakefulness." },
        { speaker: "Lecturer", voiceId: VOICES.brian, text: "The impact of artificial light on sleep is another major area of concern. Blue light from screens suppresses the production of melatonin, the hormone that regulates our sleep-wake cycle. Research has shown that using a smartphone for just thirty minutes before bed can delay sleep onset by approximately twenty minutes. Many sleep researchers now recommend a digital curfew — no screens for at least one hour before bedtime." },
      ],
      questions: [
        { number: 31, type: "mcq", text: "What percentage of UK adults regularly get insufficient sleep?", options: ["A 25%", "B 30%", "C 35%"], correctAnswer: "C", explanation: "Approximately thirty-five per cent." },
        { number: 32, type: "mcq", text: "How long does each sleep cycle last?", options: ["A 60 minutes", "B 90 minutes", "C 120 minutes"], correctAnswer: "B", explanation: "Cycles lasting approximately ninety minutes." },
        { number: 33, type: "mcq", text: "How much better did students who slept perform on a new skill?", options: ["A 30% better", "B 40% better", "C 50% better"], correctAnswer: "B", explanation: "Performed forty per cent better." },
        { number: 34, type: "sentence_completion", text: "REM sleep makes up _______ to 25% of total sleep time.", correctAnswer: "20", explanation: "About twenty to twenty-five per cent." },
        { number: 35, type: "sentence_completion", text: "The glymphatic system is _______ per cent more active during sleep.", correctAnswer: "60", explanation: "Approximately sixty per cent more active." },
        { number: 36, type: "sentence_completion", text: "Using a smartphone before bed delays sleep onset by _______ minutes.", correctAnswer: "20", explanation: "Approximately twenty minutes." },
        { number: 37, type: "sentence_completion", text: "Chronic sleep deprivation increases heart disease risk by _______ per cent.", correctAnswer: "48", explanation: "A forty-eight per cent increased risk." },
        { number: 38, type: "summary_completion", text: "During deep sleep, the body undergoes physical _______ and immune function.", correctAnswer: "restoration", explanation: "Crucial for physical restoration." },
        { number: 39, type: "summary_completion", text: "The glymphatic system removes toxic _______ from the brain.", correctAnswer: "proteins", explanation: "Removes toxic proteins including beta-amyloid." },
        { number: 40, type: "summary_completion", text: "Sleep researchers recommend a digital _______ before bedtime.", correctAnswer: "curfew", explanation: "A digital curfew — no screens for at least one hour." },
      ],
    },
  ],
};
