import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_51: ReadingTest = {
  id: 51,
  passages: [
    {
      title: "History of Transportation Technology",
      text: `The history of transportation is a story of humanity's relentless quest to move faster, further, and more efficiently. From the domestication of the horse to the development of hypersonic aircraft, each major advance in transportation technology has reshaped economies, redrawn political boundaries, and transformed the daily lives of ordinary people. The pace of innovation has accelerated dramatically over the past two centuries, compressing into decades changes that previously took millennia.

The wheel, invented around 3500 BCE in Mesopotamia, is often cited as the foundational transportation technology. Initially used for pottery making, it was soon adapted for carts and chariots. The combination of the wheel with animal traction — oxen, horses, and camels — enabled the movement of goods and people over distances that would have been impractical on foot. Road networks followed: the Persian Royal Road, stretching over 2,700 kilometres from Susa to Sardis, allowed mounted couriers to traverse the empire in nine days.

Maritime technology developed in parallel. The ancient Egyptians constructed reed boats for Nile navigation as early as 4000 BCE, and by the second millennium BCE, Phoenician traders were sailing across the Mediterranean in sturdy wooden vessels powered by oars and sails. The Chinese junk, with its distinctive battened sails and watertight compartments, represented a significant advance in ship design. European caravel and carrack designs of the fifteenth century, with their combination of square and lateen sails, enabled the transoceanic voyages that connected the world's continents.

The steam engine, developed in the late eighteenth century, revolutionised both land and water transport. George Stephenson's Rocket locomotive, which achieved speeds of approximately 48 kilometres per hour in 1829, demonstrated the viability of steam-powered rail travel. Within decades, railway networks criss-crossed Europe and North America, reducing journey times from days to hours. Steamships similarly transformed maritime trade, eliminating dependence on wind and enabling predictable schedules across oceans.

The internal combustion engine, perfected in the late nineteenth century, enabled the development of automobiles and eventually aircraft. Karl Benz patented the first petrol-powered automobile in 1886, and Henry Ford's Model T, introduced in 1908, made car ownership accessible to ordinary families. The Wright Brothers' first powered flight at Kitty Hawk in 1903 lasted just twelve seconds and covered 37 metres, yet within forty years, aircraft were crossing oceans and carrying hundreds of passengers.

The jet age, which began commercially in the 1950s with the de Havilland Comet and the Boeing 707, collapsed global distances further. A journey from London to New York, which took five days by steamship in 1900, could be completed in seven hours by jet aircraft. High-speed rail, pioneered by Japan's Shinkansen in 1964, offered an alternative for medium-distance travel, with modern trains reaching speeds exceeding 300 kilometres per hour.

Today, transportation technology stands on the threshold of another transformation. Electric vehicles are replacing internal combustion engines, driven by falling battery costs and climate concerns. Autonomous driving technology promises to reshape urban mobility. Hyperloop concepts envision passengers travelling through vacuum tubes at speeds exceeding 1,000 kilometres per hour. Space tourism, once the domain of science fiction, became a commercial reality in 2021 when private companies launched paying passengers beyond the atmosphere.

Each transportation revolution has brought both benefits and costs — economic growth alongside environmental degradation, connectivity alongside cultural homogenisation, speed alongside risk. The challenge for the current generation is to harness emerging technologies in ways that maximise mobility while minimising their social and environmental footprint.`,
      questions: [
        { number: 1, type: "true_false_not_given", text: "The wheel was originally invented for transportation purposes.", correctAnswer: "FALSE", explanation: "The passage says it was 'Initially used for pottery making.'" },
        { number: 2, type: "true_false_not_given", text: "The Persian Royal Road was over 2,700 kilometres long.", correctAnswer: "TRUE", explanation: "The passage states this directly." },
        { number: 3, type: "true_false_not_given", text: "Chinese junks were less advanced than European ships.", correctAnswer: "NOT GIVEN", explanation: "The passage describes Chinese junks as having significant advances but does not compare them as inferior to European ships." },
        { number: 4, type: "true_false_not_given", text: "Stephenson's Rocket reached speeds of approximately 48 km/h.", correctAnswer: "TRUE", explanation: "The passage directly states this." },
        { number: 5, type: "true_false_not_given", text: "The Wright Brothers' first flight lasted over a minute.", correctAnswer: "FALSE", explanation: "The passage says it 'lasted just twelve seconds.'" },
        { number: 6, type: "true_false_not_given", text: "Japan's Shinkansen began service in 1964.", correctAnswer: "TRUE", explanation: "The passage states 'pioneered by Japan's Shinkansen in 1964.'" },
        { number: 7, type: "true_false_not_given", text: "Space tourism first became commercially available in 2025.", correctAnswer: "FALSE", explanation: "The passage says it 'became a commercial reality in 2021.'" },
        { number: 8, type: "sentence_completion", text: "Karl Benz patented the first petrol-powered automobile in ________.", correctAnswer: "1886", explanation: "The passage states 'patented in 1886.'" },
        { number: 9, type: "sentence_completion", text: "Ford's ________ made car ownership accessible to ordinary families.", correctAnswer: "Model T", explanation: "The passage says 'Henry Ford's Model T.'" },
        { number: 10, type: "sentence_completion", text: "A London to New York journey took five days by ________ in 1900.", correctAnswer: "steamship", explanation: "The passage says 'five days by steamship in 1900.'" },
        { number: 11, type: "sentence_completion", text: "Modern high-speed trains reach speeds exceeding ________ kilometres per hour.", correctAnswer: "300", explanation: "The passage states 'speeds exceeding 300 kilometres per hour.'" },
        { number: 12, type: "sentence_completion", text: "Hyperloop concepts envision speeds exceeding ________ kilometres per hour.", correctAnswer: "1,000", explanation: "The passage says 'speeds exceeding 1,000 kilometres per hour.'" },
        { number: 13, type: "sentence_completion", text: "The Wright Brothers' first flight covered ________ metres.", correctAnswer: "37", explanation: "The passage says 'covered 37 metres.'" }
      ]
    },
    {
      title: "Environmental Sustainability Solutions",
      text: `A. Environmental sustainability — the capacity to maintain ecological processes and biodiversity while meeting current human needs without compromising the ability of future generations to meet theirs — has become one of the defining challenges of the twenty-first century. As the consequences of industrialisation, population growth, and resource extraction become increasingly apparent, governments, businesses, and individuals are seeking solutions that balance economic development with environmental protection.

B. The circular economy represents a fundamental rethinking of the traditional linear model of production and consumption — take, make, dispose. Instead, it aims to keep materials in use for as long as possible through strategies including repair, reuse, remanufacturing, and recycling. The Ellen MacArthur Foundation estimates that transitioning to a circular economy could generate $4.5 trillion in economic benefits by 2030. Some companies have already embraced this model: Patagonia offers repair services for its clothing, and Renault remanufactures automotive parts to the same specifications as new components.

C. Renewable energy deployment has accelerated dramatically in recent years. Solar and wind power now represent the cheapest sources of new electricity generation in most countries. In 2022, renewables accounted for over twenty-nine per cent of global electricity generation. Energy storage technologies, particularly lithium-ion batteries, have become increasingly affordable, addressing the intermittency challenge that has historically limited renewable deployment. Community energy projects, in which local groups collectively own and operate renewable installations, are gaining traction across Europe.

D. Sustainable agriculture practices are essential for reducing the environmental impact of food production. Regenerative farming techniques — including cover cropping, reduced tillage, and integrated pest management — can restore soil health, increase carbon sequestration, and reduce dependence on synthetic inputs. Vertical farming, which grows crops in stacked layers within controlled indoor environments, can produce food year-round using up to ninety-five per cent less water than conventional agriculture, though its high energy requirements remain a challenge.

E. Urban sustainability initiatives are transforming cities worldwide. Green building standards such as LEED and BREEAM encourage energy-efficient design, sustainable materials, and reduced water consumption. Urban greening — the creation of parks, green roofs, and tree-lined streets — mitigates heat island effects, improves air quality, and enhances residents' mental health. Cities like Amsterdam and Copenhagen have invested heavily in cycling infrastructure, with cycling now accounting for a significant proportion of daily trips.

F. Ocean conservation has emerged as a critical sustainability priority. Marine protected areas (MPAs), which restrict or prohibit extractive activities like fishing and mining, now cover approximately eight per cent of the world's oceans. The UN High Seas Treaty, adopted in 2023, provides a framework for establishing MPAs in international waters for the first time. However, enforcement remains challenging, and scientists argue that at least thirty per cent of the ocean must be protected to maintain marine ecosystem health.

G. Behavioural change at the individual level is increasingly recognised as essential for sustainability. Reducing meat consumption, minimising air travel, choosing sustainable products, and reducing household energy use can significantly lower an individual's environmental footprint. However, critics argue that placing the burden of sustainability on individuals distracts from the systemic changes — in energy systems, industrial processes, and regulatory frameworks — that are necessary to address environmental challenges at scale.

H. The financing of sustainability initiatives presents both challenges and opportunities. Green bonds — fixed-income instruments whose proceeds fund environmental projects — have grown from a niche market to a multi-trillion-dollar asset class. Impact investing, which seeks financial returns alongside measurable social and environmental benefits, has attracted growing interest from institutional investors. Carbon markets, despite their imperfections, provide economic incentives for emissions reduction. The challenge is to ensure that these financial mechanisms channel resources toward genuinely transformative projects rather than incremental improvements.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Paragraph B", options: ["i. Protecting the seas", "ii. Rethinking production and waste", "iii. Green finance growth", "iv. Individual action debate", "v. Clean energy expansion", "vi. Cities going green", "vii. Farming for the future", "viii. Defining sustainability"], correctAnswer: "ii", explanation: "Paragraph B discusses the circular economy as a rethinking of production." },
        { number: 15, type: "matching_headings", text: "Paragraph D", options: ["i. Protecting the seas", "ii. Rethinking production and waste", "iii. Green finance growth", "iv. Individual action debate", "v. Clean energy expansion", "vi. Cities going green", "vii. Farming for the future", "viii. Defining sustainability"], correctAnswer: "vii", explanation: "Paragraph D discusses sustainable agriculture practices." },
        { number: 16, type: "matching_headings", text: "Paragraph F", options: ["i. Protecting the seas", "ii. Rethinking production and waste", "iii. Green finance growth", "iv. Individual action debate", "v. Clean energy expansion", "vi. Cities going green", "vii. Farming for the future", "viii. Defining sustainability"], correctAnswer: "i", explanation: "Paragraph F discusses ocean conservation and marine protected areas." },
        { number: 17, type: "matching_headings", text: "Paragraph H", options: ["i. Protecting the seas", "ii. Rethinking production and waste", "iii. Green finance growth", "iv. Individual action debate", "v. Clean energy expansion", "vi. Cities going green", "vii. Farming for the future", "viii. Defining sustainability"], correctAnswer: "iii", explanation: "Paragraph H discusses green bonds, impact investing, and carbon markets." },
        { number: 18, type: "summary_completion", text: "The circular economy could generate $________ trillion in economic benefits by 2030.", correctAnswer: "4.5", explanation: "The passage states '$4.5 trillion in economic benefits.'" },
        { number: 19, type: "summary_completion", text: "In 2022, renewables accounted for over ________ per cent of global electricity.", correctAnswer: "twenty-nine", explanation: "The passage says 'over twenty-nine per cent.'" },
        { number: 20, type: "summary_completion", text: "Vertical farming uses up to ________ per cent less water than conventional agriculture.", correctAnswer: "ninety-five", explanation: "The passage states 'up to ninety-five per cent less water.'" },
        { number: 21, type: "summary_completion", text: "Marine protected areas cover approximately ________ per cent of the world's oceans.", correctAnswer: "eight", explanation: "The passage says 'approximately eight per cent.'" },
        { number: 22, type: "summary_completion", text: "The UN High Seas Treaty was adopted in ________.", correctAnswer: "2023", explanation: "The passage states 'adopted in 2023.'" },
        { number: 23, type: "summary_completion", text: "Scientists argue at least ________ per cent of the ocean must be protected.", correctAnswer: "thirty", explanation: "The passage says 'at least thirty per cent.'" },
        { number: 24, type: "summary_completion", text: "Patagonia offers ________ services for its clothing as a circular economy practice.", correctAnswer: "repair", explanation: "The passage says 'Patagonia offers repair services.'" },
        { number: 25, type: "summary_completion", text: "Green building standards include ________ and BREEAM.", correctAnswer: "LEED", explanation: "The passage says 'Green building standards such as LEED and BREEAM.'" },
        { number: 26, type: "summary_completion", text: "Green bonds have grown into a multi-________-dollar asset class.", correctAnswer: "trillion", explanation: "The passage says 'a multi-trillion-dollar asset class.'" }
      ]
    },
    {
      title: "Artificial Intelligence in Workplaces",
      text: `A. Artificial intelligence is transforming workplaces across every sector of the economy, from manufacturing and healthcare to finance and creative industries. The integration of AI into professional environments raises fundamental questions about productivity, employment, skill requirements, and the nature of work itself. As organisations adopt AI tools at an accelerating pace, understanding their impact on workers and workplaces has become a priority for researchers, policymakers, and business leaders alike.

B. In manufacturing, AI-powered robots have moved beyond repetitive assembly-line tasks to perform complex operations requiring adaptability and precision. Collaborative robots, or "cobots," are designed to work alongside human workers, handling physically demanding or dangerous tasks while humans focus on quality control, problem-solving, and creative decision-making. BMW's factories, for example, deploy cobots that can adjust their movements in real time based on sensor feedback, reducing workplace injuries while improving production efficiency.

C. The healthcare sector has been an early adopter of AI technologies. Machine learning algorithms can now analyse medical images — X-rays, MRI scans, and histology slides — with accuracy rivalling or exceeding that of experienced radiologists. AI systems assist in drug discovery by predicting molecular interactions and identifying promising compounds far faster than traditional laboratory methods. Natural language processing tools help clinicians navigate vast medical literature, summarising relevant research and flagging potential drug interactions.

D. In financial services, AI has transformed trading, risk assessment, and customer service. Algorithmic trading systems execute transactions at speeds impossible for human traders, analysing market data and executing orders in microseconds. AI-powered credit scoring models assess borrower risk by analysing thousands of variables — including non-traditional data such as utility payment patterns and mobile phone usage — potentially expanding access to credit for underserved populations. Chatbots and virtual assistants handle routine customer inquiries, reducing costs while providing twenty-four-hour service.

E. The creative industries, once considered immune to automation, are being reshaped by generative AI. Large language models can produce marketing copy, news articles, and even poetry. Image generation tools create visual content from text descriptions. AI music composition software produces background tracks for videos and advertisements. While some creative professionals view these tools as productivity enhancers that handle routine tasks, others fear they will devalue human creativity and reduce employment opportunities in creative fields.

F. The impact of AI on employment patterns is hotly debated. Some economists argue that AI will primarily augment human capabilities rather than replace workers — making individuals more productive rather than redundant. Others warn that the current wave of AI automation differs from previous technological disruptions in its ability to perform cognitive tasks previously thought to require human intelligence. A 2023 analysis by Goldman Sachs estimated that generative AI could affect approximately 300 million full-time jobs globally, though it emphasised that "affected" does not necessarily mean "eliminated."

G. The skills required in AI-augmented workplaces are shifting significantly. Technical skills in data analysis, programming, and AI system management are increasingly valued, but so-called "soft skills" — critical thinking, creativity, emotional intelligence, and interpersonal communication — are gaining importance precisely because they are difficult for machines to replicate. Educational institutions and corporate training programmes are adapting curricula to prepare workers for this evolving landscape, though the pace of change often outstrips the capacity of training systems to respond.

H. Ethical concerns about AI in the workplace extend beyond employment effects. AI monitoring tools that track employee keystrokes, screen activity, and even facial expressions raise concerns about surveillance and worker autonomy. Algorithmic management systems that assign tasks, evaluate performance, and make scheduling decisions can reduce human discretion and create stress. The challenge for organisations is to deploy AI in ways that enhance productivity and working conditions while respecting workers' dignity, privacy, and professional development.`,
      questions: [
        { number: 27, type: "matching_information", text: "AI tools that monitor employee behaviour and create surveillance concerns", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "H", explanation: "Paragraph H discusses AI monitoring tools tracking keystrokes and facial expressions." },
        { number: 28, type: "matching_information", text: "The use of AI in medical image analysis", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "C", explanation: "Paragraph C discusses AI analysing X-rays, MRI scans, and histology slides." },
        { number: 29, type: "matching_information", text: "An estimate of jobs globally that could be affected by generative AI", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "F", explanation: "Paragraph F mentions Goldman Sachs' estimate of 300 million jobs." },
        { number: 30, type: "matching_information", text: "The growing importance of soft skills in AI workplaces", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "G", explanation: "Paragraph G discusses the increasing value of soft skills." },
        { number: 31, type: "multiple_choice", text: "What are 'cobots' designed to do?", options: ["A. Replace all human workers", "B. Work alongside humans on difficult tasks", "C. Operate independently without supervision", "D. Manage other robots"], correctAnswer: "B", explanation: "The passage says cobots are 'designed to work alongside human workers.'" },
        { number: 32, type: "multiple_choice", text: "According to Goldman Sachs, how many jobs could generative AI affect?", options: ["A. 100 million", "B. 200 million", "C. 300 million", "D. 500 million"], correctAnswer: "C", explanation: "The passage states 'approximately 300 million full-time jobs globally.'" },
        { number: 33, type: "multiple_choice", text: "Which industry was described as once considered immune to automation?", options: ["A. Manufacturing", "B. Healthcare", "C. Financial services", "D. Creative industries"], correctAnswer: "D", explanation: "The passage says 'The creative industries, once considered immune to automation.'" },
        { number: 34, type: "short_answer", text: "What type of robots work alongside humans in BMW factories?", correctAnswer: "cobots", explanation: "The passage mentions 'Collaborative robots, or cobots.'" },
        { number: 35, type: "short_answer", text: "What do algorithmic trading systems execute in microseconds?", correctAnswer: "transactions/orders", explanation: "The passage says they execute 'transactions at speeds impossible for human traders.'" },
        { number: 36, type: "short_answer", text: "What non-traditional data might AI credit scoring use?", correctAnswer: "utility payment patterns and mobile phone usage", explanation: "The passage lists these as examples." },
        { number: 37, type: "short_answer", text: "What type of AI can produce marketing copy and news articles?", correctAnswer: "large language models", explanation: "The passage says 'Large language models can produce marketing copy, news articles.'" },
        { number: 38, type: "short_answer", text: "Name two soft skills mentioned as gaining importance.", correctAnswer: "critical thinking and creativity", explanation: "The passage lists critical thinking, creativity, emotional intelligence, and interpersonal communication." },
        { number: 39, type: "short_answer", text: "What do algorithmic management systems assign to workers?", correctAnswer: "tasks", explanation: "The passage says they 'assign tasks, evaluate performance, and make scheduling decisions.'" },
        { number: 40, type: "short_answer", text: "What does AI help clinicians navigate in healthcare?", correctAnswer: "medical literature", explanation: "The passage says AI tools 'help clinicians navigate vast medical literature.'" }
      ]
    }
  ]
};
