import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_17: ReadingTest = {
  id: 17,
  passages: [
    {
      title: "Ancient Civilizations and Trade",
      text: `Trade has been a driving force in the development of human civilisations since the earliest settled communities began to produce surpluses of food, raw materials, and crafted goods. The exchange of commodities between distant peoples not only enriched material life but also facilitated the spread of ideas, technologies, languages, and religious beliefs, weaving the diverse cultures of the ancient world into an increasingly interconnected tapestry.

The earliest evidence of long-distance trade dates back to the Neolithic period, around 7000 BCE, when obsidian — a volcanic glass prized for making sharp tools and weapons — was transported from sources in Anatolia (modern Turkey) to settlements hundreds of kilometres away in the Levant and Mesopotamia. The fact that Neolithic communities valued obsidian highly enough to transport it over such distances indicates that organised exchange networks existed long before the invention of writing or the emergence of cities.

The civilisations of ancient Mesopotamia, situated between the Tigris and Euphrates rivers in modern-day Iraq, were among the first to develop formal systems of trade. The Sumerians, who established some of the world's earliest cities around 3500 BCE, lacked many essential natural resources — including timber, stone, and metals — and relied on trade to obtain them. Sumerian merchants exchanged locally produced goods such as textiles, grain, and pottery for cedar wood from Lebanon, copper from Oman, and lapis lazuli from Afghanistan. The development of cuneiform writing around 3200 BCE was itself partly driven by the need to keep records of commercial transactions.

Ancient Egypt's trade networks extended southward into Nubia (modern Sudan), eastward across the Red Sea to the land of Punt (believed to be in the Horn of Africa), and northward into the eastern Mediterranean. Egyptian merchants exported gold, papyrus, linen, and grain, and imported exotic goods such as incense, myrrh, ebony, ivory, and live animals. The expedition to Punt organised by Queen Hatshepsut around 1470 BCE, depicted in detailed reliefs at her mortuary temple at Deir el-Bahari, is one of the best-documented trading voyages of the ancient world.

The Phoenicians, based in city-states along the coast of modern Lebanon — including Tyre, Sidon, and Byblos — were the greatest maritime traders of the ancient Mediterranean. From approximately 1500 to 300 BCE, Phoenician ships carried goods across the entire Mediterranean basin and beyond, establishing trading colonies as far west as Carthage in North Africa and Cádiz in Spain. The Phoenicians traded in a wide variety of commodities, but they were especially renowned for their production of Tyrian purple dye, extracted from the murex sea snail, which was so expensive that it became associated with royalty and nobility. Perhaps the Phoenicians' most enduring legacy, however, was their alphabet — a system of 22 consonantal letters that was far simpler than the cuneiform and hieroglyphic scripts it competed with, and which became the ancestor of the Greek, Latin, Arabic, and Hebrew alphabets.

The ancient Greeks built upon Phoenician foundations to create a sophisticated maritime trading economy. Greek city-states such as Athens and Corinth exported olive oil, wine, pottery, and silver, and imported grain, timber, metals, and luxury goods. The Athenian silver mines at Laurion financed the construction of the fleet that defeated the Persians at the Battle of Salamis in 480 BCE. Greek colonisation of the Black Sea coast, southern Italy, and Sicily was driven largely by commercial motives, establishing new markets and securing access to vital agricultural resources.

The Roman Empire created the most extensive and integrated trading network the ancient world had ever seen. Roman roads, harbours, and shipping lanes connected Britain to Egypt and Spain to Syria, facilitating the movement of goods on a scale that would not be matched for over a millennium. The Roman state actively promoted trade through standardised weights and measures, a stable currency system, and the suppression of piracy. At the height of the Empire, luxury goods from as far afield as India and China — including silk, spices, precious stones, and exotic animals — flowed into Roman markets, while Roman glass, metalwork, and wine were exported in return.

These ancient trade networks demonstrate that globalisation is not a modern phenomenon but rather the continuation of processes that have been shaping human civilisation for millennia.`,
      questions: [
        { number: 1, type: "true_false_not_given", text: "Obsidian was traded in the Neolithic period primarily for decorative purposes.", correctAnswer: "FALSE", explanation: "The passage says obsidian was 'prized for making sharp tools and weapons,' not decoration." },
        { number: 2, type: "true_false_not_given", text: "The Sumerians had abundant natural resources within their own territory.", correctAnswer: "FALSE", explanation: "The passage states the Sumerians 'lacked many essential natural resources.'" },
        { number: 3, type: "true_false_not_given", text: "Cuneiform writing was developed partly to record commercial transactions.", correctAnswer: "TRUE", explanation: "The passage says cuneiform 'was itself partly driven by the need to keep records of commercial transactions.'" },
        { number: 4, type: "true_false_not_given", text: "The exact location of the land of Punt has been confirmed by archaeologists.", correctAnswer: "FALSE", explanation: "The passage says Punt is only 'believed to be in the Horn of Africa,' indicating its location is not confirmed." },
        { number: 5, type: "true_false_not_given", text: "Queen Hatshepsut personally led the expedition to Punt.", correctAnswer: "NOT GIVEN", explanation: "The passage says Hatshepsut 'organised' the expedition but does not say she personally led it." },
        { number: 6, type: "true_false_not_given", text: "Tyrian purple dye was affordable for ordinary Phoenician citizens.", correctAnswer: "FALSE", explanation: "The passage says it 'was so expensive that it became associated with royalty and nobility.'" },
        { number: 7, type: "true_false_not_given", text: "The Phoenician alphabet contained 22 letters.", correctAnswer: "TRUE", explanation: "The passage states 'a system of 22 consonantal letters.'" },
        { number: 8, type: "true_false_not_given", text: "Athens exported more olive oil than wine.", correctAnswer: "NOT GIVEN", explanation: "The passage mentions Athens exported both but does not compare quantities." },
        { number: 9, type: "true_false_not_given", text: "The silver mines at Laurion helped fund the Athenian navy.", correctAnswer: "TRUE", explanation: "The passage says the mines 'financed the construction of the fleet that defeated the Persians.'" },
        { number: 10, type: "true_false_not_given", text: "Roman trade networks were surpassed in scale within two centuries of the Empire's fall.", correctAnswer: "FALSE", explanation: "The passage says the scale 'would not be matched for over a millennium.'" },
        { number: 11, type: "true_false_not_given", text: "The Romans imported silk from China.", correctAnswer: "TRUE", explanation: "The passage mentions 'luxury goods from as far afield as India and China — including silk.'" },
        { number: 12, type: "true_false_not_given", text: "Carthage was originally a Greek colony.", correctAnswer: "FALSE", explanation: "The passage says the Phoenicians established 'trading colonies as far west as Carthage.'" },
        { number: 13, type: "true_false_not_given", text: "The passage argues that globalisation began in the twentieth century.", correctAnswer: "FALSE", explanation: "The passage concludes that globalisation 'is not a modern phenomenon' but a continuation of ancient processes." },
      ],
    },
    {
      title: "Forest Ecosystems",
      text: `A. Forests are among the most complex and ecologically important ecosystems on Earth, covering approximately 31 percent of the global land area — roughly 4.06 billion hectares. They harbour an estimated 80 percent of all terrestrial biodiversity, including millions of species of plants, animals, fungi, and microorganisms, many of which remain undiscovered by science. Beyond their biological richness, forests provide a vast array of ecosystem services that are essential for human well-being, including climate regulation, water purification, soil stabilisation, flood mitigation, and the provision of food, medicine, and raw materials.

B. Tropical forests, found in a belt around the equator in regions such as the Amazon Basin, the Congo Basin, and Southeast Asia, are the most biologically diverse terrestrial ecosystems. A single hectare of tropical rainforest can contain over 300 tree species — more than are found in the entire forests of some temperate countries. Tropical forests also play a disproportionately important role in the global carbon cycle, storing an estimated 250 billion tonnes of carbon in their biomass and soil — roughly equivalent to 30 years of global fossil fuel emissions. The canopy of a tropical rainforest can reach heights of 50 metres or more, creating a vertical structure of distinct layers — the emergent layer, canopy, understory, and forest floor — each supporting its own community of specialised organisms.

C. Temperate forests, found in regions with distinct seasons including parts of North America, Europe, and East Asia, are dominated by broadleaved deciduous trees such as oak, beech, and maple, or by evergreen conifers such as pine, spruce, and fir. These forests experience marked seasonal changes: deciduous trees shed their leaves in autumn, enter dormancy during winter, and produce new foliage in spring, in a cycle driven by changes in day length and temperature. Temperate forests are significant carbon sinks and support diverse wildlife, including large mammals such as deer, bears, and wolves. Historically, temperate forests have been among the most heavily exploited by humans for timber, agriculture, and urban development, though reforestation efforts in recent decades have increased forest cover in some regions.

D. Boreal forests, also known as taiga, form the largest terrestrial biome, stretching across northern latitudes in Russia, Canada, Scandinavia, and Alaska. These forests are dominated by cold-tolerant coniferous species such as spruce, larch, and pine, and experience long, harsh winters with temperatures that can drop below minus 40 degrees Celsius. Despite their lower species diversity compared to tropical forests, boreal forests are globally significant as carbon reservoirs: they store an estimated 32 percent of the world's forest carbon, much of it in the thick layers of peat and organic matter that accumulate in their waterlogged soils. Boreal forests are increasingly threatened by climate change, which is causing rising temperatures, increased wildfire frequency and intensity, and outbreaks of bark beetle infestations that can devastate vast areas of forest.

E. Deforestation — the permanent conversion of forest land to other uses such as agriculture, ranching, mining, and urban development — remains one of the most pressing environmental challenges of the twenty-first century. Between 2001 and 2020, the world lost approximately 411 million hectares of tree cover — an area larger than the European Union. Tropical deforestation is the most severe, driven primarily by the expansion of commercial agriculture, particularly for the production of soy, palm oil, beef, and timber. The Amazon rainforest alone lost over 34 million hectares during this period, raising concerns about the forest approaching a "tipping point" beyond which it could transform irreversibly from a carbon sink into a carbon source, accelerating global warming.

F. Forest restoration and sustainable management are increasingly recognised as critical strategies for addressing climate change, biodiversity loss, and rural poverty. The Bonn Challenge, launched in 2011, aims to restore 350 million hectares of degraded and deforested land by 2030, and over 60 countries have made pledges contributing to this target. Natural regeneration — allowing forests to regrow naturally on abandoned or degraded land — is often more effective and cost-efficient than active tree planting, producing forests that are more diverse and resilient. Community forestry programmes, which give local communities legal rights and responsibilities over forest resources, have been shown to reduce deforestation rates while improving livelihoods and strengthening social cohesion. The economic value of standing forests — through carbon credits, eco-tourism, sustainable timber harvesting, and non-timber forest products — is increasingly being recognised as a powerful incentive for conservation.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Paragraph B", options: ["i. The vast northern coniferous forests", "ii. The biological richness of equatorial forests", "iii. Efforts to restore the world's forests", "iv. Forests with seasonal leaf cycles", "v. The scale and importance of global forests", "vi. The ongoing destruction of forest habitats", "vii. Carbon storage in waterlogged soils", "viii. Legal frameworks for forest management"], correctAnswer: "ii", explanation: "Paragraph B describes tropical forests as 'the most biologically diverse terrestrial ecosystems.'" },
        { number: 15, type: "matching_headings", text: "Paragraph C", options: ["i. The vast northern coniferous forests", "ii. The biological richness of equatorial forests", "iii. Efforts to restore the world's forests", "iv. Forests with seasonal leaf cycles", "v. The scale and importance of global forests", "vi. The ongoing destruction of forest habitats", "vii. Carbon storage in waterlogged soils", "viii. Legal frameworks for forest management"], correctAnswer: "iv", explanation: "Paragraph C describes temperate deciduous forests that 'shed their leaves in autumn.'" },
        { number: 16, type: "matching_headings", text: "Paragraph D", options: ["i. The vast northern coniferous forests", "ii. The biological richness of equatorial forests", "iii. Efforts to restore the world's forests", "iv. Forests with seasonal leaf cycles", "v. The scale and importance of global forests", "vi. The ongoing destruction of forest habitats", "vii. Carbon storage in waterlogged soils", "viii. Legal frameworks for forest management"], correctAnswer: "i", explanation: "Paragraph D describes boreal forests (taiga) — the largest terrestrial biome in northern latitudes." },
        { number: 17, type: "matching_headings", text: "Paragraph E", options: ["i. The vast northern coniferous forests", "ii. The biological richness of equatorial forests", "iii. Efforts to restore the world's forests", "iv. Forests with seasonal leaf cycles", "v. The scale and importance of global forests", "vi. The ongoing destruction of forest habitats", "vii. Carbon storage in waterlogged soils", "viii. Legal frameworks for forest management"], correctAnswer: "vi", explanation: "Paragraph E discusses deforestation, tree cover loss, and the Amazon tipping point." },
        { number: 18, type: "matching_headings", text: "Paragraph F", options: ["i. The vast northern coniferous forests", "ii. The biological richness of equatorial forests", "iii. Efforts to restore the world's forests", "iv. Forests with seasonal leaf cycles", "v. The scale and importance of global forests", "vi. The ongoing destruction of forest habitats", "vii. Carbon storage in waterlogged soils", "viii. Legal frameworks for forest management"], correctAnswer: "iii", explanation: "Paragraph F discusses the Bonn Challenge, natural regeneration, and community forestry." },
        { number: 19, type: "table_completion", text: "Forests cover approximately _______ percent of global land area.", correctAnswer: "31", explanation: "The passage states 'approximately 31 percent.'" },
        { number: 20, type: "table_completion", text: "Forests harbour an estimated _______ percent of terrestrial biodiversity.", correctAnswer: "80", explanation: "The passage says 'an estimated 80 percent.'" },
        { number: 21, type: "table_completion", text: "Tropical forests store approximately _______ billion tonnes of carbon.", correctAnswer: "250", explanation: "The passage says 'storing an estimated 250 billion tonnes.'" },
        { number: 22, type: "table_completion", text: "A single hectare of tropical rainforest can contain over _______ tree species.", correctAnswer: "300", explanation: "The passage states 'over 300 tree species.'" },
        { number: 23, type: "table_completion", text: "Boreal forests store approximately _______ percent of the world's forest carbon.", correctAnswer: "32", explanation: "The passage says 'an estimated 32 percent.'" },
        { number: 24, type: "table_completion", text: "Between 2001 and 2020, the world lost approximately _______ million hectares of tree cover.", correctAnswer: "411", explanation: "The passage states 'approximately 411 million hectares.'" },
        { number: 25, type: "table_completion", text: "The Bonn Challenge aims to restore _______ million hectares by 2030.", correctAnswer: "350", explanation: "The passage says 'restore 350 million hectares.'" },
        { number: 26, type: "table_completion", text: "The Amazon lost over _______ million hectares between 2001 and 2020.", correctAnswer: "34", explanation: "The passage says 'over 34 million hectares.'" },
      ],
    },
    {
      title: "Robotics and Automation",
      text: `The field of robotics and automation has undergone a dramatic transformation in the twenty-first century, moving far beyond the repetitive industrial tasks for which robots were originally designed. Today, robots are being deployed in environments ranging from hospital operating theatres and deep-sea exploration vessels to warehouses, farms, restaurants, and private homes. This expansion has been driven by advances in artificial intelligence, sensor technology, materials science, and computing power, which have made robots increasingly capable of operating in complex, unstructured, and unpredictable environments.

A. Industrial robotics remains the backbone of the field, with manufacturing accounting for the largest share of robot installations worldwide. The International Federation of Robotics (IFR) reports that the global stock of operational industrial robots reached approximately 3.9 million units in 2022, with annual installations exceeding 530,000 — a record high. The automotive industry has traditionally been the largest user of industrial robots, but electronics manufacturing, metal fabrication, food processing, and pharmaceuticals are rapidly increasing their adoption. Modern industrial robots are far more versatile than their predecessors: collaborative robots, or "cobots," are designed to work alongside human workers without the need for safety cages, using force-limiting sensors and advanced vision systems to detect and avoid contact with people.

B. Warehouse and logistics automation has emerged as one of the fastest-growing applications of robotics, driven by the explosive growth of e-commerce. Amazon, which operates over 750,000 robots across its global fulfilment network, has pioneered the use of autonomous mobile robots (AMRs) that navigate warehouse floors carrying shelving units to human pickers, dramatically reducing the time and distance workers must travel. Automated sorting systems can process thousands of parcels per hour, using computer vision and machine learning to read labels, classify packages, and route them to the correct destination. The development of autonomous delivery robots and drones promises to extend automation beyond the warehouse to the "last mile" of the delivery chain, though regulatory and safety challenges remain significant.

C. Agricultural robotics is addressing critical labour shortages and sustainability challenges in farming. Autonomous tractors equipped with GPS and computer vision can plough, seed, and spray fields with precision, reducing fuel consumption, chemical use, and soil compaction. Harvesting robots, though technically challenging due to the delicate nature of many fruits and vegetables, are being developed for crops including strawberries, apples, and tomatoes, using soft grippers and advanced vision systems to identify and pick ripe produce without damage. Drone-based crop monitoring enables farmers to detect plant stress, pest infestations, and irrigation problems at an early stage, enabling targeted interventions that reduce costs and improve yields.

D. Service robotics — robots designed to assist or interact with people in non-manufacturing settings — is a rapidly expanding category. Healthcare robots include surgical systems, rehabilitation exoskeletons, and social companion robots for elderly and dementia patients. Hospitality robots are being deployed in hotels and restaurants to deliver room service, prepare food, and greet guests. Cleaning robots, from consumer-grade vacuum cleaners to industrial floor scrubbers, have become commonplace. Educational robots are used in schools to teach programming, science, and mathematics through interactive, hands-on learning experiences. The global service robotics market was valued at approximately $37 billion in 2022 and is projected to grow at a compound annual rate of over 20 percent through the end of the decade.

E. The social and economic implications of widespread robotics and automation are the subject of intense debate. Optimists argue that robots will free humans from dangerous, dirty, and repetitive tasks, increase productivity, and create new industries and employment opportunities that we cannot yet imagine — much as previous waves of automation ultimately created more jobs than they destroyed. Pessimists warn that the current wave of automation, powered by AI, is qualitatively different from previous technological revolutions because it threatens not only manual labour but also cognitive tasks such as data analysis, customer service, and even creative work. A report by the World Economic Forum projected that automation could displace 85 million jobs globally by 2025 but create 97 million new roles, resulting in a net gain — though the transition is likely to be painful for workers in displaced occupations, requiring massive investment in retraining and social safety nets.

F. The development of ethical frameworks for robotics is becoming increasingly urgent as robots take on greater roles in society. Questions of accountability — who is responsible when a robot causes harm? — are legally complex and vary across jurisdictions. The potential for autonomous weapons systems to make life-and-death decisions without human oversight has prompted calls for international regulation, with over 30 countries supporting a ban on fully autonomous lethal weapons. Privacy concerns arise when robots equipped with cameras and sensors operate in homes, hospitals, and public spaces. As robots become more capable and autonomous, society will need to establish clear norms, laws, and institutions to govern their development and deployment, ensuring that the benefits of robotics are distributed equitably and that fundamental human rights and values are protected.`,
      questions: [
        { number: 27, type: "matching_information", text: "The projected impact of automation on global employment figures", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "E", explanation: "Paragraph E cites the WEF report projecting '85 million jobs displaced but 97 million new roles.'" },
        { number: 28, type: "matching_information", text: "Robots that can work safely next to humans without protective barriers", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "A", explanation: "Paragraph A describes cobots 'designed to work alongside human workers without the need for safety cages.'" },
        { number: 29, type: "matching_information", text: "The use of drones to detect crop problems early", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "C", explanation: "Paragraph C describes 'Drone-based crop monitoring' detecting 'plant stress, pest infestations.'" },
        { number: 30, type: "matching_information", text: "Calls for an international ban on weapons that can kill without human control", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "F", explanation: "Paragraph F mentions 'over 30 countries supporting a ban on fully autonomous lethal weapons.'" },
        { number: 31, type: "matching_information", text: "A company using over 750,000 robots in its operations", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "B", explanation: "Paragraph B states 'Amazon operates over 750,000 robots across its global fulfilment network.'" },
        { number: 32, type: "sentence_completion", text: "The global stock of industrial robots reached approximately _______ million units in 2022.", correctAnswer: "3.9", explanation: "The passage states 'approximately 3.9 million units.'" },
        { number: 33, type: "sentence_completion", text: "Annual industrial robot installations exceeded _______ in 2022.", correctAnswer: "530,000", explanation: "The passage says 'annual installations exceeding 530,000.'" },
        { number: 34, type: "sentence_completion", text: "Collaborative robots are commonly known as _______.", correctAnswer: "cobots", explanation: "The passage introduces 'collaborative robots, or \"cobots.\"'" },
        { number: 35, type: "sentence_completion", text: "The global service robotics market was valued at approximately $_______ billion in 2022.", correctAnswer: "37", explanation: "The passage states 'valued at approximately $37 billion.'" },
        { number: 36, type: "sentence_completion", text: "The WEF projected automation could displace _______ million jobs by 2025.", correctAnswer: "85", explanation: "The passage says 'displace 85 million jobs globally by 2025.'" },
        { number: 37, type: "sentence_completion", text: "The WEF projected automation would create _______ million new roles.", correctAnswer: "97", explanation: "The passage says 'create 97 million new roles.'" },
        { number: 38, type: "sentence_completion", text: "Over _______ countries support a ban on fully autonomous lethal weapons.", correctAnswer: "30", explanation: "The passage states 'over 30 countries.'" },
        { number: 39, type: "sentence_completion", text: "The service robotics market is projected to grow at over _______ percent annually.", correctAnswer: "20", explanation: "The passage says 'a compound annual rate of over 20 percent.'" },
        { number: 40, type: "sentence_completion", text: "The _______ industry has traditionally been the largest user of industrial robots.", correctAnswer: "automotive", explanation: "The passage states 'The automotive industry has traditionally been the largest user.'" },
      ],
    },
  ],
};
