import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_15: ReadingTest = {
  id: 15,
  passages: [
    {
      title: "Early Printing Technology",
      text: `The invention of printing is widely regarded as one of the most important developments in human history, comparable in its impact to the invention of writing itself. By enabling the rapid and inexpensive reproduction of text, printing democratised access to knowledge, accelerated the spread of ideas, and fundamentally transformed education, religion, politics, and commerce. The story of printing spans continents and centuries, beginning in East Asia long before the technology reached Europe.

The earliest known form of printing is woodblock printing, which originated in China during the Tang Dynasty (618–907 CE). In this process, an entire page of text and illustrations was carved in reverse into a flat block of wood, which was then inked and pressed onto paper or fabric. The oldest surviving printed book produced by this method is the Diamond Sutra, a Buddhist text dated to 868 CE, discovered in the Mogao Caves near Dunhuang in northwestern China. Woodblock printing was labour-intensive — each page required the carving of a new block — but it was well suited to the Chinese writing system, which uses thousands of distinct characters, making the assembly of individual type pieces impractical at the time.

The next major innovation was movable type, invented by the Chinese artisan Bi Sheng around 1040 CE during the Song Dynasty. Bi Sheng created individual character pieces from baked clay, which could be arranged on a plate to compose a page, inked, and printed. After printing, the type pieces could be rearranged to compose a different page, making the process more flexible and economical for long print runs. Despite its ingenuity, movable type was not widely adopted in China, partly because the enormous number of Chinese characters (over 40,000 in common use) made the creation and management of a complete type set extraordinarily complex. In Korea, however, metal movable type was developed in the thirteenth century and used to print Buddhist texts and government documents, predating Gutenberg's European invention by approximately two centuries.

Johannes Gutenberg's development of a practical movable type printing system in Mainz, Germany, around 1440, is generally considered the most consequential moment in the history of printing. Gutenberg's system combined several innovations: durable metal type cast from a lead-tin-antimony alloy using an adjustable hand mould; an oil-based ink that adhered well to metal type and produced clear impressions on paper; and a wooden printing press adapted from the screw presses used in winemaking and papermaking. Together, these elements created a system that was fast, reliable, and scalable. Gutenberg's masterpiece, the 42-line Bible (also known as the Gutenberg Bible), printed around 1455, demonstrated the extraordinary quality that his system could achieve: the text is set in a Gothic typeface of remarkable regularity and beauty, with each page containing 42 lines of text in two columns.

The impact of Gutenberg's invention was immediate and far-reaching. Within fifty years, printing presses had been established in over 270 cities across Europe, and an estimated 20 million volumes had been produced — more than all the books copied by hand in the previous thousand years combined. The cost of books fell dramatically, making them accessible to a far wider audience than had previously been possible. The Protestant Reformation, which began in 1517 when Martin Luther published his Ninety-Five Theses, was fundamentally enabled by the printing press: Luther's writings were reprinted and distributed across Germany and beyond with extraordinary speed, reaching an audience that would have been impossible to achieve through manuscript circulation alone. The press also facilitated the Scientific Revolution by enabling researchers to share their findings widely and build upon each other's work.

Printing technology continued to evolve in the centuries following Gutenberg. The development of lithography by Alois Senefelder in 1796 introduced a fundamentally different printing method based on the chemical repulsion of oil and water, enabling the efficient reproduction of illustrations, maps, and colour images. The steam-powered rotary press, developed in the nineteenth century, vastly increased printing speeds, enabling the mass production of newspapers and magazines. Offset printing, which transfers ink from a plate to a rubber blanket before pressing it onto paper, became the dominant commercial printing technology in the twentieth century, prized for its consistent quality and ability to print on a wide range of surfaces. The introduction of digital printing and desktop publishing in the late twentieth century brought the means of production within reach of individuals and small businesses, further extending the democratising legacy of Gutenberg's original innovation.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "The Diamond Sutra is significant because it is", options: ["A the first text ever written in Chinese.", "B the oldest surviving printed book.", "C the first book printed using movable type.", "D the most widely distributed Buddhist text."], correctAnswer: "B", explanation: "The passage describes it as 'The oldest surviving printed book produced by this method.'" },
        { number: 2, type: "multiple_choice", text: "Movable type was not widely adopted in China mainly because", options: ["A the technology was too expensive.", "B woodblock printing was faster.", "C the large number of Chinese characters made it impractical.", "D the government banned its use."], correctAnswer: "C", explanation: "The passage says 'the enormous number of Chinese characters made the creation and management of a complete type set extraordinarily complex.'" },
        { number: 3, type: "multiple_choice", text: "Gutenberg's printing press was adapted from technology used in", options: ["A textile manufacturing.", "B winemaking and papermaking.", "C metalworking.", "D shipbuilding."], correctAnswer: "B", explanation: "The passage says 'a wooden printing press adapted from the screw presses used in winemaking and papermaking.'" },
        { number: 4, type: "multiple_choice", text: "Within fifty years of Gutenberg's invention, approximately how many volumes had been produced?", options: ["A 2 million.", "B 10 million.", "C 20 million.", "D 100 million."], correctAnswer: "C", explanation: "The passage states 'an estimated 20 million volumes had been produced.'" },
        { number: 5, type: "multiple_choice", text: "The passage suggests that the printing press was essential to the Protestant Reformation because it", options: ["A reduced the power of the Catholic Church directly.", "B enabled Luther's ideas to be distributed rapidly and widely.", "C allowed Luther to print in multiple languages.", "D was used exclusively by Protestant churches."], correctAnswer: "B", explanation: "The passage says Luther's writings 'were reprinted and distributed across Germany and beyond with extraordinary speed.'" },
        { number: 6, type: "true_false_not_given", text: "Woodblock printing was invented during the Han Dynasty.", correctAnswer: "FALSE", explanation: "The passage says it 'originated in China during the Tang Dynasty,' not the Han Dynasty." },
        { number: 7, type: "true_false_not_given", text: "Bi Sheng's movable type pieces were made from metal.", correctAnswer: "FALSE", explanation: "The passage states Bi Sheng 'created individual character pieces from baked clay,' not metal." },
        { number: 8, type: "true_false_not_given", text: "Korean metal movable type predated Gutenberg's invention by about 200 years.", correctAnswer: "TRUE", explanation: "The passage says Korean metal movable type 'predating Gutenberg's European invention by approximately two centuries.'" },
        { number: 9, type: "true_false_not_given", text: "The Gutenberg Bible was the first book ever printed in Europe.", correctAnswer: "NOT GIVEN", explanation: "The passage does not claim the Gutenberg Bible was the first European printed book, only Gutenberg's masterpiece." },
        { number: 10, type: "true_false_not_given", text: "Gutenberg used a water-based ink for his printing system.", correctAnswer: "FALSE", explanation: "The passage says he used 'an oil-based ink,' not water-based." },
        { number: 11, type: "true_false_not_given", text: "Lithography was invented in Germany.", correctAnswer: "NOT GIVEN", explanation: "The passage mentions Alois Senefelder developed lithography in 1796 but does not specify the country." },
        { number: 12, type: "true_false_not_given", text: "Offset printing can print on various types of surfaces.", correctAnswer: "TRUE", explanation: "The passage says offset printing is 'prized for its ability to print on a wide range of surfaces.'" },
        { number: 13, type: "true_false_not_given", text: "Digital printing was first developed in the early twentieth century.", correctAnswer: "FALSE", explanation: "The passage says digital printing was introduced 'in the late twentieth century.'" },
      ],
    },
    {
      title: "Plastic Recycling Methods",
      text: `A. Plastic has become one of the most ubiquitous materials in modern life. Global plastic production has grown from approximately 2 million tonnes in 1950 to over 400 million tonnes per year today, and cumulative production since the mid-twentieth century has exceeded 10 billion tonnes. Plastics offer remarkable versatility, durability, and low cost, making them indispensable in packaging, construction, healthcare, electronics, and transportation. However, the same properties that make plastics so useful — particularly their resistance to degradation — also make them a major environmental problem. An estimated 79 percent of all plastic ever produced has ended up in landfills or the natural environment, where it can persist for hundreds of years, polluting soils, waterways, and oceans.

B. Mechanical recycling is the most established and widely practised method of plastic recycling. The process involves collecting, sorting, cleaning, shredding, and melting plastic waste into pellets or flakes that can be used as raw material for manufacturing new products. The most commonly mechanically recycled plastics are PET (polyethylene terephthalate), used in beverage bottles, and HDPE (high-density polyethylene), used in milk jugs and detergent containers. However, mechanical recycling has significant limitations: plastics degrade in quality each time they are reprocessed, a phenomenon known as "downcycling," which means that mechanically recycled material is typically used for lower-value applications rather than being returned to its original use. Contamination — the mixing of different plastic types or the presence of food residue, labels, and adhesives — further reduces the quality of recycled output and increases processing costs.

C. Chemical recycling, also known as advanced recycling, encompasses a range of technologies that break plastic waste down to its molecular building blocks, which can then be reassembled into new, virgin-quality plastic or converted into other chemical products. The three main chemical recycling processes are pyrolysis, which uses heat in the absence of oxygen to decompose plastics into oils and gases; gasification, which converts plastic into synthesis gas (syngas) that can be used as a fuel or feedstock for chemical production; and depolymerisation, which reverses the chemical reaction by which plastics are formed, breaking polymers back into their original monomers. Chemical recycling can handle mixed, contaminated, and multi-layer plastics that are unsuitable for mechanical recycling, and in principle can produce output of equivalent quality to virgin material, enabling true "closed-loop" recycling. However, chemical recycling technologies are currently more expensive and energy-intensive than mechanical recycling, and their environmental benefits are debated.

D. Biodegradable and compostable plastics are often presented as an alternative to conventional plastics that could reduce the accumulation of plastic waste in the environment. Biodegradable plastics are designed to break down through the action of naturally occurring microorganisms, while compostable plastics meet specific standards for decomposition within a defined timeframe under controlled composting conditions. Polylactic acid (PLA), derived from corn starch or sugarcane, is one of the most widely used compostable plastics, commonly found in food packaging and disposable cutlery. However, critics point out that most biodegradable and compostable plastics do not decompose readily in natural environments such as oceans or landfills; they require the high temperatures and microbial activity found in industrial composting facilities, which are not widely available in many regions. Furthermore, the mixing of biodegradable plastics with conventional plastics in recycling streams can contaminate and reduce the quality of recycled output.

E. Extended Producer Responsibility (EPR) schemes are policy frameworks that shift the financial and operational responsibility for managing plastic waste from municipalities and taxpayers to the companies that produce and sell plastic products and packaging. Under EPR schemes, producers are required to fund the collection, sorting, and recycling of the packaging they place on the market, creating an economic incentive to design products that are easier to recycle, use less material, and incorporate recycled content. EPR schemes for packaging have been implemented in over 50 countries, with the European Union's Packaging and Packaging Waste Directive being one of the most comprehensive. Evidence suggests that EPR schemes can significantly increase recycling rates: Germany's Green Dot system, one of the oldest EPR programmes, has helped achieve packaging recycling rates of over 65 percent.

F. Despite the growing range of recycling technologies and policy interventions, the global plastic recycling rate remains stubbornly low — approximately 9 percent of all plastic ever produced has been recycled. Increasing this rate will require a combination of improved collection and sorting infrastructure, investment in advanced recycling technologies, stronger regulatory frameworks, and fundamental changes in product design and consumer behaviour. The concept of a "circular economy" for plastics — in which plastic materials are kept in use for as long as possible, then recovered and regenerated at the end of their service life — offers a compelling vision, but realising it at scale remains one of the most formidable environmental challenges of the twenty-first century.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Paragraph B", options: ["i. Policy frameworks to make producers accountable", "ii. The traditional method of reprocessing plastic waste", "iii. Breaking plastics down to their chemical components", "iv. Plastics designed to decompose naturally", "v. The scale of global plastic production and waste", "vi. The low global rate of plastic recycling", "vii. The circular economy concept for plastics", "viii. Government subsidies for recycling programmes"], correctAnswer: "ii", explanation: "Paragraph B describes mechanical recycling — the traditional method of sorting, shredding, and melting plastic." },
        { number: 15, type: "matching_headings", text: "Paragraph C", options: ["i. Policy frameworks to make producers accountable", "ii. The traditional method of reprocessing plastic waste", "iii. Breaking plastics down to their chemical components", "iv. Plastics designed to decompose naturally", "v. The scale of global plastic production and waste", "vi. The low global rate of plastic recycling", "vii. The circular economy concept for plastics", "viii. Government subsidies for recycling programmes"], correctAnswer: "iii", explanation: "Paragraph C describes chemical recycling including pyrolysis, gasification, and depolymerisation." },
        { number: 16, type: "matching_headings", text: "Paragraph D", options: ["i. Policy frameworks to make producers accountable", "ii. The traditional method of reprocessing plastic waste", "iii. Breaking plastics down to their chemical components", "iv. Plastics designed to decompose naturally", "v. The scale of global plastic production and waste", "vi. The low global rate of plastic recycling", "vii. The circular economy concept for plastics", "viii. Government subsidies for recycling programmes"], correctAnswer: "iv", explanation: "Paragraph D discusses biodegradable and compostable plastics designed to break down." },
        { number: 17, type: "matching_headings", text: "Paragraph E", options: ["i. Policy frameworks to make producers accountable", "ii. The traditional method of reprocessing plastic waste", "iii. Breaking plastics down to their chemical components", "iv. Plastics designed to decompose naturally", "v. The scale of global plastic production and waste", "vi. The low global rate of plastic recycling", "vii. The circular economy concept for plastics", "viii. Government subsidies for recycling programmes"], correctAnswer: "i", explanation: "Paragraph E describes EPR schemes that shift responsibility to producers." },
        { number: 18, type: "matching_headings", text: "Paragraph F", options: ["i. Policy frameworks to make producers accountable", "ii. The traditional method of reprocessing plastic waste", "iii. Breaking plastics down to their chemical components", "iv. Plastics designed to decompose naturally", "v. The scale of global plastic production and waste", "vi. The low global rate of plastic recycling", "vii. The circular economy concept for plastics", "viii. Government subsidies for recycling programmes"], correctAnswer: "vi", explanation: "Paragraph F highlights that only 9% of plastic has been recycled and discusses the challenges ahead." },
        { number: 19, type: "table_completion", text: "Global plastic production has grown to over _______ million tonnes per year.", correctAnswer: "400", explanation: "The passage states 'over 400 million tonnes per year today.'" },
        { number: 20, type: "table_completion", text: "An estimated _______ percent of all plastic produced has ended up in landfills or the environment.", correctAnswer: "79", explanation: "The passage says 'An estimated 79 percent.'" },
        { number: 21, type: "table_completion", text: "The degradation of plastic quality through repeated recycling is called _______.", correctAnswer: "downcycling", explanation: "The passage defines this as 'downcycling.'" },
        { number: 22, type: "table_completion", text: "PLA is commonly derived from corn starch or _______.", correctAnswer: "sugarcane", explanation: "The passage says 'derived from corn starch or sugarcane.'" },
        { number: 23, type: "table_completion", text: "EPR schemes for packaging have been implemented in over _______ countries.", correctAnswer: "50", explanation: "The passage states 'implemented in over 50 countries.'" },
        { number: 24, type: "table_completion", text: "Germany's Green Dot system has achieved packaging recycling rates of over _______ percent.", correctAnswer: "65", explanation: "The passage says 'recycling rates of over 65 percent.'" },
        { number: 25, type: "table_completion", text: "Only approximately _______ percent of all plastic ever produced has been recycled.", correctAnswer: "9", explanation: "The passage states 'approximately 9 percent.'" },
        { number: 26, type: "table_completion", text: "Cumulative plastic production since the mid-twentieth century has exceeded _______ billion tonnes.", correctAnswer: "10", explanation: "The passage says 'cumulative production has exceeded 10 billion tonnes.'" },
      ],
    },
    {
      title: "Nanotechnology Applications",
      text: `Nanotechnology — the manipulation of matter at the atomic and molecular scale, typically involving structures between 1 and 100 nanometres in size — is a rapidly advancing field with the potential to transform virtually every sector of industry and human life. To put the nanoscale in perspective, a nanometre is one billionth of a metre; a human hair is approximately 80,000 nanometres wide, and a single gold atom is about one-third of a nanometre in diameter. At this scale, materials can exhibit properties fundamentally different from those of their bulk counterparts, opening up extraordinary possibilities for innovation.

A. In medicine, nanotechnology is enabling the development of targeted drug delivery systems that can transport therapeutic agents directly to diseased cells while sparing healthy tissue. Nanoparticles — tiny capsules made of materials such as lipids, polymers, or metals — can be engineered to recognise and bind to specific cell surface markers, releasing their drug payload only when they reach the target site. This approach has shown particular promise in cancer treatment, where conventional chemotherapy drugs are notoriously toxic because they kill healthy cells along with cancerous ones. Liposomal nanoparticles, which encapsulate drugs in a lipid bilayer, have been approved for the treatment of several cancers, and lipid nanoparticles (LNPs) were the delivery vehicle for the mRNA COVID-19 vaccines developed by Pfizer-BioNTech and Moderna, enabling the successful delivery of fragile mRNA molecules into human cells. Diagnostic nanosensors capable of detecting biomarkers at extremely low concentrations are also being developed, with the potential to enable early detection of diseases such as cancer and Alzheimer's at stages when treatment is most effective.

B. The electronics industry has been at the forefront of nanotechnology for decades, driven by the relentless miniaturisation of semiconductor devices predicted by Moore's Law. Modern computer processors contain transistors with feature sizes as small as 3 nanometres, enabling billions of transistors to be packed onto a single chip. Beyond conventional silicon-based electronics, researchers are exploring nanomaterials such as carbon nanotubes, graphene, and quantum dots for next-generation computing, sensing, and display technologies. Graphene — a single layer of carbon atoms arranged in a hexagonal lattice — is the strongest material ever measured, an excellent conductor of electricity and heat, and nearly transparent, making it a candidate for applications ranging from flexible electronics and ultra-fast transistors to transparent conductive coatings and water filtration membranes.

C. Nanotechnology is making significant contributions to energy technology. Nanostructured materials are being used to improve the efficiency of solar cells: quantum dots, for example, can be tuned to absorb different wavelengths of light by varying their size, potentially enabling solar cells that capture a wider spectrum of solar energy than conventional silicon-based cells. In battery technology, nanostructured electrodes and electrolytes offer the prospect of batteries with higher energy density, faster charging rates, and longer cycle life. Nanocatalysts — catalytic particles with extremely high surface-area-to-volume ratios — are improving the efficiency of fuel cells and the production of hydrogen through water splitting, contributing to the development of clean energy technologies.

D. Environmental applications of nanotechnology include water purification, air filtration, and soil remediation. Nanofiltration membranes with precisely controlled pore sizes can remove bacteria, viruses, heavy metals, and organic pollutants from water with high efficiency and low energy consumption. Iron nanoparticles have been used in groundwater remediation to neutralise contaminants such as chlorinated solvents and heavy metals through chemical reduction reactions. Nano-enabled sensors can detect environmental pollutants at parts-per-billion concentrations, enabling more precise monitoring of water and air quality. Research into the use of nanoparticles for carbon capture — trapping CO2 molecules from industrial emissions or the atmosphere — is also under way, though still at an early stage.

E. The food industry is another area where nanotechnology is finding practical applications. Nano-encapsulation techniques can protect sensitive nutrients, flavours, and bioactive compounds from degradation during food processing and storage, releasing them at the point of consumption. Nano-based packaging materials with enhanced barrier properties can extend the shelf life of perishable products, reducing food waste. Nanosensors embedded in packaging can detect the presence of pathogens or the onset of spoilage, providing real-time food safety information to consumers and retailers. Titanium dioxide nanoparticles have been used as a whitening agent in foods and confectionery, though their safety has been questioned, and the European Union banned their use in food products in 2022.

F. The rapid development of nanotechnology has outpaced the establishment of comprehensive regulatory frameworks, raising concerns about the potential health and environmental risks of engineered nanomaterials. Because nanoparticles can penetrate biological barriers — including cell membranes, the blood-brain barrier, and the lining of the lungs — that are impermeable to larger particles, there are legitimate questions about their toxicity, bioaccumulation, and long-term effects on human health and ecosystems. Studies have shown that some nanoparticles can cause inflammation, oxidative stress, and DNA damage in laboratory settings, though the relevance of these findings to real-world exposure levels is debated. International bodies including the OECD and the World Health Organization are working to develop guidelines for the safe use and regulation of nanomaterials, but harmonised global standards remain elusive.`,
      questions: [
        { number: 27, type: "matching_information", text: "The use of nanoparticles to deliver mRNA vaccines", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "A", explanation: "Paragraph A describes lipid nanoparticles as 'the delivery vehicle for the mRNA COVID-19 vaccines.'" },
        { number: 28, type: "matching_information", text: "Concerns about the toxicity of nanomaterials in living organisms", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "F", explanation: "Paragraph F discusses health risks, toxicity, inflammation, and DNA damage from nanoparticles." },
        { number: 29, type: "matching_information", text: "The use of iron particles to clean contaminated groundwater", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "D", explanation: "Paragraph D mentions 'Iron nanoparticles used in groundwater remediation.'" },
        { number: 30, type: "matching_information", text: "A ban on a nanoparticle food additive by a European authority", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "E", explanation: "Paragraph E states the EU 'banned their use in food products in 2022' regarding titanium dioxide." },
        { number: 31, type: "matching_information", text: "The properties of a material that is both the strongest ever measured and nearly transparent", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "B", explanation: "Paragraph B describes graphene as 'the strongest material ever measured' and 'nearly transparent.'" },
        { number: 32, type: "sentence_completion", text: "A nanometre is one _______ of a metre.", correctAnswer: "billionth", explanation: "The passage states 'a nanometre is one billionth of a metre.'" },
        { number: 33, type: "sentence_completion", text: "A human hair is approximately _______ nanometres wide.", correctAnswer: "80,000", explanation: "The passage says 'a human hair is approximately 80,000 nanometres wide.'" },
        { number: 34, type: "sentence_completion", text: "Modern computer processors contain transistors as small as _______ nanometres.", correctAnswer: "3", explanation: "The passage states 'feature sizes as small as 3 nanometres.'" },
        { number: 35, type: "sentence_completion", text: "Quantum dots can be tuned to absorb different wavelengths of light by varying their _______.", correctAnswer: "size", explanation: "The passage says quantum dots 'can be tuned to absorb different wavelengths of light by varying their size.'" },
        { number: 36, type: "sentence_completion", text: "Graphene consists of a single layer of _______ atoms in a hexagonal lattice.", correctAnswer: "carbon", explanation: "The passage describes graphene as 'a single layer of carbon atoms arranged in a hexagonal lattice.'" },
        { number: 37, type: "short_answer", text: "What type of nanoparticle was used to deliver COVID-19 mRNA vaccines?", correctAnswer: "lipid nanoparticles", explanation: "The passage identifies 'lipid nanoparticles (LNPs)' as the delivery vehicle." },
        { number: 38, type: "short_answer", text: "What food additive did the EU ban in 2022?", correctAnswer: "titanium dioxide nanoparticles", explanation: "The passage says 'the European Union banned their use in food products in 2022' referring to titanium dioxide." },
        { number: 39, type: "short_answer", text: "What property of nanocatalysts makes them particularly effective?", correctAnswer: "high surface-area-to-volume ratios", explanation: "The passage describes nanocatalysts as having 'extremely high surface-area-to-volume ratios.'" },
        { number: 40, type: "short_answer", text: "Name two international bodies working on nanomaterial safety guidelines.", correctAnswer: "OECD and World Health Organization", explanation: "The passage mentions 'the OECD and the World Health Organization.'" },
      ],
    },
  ],
};
