import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_49: ReadingTest = {
  id: 49,
  passages: [
    {
      title: "Marine Biology Discoveries",
      text: `The ocean covers more than seventy per cent of the Earth's surface, yet until recently, much of it remained as mysterious as outer space. Marine biology — the scientific study of organisms living in or dependent on the ocean — has undergone a remarkable transformation over the past century, propelled by technological advances that have opened previously inaccessible environments to investigation. From the discovery of hydrothermal vent ecosystems to the mapping of coral reef biodiversity, marine biology continues to reshape our understanding of life on Earth.

For centuries, scientists assumed that the deep ocean floor was a lifeless desert — too dark, too cold, and under too much pressure to support complex life. This assumption was dramatically overturned in 1977, when researchers aboard the submersible Alvin discovered thriving communities of organisms clustered around hydrothermal vents on the Galápagos Rift in the eastern Pacific Ocean. These vents, where superheated water laden with minerals gushes from cracks in the seafloor, support ecosystems based not on photosynthesis but on chemosynthesis — a process in which bacteria derive energy from chemical reactions involving hydrogen sulphide and other compounds.

The vent ecosystems proved astonishingly diverse. Giant tube worms (Riftia pachyptila), some exceeding two metres in length, harbour chemosynthetic bacteria within specialised organs called trophosomes, obtaining all their nutrition from these microbial partners. Vent crabs, shrimp, mussels, and clams have evolved unique adaptations to thrive in this extreme environment, where temperatures can exceed 400 degrees Celsius at the vent opening while surrounding water hovers near freezing. More than 700 species have been identified at hydrothermal vents worldwide, many of them found nowhere else.

Coral reefs, sometimes called the "rainforests of the sea," represent another frontier of marine biological research. Occupying less than one per cent of the ocean floor, coral reefs support approximately twenty-five per cent of all known marine species. This extraordinary biodiversity arises from the symbiotic relationship between reef-building corals and photosynthetic algae called zooxanthellae. The algae live within coral tissue, providing up to ninety per cent of the coral's energy requirements through photosynthesis while receiving shelter and nutrients in return.

However, coral reefs face unprecedented threats. Rising ocean temperatures cause coral bleaching — a stress response in which corals expel their zooxanthellae, turning white and becoming vulnerable to starvation and disease. The Great Barrier Reef has experienced mass bleaching events in 2016, 2017, 2020, and 2022, each causing widespread coral mortality. Ocean acidification, caused by the absorption of atmospheric carbon dioxide, further weakens coral skeletons by reducing the availability of carbonate ions needed for calcification.

Marine biologists have also made remarkable discoveries about the cognitive abilities of ocean animals. Octopuses, which diverged from the vertebrate lineage over 500 million years ago, demonstrate sophisticated problem-solving, tool use, and even play behaviour. Cuttlefish can change colour and texture in milliseconds for camouflage and communication. Dolphins use signature whistles that function as individual names, and recent research suggests that whale songs contain syntactic structures that may constitute a form of language.

The development of environmental DNA (eDNA) sampling has revolutionised biodiversity assessment in marine environments. Rather than physically capturing organisms, researchers can now detect species by analysing trace amounts of genetic material shed into the water through skin cells, mucus, and waste products. A single water sample can reveal the presence of dozens of species, enabling rapid and non-invasive monitoring of marine communities. This technique has proven particularly valuable for detecting rare or elusive species that traditional survey methods might miss.

Despite these advances, the ocean remains largely unexplored. Less than twenty per cent of the global seabed has been mapped at high resolution, and an estimated two-thirds of marine species remain scientifically undescribed. Deep-sea mining proposals, expanding fishing operations, and climate change continue to threaten marine ecosystems before their full ecological significance is understood. The challenge for marine biology in the coming decades is not only to document this hidden diversity but to develop conservation strategies that protect it for future generations.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "What was discovered at the Galápagos Rift in 1977?", options: ["A. New species of coral", "B. Hydrothermal vent ecosystems", "C. Ancient shipwrecks", "D. Underwater volcanoes without life"], correctAnswer: "B", explanation: "The passage describes the discovery of 'thriving communities of organisms clustered around hydrothermal vents.'" },
        { number: 2, type: "multiple_choice", text: "Giant tube worms obtain nutrition from", options: ["A. photosynthesis", "B. predation on other vent species", "C. chemosynthetic bacteria in trophosomes", "D. filtering nutrients from seawater"], correctAnswer: "C", explanation: "The passage says they 'harbour chemosynthetic bacteria within specialised organs called trophosomes.'" },
        { number: 3, type: "multiple_choice", text: "What percentage of marine species do coral reefs support?", options: ["A. One per cent", "B. Ten per cent", "C. Twenty-five per cent", "D. Fifty per cent"], correctAnswer: "C", explanation: "The passage states reefs 'support approximately twenty-five per cent of all known marine species.'" },
        { number: 4, type: "multiple_choice", text: "What is the advantage of eDNA sampling?", options: ["A. It requires capturing organisms", "B. It only works in shallow waters", "C. It detects species non-invasively from water samples", "D. It replaces the need for taxonomists"], correctAnswer: "C", explanation: "The passage says researchers 'can now detect species by analysing trace amounts of genetic material shed into the water.'" },
        { number: 5, type: "true_false_not_given", text: "Before 1977, scientists believed the deep ocean floor could support complex life.", correctAnswer: "FALSE", explanation: "The passage says scientists 'assumed that the deep ocean floor was a lifeless desert.'" },
        { number: 6, type: "true_false_not_given", text: "Over 700 species have been found at hydrothermal vents.", correctAnswer: "TRUE", explanation: "The passage states 'More than 700 species have been identified at hydrothermal vents worldwide.'" },
        { number: 7, type: "true_false_not_given", text: "Zooxanthellae provide up to ninety per cent of coral's energy.", correctAnswer: "TRUE", explanation: "The passage says they provide 'up to ninety per cent of the coral's energy requirements.'" },
        { number: 8, type: "true_false_not_given", text: "The Great Barrier Reef experienced bleaching in 2018.", correctAnswer: "NOT GIVEN", explanation: "The passage mentions 2016, 2017, 2020, and 2022, but not 2018." },
        { number: 9, type: "true_false_not_given", text: "Less than twenty per cent of the seabed has been mapped at high resolution.", correctAnswer: "TRUE", explanation: "The passage states this directly." },
        { number: 10, type: "true_false_not_given", text: "Dolphins communicate using colour changes.", correctAnswer: "FALSE", explanation: "The passage says dolphins use 'signature whistles'; it is cuttlefish that change colour." },
        { number: 11, type: "true_false_not_given", text: "An estimated two-thirds of marine species remain scientifically undescribed.", correctAnswer: "TRUE", explanation: "The passage states this directly." },
        { number: 12, type: "true_false_not_given", text: "Octopuses diverged from the vertebrate lineage 200 million years ago.", correctAnswer: "FALSE", explanation: "The passage says 'over 500 million years ago.'" },
        { number: 13, type: "true_false_not_given", text: "Deep-sea mining has already caused the extinction of several marine species.", correctAnswer: "NOT GIVEN", explanation: "The passage mentions deep-sea mining as a threat but does not say it has caused extinctions." }
      ]
    },
    {
      title: "History of Writing Systems",
      text: `A. Writing is arguably humanity's most transformative invention. Unlike speech, which vanishes the moment it is produced, writing creates a permanent record of thought — enabling communication across time and space, the accumulation of knowledge, and the administration of complex societies. The development of writing systems represents a profound cognitive achievement: the insight that spoken language can be represented by visible marks, and that these marks can be standardised, learned, and reproduced.

B. The earliest known writing system is cuneiform, which emerged in Sumer (modern-day southern Iraq) around 3400 BCE. The term "cuneiform" derives from the Latin word cuneus, meaning "wedge," describing the characteristic wedge-shaped impressions made by pressing a reed stylus into soft clay tablets. Initially, cuneiform consisted of pictographs — simplified drawings representing objects or concepts. Over time, these evolved into abstract symbols representing syllables, enabling the script to record the sounds of the Sumerian language rather than merely depicting objects.

C. Egyptian hieroglyphs developed independently around the same period. Unlike cuneiform, which was primarily used for administrative and commercial records, hieroglyphs served a broader range of functions including monumental inscriptions, religious texts, and literary compositions. The hieroglyphic system combined logographic and alphabetic elements: some symbols represented whole words, while others represented individual consonant sounds. The script remained in use for over three thousand years, with the last known hieroglyphic inscription dating to 394 CE.

D. Chinese script, which emerged around 1200 BCE during the Shang Dynasty, represents the only ancient writing system still in continuous use today. The earliest Chinese characters appear on oracle bones — animal bones and turtle shells used for divination. Like early cuneiform, Chinese characters began as pictographs but evolved into a complex logographic system in which each character represents a morpheme — a meaningful unit of language. Modern Chinese uses approximately 50,000 characters, though literacy requires knowledge of roughly 3,000 to 4,000.

E. The development of alphabetic writing — in which individual symbols represent individual speech sounds — was a revolutionary simplification. The first true alphabet is generally attributed to the Phoenicians, a seafaring people based in present-day Lebanon, around 1050 BCE. The Phoenician alphabet consisted of only twenty-two consonant symbols, making it far easier to learn than the hundreds or thousands of characters required by logographic systems. Greek scholars adapted the Phoenician alphabet around the eighth century BCE, adding symbols for vowel sounds and creating the first complete alphabetic system. The Latin alphabet, derived from the Greek via Etruscan intermediaries, became the basis for most European writing systems and is today the world's most widely used script.

F. Writing systems did not spread solely through cultural borrowing. Several civilisations developed writing independently. Mesoamerican scripts, including Maya hieroglyphs, emerged without any contact with Old World writing traditions. Maya script, which combined logographic and syllabic elements, was used to record historical events, astronomical observations, and religious rituals. The script was largely undeciphered until breakthroughs in the 1970s and 1980s revealed it to be a fully phonetic system capable of recording the Maya language.

G. The invention of the printing press in the fifteenth century and the subsequent development of digital technology have transformed the creation, distribution, and storage of written text. Yet the fundamental principle remains unchanged: the conversion of ephemeral speech into durable visible symbols. This principle, first grasped by Sumerian scribes pressing reeds into clay over five thousand years ago, continues to underpin every text message, academic paper, and legal document produced today.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Paragraph B", options: ["i. The birth of alphabetic writing", "ii. Cuneiform: the first writing system", "iii. Writing in the Americas", "iv. The enduring Chinese script", "v. Egyptian hieroglyphs and their functions", "vi. From clay tablets to digital text", "vii. Independent invention of writing"], correctAnswer: "ii", explanation: "Paragraph B discusses cuneiform as the earliest known writing system." },
        { number: 15, type: "matching_headings", text: "Paragraph D", options: ["i. The birth of alphabetic writing", "ii. Cuneiform: the first writing system", "iii. Writing in the Americas", "iv. The enduring Chinese script", "v. Egyptian hieroglyphs and their functions", "vi. From clay tablets to digital text", "vii. Independent invention of writing"], correctAnswer: "iv", explanation: "Paragraph D covers Chinese script as the only ancient system still in use." },
        { number: 16, type: "matching_headings", text: "Paragraph E", options: ["i. The birth of alphabetic writing", "ii. Cuneiform: the first writing system", "iii. Writing in the Americas", "iv. The enduring Chinese script", "v. Egyptian hieroglyphs and their functions", "vi. From clay tablets to digital text", "vii. Independent invention of writing"], correctAnswer: "i", explanation: "Paragraph E describes the development of the Phoenician and Greek alphabets." },
        { number: 17, type: "matching_headings", text: "Paragraph F", options: ["i. The birth of alphabetic writing", "ii. Cuneiform: the first writing system", "iii. Writing in the Americas", "iv. The enduring Chinese script", "v. Egyptian hieroglyphs and their functions", "vi. From clay tablets to digital text", "vii. Independent invention of writing"], correctAnswer: "vii", explanation: "Paragraph F discusses independent development of writing in Mesoamerica." },
        { number: 18, type: "sentence_completion", text: "Cuneiform emerged in Sumer around ________ BCE.", correctAnswer: "3400", explanation: "The passage states cuneiform 'emerged in Sumer around 3400 BCE.'" },
        { number: 19, type: "sentence_completion", text: "The Phoenician alphabet consisted of ________ consonant symbols.", correctAnswer: "twenty-two", explanation: "The passage says 'twenty-two consonant symbols.'" },
        { number: 20, type: "sentence_completion", text: "Greek scholars added symbols for ________ sounds to the Phoenician alphabet.", correctAnswer: "vowel", explanation: "The passage says they added 'symbols for vowel sounds.'" },
        { number: 21, type: "sentence_completion", text: "The earliest Chinese characters appear on ________ used for divination.", correctAnswer: "oracle bones", explanation: "The passage mentions 'oracle bones — animal bones and turtle shells used for divination.'" },
        { number: 22, type: "sentence_completion", text: "The last known hieroglyphic inscription dates to ________ CE.", correctAnswer: "394", explanation: "The passage states 'the last known hieroglyphic inscription dating to 394 CE.'" },
        { number: 23, type: "sentence_completion", text: "Maya script was largely undeciphered until breakthroughs in the ________ and 1980s.", correctAnswer: "1970s", explanation: "The passage says 'breakthroughs in the 1970s and 1980s.'" },
        { number: 24, type: "sentence_completion", text: "Modern Chinese uses approximately ________ characters in total.", correctAnswer: "50,000", explanation: "The passage says 'approximately 50,000 characters.'" },
        { number: 25, type: "sentence_completion", text: "The Latin alphabet was derived from Greek via ________ intermediaries.", correctAnswer: "Etruscan", explanation: "The passage says 'derived from the Greek via Etruscan intermediaries.'" },
        { number: 26, type: "sentence_completion", text: "The word cuneiform derives from the Latin word meaning ________.", correctAnswer: "wedge", explanation: "The passage says 'from the Latin word cuneus, meaning wedge.'" }
      ]
    },
    {
      title: "Social Change and Technology",
      text: `A. Technology has always been a catalyst for social change, but the pace at which digital technologies are reshaping human societies is without historical precedent. The smartphone, social media, artificial intelligence, and the internet of things are not merely tools — they are restructuring the way people work, communicate, form relationships, participate in politics, and understand themselves. Sociologists, psychologists, and political scientists are only beginning to grasp the implications.

B. The transformation of work is perhaps the most visible impact. Automation and artificial intelligence are displacing routine cognitive and manual tasks at an accelerating rate. A widely cited 2013 study by researchers at Oxford University estimated that 47 per cent of US jobs were at high risk of automation within twenty years. While subsequent analyses have revised this figure downward, the direction of change is clear: tasks that involve predictable, repetitive operations — from data entry to warehouse logistics — are increasingly performed by machines.

C. Yet technology also creates new forms of employment. The "gig economy" — in which workers perform short-term tasks or projects through digital platforms like Uber, Deliveroo, and Fiverr — has grown rapidly, offering flexibility to some workers while raising concerns about job security, benefits, and labour rights. Remote work, enabled by video conferencing and cloud computing, expanded dramatically during the COVID-19 pandemic and has become a permanent feature of many industries. These developments are blurring traditional boundaries between work and personal life, office and home, employer and independent contractor.

D. Social media has fundamentally altered human communication. Platforms like Facebook, Twitter, Instagram, and TikTok enable instant sharing of information, opinions, and creative content with global audiences. They have empowered social movements — from the Arab Spring to Black Lives Matter — by providing tools for organisation and amplification that bypass traditional media gatekeepers. However, these same platforms have been criticised for facilitating the spread of misinformation, enabling harassment, and contributing to political polarisation through algorithmic echo chambers that reinforce existing beliefs.

E. The effects on mental health, particularly among young people, have become a major focus of research and public concern. Studies have found correlations between heavy social media use and increased rates of anxiety, depression, and loneliness among adolescents. The mechanisms are debated — potential factors include social comparison, cyberbullying, sleep disruption from screen use, and the addictive design of platform interfaces optimised for engagement. Several countries have considered or implemented age restrictions on social media use in response to these findings.

F. Privacy and surveillance represent another critical dimension of technology-driven social change. The business model of major technology companies depends on collecting, analysing, and monetising vast quantities of personal data. Smartphones track location continuously; smart speakers record conversations; fitness trackers monitor health metrics. Governments, too, have expanded digital surveillance capabilities, from facial recognition systems in public spaces to the monitoring of online communications. The resulting tension between security and civil liberties is one of the defining political debates of the digital age.

G. Education is being transformed by technology in ways both promising and troubling. Online learning platforms have made educational content accessible to millions who lack access to traditional institutions. Artificial intelligence enables personalised instruction tailored to individual learning styles and pace. However, the digital divide — the gap between those with reliable internet access and digital literacy and those without — risks exacerbating existing educational inequalities rather than reducing them.

H. The long-term social consequences of current technological changes remain deeply uncertain. Optimists point to the potential for technology to solve pressing problems — climate change, disease, poverty — through innovation and efficiency gains. Pessimists warn of mass unemployment, social fragmentation, and the erosion of democratic institutions under the influence of unaccountable technology corporations. The most likely outcome lies between these extremes, shaped by the policy choices, institutional adaptations, and collective decisions that societies make in the coming decades.`,
      questions: [
        { number: 27, type: "matching_information", text: "Statistics on the proportion of jobs at risk from automation", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "B", explanation: "Paragraph B cites the Oxford study estimating 47% of US jobs at risk." },
        { number: 28, type: "matching_information", text: "The role of social media in political movements", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "D", explanation: "Paragraph D discusses social movements like the Arab Spring and Black Lives Matter." },
        { number: 29, type: "matching_information", text: "Concerns about the gap in access to digital technology", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "G", explanation: "Paragraph G discusses the digital divide." },
        { number: 30, type: "matching_information", text: "The collection of personal data by technology companies", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "F", explanation: "Paragraph F discusses privacy and data collection." },
        { number: 31, type: "summary_completion", text: "The Oxford study estimated that ________ per cent of US jobs were at high risk of automation.", correctAnswer: "47", explanation: "The passage states '47 per cent of US jobs.'" },
        { number: 32, type: "summary_completion", text: "The gig economy uses digital ________ like Uber and Fiverr.", correctAnswer: "platforms", explanation: "The passage says 'digital platforms like Uber, Deliveroo, and Fiverr.'" },
        { number: 33, type: "summary_completion", text: "Several countries have considered age ________ on social media use.", correctAnswer: "restrictions", explanation: "The passage says 'age restrictions on social media use.'" },
        { number: 34, type: "summary_completion", text: "Facial recognition systems represent expanded government ________ capabilities.", correctAnswer: "surveillance", explanation: "The passage discusses 'digital surveillance capabilities' including facial recognition." },
        { number: 35, type: "short_answer", text: "What type of economy involves short-term tasks through digital platforms?", correctAnswer: "gig economy", explanation: "The passage defines 'The gig economy.'" },
        { number: 36, type: "short_answer", text: "Name two social movements mentioned that were empowered by social media.", correctAnswer: "Arab Spring and Black Lives Matter", explanation: "The passage mentions both movements." },
        { number: 37, type: "short_answer", text: "What global event accelerated the expansion of remote work?", correctAnswer: "COVID-19 pandemic", explanation: "The passage says remote work 'expanded dramatically during the COVID-19 pandemic.'" },
        { number: 38, type: "short_answer", text: "What does AI enable in education that is tailored to individuals?", correctAnswer: "personalised instruction", explanation: "The passage says AI enables 'personalised instruction.'" },
        { number: 39, type: "short_answer", text: "What design feature of platforms contributes to addictive use?", correctAnswer: "engagement", explanation: "The passage mentions 'addictive design of platform interfaces optimised for engagement.'" },
        { number: 40, type: "short_answer", text: "What is the term for the gap between those with and without internet access?", correctAnswer: "digital divide", explanation: "The passage defines 'the digital divide.'" }
      ]
    }
  ]
};
