import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_18: ReadingTest = {
  id: 18,
  passages: [
    {
      title: "Early Aviation History",
      text: `The dream of human flight stretches back to the earliest myths and legends of antiquity, but it was not until the late eighteenth century that humans first took to the skies, and not until the early twentieth century that powered, heavier-than-air flight became a reality. The story of aviation's development is one of persistent experimentation, daring risk-taking, and incremental engineering advances that ultimately transformed the world.

The first successful human flights were achieved not in aeroplanes but in balloons. On 21 November 1783, Jean-François Pilâtre de Rozier and the Marquis d'Arlandes made the first untethered manned balloon flight in a hot-air balloon designed by the Montgolfier brothers, Joseph-Michel and Jacques-Étienne. The balloon rose to an altitude of approximately 150 metres and flew for about 25 minutes over Paris, covering a distance of nine kilometres. Just ten days later, the physicist Jacques Charles and Nicolas-Louis Robert made the first flight in a hydrogen-filled balloon, reaching an altitude of approximately 550 metres. These early balloon flights captured the public imagination across Europe and demonstrated that human flight was possible, though balloons were inherently limited by their inability to be steered against the wind.

Throughout the nineteenth century, inventors and engineers worked to develop dirigibles — steerable, powered lighter-than-air craft — and to understand the principles of heavier-than-air flight. Sir George Cayley, an English baronet often called the "father of aeronautics," identified the four forces acting on a flying machine — lift, weight, thrust, and drag — and built and flew the first successful glider in 1853, reportedly carrying his coachman across a small valley. Otto Lilienthal, a German engineer, made over 2,000 glider flights between 1891 and 1896, carefully documenting his observations of wing shapes and air currents. Lilienthal's work was widely published and profoundly influenced the Wright brothers, who acknowledged him as their primary inspiration.

Orville and Wilbur Wright, bicycle mechanics from Dayton, Ohio, achieved the first sustained, controlled, powered heavier-than-air flight on 17 December 1903 at Kitty Hawk, North Carolina. Their aircraft, the Wright Flyer, was powered by a custom-built 12-horsepower petrol engine and featured a biplane design with a wingspan of 12.3 metres. The first flight lasted just 12 seconds and covered 37 metres; by the fourth flight of the day, Wilbur kept the aircraft aloft for 59 seconds over a distance of 260 metres. The Wrights' key innovation was their system of wing warping, which allowed the pilot to control the aircraft's roll by twisting the wings, combined with a movable rudder for yaw control — a three-axis control system that remains the fundamental basis of aircraft control today.

The years following the Wright brothers' breakthrough saw rapid advances in aircraft design, performance, and application. Louis Blériot's crossing of the English Channel in a monoplane in July 1909 demonstrated that aircraft could travel significant distances over open water. The First World War (1914–1918) accelerated aviation development enormously, as military requirements drove improvements in speed, altitude, reliability, and armament. By the end of the war, aircraft had evolved from fragile, slow machines capable of little more than reconnaissance into robust fighters and bombers with speeds exceeding 200 kilometres per hour.

The interwar period (1918–1939) witnessed the emergence of commercial aviation. The world's first scheduled commercial airline service began in 1914, operating a short route across Tampa Bay in Florida using a single-engine flying boat. By the 1930s, airlines such as Pan American, Imperial Airways, and Lufthansa were operating long-distance routes using large multi-engine aircraft such as the Douglas DC-3, which could carry 21 passengers at a cruising speed of 300 kilometres per hour. The DC-3 is widely regarded as the aircraft that made commercial aviation economically viable, and over 16,000 were built, many serving as military transports during the Second World War.

The introduction of jet propulsion revolutionised aviation after 1945. The first commercial jet airliner, the de Havilland Comet, entered service in 1952, followed by the Boeing 707 in 1958. Jet aircraft offered dramatically higher speeds, greater range, and smoother high-altitude flight than their piston-engine predecessors, making intercontinental travel routine for the first time. The Boeing 747, which entered service in 1970 with a capacity of over 400 passengers, ushered in the era of mass air travel, driving down ticket prices and making flying accessible to millions of people who had never before been able to afford it.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "The first untethered manned balloon flight took place in", options: ["A 1770.", "B 1783.", "C 1803.", "D 1853."], correctAnswer: "B", explanation: "The passage states the flight was 'On 21 November 1783.'" },
        { number: 2, type: "multiple_choice", text: "Sir George Cayley is known as the 'father of aeronautics' because he", options: ["A built the first powered aeroplane.", "B invented the hot-air balloon.", "C identified the four forces of flight and built the first glider.", "D designed the first commercial aircraft."], correctAnswer: "C", explanation: "The passage says Cayley 'identified the four forces' and 'built and flew the first successful glider.'" },
        { number: 3, type: "multiple_choice", text: "The Wright brothers' most important technical innovation was", options: ["A a more powerful engine than any previously built.", "B a system for controlling the aircraft in three axes.", "C the use of a monoplane wing design.", "D the ability to take off from water."], correctAnswer: "B", explanation: "The passage says their key innovation was 'a three-axis control system' using wing warping and a movable rudder." },
        { number: 4, type: "multiple_choice", text: "The Douglas DC-3 is considered historically important because it", options: ["A was the first aircraft to cross the Atlantic.", "B made commercial aviation economically viable.", "C was the first jet-powered airliner.", "D could carry more than 100 passengers."], correctAnswer: "B", explanation: "The passage says the DC-3 'is widely regarded as the aircraft that made commercial aviation economically viable.'" },
        { number: 5, type: "multiple_choice", text: "The Boeing 747 transformed air travel by", options: ["A introducing supersonic flight.", "B reducing the need for airports.", "C making flying affordable for millions of people.", "D using electric propulsion."], correctAnswer: "C", explanation: "The passage says the 747 drove 'down ticket prices and making flying accessible to millions.'" },
        { number: 6, type: "sentence_completion", text: "The first hot-air balloon was designed by the _______ brothers.", correctAnswer: "Montgolfier", explanation: "The passage says 'a hot-air balloon designed by the Montgolfier brothers.'" },
        { number: 7, type: "sentence_completion", text: "Otto Lilienthal made over _______ glider flights.", correctAnswer: "2,000", explanation: "The passage states 'over 2,000 glider flights.'" },
        { number: 8, type: "sentence_completion", text: "The Wright Flyer had a wingspan of _______ metres.", correctAnswer: "12.3", explanation: "The passage says 'a wingspan of 12.3 metres.'" },
        { number: 9, type: "sentence_completion", text: "The Wright Flyer's engine produced _______ horsepower.", correctAnswer: "12", explanation: "The passage states 'a custom-built 12-horsepower petrol engine.'" },
        { number: 10, type: "sentence_completion", text: "Louis Blériot crossed the English Channel in _______.", correctAnswer: "1909", explanation: "The passage says 'in July 1909.'" },
        { number: 11, type: "sentence_completion", text: "The DC-3 could carry _______ passengers.", correctAnswer: "21", explanation: "The passage states 'carry 21 passengers.'" },
        { number: 12, type: "sentence_completion", text: "The first commercial jet airliner was the de Havilland _______.", correctAnswer: "Comet", explanation: "The passage names 'the de Havilland Comet.'" },
        { number: 13, type: "sentence_completion", text: "The Boeing 747 could carry over _______ passengers.", correctAnswer: "400", explanation: "The passage says 'a capacity of over 400 passengers.'" },
      ],
    },
    {
      title: "Urban Housing Development",
      text: `A. The provision of adequate, affordable housing is one of the most pressing challenges facing cities around the world. Rapid urbanisation, population growth, rising land and construction costs, and widening income inequality have combined to create housing crises in cities as diverse as London, New York, Mumbai, Lagos, and Sydney. The United Nations estimates that approximately 1.6 billion people currently live in inadequate housing conditions globally, and that by 2030, an additional 3 billion people — roughly 40 percent of the world's population — will need access to adequate and affordable housing, requiring the construction of 96,000 new housing units per day.

B. The history of urban housing policy has been shaped by successive waves of ideology and experimentation. In the post-Second World War era, many governments in Europe, North America, and Asia embarked on massive public housing programmes, constructing large estates of social housing to address wartime destruction and accommodate growing urban populations. In Britain, the Housing Act of 1949 expanded the scope of council housing, and by the mid-1970s, approximately one-third of all British households lived in publicly owned dwellings. Similar programmes were implemented in France (the grands ensembles), Sweden (the Million Programme), and Singapore (the Housing and Development Board), which today houses approximately 80 percent of the city-state's population in publicly built apartments.

C. From the 1980s onwards, many countries shifted away from direct government provision of housing towards market-based approaches, deregulating housing markets, reducing public housing investment, and promoting homeownership through subsidies, tax incentives, and the liberalisation of mortgage lending. The privatisation of public housing stock — exemplified by Britain's Right to Buy policy, introduced in 1980, which allowed council tenants to purchase their homes at discounted prices — transferred millions of dwellings from public to private ownership. While these policies expanded homeownership for many families, they also contributed to a reduction in the supply of affordable rental housing and, in some cases, fuelled speculative housing bubbles that culminated in financial crises, most notably the US subprime mortgage crisis of 2007–2008.

D. The affordability of housing is typically measured by the ratio of house prices or rents to household income. A commonly used benchmark holds that housing is affordable when it costs no more than 30 percent of gross household income. By this measure, housing has become increasingly unaffordable in many cities: in London, the average house price is approximately 12 times the average annual salary; in Hong Kong, the ratio exceeds 20; and even in cities with historically more affordable markets, such as Dublin and Auckland, prices have risen sharply in recent years. The causes of housing unaffordability are complex and include restrictive land-use regulations that limit new construction, insufficient investment in public and social housing, the financialisation of housing (treating residential property as an investment asset), low interest rates that inflate property values, and the growth of short-term rental platforms that reduce the supply of long-term rental housing.

E. Innovative approaches to housing construction are emerging in response to the affordability and sustainability challenges. Modular and prefabricated construction — in which building components are manufactured off-site in factory conditions and assembled on-site — can reduce construction time by 30 to 50 percent and costs by 10 to 20 percent compared with traditional methods, while improving quality control and reducing waste. 3D-printed housing, in which structures are built layer by layer using large-scale concrete printers, has demonstrated the ability to construct a basic dwelling in as little as 24 hours at a fraction of conventional costs. Mass timber construction, using engineered wood products such as cross-laminated timber (CLT), offers a sustainable alternative to steel and concrete, sequestering carbon rather than emitting it and enabling the construction of buildings up to 18 storeys tall.

F. The concept of inclusive housing policy — ensuring that housing systems serve the needs of all residents, including low-income households, the elderly, people with disabilities, and marginalised communities — is gaining traction in urban planning discourse. Inclusionary zoning policies, which require private developers to include a proportion of affordable units in new residential developments, have been adopted in cities including New York, San Francisco, London, and Sydney. Community land trusts (CLTs), which acquire and hold land in trust for the benefit of the community, removing it from the speculative market and ensuring permanent affordability, are growing in number in the United States, Britain, and Belgium. Co-housing and cooperative housing models, in which residents collectively own and manage their housing, offer alternatives to both market-rate and traditional social housing. Ultimately, addressing the global housing crisis will require a combination of increased public investment, progressive regulation, innovative construction methods, and a fundamental shift in the way societies view housing — not primarily as a financial asset, but as a basic human right.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Paragraph B", options: ["i. New construction technologies and methods", "ii. The shift towards market-driven housing policies", "iii. Government-led housing programmes after 1945", "iv. Ensuring housing serves all community members", "v. The growing global housing shortage", "vi. Measuring and understanding housing costs", "vii. The environmental impact of housing construction", "viii. The role of private developers in social housing"], correctAnswer: "iii", explanation: "Paragraph B describes post-WWII public housing programmes in Britain, France, Sweden, and Singapore." },
        { number: 15, type: "matching_headings", text: "Paragraph C", options: ["i. New construction technologies and methods", "ii. The shift towards market-driven housing policies", "iii. Government-led housing programmes after 1945", "iv. Ensuring housing serves all community members", "v. The growing global housing shortage", "vi. Measuring and understanding housing costs", "vii. The environmental impact of housing construction", "viii. The role of private developers in social housing"], correctAnswer: "ii", explanation: "Paragraph C discusses deregulation, Right to Buy, and market-based approaches from the 1980s." },
        { number: 16, type: "matching_headings", text: "Paragraph D", options: ["i. New construction technologies and methods", "ii. The shift towards market-driven housing policies", "iii. Government-led housing programmes after 1945", "iv. Ensuring housing serves all community members", "v. The growing global housing shortage", "vi. Measuring and understanding housing costs", "vii. The environmental impact of housing construction", "viii. The role of private developers in social housing"], correctAnswer: "vi", explanation: "Paragraph D discusses price-to-income ratios and the causes of unaffordability." },
        { number: 17, type: "matching_headings", text: "Paragraph E", options: ["i. New construction technologies and methods", "ii. The shift towards market-driven housing policies", "iii. Government-led housing programmes after 1945", "iv. Ensuring housing serves all community members", "v. The growing global housing shortage", "vi. Measuring and understanding housing costs", "vii. The environmental impact of housing construction", "viii. The role of private developers in social housing"], correctAnswer: "i", explanation: "Paragraph E discusses modular construction, 3D printing, and mass timber." },
        { number: 18, type: "matching_headings", text: "Paragraph F", options: ["i. New construction technologies and methods", "ii. The shift towards market-driven housing policies", "iii. Government-led housing programmes after 1945", "iv. Ensuring housing serves all community members", "v. The growing global housing shortage", "vi. Measuring and understanding housing costs", "vii. The environmental impact of housing construction", "viii. The role of private developers in social housing"], correctAnswer: "iv", explanation: "Paragraph F discusses inclusionary zoning, CLTs, co-housing — ensuring housing for all." },
        { number: 19, type: "summary_completion", text: "By 2030, approximately _______ billion additional people will need adequate housing.", correctAnswer: "3", explanation: "The passage says 'an additional 3 billion people.'" },
        { number: 20, type: "summary_completion", text: "Addressing housing needs would require building _______ new units per day.", correctAnswer: "96,000", explanation: "The passage states 'requiring the construction of 96,000 new housing units per day.'" },
        { number: 21, type: "summary_completion", text: "Singapore's HDB houses approximately _______ percent of the population.", correctAnswer: "80", explanation: "The passage says 'approximately 80 percent of the city-state's population.'" },
        { number: 22, type: "summary_completion", text: "Housing is considered affordable when it costs no more than _______ percent of income.", correctAnswer: "30", explanation: "The passage states 'no more than 30 percent of gross household income.'" },
        { number: 23, type: "summary_completion", text: "In Hong Kong, the house price to salary ratio exceeds _______.", correctAnswer: "20", explanation: "The passage says 'the ratio exceeds 20.'" },
        { number: 24, type: "summary_completion", text: "Modular construction can reduce building time by _______ to 50 percent.", correctAnswer: "30", explanation: "The passage states 'reduce construction time by 30 to 50 percent.'" },
        { number: 25, type: "summary_completion", text: "3D-printed housing can construct a basic dwelling in as little as _______ hours.", correctAnswer: "24", explanation: "The passage says 'in as little as 24 hours.'" },
        { number: 26, type: "summary_completion", text: "Mass timber buildings can reach up to _______ storeys tall.", correctAnswer: "18", explanation: "The passage states 'buildings up to 18 storeys tall.'" },
      ],
    },
    {
      title: "Digital Technology and Society",
      text: `Digital technology has fundamentally reshaped nearly every aspect of human society in the span of just a few decades. The proliferation of the internet, smartphones, social media, cloud computing, and artificial intelligence has transformed the way people communicate, work, learn, shop, govern, and relate to one another. While the benefits of the digital revolution are substantial and widely acknowledged, it has also created new challenges — including threats to privacy, the spread of misinformation, digital inequality, and the disruption of established economic structures — that societies are still struggling to address.

A. The internet, which grew from a specialised academic and military network in the 1960s to a global communications infrastructure connecting over 5.3 billion users by 2023, has been the foundational technology of the digital age. The development of the World Wide Web by Tim Berners-Lee in 1989 made the internet accessible to non-technical users for the first time, enabling the creation of websites, email, and online commerce. The subsequent emergence of broadband connectivity, Wi-Fi, and mobile internet transformed the internet from a tool primarily used at desktop computers into an always-on, always-available utility accessed through smartphones, tablets, and an expanding universe of connected devices — a phenomenon known as the Internet of Things (IoT). By 2025, it is estimated that the number of IoT-connected devices worldwide will exceed 75 billion.

B. Social media platforms have profoundly altered the dynamics of human communication and public discourse. Facebook (now Meta), launched in 2004, has grown to over 3 billion monthly active users; YouTube hosts over 800 million videos; and TikTok, launched internationally in 2017, reached 1 billion users faster than any platform in history. Social media has empowered individuals to share information, organise communities, and hold institutions to account, playing pivotal roles in social movements such as the Arab Spring and Black Lives Matter. However, social media has also been criticised for amplifying misinformation, enabling cyberbullying and harassment, fostering political polarisation, and creating addictive patterns of use linked to declining mental health, particularly among adolescents.

C. The digital economy has created enormous wealth and transformed traditional industries, but its benefits have been unevenly distributed. The combined market capitalisation of the five largest technology companies — Apple, Microsoft, Alphabet (Google), Amazon, and Meta — exceeded $10 trillion by 2023, making them among the most valuable entities in human history. The gig economy, enabled by digital platforms such as Uber, DoorDash, and Fiverr, has created flexible work opportunities for millions but has also been criticised for offering low pay, few benefits, and limited job security. The automation of routine cognitive and manual tasks through AI and robotics threatens to displace workers in sectors ranging from manufacturing and transport to customer service and data entry, raising urgent questions about the future of work and the need for educational reform and social safety nets.

D. Digital governance and e-government services are transforming the relationship between citizens and the state. Estonia has established itself as a global leader in digital governance, offering over 99 percent of government services online, including voting, tax filing, company registration, and healthcare prescriptions. Digital identity systems enable citizens to access services securely, while blockchain-based systems ensure the integrity and transparency of government records. However, the digitisation of government services also raises concerns about cybersecurity, data protection, and the exclusion of citizens who lack digital literacy or internet access. The European Union's General Data Protection Regulation (GDPR), implemented in 2018, has become a global benchmark for data privacy legislation, establishing principles such as the right to be forgotten, data portability, and the requirement for explicit consent before personal data can be collected or processed.

E. The impact of digital technology on education has been accelerated dramatically by the COVID-19 pandemic, which forced schools and universities worldwide to shift to online learning. While digital education tools offer significant advantages — including access to vast repositories of knowledge, personalised learning experiences, and the ability to connect students with teachers and peers across geographic boundaries — the pandemic also exposed stark inequalities in access to technology and connectivity. An estimated 1.3 billion students worldwide lacked internet access at home during the pandemic, and many more lacked the devices, quiet study spaces, or parental support needed to learn effectively online. The challenge of the "digital divide" — the gap between those who have access to digital technology and those who do not — remains one of the most critical issues in ensuring that the benefits of the digital revolution are shared equitably.

F. Looking ahead, emerging technologies such as quantum computing, extended reality (XR), brain-computer interfaces, and advanced AI systems promise to deepen the integration of digital technology into every facet of human life. Quantum computers, which harness the principles of quantum mechanics to perform calculations exponentially faster than classical computers, could revolutionise fields from drug discovery and materials science to cryptography and climate modelling. Extended reality technologies — encompassing virtual reality (VR), augmented reality (AR), and mixed reality (MR) — are creating immersive digital experiences for entertainment, education, training, and remote collaboration. The responsible development and governance of these technologies will be among the defining challenges of the coming decades.`,
      questions: [
        { number: 27, type: "matching_information", text: "A country that offers nearly all government services digitally", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "D", explanation: "Paragraph D describes Estonia offering 'over 99 percent of government services online.'" },
        { number: 28, type: "matching_information", text: "The number of students without internet access during the pandemic", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "E", explanation: "Paragraph E states 'an estimated 1.3 billion students worldwide lacked internet access.'" },
        { number: 29, type: "matching_information", text: "The combined value of the world's largest technology companies", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "C", explanation: "Paragraph C states the combined market cap 'exceeded $10 trillion by 2023.'" },
        { number: 30, type: "matching_information", text: "Technologies that could perform calculations far faster than current computers", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "F", explanation: "Paragraph F describes quantum computers performing 'calculations exponentially faster than classical computers.'" },
        { number: 31, type: "matching_information", text: "The role of social media in major political and social movements", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "B", explanation: "Paragraph B mentions social media's role in 'the Arab Spring and Black Lives Matter.'" },
        { number: 32, type: "flow_chart_completion", text: "The World Wide Web was developed by _______ in 1989.", correctAnswer: "Tim Berners-Lee", explanation: "The passage says 'developed by Tim Berners-Lee in 1989.'" },
        { number: 33, type: "flow_chart_completion", text: "By 2023, the internet connected over _______ billion users.", correctAnswer: "5.3", explanation: "The passage states 'over 5.3 billion users by 2023.'" },
        { number: 34, type: "flow_chart_completion", text: "By 2025, IoT-connected devices are expected to exceed _______ billion.", correctAnswer: "75", explanation: "The passage says 'will exceed 75 billion.'" },
        { number: 35, type: "flow_chart_completion", text: "Facebook has grown to over _______ billion monthly active users.", correctAnswer: "3", explanation: "The passage states 'over 3 billion monthly active users.'" },
        { number: 36, type: "flow_chart_completion", text: "TikTok reached _______ billion users faster than any platform in history.", correctAnswer: "1", explanation: "The passage says 'reached 1 billion users faster than any platform.'" },
        { number: 37, type: "flow_chart_completion", text: "Estonia offers over _______ percent of government services online.", correctAnswer: "99", explanation: "The passage states 'over 99 percent.'" },
        { number: 38, type: "flow_chart_completion", text: "The EU's data privacy regulation, implemented in 2018, is known as _______.", correctAnswer: "GDPR", explanation: "The passage names it 'the General Data Protection Regulation (GDPR).'" },
        { number: 39, type: "flow_chart_completion", text: "An estimated _______ billion students lacked internet access at home during the pandemic.", correctAnswer: "1.3", explanation: "The passage says 'An estimated 1.3 billion students.'" },
        { number: 40, type: "flow_chart_completion", text: "Extended reality encompasses VR, AR, and _______ reality.", correctAnswer: "mixed", explanation: "The passage lists 'virtual reality (VR), augmented reality (AR), and mixed reality (MR).'" },
      ],
    },
  ],
};
