import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_33: ReadingTest = {
  id: 33,
  passages: [
    {
      title: "History of Astronomy",
      text: `Astronomy, the study of celestial objects and phenomena beyond Earth's atmosphere, is among the oldest of the natural sciences. Humans have gazed at the night sky with wonder and curiosity since prehistory, and the systematic observation of stars, planets, and other celestial bodies has driven some of the most profound revolutions in human understanding of the universe and our place within it.

The earliest astronomical records come from ancient Mesopotamia, where Babylonian priest-astronomers meticulously recorded the positions and movements of celestial bodies on clay tablets as early as 1800 BCE. These observations were primarily motivated by astrology — the belief that celestial events influenced terrestrial affairs — but they produced remarkably accurate data. The Babylonians identified the five visible planets, tracked the eighteen-year Saros cycle of lunar eclipses, and developed mathematical methods for predicting planetary positions that remained unsurpassed for centuries.

Ancient Egyptian astronomy, though less mathematically sophisticated than Babylonian, was deeply integrated into religious and civic life. The alignment of the Great Pyramids of Giza with cardinal directions and specific stars demonstrates considerable astronomical knowledge. The Egyptian calendar, based on the heliacal rising of the star Sirius, which coincided with the annual flooding of the Nile, consisted of 365 days — one of the earliest approximations of the solar year.

Greek astronomy transformed the discipline from observational record-keeping into a theoretical science. Aristarchus of Samos proposed a heliocentric model — placing the Sun rather than the Earth at the centre of the cosmos — in the third century BCE, an idea that was far ahead of its time and largely rejected in favour of the geocentric model systematised by Claudius Ptolemy around 150 CE. Ptolemy's Almagest, which described planetary motions using complex systems of epicycles, remained the authoritative astronomical text for nearly fourteen centuries.

The Copernican Revolution of the sixteenth century overturned the Ptolemaic worldview. Nicolaus Copernicus published De Revolutionibus Orbium Coelestium in 1543, reviving the heliocentric hypothesis with mathematical rigour. Johannes Kepler subsequently demonstrated that planetary orbits are elliptical rather than circular, formulating three laws of planetary motion that remain fundamental to orbital mechanics. Galileo Galilei's telescopic observations beginning in 1609 — revealing the moons of Jupiter, the phases of Venus, and the craters of the Moon — provided compelling empirical support for the Copernican model, though his advocacy earned him persecution by the Inquisition.

Isaac Newton's Principia Mathematica (1687) unified celestial and terrestrial mechanics under a single framework of gravitational theory, explaining why planets follow Kepler's laws and enabling precise predictions of astronomical phenomena. Newtonian mechanics dominated astronomy for two centuries, guiding the discovery of Neptune in 1846 through the mathematical prediction of its gravitational influence on Uranus.

The twentieth century brought revolutionary changes. Albert Einstein's general theory of relativity (1915) described gravity as the curvature of spacetime, predicting phenomena such as gravitational lensing and black holes. Edwin Hubble's observation in 1929 that galaxies are receding from one another provided the first empirical evidence for an expanding universe, leading to the Big Bang theory. The discovery of the cosmic microwave background radiation in 1965 by Arno Penzias and Robert Wilson provided powerful confirmation of this model.

Modern astronomy employs technologies undreamt of by earlier generations. Space-based telescopes such as Hubble and the James Webb Space Telescope observe the universe across the electromagnetic spectrum, free from atmospheric distortion. Gravitational wave detectors such as LIGO have opened an entirely new window on the cosmos, detecting ripples in spacetime caused by colliding black holes and neutron stars. The discovery of thousands of exoplanets — planets orbiting other stars — has transformed our understanding of planetary systems and intensified the search for extraterrestrial life.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "What was the primary motivation for Babylonian astronomical observations?", options: ["A Scientific curiosity", "B Religious astrology", "C Agricultural planning", "D Military strategy"], correctAnswer: "B", explanation: "The passage states observations 'were primarily motivated by astrology.'" },
        { number: 2, type: "multiple_choice", text: "Who first proposed a heliocentric model of the cosmos?", options: ["A Copernicus", "B Ptolemy", "C Aristarchus of Samos", "D Galileo"], correctAnswer: "C", explanation: "The passage says 'Aristarchus of Samos proposed a heliocentric model' in the third century BCE." },
        { number: 3, type: "multiple_choice", text: "What did Kepler demonstrate about planetary orbits?", options: ["A They are perfectly circular.", "B They are elliptical.", "C They are random.", "D They follow spiral paths."], correctAnswer: "B", explanation: "The passage states Kepler 'demonstrated that planetary orbits are elliptical.'" },
        { number: 4, type: "multiple_choice", text: "How was Neptune discovered?", options: ["A Through direct telescopic observation", "B By analysing ancient Babylonian tablets", "C Through mathematical prediction of its gravitational influence on Uranus", "D By accident during a survey of asteroids"], correctAnswer: "C", explanation: "The passage says Neptune was discovered 'through the mathematical prediction of its gravitational influence on Uranus.'" },
        { number: 5, type: "sentence_completion", text: "The Babylonians tracked the __(5)__-year Saros cycle of lunar eclipses.", correctAnswer: "eighteen", explanation: "The passage states 'the eighteen-year Saros cycle.'" },
        { number: 6, type: "sentence_completion", text: "The Egyptian calendar was based on the heliacal rising of the star __(6)__.", correctAnswer: "Sirius", explanation: "The passage mentions 'the star Sirius.'" },
        { number: 7, type: "sentence_completion", text: "Ptolemy's __(7)__ remained the authoritative astronomical text for nearly fourteen centuries.", correctAnswer: "Almagest", explanation: "The passage names 'Ptolemy's Almagest.'" },
        { number: 8, type: "sentence_completion", text: "Copernicus published De Revolutionibus Orbium Coelestium in __(8)__.", correctAnswer: "1543", explanation: "The passage states 'in 1543.'" },
        { number: 9, type: "sentence_completion", text: "Galileo began his telescopic observations in __(9)__.", correctAnswer: "1609", explanation: "The passage says 'beginning in 1609.'" },
        { number: 10, type: "sentence_completion", text: "Edwin Hubble provided the first evidence for an __(10)__ universe in 1929.", correctAnswer: "expanding", explanation: "The passage mentions 'an expanding universe.'" },
        { number: 11, type: "sentence_completion", text: "The cosmic microwave background radiation was discovered in __(11)__ by Penzias and Wilson.", correctAnswer: "1965", explanation: "The passage states 'in 1965.'" },
        { number: 12, type: "sentence_completion", text: "LIGO detects ripples in spacetime called gravitational __(12)__.", correctAnswer: "waves", explanation: "The passage mentions 'Gravitational wave detectors such as LIGO.'" },
        { number: 13, type: "sentence_completion", text: "Newton's __(13)__ Mathematica unified celestial and terrestrial mechanics.", correctAnswer: "Principia", explanation: "The passage names 'Newton's Principia Mathematica.'" },
      ],
    },
    {
      title: "Water Conservation",
      text: `A. Fresh water is essential to all life on Earth, yet it represents only 2.5 per cent of the planet's total water supply. Of this small fraction, approximately sixty-nine per cent is locked in glaciers and ice caps, and most of the remainder is stored as groundwater, leaving less than one per cent readily accessible in rivers, lakes, and the atmosphere. With global water demand projected to exceed supply by forty per cent by 2030, water conservation has become an urgent priority for governments, industries, and individuals worldwide.

B. Agriculture is by far the largest consumer of fresh water, accounting for approximately seventy per cent of global withdrawals. Irrigation, essential for producing food for the world's growing population, is often highly inefficient: traditional flood irrigation can lose up to sixty per cent of applied water to evaporation, runoff, and seepage. Drip irrigation, which delivers water directly to plant root zones through networks of tubes and emitters, reduces water consumption by forty to sixty per cent compared with flood methods while often increasing crop yields. Israel, a global leader in water-efficient agriculture, irrigates over seventy-five per cent of its farmland using drip technology.

C. Industry consumes roughly twenty per cent of global fresh water, with significant variation by sector. Thermoelectric power generation, textile manufacturing, and food processing are particularly water-intensive. Industrial water recycling, in which process water is treated and reused rather than discharged, can reduce consumption by up to ninety per cent in some applications. Closed-loop cooling systems in power plants, for example, recirculate water rather than drawing fresh supplies from rivers or lakes, dramatically reducing both water withdrawal and thermal pollution.

D. Domestic water use, accounting for approximately ten per cent of global consumption, offers substantial conservation opportunities. Low-flow fixtures — toilets, showerheads, and faucets engineered to reduce water volume without sacrificing performance — can cut household water use by thirty to fifty per cent. Smart water meters provide real-time consumption data to householders, enabling informed decisions and rapid leak detection. Greywater recycling systems collect water from sinks, showers, and washing machines for reuse in toilet flushing and garden irrigation, further reducing demand on potable water supplies.

E. Water pricing and economic incentives play a crucial role in promoting conservation. In many regions, water is priced well below its true economic and environmental cost, encouraging wasteful use. Tiered pricing structures, which charge progressively higher rates as consumption increases, have proven effective in reducing demand. Cape Town, South Africa, facing a severe drought in 2018, implemented aggressive demand management measures including tiered pricing, public awareness campaigns, and consumption targets that reduced daily usage from over one billion litres to approximately five hundred million litres within months.

F. Desalination — the removal of salt from seawater or brackish water to produce fresh water — has expanded dramatically as a supply-side technology. Reverse osmosis, the dominant desalination method, forces seawater through semi-permeable membranes under high pressure, separating salt and impurities from water molecules. Global desalination capacity exceeds one hundred million cubic metres per day, with the Middle East accounting for roughly half of installed capacity. However, desalination remains energy-intensive and produces concentrated brine waste that can harm marine ecosystems if not managed responsibly.

G. Nature-based solutions are gaining recognition as cost-effective approaches to water management. Wetland restoration, reforestation of watersheds, and the preservation of natural floodplains enhance water storage, filtration, and flood mitigation without the capital costs of engineered infrastructure. New York City's watershed protection programme, which invested in preserving the forested Catskill Mountains watershed rather than building a costly filtration plant, has saved the city billions of dollars while providing clean water to nine million residents.

H. Climate change is intensifying water scarcity through altered precipitation patterns, accelerated glacial melting, and more frequent and severe droughts. Regions that depend on glacial meltwater for dry-season irrigation, including parts of South America, Central Asia, and the Himalayas, face particular vulnerability as glaciers retreat. Adapting to these changes will require not only improved water conservation and efficiency but also fundamental shifts in how societies value, govern, and allocate this most essential of natural resources.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Section A", options: ["I. Water use in farming and irrigation innovation", "II. The scarcity of accessible fresh water", "III. Reducing water waste in factories", "IV. Saving water at home", "V. Using price signals to reduce consumption", "VI. Converting seawater to drinking water", "VII. Protecting natural water systems", "VIII. Climate threats to water security"], correctAnswer: "II", explanation: "Section A discusses fresh water scarcity." },
        { number: 15, type: "matching_headings", text: "Section B", options: ["I. Water use in farming and irrigation innovation", "II. The scarcity of accessible fresh water", "III. Reducing water waste in factories", "IV. Saving water at home", "V. Using price signals to reduce consumption", "VI. Converting seawater to drinking water", "VII. Protecting natural water systems", "VIII. Climate threats to water security"], correctAnswer: "I", explanation: "Section B discusses agriculture and drip irrigation." },
        { number: 16, type: "matching_headings", text: "Section C", options: ["I. Water use in farming and irrigation innovation", "II. The scarcity of accessible fresh water", "III. Reducing water waste in factories", "IV. Saving water at home", "V. Using price signals to reduce consumption", "VI. Converting seawater to drinking water", "VII. Protecting natural water systems", "VIII. Climate threats to water security"], correctAnswer: "III", explanation: "Section C discusses industrial water consumption and recycling." },
        { number: 17, type: "matching_headings", text: "Section D", options: ["I. Water use in farming and irrigation innovation", "II. The scarcity of accessible fresh water", "III. Reducing water waste in factories", "IV. Saving water at home", "V. Using price signals to reduce consumption", "VI. Converting seawater to drinking water", "VII. Protecting natural water systems", "VIII. Climate threats to water security"], correctAnswer: "IV", explanation: "Section D discusses domestic water conservation." },
        { number: 18, type: "matching_headings", text: "Section E", options: ["I. Water use in farming and irrigation innovation", "II. The scarcity of accessible fresh water", "III. Reducing water waste in factories", "IV. Saving water at home", "V. Using price signals to reduce consumption", "VI. Converting seawater to drinking water", "VII. Protecting natural water systems", "VIII. Climate threats to water security"], correctAnswer: "V", explanation: "Section E discusses pricing and economic incentives." },
        { number: 19, type: "matching_headings", text: "Section F", options: ["I. Water use in farming and irrigation innovation", "II. The scarcity of accessible fresh water", "III. Reducing water waste in factories", "IV. Saving water at home", "V. Using price signals to reduce consumption", "VI. Converting seawater to drinking water", "VII. Protecting natural water systems", "VIII. Climate threats to water security"], correctAnswer: "VI", explanation: "Section F discusses desalination." },
        { number: 20, type: "table_completion", text: "Fresh water represents only __(20)__ per cent of the planet's total water supply.", correctAnswer: "2.5", explanation: "The passage states '2.5 per cent.'" },
        { number: 21, type: "table_completion", text: "Agriculture accounts for approximately __(21)__ per cent of global water withdrawals.", correctAnswer: "seventy", explanation: "The passage states 'approximately seventy per cent.'" },
        { number: 22, type: "table_completion", text: "Drip irrigation reduces water consumption by __(22)__ to sixty per cent.", correctAnswer: "forty", explanation: "The passage states 'forty to sixty per cent.'" },
        { number: 23, type: "table_completion", text: "Global desalination capacity exceeds __(23)__ million cubic metres per day.", correctAnswer: "one hundred", explanation: "The passage states 'one hundred million cubic metres per day.'" },
        { number: 24, type: "table_completion", text: "Israel irrigates over __(24)__ per cent of its farmland using drip technology.", correctAnswer: "seventy-five", explanation: "The passage states 'over seventy-five per cent.'" },
        { number: 25, type: "table_completion", text: "Cape Town reduced daily water usage from over one billion litres to approximately __(25)__ million litres.", correctAnswer: "five hundred", explanation: "The passage states 'approximately five hundred million litres.'" },
        { number: 26, type: "table_completion", text: "New York City's watershed programme provides water to __(26)__ million residents.", correctAnswer: "nine", explanation: "The passage states 'nine million residents.'" },
      ],
    },
    {
      title: "Autonomous Robots",
      text: `Autonomous robots — machines capable of performing tasks in unstructured environments without continuous human guidance — represent one of the most dynamic and consequential areas of technological development. Drawing on advances in artificial intelligence, computer vision, sensor technology, and mechanical engineering, autonomous robots are moving from laboratory prototypes and factory floors into homes, hospitals, farms, warehouses, and public spaces, with implications that extend across the economy, workforce, and society.

Industrial robotics has been the most established application of robotic technology since the Unimate robot arm was installed on a General Motors assembly line in 1961. Modern industrial robots perform welding, painting, assembly, and material handling with speed and precision that far exceed human capabilities. However, traditional industrial robots operate in highly controlled environments behind safety cages, following pre-programmed movements. The emergence of collaborative robots, or cobots, designed to work safely alongside human workers without physical barriers, represents a significant evolution. Companies such as Universal Robots and Rethink Robotics have developed cobots equipped with force sensors and compliant actuators that allow them to detect contact with humans and respond by slowing or stopping, enabling flexible human-robot collaboration in manufacturing, packaging, and quality inspection tasks.

Autonomous mobile robots (AMRs) are transforming logistics and warehousing. Amazon's acquisition of Kiva Systems in 2012 signalled the beginning of widespread warehouse automation. Today, Amazon operates over 750,000 robots across its fulfilment centres, moving shelving units to human pickers and dramatically increasing throughput. Unlike automated guided vehicles (AGVs), which follow fixed paths, AMRs navigate dynamically using LIDAR, cameras, and onboard computers, enabling them to adapt to changing environments and avoid obstacles in real time.

Agricultural robotics is addressing labour shortages and sustainability challenges in farming. Autonomous tractors, guided by GPS and computer vision, can plough, plant, and harvest with centimetre-level precision, reducing overlap and waste. Specialised robots harvest delicate crops such as strawberries and tomatoes using soft grippers and machine learning algorithms trained to identify ripe fruit. Weeding robots use cameras and AI to distinguish crops from weeds, applying targeted herbicide microdoses or mechanical removal that reduces chemical use by up to ninety per cent.

Healthcare robotics encompasses a broad spectrum of applications. Surgical robots such as the da Vinci system enable minimally invasive procedures with enhanced precision, smaller incisions, and faster patient recovery. Telepresence robots allow specialists to conduct remote consultations, while autonomous mobile robots transport medications, meals, and laboratory samples within hospitals, reducing staff workload. Rehabilitation robots assist patients recovering from strokes and injuries by providing repetitive, precisely controlled movement therapy. Social robots designed for elderly care provide companionship, medication reminders, and emergency alerts, addressing some of the challenges posed by ageing populations and healthcare workforce shortages.

Service robots are increasingly visible in public-facing roles. Hotels deploy robots for room service delivery and concierge assistance. Restaurants use robotic kitchen assistants and autonomous serving platforms. Security patrol robots equipped with cameras, microphones, and environmental sensors monitor commercial properties and public spaces. While these applications remain relatively limited in scope, they demonstrate the expanding range of tasks that autonomous robots can perform outside traditional industrial settings.

The societal implications of autonomous robotics are profound. Economic analyses predict that automation could displace between 400 million and 800 million jobs globally by 2030, while simultaneously creating new roles in robot design, programming, maintenance, and supervision. The net employment effect remains a subject of vigorous debate among economists. Ethical questions surrounding autonomous weapons systems, privacy concerns related to surveillance robots, and liability frameworks for accidents involving autonomous machines all require urgent attention from policymakers.

The technological trajectory suggests that autonomous robots will become progressively more capable, affordable, and ubiquitous. Advances in reinforcement learning enable robots to acquire new skills through trial and error in simulated environments before deploying them in the physical world. Improved battery technology extends operational range and duration. The convergence of 5G connectivity, edge computing, and cloud AI enables robots to access vast computational resources in real time, enhancing their decision-making capabilities beyond what onboard processors alone could achieve.`,
      questions: [
        { number: 27, type: "multiple_choice", text: "What distinguishes collaborative robots from traditional industrial robots?", options: ["A They are smaller and cheaper.", "B They can work safely alongside humans without barriers.", "C They operate only in healthcare settings.", "D They require no programming."], correctAnswer: "B", explanation: "The passage says cobots are 'designed to work safely alongside human workers without physical barriers.'" },
        { number: 28, type: "multiple_choice", text: "How do autonomous mobile robots differ from automated guided vehicles?", options: ["A They are slower but more accurate.", "B They navigate dynamically rather than following fixed paths.", "C They are used only in Amazon warehouses.", "D They require human remote control at all times."], correctAnswer: "B", explanation: "The passage says 'AMRs navigate dynamically... enabling them to adapt to changing environments.'" },
        { number: 29, type: "multiple_choice", text: "According to the passage, how many jobs could automation displace globally by 2030?", options: ["A 100 to 200 million", "B 200 to 400 million", "C 400 to 800 million", "D Over one billion"], correctAnswer: "C", explanation: "The passage states 'between 400 million and 800 million jobs.'" },
        { number: 30, type: "multiple_choice", text: "What technology enables robots to acquire new skills through simulated trial and error?", options: ["A Computer vision", "B Reinforcement learning", "C Blockchain", "D 3D printing"], correctAnswer: "B", explanation: "The passage says 'reinforcement learning enable robots to acquire new skills through trial and error.'" },
        { number: 31, type: "short_answer", text: "What was the first industrial robot installed on an assembly line?", correctAnswer: "Unimate", explanation: "The passage names 'the Unimate robot arm.'" },
        { number: 32, type: "short_answer", text: "Which company did Amazon acquire in 2012 for warehouse robotics?", correctAnswer: "Kiva Systems", explanation: "The passage states 'Amazon's acquisition of Kiva Systems in 2012.'" },
        { number: 33, type: "short_answer", text: "How many robots does Amazon operate across its fulfilment centres?", correctAnswer: "over 750,000", explanation: "The passage states 'over 750,000 robots.'" },
        { number: 34, type: "short_answer", text: "What surgical robot system enables minimally invasive procedures?", correctAnswer: "da Vinci", explanation: "The passage names 'the da Vinci system.'" },
        { number: 35, type: "short_answer", text: "By what percentage can weeding robots reduce chemical herbicide use?", correctAnswer: "ninety per cent", explanation: "The passage states 'reduces chemical use by up to ninety per cent.'" },
        { number: 36, type: "short_answer", text: "What type of sensors do cobots use to detect contact with humans?", correctAnswer: "force sensors", explanation: "The passage mentions 'force sensors and compliant actuators.'" },
        { number: 37, type: "short_answer", text: "What navigation technology do AMRs use alongside cameras and computers?", correctAnswer: "LIDAR", explanation: "The passage says AMRs use 'LIDAR, cameras, and onboard computers.'" },
        { number: 38, type: "short_answer", text: "What type of grippers do strawberry-harvesting robots use?", correctAnswer: "soft grippers", explanation: "The passage mentions 'soft grippers.'" },
        { number: 39, type: "short_answer", text: "What type of robots provide companionship to elderly people?", correctAnswer: "social robots", explanation: "The passage mentions 'Social robots designed for elderly care.'" },
        { number: 40, type: "short_answer", text: "What connectivity technology enhances robots' real-time decision-making?", correctAnswer: "5G", explanation: "The passage mentions '5G connectivity, edge computing, and cloud AI.'" },
      ],
    },
  ],
};
