import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_37: ReadingTest = {
  id: 37,
  passages: [
    {
      title: "The History of Printing",
      text: `The ability to reproduce text mechanically has shaped the course of human civilisation more profoundly than almost any other technological development. Before printing, every book in Europe had to be copied by hand, a painstaking process that kept literacy confined to a small elite of clergy, scholars, and aristocrats. The average medieval scribe could produce perhaps four pages of text per day, meaning that a single copy of the Bible — roughly 1,200 pages — required nearly a year of uninterrupted labour. Books were so costly that a university library of two hundred volumes was considered exceptional.

The story of printing, however, begins not in Europe but in East Asia. Chinese artisans were carving text into wooden blocks and pressing inked impressions onto paper as early as the seventh century CE. The oldest surviving printed book, a copy of the Diamond Sutra, dates from 868 CE and was discovered in 1907 in the Mogao Caves of Dunhuang, China. Woodblock printing spread to Korea and Japan, where Buddhist monks used it extensively to reproduce religious scriptures. Around 1040 CE, a Chinese commoner named Bi Sheng invented movable type, fashioning individual characters from baked clay that could be arranged, printed, and reused. Because written Chinese employs thousands of distinct characters, however, the practical advantages of movable type were limited, and woodblock printing remained dominant in East Asia for centuries.

In Europe, the breakthrough came in the 1440s when Johannes Gutenberg, a goldsmith from Mainz in present-day Germany, developed a printing system that combined movable metal type, an oil-based ink, and a wooden press adapted from those used in winemaking. Gutenberg's genius lay not in any single invention but in the integration of several technologies into a reliable, efficient production process. His metal type, cast from a lead-tin-antimony alloy, was durable enough to print thousands of identical pages, and his ink adhered to metal far better than the water-based inks used in Asian woodblock printing.

The impact of Gutenberg's press was swift and far-reaching. By 1500, an estimated twenty million volumes had been printed in Europe, and the price of books had fallen by roughly eighty per cent. The sudden availability of affordable texts fuelled the Renaissance, the Protestant Reformation, and the Scientific Revolution. Martin Luther's Ninety-Five Theses, posted in 1517, were reprinted and distributed across Germany within weeks — a speed of dissemination inconceivable in the age of manuscript copying. Scientists could now share findings with colleagues across the continent almost immediately, accelerating the accumulation of knowledge.

Subsequent centuries brought steady improvements. The iron handpress, introduced around 1800, doubled the output of Gutenberg's wooden press. Steam-powered rotary presses, developed in the 1840s, could print thousands of sheets per hour and made mass-circulation newspapers economically viable. Linotype machines, patented in 1886, automated the setting of type and slashed the time needed to compose a page of text. By the early twentieth century, offset lithography had become the dominant printing method, producing high-quality images alongside text at industrial speed.

The late twentieth century ushered in the digital revolution. Desktop publishing software, laser printers, and eventually inkjet printers brought professional-quality printing into homes and small offices. The internet and electronic books have since challenged the primacy of print itself, yet global paper-based printing remains a multi-billion-dollar industry. Packaging, textiles, and commercial signage all rely on advanced printing technologies, including three-dimensional printing, which deposits successive layers of material to create physical objects from digital designs.

From Bi Sheng's clay characters to Gutenberg's metal type to today's digital presses, the history of printing is a history of democratising information. Each technological leap has widened access to knowledge, empowered new voices, and reshaped the societies that adopted it.`,
      questions: [
        { number: 1, type: "true_false_not_given", text: "Before printing, most European books were produced by professional publishers.", correctAnswer: "FALSE", explanation: "The passage says books 'had to be copied by hand' by scribes, not professional publishers." },
        { number: 2, type: "true_false_not_given", text: "The Diamond Sutra was discovered in the Mogao Caves.", correctAnswer: "TRUE", explanation: "The passage states it 'was discovered in 1907 in the Mogao Caves of Dunhuang, China.'" },
        { number: 3, type: "true_false_not_given", text: "Bi Sheng was a wealthy aristocrat.", correctAnswer: "FALSE", explanation: "The passage describes Bi Sheng as 'a Chinese commoner.'" },
        { number: 4, type: "true_false_not_given", text: "Gutenberg's press used water-based ink.", correctAnswer: "FALSE", explanation: "The passage says Gutenberg used 'an oil-based ink,' contrasting it with Asian water-based inks." },
        { number: 5, type: "true_false_not_given", text: "Luther's Ninety-Five Theses were distributed across Germany within weeks.", correctAnswer: "TRUE", explanation: "The passage says they 'were reprinted and distributed across Germany within weeks.'" },
        { number: 6, type: "true_false_not_given", text: "The Linotype machine was invented by Gutenberg.", correctAnswer: "FALSE", explanation: "The passage says Linotype machines were 'patented in 1886,' centuries after Gutenberg." },
        { number: 7, type: "true_false_not_given", text: "Offset lithography was developed primarily for printing newspapers.", correctAnswer: "NOT GIVEN", explanation: "The passage mentions offset lithography becoming the dominant method but does not specify it was developed primarily for newspapers." },
        { number: 8, type: "sentence_completion", text: "A medieval scribe could produce approximately __(8)__ pages of text per day.", correctAnswer: "four", explanation: "The passage says 'perhaps four pages of text per day.'" },
        { number: 9, type: "sentence_completion", text: "Bi Sheng fashioned individual characters from baked __(9)__.", correctAnswer: "clay", explanation: "The passage says he fashioned characters 'from baked clay.'" },
        { number: 10, type: "sentence_completion", text: "Gutenberg's metal type was cast from a lead-tin-__(10)__ alloy.", correctAnswer: "antimony", explanation: "The passage says 'a lead-tin-antimony alloy.'" },
        { number: 11, type: "sentence_completion", text: "By 1500, the price of books had fallen by roughly __(11)__ per cent.", correctAnswer: "eighty", explanation: "The passage says 'the price of books had fallen by roughly eighty per cent.'" },
        { number: 12, type: "sentence_completion", text: "Steam-powered rotary presses could print thousands of sheets per __(12)__.", correctAnswer: "hour", explanation: "The passage says 'thousands of sheets per hour.'" },
        { number: 13, type: "sentence_completion", text: "Three-dimensional printing deposits successive layers of __(13)__ to create physical objects.", correctAnswer: "material", explanation: "The passage says it 'deposits successive layers of material to create physical objects.'" },
      ],
    },
    {
      title: "Marine Conservation",
      text: `A. The world's oceans cover more than seventy per cent of the Earth's surface and sustain a breathtaking diversity of life, from microscopic phytoplankton that generate half the planet's oxygen to the blue whale, the largest animal ever to have lived. Yet marine ecosystems are under unprecedented pressure. Overfishing, pollution, habitat destruction, and climate change are degrading ocean health at an alarming rate, prompting scientists and policymakers to call for urgent and coordinated conservation efforts.

B. Overfishing is perhaps the most immediate threat. The United Nations Food and Agriculture Organization estimates that more than one-third of global fish stocks are now exploited beyond sustainable levels. Industrial trawlers equipped with sonar and satellite technology can locate and harvest fish with ruthless efficiency, depleting populations faster than they can reproduce. The collapse of the North Atlantic cod fishery in the early 1990s stands as a cautionary example: after decades of overharvesting, cod stocks off Newfoundland fell to less than one per cent of their historical levels, and the fishery was closed in 1992. More than thirty years later, cod numbers have still not fully recovered.

C. Plastic pollution has emerged as another critical concern. An estimated eight million tonnes of plastic enter the oceans every year, forming vast accumulations such as the Great Pacific Garbage Patch, which covers an area roughly three times the size of France. Marine animals ingest plastic debris or become entangled in discarded fishing nets, known as ghost nets. Microplastics — fragments smaller than five millimetres — have been found in the tissues of organisms ranging from plankton to polar bears, and their long-term effects on marine food webs remain poorly understood.

D. Coral reefs, often called the rainforests of the sea, are particularly vulnerable. Rising ocean temperatures cause coral bleaching, a stress response in which corals expel the symbiotic algae that provide them with colour and nutrition. If bleaching persists, the coral dies, and the complex ecosystem it supports collapses. The Great Barrier Reef experienced mass bleaching events in 2016, 2017, 2020, and 2022, and scientists warn that if global temperatures rise by more than 1.5 degrees Celsius above pre-industrial levels, ninety per cent of the world's coral reefs could be lost.

E. Marine Protected Areas (MPAs) are one of the principal tools of ocean conservation. An MPA is a clearly defined geographical space in which human activities — particularly fishing and resource extraction — are restricted or prohibited. Well-managed MPAs have been shown to increase fish biomass, restore biodiversity, and enhance the resilience of ecosystems to climate change. The Papahānaumokuākea Marine National Monument in Hawaii, one of the largest MPAs in the world, protects more than 7,000 marine species across 1.5 million square kilometres of ocean.

F. International cooperation is essential because marine ecosystems do not respect national boundaries. Migratory species such as tuna, sharks, and sea turtles traverse entire ocean basins, and pollution released in one country can affect coastlines thousands of kilometres away. The United Nations High Seas Treaty, agreed in 2023, provides a framework for creating protected areas in international waters — the two-thirds of the ocean that lie beyond any nation's jurisdiction. If effectively implemented, the treaty could safeguard some of the planet's most remote and biodiverse marine environments.

G. Technological innovation is also playing an increasing role in conservation. Satellite monitoring can detect illegal fishing vessels in real time; environmental DNA (eDNA) sampling allows scientists to identify which species inhabit a body of water simply by analysing trace genetic material; and underwater drones survey habitats that are too deep or dangerous for human divers. These tools are making conservation efforts more targeted, efficient, and data-driven.

H. Ultimately, the fate of the oceans depends on the choices made by governments, industries, and individuals. Reducing carbon emissions, eliminating single-use plastics, enforcing sustainable fishing quotas, and expanding marine protected areas are all necessary steps. The ocean has sustained human civilisation for millennia; whether it can continue to do so depends on the willingness of this generation to act.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Section A", options: ["I. The role of technology in protecting seas", "II. Threats to ocean ecosystems", "III. The problem of excessive fishing", "IV. International agreements for ocean protection", "V. Damage to coral reef systems", "VI. Protected zones in the ocean", "VII. Plastic waste in marine environments", "VIII. Responsibility for future ocean health"], correctAnswer: "II", explanation: "Section A introduces the various pressures on marine ecosystems." },
        { number: 15, type: "matching_headings", text: "Section B", options: ["I. The role of technology in protecting seas", "II. Threats to ocean ecosystems", "III. The problem of excessive fishing", "IV. International agreements for ocean protection", "V. Damage to coral reef systems", "VI. Protected zones in the ocean", "VII. Plastic waste in marine environments", "VIII. Responsibility for future ocean health"], correctAnswer: "III", explanation: "Section B discusses overfishing in detail." },
        { number: 16, type: "matching_headings", text: "Section C", options: ["I. The role of technology in protecting seas", "II. Threats to ocean ecosystems", "III. The problem of excessive fishing", "IV. International agreements for ocean protection", "V. Damage to coral reef systems", "VI. Protected zones in the ocean", "VII. Plastic waste in marine environments", "VIII. Responsibility for future ocean health"], correctAnswer: "VII", explanation: "Section C discusses plastic pollution in the oceans." },
        { number: 17, type: "matching_headings", text: "Section D", options: ["I. The role of technology in protecting seas", "II. Threats to ocean ecosystems", "III. The problem of excessive fishing", "IV. International agreements for ocean protection", "V. Damage to coral reef systems", "VI. Protected zones in the ocean", "VII. Plastic waste in marine environments", "VIII. Responsibility for future ocean health"], correctAnswer: "V", explanation: "Section D discusses coral bleaching and reef vulnerability." },
        { number: 18, type: "matching_headings", text: "Section E", options: ["I. The role of technology in protecting seas", "II. Threats to ocean ecosystems", "III. The problem of excessive fishing", "IV. International agreements for ocean protection", "V. Damage to coral reef systems", "VI. Protected zones in the ocean", "VII. Plastic waste in marine environments", "VIII. Responsibility for future ocean health"], correctAnswer: "VI", explanation: "Section E discusses Marine Protected Areas." },
        { number: 19, type: "matching_headings", text: "Section F", options: ["I. The role of technology in protecting seas", "II. Threats to ocean ecosystems", "III. The problem of excessive fishing", "IV. International agreements for ocean protection", "V. Damage to coral reef systems", "VI. Protected zones in the ocean", "VII. Plastic waste in marine environments", "VIII. Responsibility for future ocean health"], correctAnswer: "IV", explanation: "Section F discusses international cooperation and the UN High Seas Treaty." },
        { number: 20, type: "table_completion", text: "Cod stocks off Newfoundland fell to less than __(20)__ per cent of historical levels.", correctAnswer: "one", explanation: "The passage says 'less than one per cent of their historical levels.'" },
        { number: 21, type: "table_completion", text: "An estimated __(21)__ million tonnes of plastic enter the oceans every year.", correctAnswer: "eight", explanation: "The passage says 'eight million tonnes of plastic enter the oceans every year.'" },
        { number: 22, type: "table_completion", text: "The Papahānaumokuākea monument protects more than __(22)__ marine species.", correctAnswer: "7,000", explanation: "The passage says 'more than 7,000 marine species.'" },
        { number: 23, type: "table_completion", text: "The UN High Seas Treaty was agreed in __(23)__.", correctAnswer: "2023", explanation: "The passage says 'The United Nations High Seas Treaty, agreed in 2023.'" },
        { number: 24, type: "short_answer", text: "What are discarded fishing nets in the ocean called?", correctAnswer: "ghost nets", explanation: "The passage refers to 'discarded fishing nets, known as ghost nets.'" },
        { number: 25, type: "short_answer", text: "What do corals expel during bleaching?", correctAnswer: "symbiotic algae", explanation: "The passage says corals 'expel the symbiotic algae.'" },
        { number: 26, type: "short_answer", text: "What type of DNA sampling helps identify species from trace genetic material?", correctAnswer: "environmental DNA", explanation: "The passage mentions 'environmental DNA (eDNA) sampling.'" },
      ],
    },
    {
      title: "Electric Aviation",
      text: `The aviation industry contributes approximately two to three per cent of global carbon dioxide emissions, a figure that is projected to rise sharply as air travel demand grows. While other transport sectors have made significant progress toward electrification — electric cars now account for roughly one in five new vehicle sales worldwide — aviation has lagged behind, constrained by the enormous energy demands of flight and the limitations of current battery technology. Nevertheless, a growing number of companies, research institutions, and governments are investing heavily in electric aviation, and the first commercial electric aircraft are expected to enter service within the next decade.

The fundamental challenge is energy density. Aviation fuel (kerosene) contains approximately 12,000 watt-hours of energy per kilogramme, whereas the best lithium-ion batteries currently available store only about 250 watt-hours per kilogramme — roughly one-fiftieth of the energy for the same weight. Since an aircraft must carry its energy source aloft, this disparity makes battery-powered flight feasible only for short distances with small payloads. Most electric aircraft under development are therefore designed for regional routes of 200 to 500 kilometres, carrying between nine and thirty passengers.

Several start-up companies have reached advanced stages of development. Heart Aerospace, a Swedish firm, is building the ES-30, a thirty-seat hybrid-electric aircraft intended for regional airlines. The ES-30 uses battery power for take-off and climb, then switches to conventional turbogenerators for cruise, achieving a claimed thirty per cent reduction in fuel consumption and emissions compared with equivalent turboprops. Eviation, an Israeli company, has developed the Alice, a fully electric nine-seat commuter aircraft with a projected range of 463 kilometres. The Alice completed its maiden flight in September 2022 and has attracted orders from regional carriers in the United States and Europe.

Larger electric aircraft remain a more distant prospect. Airbus has announced its ambition to bring a hydrogen-powered narrow-body airliner — the ZEROe — to market by 2035. The ZEROe concept relies not on batteries but on hydrogen fuel cells or hydrogen combustion, both of which produce water vapour rather than carbon dioxide as their primary emission. Hydrogen's energy density by weight is roughly three times that of kerosene, but it occupies far more volume, requiring radically redesigned fuselages. Airbus engineers are exploring blended-wing-body configurations that would provide the internal space needed to store hydrogen tanks while maintaining aerodynamic efficiency.

Advances in battery technology could shift the calculus. Solid-state batteries, which replace the liquid electrolyte in conventional lithium-ion cells with a solid material, promise energy densities of 500 watt-hours per kilogramme or more — roughly double today's best cells. If solid-state batteries reach commercial maturity, the viable range of all-electric aircraft could extend to 1,000 kilometres, opening routes such as London to Paris or New York to Chicago. Research laboratories in Japan, South Korea, and the United States are racing to solve the remaining engineering challenges, including manufacturing scalability and long-term durability.

Infrastructure is another critical consideration. Electric and hydrogen aircraft will require airports to install charging stations or hydrogen refuelling facilities, investments that airlines and airport authorities have been slow to commit to in the absence of certified aircraft. Norway, however, has taken a proactive stance, announcing that all short-haul flights within the country should be electric by 2040 and allocating funding for the necessary airport upgrades.

The regulatory landscape is also evolving. Aviation safety authorities in Europe and the United States are developing new certification standards for electric powertrains, batteries, and hydrogen systems. These standards must balance the need for innovation with the aviation industry's paramount requirement for safety. Certification timelines remain uncertain, but industry analysts expect the first type certificates for electric regional aircraft to be issued by 2026 or 2027.

Electric aviation will not replace kerosene-powered long-haul flight in the foreseeable future, but it has the potential to transform short-haul and regional travel. If battery and hydrogen technologies continue to advance, a significant proportion of flights under 1,000 kilometres — which account for roughly half of all departures worldwide — could eventually be emissions-free.`,
      questions: [
        { number: 27, type: "multiple_choice", text: "What percentage of global CO2 emissions does aviation currently contribute?", options: ["A 5 to 7 per cent", "B 2 to 3 per cent", "C 10 to 12 per cent", "D Less than 1 per cent"], correctAnswer: "B", explanation: "The passage says aviation 'contributes approximately two to three per cent.'" },
        { number: 28, type: "multiple_choice", text: "What is the approximate energy density of lithium-ion batteries per kilogramme?", options: ["A 12,000 watt-hours", "B 500 watt-hours", "C 250 watt-hours", "D 1,000 watt-hours"], correctAnswer: "C", explanation: "The passage says batteries store 'only about 250 watt-hours per kilogramme.'" },
        { number: 29, type: "multiple_choice", text: "When did the Eviation Alice complete its maiden flight?", options: ["A January 2020", "B March 2021", "C September 2022", "D December 2023"], correctAnswer: "C", explanation: "The passage says 'The Alice completed its maiden flight in September 2022.'" },
        { number: 30, type: "multiple_choice", text: "What does Airbus plan to use as fuel for its ZEROe aircraft?", options: ["A Lithium-ion batteries", "B Biofuels", "C Hydrogen", "D Solar energy"], correctAnswer: "C", explanation: "The passage says the ZEROe concept 'relies not on batteries but on hydrogen fuel cells or hydrogen combustion.'" },
        { number: 31, type: "flow_chart_completion", text: "The ES-30 uses __(31)__ power for take-off and climb.", correctAnswer: "battery", explanation: "The passage says 'uses battery power for take-off and climb.'" },
        { number: 32, type: "flow_chart_completion", text: "During cruise, the ES-30 switches to conventional __(32)__.", correctAnswer: "turbogenerators", explanation: "The passage says it 'switches to conventional turbogenerators for cruise.'" },
        { number: 33, type: "flow_chart_completion", text: "This achieves a __(33)__ per cent reduction in fuel consumption.", correctAnswer: "thirty", explanation: "The passage says 'a claimed thirty per cent reduction.'" },
        { number: 34, type: "flow_chart_completion", text: "Solid-state batteries promise energy densities of __(34)__ watt-hours per kilogramme.", correctAnswer: "500", explanation: "The passage says 'energy densities of 500 watt-hours per kilogramme or more.'" },
        { number: 35, type: "sentence_completion", text: "Hydrogen's energy density by weight is roughly __(35)__ times that of kerosene.", correctAnswer: "three", explanation: "The passage says 'roughly three times that of kerosene.'" },
        { number: 36, type: "sentence_completion", text: "Norway has announced that all short-haul flights should be electric by __(36)__.", correctAnswer: "2040", explanation: "The passage says 'all short-haul flights within the country should be electric by 2040.'" },
        { number: 37, type: "sentence_completion", text: "Industry analysts expect the first type certificates for electric aircraft by __(37)__ or 2027.", correctAnswer: "2026", explanation: "The passage says 'by 2026 or 2027.'" },
        { number: 38, type: "sentence_completion", text: "Flights under 1,000 kilometres account for roughly __(38)__ of all departures worldwide.", correctAnswer: "half", explanation: "The passage says 'roughly half of all departures worldwide.'" },
        { number: 39, type: "sentence_completion", text: "Airbus engineers are exploring blended-wing-body __(39)__ for hydrogen aircraft.", correctAnswer: "configurations", explanation: "The passage says 'blended-wing-body configurations.'" },
        { number: 40, type: "sentence_completion", text: "Electric aircraft under development are designed for regional routes of __(40)__ to 500 kilometres.", correctAnswer: "200", explanation: "The passage says 'regional routes of 200 to 500 kilometres.'" },
      ],
    },
  ],
};
