import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_48: ReadingTest = {
  id: 48,
  passages: [
    {
      title: "Ancient Cultures and Architecture",
      text: `Architecture is among the most enduring expressions of human culture. The structures that ancient civilisations left behind — temples, palaces, fortifications, and dwellings — reveal not only their builders' technical capabilities but also their social hierarchies, religious beliefs, and aesthetic sensibilities. From the monumental pyramids of Egypt to the sophisticated urban planning of the Indus Valley, ancient architecture provides a window into the values and aspirations of societies long vanished.

The pyramids of Giza, constructed around 2560 BCE during the reign of Pharaoh Khufu, remain among the most iconic structures ever built. The Great Pyramid stood approximately 146 metres tall and was the tallest man-made structure in the world for over 3,800 years. Its construction required an estimated 2.3 million limestone blocks, each weighing an average of 2.5 tonnes. The precision of its construction — the base is level to within just 2.1 centimetres across its 230-metre length — continues to astonish engineers. Yet beyond their technical achievement, the pyramids embodied the pharaoh's divine status and the Egyptian belief in an afterlife requiring monumental preparation.

In Mesopotamia, the civilisations of Sumer, Babylon, and Assyria developed distinctive architectural traditions centred on the ziggurat — a terraced, pyramid-like temple platform. Unlike Egyptian pyramids, which were solid structures serving as tombs, ziggurats were hollow, with staircases leading to a shrine at the summit where priests conducted rituals. The Great Ziggurat of Ur, built around 2100 BCE, originally rose to approximately 30 metres and was dedicated to the moon god Nanna. Its massive mudbrick walls, reinforced with layers of bitumen and woven reeds, demonstrate sophisticated understanding of materials engineering.

The ancient Greeks contributed an architectural vocabulary that continues to influence building design worldwide. The three classical orders — Doric, Ionic, and Corinthian — established proportional systems that governed column design, entablature arrangement, and decorative detailing. The Parthenon in Athens, completed in 432 BCE, exemplifies the Doric order's emphasis on strength and simplicity. Its architects, Ictinus and Callicrates, incorporated subtle optical refinements: the columns lean slightly inward, and the stylobate — the platform on which they stand — curves almost imperceptibly upward at its centre. These adjustments corrected visual distortions that would have made the building appear to sag.

Roman architecture extended Greek principles through revolutionary engineering innovations. The development of concrete — a mixture of volcanic ash, lime, and aggregate — enabled the construction of vast interior spaces previously impossible with stone or timber. The Pantheon in Rome, completed around 125 CE under Emperor Hadrian, features an unreinforced concrete dome spanning 43.3 metres — a record that stood for nearly 1,300 years until the construction of Florence Cathedral's dome in 1436. The Romans also perfected the arch and the vault, enabling the construction of aqueducts, bridges, and amphitheatres on an unprecedented scale.

The Indus Valley civilisation, flourishing between approximately 3300 and 1300 BCE in present-day Pakistan and northwest India, developed perhaps the most advanced urban planning of the ancient world. The cities of Mohenjo-daro and Harappa featured grid-patterned streets, standardised brick construction, and remarkably sophisticated drainage and sanitation systems. Nearly every house had access to a private bathing area connected to covered drains that ran beneath the streets — a level of municipal infrastructure not matched in Europe until the nineteenth century.

In Mesoamerica, the Maya and Aztec civilisations created monumental architecture that reflected their astronomical knowledge and religious cosmology. The Pyramid of Kukulcán at Chichén Itzá, built around the tenth century CE, was designed so that during the spring and autumn equinoxes, the play of sunlight and shadow creates the illusion of a serpent descending the northern staircase. This integration of architecture with astronomical observation demonstrates a sophisticated understanding of celestial mechanics.

The study of ancient architecture reveals that building was never merely a practical activity. Structures encoded meaning: they expressed power, celebrated deities, marked cosmic events, and ordered social life. The materials and methods varied enormously — from Egyptian limestone to Mesopotamian mudbrick, from Greek marble to Roman concrete — but the impulse to build structures that transcended mere shelter was universal. Understanding these traditions enriches our appreciation of the built environment and reminds us that architecture has always been a dialogue between human ambition and the possibilities of the physical world.`,
      questions: [
        { number: 1, type: "true_false_not_given", text: "The Great Pyramid was the tallest man-made structure for over 3,800 years.", correctAnswer: "TRUE", explanation: "The passage directly states this." },
        { number: 2, type: "true_false_not_given", text: "The Great Pyramid required approximately 2.3 million blocks of granite.", correctAnswer: "FALSE", explanation: "The passage says 'limestone blocks,' not granite." },
        { number: 3, type: "true_false_not_given", text: "Ziggurats served the same purpose as Egyptian pyramids.", correctAnswer: "FALSE", explanation: "The passage says ziggurats were temple platforms, while pyramids were tombs." },
        { number: 4, type: "true_false_not_given", text: "The Great Ziggurat of Ur was dedicated to the sun god.", correctAnswer: "FALSE", explanation: "The passage says it was 'dedicated to the moon god Nanna.'" },
        { number: 5, type: "true_false_not_given", text: "Greek architects used optical refinements to correct visual distortions.", correctAnswer: "TRUE", explanation: "The passage describes adjustments that 'corrected visual distortions.'" },
        { number: 6, type: "true_false_not_given", text: "The Pantheon's dome record was broken in the fifteenth century.", correctAnswer: "TRUE", explanation: "The passage says the record stood 'until the construction of Florence Cathedral's dome in 1436.'" },
        { number: 7, type: "true_false_not_given", text: "The Indus Valley civilisation was located in present-day China.", correctAnswer: "FALSE", explanation: "The passage says it was in 'present-day Pakistan and northwest India.'" },
        { number: 8, type: "true_false_not_given", text: "The Maya Pyramid of Kukulcán was built in the fifth century CE.", correctAnswer: "FALSE", explanation: "The passage says it was 'built around the tenth century CE.'" },
        { number: 9, type: "sentence_completion", text: "Each limestone block of the Great Pyramid weighed an average of ________ tonnes.", correctAnswer: "2.5", explanation: "The passage states 'each weighing an average of 2.5 tonnes.'" },
        { number: 10, type: "sentence_completion", text: "The three classical Greek orders are Doric, Ionic, and ________.", correctAnswer: "Corinthian", explanation: "The passage lists 'Doric, Ionic, and Corinthian.'" },
        { number: 11, type: "sentence_completion", text: "Roman concrete was made from volcanic ash, lime, and ________.", correctAnswer: "aggregate", explanation: "The passage says 'a mixture of volcanic ash, lime, and aggregate.'" },
        { number: 12, type: "sentence_completion", text: "The Indus Valley cities of Mohenjo-daro and ________ featured grid-patterned streets.", correctAnswer: "Harappa", explanation: "The passage mentions 'Mohenjo-daro and Harappa.'" },
        { number: 13, type: "sentence_completion", text: "During equinoxes at Chichén Itzá, sunlight creates the illusion of a ________ descending the staircase.", correctAnswer: "serpent", explanation: "The passage says 'the illusion of a serpent descending the northern staircase.'" }
      ]
    },
    {
      title: "Health and Sleep Science",
      text: `A. Sleep is one of the most fundamental biological processes, yet it remains one of the least understood. Every animal with a nervous system sleeps or enters a sleep-like state, suggesting that sleep serves essential functions that evolution has preserved across hundreds of millions of years. In humans, sleep occupies roughly one-third of life — an enormous investment of time that would be difficult to explain if it did not confer critical advantages.

B. Modern sleep science recognises two distinct types of sleep: rapid eye movement (REM) sleep and non-rapid eye movement (NREM) sleep, which is further divided into three stages of increasing depth. A typical night's sleep consists of four to six cycles, each lasting approximately ninety minutes, that alternate between NREM and REM phases. During NREM sleep, brain activity slows, muscles relax, and the body engages in physical repair processes including tissue growth, immune system strengthening, and hormone regulation. REM sleep, by contrast, is characterised by intense brain activity, vivid dreaming, and temporary paralysis of voluntary muscles.

C. The discovery of REM sleep in 1953 by Eugene Aserinsky and Nathaniel Kleitman at the University of Chicago revolutionised understanding of sleep's complexity. Before this discovery, sleep was widely regarded as a uniform state of unconsciousness. The identification of distinct sleep stages revealed that the sleeping brain is anything but passive — it cycles through highly organised patterns of neural activity that serve different physiological and cognitive functions.

D. Research over the past two decades has dramatically expanded understanding of sleep's role in cognitive function. Studies have shown that sleep is essential for memory consolidation — the process by which short-term memories are stabilised and integrated into long-term storage. During NREM sleep, the hippocampus — a brain structure critical for memory — replays patterns of neural activity from the preceding day, effectively transferring information to the neocortex for permanent storage. REM sleep appears to play a complementary role, facilitating the integration of new memories with existing knowledge and supporting creative problem-solving.

E. Sleep deprivation has profound effects on human performance and health. Even moderate sleep restriction — sleeping six hours instead of eight for several consecutive nights — significantly impairs attention, reaction time, and decision-making. Chronic sleep deprivation has been linked to increased risk of cardiovascular disease, diabetes, obesity, and depression. A landmark study published in 2003 found that people who slept fewer than six hours per night had a 13 per cent higher mortality risk than those who slept seven to eight hours.

F. The circadian rhythm — the body's internal clock — plays a central role in regulating sleep timing. This clock, located in the suprachiasmatic nucleus of the hypothalamus, operates on an approximately 24-hour cycle synchronised primarily by exposure to light. Morning light suppresses the production of melatonin, a hormone that promotes sleepiness, while darkness triggers its release. Modern lifestyles, however, increasingly disrupt circadian rhythms. Artificial lighting, shift work, and the blue light emitted by electronic screens all interfere with natural melatonin production, contributing to widespread sleep difficulties.

G. Adolescents face particular challenges. During puberty, the circadian clock shifts later, causing teenagers to naturally feel sleepy later at night and wake later in the morning. This biological shift conflicts with early school start times, resulting in chronic sleep deprivation among many secondary school students. Several studies have demonstrated that delaying school start times by even thirty minutes can significantly improve academic performance, attendance, and mental health outcomes.

H. The economic cost of insufficient sleep is staggering. A 2016 study by the RAND Corporation estimated that sleep deprivation costs the United States economy up to $411 billion annually through lost productivity, absenteeism, and health care expenditures. Japan, Germany, and the United Kingdom face proportionally similar losses. These figures have prompted growing interest among employers and policymakers in strategies to promote better sleep habits, including flexible work schedules, workplace nap facilities, and public health campaigns emphasising sleep hygiene.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Paragraph B", options: ["i. The economic burden of poor sleep", "ii. Teenagers and the shifted body clock", "iii. Sleep stages and their characteristics", "iv. How sleep aids memory", "v. The impact of light on sleep timing", "vi. Health consequences of sleep loss", "vii. A groundbreaking discovery", "viii. Strategies to improve national sleep habits"], correctAnswer: "iii", explanation: "Paragraph B describes REM and NREM sleep stages." },
        { number: 15, type: "matching_headings", text: "Paragraph D", options: ["i. The economic burden of poor sleep", "ii. Teenagers and the shifted body clock", "iii. Sleep stages and their characteristics", "iv. How sleep aids memory", "v. The impact of light on sleep timing", "vi. Health consequences of sleep loss", "vii. A groundbreaking discovery", "viii. Strategies to improve national sleep habits"], correctAnswer: "iv", explanation: "Paragraph D discusses sleep's role in memory consolidation." },
        { number: 16, type: "matching_headings", text: "Paragraph F", options: ["i. The economic burden of poor sleep", "ii. Teenagers and the shifted body clock", "iii. Sleep stages and their characteristics", "iv. How sleep aids memory", "v. The impact of light on sleep timing", "vi. Health consequences of sleep loss", "vii. A groundbreaking discovery", "viii. Strategies to improve national sleep habits"], correctAnswer: "v", explanation: "Paragraph F discusses circadian rhythm and light's role." },
        { number: 17, type: "matching_headings", text: "Paragraph H", options: ["i. The economic burden of poor sleep", "ii. Teenagers and the shifted body clock", "iii. Sleep stages and their characteristics", "iv. How sleep aids memory", "v. The impact of light on sleep timing", "vi. Health consequences of sleep loss", "vii. A groundbreaking discovery", "viii. Strategies to improve national sleep habits"], correctAnswer: "i", explanation: "Paragraph H provides economic cost figures for sleep deprivation." },
        { number: 18, type: "summary_completion", text: "REM sleep was discovered in ________ by Aserinsky and Kleitman.", correctAnswer: "1953", explanation: "The passage states 'The discovery of REM sleep in 1953.'" },
        { number: 19, type: "summary_completion", text: "During NREM sleep, the ________ replays neural activity patterns from the day.", correctAnswer: "hippocampus", explanation: "The passage says 'the hippocampus replays patterns of neural activity.'" },
        { number: 20, type: "summary_completion", text: "People sleeping fewer than six hours had a ________ per cent higher mortality risk.", correctAnswer: "13", explanation: "The passage states 'a 13 per cent higher mortality risk.'" },
        { number: 21, type: "summary_completion", text: "The body's internal clock is located in the suprachiasmatic nucleus of the ________.", correctAnswer: "hypothalamus", explanation: "The passage says it is 'located in the suprachiasmatic nucleus of the hypothalamus.'" },
        { number: 22, type: "short_answer", text: "How long does a typical sleep cycle last?", correctAnswer: "ninety minutes", explanation: "The passage says 'each lasting approximately ninety minutes.'" },
        { number: 23, type: "short_answer", text: "What hormone promotes sleepiness?", correctAnswer: "melatonin", explanation: "The passage identifies 'melatonin, a hormone that promotes sleepiness.'" },
        { number: 24, type: "short_answer", text: "How much did RAND estimate sleep deprivation costs the US economy annually?", correctAnswer: "$411 billion", explanation: "The passage states 'up to $411 billion annually.'" },
        { number: 25, type: "short_answer", text: "What type of light from electronic screens interferes with melatonin production?", correctAnswer: "blue light", explanation: "The passage mentions 'the blue light emitted by electronic screens.'" },
        { number: 26, type: "short_answer", text: "By how much can delaying school start times improve outcomes?", correctAnswer: "thirty minutes", explanation: "The passage says 'delaying school start times by even thirty minutes.'" }
      ]
    },
    {
      title: "Economic History and Trade",
      text: `The history of international trade is, in many ways, the history of civilisation itself. The exchange of goods across distances — from neighbouring villages to distant continents — has driven economic growth, cultural exchange, and political transformation for millennia. Understanding the evolution of trade illuminates not only how economies develop but also how societies interact, compete, and cooperate.

The earliest evidence of long-distance trade dates to the Neolithic period, when obsidian — a volcanic glass prized for making tools and weapons — was transported across hundreds of kilometres in the ancient Near East. By the third millennium BCE, sophisticated trading networks connected Mesopotamia with the Indus Valley, exchanging textiles, metals, and precious stones. The Phoenicians, based in present-day Lebanon, established a maritime trading empire that spanned the Mediterranean by the first millennium BCE, founding colonies in North Africa, Sicily, and Spain.

The Silk Road, a network of overland and maritime routes linking China with the Mediterranean, represents perhaps the most famous trading system in history. Established during the Han Dynasty around the second century BCE, the Silk Road facilitated the exchange of silk, spices, precious metals, and gemstones. But its significance extended far beyond commerce: religions, technologies, and diseases travelled along these routes, reshaping civilisations across Eurasia. Buddhism spread from India to China and Southeast Asia; papermaking technology moved from China westward; and the Black Death of the fourteenth century may have followed Silk Road trade routes from Central Asia to Europe.

The Age of Exploration, beginning in the fifteenth century, transformed trade from a predominantly regional activity into a truly global enterprise. Portuguese navigators established sea routes to West Africa, India, and eventually Southeast Asia, seeking direct access to the lucrative spice trade that had previously been controlled by Arab and Venetian intermediaries. Christopher Columbus's voyages to the Americas, beginning in 1492, initiated the Columbian Exchange — a massive transfer of plants, animals, diseases, and people between the Old World and the New that fundamentally altered ecosystems and demographics on both sides of the Atlantic.

The establishment of joint-stock companies in the seventeenth century marked a crucial institutional innovation in trade organisation. The British East India Company, chartered in 1600, and the Dutch East India Company (VOC), founded in 1602, pooled capital from multiple investors to finance trading voyages too expensive and risky for individual merchants. The VOC is often cited as the world's first multinational corporation and the first company to issue publicly traded shares. These organisations wielded enormous economic and political power, effectively governing territories and commanding private armies.

The Industrial Revolution of the eighteenth and nineteenth centuries dramatically expanded both the volume and nature of international trade. Mechanised manufacturing created unprecedented quantities of goods seeking overseas markets. Improvements in transportation — steamships, railways, and the opening of the Suez Canal in 1869 — reduced shipping costs and transit times. Britain, as the world's first industrial power, pursued a policy of free trade, reducing tariffs and opening its markets to foreign goods while exporting manufactured products worldwide.

The twentieth century saw the creation of international institutions designed to govern trade. The General Agreement on Tariffs and Trade (GATT), established in 1947, promoted tariff reduction and non-discriminatory trade among its members. Its successor, the World Trade Organization (WTO), founded in 1995, provides a framework for negotiating trade agreements and resolving disputes. Regional trade agreements — including the European Economic Community (later the EU), NAFTA (later USMCA), and ASEAN — have created zones of preferential trade access among neighbouring countries.

Today, international trade faces new challenges and opportunities. Digital commerce enables even small businesses to access global markets. Supply chain disruptions — highlighted by the COVID-19 pandemic — have prompted companies and governments to reconsider the risks of global interdependence. Debates about trade's distributional effects — who benefits and who loses — continue to shape politics in developed and developing countries alike.`,
      questions: [
        { number: 27, type: "table_completion", text: "In the Neolithic period, ________ was transported hundreds of kilometres for tool-making.", correctAnswer: "obsidian", explanation: "The passage says 'obsidian — a volcanic glass prized for making tools.'" },
        { number: 28, type: "table_completion", text: "The Phoenicians were based in present-day ________.", correctAnswer: "Lebanon", explanation: "The passage says 'based in present-day Lebanon.'" },
        { number: 29, type: "table_completion", text: "The Silk Road was established during the ________ Dynasty.", correctAnswer: "Han", explanation: "The passage says 'Established during the Han Dynasty.'" },
        { number: 30, type: "table_completion", text: "The Dutch East India Company was founded in ________.", correctAnswer: "1602", explanation: "The passage states it was 'founded in 1602.'" },
        { number: 31, type: "multiple_choice", text: "What was the Columbian Exchange?", options: ["A. A financial trading system between European banks", "B. A transfer of plants, animals, diseases, and people between hemispheres", "C. A diplomatic agreement between Spain and Portugal", "D. A route connecting China with Europe"], correctAnswer: "B", explanation: "The passage describes it as 'a massive transfer of plants, animals, diseases, and people.'" },
        { number: 32, type: "multiple_choice", text: "Why is the VOC historically significant?", options: ["A. It was the first company to use paper currency", "B. It discovered the Americas", "C. It is considered the first multinational corporation", "D. It invented the steam engine"], correctAnswer: "C", explanation: "The passage says the VOC 'is often cited as the world's first multinational corporation.'" },
        { number: 33, type: "multiple_choice", text: "Which canal opened in 1869 to reduce shipping costs?", options: ["A. Panama Canal", "B. Erie Canal", "C. Suez Canal", "D. Kiel Canal"], correctAnswer: "C", explanation: "The passage mentions 'the opening of the Suez Canal in 1869.'" },
        { number: 34, type: "multiple_choice", text: "What replaced GATT in 1995?", options: ["A. The United Nations", "B. The World Trade Organization", "C. The International Monetary Fund", "D. The World Bank"], correctAnswer: "B", explanation: "The passage says 'Its successor, the World Trade Organization (WTO), founded in 1995.'" },
        { number: 35, type: "sentence_completion", text: "Buddhism spread from India to China and ________ along the Silk Road.", correctAnswer: "Southeast Asia", explanation: "The passage says 'Buddhism spread from India to China and Southeast Asia.'" },
        { number: 36, type: "sentence_completion", text: "The Black Death may have followed Silk Road routes from ________ to Europe.", correctAnswer: "Central Asia", explanation: "The passage says it 'may have followed Silk Road trade routes from Central Asia to Europe.'" },
        { number: 37, type: "sentence_completion", text: "Portuguese navigators sought direct access to the lucrative ________ trade.", correctAnswer: "spice", explanation: "The passage says they were 'seeking direct access to the lucrative spice trade.'" },
        { number: 38, type: "sentence_completion", text: "Britain pursued a policy of ________ trade during the Industrial Revolution.", correctAnswer: "free", explanation: "The passage says 'Britain pursued a policy of free trade.'" },
        { number: 39, type: "sentence_completion", text: "The British East India Company was chartered in ________.", correctAnswer: "1600", explanation: "The passage states 'chartered in 1600.'" },
        { number: 40, type: "sentence_completion", text: "Supply chain disruptions were highlighted by the ________ pandemic.", correctAnswer: "COVID-19", explanation: "The passage says 'highlighted by the COVID-19 pandemic.'" }
      ]
    }
  ]
};
