import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_19: ReadingTest = {
  id: 19,
  passages: [
    {
      title: "The Evolution of Currency",
      text: `The history of currency is the history of humanity's search for a reliable, portable, and universally accepted medium of exchange. From the earliest barter systems to today's digital cryptocurrencies, the forms that money has taken have evolved dramatically, reflecting changes in technology, social organisation, economic complexity, and political power. Understanding the evolution of currency provides valuable insights into the forces that have shaped — and continue to shape — human civilisation.

Before the invention of currency, trade was conducted through barter — the direct exchange of goods and services. A farmer with surplus grain might trade it for a potter's clay vessels, or a herder might exchange livestock for tools. However, barter has significant limitations: it requires a "double coincidence of wants" — both parties must have something the other desires at the same time — and it is difficult to establish fair exchange rates between disparate goods. As societies grew larger and more complex, the inefficiencies of barter became increasingly problematic, creating a need for a standardised medium of exchange.

The earliest forms of currency were commodity monies — objects with intrinsic value that were widely accepted in trade. In many cultures, livestock — particularly cattle — served as an early form of money; the English word "pecuniary" derives from the Latin pecus, meaning cattle. Cowrie shells, small and durable marine shells, were used as currency across large parts of Africa, South Asia, and East Asia for thousands of years. Other commodity monies included salt (from which the word "salary" derives), tea bricks, grain, tobacco, and wampum (shell beads used by Indigenous peoples of North America).

The introduction of metal coinage represented a major advance in the evolution of currency. The earliest known coins were produced in the kingdom of Lydia (in modern-day western Turkey) around 600 BCE. These coins were made from electrum, a naturally occurring alloy of gold and silver, and were stamped with official marks guaranteeing their weight and purity. The use of coins spread rapidly across the ancient Mediterranean world, adopted and refined by the Greeks, Persians, and Romans. Coinage offered several advantages over commodity money: coins were portable, durable, divisible, and their value was standardised and guaranteed by a state authority, facilitating trade across long distances and between different cultures.

Paper money originated in China during the Tang Dynasty (618–907 CE), initially in the form of promissory notes issued by merchants and later formalised by the government. During the Song Dynasty (960–1279 CE), the Chinese government issued jiaozi — the world's first official government-backed paper currency — to address a shortage of copper for coinage. Paper money represented a fundamental conceptual shift: unlike coins, which had intrinsic value based on their metal content, paper notes derived their value entirely from the trust placed in the issuing authority's promise to honour them. This principle of fiduciary currency — money whose value is based on confidence rather than physical material — remains the foundation of all modern monetary systems.

The development of banking in medieval Europe created new forms of currency and financial instruments. Italian city-states such as Florence, Venice, and Genoa became centres of international banking, and institutions such as the Medici Bank facilitated trade by issuing bills of exchange — written orders to pay a specified sum at a future date or in another location — which reduced the need to transport large quantities of coins. The establishment of central banks, beginning with the Swedish Riksbank in 1668 and the Bank of England in 1694, formalised the relationship between governments and the monetary system, with central banks assuming responsibility for issuing currency, managing the money supply, and maintaining financial stability.

The gold standard, which linked the value of national currencies to a fixed quantity of gold, dominated the international monetary system from the mid-nineteenth century until the twentieth century. Under the gold standard, countries agreed to convert their currency into gold at a predetermined rate, providing a mechanism for stabilising exchange rates and facilitating international trade. The system was gradually abandoned during the twentieth century — first partially during the interwar period, and finally in 1971 when US President Richard Nixon suspended the convertibility of the dollar into gold, inaugurating the era of freely floating fiat currencies that persists today.

The twenty-first century has witnessed the emergence of digital and cryptocurrencies. Bitcoin, created by the pseudonymous Satoshi Nakamoto in 2009, introduced a decentralised digital currency based on blockchain technology — a distributed ledger that records transactions across a network of computers without the need for a central authority. Since Bitcoin's launch, thousands of cryptocurrencies have been created, and the total market capitalisation of the cryptocurrency market has at times exceeded $3 trillion. Central banks in numerous countries are also developing central bank digital currencies (CBDCs), which would combine the efficiency of digital payments with the stability and regulatory oversight of traditional fiat money.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "The main limitation of barter systems was that they", options: ["A could only be used for agricultural products.", "B required both parties to want what the other had.", "C were banned by early governments.", "D could not be used over long distances."], correctAnswer: "B", explanation: "The passage describes the 'double coincidence of wants' as barter's key limitation." },
        { number: 2, type: "multiple_choice", text: "The English word 'salary' derives from the use of which commodity as money?", options: ["A gold", "B cattle", "C salt", "D cowrie shells"], correctAnswer: "C", explanation: "The passage says 'salt (from which the word \"salary\" derives).'" },
        { number: 3, type: "multiple_choice", text: "The earliest known coins were made from", options: ["A pure gold.", "B copper.", "C bronze.", "D an alloy of gold and silver."], correctAnswer: "D", explanation: "The passage says coins were 'made from electrum, a naturally occurring alloy of gold and silver.'" },
        { number: 4, type: "multiple_choice", text: "Paper money represented a conceptual shift because it", options: ["A was more durable than coins.", "B could be used internationally.", "C derived its value from trust rather than material.", "D was controlled by merchants rather than governments."], correctAnswer: "C", explanation: "The passage says paper notes 'derived their value entirely from the trust placed in the issuing authority's promise.'" },
        { number: 5, type: "multiple_choice", text: "The gold standard was finally abandoned in", options: ["A 1914.", "B 1945.", "C 1971.", "D 2009."], correctAnswer: "C", explanation: "The passage says 'in 1971 when US President Richard Nixon suspended the convertibility.'" },
        { number: 6, type: "true_false_not_given", text: "Cowrie shells were used as currency only in Africa.", correctAnswer: "FALSE", explanation: "The passage says cowrie shells were used 'across large parts of Africa, South Asia, and East Asia.'" },
        { number: 7, type: "true_false_not_given", text: "The first coins were produced in ancient Greece.", correctAnswer: "FALSE", explanation: "The passage says the earliest coins were from 'the kingdom of Lydia,' not Greece." },
        { number: 8, type: "true_false_not_given", text: "The world's first paper currency was issued during the Song Dynasty.", correctAnswer: "TRUE", explanation: "The passage says 'During the Song Dynasty, the Chinese government issued jiaozi — the world's first official government-backed paper currency.'" },
        { number: 9, type: "true_false_not_given", text: "The Medici Bank was the largest bank in medieval Europe.", correctAnswer: "NOT GIVEN", explanation: "The passage mentions the Medici Bank but does not claim it was the largest." },
        { number: 10, type: "true_false_not_given", text: "The Swedish Riksbank was established before the Bank of England.", correctAnswer: "TRUE", explanation: "The passage says the Riksbank was established in 1668, the Bank of England in 1694." },
        { number: 11, type: "true_false_not_given", text: "Bitcoin was created by an individual whose real identity is publicly known.", correctAnswer: "FALSE", explanation: "The passage says Bitcoin was created by 'the pseudonymous Satoshi Nakamoto.'" },
        { number: 12, type: "true_false_not_given", text: "The total cryptocurrency market has exceeded $3 trillion at times.", correctAnswer: "TRUE", explanation: "The passage says it 'has at times exceeded $3 trillion.'" },
        { number: 13, type: "true_false_not_given", text: "All central banks have now launched their own digital currencies.", correctAnswer: "FALSE", explanation: "The passage says central banks 'are developing' CBDCs — they have not all launched them." },
      ],
    },
    {
      title: "Agricultural Innovation",
      text: `A. Agriculture has undergone continuous transformation since its origins approximately 10,000 years ago, with each era bringing new tools, techniques, and scientific understanding that have expanded humanity's capacity to produce food. Today, the pace of agricultural innovation is accelerating as the world confronts the challenge of feeding a population projected to reach nearly 10 billion by 2050, while simultaneously reducing agriculture's environmental footprint and adapting to the impacts of climate change.

B. The mechanisation of agriculture, which began in earnest during the eighteenth and nineteenth centuries, was one of the most significant transformations in farming history. The seed drill, invented by Jethro Tull around 1701, enabled seeds to be planted in neat rows at controlled depths, dramatically improving germination rates compared with the traditional method of broadcasting seeds by hand. The mechanical reaper, developed by Cyrus McCormick in the 1830s, allowed a single farmer to harvest as much grain as several labourers could cut by hand. The introduction of steam-powered and later diesel-powered tractors in the late nineteenth and early twentieth centuries replaced animal draught power on farms throughout the industrialised world, vastly increasing the area that a single farmer could cultivate.

C. The Green Revolution of the 1960s and 1970s represented a dramatic leap in agricultural productivity, driven by the development and dissemination of high-yielding varieties (HYVs) of staple crops, combined with the expanded use of synthetic fertilisers, chemical pesticides, and mechanised irrigation. The agronomist Norman Borlaug, who is credited with saving over one billion lives through his work on disease-resistant, high-yielding wheat varieties, was awarded the Nobel Peace Prize in 1970. The Green Revolution was particularly impactful in Asia, where rice and wheat yields doubled or tripled in countries including India, Pakistan, and the Philippines. However, the environmental costs of the Green Revolution — including soil degradation, water pollution, loss of genetic diversity, and dependence on fossil fuel-derived inputs — have prompted a reassessment of its legacy and a search for more sustainable approaches.

D. Genetic modification (GM) technology has enabled scientists to introduce specific traits into crop plants by transferring genes from other organisms — including bacteria, viruses, and unrelated plant species. The first commercially grown GM crop was the Flavr Savr tomato, approved in the United States in 1994, which was engineered for delayed ripening to extend shelf life. Today, the most widely grown GM crops are soybeans, maize, cotton, and canola, engineered primarily for herbicide tolerance (allowing farmers to spray fields with specific herbicides that kill weeds without harming the crop) and insect resistance (through the incorporation of genes from the bacterium Bacillus thuringiensis, or Bt, which produces proteins toxic to certain insect pests). GM crops are now cultivated on approximately 190 million hectares in 26 countries, though their adoption remains controversial, particularly in Europe, where consumer resistance and strict regulatory requirements have limited commercial cultivation.

E. Precision agriculture uses digital technologies — including GPS, satellite imagery, drones, soil sensors, and data analytics — to monitor and manage crop production at a highly granular level. Variable-rate technology (VRT) enables farmers to apply fertilisers, pesticides, and irrigation water in precise quantities tailored to the specific needs of different areas within a single field, reducing waste and environmental impact while optimising yields. Yield monitors fitted to combine harvesters create detailed maps of productivity variation across fields, enabling farmers to identify and address the causes of underperformance. The integration of machine learning and artificial intelligence into precision agriculture platforms is enabling predictive analytics — forecasting crop yields, pest outbreaks, and weather impacts with increasing accuracy — empowering farmers to make better-informed decisions.

F. Vertical farming and cellular agriculture represent two of the most radical innovations in food production. Vertical farms grow crops indoors in stacked layers under LED lighting, using hydroponic or aeroponic systems that circulate nutrient-rich water directly to plant roots without soil. These controlled environments can produce crops year-round, independent of weather and season, using up to 95 percent less water than conventional agriculture. Cellular agriculture takes an even more radical approach, producing animal products — including meat, dairy, and eggs — directly from cell cultures rather than from whole animals. The first cultured meat hamburger was produced by Professor Mark Post at Maastricht University in 2013 at a cost of $330,000; by 2023, regulatory approval for the commercial sale of cultured meat had been granted in Singapore and the United States, and production costs had fallen dramatically, though they remain higher than conventional meat.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Paragraph B", options: ["i. Growing food without soil or natural light", "ii. The introduction of machines to farming", "iii. High-yielding crop varieties and their consequences", "iv. Altering crop DNA for specific traits", "v. Using data to optimise farm management", "vi. The scale and urgency of agricultural challenges", "vii. Producing meat from cell cultures", "viii. Organic farming methods and their limitations"], correctAnswer: "ii", explanation: "Paragraph B describes the seed drill, mechanical reaper, and tractors — mechanisation." },
        { number: 15, type: "matching_headings", text: "Paragraph C", options: ["i. Growing food without soil or natural light", "ii. The introduction of machines to farming", "iii. High-yielding crop varieties and their consequences", "iv. Altering crop DNA for specific traits", "v. Using data to optimise farm management", "vi. The scale and urgency of agricultural challenges", "vii. Producing meat from cell cultures", "viii. Organic farming methods and their limitations"], correctAnswer: "iii", explanation: "Paragraph C describes the Green Revolution, HYVs, and their environmental costs." },
        { number: 16, type: "matching_headings", text: "Paragraph D", options: ["i. Growing food without soil or natural light", "ii. The introduction of machines to farming", "iii. High-yielding crop varieties and their consequences", "iv. Altering crop DNA for specific traits", "v. Using data to optimise farm management", "vi. The scale and urgency of agricultural challenges", "vii. Producing meat from cell cultures", "viii. Organic farming methods and their limitations"], correctAnswer: "iv", explanation: "Paragraph D discusses genetic modification and transferring genes into crop plants." },
        { number: 17, type: "matching_headings", text: "Paragraph E", options: ["i. Growing food without soil or natural light", "ii. The introduction of machines to farming", "iii. High-yielding crop varieties and their consequences", "iv. Altering crop DNA for specific traits", "v. Using data to optimise farm management", "vi. The scale and urgency of agricultural challenges", "vii. Producing meat from cell cultures", "viii. Organic farming methods and their limitations"], correctAnswer: "v", explanation: "Paragraph E describes precision agriculture using GPS, sensors, and data analytics." },
        { number: 18, type: "matching_headings", text: "Paragraph F", options: ["i. Growing food without soil or natural light", "ii. The introduction of machines to farming", "iii. High-yielding crop varieties and their consequences", "iv. Altering crop DNA for specific traits", "v. Using data to optimise farm management", "vi. The scale and urgency of agricultural challenges", "vii. Producing meat from cell cultures", "viii. Organic farming methods and their limitations"], correctAnswer: "i", explanation: "Paragraph F describes vertical farming (indoors, under LED lighting) and cellular agriculture." },
        { number: 19, type: "table_completion", text: "The seed drill was invented by Jethro Tull around _______.", correctAnswer: "1701", explanation: "The passage says 'around 1701.'" },
        { number: 20, type: "table_completion", text: "Norman Borlaug was awarded the Nobel _______ Prize in 1970.", correctAnswer: "Peace", explanation: "The passage says 'was awarded the Nobel Peace Prize in 1970.'" },
        { number: 21, type: "table_completion", text: "The first commercially grown GM crop was the Flavr Savr _______.", correctAnswer: "tomato", explanation: "The passage says 'the Flavr Savr tomato.'" },
        { number: 22, type: "table_completion", text: "GM crops are cultivated in _______ countries.", correctAnswer: "26", explanation: "The passage states 'in 26 countries.'" },
        { number: 23, type: "table_completion", text: "Bt genes produce proteins toxic to certain _______ pests.", correctAnswer: "insect", explanation: "The passage says 'proteins toxic to certain insect pests.'" },
        { number: 24, type: "table_completion", text: "The first cultured meat hamburger was produced in _______.", correctAnswer: "2013", explanation: "The passage says 'produced in 2013.'" },
        { number: 25, type: "table_completion", text: "The first cultured hamburger cost $_______.", correctAnswer: "330,000", explanation: "The passage says 'at a cost of $330,000.'" },
        { number: 26, type: "table_completion", text: "Norman Borlaug is credited with saving over _______ billion lives.", correctAnswer: "one", explanation: "The passage says 'saving over one billion lives.'" },
      ],
    },
    {
      title: "Space Technology Development",
      text: `Space technology has advanced at a remarkable pace since the dawn of the Space Age in the 1950s, evolving from rudimentary rockets and simple satellites into sophisticated systems that underpin modern communications, navigation, weather forecasting, scientific research, and national security. The development of space technology has been shaped by geopolitical competition, scientific ambition, commercial opportunity, and the enduring human desire to explore the unknown.

A. The foundations of modern rocketry were laid in the early twentieth century by three visionary pioneers, working largely independently. Konstantin Tsiolkovsky, a Russian schoolteacher, published theoretical papers on rocket propulsion and space travel as early as 1903, deriving the fundamental equation governing rocket performance that still bears his name. Robert Goddard, an American physicist, built and launched the world's first liquid-fuelled rocket in March 1926, which flew for 2.5 seconds and reached an altitude of 12.5 metres. Hermann Oberth, a Romanian-born German physicist, published influential works on the mathematics of space flight and inspired a generation of German rocket engineers, including Wernher von Braun, who would later develop the V-2 rocket and, after emigrating to the United States, lead the development of the Saturn V rocket that carried Apollo astronauts to the Moon.

B. Satellite technology has become the invisible backbone of modern civilisation. The first artificial satellite, Sputnik 1, was launched by the Soviet Union on 4 October 1957, weighing just 83.6 kilograms and orbiting the Earth every 96 minutes. Today, over 10,000 active satellites orbit the Earth, providing services that are woven into the fabric of daily life. Communication satellites relay telephone calls, television broadcasts, and internet traffic across continents and oceans. Weather satellites enable accurate forecasting that saves lives and supports economic planning. Earth observation satellites monitor deforestation, glacier melt, ocean temperatures, urban growth, and agricultural conditions, providing critical data for environmental management and disaster response.

C. Human spaceflight has captured public imagination like no other aspect of space technology. The International Space Station (ISS), which has been continuously occupied since November 2000, has hosted over 270 crew members from 21 countries and served as a laboratory for over 3,000 scientific experiments. Research conducted on the ISS has contributed to advances in fields including protein crystallography, materials science, human physiology, and Earth observation. The ISS is scheduled for decommissioning in the early 2030s, and plans are under way for commercial space stations operated by companies such as Axiom Space and Orbital Reef (a joint venture of Blue Origin and Sierra Space) to take its place.

D. Robotic space exploration has extended humanity's reach to every planet in the solar system and beyond. NASA's Voyager 1 probe, launched in 1977, has entered interstellar space — the region between stars — becoming the most distant human-made object, at over 24 billion kilometres from Earth. Mars has been the primary target of robotic exploration, with NASA's Perseverance rover (landed 2021) actively searching for signs of ancient microbial life and collecting rock samples for eventual return to Earth. The James Webb Space Telescope (JWST), launched in December 2021 and positioned 1.5 million kilometres from Earth, is providing unprecedented observations of the early universe, exoplanet atmospheres, and the formation of stars and galaxies.

E. The commercialisation of space has accelerated dramatically in the twenty-first century. SpaceX has reduced the cost of launching payloads to orbit by developing reusable rockets, with its Falcon 9 booster having been reflown over 200 times. The company's Starlink constellation, comprising over 5,000 satellites, is providing broadband internet to remote and underserved areas worldwide. Blue Origin and Virgin Galactic have opened the door to space tourism, with paying customers experiencing suborbital flights and brief periods of weightlessness. The global space economy was valued at approximately $469 billion in 2022, and projections suggest it could exceed $1 trillion by the early 2030s.

F. The next frontiers of space technology include the return of humans to the Moon, the eventual crewed exploration of Mars, and the development of space-based resources. NASA's Artemis programme is working to establish a sustainable human presence on the Moon, using it as a staging point for deeper space exploration. Several companies and national space agencies are investigating the feasibility of asteroid mining — extracting valuable minerals and metals from near-Earth asteroids — which could potentially supply raw materials worth trillions of dollars. The challenges are enormous: the harsh radiation environment of deep space, the physiological effects of prolonged microgravity, the distances involved, and the cost of sustaining human life far from Earth all present formidable technical and logistical hurdles. Yet the rapid pace of innovation in space technology suggests that ambitions once confined to science fiction may become reality within the coming decades.`,
      questions: [
        { number: 27, type: "matching_information", text: "Plans for privately operated space stations to replace the ISS", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "C", explanation: "Paragraph C mentions Axiom Space and Orbital Reef as commercial replacements." },
        { number: 28, type: "matching_information", text: "A probe that has left the solar system", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "D", explanation: "Paragraph D describes Voyager 1 entering 'interstellar space.'" },
        { number: 29, type: "matching_information", text: "The total value of the global space industry", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "E", explanation: "Paragraph E states 'valued at approximately $469 billion in 2022.'" },
        { number: 30, type: "matching_information", text: "The possibility of extracting minerals from objects in space", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "F", explanation: "Paragraph F discusses 'asteroid mining — extracting valuable minerals and metals.'" },
        { number: 31, type: "matching_information", text: "The first person to successfully launch a liquid-fuelled rocket", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "A", explanation: "Paragraph A describes Robert Goddard launching 'the world's first liquid-fuelled rocket.'" },
        { number: 32, type: "short_answer", text: "What was the weight of Sputnik 1?", correctAnswer: "83.6 kilograms", explanation: "The passage says 'weighing just 83.6 kilograms.'" },
        { number: 33, type: "short_answer", text: "How many active satellites currently orbit the Earth?", correctAnswer: "over 10,000", explanation: "The passage states 'over 10,000 active satellites orbit the Earth.'" },
        { number: 34, type: "short_answer", text: "How many scientific experiments have been conducted on the ISS?", correctAnswer: "over 3,000", explanation: "The passage says 'over 3,000 scientific experiments.'" },
        { number: 35, type: "short_answer", text: "How far is Voyager 1 from Earth?", correctAnswer: "over 24 billion kilometres", explanation: "The passage says 'over 24 billion kilometres from Earth.'" },
        { number: 36, type: "short_answer", text: "How many times has the Falcon 9 booster been reflown?", correctAnswer: "over 200", explanation: "The passage states 'reflown over 200 times.'" },
        { number: 37, type: "short_answer", text: "How many satellites are in the Starlink constellation?", correctAnswer: "over 5,000", explanation: "The passage says 'comprising over 5,000 satellites.'" },
        { number: 38, type: "short_answer", text: "What was the value of the global space economy in 2022?", correctAnswer: "$469 billion", explanation: "The passage states 'valued at approximately $469 billion in 2022.'" },
        { number: 39, type: "short_answer", text: "How far from Earth is the James Webb Space Telescope positioned?", correctAnswer: "1.5 million kilometres", explanation: "The passage says 'positioned 1.5 million kilometres from Earth.'" },
        { number: 40, type: "short_answer", text: "In what year was Goddard's first liquid-fuelled rocket launched?", correctAnswer: "1926", explanation: "The passage says 'in March 1926.'" },
      ],
    },
  ],
};
