import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_45: ReadingTest = {
  id: 45,
  passages: [
    {
      title: "History of Aviation",
      text: `The dream of human flight is as old as civilisation itself. Ancient myths — Icarus in Greece, the flying carpet in Arabian folklore, the Vimana in Hindu scripture — testify to humanity's enduring desire to escape the bonds of gravity. Yet it was only in the closing years of the nineteenth century that advances in engineering, materials science, and aerodynamic theory brought powered flight within practical reach.

The modern story of aviation begins with the work of Sir George Cayley, an English baronet who, in 1799, sketched the first design for a fixed-wing aircraft with separate systems for lift, propulsion, and control — the fundamental configuration that all modern aeroplanes follow. Cayley built and flew several gliders over the following decades, including one in 1853 that reportedly carried his coachman across a small valley, making it arguably the first manned glider flight in history.

Otto Lilienthal, a German engineer, advanced the science of flight more than any other individual before the Wright brothers. Between 1891 and 1896, Lilienthal made more than 2,000 glider flights from artificial hills near Berlin, systematically testing wing shapes and documenting their lift and drag characteristics. His published data provided an invaluable resource for later experimenters. Lilienthal died in a glider crash in 1896, but his work inspired a generation of aviation pioneers, including Orville and Wilbur Wright.

The Wright brothers' achievement on 17 December 1903 at Kitty Hawk, North Carolina, represents the pivotal moment in aviation history. Their Flyer, a biplane powered by a twelve-horsepower petrol engine of their own design, made four flights that day, the longest lasting fifty-nine seconds and covering 260 metres. The Wrights' key innovation was three-axis control — the ability to control the aircraft's roll, pitch, and yaw simultaneously — a principle that remains fundamental to aircraft design today.

The First World War accelerated the development of aviation from a novelty into a military necessity. By 1918, aircraft had evolved from fragile biplanes capable of little more than observation into specialised fighters, bombers, and reconnaissance platforms. Engine power increased dramatically, and speeds rose from roughly 100 kilometres per hour at the start of the war to over 200 kilometres per hour by its end. The war also demonstrated the strategic potential of air power, a lesson that would be exploited far more extensively in the Second World War.

The interwar period saw the birth of commercial aviation. In 1919, the first scheduled international airline service began between London and Paris, operated by Aircraft Transport and Travel Ltd. The Douglas DC-3, introduced in 1936, was the aircraft that made commercial air travel economically viable: it could carry twenty-one passengers at a cruising speed of 310 kilometres per hour and had the range to cross the United States with just three refuelling stops. By 1939, airlines were carrying more than three million passengers annually.

The jet age began on 27 July 1949 with the maiden flight of the de Havilland Comet, the world's first commercial jet airliner. Although the Comet suffered a series of catastrophic structural failures that grounded the fleet, the lessons learned led to safer designs. The Boeing 707, introduced in 1958, established the template for modern jet travel: swept wings, podded engines, and a pressurised cabin capable of cruising at altitudes above 10,000 metres. Air travel became accessible to the middle class, and by the end of the twentieth century, airlines were carrying more than 1.5 billion passengers per year.

Today, the aviation industry faces the challenge of decarbonisation. Commercial aviation accounts for approximately two to three per cent of global carbon dioxide emissions, and the sector is exploring solutions including sustainable aviation fuels, hydrogen propulsion, electric aircraft for short routes, and improved air-traffic management to reduce fuel consumption. The history of aviation suggests that technological challenges that once seemed insurmountable — heavier-than-air flight, transatlantic travel, supersonic speed — can be overcome with sufficient ingenuity and determination.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "Who sketched the first design for a fixed-wing aircraft in 1799?", options: ["A Otto Lilienthal", "B The Wright brothers", "C Sir George Cayley", "D Louis Blériot"], correctAnswer: "C", explanation: "The passage says 'Sir George Cayley, an English baronet who, in 1799, sketched the first design.'" },
        { number: 2, type: "multiple_choice", text: "How many glider flights did Lilienthal make?", options: ["A Over 500", "B Over 1,000", "C Over 2,000", "D Over 5,000"], correctAnswer: "C", explanation: "The passage says 'more than 2,000 glider flights.'" },
        { number: 3, type: "multiple_choice", text: "What was the Wright brothers' key innovation?", options: ["A The jet engine", "B Three-axis control", "C Retractable landing gear", "D Swept-wing design"], correctAnswer: "B", explanation: "The passage says 'The Wrights' key innovation was three-axis control.'" },
        { number: 4, type: "multiple_choice", text: "Which aircraft made commercial air travel economically viable?", options: ["A De Havilland Comet", "B Boeing 707", "C Douglas DC-3", "D Concorde"], correctAnswer: "C", explanation: "The passage says 'The Douglas DC-3... was the aircraft that made commercial air travel economically viable.'" },
        { number: 5, type: "sentence_completion", text: "The longest Wright brothers flight at Kitty Hawk lasted __(5)__ seconds.", correctAnswer: "fifty-nine", explanation: "The passage says 'the longest lasting fifty-nine seconds.'" },
        { number: 6, type: "sentence_completion", text: "The first scheduled international airline service operated between London and __(6)__.", correctAnswer: "Paris", explanation: "The passage says 'between London and Paris.'" },
        { number: 7, type: "sentence_completion", text: "The DC-3 could carry __(7)__ passengers.", correctAnswer: "twenty-one", explanation: "The passage says 'carry twenty-one passengers.'" },
        { number: 8, type: "sentence_completion", text: "The de Havilland Comet's maiden flight was on 27 July __(8)__.", correctAnswer: "1949", explanation: "The passage says '27 July 1949.'" },
        { number: 9, type: "sentence_completion", text: "The Boeing 707 was introduced in __(9)__.", correctAnswer: "1958", explanation: "The passage says 'introduced in 1958.'" },
        { number: 10, type: "sentence_completion", text: "By 1939, airlines were carrying more than __(10)__ million passengers annually.", correctAnswer: "three", explanation: "The passage says 'more than three million passengers annually.'" },
        { number: 11, type: "sentence_completion", text: "Lilienthal died in a glider __(11)__ in 1896.", correctAnswer: "crash", explanation: "The passage says 'died in a glider crash in 1896.'" },
        { number: 12, type: "sentence_completion", text: "By the end of the twentieth century, airlines carried more than __(12)__ billion passengers per year.", correctAnswer: "1.5", explanation: "The passage says 'more than 1.5 billion passengers per year.'" },
        { number: 13, type: "sentence_completion", text: "The Wright Flyer was powered by a __(13)__-horsepower engine.", correctAnswer: "twelve", explanation: "The passage says 'a twelve-horsepower petrol engine.'" },
      ],
    },
    {
      title: "Environmental Policies",
      text: `A. Environmental policy has evolved from a marginal concern to a central pillar of governance in most countries over the past half-century. The modern environmental movement is often traced to the publication of Rachel Carson's Silent Spring in 1962, which documented the devastating effects of pesticides — particularly DDT — on wildlife and human health. The book catalysed public awareness and political action, contributing to the establishment of the United States Environmental Protection Agency (EPA) in 1970 and the passage of landmark legislation including the Clean Air Act (1970) and the Clean Water Act (1972).

B. International environmental cooperation began in earnest at the 1972 United Nations Conference on the Human Environment in Stockholm, which produced a declaration of principles and led to the creation of the United Nations Environment Programme (UNEP). Stockholm placed the environment on the global diplomatic agenda for the first time, recognising that pollution, resource depletion, and habitat destruction transcend national boundaries and require coordinated international responses.

C. The Montreal Protocol, signed in 1987, is widely regarded as the most successful international environmental agreement. The treaty committed signatory nations to phasing out the production and consumption of ozone-depleting substances, primarily chlorofluorocarbons (CFCs) used in refrigeration, aerosols, and industrial processes. Thanks to near-universal compliance, the concentration of ozone-depleting substances in the atmosphere has declined steadily, and scientists project that the ozone layer will recover to pre-1980 levels by approximately 2066.

D. Climate policy has proven far more contentious. The United Nations Framework Convention on Climate Change (UNFCCC), adopted at the 1992 Earth Summit in Rio de Janeiro, established the principle that nations have a common but differentiated responsibility to reduce greenhouse-gas emissions. The Kyoto Protocol, agreed in 1997, set binding emission-reduction targets for developed countries but excluded developing nations, a distinction that drew criticism from the United States, which never ratified the treaty.

E. The Paris Agreement, adopted in 2015, represented a new approach. Rather than imposing top-down targets, it invited every country to submit its own Nationally Determined Contribution (NDC) — a voluntary emission-reduction pledge — and established a mechanism for ratcheting up ambition over time through five-yearly review cycles. As of 2024, 195 countries have ratified the agreement, but analysis by Climate Action Tracker indicates that current NDCs, even if fully implemented, would result in warming of approximately 2.5 to 2.9 degrees Celsius by 2100 — well above the agreement's goal of limiting warming to 1.5 degrees.

F. Carbon pricing has emerged as a key policy instrument. Emissions trading systems (ETS), also known as cap-and-trade schemes, set an overall cap on emissions and allow companies to buy and sell permits within that cap, creating a financial incentive to reduce pollution. The European Union Emissions Trading System (EU ETS), launched in 2005, is the world's largest carbon market, covering roughly forty per cent of EU emissions. Carbon taxes, an alternative approach, set a direct price per tonne of CO2 emitted. As of 2023, more than seventy carbon-pricing initiatives were in operation or scheduled for implementation worldwide, covering approximately twenty-three per cent of global greenhouse-gas emissions.

G. Nature-based solutions — protecting, restoring, and sustainably managing ecosystems — are increasingly recognised as essential components of environmental policy. Forests, wetlands, mangroves, and seagrass meadows absorb and store significant quantities of carbon, and their conservation delivers co-benefits including biodiversity protection, flood mitigation, and improved water quality. The Kunming-Montreal Global Biodiversity Framework, adopted in 2022, commits nations to protecting thirty per cent of the world's land and ocean areas by 2030.

H. Effective environmental policy requires not only ambitious targets but also robust implementation, enforcement, and monitoring. Many countries have adopted strong environmental legislation on paper but lack the institutional capacity or political will to enforce it. Civil society organisations, the media, and an informed public play vital roles in holding governments and corporations accountable. As environmental challenges — climate change, biodiversity loss, pollution — grow more urgent, the quality and courage of environmental policymaking will be a defining test of governance in the twenty-first century.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Section A", options: ["I. The success of ozone protection", "II. The birth of modern environmentalism", "III. The beginning of global environmental diplomacy", "IV. Pricing carbon emissions", "V. Climate negotiations and disagreements", "VI. Using nature to address environmental problems", "VII. The Paris Agreement approach", "VIII. Challenges in policy enforcement"], correctAnswer: "II", explanation: "Section A discusses Silent Spring and the birth of the modern environmental movement." },
        { number: 15, type: "matching_headings", text: "Section B", options: ["I. The success of ozone protection", "II. The birth of modern environmentalism", "III. The beginning of global environmental diplomacy", "IV. Pricing carbon emissions", "V. Climate negotiations and disagreements", "VI. Using nature to address environmental problems", "VII. The Paris Agreement approach", "VIII. Challenges in policy enforcement"], correctAnswer: "III", explanation: "Section B discusses the 1972 Stockholm conference." },
        { number: 16, type: "matching_headings", text: "Section C", options: ["I. The success of ozone protection", "II. The birth of modern environmentalism", "III. The beginning of global environmental diplomacy", "IV. Pricing carbon emissions", "V. Climate negotiations and disagreements", "VI. Using nature to address environmental problems", "VII. The Paris Agreement approach", "VIII. Challenges in policy enforcement"], correctAnswer: "I", explanation: "Section C discusses the Montreal Protocol's success." },
        { number: 17, type: "matching_headings", text: "Section D", options: ["I. The success of ozone protection", "II. The birth of modern environmentalism", "III. The beginning of global environmental diplomacy", "IV. Pricing carbon emissions", "V. Climate negotiations and disagreements", "VI. Using nature to address environmental problems", "VII. The Paris Agreement approach", "VIII. Challenges in policy enforcement"], correctAnswer: "V", explanation: "Section D discusses contentious climate negotiations." },
        { number: 18, type: "matching_headings", text: "Section E", options: ["I. The success of ozone protection", "II. The birth of modern environmentalism", "III. The beginning of global environmental diplomacy", "IV. Pricing carbon emissions", "V. Climate negotiations and disagreements", "VI. Using nature to address environmental problems", "VII. The Paris Agreement approach", "VIII. Challenges in policy enforcement"], correctAnswer: "VII", explanation: "Section E discusses the Paris Agreement." },
        { number: 19, type: "matching_headings", text: "Section F", options: ["I. The success of ozone protection", "II. The birth of modern environmentalism", "III. The beginning of global environmental diplomacy", "IV. Pricing carbon emissions", "V. Climate negotiations and disagreements", "VI. Using nature to address environmental problems", "VII. The Paris Agreement approach", "VIII. Challenges in policy enforcement"], correctAnswer: "IV", explanation: "Section F discusses carbon pricing mechanisms." },
        { number: 20, type: "table_completion", text: "Rachel Carson's Silent Spring was published in __(20)__.", correctAnswer: "1962", explanation: "The passage says 'published... in 1962.'" },
        { number: 21, type: "table_completion", text: "The Montreal Protocol was signed in __(21)__.", correctAnswer: "1987", explanation: "The passage says 'signed in 1987.'" },
        { number: 22, type: "table_completion", text: "The ozone layer is projected to recover by approximately __(22)__.", correctAnswer: "2066", explanation: "The passage says 'by approximately 2066.'" },
        { number: 23, type: "table_completion", text: "The EU ETS covers roughly __(23)__ per cent of EU emissions.", correctAnswer: "forty", explanation: "The passage says 'roughly forty per cent.'" },
        { number: 24, type: "table_completion", text: "Current NDCs would result in warming of approximately __(24)__ to 2.9 degrees.", correctAnswer: "2.5", explanation: "The passage says 'approximately 2.5 to 2.9 degrees Celsius.'" },
        { number: 25, type: "table_completion", text: "As of 2024, __(25)__ countries have ratified the Paris Agreement.", correctAnswer: "195", explanation: "The passage says '195 countries have ratified.'" },
        { number: 26, type: "table_completion", text: "Carbon-pricing initiatives cover approximately __(26)__ per cent of global emissions.", correctAnswer: "twenty-three", explanation: "The passage says 'approximately twenty-three per cent.'" },
      ],
    },
    {
      title: "Nanorobots in Medicine",
      text: `Nanorobots — microscopic machines typically ranging from one to one hundred nanometres in size — represent one of the most ambitious frontiers of medical technology. Although fully autonomous nanorobots remain largely theoretical, rapid advances in nanotechnology, materials science, and bioengineering are bringing the concept closer to clinical reality. Researchers around the world are developing nanoscale devices capable of navigating the human body, diagnosing diseases at the cellular level, and delivering therapeutic agents with pinpoint precision.

A. The concept of medical nanorobots was popularised by the physicist Richard Feynman in his famous 1959 lecture "There's Plenty of Room at the Bottom," in which he envisioned the possibility of building machines small enough to operate inside living cells. The idea was further developed by K. Eric Drexler in his 1986 book Engines of Creation, which outlined a vision of molecular manufacturing and programmable nanoscale assemblers. While Drexler's most ambitious proposals remain speculative, his work stimulated research into nanoscale engineering that has yielded practical results.

B. One of the most promising applications of nanorobots is targeted drug delivery. Conventional drug administration — swallowing a pill or receiving an injection — distributes medication throughout the body, exposing healthy tissues to potentially toxic substances. Nanorobots could be programmed to travel through the bloodstream, identify diseased cells by recognising specific molecular markers on their surfaces, and release their drug payload directly at the site of disease. This approach could dramatically improve the efficacy of treatments for cancer, cardiovascular disease, and infections while reducing side effects.

C. Several research groups have demonstrated proof-of-concept nanorobots in laboratory and animal studies. In 2018, researchers at Arizona State University and the National Center for Nanoscience and Technology in China developed DNA nanorobots that successfully targeted and cut off the blood supply to tumours in mice. The nanorobots were constructed from folded DNA strands — a technique known as DNA origami — and were programmed to release the blood-clotting enzyme thrombin when they encountered a protein found exclusively on the surface of tumour blood vessels. The tumours shrank significantly, and no adverse effects were observed in healthy tissues.

D. Nanorobots powered by external energy sources are another active area of research. Magnetically driven nanorobots can be guided through the body using external magnetic fields, allowing clinicians to steer them to specific locations with high precision. Researchers at ETH Zurich have developed helical nanorobots, inspired by the flagella of bacteria, that can swim through bodily fluids when rotated by a magnetic field. These devices have been tested in animal models and show promise for applications including clearing blood clots, delivering drugs to the brain, and performing minimally invasive biopsies.

E. Diagnostic nanorobots could revolutionise the detection of disease. Nanoscale sensors circulating in the bloodstream could continuously monitor biomarkers associated with cancer, diabetes, or infectious disease, providing real-time health data and alerting patients and physicians to problems at the earliest possible stage. Some researchers envision implantable nanoscale devices that communicate wirelessly with smartphones or medical monitoring systems, creating a form of continuous, non-invasive health surveillance.

F. The challenges facing medical nanorobotics are formidable. Biocompatibility — ensuring that nanorobots do not trigger immune responses, toxicity, or inflammation — is a critical requirement. The body's immune system is highly efficient at identifying and destroying foreign particles, and nanorobots must be designed to evade detection or be made from biocompatible materials that the immune system tolerates. Powering nanorobots within the body is another unsolved problem: most current designs rely on external energy sources, but researchers are exploring the use of biochemical fuels — glucose, for example — that are naturally available in bodily fluids.

G. Regulatory and ethical considerations add further complexity. No regulatory framework currently exists specifically for medical nanorobots, and existing approval pathways for drugs and medical devices may not be adequate for devices that combine elements of both. Questions about long-term safety — what happens to nanorobots after they have completed their mission? Can they be reliably retrieved or broken down? — must be answered before clinical trials can proceed. Ethical concerns about surveillance, consent, and equitable access parallel those raised by other emerging medical technologies.

H. Despite these obstacles, the field is advancing rapidly. Global investment in nanomedicine research continues to grow, and the convergence of nanotechnology with artificial intelligence, synthetic biology, and advanced imaging is creating new possibilities that were inconceivable even a decade ago. While fully autonomous medical nanorobots may still be years or decades away, the incremental advances being made today — in targeted drug delivery, nanoscale imaging, and biocompatible materials — are laying the groundwork for a medical revolution that could fundamentally transform how diseases are diagnosed and treated.`,
      questions: [
        { number: 27, type: "matching_information", text: "A description of DNA-based nanorobots tested on tumours in mice", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "C", explanation: "Paragraph C describes DNA nanorobots that targeted tumours in mice." },
        { number: 28, type: "matching_information", text: "The challenge of avoiding immune system detection", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "F", explanation: "Paragraph F discusses biocompatibility and immune system evasion." },
        { number: 29, type: "matching_information", text: "The concept of continuous health monitoring using nanoscale sensors", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "E", explanation: "Paragraph E discusses diagnostic nanorobots for continuous monitoring." },
        { number: 30, type: "matching_information", text: "Nanorobots that can be steered using magnetic fields", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "D", explanation: "Paragraph D discusses magnetically driven nanorobots." },
        { number: 31, type: "matching_information", text: "The origins of the nanorobot concept in a famous lecture", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "A", explanation: "Paragraph A discusses Feynman's 1959 lecture." },
        { number: 32, type: "matching_information", text: "Regulatory gaps for nanorobot approval", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "G", explanation: "Paragraph G discusses the lack of regulatory frameworks." },
        { number: 33, type: "multiple_choice", text: "What technique was used to construct the DNA nanorobots?", options: ["A CRISPR gene editing", "B DNA origami", "C Protein engineering", "D Lithography"], correctAnswer: "B", explanation: "The passage says 'a technique known as DNA origami.'" },
        { number: 34, type: "multiple_choice", text: "What enzyme did the DNA nanorobots release?", options: ["A Insulin", "B Lipase", "C Thrombin", "D Amylase"], correctAnswer: "C", explanation: "The passage says 'release the blood-clotting enzyme thrombin.'" },
        { number: 35, type: "multiple_choice", text: "What inspired the helical nanorobots developed at ETH Zurich?", options: ["A Human blood cells", "B Bacterial flagella", "C DNA strands", "D Viral structures"], correctAnswer: "B", explanation: "The passage says 'inspired by the flagella of bacteria.'" },
        { number: 36, type: "multiple_choice", text: "What biochemical fuel are researchers exploring for powering nanorobots?", options: ["A Oxygen", "B ATP", "C Glucose", "D Amino acids"], correctAnswer: "C", explanation: "The passage mentions 'biochemical fuels — glucose, for example.'" },
        { number: 37, type: "short_answer", text: "In what year did Richard Feynman deliver his famous lecture?", correctAnswer: "1959", explanation: "The passage says 'his famous 1959 lecture.'" },
        { number: 38, type: "short_answer", text: "What book did K. Eric Drexler publish in 1986?", correctAnswer: "Engines of Creation", explanation: "The passage says 'his 1986 book Engines of Creation.'" },
        { number: 39, type: "short_answer", text: "What happened to the tumours in mice after DNA nanorobot treatment?", correctAnswer: "they shrank significantly", explanation: "The passage says 'The tumours shrank significantly.'" },
        { number: 40, type: "short_answer", text: "What institution developed the helical nanorobots?", correctAnswer: "ETH Zurich", explanation: "The passage says 'Researchers at ETH Zurich.'" },
      ],
    },
  ],
};
