import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_60: ReadingTest = {
  id: 60,
  passages: [
    {
      title: "Glaciers and Climate Science",
      text: `Glaciers are among the most powerful and visible indicators of climate change on Earth. These vast rivers of compressed ice, formed over centuries from accumulated snowfall, cover approximately 10 percent of the planet's land surface and contain roughly 69 percent of all the fresh water on Earth. As global temperatures rise, glaciers around the world are retreating at unprecedented rates, providing scientists with compelling and visually dramatic evidence of a warming planet — and raising urgent concerns about sea-level rise, water security, and the disruption of ecosystems that depend on glacial meltwater.

A glacier forms when snow accumulates faster than it melts over many years, gradually compressing under its own weight into dense, crystalline ice. This process typically requires decades to centuries, depending on snowfall rates and temperatures. Glaciers are found in two primary settings: alpine glaciers, which form in mountain valleys and flow downhill under the influence of gravity, and ice sheets, which are continental-scale masses of ice that cover vast areas of land. The only existing ice sheets today are those covering Greenland and Antarctica, which together contain enough ice to raise global sea levels by approximately 65 metres if fully melted. Alpine glaciers, though far smaller individually, are found on every continent except Australia and collectively contribute significantly to regional water supplies, particularly in South America, Central Asia, and parts of Europe.

Glaciologists — scientists who study glaciers — use a variety of techniques to measure glacier health and reconstruct past climate conditions. Mass balance measurements compare the amount of snow and ice gained through accumulation (primarily snowfall) with the amount lost through ablation (melting, calving, and sublimation) over a given period. A glacier with a negative mass balance is losing more ice than it gains and is therefore shrinking. Satellite imagery and GPS technology have revolutionised glacier monitoring, enabling scientists to track changes in glacier extent, surface elevation, and flow velocity across entire mountain ranges and ice sheets simultaneously. The World Glacier Monitoring Service (WGMS), based in Zurich, maintains a global database of glacier observations and has documented a clear and accelerating trend of glacier retreat since the mid-twentieth century.

Ice cores drilled from glaciers and ice sheets provide one of the most valuable archives of past climate conditions available to science. As snow accumulates and compresses into ice, it traps tiny bubbles of atmospheric air, particles of dust and volcanic ash, pollen grains, and chemical signatures that preserve a detailed record of atmospheric composition, temperature, volcanic activity, and even human pollution stretching back hundreds of thousands of years. The longest ice cores, drilled from the Antarctic ice sheet, extend back approximately 800,000 years and have revealed the intimate relationship between greenhouse gas concentrations and global temperature over multiple glacial and interglacial cycles. These records show that current levels of atmospheric carbon dioxide — approximately 421 parts per million — are higher than at any point in at least 800,000 years, providing powerful evidence that modern climate change is unprecedented in the recent geological record.

The retreat of glaciers has profound consequences for human societies and natural ecosystems. In regions such as the Andes, the Himalayas, and the Alps, glaciers serve as natural water towers, storing precipitation as ice during wet seasons and releasing meltwater during dry seasons, providing a critical source of fresh water for agriculture, hydropower generation, and domestic consumption. The Indus, Ganges, and Brahmaputra river systems, which supply water to approximately 1.5 billion people across South Asia, depend significantly on glacial meltwater from the Himalayas and the Karakoram range. As glaciers shrink, the volume of meltwater initially increases — a phenomenon known as "peak water" — but eventually declines as the glaciers disappear, threatening long-term water security for hundreds of millions of people.

Sea-level rise driven by glacier and ice sheet melting is one of the most consequential impacts of climate change. Between 2006 and 2015, glaciers and ice sheets contributed approximately 1.8 millimetres per year to global sea-level rise — more than half the total observed rate of 3.6 millimetres per year during the same period. The Intergovernmental Panel on Climate Change (IPCC) has projected that under high-emission scenarios, global sea levels could rise by 0.6 to 1.1 metres by 2100, with continued rise for centuries thereafter. Such increases would inundate low-lying coastal areas, displace tens of millions of people, damage critical infrastructure, contaminate freshwater aquifers with saltwater intrusion, and intensify coastal flooding and storm surge damage. Small island nations in the Pacific and Indian Oceans face an existential threat, with some projected to become uninhabitable within decades.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "What percentage of Earth's fresh water is contained in glaciers?", options: ["A. Approximately 10 percent", "B. Approximately 50 percent", "C. Approximately 69 percent", "D. Approximately 85 percent"], correctAnswer: "C", explanation: "The passage says glaciers 'contain roughly 69 percent of all the fresh water on Earth.'" },
        { number: 2, type: "multiple_choice", text: "Where are the only existing ice sheets found today?", options: ["A. The Alps and Andes", "B. Greenland and Antarctica", "C. The Himalayas and Karakoram", "D. North America and Siberia"], correctAnswer: "B", explanation: "The passage says 'The only existing ice sheets today are those covering Greenland and Antarctica.'" },
        { number: 3, type: "multiple_choice", text: "What is 'peak water' in the context of glacier retreat?", options: ["A. The maximum depth of glacial lakes", "B. The time when meltwater volume initially increases before glaciers disappear", "C. The highest point of a glacier", "D. The season with the most rainfall"], correctAnswer: "B", explanation: "The passage says 'the volume of meltwater initially increases — a phenomenon known as \"peak water\" — but eventually declines as the glaciers disappear.'" },
        { number: 4, type: "multiple_choice", text: "How much could global sea levels rise by 2100 under high-emission scenarios?", options: ["A. 0.1 to 0.3 metres", "B. 0.3 to 0.5 metres", "C. 0.6 to 1.1 metres", "D. 1.5 to 2.0 metres"], correctAnswer: "C", explanation: "The passage says 'global sea levels could rise by 0.6 to 1.1 metres by 2100.'" },
        { number: 5, type: "sentence_completion", text: "Glaciers cover approximately _______ percent of the planet's land surface.", correctAnswer: "10", explanation: "The passage says 'cover approximately 10 percent of the planet's land surface.'" },
        { number: 6, type: "sentence_completion", text: "If fully melted, Greenland and Antarctica could raise sea levels by approximately _______ metres.", correctAnswer: "65", explanation: "The passage says 'enough ice to raise global sea levels by approximately 65 metres.'" },
        { number: 7, type: "sentence_completion", text: "The World Glacier Monitoring Service is based in _______.", correctAnswer: "Zurich", explanation: "The passage says 'The World Glacier Monitoring Service (WGMS), based in Zurich.'" },
        { number: 8, type: "sentence_completion", text: "The longest Antarctic ice cores extend back approximately _______ years.", correctAnswer: "800,000", explanation: "The passage says 'extend back approximately 800,000 years.'" },
        { number: 9, type: "sentence_completion", text: "The Himalayan rivers supply water to approximately _______ billion people.", correctAnswer: "1.5", explanation: "The passage says 'supply water to approximately 1.5 billion people.'" },
        { number: 10, type: "sentence_completion", text: "Between 2006 and 2015, glaciers contributed approximately _______ millimetres per year to sea-level rise.", correctAnswer: "1.8", explanation: "The passage says 'approximately 1.8 millimetres per year.'" },
        { number: 11, type: "sentence_completion", text: "Current atmospheric CO₂ levels are approximately _______ parts per million.", correctAnswer: "421", explanation: "The passage says 'approximately 421 parts per million.'" },
        { number: 12, type: "sentence_completion", text: "The total observed rate of sea-level rise was _______ millimetres per year between 2006 and 2015.", correctAnswer: "3.6", explanation: "The passage says '3.6 millimetres per year during the same period.'" },
        { number: 13, type: "sentence_completion", text: "A glacier with a negative mass balance is losing more _______ than it gains.", correctAnswer: "ice", explanation: "The passage says 'A glacier with a negative mass balance is losing more ice than it gains.'" },
      ],
    },
    {
      title: "The Context and Meaning of Tourism",
      text: `A. Tourism, broadly defined as the temporary movement of people to destinations outside their normal places of residence and work, is one of the largest and fastest-growing industries in the global economy. According to the World Travel and Tourism Council (WTTC), travel and tourism contributed approximately $9.6 trillion to global GDP in 2019 — representing 10.4 percent of all economic activity — and supported 334 million jobs, or approximately one in ten of all jobs worldwide. Despite severe disruption caused by the COVID-19 pandemic, the industry has demonstrated remarkable resilience, with global tourism revenues recovering to approximately 95 percent of pre-pandemic levels by the end of 2023.

B. The concept of tourism as a leisure activity accessible to ordinary people is a relatively recent development in human history. For most of recorded history, long-distance travel was undertaken primarily for trade, religious pilgrimage, military conquest, or diplomacy, and was confined to a small elite who possessed the wealth, freedom, and motivation to journey beyond their immediate communities. The emergence of modern tourism is generally traced to the eighteenth-century Grand Tour — a cultural journey through France, Italy, and other European countries undertaken by young British aristocrats as part of their education. Thomas Cook, a British businessman, is widely credited with creating the modern tourism industry when he organised the first commercially advertised excursion train in 1841, carrying 570 passengers from Leicester to Loughborough for a temperance meeting at a cost of one shilling per person.

C. The democratisation of tourism accelerated dramatically in the twentieth century with the development of mass air travel. The introduction of jet aircraft in the 1950s and the subsequent growth of charter airlines and package holiday companies made international travel affordable for middle-class consumers in Europe and North America for the first time. The number of international tourist arrivals worldwide grew from approximately 25 million in 1950 to 278 million in 1980, 674 million in 2000, and 1.46 billion in 2019 — a nearly sixty-fold increase in seven decades. This extraordinary growth was driven by rising incomes, increasing leisure time, the expansion of air routes and airport infrastructure, and the progressive liberalisation of international visa and travel regulations.

D. Tourism scholars have developed numerous typologies and frameworks for understanding the diverse motivations and behaviours of tourists. One of the most influential is sociologist Erik Cohen's classification of tourists into five categories: the organised mass tourist, who purchases standardised package holidays and remains largely within the "environmental bubble" of familiar hotels and tourist infrastructure; the individual mass tourist, who arranges travel independently but still relies on established tourist facilities; the explorer, who seeks novel experiences and contact with local cultures while retaining access to comfortable accommodation; the drifter, who avoids all tourist infrastructure and seeks total immersion in local communities; and the existential tourist, who travels in search of spiritual meaning or a deeper sense of identity. Cohen's typology, though developed in 1972, remains widely cited and has been adapted and extended by subsequent researchers.

E. The impacts of tourism are complex and multifaceted, encompassing economic, environmental, social, and cultural dimensions. Economically, tourism generates revenue, creates employment, stimulates infrastructure development, and provides foreign exchange earnings for destination countries. However, the economic benefits of tourism are often unevenly distributed: a significant proportion of tourist spending in developing countries "leaks" back to the tourists' home countries through foreign-owned hotels, airlines, and tour operators, and tourism employment is often seasonal, low-paid, and insecure. Environmentally, tourism contributes to carbon emissions through air travel, places pressure on fragile ecosystems through overdevelopment and visitor traffic, and generates waste and water consumption that can exceed the carrying capacity of destination communities. The carbon footprint of tourism is estimated at approximately 8 percent of global greenhouse gas emissions, with aviation accounting for the largest share.

F. In response to these challenges, the concept of sustainable tourism has gained increasing prominence. The UNWTO defines sustainable tourism as "tourism that takes full account of its current and future economic, social and environmental impacts, addressing the needs of visitors, the industry, the environment and host communities." In practice, sustainable tourism encompasses a range of approaches, including ecotourism (nature-based tourism that promotes conservation and supports local communities), community-based tourism (in which local communities own and manage tourist facilities and activities), slow tourism (which emphasises deeper engagement with fewer destinations over longer periods), and voluntourism (in which tourists combine travel with volunteer work). While these approaches represent important steps toward more responsible tourism, critics argue that sustainable tourism remains a niche segment of the market and that systemic change will require fundamental reforms to the economic incentives, regulatory frameworks, and consumer expectations that drive mass tourism.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Paragraph A", options: ["i. Different types of tourists", "ii. The economic scale of global tourism", "iii. The origins of modern tourism", "iv. Moving toward responsible travel", "v. The positive and negative effects of tourism", "vi. How air travel changed tourism", "vii. Government tourism policies", "viii. The future of ecotourism"], correctAnswer: "ii", explanation: "Paragraph A presents tourism's $9.6 trillion GDP contribution and 334 million jobs." },
        { number: 15, type: "matching_headings", text: "Paragraph B", options: ["i. Different types of tourists", "ii. The economic scale of global tourism", "iii. The origins of modern tourism", "iv. Moving toward responsible travel", "v. The positive and negative effects of tourism", "vi. How air travel changed tourism", "vii. Government tourism policies", "viii. The future of ecotourism"], correctAnswer: "iii", explanation: "Paragraph B traces tourism from the Grand Tour to Thomas Cook's first excursion." },
        { number: 16, type: "matching_headings", text: "Paragraph C", options: ["i. Different types of tourists", "ii. The economic scale of global tourism", "iii. The origins of modern tourism", "iv. Moving toward responsible travel", "v. The positive and negative effects of tourism", "vi. How air travel changed tourism", "vii. Government tourism policies", "viii. The future of ecotourism"], correctAnswer: "vi", explanation: "Paragraph C discusses jet aircraft, charter airlines, and the sixty-fold growth in arrivals." },
        { number: 17, type: "matching_headings", text: "Paragraph D", options: ["i. Different types of tourists", "ii. The economic scale of global tourism", "iii. The origins of modern tourism", "iv. Moving toward responsible travel", "v. The positive and negative effects of tourism", "vi. How air travel changed tourism", "vii. Government tourism policies", "viii. The future of ecotourism"], correctAnswer: "i", explanation: "Paragraph D presents Erik Cohen's five tourist categories." },
        { number: 18, type: "matching_headings", text: "Paragraph E", options: ["i. Different types of tourists", "ii. The economic scale of global tourism", "iii. The origins of modern tourism", "iv. Moving toward responsible travel", "v. The positive and negative effects of tourism", "vi. How air travel changed tourism", "vii. Government tourism policies", "viii. The future of ecotourism"], correctAnswer: "v", explanation: "Paragraph E discusses economic, environmental, and social impacts of tourism." },
        { number: 19, type: "matching_headings", text: "Paragraph F", options: ["i. Different types of tourists", "ii. The economic scale of global tourism", "iii. The origins of modern tourism", "iv. Moving toward responsible travel", "v. The positive and negative effects of tourism", "vi. How air travel changed tourism", "vii. Government tourism policies", "viii. The future of ecotourism"], correctAnswer: "iv", explanation: "Paragraph F discusses sustainable tourism approaches like ecotourism and slow tourism." },
        { number: 20, type: "summary_completion", text: "Tourism contributed approximately $_______ trillion to global GDP in 2019.", correctAnswer: "9.6", explanation: "The passage says 'approximately $9.6 trillion.'" },
        { number: 21, type: "summary_completion", text: "Tourism supported _______ million jobs worldwide in 2019.", correctAnswer: "334", explanation: "The passage says 'supported 334 million jobs.'" },
        { number: 22, type: "summary_completion", text: "Thomas Cook's first excursion in 1841 cost _______ per person.", correctAnswer: "one shilling", explanation: "The passage says 'at a cost of one shilling per person.'" },
        { number: 23, type: "summary_completion", text: "International tourist arrivals grew from 25 million in 1950 to _______ billion in 2019.", correctAnswer: "1.46", explanation: "The passage says '1.46 billion in 2019.'" },
        { number: 24, type: "summary_completion", text: "Erik Cohen's classification of tourists was developed in _______.", correctAnswer: "1972", explanation: "The passage says 'developed in 1972.'" },
        { number: 25, type: "summary_completion", text: "Tourism's carbon footprint is approximately _______ percent of global greenhouse gas emissions.", correctAnswer: "8", explanation: "The passage says 'approximately 8 percent of global greenhouse gas emissions.'" },
        { number: 26, type: "summary_completion", text: "Thomas Cook organised the first excursion carrying _______ passengers.", correctAnswer: "570", explanation: "The passage says 'carrying 570 passengers.'" },
      ],
    },
    {
      title: "Lie Detector Technology and Human Behavior",
      text: `The quest to determine whether a person is telling the truth has fascinated humanity for millennia. Ancient civilisations developed various methods for detecting deception, from the ordeal by fire and water practised in medieval Europe to the practice in ancient China of requiring suspects to chew dry rice and spit it out — on the theory that a guilty person's mouth would become dry from anxiety, causing the rice to stick. Modern lie detection technology, while far more sophisticated, continues to grapple with the same fundamental challenge: reliably distinguishing truthful statements from deceptive ones by measuring physiological or behavioural indicators of deception.

The polygraph, commonly known as the lie detector, is the most widely used deception detection device in the world. Developed in the early twentieth century, the modern polygraph simultaneously measures several physiological responses that are believed to be associated with the stress of lying: respiratory rate, blood pressure, heart rate, and electrodermal activity (skin conductance), which reflects sweat gland activity. During a polygraph examination, the subject is asked a series of questions while attached to sensors that record these physiological signals on a moving chart or digital display. The examiner then analyses the recorded data to determine whether the subject showed significant physiological reactions to specific questions — reactions that are interpreted as indicators of deception.

The most commonly used polygraph testing format is the Control Question Test (CQT), developed by polygraph researcher John Reid in the 1940s. In the CQT, the examiner asks three types of questions: relevant questions directly related to the matter under investigation (e.g., "Did you steal the money?"); control questions designed to produce a moderate level of anxiety in truthful subjects (e.g., "Have you ever taken something that did not belong to you?"); and irrelevant questions that serve as baseline comparisons (e.g., "Is today Tuesday?"). The theory underlying the CQT is that truthful subjects will show stronger physiological reactions to the control questions — which are designed to be uncomfortable but answerable — than to the relevant questions, while deceptive subjects will react more strongly to the relevant questions because of the stress of lying.

Despite its widespread use, the scientific validity of the polygraph has been the subject of intense and sustained criticism. In 2003, the National Academy of Sciences (NAS) of the United States published a comprehensive review of polygraph research and concluded that "the theoretical rationale for the polygraph is quite weak" and that polygraph tests produce unacceptable rates of both false positives (innocent people wrongly classified as deceptive) and false negatives (deceptive people wrongly classified as truthful). The NAS estimated that the accuracy of the CQT ranges from approximately 80 to 90 percent under controlled laboratory conditions — a figure that may sound impressive but implies that between 10 and 20 percent of all examinees are misclassified. In real-world conditions, where the stakes are higher and examiners may be subject to confirmation bias, accuracy rates may be lower still.

Several alternative technologies for detecting deception have been developed in recent decades. Functional magnetic resonance imaging (fMRI), which measures changes in blood oxygenation in the brain, has been investigated as a potential tool for identifying brain regions associated with deception. Research has shown that lying tends to activate prefrontal and anterior cingulate cortex regions more strongly than truth-telling, reflecting the greater cognitive effort required to construct and maintain a false narrative. However, fMRI-based lie detection remains experimental: the technology is expensive, immobile, sensitive to movement artefacts, and has not been validated for use with individual subjects in real-world forensic settings. Eye-tracking technology, which analyses patterns of eye movement and pupil dilation, and voice stress analysis, which claims to detect micro-tremors in the voice associated with deception, have also been proposed as alternatives, though neither has achieved the level of scientific validation needed for reliable forensic use.

The legal and ethical implications of lie detection technology are profound. In most legal systems, polygraph results are not admissible as evidence in court, though they are widely used in criminal investigations, employee screening (particularly in law enforcement and intelligence agencies), and parole and probation monitoring. The fundamental objection to polygraph testing — and to all physiological lie detection methods — is that they do not actually detect lies. Instead, they detect physiological arousal, which can be caused by many factors other than deception, including anxiety, anger, surprise, embarrassment, and the stress of being tested itself. Countermeasures — deliberate techniques used by subjects to manipulate their physiological responses, such as biting their tongue during control questions to artificially elevate their baseline arousal — further undermine the reliability of polygraph testing. As artificial intelligence and machine learning are increasingly applied to deception detection — through analysis of micro-expressions, linguistic patterns, body language, and multimodal behavioural cues — the ethical questions surrounding automated truth assessment are likely to become even more pressing in the years ahead.`,
      questions: [
        { number: 27, type: "matching_information", text: "A description of ancient methods used to detect lying", options: ["Paragraph 1", "Paragraph 2", "Paragraph 3", "Paragraph 4", "Paragraph 5", "Paragraph 6"], correctAnswer: "Paragraph 1", explanation: "Paragraph 1 describes ancient Chinese rice-chewing and medieval ordeal methods." },
        { number: 28, type: "matching_information", text: "Details of the three types of questions used in polygraph testing", options: ["Paragraph 1", "Paragraph 2", "Paragraph 3", "Paragraph 4", "Paragraph 5", "Paragraph 6"], correctAnswer: "Paragraph 3", explanation: "Paragraph 3 describes relevant, control, and irrelevant questions in the CQT." },
        { number: 29, type: "matching_information", text: "Scientific criticism of polygraph accuracy", options: ["Paragraph 1", "Paragraph 2", "Paragraph 3", "Paragraph 4", "Paragraph 5", "Paragraph 6"], correctAnswer: "Paragraph 4", explanation: "Paragraph 4 discusses the NAS review finding 80-90% accuracy and 'quite weak' theoretical rationale." },
        { number: 30, type: "matching_information", text: "Brain imaging as an alternative lie detection method", options: ["Paragraph 1", "Paragraph 2", "Paragraph 3", "Paragraph 4", "Paragraph 5", "Paragraph 6"], correctAnswer: "Paragraph 5", explanation: "Paragraph 5 discusses fMRI-based lie detection research." },
        { number: 31, type: "matching_information", text: "Techniques people use to fool lie detectors", options: ["Paragraph 1", "Paragraph 2", "Paragraph 3", "Paragraph 4", "Paragraph 5", "Paragraph 6"], correctAnswer: "Paragraph 6", explanation: "Paragraph 6 describes countermeasures like biting the tongue during control questions." },
        { number: 32, type: "multiple_choice", text: "What does a polygraph measure?", options: ["A. Brain waves and neural activity", "B. Respiratory rate, blood pressure, heart rate, and skin conductance", "C. Voice patterns and facial expressions", "D. Eye movements and pupil dilation"], correctAnswer: "B", explanation: "The passage says the polygraph 'measures several physiological responses... respiratory rate, blood pressure, heart rate, and electrodermal activity.'" },
        { number: 33, type: "multiple_choice", text: "Who developed the Control Question Test?", options: ["A. The National Academy of Sciences", "B. John Reid", "C. A team at Harvard University", "D. The FBI"], correctAnswer: "B", explanation: "The passage says 'the Control Question Test (CQT), developed by polygraph researcher John Reid.'" },
        { number: 34, type: "multiple_choice", text: "What accuracy rate did the NAS estimate for the CQT?", options: ["A. 60 to 70 percent", "B. 70 to 80 percent", "C. 80 to 90 percent", "D. 90 to 95 percent"], correctAnswer: "C", explanation: "The passage says 'approximately 80 to 90 percent under controlled laboratory conditions.'" },
        { number: 35, type: "multiple_choice", text: "What is the fundamental objection to polygraph testing?", options: ["A. It is too expensive for most agencies", "B. It detects physiological arousal, not actual lies", "C. It can only be used on willing subjects", "D. Results take too long to analyse"], correctAnswer: "B", explanation: "The passage says 'they do not actually detect lies. Instead, they detect physiological arousal.'" },
        { number: 36, type: "short_answer", text: "What did the ancient Chinese method of detecting deception involve?", correctAnswer: "chewing dry rice", explanation: "The passage describes 'requiring suspects to chew dry rice and spit it out.'" },
        { number: 37, type: "short_answer", text: "What brain regions are more active during lying according to fMRI research?", correctAnswer: "prefrontal and anterior cingulate cortex", explanation: "The passage says 'lying tends to activate prefrontal and anterior cingulate cortex regions.'" },
        { number: 38, type: "short_answer", text: "In what year did the NAS publish its comprehensive review of polygraph research?", correctAnswer: "2003", explanation: "The passage says 'In 2003, the National Academy of Sciences... published a comprehensive review.'" },
        { number: 39, type: "short_answer", text: "Name one countermeasure subjects use to manipulate polygraph results.", correctAnswer: "biting their tongue", explanation: "The passage mentions 'biting their tongue during control questions.'" },
        { number: 40, type: "short_answer", text: "Are polygraph results generally admissible as evidence in court?", correctAnswer: "no", explanation: "The passage says 'polygraph results are not admissible as evidence in court.'" },
      ],
    },
  ],
};
