import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_41: ReadingTest = {
  id: 41,
  passages: [
    {
      title: "History of Navigation",
      text: `Navigating the open sea has been one of humanity's greatest challenges. For thousands of years, mariners relied on natural cues — the positions of stars, the direction of prevailing winds, the flight patterns of birds, and the colour and temperature of ocean currents — to find their way across featureless expanses of water. Polynesian voyagers, perhaps the most skilled open-ocean navigators in history, colonised islands scattered across more than 25 million square kilometres of the Pacific Ocean using a sophisticated system of wayfinding that combined celestial observation, wave-pattern reading, and mental maps passed down through oral tradition.

In the Mediterranean world, navigation was initially coastal: ships hugged the shoreline, using prominent landmarks — headlands, mountains, harbour entrances — as reference points. The development of the magnetic compass, which arrived in Europe from China around the twelfth century, transformed maritime travel by providing a reliable directional reference even when the sky was overcast or the coast was out of sight. The compass was soon paired with the portolan chart, a type of navigational map that depicted coastlines with remarkable accuracy and was overlaid with a network of rhumb lines radiating from compass roses.

Determining latitude — one's north-south position — became relatively straightforward with the development of instruments such as the astrolabe, the quadrant, and, later, the sextant. By measuring the angle between the horizon and a known celestial body, typically the North Star or the sun at noon, a navigator could calculate latitude with reasonable precision. The sextant, perfected in the eighteenth century, remained the primary tool for celestial navigation until the advent of electronic positioning systems in the late twentieth century.

Longitude — one's east-west position — proved far more difficult to determine. Because the Earth rotates, longitude is essentially a measure of time difference: each fifteen degrees of longitude corresponds to a one-hour difference in local solar time relative to a reference meridian. In theory, a navigator who knew the exact time at a reference point (such as Greenwich, England) could compare it with local noon and calculate longitude. In practice, no clock available before the eighteenth century could keep accurate time aboard a pitching ship for weeks or months at a time.

The problem was so critical to maritime safety and commerce that the British Parliament established the Board of Longitude in 1714, offering a prize of £20,000 — roughly £3 million in today's money — for a practical method of determining longitude at sea to within half a degree. John Harrison, a self-taught Yorkshire clockmaker, devoted decades to the challenge and produced a series of increasingly refined marine chronometers. His fourth timekeeper, the H4, completed in 1761, lost only five seconds during a 81-day voyage to Jamaica, easily satisfying the Board's accuracy requirements. Harrison's chronometer revolutionised navigation, enabling captains to plot their positions on a chart with unprecedented precision and dramatically reducing the number of shipwrecks caused by navigational errors.

The twentieth century brought electronic navigation systems. Radio direction-finding, introduced during the First World War, allowed ships to determine their bearing relative to shore-based radio transmitters. The Long Range Navigation (LORAN) system, developed during the Second World War, used the time difference between signals from pairs of land-based radio stations to fix a vessel's position within a few hundred metres. In 1973, the United States Department of Defense began developing the Global Positioning System (GPS), a constellation of satellites orbiting at approximately 20,200 kilometres above the Earth. GPS receivers calculate position by measuring the time it takes signals from at least four satellites to reach the device, achieving accuracy of a few metres under normal conditions and centimetre-level precision with advanced techniques.

Today, GPS and its counterparts — Europe's Galileo, Russia's GLONASS, and China's BeiDou — underpin not only maritime navigation but also aviation, road transport, agriculture, surveying, and countless smartphone applications. The transformation from star-gazing Polynesian wayfinders to satellite-guided supertankers spans millennia but reflects a single, enduring human aspiration: to know where we are and where we are going.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "How did Polynesian voyagers navigate the Pacific Ocean?", options: ["A Using magnetic compasses and portolan charts", "B Combining celestial observation, wave patterns, and oral tradition", "C Following radio signals from shore stations", "D Using GPS satellite technology"], correctAnswer: "B", explanation: "The passage describes Polynesian wayfinding using 'celestial observation, wave-pattern reading, and mental maps passed down through oral tradition.'" },
        { number: 2, type: "multiple_choice", text: "What instrument was perfected in the eighteenth century for measuring latitude?", options: ["A The astrolabe", "B The magnetic compass", "C The sextant", "D The quadrant"], correctAnswer: "C", explanation: "The passage says 'The sextant, perfected in the eighteenth century.'" },
        { number: 3, type: "multiple_choice", text: "How much was the Board of Longitude prize worth?", options: ["A £10,000", "B £15,000", "C £20,000", "D £25,000"], correctAnswer: "C", explanation: "The passage says 'offering a prize of £20,000.'" },
        { number: 4, type: "multiple_choice", text: "At what altitude do GPS satellites orbit?", options: ["A 10,000 kilometres", "B 15,500 kilometres", "C 20,200 kilometres", "D 35,800 kilometres"], correctAnswer: "C", explanation: "The passage says 'approximately 20,200 kilometres above the Earth.'" },
        { number: 5, type: "true_false_not_given", text: "The magnetic compass was invented in Europe.", correctAnswer: "FALSE", explanation: "The passage says it 'arrived in Europe from China around the twelfth century.'" },
        { number: 6, type: "true_false_not_given", text: "Each fifteen degrees of longitude corresponds to a one-hour time difference.", correctAnswer: "TRUE", explanation: "The passage states 'each fifteen degrees of longitude corresponds to a one-hour difference.'" },
        { number: 7, type: "true_false_not_given", text: "John Harrison was formally trained as a clockmaker.", correctAnswer: "FALSE", explanation: "The passage describes Harrison as 'a self-taught Yorkshire clockmaker.'" },
        { number: 8, type: "true_false_not_given", text: "Harrison's H4 lost only five seconds during an 81-day voyage.", correctAnswer: "TRUE", explanation: "The passage says 'lost only five seconds during a 81-day voyage to Jamaica.'" },
        { number: 9, type: "true_false_not_given", text: "LORAN was developed during the First World War.", correctAnswer: "FALSE", explanation: "The passage says LORAN was 'developed during the Second World War.'" },
        { number: 10, type: "true_false_not_given", text: "Russia's satellite navigation system is called BeiDou.", correctAnswer: "FALSE", explanation: "The passage says Russia's system is GLONASS; BeiDou is China's." },
        { number: 11, type: "true_false_not_given", text: "GPS can achieve centimetre-level precision with advanced techniques.", correctAnswer: "TRUE", explanation: "The passage says 'centimetre-level precision with advanced techniques.'" },
        { number: 12, type: "true_false_not_given", text: "Portolan charts were first developed in ancient Egypt.", correctAnswer: "NOT GIVEN", explanation: "The passage does not specify where portolan charts were first developed." },
        { number: 13, type: "true_false_not_given", text: "Polynesian voyagers colonised islands across more than 25 million square kilometres.", correctAnswer: "TRUE", explanation: "The passage says 'more than 25 million square kilometres of the Pacific Ocean.'" },
      ],
    },
    {
      title: "Endangered Animals",
      text: `A. The Earth is currently experiencing what many scientists describe as the sixth mass extinction, a catastrophic loss of biodiversity driven not by an asteroid impact or volcanic eruption but by human activity. The International Union for Conservation of Nature (IUCN) Red List, the most comprehensive inventory of the conservation status of species, currently classifies more than 44,000 species as threatened with extinction — roughly twenty-eight per cent of all species assessed. The rate of species loss is estimated to be between one hundred and one thousand times higher than the natural background rate, a pace unprecedented in the last sixty-five million years.

B. Habitat destruction is the single greatest driver of species decline. As forests are cleared for agriculture, wetlands drained for development, and grasslands converted to cropland, the ecosystems on which countless species depend are shrinking at an alarming rate. Tropical rainforests, which cover just six per cent of the Earth's land surface but harbour more than half of all terrestrial species, are disappearing at a rate of approximately 4.7 million hectares per year. The orangutan, native to the rainforests of Borneo and Sumatra, has lost more than eighty per cent of its habitat in the past forty years, primarily to palm-oil plantations, and its population has declined by an estimated fifty per cent.

C. Climate change is exacerbating the crisis. Rising temperatures alter habitats faster than many species can adapt or migrate. Polar bears, which depend on Arctic sea ice for hunting seals, face shrinking hunting grounds as summer ice extent declines by approximately thirteen per cent per decade. Coral reef ecosystems, which support roughly twenty-five per cent of all marine species, are bleaching and dying as ocean temperatures rise. Mountain-dwelling species such as the pika, a small mammal, are being pushed to ever-higher elevations with nowhere left to go.

D. Overexploitation — hunting, fishing, and harvesting at unsustainable rates — threatens many species. The African elephant population has declined from an estimated 1.3 million in 1979 to approximately 415,000 today, driven primarily by ivory poaching. Shark populations have fallen by over seventy per cent in the past fifty years, largely due to demand for shark-fin soup in parts of East Asia. The illegal wildlife trade, valued at an estimated $23 billion per year, targets species ranging from pangolins to parrots, driving many toward extinction.

E. Conservation efforts take many forms. Protected areas — national parks, wildlife reserves, and marine sanctuaries — now cover approximately fifteen per cent of the world's land surface and roughly eight per cent of the oceans. Captive breeding programmes have pulled several species back from the brink of extinction: the California condor, reduced to just 27 individuals in 1987, now numbers over 500 thanks to a decades-long breeding and reintroduction programme. Similarly, the Arabian oryx was declared extinct in the wild in 1972 but has been reintroduced to its native habitats in Oman, Saudi Arabia, and the United Arab Emirates, with a current wild population exceeding 1,000.

F. Community-based conservation, which engages local people as stewards of their natural environment, has proven particularly effective in developing countries. In Namibia, a system of communal conservancies gives rural communities legal rights over wildlife on their land, creating economic incentives for conservation through tourism and sustainable use. Since the conservancy programme began in 1998, populations of elephants, lions, and black rhinos in communal areas have increased substantially.

G. International agreements play a crucial role. The Convention on International Trade in Endangered Species (CITES), signed in 1973, regulates the cross-border trade in more than 38,000 species of plants and animals. The Convention on Biological Diversity, adopted at the 1992 Earth Summit, commits signatory nations to conserving biological diversity and using biological resources sustainably. In December 2022, the Kunming-Montreal Global Biodiversity Framework set a target of protecting thirty per cent of the world's land and sea areas by 2030, an ambition known as the "30 by 30" goal.

H. Despite these efforts, the trajectory of biodiversity loss remains deeply concerning. The World Wildlife Fund's Living Planet Report 2022 documented an average sixty-nine per cent decline in monitored wildlife populations between 1970 and 2018. Reversing this trend will require not only expanded conservation measures but also fundamental changes in the economic systems that drive habitat destruction, overexploitation, and climate change. The choices made in the coming decade will determine whether the sixth mass extinction can be slowed or whether it will reshape life on Earth for millions of years to come.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Section A", options: ["I. The impact of rising temperatures on wildlife", "II. The current extinction crisis", "III. Destroying natural habitats", "IV. International conservation treaties", "V. Breeding programmes that saved species", "VI. Unsustainable hunting and trade", "VII. Engaging local communities in conservation", "VIII. The continuing decline of biodiversity"], correctAnswer: "II", explanation: "Section A introduces the sixth mass extinction and overall statistics." },
        { number: 15, type: "matching_headings", text: "Section B", options: ["I. The impact of rising temperatures on wildlife", "II. The current extinction crisis", "III. Destroying natural habitats", "IV. International conservation treaties", "V. Breeding programmes that saved species", "VI. Unsustainable hunting and trade", "VII. Engaging local communities in conservation", "VIII. The continuing decline of biodiversity"], correctAnswer: "III", explanation: "Section B discusses habitat destruction as the greatest driver." },
        { number: 16, type: "matching_headings", text: "Section C", options: ["I. The impact of rising temperatures on wildlife", "II. The current extinction crisis", "III. Destroying natural habitats", "IV. International conservation treaties", "V. Breeding programmes that saved species", "VI. Unsustainable hunting and trade", "VII. Engaging local communities in conservation", "VIII. The continuing decline of biodiversity"], correctAnswer: "I", explanation: "Section C discusses climate change effects on species." },
        { number: 17, type: "matching_headings", text: "Section D", options: ["I. The impact of rising temperatures on wildlife", "II. The current extinction crisis", "III. Destroying natural habitats", "IV. International conservation treaties", "V. Breeding programmes that saved species", "VI. Unsustainable hunting and trade", "VII. Engaging local communities in conservation", "VIII. The continuing decline of biodiversity"], correctAnswer: "VI", explanation: "Section D discusses overexploitation and illegal wildlife trade." },
        { number: 18, type: "matching_headings", text: "Section E", options: ["I. The impact of rising temperatures on wildlife", "II. The current extinction crisis", "III. Destroying natural habitats", "IV. International conservation treaties", "V. Breeding programmes that saved species", "VI. Unsustainable hunting and trade", "VII. Engaging local communities in conservation", "VIII. The continuing decline of biodiversity"], correctAnswer: "V", explanation: "Section E discusses captive breeding and reintroduction programmes." },
        { number: 19, type: "matching_headings", text: "Section F", options: ["I. The impact of rising temperatures on wildlife", "II. The current extinction crisis", "III. Destroying natural habitats", "IV. International conservation treaties", "V. Breeding programmes that saved species", "VI. Unsustainable hunting and trade", "VII. Engaging local communities in conservation", "VIII. The continuing decline of biodiversity"], correctAnswer: "VII", explanation: "Section F discusses community-based conservation in Namibia." },
        { number: 20, type: "table_completion", text: "The IUCN Red List classifies more than __(20)__ species as threatened.", correctAnswer: "44,000", explanation: "The passage says 'more than 44,000 species.'" },
        { number: 21, type: "table_completion", text: "Tropical rainforests are disappearing at __(21)__ million hectares per year.", correctAnswer: "4.7", explanation: "The passage says 'approximately 4.7 million hectares per year.'" },
        { number: 22, type: "table_completion", text: "The California condor was reduced to just __(22)__ individuals in 1987.", correctAnswer: "27", explanation: "The passage says 'reduced to just 27 individuals in 1987.'" },
        { number: 23, type: "table_completion", text: "The illegal wildlife trade is valued at approximately $__(23)__ billion per year.", correctAnswer: "23", explanation: "The passage says 'valued at an estimated $23 billion per year.'" },
        { number: 24, type: "short_answer", text: "What is the primary cause of orangutan habitat loss?", correctAnswer: "palm-oil plantations", explanation: "The passage says habitat lost 'primarily to palm-oil plantations.'" },
        { number: 25, type: "short_answer", text: "In which country does the communal conservancy programme operate?", correctAnswer: "Namibia", explanation: "The passage says 'In Namibia, a system of communal conservancies.'" },
        { number: 26, type: "short_answer", text: "What is the '30 by 30' goal?", correctAnswer: "protecting thirty per cent of land and sea by 2030", explanation: "The passage says 'protecting thirty per cent of the world's land and sea areas by 2030.'" },
      ],
    },
    {
      title: "Biotechnology Innovations",
      text: `Biotechnology — the application of biological systems and living organisms to develop products, processes, and technologies — has advanced with breathtaking speed in the twenty-first century. From gene editing and synthetic biology to biopharmaceuticals and agricultural biotechnology, the field is reshaping medicine, food production, energy, and environmental management in ways that were unimaginable a generation ago.

A. The most revolutionary biotechnological tool to emerge in recent years is CRISPR-Cas9, a gene-editing system derived from a natural defence mechanism found in bacteria. CRISPR allows scientists to cut, delete, or insert DNA sequences at precise locations within a genome with unprecedented ease and accuracy. Since its development as a laboratory tool in 2012 by Jennifer Doudna and Emmanuelle Charpentier, CRISPR has been applied to an extraordinary range of problems: correcting genetic mutations that cause inherited diseases, engineering pest-resistant crops, developing gene-drive systems to control malaria-carrying mosquitoes, and creating animal models for drug research.

B. In medicine, CRISPR-based therapies have already entered clinical use. In December 2023, the UK and US regulatory agencies approved Casgevy, a CRISPR therapy for sickle-cell disease and transfusion-dependent beta-thalassaemia. The treatment works by editing a patient's own stem cells to reactivate the production of foetal haemoglobin, which compensates for the defective adult haemoglobin that causes the disease. Early clinical data show that the majority of treated patients achieve freedom from the painful crises that characterise sickle-cell disease, representing a potential functional cure for a condition that affects millions worldwide.

C. Synthetic biology, a related discipline, goes beyond editing existing genomes to designing and constructing entirely new biological systems. Researchers have created synthetic organisms that produce biofuels, pharmaceuticals, and industrial chemicals from renewable feedstocks. Amyris, a California-based company, has engineered yeast strains that synthesise artemisinin, a key antimalarial drug traditionally extracted from the sweet wormwood plant. By producing artemisinin through fermentation rather than agriculture, the cost and supply volatility of this life-saving medicine have been significantly reduced.

D. Agricultural biotechnology continues to generate both innovation and controversy. Genetically modified (GM) crops engineered for herbicide tolerance, insect resistance, or enhanced nutritional content are now cultivated on more than 190 million hectares worldwide, primarily in the Americas and Asia. Golden Rice, enriched with beta-carotene to combat vitamin A deficiency, received regulatory approval in the Philippines in 2019 and Australia and New Zealand in 2021. Critics, however, raise concerns about the environmental impact of GM crops, including the potential for gene flow to wild relatives, the development of herbicide-resistant weeds, and the socio-economic effects on smallholder farmers who cannot afford proprietary seeds.

E. Biopharmaceuticals — therapeutic products derived from biological sources — now account for a large and growing share of the pharmaceutical market. Monoclonal antibodies, engineered to target specific proteins involved in disease, are used to treat cancers, autoimmune disorders, and infectious diseases. The global biopharmaceutical market was valued at approximately $400 billion in 2022, and biologics are expected to constitute more than a third of all pharmaceutical sales by 2030. The COVID-19 pandemic accelerated the development of mRNA-based therapies: the Pfizer-BioNTech and Moderna vaccines demonstrated that mRNA, delivered via lipid nanoparticles, could instruct human cells to produce viral proteins and generate a protective immune response, an approach now being explored for cancer vaccines and treatments for rare genetic diseases.

F. Environmental biotechnology offers tools for addressing pollution and climate change. Bioremediation uses micro-organisms to break down or neutralise contaminants in soil and water, including oil spills, heavy metals, and pesticide residues. Researchers are engineering bacteria capable of degrading polyethylene terephthalate (PET), the plastic most commonly used in bottles and packaging. If scaled successfully, enzymatic plastic degradation could complement mechanical and chemical recycling and help close the loop on plastic waste.

G. Despite its transformative potential, biotechnology raises profound ethical, legal, and social questions. The ability to edit the human germline — making heritable changes that would be passed to future generations — is technically possible with CRISPR but remains highly controversial. The birth of gene-edited babies in China in 2018 provoked international condemnation and calls for a moratorium on germline editing until ethical frameworks and regulatory safeguards are in place. Ensuring equitable access to biotechnological advances, protecting biodiversity from unintended consequences of gene drives, and maintaining public trust through transparent governance are challenges that will shape the trajectory of biotechnology for decades to come.`,
      questions: [
        { number: 27, type: "matching_information", text: "A therapy approved for sickle-cell disease using gene editing", options: ["A", "B", "C", "D", "E", "F", "G"], correctAnswer: "B", explanation: "Paragraph B discusses Casgevy, approved for sickle-cell disease." },
        { number: 28, type: "matching_information", text: "Use of micro-organisms to clean up environmental contamination", options: ["A", "B", "C", "D", "E", "F", "G"], correctAnswer: "F", explanation: "Paragraph F discusses bioremediation." },
        { number: 29, type: "matching_information", text: "Concerns about making heritable genetic changes in humans", options: ["A", "B", "C", "D", "E", "F", "G"], correctAnswer: "G", explanation: "Paragraph G discusses the ethics of germline editing." },
        { number: 30, type: "matching_information", text: "Production of a malaria drug through yeast fermentation", options: ["A", "B", "C", "D", "E", "F", "G"], correctAnswer: "C", explanation: "Paragraph C discusses Amyris engineering yeast to produce artemisinin." },
        { number: 31, type: "matching_information", text: "The scale of global cultivation of genetically modified crops", options: ["A", "B", "C", "D", "E", "F", "G"], correctAnswer: "D", explanation: "Paragraph D states GM crops are cultivated on 'more than 190 million hectares.'" },
        { number: 32, type: "matching_information", text: "The market value of biopharmaceutical products", options: ["A", "B", "C", "D", "E", "F", "G"], correctAnswer: "E", explanation: "Paragraph E states the market 'was valued at approximately $400 billion in 2022.'" },
        { number: 33, type: "multiple_choice", text: "Who developed CRISPR-Cas9 as a laboratory tool?", options: ["A James Watson and Francis Crick", "B Jennifer Doudna and Emmanuelle Charpentier", "C Alexander Fleming", "D Craig Venter"], correctAnswer: "B", explanation: "The passage says it was developed 'by Jennifer Doudna and Emmanuelle Charpentier.'" },
        { number: 34, type: "multiple_choice", text: "What does Golden Rice contain to address nutritional deficiency?", options: ["A Iron supplements", "B Omega-3 fatty acids", "C Beta-carotene", "D Vitamin D"], correctAnswer: "C", explanation: "The passage says Golden Rice is 'enriched with beta-carotene.'" },
        { number: 35, type: "multiple_choice", text: "What percentage of pharmaceutical sales are biologics expected to constitute by 2030?", options: ["A More than a quarter", "B More than a third", "C More than half", "D More than two-thirds"], correctAnswer: "B", explanation: "The passage says 'more than a third of all pharmaceutical sales by 2030.'" },
        { number: 36, type: "multiple_choice", text: "What provoked international condemnation in 2018?", options: ["A Release of GM crops in Europe", "B Cloning of a human embryo", "C Birth of gene-edited babies in China", "D Use of CRISPR on endangered species"], correctAnswer: "C", explanation: "The passage says 'The birth of gene-edited babies in China in 2018 provoked international condemnation.'" },
        { number: 37, type: "sentence_completion", text: "CRISPR is derived from a natural defence mechanism found in __(37)__.", correctAnswer: "bacteria", explanation: "The passage says 'a natural defence mechanism found in bacteria.'" },
        { number: 38, type: "sentence_completion", text: "Casgevy works by reactivating the production of foetal __(38)__.", correctAnswer: "haemoglobin", explanation: "The passage says 'reactivate the production of foetal haemoglobin.'" },
        { number: 39, type: "sentence_completion", text: "Researchers are engineering bacteria to degrade __(39)__, a common plastic.", correctAnswer: "PET", explanation: "The passage says 'degrading polyethylene terephthalate (PET).'" },
        { number: 40, type: "sentence_completion", text: "The global biopharmaceutical market was valued at approximately $__(40)__ billion in 2022.", correctAnswer: "400", explanation: "The passage says 'approximately $400 billion in 2022.'" },
      ],
    },
  ],
};
