import { ReadingTest } from "./reading-tests-data";

const p2Headings = [
  "i. The invention of movable type",
  "ii. Pictographic origins of written communication",
  "iii. The spread of alphabetic writing",
  "iv. Clay tablets and wedge-shaped marks",
  "v. Writing as a tool of political power",
  "vi. The decline of handwriting in the digital age",
  "vii. Sacred scripts of the Nile Valley",
  "viii. The role of trade in spreading literacy",
];

const p3Paragraphs = ["A", "B", "C", "D", "E", "F", "G"];

export const READING_TEST_3: ReadingTest = {
  id: 3,
  passages: [
    {
      title: "Climate Change and Ocean Ecosystems",
      text: `The world's oceans, covering more than 70 percent of the Earth's surface, play a critical role in regulating the global climate. They absorb approximately 30 percent of the carbon dioxide produced by human activities and capture over 90 percent of the excess heat generated by rising greenhouse gas concentrations. However, this buffering capacity comes at a significant cost to marine ecosystems.

Rising sea temperatures are perhaps the most visible threat. Warmer waters disrupt the delicate symbiotic relationship between coral polyps and the microscopic algae — known as zooxanthellae — that provide them with both colour and the majority of their energy through photosynthesis. When water temperatures exceed a critical threshold, corals expel these algae in a process called bleaching. If conditions do not improve within weeks, the corals starve and die. The Great Barrier Reef, the world's largest coral reef system, experienced unprecedented mass bleaching events in 2016, 2017, and 2020, affecting more than two-thirds of its extent.

Ocean acidification — the decrease in seawater pH caused by the absorption of atmospheric CO₂ — represents a less visible but equally serious problem. As CO₂ dissolves in seawater, it forms carbonic acid, which reduces the availability of carbonate ions that marine organisms need to build shells and skeletons. Shellfish, sea urchins, and certain types of plankton are particularly vulnerable. Since these organisms form the base of many marine food webs, their decline could cascade upward, affecting fish stocks and, ultimately, human food security.

Changes in ocean temperature and chemistry are also altering the distribution of marine species. Many fish populations are shifting poleward in search of cooler waters, disrupting established fisheries and creating new ones. In the North Sea, for example, species traditionally associated with warmer southern waters — such as red mullet and sea bass — have become increasingly common, while cold-water species like cod have declined.

Deoxygenation — the loss of dissolved oxygen from seawater — is another growing concern. Warmer water holds less oxygen, and increased nutrient runoff from agriculture fuels algal blooms that further deplete oxygen levels. The resulting "dead zones," where oxygen levels are too low to support most marine life, have been expanding in both number and size. The Gulf of Mexico dead zone, fed by nutrients from the Mississippi River basin, now regularly exceeds 15,000 square kilometres during summer months.

Scientists warn that these threats are interconnected and self-reinforcing: warming promotes acidification, acidification weakens organisms' ability to cope with warming, and deoxygenation compounds both stresses. Addressing these challenges requires not only reducing greenhouse gas emissions but also tackling local sources of pollution, establishing marine protected areas, and investing in ocean monitoring and research.`,
      questions: [
        { number: 1, type: "true_false_not_given", text: "Oceans absorb approximately half of all human-produced CO₂.", correctAnswer: "False", explanation: "The passage states oceans absorb approximately 30 percent." },
        { number: 2, type: "true_false_not_given", text: "Zooxanthellae provide corals with energy through photosynthesis.", correctAnswer: "True" },
        { number: 3, type: "true_false_not_given", text: "The Great Barrier Reef experienced mass bleaching in 2018.", correctAnswer: "Not Given", explanation: "The passage mentions 2016, 2017, and 2020 but not 2018." },
        { number: 4, type: "true_false_not_given", text: "Ocean acidification reduces the availability of carbonate ions.", correctAnswer: "True" },
        { number: 5, type: "true_false_not_given", text: "Cod populations in the North Sea have increased.", correctAnswer: "False", explanation: "The passage states cold-water species like cod have declined." },
        { number: 6, type: "true_false_not_given", text: "Dead zones are areas where oxygen levels are too low for most marine life.", correctAnswer: "True" },
        { number: 7, type: "true_false_not_given", text: "The Gulf of Mexico dead zone is the largest in the world.", correctAnswer: "Not Given", explanation: "The passage describes its size but does not compare it to others globally." },
        { number: 8, type: "sentence_completion", text: "Corals expel their algae in a process called _______.", correctAnswer: "bleaching" },
        { number: 9, type: "sentence_completion", text: "CO₂ dissolving in seawater forms _______ acid.", correctAnswer: "carbonic" },
        { number: 10, type: "sentence_completion", text: "Many fish populations are shifting _______ in search of cooler waters.", correctAnswer: "poleward" },
        { number: 11, type: "sentence_completion", text: "Increased nutrient runoff from agriculture fuels _______ blooms.", correctAnswer: "algal" },
        { number: 12, type: "sentence_completion", text: "The Gulf of Mexico dead zone regularly exceeds _______ square kilometres.", correctAnswer: "15,000" },
        { number: 13, type: "sentence_completion", text: "Warming promotes acidification, which weakens organisms' ability to cope with _______.", correctAnswer: "warming" },
      ],
    },
    {
      title: "The Development of Writing Systems",
      text: `Paragraph A
The earliest known writing systems emerged independently in several parts of the world around 3500–3000 BCE, driven primarily by the administrative needs of increasingly complex societies. In Mesopotamia, the Sumerians developed a system of pictographs — simplified drawings representing objects and concepts — to keep records of agricultural produce, livestock, and trade transactions. These early symbols were pressed into soft clay tablets using a reed stylus.

Paragraph B
Over the following centuries, Sumerian pictographs evolved into cuneiform, a system of wedge-shaped marks that could represent not only objects but also sounds and abstract ideas. This made cuneiform far more versatile than its pictographic predecessor, enabling the recording of laws, literature, and scientific observations. The famous Code of Hammurabi, one of the oldest known legal codes, was written in cuneiform around 1754 BCE.

Paragraph C
In Egypt, a parallel writing tradition developed along the banks of the Nile. Egyptian hieroglyphics combined logographic and alphabetic elements in a visually striking system closely associated with religious and royal contexts. Hieroglyphic inscriptions adorned temple walls, tomb chambers, and monumental obelisks, serving both communicative and decorative purposes. The priests who mastered this complex script wielded considerable cultural and political influence.

Paragraph D
The Phoenician alphabet, developed around 1050 BCE in the coastal trading cities of present-day Lebanon, represented a revolutionary simplification. By reducing the writing system to just 22 consonant symbols, the Phoenicians created a script that was far easier to learn and use than the elaborate systems it replaced. Phoenician traders spread this alphabet throughout the Mediterranean world, where it was adopted and adapted by the Greeks, who added symbols for vowels, creating the ancestor of all modern European alphabets.

Paragraph E
In China, a logographic writing system developed independently around 1200 BCE, with the earliest examples found on oracle bones used for divination during the Shang dynasty. Unlike alphabetic systems, Chinese characters represent whole words or morphemes rather than individual sounds. This system, though demanding to learn — requiring knowledge of thousands of characters — has provided cultural continuity across millennia and across the many distinct spoken languages of China.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Paragraph A", options: p2Headings, correctAnswer: "ii" },
        { number: 15, type: "matching_headings", text: "Paragraph B", options: p2Headings, correctAnswer: "iv" },
        { number: 16, type: "matching_headings", text: "Paragraph C", options: p2Headings, correctAnswer: "vii" },
        { number: 17, type: "matching_headings", text: "Paragraph D", options: p2Headings, correctAnswer: "iii" },
        { number: 18, type: "matching_headings", text: "Paragraph E", options: p2Headings, correctAnswer: "v" },
        { number: 19, type: "multiple_choice", text: "What drove the development of the earliest writing systems?", options: ["A Religious ceremonies", "B Administrative needs", "C Military communication", "D Artistic expression"], correctAnswer: "B" },
        { number: 20, type: "multiple_choice", text: "What made cuneiform more versatile than pictographs?", options: ["A It used coloured inks", "B It could represent sounds and abstract ideas", "C It was carved in stone", "D It used fewer symbols"], correctAnswer: "B" },
        { number: 21, type: "multiple_choice", text: "How many consonant symbols did the Phoenician alphabet contain?", options: ["A 16", "B 22", "C 26", "D 30"], correctAnswer: "B" },
        { number: 22, type: "multiple_choice", text: "What did the Greeks add to the Phoenician alphabet?", options: ["A Consonant symbols", "B Punctuation marks", "C Vowel symbols", "D Number symbols"], correctAnswer: "C" },
        { number: 23, type: "multiple_choice", text: "Chinese characters represent:", options: ["A Individual sounds", "B Whole words or morphemes", "C Syllables only", "D Grammatical structures"], correctAnswer: "B" },
        { number: 24, type: "summary_completion", text: "Sumerian pictographs were pressed into soft clay tablets using a reed _______.", correctAnswer: "stylus" },
        { number: 25, type: "summary_completion", text: "The Code of Hammurabi is one of the oldest known _______ codes.", correctAnswer: "legal" },
        { number: 26, type: "summary_completion", text: "The earliest Chinese characters were found on _______ bones.", correctAnswer: "oracle" },
      ],
    },
    {
      title: "Renewable Energy Technologies",
      text: `Paragraph A
The transition from fossil fuels to renewable energy sources is widely regarded as one of the most important challenges of the twenty-first century. Solar, wind, hydroelectric, and geothermal technologies each offer distinct advantages and face particular limitations, but collectively they represent the most promising pathway to a low-carbon energy future.

Paragraph B
Solar photovoltaic (PV) technology converts sunlight directly into electricity using semiconductor materials, most commonly silicon. The cost of solar PV has plummeted by over 90 percent since 2010, making it the cheapest source of new electricity generation in many parts of the world. Large-scale solar farms now cover thousands of hectares in sun-rich regions, while rooftop installations allow individual households to generate their own power.

Paragraph C
Wind energy harnesses the kinetic energy of moving air through turbines mounted on tall towers. Modern onshore wind turbines can generate up to 5 megawatts of power, while offshore installations, benefiting from stronger and more consistent winds, can exceed 15 megawatts per turbine. Denmark, a pioneer in wind energy, now generates more than 50 percent of its electricity from wind on an annual basis.

Paragraph D
Hydroelectric power, generated by channelling flowing water through turbines, remains the largest source of renewable electricity worldwide. Large dams such as China's Three Gorges Dam can produce enormous quantities of power, but their construction often involves significant environmental and social costs, including the flooding of ecosystems and the displacement of communities.

Paragraph E
Geothermal energy exploits heat stored beneath the Earth's surface, typically in volcanically active regions. Iceland, where geothermal energy supplies approximately 25 percent of electricity generation and heats nearly 90 percent of homes, demonstrates the technology's potential. However, high upfront drilling costs and geographical limitations restrict widespread deployment.

Paragraph F
Energy storage remains the critical bottleneck for renewable energy expansion. Because solar and wind power are intermittent — dependent on weather conditions and time of day — reliable electricity supply requires either large-scale battery systems, pumped hydro storage, or other technologies capable of storing surplus generation for later use. Lithium-ion batteries have improved rapidly, but researchers are actively developing alternatives such as solid-state batteries, flow batteries, and green hydrogen as longer-duration storage solutions.

Paragraph G
The path to a fully renewable energy system will require not only technological innovation but also substantial investment in grid infrastructure, supportive policy frameworks, and international cooperation. While challenges remain significant, the pace of progress in recent years provides grounds for cautious optimism about achieving meaningful reductions in carbon emissions within the coming decades.`,
      questions: [
        { number: 27, type: "matching_information", text: "The environmental and social costs of a renewable technology", options: p3Paragraphs, correctAnswer: "D" },
        { number: 28, type: "matching_information", text: "A country generating over half its electricity from one renewable source", options: p3Paragraphs, correctAnswer: "C" },
        { number: 29, type: "matching_information", text: "The dramatic decline in cost of a specific technology", options: p3Paragraphs, correctAnswer: "B" },
        { number: 30, type: "matching_information", text: "Alternative storage technologies being researched", options: p3Paragraphs, correctAnswer: "F" },
        { number: 31, type: "matching_information", text: "The use of underground heat for both electricity and heating", options: p3Paragraphs, correctAnswer: "E" },
        { number: 32, type: "matching_information", text: "The need for policy and international cooperation", options: p3Paragraphs, correctAnswer: "G" },
        { number: 33, type: "yes_no_not_given", text: "The author believes solar PV is the most important renewable technology.", correctAnswer: "Not Given", explanation: "The passage discusses multiple technologies without ranking them." },
        { number: 34, type: "yes_no_not_given", text: "Offshore wind turbines can produce more power than onshore turbines.", correctAnswer: "Yes", explanation: "The passage states offshore installations can exceed 15 MW compared to up to 5 MW onshore." },
        { number: 35, type: "yes_no_not_given", text: "Large hydroelectric dams have no negative environmental effects.", correctAnswer: "No", explanation: "The passage mentions significant environmental and social costs." },
        { number: 36, type: "yes_no_not_given", text: "Lithium-ion batteries are sufficient for long-duration energy storage.", correctAnswer: "No", explanation: "The passage indicates researchers are developing alternatives for longer-duration storage." },
        { number: 37, type: "short_answer", text: "What is the largest source of renewable electricity worldwide?", correctAnswer: "hydroelectric power" },
        { number: 38, type: "short_answer", text: "What percentage of Iceland's homes are heated by geothermal energy?", correctAnswer: "90 percent" },
        { number: 39, type: "short_answer", text: "What type of batteries have improved rapidly for energy storage?", correctAnswer: "lithium-ion batteries" },
        { number: 40, type: "short_answer", text: "What characteristic of solar and wind makes storage necessary?", correctAnswer: "intermittent" },
      ],
    },
  ],
};
