import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_22: ReadingTest = {
  id: 22,
  passages: [
    {
      title: "The Development of Libraries",
      text: `Libraries are among the oldest cultural institutions in human civilisation, with origins stretching back more than four thousand years. The earliest known collections of written records were found in the ancient cities of Mesopotamia, where clay tablets inscribed with cuneiform script were stored in temple and palace archives. These collections served primarily administrative and religious purposes, recording laws, commercial transactions, and sacred texts rather than serving the broader public.

The most celebrated library of the ancient world was the Library of Alexandria, established in the third century BCE under the patronage of the Ptolemaic dynasty in Egypt. At its peak, the library is believed to have housed several hundred thousand scrolls, encompassing virtually the entire body of Greek literary and scientific knowledge. Scholars from across the Mediterranean world travelled to Alexandria to study and contribute to its collection. The library also pioneered systematic approaches to cataloguing, with the scholar Callimachus creating what is considered the first library catalogue, organising works by author and subject.

The destruction of the Library of Alexandria — which occurred gradually through multiple events rather than in a single catastrophe — represented an incalculable loss to human knowledge. However, the tradition of library building continued throughout the ancient and medieval periods. Roman public libraries, of which there were eventually twenty-eight in the city of Rome alone, were often attached to public baths and served as social as well as intellectual centres. During the medieval period in Europe, monastic libraries preserved classical learning through centuries of political upheaval, with monks painstakingly copying manuscripts by hand.

The invention of the printing press by Johannes Gutenberg around 1440 transformed libraries fundamentally. Books, which had previously been rare and extraordinarily expensive handwritten objects, could now be produced in multiple copies relatively quickly and cheaply. Library collections grew rapidly, and the challenge shifted from the scarcity of books to their organisation and management. The development of systematic classification schemes — notably the Dewey Decimal System, introduced by Melvil Dewey in 1876, and the Library of Congress Classification, adopted in 1897 — provided standardised frameworks for organising increasingly large collections.

The concept of the free public library, supported by taxation and open to all citizens regardless of social status, emerged in the mid-nineteenth century. The United Kingdom's Public Libraries Act of 1850 empowered local authorities to establish tax-funded libraries, and similar legislation followed in other countries. The American industrialist Andrew Carnegie became the most prolific benefactor of public libraries in history, funding the construction of more than 2,500 libraries in the United States, the United Kingdom, and other English-speaking countries between 1883 and 1929.

The digital revolution of the late twentieth and early twenty-first centuries has posed both opportunities and challenges for libraries. Electronic databases, digital archives, and the internet have vastly expanded access to information, enabling library users to search millions of records instantly. E-books and digital lending have extended libraries' reach beyond their physical walls. However, the abundance of freely available online information has led some to question the continued relevance of physical libraries. Library advocates argue that libraries provide far more than access to books — they serve as community centres, offer digital literacy training, provide meeting spaces, and support lifelong learning, functions that remain vital in an increasingly digital world.`,
      questions: [
        { number: 1, type: "true_false_not_given", text: "The earliest known collections of written records were found in Egypt.", correctAnswer: "False", explanation: "The passage states they were found in 'ancient cities of Mesopotamia'." },
        { number: 2, type: "true_false_not_given", text: "The Library of Alexandria housed over one million scrolls at its peak.", correctAnswer: "Not Given", explanation: "The passage says 'several hundred thousand scrolls' without specifying over a million." },
        { number: 3, type: "true_false_not_given", text: "Callimachus is credited with creating the first library catalogue.", correctAnswer: "True", explanation: "The passage states he created 'what is considered the first library catalogue'." },
        { number: 4, type: "true_false_not_given", text: "The Library of Alexandria was destroyed in a single event.", correctAnswer: "False", explanation: "The passage says it 'occurred gradually through multiple events rather than in a single catastrophe'." },
        { number: 5, type: "true_false_not_given", text: "There were twenty-eight Roman public libraries in the city of Rome.", correctAnswer: "True", explanation: "Directly stated in the passage." },
        { number: 6, type: "true_false_not_given", text: "The Dewey Decimal System was more widely adopted than the Library of Congress system.", correctAnswer: "Not Given", explanation: "The passage does not compare their relative adoption rates." },
        { number: 7, type: "true_false_not_given", text: "Andrew Carnegie funded the construction of more than 2,500 libraries.", correctAnswer: "True", explanation: "Directly stated in the passage." },
        { number: 8, type: "sentence_completion", text: "The earliest written records in Mesopotamia were inscribed on clay tablets using ________ script.", correctAnswer: "cuneiform", explanation: "The passage states 'clay tablets inscribed with cuneiform script'." },
        { number: 9, type: "sentence_completion", text: "Medieval monks preserved classical learning by copying ________ by hand.", correctAnswer: "manuscripts", explanation: "The passage states 'monks painstakingly copying manuscripts by hand'." },
        { number: 10, type: "sentence_completion", text: "The printing press was invented by Johannes Gutenberg around ________.", correctAnswer: "1440", explanation: "Directly stated in the passage." },
        { number: 11, type: "sentence_completion", text: "The UK's Public Libraries Act empowered local authorities to establish ________-funded libraries.", correctAnswer: "tax", explanation: "The passage mentions 'tax-funded libraries'." },
        { number: 12, type: "sentence_completion", text: "Libraries provide digital ________ training as one of their modern functions.", correctAnswer: "literacy", explanation: "The passage states libraries 'offer digital literacy training'." },
        { number: 13, type: "sentence_completion", text: "Roman public libraries were often attached to public ________.", correctAnswer: "baths", explanation: "The passage states libraries 'were often attached to public baths'." },
      ],
    },
    {
      title: "Animal Migration",
      text: `Paragraph A
Animal migration is one of the most remarkable phenomena in the natural world. Each year, billions of creatures — from tiny insects to massive whales — undertake journeys of extraordinary length and precision, driven by the need to find food, suitable breeding grounds, or favourable climatic conditions. These journeys, which may span thousands of kilometres and traverse oceans, deserts, and mountain ranges, have fascinated naturalists for centuries and continue to reveal surprising complexities to modern researchers.

Paragraph B
Among the most impressive migrants are Arctic terns, small seabirds weighing barely one hundred grams that undertake the longest known migration of any animal. Each year, Arctic terns fly from their breeding grounds in the Arctic to the Antarctic and back again, covering approximately seventy thousand kilometres annually. Over a lifespan of thirty years, an individual tern may fly a total distance equivalent to three round trips to the moon. The birds time their migrations to experience two polar summers each year, maximising their exposure to daylight and the abundant food supplies that accompany long summer days.

Paragraph C
The mechanisms by which animals navigate during migration remain a subject of active research. Birds are known to use multiple navigational cues, including the position of the sun and stars, the Earth's magnetic field, and visual landmarks. Experiments have shown that some species possess magnetite crystals in their beaks or inner ears that function as biological compasses. Other species appear to detect the angle of polarised light in the sky, providing directional information even on overcast days. Young birds of many species learn migration routes by following experienced adults, but some species, such as cuckoos, migrate successfully to destinations they have never visited, suggesting that route information is encoded genetically.

Paragraph D
Marine migrations present their own distinctive challenges and adaptations. Humpback whales travel up to eight thousand kilometres between their cold-water feeding grounds near the poles and their warm-water breeding areas in tropical seas. During these journeys, which may last several weeks, the whales eat little or nothing, relying on energy reserves stored in their thick layer of blubber. Sea turtles navigate across entire ocean basins to return to the specific beaches where they were born to lay their eggs, a feat of navigation that scientists believe relies partly on detecting the unique magnetic signature of their natal beach.

Paragraph E
Climate change is increasingly disrupting established migration patterns worldwide. Rising temperatures are causing some species to shift their ranges poleward or to higher elevations, altering the timing and routes of traditional migrations. Migratory birds in Europe are arriving at their breeding grounds earlier in spring, but the insects and plants they depend on may not have shifted their own cycles at the same rate, creating ecological mismatches that can reduce breeding success. Ocean warming is affecting the distribution of plankton and fish stocks, forcing marine migrants to travel greater distances to find adequate food.

Paragraph F
Conservation efforts to protect migratory species face unique challenges because these animals cross multiple national boundaries during their journeys. International agreements, such as the Convention on Migratory Species, seek to coordinate protection across countries, but enforcement remains inconsistent. Habitat loss along migration corridors — the destruction of wetlands used as stopover sites by migratory birds, for example — can devastate populations even if breeding and wintering grounds are protected. Effective conservation of migratory species requires a holistic approach that protects the entire network of habitats upon which these animals depend throughout their annual cycles.`,
      questions: (() => {
        const headings = [
          "i. The extraordinary journey of the Arctic tern",
          "ii. How climate change affects migration timing",
          "iii. An overview of migration in the animal kingdom",
          "iv. International efforts to protect migrating animals",
          "v. Navigational tools used by migrating birds",
          "vi. The economic impact of migration on local communities",
          "vii. Long-distance travel in the ocean",
          "viii. The role of genetics in migration patterns",
        ];
        return [
          { number: 14, type: "matching_headings" as const, text: "Paragraph A", options: headings, correctAnswer: "iii", explanation: "Paragraph A provides a general overview of animal migration." },
          { number: 15, type: "matching_headings" as const, text: "Paragraph B", options: headings, correctAnswer: "i", explanation: "Paragraph B focuses specifically on Arctic terns." },
          { number: 16, type: "matching_headings" as const, text: "Paragraph C", options: headings, correctAnswer: "v", explanation: "Paragraph C discusses navigation mechanisms including magnetic fields and visual cues." },
          { number: 17, type: "matching_headings" as const, text: "Paragraph D", options: headings, correctAnswer: "vii", explanation: "Paragraph D discusses marine migrations of whales and sea turtles." },
          { number: 18, type: "matching_headings" as const, text: "Paragraph E", options: headings, correctAnswer: "ii", explanation: "Paragraph E discusses climate change disrupting migration patterns." },
          { number: 19, type: "matching_headings" as const, text: "Paragraph F", options: headings, correctAnswer: "iv", explanation: "Paragraph F discusses international conservation agreements." },
          { number: 20, type: "table_completion" as const, text: "Arctic terns cover approximately ________ kilometres each year.", correctAnswer: "seventy thousand", explanation: "The passage states 'approximately seventy thousand kilometres annually'." },
          { number: 21, type: "table_completion" as const, text: "Some bird species have magnetite crystals in their beaks or inner ________.", correctAnswer: "ears", explanation: "The passage mentions 'magnetite crystals in their beaks or inner ears'." },
          { number: 22, type: "table_completion" as const, text: "Humpback whales rely on energy stored in their thick layer of ________.", correctAnswer: "blubber", explanation: "The passage states 'energy reserves stored in their thick layer of blubber'." },
          { number: 23, type: "short_answer" as const, text: "What international agreement seeks to coordinate protection of migratory species?", correctAnswer: "Convention on Migratory Species", explanation: "Directly named in the passage." },
          { number: 24, type: "short_answer" as const, text: "What type of habitat destruction along migration corridors is specifically mentioned?", correctAnswer: "wetlands", explanation: "The passage mentions 'the destruction of wetlands used as stopover sites'." },
          { number: 25, type: "short_answer" as const, text: "What do sea turtles detect to navigate back to their birth beach?", correctAnswer: "magnetic signature", explanation: "The passage mentions 'the unique magnetic signature of their natal beach'." },
          { number: 26, type: "short_answer" as const, text: "What are migratory birds in Europe arriving at earlier due to rising temperatures?", correctAnswer: "breeding grounds", explanation: "The passage states birds 'are arriving at their breeding grounds earlier in spring'." },
        ];
      })(),
    },
    {
      title: "The Future of Space Tourism",
      text: `The concept of space tourism — paying civilians travelling beyond Earth's atmosphere for recreational purposes — has progressed from science fiction fantasy to emerging commercial reality within just two decades. What was once the exclusive domain of government-trained astronauts has been opened, tentatively, to private individuals willing and able to pay extraordinary sums for the experience of spaceflight. As technology advances and competition intensifies among private space companies, advocates predict that space tourism will eventually become accessible to a much broader segment of the population.

The modern era of space tourism effectively began in 2001, when American businessman Dennis Tito paid a reported twenty million dollars for a seat aboard a Russian Soyuz spacecraft and spent nearly eight days aboard the International Space Station. Between 2001 and 2009, seven private citizens made similar orbital flights, all brokered by the American company Space Adventures and launched on Russian vehicles. These early space tourists underwent months of rigorous training at Russia's Star City facility before their flights, and the prohibitive cost ensured that the experience remained limited to extremely wealthy individuals.

The landscape shifted dramatically in 2021, when three companies — Virgin Galactic, Blue Origin, and SpaceX — each conducted crewed flights carrying private passengers. Virgin Galactic and Blue Origin focused on suborbital flights, brief journeys reaching the edge of space and providing several minutes of weightlessness before returning to Earth. SpaceX went further, launching the Inspiration4 mission, an entirely privately funded orbital flight that circled Earth for three days with a crew of four civilians, none of whom were professional astronauts. The mission demonstrated that orbital spaceflight could be conducted safely without government astronauts on board.

Suborbital space tourism represents the most immediately accessible tier of the market. Flights lasting approximately ninety minutes, with only a few minutes spent above the Kármán line — the internationally recognised boundary of space at one hundred kilometres altitude — are priced at several hundred thousand dollars per seat. While still far beyond the means of most people, these prices are orders of magnitude lower than orbital flights. Companies are working to increase flight frequency and reduce costs through reusable vehicle technology and operational efficiency improvements.

Orbital tourism, offering longer stays in space, remains considerably more expensive but is developing rapidly. SpaceX has contracted with multiple clients for flights aboard its Crew Dragon spacecraft, and the company is developing the Starship vehicle, which it hopes will further reduce per-seat costs through its fully reusable design and much larger passenger capacity. Several companies are developing commercial space stations intended to host tourists, researchers, and commercial activities in low Earth orbit. Axiom Space has already sent private missions to the International Space Station and is constructing modules for what it plans to be the first commercial space station.

The potential environmental impact of space tourism has drawn scrutiny from scientists and environmentalists. Rocket engines release carbon dioxide, water vapour, black carbon (soot), and alumina particles directly into the upper atmosphere and stratosphere, where their warming effects may be disproportionately large compared with emissions at ground level. A 2022 study published in the journal Earth's Future warned that a significant increase in rocket launches could deplete the ozone layer and contribute to climate change. The industry argues that its current emissions are negligible compared with aviation and that ongoing research into cleaner propellant technologies will mitigate future impacts.

Safety remains the paramount concern for the industry. The destruction of the Space Shuttle Challenger in 1986 and Columbia in 2003, along with fatal accidents during Virgin Galactic's test flight programme, underscore the inherent risks of spaceflight. Regulatory frameworks are still evolving, with the United States Federal Aviation Administration currently operating under a "learning period" policy that allows the commercial spaceflight industry to develop safety standards based on operational experience rather than imposing prescriptive regulations prematurely. As flight frequency increases and more data becomes available, comprehensive safety standards will need to be established to protect passengers while permitting continued innovation.`,
      questions: [
        { number: 27, type: "multiple_choice", text: "Who was the first space tourist?", options: ["A. Richard Branson", "B. Jeff Bezos", "C. Dennis Tito", "D. Elon Musk"], correctAnswer: "C", explanation: "The passage identifies Dennis Tito as paying for the first tourist flight in 2001." },
        { number: 28, type: "multiple_choice", text: "What was notable about the Inspiration4 mission?", options: ["A. It was the cheapest space flight ever", "B. It was the first orbital flight with no professional astronauts", "C. It visited the International Space Station", "D. It lasted more than a week"], correctAnswer: "B", explanation: "The passage states the crew were 'four civilians, none of whom were professional astronauts'." },
        { number: 29, type: "multiple_choice", text: "Where is the Kármán line located?", options: ["A. 50 kilometres altitude", "B. 80 kilometres altitude", "C. 100 kilometres altitude", "D. 200 kilometres altitude"], correctAnswer: "C", explanation: "Defined as 'the internationally recognised boundary of space at one hundred kilometres altitude'." },
        { number: 30, type: "multiple_choice", text: "Which company is building the first commercial space station?", options: ["A. SpaceX", "B. Blue Origin", "C. Virgin Galactic", "D. Axiom Space"], correctAnswer: "D", explanation: "The passage states Axiom Space 'is constructing modules for what it plans to be the first commercial space station'." },
        { number: 31, type: "flow_chart_completion", text: "Dennis Tito paid twenty million dollars and spent nearly ________ days aboard the ISS.", correctAnswer: "eight", explanation: "The passage states 'spent nearly eight days aboard the International Space Station'." },
        { number: 32, type: "flow_chart_completion", text: "Early space tourists underwent months of training at Russia's ________ facility.", correctAnswer: "Star City", explanation: "The passage mentions 'Russia's Star City facility'." },
        { number: 33, type: "flow_chart_completion", text: "In 2021, three companies conducted crewed flights: Virgin Galactic, Blue Origin, and ________.", correctAnswer: "SpaceX", explanation: "Directly stated in the passage." },
        { number: 34, type: "flow_chart_completion", text: "Suborbital flights last approximately ________ minutes.", correctAnswer: "ninety", explanation: "The passage states 'flights lasting approximately ninety minutes'." },
        { number: 35, type: "sentence_completion", text: "Rocket engines release carbon dioxide, water vapour, black carbon, and ________ particles into the upper atmosphere.", correctAnswer: "alumina", explanation: "The passage lists 'carbon dioxide, water vapour, black carbon (soot), and alumina particles'." },
        { number: 36, type: "sentence_completion", text: "A 2022 study warned that increased launches could deplete the ________ layer.", correctAnswer: "ozone", explanation: "The passage states they 'could deplete the ozone layer'." },
        { number: 37, type: "sentence_completion", text: "SpaceX is developing the ________ vehicle, which features a fully reusable design.", correctAnswer: "Starship", explanation: "The passage mentions 'the Starship vehicle'." },
        { number: 38, type: "sentence_completion", text: "The US Federal Aviation Administration is operating under a '________' policy for commercial spaceflight.", correctAnswer: "learning period", explanation: "The passage states 'a \"learning period\" policy'." },
        { number: 39, type: "sentence_completion", text: "Between 2001 and 2009, ________ private citizens made orbital flights.", correctAnswer: "seven", explanation: "The passage states 'seven private citizens made similar orbital flights'." },
        { number: 40, type: "sentence_completion", text: "Suborbital flights are priced at several hundred thousand ________ per seat.", correctAnswer: "dollars", explanation: "The passage states 'priced at several hundred thousand dollars per seat'." },
      ],
    },
  ],
};
