import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_38: ReadingTest = {
  id: 38,
  passages: [
    {
      title: "History of Medicine",
      text: `The practice of medicine is as old as civilisation itself. Archaeological evidence from ancient Mesopotamia, dating to around 2100 BCE, includes clay tablets inscribed with lists of symptoms and herbal treatments, suggesting that healers had already begun to systematise medical knowledge thousands of years ago. In ancient Egypt, the Ebers Papyrus, composed around 1550 BCE, catalogues more than seven hundred remedies for ailments ranging from eye infections to digestive disorders, blending empirical observation with magical incantations.

The ancient Greeks transformed medicine by insisting that disease had natural, rather than supernatural, causes. Hippocrates of Kos, born around 460 BCE, is widely regarded as the father of Western medicine. He and his followers rejected the prevailing belief that illness was a punishment from the gods, proposing instead that health depended on the balance of four bodily fluids, or humours: blood, phlegm, yellow bile, and black bile. Although the humoral theory was ultimately incorrect, the Hippocratic approach — systematic observation, documentation of symptoms, and rational analysis — established enduring principles of clinical practice. The Hippocratic Oath, a set of ethical guidelines attributed to Hippocrates, continues to influence medical ethics today.

In the Islamic Golden Age, spanning roughly from the eighth to the fourteenth century, scholars in the Muslim world preserved, translated, and extended Greek medical texts. The Persian polymath Ibn Sina, known in Europe as Avicenna, compiled The Canon of Medicine around 1025 CE, a five-volume encyclopaedia that integrated Greek, Roman, and Islamic medical knowledge. The Canon served as a standard medical textbook in European universities until the seventeenth century. Islamic physicians also pioneered surgical techniques, developed early forms of anaesthesia using opium and other substances, and established some of the world's first hospitals with separate wards for different conditions.

The Renaissance and the Scientific Revolution brought revolutionary advances. Andreas Vesalius published De Humani Corporis Fabrica in 1543, correcting numerous anatomical errors that had persisted since the time of Galen and establishing dissection-based anatomy as the foundation of medical education. William Harvey demonstrated the circulation of blood in 1628, overturning centuries of misconception. The invention of the microscope in the late seventeenth century opened an entirely new world, revealing the existence of micro-organisms that would later be linked to disease.

The nineteenth century witnessed what many historians consider the greatest transformation in medical history. In 1847, the Hungarian physician Ignaz Semmelweis demonstrated that handwashing with chlorinated lime solutions dramatically reduced mortality from puerperal fever in maternity wards — a finding initially met with hostility from the medical establishment. Louis Pasteur's germ theory of disease, developed in the 1860s, provided the scientific framework that vindicated Semmelweis and revolutionised hygiene. Joseph Lister subsequently introduced antiseptic surgery, spraying carbolic acid over surgical instruments and incisions to prevent infection, and surgical mortality rates plummeted.

The twentieth century saw the advent of antibiotics, vaccines, and advanced diagnostic imaging. Alexander Fleming's discovery of penicillin in 1928 — and its mass production during the Second World War — saved millions of lives and inaugurated the antibiotic era. Vaccination programmes eradicated smallpox by 1980 and have brought polio to the brink of elimination. X-rays, magnetic resonance imaging (MRI), and computed tomography (CT) scanning have given physicians the ability to visualise the interior of the living body with extraordinary precision.

Today, medicine stands at the threshold of yet another revolution. Genomic sequencing, personalised therapies, artificial intelligence, and robotic surgery are transforming diagnosis and treatment. The development of mRNA vaccines during the COVID-19 pandemic demonstrated that new medical technologies can be brought from concept to global deployment in under a year. As the boundaries of knowledge continue to expand, the history of medicine reminds us that progress often depends not only on scientific discovery but also on the courage to challenge established beliefs.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "What does the Ebers Papyrus contain?", options: ["A Instructions for building temples", "B Over 700 medical remedies", "C Recipes for Egyptian cuisine", "D Maps of ancient trade routes"], correctAnswer: "B", explanation: "The passage says the Ebers Papyrus 'catalogues more than seven hundred remedies.'" },
        { number: 2, type: "multiple_choice", text: "What did Hippocrates propose as the basis of health?", options: ["A Divine intervention", "B Regular exercise", "C Balance of four bodily humours", "D Herbal remedies"], correctAnswer: "C", explanation: "The passage says health 'depended on the balance of four bodily fluids, or humours.'" },
        { number: 3, type: "multiple_choice", text: "How long did The Canon of Medicine serve as a standard textbook?", options: ["A Until the 15th century", "B Until the 17th century", "C Until the 19th century", "D Until the 20th century"], correctAnswer: "B", explanation: "The passage says it served 'as a standard medical textbook in European universities until the seventeenth century.'" },
        { number: 4, type: "multiple_choice", text: "Who introduced antiseptic surgery?", options: ["A Alexander Fleming", "B Louis Pasteur", "C Joseph Lister", "D Ignaz Semmelweis"], correctAnswer: "C", explanation: "The passage says 'Joseph Lister subsequently introduced antiseptic surgery.'" },
        { number: 5, type: "true_false_not_given", text: "The ancient Mesopotamians used clay tablets to record medical information.", correctAnswer: "TRUE", explanation: "The passage says 'clay tablets inscribed with lists of symptoms and herbal treatments.'" },
        { number: 6, type: "true_false_not_given", text: "Hippocrates believed illness was a punishment from the gods.", correctAnswer: "FALSE", explanation: "The passage says Hippocrates and his followers 'rejected the prevailing belief that illness was a punishment from the gods.'" },
        { number: 7, type: "true_false_not_given", text: "Islamic physicians are credited with developing early forms of anaesthesia.", correctAnswer: "TRUE", explanation: "The passage says Islamic physicians 'developed early forms of anaesthesia using opium and other substances.'" },
        { number: 8, type: "true_false_not_given", text: "Semmelweis's findings about handwashing were immediately accepted by the medical community.", correctAnswer: "FALSE", explanation: "The passage says his finding was 'initially met with hostility from the medical establishment.'" },
        { number: 9, type: "true_false_not_given", text: "Penicillin was first used commercially in the 1930s.", correctAnswer: "NOT GIVEN", explanation: "The passage mentions Fleming's discovery in 1928 and mass production during WWII but doesn't specify commercial use in the 1930s." },
        { number: 10, type: "true_false_not_given", text: "Smallpox was eradicated by 1980.", correctAnswer: "TRUE", explanation: "The passage says 'Vaccination programmes eradicated smallpox by 1980.'" },
        { number: 11, type: "true_false_not_given", text: "Vesalius published his anatomy work before Harvey demonstrated blood circulation.", correctAnswer: "TRUE", explanation: "Vesalius published in 1543; Harvey demonstrated blood circulation in 1628." },
        { number: 12, type: "true_false_not_given", text: "MRI technology was developed in ancient Egypt.", correctAnswer: "FALSE", explanation: "MRI is described as a twentieth-century development." },
        { number: 13, type: "true_false_not_given", text: "mRNA vaccine technology took over five years to develop during the pandemic.", correctAnswer: "FALSE", explanation: "The passage says mRNA vaccines were 'brought from concept to global deployment in under a year.'" },
      ],
    },
    {
      title: "Air Pollution in Cities",
      text: `A. Urban air pollution is one of the most pressing environmental health challenges of the twenty-first century. The World Health Organization estimates that ambient air pollution causes approximately 4.2 million premature deaths each year, with the burden falling disproportionately on residents of low- and middle-income countries. In many of the world's largest cities, pollutant concentrations regularly exceed WHO guideline levels by a factor of five or more, exposing hundreds of millions of people to air that is demonstrably harmful to breathe.

B. The primary sources of urban air pollution include road transport, industrial facilities, power generation, construction activity, and the burning of solid fuels for domestic heating and cooking. Motor vehicles are the dominant source in most developed-world cities: exhaust emissions contain nitrogen oxides (NOx), carbon monoxide (CO), volatile organic compounds (VOCs), and fine particulate matter (PM2.5) — particles with a diameter of less than 2.5 micrometres that can penetrate deep into the lungs and enter the bloodstream. Diesel engines produce particularly high levels of NOx and PM2.5, which is why many cities have introduced restrictions on diesel vehicles.

C. The health effects of air pollution are well documented and wide-ranging. Short-term exposure to high levels of PM2.5 triggers respiratory symptoms such as coughing, wheezing, and shortness of breath, and can precipitate asthma attacks and heart attacks in vulnerable individuals. Long-term exposure is associated with chronic obstructive pulmonary disease (COPD), lung cancer, cardiovascular disease, and neurological disorders including dementia. Children are especially susceptible because their lungs are still developing, and studies have linked childhood exposure to stunted lung growth and increased rates of asthma.

D. Low-emission zones (LEZs) have become one of the most widely adopted policy responses. An LEZ restricts the entry of the most polluting vehicles into a designated urban area, typically the city centre. London's Ultra Low Emission Zone (ULEZ), introduced in 2019 and expanded in 2021, charges vehicles that do not meet strict emissions standards a daily fee. Transport for London reported that roadside nitrogen dioxide concentrations within the zone fell by approximately forty-four per cent in the first two years of operation. Berlin, Brussels, Amsterdam, and more than three hundred other European cities have implemented similar schemes.

E. Green infrastructure offers a complementary approach. Trees and vegetation absorb gaseous pollutants and trap particulate matter on their leaves, acting as natural air filters. A study published in the journal Environmental Science & Technology estimated that urban trees in the United States remove approximately 17.4 million tonnes of air pollutants each year, a service valued at over $6.8 billion. Urban planners are increasingly incorporating green corridors, pocket parks, and vegetated building facades into city designs, not only for air-quality benefits but also to mitigate the urban heat island effect and improve residents' mental health.

F. Technological innovation is also contributing to cleaner urban air. The rapid adoption of electric vehicles, supported by government subsidies and expanding charging infrastructure, is reducing tailpipe emissions in cities around the world. Oslo, for example, now has the highest per-capita density of electric vehicles of any city, and its air quality has improved measurably as a result. In the industrial sector, smokestack scrubbers, catalytic converters, and carbon-capture systems are reducing emissions from factories and power plants.

G. Monitoring technology has advanced considerably. Networks of low-cost air-quality sensors, often mounted on lampposts or bus shelters, provide real-time pollution data at street level, enabling residents to plan routes that minimise exposure and empowering local authorities to target enforcement measures. Satellite remote sensing can map pollution plumes over entire metropolitan regions, revealing hotspots that ground-level monitors might miss.

H. Despite these advances, progress remains uneven. Many cities in South Asia, sub-Saharan Africa, and Southeast Asia lack the financial and institutional resources to enforce emission standards, expand public transport, or invest in green infrastructure. Addressing urban air pollution globally will require not only technological solutions but also sustained political will, international cooperation, and equitable access to clean-energy technologies.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Section A", options: ["I. Policy measures to limit vehicle emissions", "II. The scale of urban air pollution", "III. Sources of pollutants in cities", "IV. Natural solutions for cleaner air", "V. Advances in pollution monitoring", "VI. Health consequences of polluted air", "VII. Challenges in developing nations", "VIII. The role of electric vehicles and industrial technology"], correctAnswer: "II", explanation: "Section A presents the scale and severity of urban air pollution." },
        { number: 15, type: "matching_headings", text: "Section B", options: ["I. Policy measures to limit vehicle emissions", "II. The scale of urban air pollution", "III. Sources of pollutants in cities", "IV. Natural solutions for cleaner air", "V. Advances in pollution monitoring", "VI. Health consequences of polluted air", "VII. Challenges in developing nations", "VIII. The role of electric vehicles and industrial technology"], correctAnswer: "III", explanation: "Section B discusses the primary sources of urban air pollution." },
        { number: 16, type: "matching_headings", text: "Section C", options: ["I. Policy measures to limit vehicle emissions", "II. The scale of urban air pollution", "III. Sources of pollutants in cities", "IV. Natural solutions for cleaner air", "V. Advances in pollution monitoring", "VI. Health consequences of polluted air", "VII. Challenges in developing nations", "VIII. The role of electric vehicles and industrial technology"], correctAnswer: "VI", explanation: "Section C discusses health effects of air pollution." },
        { number: 17, type: "matching_headings", text: "Section D", options: ["I. Policy measures to limit vehicle emissions", "II. The scale of urban air pollution", "III. Sources of pollutants in cities", "IV. Natural solutions for cleaner air", "V. Advances in pollution monitoring", "VI. Health consequences of polluted air", "VII. Challenges in developing nations", "VIII. The role of electric vehicles and industrial technology"], correctAnswer: "I", explanation: "Section D discusses low-emission zones as a policy response." },
        { number: 18, type: "matching_headings", text: "Section E", options: ["I. Policy measures to limit vehicle emissions", "II. The scale of urban air pollution", "III. Sources of pollutants in cities", "IV. Natural solutions for cleaner air", "V. Advances in pollution monitoring", "VI. Health consequences of polluted air", "VII. Challenges in developing nations", "VIII. The role of electric vehicles and industrial technology"], correctAnswer: "IV", explanation: "Section E discusses green infrastructure as natural air filters." },
        { number: 19, type: "matching_headings", text: "Section F", options: ["I. Policy measures to limit vehicle emissions", "II. The scale of urban air pollution", "III. Sources of pollutants in cities", "IV. Natural solutions for cleaner air", "V. Advances in pollution monitoring", "VI. Health consequences of polluted air", "VII. Challenges in developing nations", "VIII. The role of electric vehicles and industrial technology"], correctAnswer: "VIII", explanation: "Section F discusses electric vehicles and industrial emission reduction technology." },
        { number: 20, type: "summary_completion", text: "Air pollution causes approximately __(20)__ million premature deaths each year.", correctAnswer: "4.2", explanation: "The passage says 'approximately 4.2 million premature deaths.'" },
        { number: 21, type: "summary_completion", text: "PM2.5 particles can penetrate the lungs and enter the __(21)__.", correctAnswer: "bloodstream", explanation: "The passage says they 'can penetrate deep into the lungs and enter the bloodstream.'" },
        { number: 22, type: "summary_completion", text: "London's ULEZ reduced roadside nitrogen dioxide by approximately __(22)__ per cent.", correctAnswer: "forty-four", explanation: "The passage says 'fell by approximately forty-four per cent.'" },
        { number: 23, type: "summary_completion", text: "Urban trees in the US remove approximately 17.4 million tonnes of air __(23)__ each year.", correctAnswer: "pollutants", explanation: "The passage says 'remove approximately 17.4 million tonnes of air pollutants.'" },
        { number: 24, type: "summary_completion", text: "Oslo has the highest per-capita density of __(24)__ vehicles of any city.", correctAnswer: "electric", explanation: "The passage says 'the highest per-capita density of electric vehicles.'" },
        { number: 25, type: "summary_completion", text: "Low-cost air-quality sensors are often mounted on lampposts or __(25)__.", correctAnswer: "bus shelters", explanation: "The passage says 'mounted on lampposts or bus shelters.'" },
        { number: 26, type: "summary_completion", text: "Satellite remote sensing can map pollution __(26)__ over entire metropolitan regions.", correctAnswer: "plumes", explanation: "The passage says 'map pollution plumes over entire metropolitan regions.'" },
      ],
    },
    {
      title: "Robotics in Industry",
      text: `The use of robots in manufacturing dates back to the early 1960s, when General Motors installed the Unimate, a hydraulic arm designed by George Devol and Joseph Engelberger, on its assembly line in Ewing Township, New Jersey. The Unimate performed a single repetitive task — extracting hot metal castings from a die-casting machine — but it demonstrated that programmable machines could operate reliably in harsh industrial environments. Within a decade, automotive manufacturers in the United States, Japan, and Europe had adopted robotic arms for welding, painting, and material handling, launching what would become a global transformation of factory production.

A. Early industrial robots were large, expensive, and inflexible. Each robot was programmed for a specific task and bolted permanently to the factory floor. Reprogramming required specialist engineers and significant downtime, making robots economical only for high-volume production runs. The automotive industry, with its long model cycles and standardised assembly sequences, was the ideal — and for many years the only — significant market for industrial robotics.

B. The 1980s and 1990s brought improvements in sensor technology, computing power, and programming languages that gradually broadened the applicability of robots. Vision systems allowed robots to identify and orient parts, reducing the need for custom fixtures. Force-torque sensors enabled robots to perform delicate assembly operations, such as inserting components into tight-fitting sockets, without damaging them. Offline programming software let engineers simulate robot motions on a computer screen before deploying them on the factory floor, cutting setup times and reducing errors.

C. The most significant recent development has been the emergence of collaborative robots, or cobots. Unlike traditional industrial robots, which operate behind safety cages to protect human workers, cobots are designed to work alongside people in shared workspaces. They are equipped with sensors that detect human proximity and automatically slow or stop to prevent collisions. Cobots are typically smaller, lighter, and far less expensive than conventional robots, with prices starting at around $25,000 — roughly one-tenth the cost of a traditional six-axis industrial arm. Their intuitive programming interfaces, often based on hand-guiding or tablet apps, mean that operators with no robotics background can teach a cobot a new task in hours rather than days.

D. The logistics and warehousing sector has become one of the fastest-growing markets for industrial robotics. Companies such as Amazon deploy fleets of autonomous mobile robots in their fulfilment centres to transport shelving units to human pickers, reducing walking time and increasing order-processing speed. Automated guided vehicles (AGVs) and autonomous mobile robots (AMRs) navigate warehouse floors using lidar, cameras, and machine-learning algorithms, avoiding obstacles and optimising routes in real time. The global market for warehouse robots was valued at approximately $6.1 billion in 2022 and is projected to exceed $18 billion by 2028.

E. In the food and beverage industry, robots handle tasks ranging from packaging and palletising to quality inspection. Hygienic design standards require food-grade robots to be constructed from stainless steel and sealed against water ingress, enabling them to withstand the high-pressure washdowns that are routine in food-processing plants. Vision-guided robots can sort fruit by size, colour, and ripeness at speeds far exceeding those of human workers, reducing waste and improving consistency.

F. The pharmaceutical and electronics industries also rely heavily on robotic automation. Cleanroom robots assemble microchips and medical devices in environments where even microscopic contamination could ruin a product. These robots operate with positional accuracy measured in micrometres and are enclosed in sealed housings that prevent particle shedding. In pharmaceutical manufacturing, robots fill vials, label packages, and inspect tablets for defects at rates of thousands per minute.

G. Despite the rapid growth of industrial robotics, challenges remain. Small and medium-sized enterprises (SMEs) often lack the capital and expertise to integrate robots into their operations, even though cobots have significantly lowered the barrier to entry. Workforce concerns persist: while robots create jobs in programming, maintenance, and systems integration, they displace workers in routine manual tasks, and the transition is not always smooth. Cybersecurity is an emerging risk, as networked robots connected to factory IT systems become potential targets for hackers. Addressing these challenges will be essential if the benefits of robotic automation are to be shared broadly across industries and economies.`,
      questions: [
        { number: 27, type: "matching_information", text: "A description of robots used in environments requiring extreme cleanliness", options: ["A", "B", "C", "D", "E", "F", "G"], correctAnswer: "F", explanation: "Paragraph F discusses cleanroom robots for microchip and medical device assembly." },
        { number: 28, type: "matching_information", text: "Mention of robots that can be programmed by workers without technical training", options: ["A", "B", "C", "D", "E", "F", "G"], correctAnswer: "C", explanation: "Paragraph C discusses cobots with 'intuitive programming interfaces' usable by 'operators with no robotics background.'" },
        { number: 29, type: "matching_information", text: "Reference to the risk of robots being targeted by cyber attacks", options: ["A", "B", "C", "D", "E", "F", "G"], correctAnswer: "G", explanation: "Paragraph G mentions cybersecurity as 'an emerging risk.'" },
        { number: 30, type: "matching_information", text: "An example of robots sorting produce by visual characteristics", options: ["A", "B", "C", "D", "E", "F", "G"], correctAnswer: "E", explanation: "Paragraph E discusses robots sorting 'fruit by size, colour, and ripeness.'" },
        { number: 31, type: "matching_information", text: "The first industrial robot and its initial application", options: ["A", "B", "C", "D", "E", "F", "G"], correctAnswer: "A", explanation: "The introduction and Paragraph A discuss early robots including the Unimate." },
        { number: 32, type: "matching_information", text: "Technology improvements that expanded what robots could do", options: ["A", "B", "C", "D", "E", "F", "G"], correctAnswer: "B", explanation: "Paragraph B discusses sensor technology, computing power, and programming improvements." },
        { number: 33, type: "sentence_completion", text: "The Unimate was installed by General Motors in __(33)__, New Jersey.", correctAnswer: "Ewing Township", explanation: "The passage says 'Ewing Township, New Jersey.'" },
        { number: 34, type: "sentence_completion", text: "Cobots are equipped with sensors that detect human __(34)__.", correctAnswer: "proximity", explanation: "The passage says 'sensors that detect human proximity.'" },
        { number: 35, type: "sentence_completion", text: "Cobots cost around $25,000, roughly one-__(35)__ the cost of traditional industrial arms.", correctAnswer: "tenth", explanation: "The passage says 'roughly one-tenth the cost.'" },
        { number: 36, type: "sentence_completion", text: "Amazon uses autonomous mobile robots to transport __(36)__ units to human pickers.", correctAnswer: "shelving", explanation: "The passage says 'transport shelving units to human pickers.'" },
        { number: 37, type: "sentence_completion", text: "The global market for warehouse robots was valued at approximately $__(37)__ billion in 2022.", correctAnswer: "6.1", explanation: "The passage says 'valued at approximately $6.1 billion in 2022.'" },
        { number: 38, type: "sentence_completion", text: "Food-grade robots must be constructed from __(38)__ steel.", correctAnswer: "stainless", explanation: "The passage says 'constructed from stainless steel.'" },
        { number: 39, type: "sentence_completion", text: "Cleanroom robots operate with positional accuracy measured in __(39)__.", correctAnswer: "micrometres", explanation: "The passage says 'positional accuracy measured in micrometres.'" },
        { number: 40, type: "sentence_completion", text: "Small and medium-sized enterprises often lack the capital and __(40)__ to integrate robots.", correctAnswer: "expertise", explanation: "The passage says 'lack the capital and expertise.'" },
      ],
    },
  ],
};
