import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_47: ReadingTest = {
  id: 47,
  passages: [
    {
      title: "Ecology and Species Adaptation",
      text: `The natural world is in a state of perpetual flux. Species evolve, ecosystems shift, and the delicate balance of biological communities is continually renegotiated in response to environmental pressures. Understanding how species adapt — or fail to adapt — to changing conditions has become one of the most urgent questions in contemporary ecology, particularly as human activities accelerate the pace of environmental change to levels unprecedented in geological history.

Adaptation, in the Darwinian sense, refers to the process by which populations of organisms become better suited to their environments over successive generations through natural selection. Individuals with traits that confer a survival or reproductive advantage in a given environment are more likely to pass those traits to their offspring. Over time, the frequency of advantageous traits increases within the population. This process operates on timescales that vary enormously — from a few generations in rapidly reproducing organisms like bacteria to millions of years in large, slowly reproducing species like elephants.

One of the most well-documented examples of rapid adaptation is the evolution of industrial melanism in the peppered moth (Biston betularia) in nineteenth-century England. Before industrialisation, the pale-coloured form of the moth was predominant, as it was well camouflaged against lichen-covered tree bark. As industrial pollution darkened tree trunks with soot, the darker melanic form gained a survival advantage and became more common. When pollution controls were introduced in the twentieth century and trees lightened again, the pale form recovered its dominance. This elegant example demonstrates that natural selection can operate on remarkably short timescales when selection pressures are strong.

However, not all species can adapt quickly enough to survive rapid environmental change. The concept of "evolutionary rescue" — where adaptation occurs fast enough to prevent population extinction — depends on several factors: the size of the population, the amount of genetic variation available, the strength and speed of the environmental change, and the generation time of the organism. Small populations with limited genetic diversity are particularly vulnerable, as they lack the raw material for natural selection to act upon.

Phenotypic plasticity offers another mechanism by which organisms can respond to environmental variation without genetic change. Plasticity refers to the ability of a single genotype to produce different phenotypes — different physical or behavioural traits — depending on environmental conditions. For example, many plant species can adjust their leaf size, root depth, and flowering time in response to temperature and moisture levels. Some fish can alter their body shape depending on the presence of predators. Arctic animals like the snowshoe hare change fur colour seasonally, transitioning from brown in summer to white in winter for camouflage.

Behavioural flexibility represents yet another adaptive strategy. Many bird species have shifted their migration timing in response to earlier springs caused by climate change. Some urban animals — coyotes, foxes, raccoons — have modified their activity patterns to avoid human contact, becoming more nocturnal in cities than their rural counterparts. Coral reef fish have been observed altering their habitat preferences as water temperatures rise, moving to deeper, cooler waters where possible.

The concept of "ecological traps" highlights the dangers of maladaptation. An ecological trap occurs when environmental changes cause an organism to prefer a habitat that is actually harmful. For example, sea turtles have evolved to nest on dark, quiet beaches. Coastal development that introduces artificial lighting can attract hatchlings away from the ocean toward dangerous roads and buildings, effectively turning a historically safe nesting site into a death trap.

Scientists are increasingly studying "assisted migration" — the deliberate relocation of species to habitats where they are more likely to survive under future climate conditions. This controversial practice raises complex ethical and ecological questions. Moving a species to a new environment could help it survive, but it could also introduce it as an invasive competitor that harms native species. The debate over assisted migration reflects a broader tension in conservation biology between preserving existing ecosystems and actively managing nature in the face of irreversible change.

Ultimately, the capacity of species to adapt will determine the future composition of Earth's ecosystems. While some organisms possess the genetic diversity, plasticity, and behavioural flexibility to adjust to a warming world, others — particularly specialists with narrow ecological requirements — face an uncertain future. The challenge for conservation science is to identify which species are most at risk and to develop strategies that maximise their chances of survival in a rapidly changing world.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "In Darwinian adaptation, which individuals are most likely to pass on their traits?", options: ["A. The largest individuals", "B. Those with traits that aid survival or reproduction", "C. Those that migrate the furthest", "D. The oldest members of a population"], correctAnswer: "B", explanation: "The passage states individuals with traits conferring 'a survival or reproductive advantage' are more likely to pass traits on." },
        { number: 2, type: "multiple_choice", text: "The peppered moth example demonstrates that natural selection", options: ["A. only works over millions of years", "B. cannot reverse previous changes", "C. can operate on short timescales", "D. is limited to tropical species"], correctAnswer: "C", explanation: "The passage says this example 'demonstrates that natural selection can operate on remarkably short timescales.'" },
        { number: 3, type: "multiple_choice", text: "Which factor does NOT affect evolutionary rescue?", options: ["A. Population size", "B. Genetic diversity", "C. Generation time", "D. Average lifespan of individual organisms"], correctAnswer: "D", explanation: "The passage lists population size, genetic variation, environmental change speed, and generation time — not individual lifespan." },
        { number: 4, type: "multiple_choice", text: "What is an 'ecological trap'?", options: ["A. A device used to capture invasive species", "B. A habitat that appears attractive but is harmful", "C. A conservation area with strict access controls", "D. A genetic mutation that reduces fitness"], correctAnswer: "B", explanation: "The passage defines it as when organisms 'prefer a habitat that is actually harmful.'" },
        { number: 5, type: "true_false_not_given", text: "Industrial melanism in peppered moths occurred due to changes in tree bark colour.", correctAnswer: "TRUE", explanation: "The passage explains pollution 'darkened tree trunks with soot,' giving the darker moth form an advantage." },
        { number: 6, type: "true_false_not_given", text: "All species can adapt quickly enough to survive rapid environmental change.", correctAnswer: "FALSE", explanation: "The passage states 'not all species can adapt quickly enough to survive rapid environmental change.'" },
        { number: 7, type: "true_false_not_given", text: "Phenotypic plasticity involves permanent genetic mutations.", correctAnswer: "FALSE", explanation: "The passage defines plasticity as responding 'without genetic change.'" },
        { number: 8, type: "true_false_not_given", text: "Assisted migration has been widely adopted by all conservation organisations.", correctAnswer: "NOT GIVEN", explanation: "The passage describes it as 'controversial' but does not state whether it has been widely adopted." },
        { number: 9, type: "true_false_not_given", text: "Coyotes in urban areas tend to be more nocturnal than those in rural areas.", correctAnswer: "TRUE", explanation: "The passage states urban animals are 'becoming more nocturnal in cities than their rural counterparts.'" },
        { number: 10, type: "true_false_not_given", text: "The snowshoe hare changes fur colour to attract mates.", correctAnswer: "FALSE", explanation: "The passage says the hare changes colour 'for camouflage,' not to attract mates." },
        { number: 11, type: "true_false_not_given", text: "Coral reef fish always move to shallower waters when temperatures rise.", correctAnswer: "FALSE", explanation: "The passage says they move 'to deeper, cooler waters.'" },
        { number: 12, type: "true_false_not_given", text: "Elephants adapt more quickly than bacteria.", correctAnswer: "FALSE", explanation: "The passage implies bacteria reproduce rapidly and adapt on shorter timescales than elephants." },
        { number: 13, type: "true_false_not_given", text: "Specialist species with narrow ecological requirements face greater risk.", correctAnswer: "TRUE", explanation: "The passage says 'specialists with narrow ecological requirements — face an uncertain future.'" }
      ]
    },
    {
      title: "History of Clocks and Time",
      text: `A. The measurement of time is so fundamental to human civilisation that it is easy to overlook just how recent precision timekeeping actually is. For most of human history, time was measured approximately — by the position of the sun, the length of shadows, or the rhythm of natural events like tides and seasons. The development of mechanical clocks in medieval Europe marked a turning point, but it was not until the twentieth century that timekeeping achieved the extraordinary accuracy we now take for granted.

B. The earliest known timekeeping devices were sundials, used in ancient Egypt as far back as 1500 BCE. These instruments tracked the sun's movement across the sky, casting a shadow on a calibrated surface to indicate the hour. While effective during daylight, sundials were obviously useless at night and on cloudy days. Water clocks, or clepsydrae, addressed this limitation by measuring time through the regulated flow of water from one vessel to another. The ancient Greeks refined these devices, and elaborate water clocks were used in Roman courts to time speeches.

C. The invention of the mechanical clock in thirteenth-century Europe represented a revolutionary advance. The earliest mechanical clocks used a verge escapement mechanism — a device that regulated the release of energy from a falling weight, converting it into a controlled oscillation. These clocks were installed in church towers and monasteries, where they marked the hours for prayer. They were large, expensive, and accurate only to within about fifteen minutes per day, but they fundamentally changed the relationship between human activity and the passage of time.

D. The introduction of the pendulum clock by Dutch scientist Christiaan Huygens in 1656 dramatically improved timekeeping accuracy. Galileo Galilei had observed the regularity of a swinging pendulum decades earlier, but it was Huygens who successfully incorporated this principle into a working clock. Pendulum clocks could maintain accuracy to within about ten seconds per day — a remarkable improvement that enabled more precise scientific measurement and navigation.

E. Maritime navigation provided a powerful incentive for further improvements. Determining longitude at sea required an accurate clock that could withstand the motion of a ship — a challenge that pendulum clocks could not meet. The British government offered a prize of £20,000 in 1714 for a practical solution. John Harrison, a self-taught Yorkshire carpenter, devoted decades to developing a series of marine chronometers. His H4 chronometer, completed in 1761, lost only five seconds over an 81-day voyage to Jamaica, effectively solving the longitude problem.

F. The nineteenth century brought the standardisation of time itself. Before the railway age, each town kept its own local time based on the position of the sun. This created chaos for train schedules, as departure and arrival times varied from station to station. In 1880, Britain adopted Greenwich Mean Time as the national standard, and by 1884, an international conference in Washington established a system of global time zones based on the Greenwich meridian.

G. The twentieth century saw the development of quartz and atomic clocks that pushed accuracy to levels unimaginable to earlier generations. Quartz clocks, introduced in the 1920s, used the vibration of a quartz crystal to regulate timekeeping, achieving accuracy to within a few seconds per year. Atomic clocks, first developed in 1955, measure time by the oscillation frequency of atoms — typically caesium-133, which vibrates exactly 9,192,631,770 times per second. Modern caesium fountain clocks are accurate to within one second over 300 million years.

H. Today, precise timekeeping underpins much of modern technology. Global Positioning System (GPS) satellites carry atomic clocks whose signals enable location accuracy to within a few metres. Financial markets depend on synchronised clocks for time-stamping transactions. Telecommunications networks require precise timing to coordinate data transmission. The scientific definition of the second — based on caesium atomic transitions rather than astronomical observations — reflects the extent to which human timekeeping has moved beyond its origins in watching the sun cross the sky.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Paragraph B", options: ["i. Solving the longitude challenge", "ii. Early timekeeping with sun and water", "iii. The pendulum revolution", "iv. Atomic precision in the modern age", "v. Mechanical clocks transform society", "vi. Railways force time standardisation", "vii. Time in the digital world", "viii. The first mechanical timekeepers"], correctAnswer: "ii", explanation: "Paragraph B discusses sundials and water clocks." },
        { number: 15, type: "matching_headings", text: "Paragraph D", options: ["i. Solving the longitude challenge", "ii. Early timekeeping with sun and water", "iii. The pendulum revolution", "iv. Atomic precision in the modern age", "v. Mechanical clocks transform society", "vi. Railways force time standardisation", "vii. Time in the digital world", "viii. The first mechanical timekeepers"], correctAnswer: "iii", explanation: "Paragraph D covers Huygens' pendulum clock." },
        { number: 16, type: "matching_headings", text: "Paragraph F", options: ["i. Solving the longitude challenge", "ii. Early timekeeping with sun and water", "iii. The pendulum revolution", "iv. Atomic precision in the modern age", "v. Mechanical clocks transform society", "vi. Railways force time standardisation", "vii. Time in the digital world", "viii. The first mechanical timekeepers"], correctAnswer: "vi", explanation: "Paragraph F discusses how railways led to time standardisation." },
        { number: 17, type: "matching_headings", text: "Paragraph G", options: ["i. Solving the longitude challenge", "ii. Early timekeeping with sun and water", "iii. The pendulum revolution", "iv. Atomic precision in the modern age", "v. Mechanical clocks transform society", "vi. Railways force time standardisation", "vii. Time in the digital world", "viii. The first mechanical timekeepers"], correctAnswer: "iv", explanation: "Paragraph G describes quartz and atomic clocks." },
        { number: 18, type: "summary_completion", text: "Sundials were used in ancient Egypt from around ________ BCE.", correctAnswer: "1500", explanation: "The passage says sundials were used 'as far back as 1500 BCE.'" },
        { number: 19, type: "summary_completion", text: "Early mechanical clocks used a ________ escapement mechanism.", correctAnswer: "verge", explanation: "The passage mentions 'a verge escapement mechanism.'" },
        { number: 20, type: "summary_completion", text: "Huygens' pendulum clock maintained accuracy to within about ten ________ per day.", correctAnswer: "seconds", explanation: "The passage states 'accuracy to within about ten seconds per day.'" },
        { number: 21, type: "summary_completion", text: "Harrison's H4 chronometer lost only ________ seconds over an 81-day voyage.", correctAnswer: "five", explanation: "The passage says it 'lost only five seconds over an 81-day voyage.'" },
        { number: 22, type: "short_answer", text: "What prize did the British government offer for solving the longitude problem?", correctAnswer: "£20,000", explanation: "The passage states 'a prize of £20,000.'" },
        { number: 23, type: "short_answer", text: "In what year did Britain adopt Greenwich Mean Time?", correctAnswer: "1880", explanation: "The passage says 'In 1880, Britain adopted Greenwich Mean Time.'" },
        { number: 24, type: "short_answer", text: "Which atom is typically used in atomic clocks?", correctAnswer: "caesium-133", explanation: "The passage mentions 'caesium-133, which vibrates exactly 9,192,631,770 times per second.'" },
        { number: 25, type: "short_answer", text: "How accurate are modern caesium fountain clocks?", correctAnswer: "one second over 300 million years", explanation: "The passage says they are 'accurate to within one second over 300 million years.'" },
        { number: 26, type: "short_answer", text: "What technology uses atomic clocks for location accuracy?", correctAnswer: "GPS", explanation: "The passage says 'Global Positioning System (GPS) satellites carry atomic clocks.'" }
      ]
    },
    {
      title: "Society and Technology",
      text: `A. The relationship between society and technology has never been simple. Each major technological advance — from the printing press to the smartphone — has triggered waves of enthusiasm, anxiety, and ultimately adaptation. The current digital revolution, characterised by artificial intelligence, social media, and pervasive connectivity, is no exception. What distinguishes this era is the speed and scale of change: technologies that once took decades to reach mass adoption now achieve it in years or even months.

B. The printing press, developed by Johannes Gutenberg around 1440, provides an instructive historical parallel. Before movable type, books were copied by hand — a laborious process that limited literacy to a small clerical and aristocratic elite. Gutenberg's invention democratised knowledge by making books affordable and widely available. Within fifty years of its introduction, an estimated twenty million volumes had been printed in Europe. The resulting spread of ideas contributed to the Protestant Reformation, the Scientific Revolution, and the eventual emergence of democratic governance.

C. Yet the printing press also generated profound anxieties. Religious authorities feared the uncontrolled dissemination of heretical ideas. Political leaders worried about the power of pamphlets to incite rebellion. Scholars lamented the decline of manuscript culture and the loss of quality control that came with mass production. These concerns — about misinformation, social disruption, and the erosion of established authority — echo remarkably in contemporary debates about social media and artificial intelligence.

D. The industrial revolution of the eighteenth and nineteenth centuries intensified the tension between technological progress and social disruption. Mechanised factories displaced skilled artisans, urbanisation strained housing and sanitation systems, and child labour became endemic in mining and manufacturing. The Luddite movement of 1811–1816, in which textile workers destroyed machinery they believed threatened their livelihoods, has become a lasting symbol of resistance to technological change. Yet the industrial revolution also generated unprecedented wealth, raised living standards over time, and created entirely new categories of employment.

E. The twentieth century accelerated this pattern. The automobile transformed urban planning, created suburban lifestyles, and generated millions of jobs — while also contributing to air pollution, traffic fatalities, and oil dependency. Television reshaped politics, entertainment, and family life. Nuclear technology offered both clean energy and existential threat. In each case, societies eventually developed regulatory frameworks, cultural norms, and institutional structures to manage the consequences of innovation — though often only after considerable disruption and debate.

F. The digital revolution presents challenges of a qualitatively different order. Social media platforms, designed to maximise engagement through algorithmic content curation, have been linked to political polarisation, mental health problems among young people, and the rapid spread of misinformation. The business model of surveillance capitalism — in which user data is harvested and monetised for targeted advertising — raises fundamental questions about privacy and autonomy that existing legal frameworks struggle to address.

G. Artificial intelligence introduces additional complexities. Machine learning systems now make decisions affecting credit applications, criminal sentencing, medical diagnoses, and employment screening. These systems can perpetuate and amplify existing biases in the data they are trained on, raising concerns about fairness and accountability. The prospect of artificial general intelligence — machines capable of performing any intellectual task that humans can — has generated intense debate among technologists, philosophers, and policymakers about existential risk.

H. Historians of technology caution against both uncritical techno-optimism and reflexive techno-pessimism. The printing press eventually contributed to human flourishing despite legitimate early concerns. The automobile reshaped civilisation in ways both beneficial and harmful. The lesson of history is not that technology is inherently good or bad, but that its consequences depend on the social, political, and economic contexts in which it is deployed — and on the choices societies make about how to govern it.

I. As digital technologies continue to reshape economies, politics, and personal relationships, the need for thoughtful governance has never been greater. This requires not only technical expertise but also ethical reflection, democratic deliberation, and a willingness to learn from the successes and failures of past technological transitions. The societies that navigate this transformation most successfully will be those that treat technology not as an autonomous force but as a tool whose effects are ultimately shaped by human decisions.`,
      questions: [
        { number: 27, type: "matching_information", text: "A reference to the destruction of machines by workers", options: ["A", "B", "C", "D", "E", "F", "G", "H", "I"], correctAnswer: "D", explanation: "Paragraph D describes the Luddite movement where textile workers destroyed machinery." },
        { number: 28, type: "matching_information", text: "Concerns about AI systems perpetuating bias", options: ["A", "B", "C", "D", "E", "F", "G", "H", "I"], correctAnswer: "G", explanation: "Paragraph G discusses how ML systems 'can perpetuate and amplify existing biases.'" },
        { number: 29, type: "matching_information", text: "A comparison between early printing press concerns and modern debates", options: ["A", "B", "C", "D", "E", "F", "G", "H", "I"], correctAnswer: "C", explanation: "Paragraph C draws parallels between printing press anxieties and modern social media debates." },
        { number: 30, type: "matching_information", text: "The concept of surveillance capitalism", options: ["A", "B", "C", "D", "E", "F", "G", "H", "I"], correctAnswer: "F", explanation: "Paragraph F introduces 'surveillance capitalism' and its implications." },
        { number: 31, type: "multiple_choice", text: "According to the passage, Gutenberg's press resulted in approximately how many volumes being printed within fifty years?", options: ["A. Two million", "B. Ten million", "C. Twenty million", "D. Fifty million"], correctAnswer: "C", explanation: "The passage states 'an estimated twenty million volumes had been printed in Europe.'" },
        { number: 32, type: "multiple_choice", text: "The Luddite movement took place during", options: ["A. 1711–1716", "B. 1811–1816", "C. 1911–1916", "D. 1840–1850"], correctAnswer: "B", explanation: "The passage says 'The Luddite movement of 1811–1816.'" },
        { number: 33, type: "multiple_choice", text: "Historians of technology recommend", options: ["A. embracing all new technology without question", "B. rejecting technology that causes disruption", "C. avoiding both extreme optimism and pessimism", "D. leaving governance to technology companies"], correctAnswer: "C", explanation: "The passage says historians 'caution against both uncritical techno-optimism and reflexive techno-pessimism.'" },
        { number: 34, type: "multiple_choice", text: "What distinguishes the current digital revolution from past technological changes?", options: ["A. It has no negative consequences", "B. It affects fewer people", "C. Its speed and scale of adoption", "D. It is entirely government-controlled"], correctAnswer: "C", explanation: "The passage says 'the speed and scale of change' distinguishes this era." },
        { number: 35, type: "sentence_completion", text: "Before movable type, books were copied by ________.", correctAnswer: "hand", explanation: "The passage says 'books were copied by hand.'" },
        { number: 36, type: "sentence_completion", text: "The automobile contributed to air pollution, traffic fatalities, and ________ dependency.", correctAnswer: "oil", explanation: "The passage mentions 'oil dependency.'" },
        { number: 37, type: "sentence_completion", text: "Machine learning systems make decisions affecting credit applications, criminal sentencing, ________, and employment screening.", correctAnswer: "medical diagnoses", explanation: "The passage lists 'medical diagnoses' as one of the areas." },
        { number: 38, type: "sentence_completion", text: "Social media platforms are designed to maximise engagement through ________ content curation.", correctAnswer: "algorithmic", explanation: "The passage says 'algorithmic content curation.'" },
        { number: 39, type: "sentence_completion", text: "The printing press contributed to the Protestant Reformation, the Scientific Revolution, and ________ governance.", correctAnswer: "democratic", explanation: "The passage mentions 'the eventual emergence of democratic governance.'" },
        { number: 40, type: "sentence_completion", text: "Societies that succeed will treat technology as a ________ shaped by human decisions.", correctAnswer: "tool", explanation: "The passage says 'a tool whose effects are ultimately shaped by human decisions.'" }
      ]
    }
  ]
};
