import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_42: ReadingTest = {
  id: 42,
  passages: [
    {
      title: "Ancient Trade",
      text: `Trade has been a fundamental driver of human civilisation since the Neolithic period. As early as 10,000 BCE, communities that produced surplus grain, livestock, or craft goods began exchanging them with neighbouring groups for resources they lacked, such as obsidian for toolmaking, shells for ornamentation, or salt for food preservation. These early exchanges, conducted through barter rather than currency, established networks of economic interdependence that would grow increasingly complex over millennia.

The Bronze Age, beginning around 3300 BCE, dramatically expanded the scale and reach of ancient trade. The production of bronze required tin and copper, metals that rarely occurred together in the same region. Tin, in particular, was scarce: significant deposits existed in Cornwall (England), the Iberian Peninsula, Central Asia, and Southeast Asia, while demand was widespread across the Mediterranean, the Near East, and the Indus Valley. The need to obtain tin drove the creation of long-distance trade routes that connected civilisations separated by thousands of kilometres.

The ancient Phoenicians, based in the coastal cities of present-day Lebanon, became the Mediterranean's most accomplished maritime traders. From roughly 1500 to 300 BCE, Phoenician ships carried cedar wood, purple dye extracted from murex snails, glassware, and metalwork to ports across the Mediterranean and beyond. They established trading colonies in North Africa, Sicily, Sardinia, and the Iberian Peninsula; Carthage, founded around 814 BCE, grew into one of the ancient world's wealthiest cities. Phoenician merchants are credited with transmitting the alphabet to Greece, an innovation that would transform communication and record-keeping across the Western world.

In the eastern Mediterranean and the Near East, the Silk Road — a network of overland trade routes linking China to the Mediterranean — began to take shape during the second century BCE, following the diplomatic missions of Zhang Qian on behalf of the Chinese Han dynasty. Although silk was the most famous commodity, the Silk Road carried an astonishing variety of goods: spices, precious stones, glass, paper, gunpowder, and horses moved westward, while gold, silver, wool, and linen travelled eastward. Perhaps more importantly, the Silk Road served as a conduit for ideas, religions, technologies, and diseases: Buddhism spread from India to Central Asia, China, and Japan along these routes, and the Black Death may have reached Europe via Silk Road trade networks in the fourteenth century.

Maritime trade in the Indian Ocean was equally significant. Arab, Indian, Malay, and Chinese merchants exploited the predictable pattern of monsoon winds — blowing southwestward in summer and northeastward in winter — to sail between East Africa, the Arabian Peninsula, India, Southeast Asia, and China. Port cities such as Kilwa, Calicut, Malacca, and Guangzhou flourished as nodes in a trading network that exchanged gold, ivory, and enslaved people from Africa; spices, cotton textiles, and gemstones from India; silk, porcelain, and tea from China; and aromatic resins and sandalwood from Southeast Asia.

The introduction of coined money, first in Lydia (western Turkey) around 600 BCE and subsequently in Greece, Persia, and India, revolutionised trade by providing a portable, standardised medium of exchange. Coins simplified transactions, enabled price comparison, and facilitated the accumulation of capital. By the Roman period, a single currency — the denarius — circulated across an empire stretching from Britain to Mesopotamia, underpinning a commercial system of remarkable sophistication that included credit arrangements, maritime insurance, and joint-stock trading ventures.

Ancient trade did more than move goods: it wove together the economies, cultures, and destinies of distant peoples. The networks established in antiquity laid the foundations for the globalised economy of the modern world, and many of the trade routes pioneered thousands of years ago remain vital arteries of international commerce today.`,
      questions: [
        { number: 1, type: "true_false_not_given", text: "The earliest forms of trade used currency rather than barter.", correctAnswer: "FALSE", explanation: "The passage says early exchanges were 'conducted through barter rather than currency.'" },
        { number: 2, type: "true_false_not_given", text: "Bronze production required tin and copper.", correctAnswer: "TRUE", explanation: "The passage says 'The production of bronze required tin and copper.'" },
        { number: 3, type: "true_false_not_given", text: "The Phoenicians were based in present-day Greece.", correctAnswer: "FALSE", explanation: "The passage says they were 'based in the coastal cities of present-day Lebanon.'" },
        { number: 4, type: "true_false_not_given", text: "Carthage was founded around 814 BCE.", correctAnswer: "TRUE", explanation: "The passage says 'Carthage, founded around 814 BCE.'" },
        { number: 5, type: "true_false_not_given", text: "The Silk Road was primarily a single road connecting two cities.", correctAnswer: "FALSE", explanation: "The passage describes it as 'a network of overland trade routes.'" },
        { number: 6, type: "true_false_not_given", text: "Zhang Qian represented the Tang dynasty.", correctAnswer: "FALSE", explanation: "The passage says he acted 'on behalf of the Chinese Han dynasty.'" },
        { number: 7, type: "true_false_not_given", text: "Monsoon winds in the Indian Ocean blow in the same direction year-round.", correctAnswer: "FALSE", explanation: "The passage describes monsoon winds as 'blowing southwestward in summer and northeastward in winter.'" },
        { number: 8, type: "sentence_completion", text: "The Phoenicians extracted purple dye from __(8)__ snails.", correctAnswer: "murex", explanation: "The passage says 'purple dye extracted from murex snails.'" },
        { number: 9, type: "sentence_completion", text: "Phoenician merchants are credited with transmitting the __(9)__ to Greece.", correctAnswer: "alphabet", explanation: "The passage says 'transmitting the alphabet to Greece.'" },
        { number: 10, type: "sentence_completion", text: "The Black Death may have reached Europe via __(10)__ trade networks.", correctAnswer: "Silk Road", explanation: "The passage says 'via Silk Road trade networks.'" },
        { number: 11, type: "sentence_completion", text: "Coined money was first introduced in __(11)__ around 600 BCE.", correctAnswer: "Lydia", explanation: "The passage says 'first in Lydia (western Turkey) around 600 BCE.'" },
        { number: 12, type: "sentence_completion", text: "The Roman __(12)__ circulated across an empire from Britain to Mesopotamia.", correctAnswer: "denarius", explanation: "The passage says 'a single currency — the denarius.'" },
        { number: 13, type: "sentence_completion", text: "Obsidian was traded for use in __(13)__.", correctAnswer: "toolmaking", explanation: "The passage says 'obsidian for toolmaking.'" },
      ],
    },
    {
      title: "Urban Transport",
      text: `A. The way people move through cities has always shaped the physical form and social character of urban life. In the ancient world, most cities were compact enough to traverse on foot, and streets were designed primarily for pedestrians, pack animals, and carts. Rome, at the height of its empire, restricted wheeled vehicles during daylight hours to reduce congestion — an early form of traffic management that would be echoed in modern pedestrianisation schemes two millennia later.

B. The nineteenth century brought the first mass-transit systems. Horse-drawn omnibuses, introduced in Paris in 1828 and London in 1829, could carry twenty or more passengers along fixed routes for a fare affordable to the middle class. Horse-drawn trams, running on iron rails set into the street, followed in the 1830s and offered a smoother, faster ride. By mid-century, the growth of railway networks allowed the development of suburban commuter services, enabling middle-class workers to live outside the city centre for the first time and commute by train.

C. The London Underground, opened in 1863, was the world's first urban metro system. Initially powered by steam locomotives — which filled the tunnels with smoke and made conditions unpleasant for passengers — the system converted to electric traction in the early twentieth century. Other cities followed London's lead: Budapest opened the first electrically powered metro line in continental Europe in 1896, and by 1940, metros were operating in cities including Paris, New York, Berlin, Tokyo, and Moscow. Underground rail systems transformed urban geography by making it possible to live far from the city centre while commuting quickly and reliably.

D. The automobile reshaped cities more dramatically than any previous transport technology. Mass production, pioneered by Henry Ford with the Model T in 1908, made cars affordable to ordinary families, and car ownership grew explosively throughout the twentieth century. Cities — particularly in North America and Australia — were redesigned around the car: wide highways, sprawling suburbs, shopping centres surrounded by parking lots, and drive-through services became defining features of the urban landscape. The environmental and social costs of car dependency, however, have become increasingly apparent: traffic congestion, air pollution, road accidents, physical inactivity, and the fragmentation of communities by multi-lane highways.

E. In response, many cities have begun to prioritise public transport, cycling, and walking. Bus Rapid Transit (BRT) systems, pioneered by Curitiba, Brazil, in 1974, use dedicated lanes, pre-paid boarding, and frequent services to achieve metro-like performance at a fraction of the cost. Bogotá's TransMilenio, one of the world's largest BRT systems, carries more than 2.4 million passengers per day. Light rail and tram networks have been revived in cities across Europe and North America, offering electric, low-emission transport along busy corridors.

F. Cycling infrastructure has expanded rapidly. The Netherlands and Denmark have invested in segregated cycle lanes, bicycle parking, and traffic-calming measures for decades, and cycling accounts for roughly twenty-seven per cent of all trips in the Netherlands. Cities such as Paris, Barcelona, and Bogotá have accelerated the construction of protected cycle lanes since the COVID-19 pandemic, which triggered a global surge in cycling demand. Bike-sharing schemes, first introduced in Lyon in 2005, are now available in more than 1,000 cities worldwide.

G. Emerging technologies promise further transformation. Electric buses are replacing diesel fleets in cities from Shenzhen, which electrified its entire bus fleet of 16,000 vehicles by 2018, to London and Santiago. Autonomous vehicles, though still in the testing phase, could eventually reduce traffic accidents, optimise traffic flow, and provide mobility for people unable to drive. Mobility-as-a-Service (MaaS) platforms integrate public transport, ride-hailing, car-sharing, and bike-sharing into a single digital interface, enabling seamless multi-modal journeys.

H. The challenge for urban planners is to design transport systems that are efficient, equitable, and sustainable. Cities that invest in high-quality public transport, safe cycling and walking infrastructure, and smart technology will be better positioned to reduce emissions, improve public health, and create liveable urban environments for the billions of people who will call cities home in the coming decades.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Section A", options: ["I. The impact of mass car ownership", "II. Walking cities of the ancient world", "III. The rise of cycling in cities", "IV. The birth of underground railways", "V. New technologies shaping future transport", "VI. Early public transport systems", "VII. Modern bus and tram solutions", "VIII. Planning for sustainable urban mobility"], correctAnswer: "II", explanation: "Section A discusses ancient cities designed for pedestrians." },
        { number: 15, type: "matching_headings", text: "Section B", options: ["I. The impact of mass car ownership", "II. Walking cities of the ancient world", "III. The rise of cycling in cities", "IV. The birth of underground railways", "V. New technologies shaping future transport", "VI. Early public transport systems", "VII. Modern bus and tram solutions", "VIII. Planning for sustainable urban mobility"], correctAnswer: "VI", explanation: "Section B discusses horse-drawn omnibuses and trams." },
        { number: 16, type: "matching_headings", text: "Section C", options: ["I. The impact of mass car ownership", "II. Walking cities of the ancient world", "III. The rise of cycling in cities", "IV. The birth of underground railways", "V. New technologies shaping future transport", "VI. Early public transport systems", "VII. Modern bus and tram solutions", "VIII. Planning for sustainable urban mobility"], correctAnswer: "IV", explanation: "Section C discusses the London Underground and subsequent metro systems." },
        { number: 17, type: "matching_headings", text: "Section D", options: ["I. The impact of mass car ownership", "II. Walking cities of the ancient world", "III. The rise of cycling in cities", "IV. The birth of underground railways", "V. New technologies shaping future transport", "VI. Early public transport systems", "VII. Modern bus and tram solutions", "VIII. Planning for sustainable urban mobility"], correctAnswer: "I", explanation: "Section D discusses the automobile's impact on cities." },
        { number: 18, type: "matching_headings", text: "Section E", options: ["I. The impact of mass car ownership", "II. Walking cities of the ancient world", "III. The rise of cycling in cities", "IV. The birth of underground railways", "V. New technologies shaping future transport", "VI. Early public transport systems", "VII. Modern bus and tram solutions", "VIII. Planning for sustainable urban mobility"], correctAnswer: "VII", explanation: "Section E discusses BRT and light rail systems." },
        { number: 19, type: "matching_headings", text: "Section F", options: ["I. The impact of mass car ownership", "II. Walking cities of the ancient world", "III. The rise of cycling in cities", "IV. The birth of underground railways", "V. New technologies shaping future transport", "VI. Early public transport systems", "VII. Modern bus and tram solutions", "VIII. Planning for sustainable urban mobility"], correctAnswer: "III", explanation: "Section F discusses cycling infrastructure expansion." },
        { number: 20, type: "summary_completion", text: "Horse-drawn omnibuses were introduced in Paris in __(20)__.", correctAnswer: "1828", explanation: "The passage says 'introduced in Paris in 1828.'" },
        { number: 21, type: "summary_completion", text: "The London Underground opened in __(21)__.", correctAnswer: "1863", explanation: "The passage says 'opened in 1863.'" },
        { number: 22, type: "summary_completion", text: "Henry Ford pioneered mass production with the __(22)__ in 1908.", correctAnswer: "Model T", explanation: "The passage says 'the Model T in 1908.'" },
        { number: 23, type: "summary_completion", text: "Bogotá's TransMilenio carries more than __(23)__ million passengers per day.", correctAnswer: "2.4", explanation: "The passage says 'more than 2.4 million passengers per day.'" },
        { number: 24, type: "summary_completion", text: "Cycling accounts for roughly __(24)__ per cent of all trips in the Netherlands.", correctAnswer: "twenty-seven", explanation: "The passage says 'roughly twenty-seven per cent.'" },
        { number: 25, type: "summary_completion", text: "Shenzhen electrified its entire bus fleet of __(25)__ vehicles by 2018.", correctAnswer: "16,000", explanation: "The passage says '16,000 vehicles by 2018.'" },
        { number: 26, type: "summary_completion", text: "Bike-sharing schemes are now available in more than __(26)__ cities worldwide.", correctAnswer: "1,000", explanation: "The passage says 'more than 1,000 cities worldwide.'" },
      ],
    },
    {
      title: "3D Printing in Industry",
      text: `Three-dimensional printing, also known as additive manufacturing, builds physical objects layer by layer from digital designs. Unlike traditional subtractive manufacturing, which removes material from a solid block through cutting, drilling, or milling, additive manufacturing deposits material only where it is needed, minimising waste and enabling the creation of complex geometries that would be impossible or prohibitively expensive to produce by conventional methods.

A. The technology originated in the 1980s with stereolithography (SLA), developed by Charles Hull in 1984. SLA uses an ultraviolet laser to cure liquid photopolymer resin into solid layers, building up a three-dimensional object from the bottom up. Hull patented the process and co-founded 3D Systems, one of the first companies to commercialise 3D printing. Other additive processes soon followed: selective laser sintering (SLS), which fuses powdered materials using a laser, was patented in 1989, and fused deposition modelling (FDM), which extrudes heated thermoplastic filament, was commercialised in the early 1990s by Stratasys.

B. For its first two decades, 3D printing was used primarily for rapid prototyping — producing physical models of new designs quickly and cheaply so that engineers could evaluate form, fit, and function before committing to expensive tooling. The technology accelerated product-development cycles: a prototype that might have taken weeks to machine from metal could be 3D-printed in hours from plastic, allowing faster iteration and more design experimentation.

C. The advent of metal 3D printing transformed the technology from a prototyping tool into a viable manufacturing method. Techniques such as direct metal laser sintering (DMLS) and electron beam melting (EBM) can produce fully dense metal parts from powdered titanium, aluminium, stainless steel, and nickel superalloys. The aerospace industry was an early adopter: GE Aviation 3D-prints fuel nozzles for its LEAP jet engine, consolidating what was previously an assembly of twenty separate parts into a single component that is twenty-five per cent lighter and five times more durable.

D. The medical sector has embraced 3D printing for patient-specific devices. Surgeons now routinely use 3D-printed anatomical models, generated from CT or MRI scans, to plan complex operations. Custom titanium implants — hip joints, cranial plates, spinal cages — are 3D-printed to match a patient's unique anatomy, improving surgical outcomes and reducing recovery times. Dental aligners, hearing aids, and prosthetic limbs are increasingly produced using additive manufacturing, which can deliver individually customised products at mass-production speed.

E. In construction, large-scale 3D printers are beginning to build houses and infrastructure. ICON, a Texas-based company, uses a robotic extrusion system to print concrete walls for single-storey homes in as little as 48 hours. The technology has been deployed in social-housing projects in Mexico and the United States, offering a potential solution to housing shortages. Dubai has announced that by 2030, twenty-five per cent of new buildings in the city must be 3D-printed. Researchers are also exploring the use of lunar and Martian regolith as printing material for extraterrestrial habitats.

F. Supply-chain considerations are driving adoption in other sectors. Because 3D printing produces parts on demand from digital files, it can eliminate the need for large inventories of spare parts. The military, for example, is exploring the deployment of mobile 3D-printing units that could manufacture replacement components in the field, reducing logistical dependence on distant factories. Similarly, remote industrial sites — offshore oil platforms, mining operations, polar research stations — could use 3D printers to produce critical parts locally, avoiding weeks-long waits for shipments.

G. Despite its growing capabilities, 3D printing faces limitations. Production speed remains slower than conventional mass-manufacturing methods for high volumes; injection moulding, for example, can produce thousands of identical plastic parts per hour, a rate no current 3D printer can match. Material costs are generally higher, and the range of printable materials, though expanding, is still narrower than that available for conventional processes. Quality assurance is another challenge: ensuring that every 3D-printed part meets exacting specifications requires advanced inspection techniques, including CT scanning and machine-learning-based defect detection.

H. The future of 3D printing lies in the convergence of additive manufacturing with artificial intelligence, robotics, and advanced materials science. AI-driven generative design software creates optimised structures that exploit the geometric freedom of 3D printing, producing parts that are lighter and stronger than those designed by human engineers alone. Multi-material printing, which deposits different materials within a single build, is opening new possibilities for functionally graded components and embedded electronics. As these technologies mature, 3D printing is poised to move from a complementary manufacturing tool to a central pillar of industrial production.`,
      questions: [
        { number: 27, type: "matching_information", text: "An example of 3D printing reducing the number of components in a product", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "C", explanation: "Paragraph C describes GE Aviation consolidating twenty parts into one." },
        { number: 28, type: "matching_information", text: "The use of 3D printing in constructing residential buildings", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "E", explanation: "Paragraph E discusses ICON printing concrete walls for homes." },
        { number: 29, type: "matching_information", text: "Limitations of 3D printing compared to traditional manufacturing", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "G", explanation: "Paragraph G discusses speed, cost, and quality limitations." },
        { number: 30, type: "matching_information", text: "Military applications of portable 3D printing", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "F", explanation: "Paragraph F discusses mobile 3D-printing units for the military." },
        { number: 31, type: "matching_information", text: "The original invention and early commercialisation of 3D printing", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "A", explanation: "Paragraph A discusses SLA, Charles Hull, and the first companies." },
        { number: 32, type: "matching_information", text: "AI-driven design and multi-material capabilities", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "H", explanation: "Paragraph H discusses generative design and multi-material printing." },
        { number: 33, type: "flow_chart_completion", text: "Charles Hull developed stereolithography in __(33)__.", correctAnswer: "1984", explanation: "The passage says 'developed by Charles Hull in 1984.'" },
        { number: 34, type: "flow_chart_completion", text: "SLA uses an ultraviolet __(34)__ to cure liquid resin.", correctAnswer: "laser", explanation: "The passage says 'an ultraviolet laser to cure liquid photopolymer resin.'" },
        { number: 35, type: "flow_chart_completion", text: "FDM was commercialised in the early 1990s by __(35)__.", correctAnswer: "Stratasys", explanation: "The passage says 'commercialised in the early 1990s by Stratasys.'" },
        { number: 36, type: "flow_chart_completion", text: "GE Aviation's 3D-printed fuel nozzle is __(36)__ per cent lighter than the original.", correctAnswer: "twenty-five", explanation: "The passage says 'twenty-five per cent lighter.'" },
        { number: 37, type: "flow_chart_completion", text: "ICON can print concrete walls for homes in as little as __(37)__ hours.", correctAnswer: "48", explanation: "The passage says 'in as little as 48 hours.'" },
        { number: 38, type: "flow_chart_completion", text: "Dubai requires __(38)__ per cent of new buildings to be 3D-printed by 2030.", correctAnswer: "twenty-five", explanation: "The passage says 'twenty-five per cent of new buildings.'" },
        { number: 39, type: "flow_chart_completion", text: "Quality assurance for 3D-printed parts uses CT scanning and __(39)__-based defect detection.", correctAnswer: "machine-learning", explanation: "The passage says 'machine-learning-based defect detection.'" },
        { number: 40, type: "flow_chart_completion", text: "__(40)__ design software creates optimised structures for 3D printing.", correctAnswer: "generative", explanation: "The passage says 'AI-driven generative design software.'" },
      ],
    },
  ],
};
