import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_35: ReadingTest = {
  id: 35,
  passages: [
    {
      title: "History of Aviation",
      text: `The dream of human flight is ancient, but its realisation is remarkably recent. From the mythical Icarus to Leonardo da Vinci's visionary sketches of flying machines, humanity imagined soaring through the skies for millennia before the necessary technologies converged to make powered, controlled flight a reality in the early twentieth century.

The first successful sustained human flight was achieved not in an aeroplane but in a hot air balloon. On 21 November 1783, Jean-François Pilâtre de Rozier and the Marquis d'Arlandes ascended over Paris in a Montgolfier brothers' balloon, travelling approximately nine kilometres in twenty-five minutes. Balloon technology advanced rapidly, finding military applications in reconnaissance during the French Revolutionary Wars and the American Civil War, but balloons lacked directional control, remaining at the mercy of the wind.

The Wright brothers, Orville and Wilbur, achieved the first powered, sustained, and controlled heavier-than-air flight at Kitty Hawk, North Carolina, on 17 December 1903. Their aircraft, the Wright Flyer, stayed airborne for twelve seconds during its initial flight, covering a distance of approximately thirty-seven metres. What distinguished the Wrights from their competitors was not engine power but their systematic approach to the problem of flight control, particularly their invention of wing warping for roll control — the conceptual predecessor of modern ailerons.

Aviation progressed with extraordinary speed in the decades following. World War I (1914–1918) accelerated aircraft development dramatically, transforming fragile biplanes into capable military machines used for reconnaissance, bombing, and aerial combat. The interwar period saw landmark achievements in long-distance flight: Charles Lindbergh's solo transatlantic crossing in 1927, Amelia Earhart's solo Atlantic flight in 1932, and the development of commercial air routes that began to connect continents.

World War II catalysed another leap forward. Military necessity drove the development of faster, more powerful aircraft, culminating in the introduction of jet propulsion. The British Gloster Meteor and German Messerschmitt Me 262 became the first operational jet fighters, demonstrating speeds and altitudes impossible for propeller-driven aircraft. The war also spurred advances in radar, navigation, and materials science that would prove essential to post-war civil aviation.

The post-war era witnessed the democratisation of air travel. The de Havilland Comet, introduced in 1952, was the world's first commercial jet airliner, though its career was marred by a series of fatal structural failures caused by metal fatigue. The Boeing 707, entering service in 1958, proved more successful and inaugurated the age of mass jet travel. The Boeing 747, the first wide-body "jumbo jet," entered service in 1970, dramatically reducing the cost per seat and making international air travel accessible to middle-class travellers for the first time.

Supersonic commercial aviation was pioneered by the Anglo-French Concorde, which entered service in 1976 and could cross the Atlantic in approximately three and a half hours — less than half the time required by conventional aircraft. However, the Concorde's extraordinary fuel consumption, limited seating capacity, noise pollution, and restricted route network confined it to a niche market, and it was retired from service in 2003.

Modern aviation faces new challenges. The industry accounts for approximately two to three per cent of global CO₂ emissions, a figure projected to grow as passenger numbers increase. Sustainable aviation fuels (SAFs), produced from biomass, waste oils, or synthetic processes, can reduce lifecycle emissions by up to eighty per cent compared with conventional jet fuel and are being adopted by major airlines. Electric and hydrogen-powered aircraft are under development for short-haul routes, with several companies targeting certification by 2030. The aviation industry has committed to achieving net-zero carbon emissions by 2050, an ambitious target that will require transformative changes across aircraft design, propulsion, operations, and fuel supply chains.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "What was the first form of sustained human flight?", options: ["A A glider designed by Leonardo da Vinci", "B A hot air balloon", "C The Wright Flyer", "D A military reconnaissance aircraft"], correctAnswer: "B", explanation: "The passage states 'The first successful sustained human flight was achieved... in a hot air balloon.'" },
        { number: 2, type: "multiple_choice", text: "What made the Wright brothers' approach to flight unique?", options: ["A They had the most powerful engine available.", "B They focused systematically on flight control.", "C They were the first to attempt powered flight.", "D They received government funding for their research."], correctAnswer: "B", explanation: "The passage says the Wrights were distinguished by 'their systematic approach to the problem of flight control.'" },
        { number: 3, type: "multiple_choice", text: "Why was the Concorde retired from service?", options: ["A It was replaced by faster aircraft.", "B Its technology became obsolete.", "C It was too expensive and environmentally problematic for mass use.", "D Its manufacturer went bankrupt."], correctAnswer: "C", explanation: "The passage mentions fuel consumption, limited capacity, noise, and restricted routes." },
        { number: 4, type: "multiple_choice", text: "What is the aviation industry's carbon emissions target?", options: ["A Reduce emissions by fifty per cent by 2030", "B Achieve net-zero carbon emissions by 2050", "C Eliminate all fossil fuel use by 2040", "D Reduce passenger numbers by twenty per cent"], correctAnswer: "B", explanation: "The passage states 'net-zero carbon emissions by 2050.'" },
        { number: 5, type: "sentence_completion", text: "The Montgolfier brothers' balloon flight covered approximately __(5)__ kilometres.", correctAnswer: "nine", explanation: "The passage states 'approximately nine kilometres.'" },
        { number: 6, type: "sentence_completion", text: "The Wright Flyer's initial flight lasted __(6)__ seconds.", correctAnswer: "twelve", explanation: "The passage states 'twelve seconds.'" },
        { number: 7, type: "sentence_completion", text: "Charles Lindbergh completed his solo transatlantic crossing in __(7)__.", correctAnswer: "1927", explanation: "The passage states '1927.'" },
        { number: 8, type: "sentence_completion", text: "The de Havilland __(8)__ was the world's first commercial jet airliner.", correctAnswer: "Comet", explanation: "The passage names 'The de Havilland Comet.'" },
        { number: 9, type: "sentence_completion", text: "The Boeing 747 entered service in __(9)__.", correctAnswer: "1970", explanation: "The passage states '1970.'" },
        { number: 10, type: "sentence_completion", text: "Concorde could cross the Atlantic in approximately __(10)__ and a half hours.", correctAnswer: "three", explanation: "The passage states 'approximately three and a half hours.'" },
        { number: 11, type: "sentence_completion", text: "Sustainable aviation fuels can reduce emissions by up to __(11)__ per cent.", correctAnswer: "eighty", explanation: "The passage states 'up to eighty per cent.'" },
        { number: 12, type: "sentence_completion", text: "Aviation accounts for approximately __(12)__ to three per cent of global CO₂ emissions.", correctAnswer: "two", explanation: "The passage states 'two to three per cent.'" },
        { number: 13, type: "sentence_completion", text: "The Wright brothers invented wing __(13)__ for roll control.", correctAnswer: "warping", explanation: "The passage mentions 'wing warping for roll control.'" },
      ],
    },
    {
      title: "Environmental Policies",
      text: `A. Environmental policy — the body of laws, regulations, and agreements designed to manage human interaction with the natural environment — has evolved dramatically since the mid-twentieth century. What began as localised responses to specific pollution incidents has grown into a complex, multilayered governance framework spanning local, national, and international levels. The effectiveness of environmental policy in addressing challenges such as climate change, biodiversity loss, and resource depletion remains one of the defining questions of our time.

B. The modern environmental movement is often traced to the publication of Rachel Carson's Silent Spring in 1962, which documented the devastating effects of pesticide use — particularly DDT — on wildlife and ecosystems. The book galvanised public concern and is widely credited with inspiring the creation of the United States Environmental Protection Agency (EPA) in 1970 and the passage of landmark legislation including the Clean Air Act (1970), the Clean Water Act (1972), and the Endangered Species Act (1973). These laws established the regulatory frameworks that continue to shape American environmental governance.

C. International environmental cooperation gained momentum from the 1970s onward. The United Nations Conference on the Human Environment, held in Stockholm in 1972, was the first major international meeting to address environmental issues, producing a declaration of principles and establishing the United Nations Environment Programme (UNEP). The Montreal Protocol (1987), which phased out the production of ozone-depleting substances, is widely regarded as the most successful international environmental agreement ever negotiated, demonstrating that coordinated global action can solve environmental problems when the science is clear and political will exists.

D. Climate change policy has proven far more difficult to negotiate. The United Nations Framework Convention on Climate Change (UNFCCC), adopted in 1992, established the principle of "common but differentiated responsibilities," acknowledging that developed nations bear greater historical responsibility for greenhouse gas emissions. The Kyoto Protocol (1997) set binding emission reduction targets for developed countries but was undermined by the withdrawal of the United States and the exclusion of major developing emitters. The Paris Agreement (2015) adopted a different approach, establishing a framework in which all nations set voluntary emission reduction targets — Nationally Determined Contributions (NDCs) — with regular review and ratcheting mechanisms designed to increase ambition over time.

E. Market-based instruments have emerged as important tools in the environmental policy arsenal. Carbon pricing, implemented through carbon taxes or emissions trading systems (ETS), places a financial cost on greenhouse gas emissions, incentivising businesses to reduce their carbon footprint. The European Union Emissions Trading System, launched in 2005, is the world's largest carbon market, covering approximately forty per cent of EU greenhouse gas emissions. Economic analysis suggests that carbon prices of $50 to $100 per tonne of CO₂ are necessary to meet Paris Agreement targets, though most existing carbon prices remain well below this threshold.

F. Regulatory approaches continue to play a central role alongside market mechanisms. Vehicle emission standards, energy efficiency requirements for buildings and appliances, renewable energy mandates, and restrictions on single-use plastics represent direct regulatory interventions that have achieved measurable environmental improvements. The EU's ban on single-use plastic items, effective from 2021, demonstrates the potential of regulatory action to drive rapid behavioural and industrial change.

G. Subnational and local governments increasingly drive environmental policy innovation. Cities such as Copenhagen, which aims to become carbon-neutral by 2025, and states such as California, which has adopted emission standards exceeding federal requirements, demonstrate that ambitious environmental action is possible even in the absence of national leadership. Corporate sustainability commitments, driven by investor pressure, consumer demand, and reputational considerations, are also shaping environmental outcomes, though concerns about greenwashing — the practice of making misleading environmental claims — remain significant.

H. The challenges ahead are formidable. Current national climate pledges, even if fully implemented, are insufficient to limit global warming to 1.5 degrees Celsius. Biodiversity continues to decline despite decades of conservation policy. Environmental justice — ensuring that the burdens of pollution and climate change do not fall disproportionately on marginalised communities — requires systemic attention. Effective environmental governance in the twenty-first century will demand not only stronger policies but also deeper integration of environmental considerations into economic planning, trade agreements, and social policy.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Section A", options: ["I. The birth of modern environmentalism", "II. The evolution of environmental governance", "III. Global cooperation on environmental issues", "IV. The complex politics of climate agreements", "V. Putting a price on pollution", "VI. Direct regulation for environmental protection", "VII. Local leadership in environmental action", "VIII. Remaining gaps in environmental policy"], correctAnswer: "II", explanation: "Section A discusses the evolution of environmental policy." },
        { number: 15, type: "matching_headings", text: "Section B", options: ["I. The birth of modern environmentalism", "II. The evolution of environmental governance", "III. Global cooperation on environmental issues", "IV. The complex politics of climate agreements", "V. Putting a price on pollution", "VI. Direct regulation for environmental protection", "VII. Local leadership in environmental action", "VIII. Remaining gaps in environmental policy"], correctAnswer: "I", explanation: "Section B discusses Silent Spring and the creation of the EPA." },
        { number: 16, type: "matching_headings", text: "Section C", options: ["I. The birth of modern environmentalism", "II. The evolution of environmental governance", "III. Global cooperation on environmental issues", "IV. The complex politics of climate agreements", "V. Putting a price on pollution", "VI. Direct regulation for environmental protection", "VII. Local leadership in environmental action", "VIII. Remaining gaps in environmental policy"], correctAnswer: "III", explanation: "Section C discusses the Stockholm conference and Montreal Protocol." },
        { number: 17, type: "matching_headings", text: "Section D", options: ["I. The birth of modern environmentalism", "II. The evolution of environmental governance", "III. Global cooperation on environmental issues", "IV. The complex politics of climate agreements", "V. Putting a price on pollution", "VI. Direct regulation for environmental protection", "VII. Local leadership in environmental action", "VIII. Remaining gaps in environmental policy"], correctAnswer: "IV", explanation: "Section D discusses UNFCCC, Kyoto, and Paris Agreement." },
        { number: 18, type: "matching_headings", text: "Section E", options: ["I. The birth of modern environmentalism", "II. The evolution of environmental governance", "III. Global cooperation on environmental issues", "IV. The complex politics of climate agreements", "V. Putting a price on pollution", "VI. Direct regulation for environmental protection", "VII. Local leadership in environmental action", "VIII. Remaining gaps in environmental policy"], correctAnswer: "V", explanation: "Section E discusses carbon pricing and ETS." },
        { number: 19, type: "matching_headings", text: "Section G", options: ["I. The birth of modern environmentalism", "II. The evolution of environmental governance", "III. Global cooperation on environmental issues", "IV. The complex politics of climate agreements", "V. Putting a price on pollution", "VI. Direct regulation for environmental protection", "VII. Local leadership in environmental action", "VIII. Remaining gaps in environmental policy"], correctAnswer: "VII", explanation: "Section G discusses cities and subnational governments." },
        { number: 20, type: "table_completion", text: "Rachel Carson published Silent Spring in __(20)__.", correctAnswer: "1962", explanation: "The passage states '1962.'" },
        { number: 21, type: "table_completion", text: "The EPA was created in __(21)__.", correctAnswer: "1970", explanation: "The passage states '1970.'" },
        { number: 22, type: "table_completion", text: "The Montreal Protocol was signed in __(22)__.", correctAnswer: "1987", explanation: "The passage states '1987.'" },
        { number: 23, type: "table_completion", text: "The EU ETS covers approximately __(23)__ per cent of EU greenhouse gas emissions.", correctAnswer: "forty", explanation: "The passage states 'approximately forty per cent.'" },
        { number: 24, type: "table_completion", text: "Carbon prices of $__(24)__ to $100 per tonne are considered necessary to meet Paris Agreement targets.", correctAnswer: "50", explanation: "The passage states '$50 to $100 per tonne.'" },
        { number: 25, type: "table_completion", text: "Copenhagen aims to become carbon-neutral by __(25)__.", correctAnswer: "2025", explanation: "The passage states 'carbon-neutral by 2025.'" },
        { number: 26, type: "table_completion", text: "The Paris Agreement was adopted in __(26)__.", correctAnswer: "2015", explanation: "The passage states '2015.'" },
      ],
    },
    {
      title: "Nanorobots in Medicine",
      text: `Nanorobotics — the design and construction of machines at the nanometre scale, typically between one and one hundred nanometres — represents one of the most ambitious and potentially transformative frontiers in medical technology. While fully autonomous nanorobots capable of navigating the human body remain largely theoretical, significant progress has been made in developing nanoscale devices and particles that can perform targeted medical functions with a precision impossible at larger scales.

A. The conceptual foundation of medical nanorobotics was laid by physicist Richard Feynman in his famous 1959 lecture "There's Plenty of Room at the Bottom," in which he speculated about the possibility of manipulating matter at the atomic level. K. Eric Drexler expanded on these ideas in his 1986 book Engines of Creation, envisioning molecular machines capable of assembling and repairing biological structures atom by atom. While Drexler's vision remains far beyond current technological capabilities, it provided an intellectual framework that has inspired decades of research.

B. The most clinically advanced application of nanotechnology in medicine is targeted drug delivery. Conventional chemotherapy drugs circulate throughout the entire body, killing cancer cells but also damaging healthy tissue and causing severe side effects. Nanoparticle drug carriers — including liposomes, polymeric nanoparticles, and dendrimers — can be engineered to accumulate preferentially in tumour tissue, either through passive targeting (exploiting the leaky vasculature of tumours) or active targeting (attaching molecules that bind to receptors specifically overexpressed on cancer cells). The first FDA-approved nanomedicine, Doxil (liposomal doxorubicin), was approved in 1995 for the treatment of ovarian cancer and Kaposi's sarcoma.

C. Magnetic nanoparticles offer unique capabilities for both diagnosis and therapy. Superparamagnetic iron oxide nanoparticles (SPIONs) serve as contrast agents in magnetic resonance imaging (MRI), enhancing the visibility of tumours, vascular abnormalities, and inflammatory lesions. When subjected to alternating magnetic fields, these same particles generate localised heat — a phenomenon called magnetic hyperthermia — that can destroy cancer cells while sparing surrounding healthy tissue. The combination of diagnostic and therapeutic functions in a single nanoplatform, known as theranostics, represents a paradigm shift in personalised medicine.

D. DNA nanorobots, constructed entirely from folded DNA strands using a technique called DNA origami, represent a remarkably innovative approach. Researchers at Arizona State University created DNA nanorobots that function as autonomous drug delivery vehicles: they travel through the bloodstream, recognise specific molecular markers on cancer cells, mechanically open to expose a blood-clotting enzyme, and cut off the tumour's blood supply. In animal studies, these DNA nanorobots significantly reduced tumour growth in breast cancer, melanoma, and ovarian cancer models without causing observable side effects.

E. Nanoscale biosensors are transforming diagnostic medicine. Gold nanoparticles change colour when they aggregate, a property exploited in rapid diagnostic tests for diseases including HIV, malaria, and COVID-19. Carbon nanotubes and graphene-based sensors can detect biomarkers at concentrations measured in parts per trillion, enabling the diagnosis of diseases at far earlier stages than conventional laboratory tests allow. Implantable nanosensors that continuously monitor glucose, pH, or specific protein levels could eventually provide real-time health data, enabling truly preventive medicine.

F. The blood-brain barrier (BBB), which prevents most therapeutic molecules from reaching the brain, presents one of the greatest challenges in neurology and neurosurgery. Nanoparticles engineered with specific surface coatings can cross the BBB, offering potential pathways for treating brain tumours, Alzheimer's disease, Parkinson's disease, and other neurological conditions that currently lack effective treatments. Focused ultrasound, used in conjunction with microbubbles, can temporarily and locally open the BBB, allowing targeted nanoparticle delivery to specific brain regions.

G. Safety and regulatory considerations present significant challenges for medical nanorobotics. The behaviour of nanoparticles in biological systems is complex and not yet fully understood. Concerns include potential toxicity, unintended accumulation in organs such as the liver and spleen, immune system activation, and long-term environmental effects of nanomaterials. Regulatory frameworks developed for conventional pharmaceuticals may not adequately address the unique properties and risks of nanomedicines, and agencies including the FDA and the European Medicines Agency are actively developing specialised guidelines.

H. The future of medical nanorobotics is both exciting and uncertain. Advances in artificial intelligence, materials science, and synthetic biology are converging to create increasingly sophisticated nanoscale devices. Swarm nanorobotics — in which large numbers of nanoscale agents coordinate their actions to perform complex tasks — is an active area of research that could eventually enable capabilities such as non-invasive surgery, plaque removal from blood vessels, and precise neural stimulation. While many of these applications remain years or decades away from clinical reality, the trajectory of the field suggests that nanorobotics will play an increasingly important role in the medicine of the future.`,
      questions: [
        { number: 27, type: "matching_information", text: "The first FDA-approved nanomedicine", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "B", explanation: "Section B discusses Doxil, approved in 1995." },
        { number: 28, type: "matching_information", text: "Nanoparticles that can cross the blood-brain barrier", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "F", explanation: "Section F discusses BBB crossing nanoparticles." },
        { number: 29, type: "matching_information", text: "Robots made from folded DNA strands", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "D", explanation: "Section D discusses DNA origami nanorobots." },
        { number: 30, type: "matching_information", text: "Concerns about the safety of nanoparticles in the body", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "G", explanation: "Section G discusses toxicity and regulatory concerns." },
        { number: 31, type: "matching_information", text: "Nanoparticles used for both imaging and cancer treatment simultaneously", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "C", explanation: "Section C discusses theranostics using magnetic nanoparticles." },
        { number: 32, type: "matching_information", text: "The concept of coordinated nanoscale agents performing complex tasks", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "H", explanation: "Section H discusses swarm nanorobotics." },
        { number: 33, type: "multiple_choice", text: "Who first proposed the idea of manipulating matter at the atomic level?", options: ["A K. Eric Drexler", "B Richard Feynman", "C Researchers at Arizona State University", "D The developers of Doxil"], correctAnswer: "B", explanation: "The passage says 'Richard Feynman in his famous 1959 lecture.'" },
        { number: 34, type: "multiple_choice", text: "How do DNA nanorobots attack tumours?", options: ["A By delivering chemotherapy drugs directly", "B By emitting radiation to destroy cancer cells", "C By cutting off the tumour's blood supply", "D By activating the patient's immune system"], correctAnswer: "C", explanation: "The passage says they 'expose a blood-clotting enzyme, and cut off the tumour's blood supply.'" },
        { number: 35, type: "multiple_choice", text: "What property of gold nanoparticles is used in rapid diagnostic tests?", options: ["A They emit fluorescent light.", "B They change colour when they aggregate.", "C They become magnetic in the presence of disease.", "D They dissolve in infected blood samples."], correctAnswer: "B", explanation: "The passage says 'Gold nanoparticles change colour when they aggregate.'" },
        { number: 36, type: "multiple_choice", text: "What is theranostics?", options: ["A A type of surgical nanorobot", "B The study of nanotoxicology", "C The combination of diagnostic and therapeutic functions in one platform", "D A regulatory framework for nanomedicines"], correctAnswer: "C", explanation: "The passage defines theranostics as 'The combination of diagnostic and therapeutic functions in a single nanoplatform.'" },
        { number: 37, type: "short_answer", text: "In what year was Doxil approved by the FDA?", correctAnswer: "1995", explanation: "The passage states 'approved in 1995.'" },
        { number: 38, type: "short_answer", text: "What technique is used to construct DNA nanorobots from folded DNA strands?", correctAnswer: "DNA origami", explanation: "The passage mentions 'a technique called DNA origami.'" },
        { number: 39, type: "short_answer", text: "What type of nanoparticles serve as MRI contrast agents?", correctAnswer: "superparamagnetic iron oxide nanoparticles", explanation: "The passage names 'Superparamagnetic iron oxide nanoparticles (SPIONs).'" },
        { number: 40, type: "short_answer", text: "What is the name of the phenomenon where magnetic nanoparticles generate localised heat?", correctAnswer: "magnetic hyperthermia", explanation: "The passage defines 'magnetic hyperthermia.'" },
      ],
    },
  ],
};
