import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_24: ReadingTest = {
  id: 24,
  passages: [
    {
      title: "The Science of Happiness",
      text: `The scientific study of happiness — what makes people feel satisfied with their lives and experience positive emotions — has grown from a marginal academic pursuit into a major interdisciplinary field over the past three decades. Traditionally, psychology focused primarily on mental illness and dysfunction, devoting relatively little attention to understanding what enables people to flourish. The emergence of positive psychology in the late 1990s, championed by the American psychologist Martin Seligman, redirected scholarly attention toward the factors that contribute to human well-being and fulfilment.

One of the most robust findings in happiness research is that beyond a certain threshold, additional income contributes surprisingly little to subjective well-being. A landmark study by the economists Daniel Kahneman and Angus Deaton, published in 2010, found that emotional well-being — the day-to-day experience of positive emotions — plateaued at an annual household income of approximately seventy-five thousand dollars in the United States. Above that level, people reported higher life satisfaction when evaluating their lives as a whole, but their moment-to-moment emotional experiences did not improve significantly. This finding challenged the widespread assumption that wealth is the primary determinant of happiness.

Social relationships have consistently emerged as the strongest predictor of happiness across cultures. The Harvard Study of Adult Development, which has followed hundreds of participants for over eighty years, concluded that the quality of close relationships is the single most important factor in long-term health and happiness. People with strong social connections — characterised by warmth, trust, and mutual support — live longer, experience less cognitive decline in old age, and report substantially higher levels of well-being than those who are socially isolated.

The concept of "flow," introduced by the Hungarian-American psychologist Mihaly Csikszentmihalyi, describes a state of complete absorption in an activity that is intrinsically rewarding. Flow occurs when a person's skills are well-matched to the challenge at hand — sufficiently demanding to require full concentration but not so difficult as to produce anxiety. During flow states, people lose awareness of time, forget about self-consciousness, and experience deep enjoyment. Csikszentmihalyi's research found that people who regularly experience flow report higher overall life satisfaction, regardless of the specific activities in which flow occurs.

Gratitude has been identified as another significant contributor to happiness. Experimental studies have shown that people who regularly practise gratitude — for example, by keeping a journal in which they record things they are thankful for — report increased positive emotions, greater life satisfaction, and improved physical health compared with control groups. The mechanisms underlying these effects are thought to include increased attention to positive experiences, reduced social comparison, and strengthened social bonds through expressions of appreciation.

Genetic factors appear to account for approximately fifty percent of individual variation in happiness levels, according to twin studies conducted by behavioural geneticists. This finding suggests that each person has a genetically influenced "set point" around which their happiness fluctuates in response to life circumstances. However, the remaining fifty percent is influenced by intentional activities, attitudes, and life circumstances, providing substantial scope for individuals to increase their well-being through deliberate choices and practices.

Recent research has increasingly focused on the concept of "eudaimonic" well-being — happiness derived from having a sense of purpose, engaging in meaningful activities, and striving toward personal growth — as distinct from "hedonic" well-being, which centres on pleasure and the avoidance of pain. Studies suggest that eudaimonic well-being is associated with better physical health outcomes, including reduced inflammation and improved immune function, compared with purely hedonic happiness. This distinction has important implications for public policy, suggesting that governments should aim to foster conditions that enable citizens to lead purposeful lives, not merely comfortable ones.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "Who championed the emergence of positive psychology?", options: ["A. Daniel Kahneman", "B. Mihaly Csikszentmihalyi", "C. Martin Seligman", "D. Angus Deaton"], correctAnswer: "C", explanation: "The passage credits Martin Seligman with championing positive psychology." },
        { number: 2, type: "multiple_choice", text: "At what income level did emotional well-being plateau according to Kahneman and Deaton?", options: ["A. $50,000", "B. $75,000", "C. $100,000", "D. $150,000"], correctAnswer: "B", explanation: "The passage states 'approximately seventy-five thousand dollars'." },
        { number: 3, type: "multiple_choice", text: "What does the Harvard Study identify as the most important factor for long-term happiness?", options: ["A. Financial security", "B. Physical exercise", "C. Quality of close relationships", "D. Career achievement"], correctAnswer: "C", explanation: "The study concluded that 'the quality of close relationships is the single most important factor'." },
        { number: 4, type: "multiple_choice", text: "What percentage of happiness variation is attributed to genetic factors?", options: ["A. Twenty-five percent", "B. Thirty-five percent", "C. Fifty percent", "D. Seventy-five percent"], correctAnswer: "C", explanation: "The passage states 'approximately fifty percent of individual variation'." },
        { number: 5, type: "multiple_choice", text: "What is 'eudaimonic' well-being associated with?", options: ["A. Financial success", "B. Pleasure and comfort", "C. Purpose and personal growth", "D. Social media engagement"], correctAnswer: "C", explanation: "Defined as 'happiness derived from having a sense of purpose, engaging in meaningful activities, and striving toward personal growth'." },
        { number: 6, type: "sentence_completion", text: "Before positive psychology, traditional psychology focused primarily on mental illness and ________.", correctAnswer: "dysfunction", explanation: "The passage states psychology 'focused primarily on mental illness and dysfunction'." },
        { number: 7, type: "sentence_completion", text: "The Harvard Study has followed participants for over ________ years.", correctAnswer: "eighty", explanation: "The passage states 'over eighty years'." },
        { number: 8, type: "sentence_completion", text: "Flow occurs when a person's skills are well-matched to the ________ at hand.", correctAnswer: "challenge", explanation: "The passage describes flow as occurring 'when a person's skills are well-matched to the challenge at hand'." },
        { number: 9, type: "sentence_completion", text: "People who practise gratitude by keeping a ________ report increased positive emotions.", correctAnswer: "journal", explanation: "The passage mentions 'keeping a journal in which they record things they are thankful for'." },
        { number: 10, type: "sentence_completion", text: "Each person has a genetically influenced '________ point' around which happiness fluctuates.", correctAnswer: "set", explanation: "The passage describes a 'genetically influenced \"set point\"'." },
        { number: 11, type: "sentence_completion", text: "During flow states, people lose awareness of ________ and forget self-consciousness.", correctAnswer: "time", explanation: "The passage states 'people lose awareness of time'." },
        { number: 12, type: "sentence_completion", text: "Eudaimonic well-being is associated with reduced inflammation and improved ________ function.", correctAnswer: "immune", explanation: "The passage states 'improved immune function'." },
        { number: 13, type: "sentence_completion", text: "Mihaly Csikszentmihalyi was a ________-American psychologist.", correctAnswer: "Hungarian", explanation: "Described as 'the Hungarian-American psychologist'." },
      ],
    },
    {
      title: "Marine Ecosystems",
      text: `Paragraph A
Marine ecosystems, which cover approximately seventy-one percent of Earth's surface, are among the most complex and productive biological systems on the planet. From the sunlit surface waters teeming with microscopic phytoplankton to the perpetual darkness of deep-sea hydrothermal vents, the oceans support an extraordinary diversity of life forms and play a vital role in regulating the global climate, nutrient cycles, and atmospheric composition.

Paragraph B
Coral reefs, often described as the rainforests of the sea, support approximately twenty-five percent of all known marine species despite covering less than one percent of the ocean floor. The structural foundation of reefs is built by coral polyps — tiny animals related to jellyfish — that secrete calcium carbonate skeletons over centuries, creating complex three-dimensional habitats. These structures provide shelter, feeding grounds, and nursery areas for thousands of species of fish, invertebrates, and algae. Coral reefs also provide essential ecosystem services to human communities, including coastal protection from storms and waves, fisheries that feed hundreds of millions of people, and tourism revenues worth billions of dollars annually.

Paragraph C
The open ocean, or pelagic zone, supports vast food webs built upon the photosynthetic activity of phytoplankton — microscopic organisms that collectively produce approximately half of the world's oxygen through photosynthesis. These tiny organisms form the base of marine food chains, supporting zooplankton, small fish, and ultimately large predators such as tuna, sharks, and marine mammals. The biological carbon pump — the process by which phytoplankton absorb carbon dioxide at the surface, die, and sink to the deep ocean — plays a critical role in regulating atmospheric carbon dioxide levels and mitigating climate change.

Paragraph D
Deep-sea ecosystems, which exist below two hundred metres where sunlight cannot penetrate, were long assumed to be biological deserts. This assumption was dramatically overturned in 1977 with the discovery of thriving communities of organisms around hydrothermal vents on the Galápagos Rift in the Pacific Ocean. These vent communities derive their energy not from sunlight but from chemosynthesis — the conversion of chemical energy from hydrogen sulphide and other compounds expelled by the vents into organic matter by specialised bacteria. Giant tubeworms, blind shrimp, and heat-tolerant crabs are among the remarkable species found in these extreme environments.

Paragraph E
Marine ecosystems face unprecedented threats from human activities. Ocean acidification, caused by the absorption of excess atmospheric carbon dioxide, reduces the ability of corals, molluscs, and other calcifying organisms to build and maintain their calcium carbonate structures. Rising sea temperatures drive coral bleaching events, during which stressed corals expel the symbiotic algae that provide them with nutrients and colour, often leading to mass coral death. Overfishing has depleted populations of numerous commercially important species and disrupted marine food webs, while plastic pollution accumulates throughout the ocean, from surface waters to the deepest trenches.

Paragraph F
Conservation efforts to protect marine ecosystems have expanded significantly in recent years. Marine protected areas, where fishing and other extractive activities are restricted or prohibited, have been shown to increase fish abundance and biodiversity within their boundaries and in surrounding waters through spillover effects. International agreements to reduce greenhouse gas emissions are essential for addressing ocean acidification and warming. Sustainable fisheries management, including science-based catch limits, seasonal closures, and the elimination of harmful subsidies that encourage overfishing, is crucial for maintaining the health and productivity of marine ecosystems for future generations.`,
      questions: (() => {
        const headings = [
          "i. Life in the deepest parts of the ocean",
          "ii. The rich biodiversity of coral reefs",
          "iii. Steps being taken to safeguard ocean life",
          "iv. An introduction to Earth's ocean environments",
          "v. Microscopic organisms that sustain ocean food chains",
          "vi. The economic value of deep-sea mining",
          "vii. Human-caused damage to marine environments",
          "viii. The history of oceanographic exploration",
        ];
        return [
          { number: 14, type: "matching_headings" as const, text: "Paragraph A", options: headings, correctAnswer: "iv", explanation: "Paragraph A provides a general introduction to marine ecosystems." },
          { number: 15, type: "matching_headings" as const, text: "Paragraph B", options: headings, correctAnswer: "ii", explanation: "Paragraph B discusses coral reefs and their biodiversity." },
          { number: 16, type: "matching_headings" as const, text: "Paragraph C", options: headings, correctAnswer: "v", explanation: "Paragraph C discusses phytoplankton and their role in food chains." },
          { number: 17, type: "matching_headings" as const, text: "Paragraph D", options: headings, correctAnswer: "i", explanation: "Paragraph D discusses deep-sea hydrothermal vent communities." },
          { number: 18, type: "matching_headings" as const, text: "Paragraph E", options: headings, correctAnswer: "vii", explanation: "Paragraph E discusses threats from human activities." },
          { number: 19, type: "matching_headings" as const, text: "Paragraph F", options: headings, correctAnswer: "iii", explanation: "Paragraph F discusses conservation efforts." },
          { number: 20, type: "summary_completion" as const, text: "Coral reefs support approximately ________ percent of all known marine species.", correctAnswer: "twenty-five", explanation: "Directly stated in the passage." },
          { number: 21, type: "summary_completion" as const, text: "Phytoplankton collectively produce approximately half of the world's ________.", correctAnswer: "oxygen", explanation: "The passage states they 'produce approximately half of the world's oxygen'." },
          { number: 22, type: "summary_completion" as const, text: "Deep-sea vent communities derive energy from ________ rather than sunlight.", correctAnswer: "chemosynthesis", explanation: "The passage describes 'chemosynthesis' as the energy source." },
          { number: 23, type: "summary_completion" as const, text: "Ocean acidification reduces the ability of organisms to build ________ carbonate structures.", correctAnswer: "calcium", explanation: "The passage mentions 'calcium carbonate structures'." },
          { number: 24, type: "short_answer" as const, text: "In what year were hydrothermal vent communities first discovered?", correctAnswer: "1977", explanation: "The passage states discovery was in 1977." },
          { number: 25, type: "short_answer" as const, text: "What do stressed corals expel during bleaching events?", correctAnswer: "symbiotic algae", explanation: "The passage states corals 'expel the symbiotic algae'." },
          { number: 26, type: "short_answer" as const, text: "What type of protected areas restrict fishing and extractive activities?", correctAnswer: "marine protected areas", explanation: "Directly described in the passage." },
        ];
      })(),
    },
    {
      title: "Autonomous Vehicles",
      text: `The development of autonomous vehicles — cars, trucks, and other road vehicles capable of navigating and operating without human input — represents one of the most ambitious and consequential technological undertakings of the early twenty-first century. Proponents argue that self-driving vehicles have the potential to dramatically reduce traffic accidents, ease congestion, lower emissions, and transform urban planning. Critics counter that the technology faces formidable technical, ethical, and regulatory hurdles that may take decades to resolve.

The Society of Automotive Engineers has defined six levels of driving automation, ranging from Level 0 (no automation) to Level 5 (full automation under all conditions). Most current commercial systems operate at Level 2, providing features such as adaptive cruise control and lane-keeping assistance that still require continuous driver supervision. Level 3 systems, which allow drivers to disengage from the driving task under certain conditions, have been approved in limited forms in some jurisdictions. The leap from Level 3 to Levels 4 and 5 — where the vehicle assumes full responsibility for driving in progressively wider operational domains — remains the industry's central technical challenge.

The technology underpinning autonomous vehicles combines multiple sensor systems, artificial intelligence, and high-definition mapping. Lidar (light detection and ranging) sensors create detailed three-dimensional maps of the vehicle's surroundings by emitting millions of laser pulses per second and measuring their reflections. Cameras provide visual information essential for reading traffic signs, detecting traffic lights, and recognising pedestrians. Radar sensors detect the speed and distance of other vehicles in all weather conditions. These sensor inputs are processed by AI algorithms that must make real-time decisions about acceleration, braking, steering, and route planning in an environment of extraordinary complexity and unpredictability.

The safety argument for autonomous vehicles is compelling in principle. Human error is responsible for approximately ninety-four percent of traffic crashes in the United States, according to the National Highway Traffic Safety Administration. Autonomous systems do not become fatigued, distracted, or intoxicated, and they can process sensor data and react to hazards far faster than human drivers. However, translating this theoretical safety advantage into real-world performance has proven challenging. Autonomous vehicles must operate safely not only in routine driving conditions but also in rare, unpredictable scenarios — a child running into the road, unusual weather conditions, road construction — that are difficult to anticipate and programme for.

Ethical dilemmas present another layer of complexity. The so-called "trolley problem" — scenarios in which an autonomous vehicle must choose between two harmful outcomes, such as hitting a pedestrian or swerving to endanger its passengers — has generated extensive philosophical debate. While such extreme scenarios are rare in practice, they highlight the broader question of how autonomous vehicles should be programmed to prioritise safety among different road users and whether such programming decisions should be made by manufacturers, regulators, or society as a whole.

The economic implications of autonomous vehicles are potentially enormous. The trucking and taxi industries, which employ millions of people worldwide, would be fundamentally disrupted by widespread adoption of self-driving technology. Urban planning could be transformed as reduced car ownership and improved traffic flow diminish the need for parking infrastructure, freeing valuable urban land for other uses. Insurance models would need to shift from individual driver liability to product liability frameworks centred on vehicle manufacturers and software developers.

Regulatory frameworks for autonomous vehicles vary significantly across jurisdictions. Some countries and states have adopted permissive approaches, allowing extensive testing on public roads, while others have taken more cautious positions. The absence of harmonised international standards creates challenges for manufacturers seeking to deploy vehicles across multiple markets. As the technology matures, establishing comprehensive regulatory frameworks that balance innovation with public safety will be essential for the responsible deployment of autonomous vehicles.`,
      questions: [
        { number: 27, type: "true_false_not_given", text: "Most current commercial autonomous systems operate at Level 3 automation.", correctAnswer: "False", explanation: "The passage states 'most current commercial systems operate at Level 2'." },
        { number: 28, type: "true_false_not_given", text: "Human error causes approximately ninety-four percent of traffic crashes in the US.", correctAnswer: "True", explanation: "Directly stated in the passage." },
        { number: 29, type: "true_false_not_given", text: "Lidar sensors work by emitting radar waves.", correctAnswer: "False", explanation: "Lidar works by 'emitting millions of laser pulses per second', not radar waves." },
        { number: 30, type: "true_false_not_given", text: "Autonomous vehicles have been proven to be safer than human drivers in all conditions.", correctAnswer: "Not Given", explanation: "The passage describes the safety advantage as 'theoretical' and notes challenges in real-world performance." },
        { number: 31, type: "true_false_not_given", text: "All countries have adopted the same regulations for autonomous vehicles.", correctAnswer: "False", explanation: "The passage states 'regulatory frameworks vary significantly across jurisdictions'." },
        { number: 32, type: "true_false_not_given", text: "The trucking industry employs more people than the taxi industry globally.", correctAnswer: "Not Given", explanation: "The passage does not compare employment numbers between the two." },
        { number: 33, type: "flow_chart_completion", text: "The SAE defines ________ levels of driving automation, from Level 0 to Level 5.", correctAnswer: "six", explanation: "The passage states 'six levels of driving automation'." },
        { number: 34, type: "flow_chart_completion", text: "Level 2 systems provide adaptive cruise control and ________-keeping assistance.", correctAnswer: "lane", explanation: "The passage mentions 'lane-keeping assistance'." },
        { number: 35, type: "flow_chart_completion", text: "Lidar sensors create three-dimensional maps by emitting millions of ________ pulses per second.", correctAnswer: "laser", explanation: "The passage describes lidar 'emitting millions of laser pulses per second'." },
        { number: 36, type: "flow_chart_completion", text: "________ sensors detect the speed and distance of other vehicles in all weather conditions.", correctAnswer: "Radar", explanation: "The passage states 'Radar sensors detect the speed and distance'." },
        { number: 37, type: "sentence_completion", text: "The ethical dilemma known as the '________ problem' involves choosing between harmful outcomes.", correctAnswer: "trolley", explanation: "The passage discusses 'the so-called \"trolley problem\"'." },
        { number: 38, type: "sentence_completion", text: "Reduced car ownership could free valuable urban land currently used for ________ infrastructure.", correctAnswer: "parking", explanation: "The passage mentions 'diminish the need for parking infrastructure'." },
        { number: 39, type: "sentence_completion", text: "Insurance models would shift from individual driver liability to ________ liability frameworks.", correctAnswer: "product", explanation: "The passage states a shift to 'product liability frameworks'." },
        { number: 40, type: "sentence_completion", text: "Cameras help autonomous vehicles read traffic signs and detect traffic ________.", correctAnswer: "lights", explanation: "The passage mentions 'reading traffic signs, detecting traffic lights'." },
      ],
    },
  ],
};
