import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_28: ReadingTest = {
  id: 28,
  passages: [
    {
      title: "The Printing Press Revolution",
      text: `The invention of the printing press in fifteenth-century Europe is widely regarded as one of the most transformative events in human history, comparable in its impact to the development of writing itself. While printing technologies had existed in East Asia for centuries — the Chinese inventor Bi Sheng created movable type from baked clay around 1040 CE — it was the German goldsmith Johannes Gutenberg who devised the system that would revolutionise European society and, ultimately, the world.

Gutenberg's genius lay not in a single invention but in the integration of several technologies into a practical, scalable system. He developed a hand mould that allowed the rapid and precise casting of individual metal type characters from a durable alloy of lead, tin, and antimony. He adapted the screw press, previously used for pressing wine and olive oil, to apply even pressure across a flat printing surface. He formulated an oil-based ink that adhered reliably to metal type and transferred cleanly onto paper or vellum. Each component was essential; together they created a technology capable of producing books at speeds previously unimaginable.

Prior to Gutenberg, books in Europe were produced almost exclusively by hand, a laborious process dominated by monastic scriptoria. A skilled scribe might require months or even years to copy a single volume. Books were consequently rare, extraordinarily expensive, and accessible only to the wealthy, the clergy, and a handful of scholars. The average medieval European lived and died without ever encountering a book, much less reading one. Literacy was the preserve of a tiny elite, and the control of knowledge rested firmly in the hands of the Church and the aristocracy.

Gutenberg's printing press shattered this monopoly. His first major project, the Gutenberg Bible, printed around 1455, demonstrated the technology's potential: approximately 180 copies were produced in a fraction of the time that a single manuscript Bible would have required. Within decades, printing workshops spread across Europe with astonishing speed. By 1500, an estimated twenty million volumes had been printed in Europe — more books than had been produced in the entire preceding millennium. The cost of books plummeted, making written knowledge accessible to an increasingly broad audience.

The consequences were revolutionary. The Protestant Reformation, ignited by Martin Luther's Ninety-Five Theses in 1517, was amplified by the printing press, which enabled Luther's arguments to reach millions within weeks. The Scientific Revolution of the sixteenth and seventeenth centuries was similarly accelerated, as researchers could disseminate findings rapidly and build upon one another's work. The standardisation of texts reduced errors that accumulated through manual copying, improving the reliability of scientific, legal, and religious documents.

The printing press also catalysed the standardisation of languages. As printers chose particular dialects for their publications — often the dialect of commercially important regions — those dialects gained prestige and eventually evolved into national standard languages. English, French, German, and Italian all underwent this process, with printing playing a central role in the emergence of unified national identities.

Education expanded dramatically. The availability of affordable textbooks made formal schooling viable for broader segments of society, while printed pamphlets, newspapers, and almanacs created a public sphere in which ideas could be debated and disseminated. The Enlightenment of the eighteenth century, with its emphasis on reason, individual rights, and democratic governance, is difficult to imagine without the foundation laid by centuries of increasingly widespread literacy enabled by print.

Critics have noted, however, that the printing press was not an unqualified blessing. It facilitated the spread of propaganda, misinformation, and inflammatory rhetoric alongside legitimate knowledge. Witch-hunting manuals, anti-Semitic tracts, and political propaganda were printed and distributed as readily as works of science and philosophy. The technology itself was morally neutral; its impact depended entirely on how it was used.

The legacy of Gutenberg's invention endures in the digital age. The internet and social media have been described as the "new printing press," and the parallels are striking: both technologies democratised the production and distribution of information, both disrupted established power structures, and both generated profound cultural, political, and economic upheaval. Understanding the printing revolution of the fifteenth century offers valuable perspective on the information revolution of the twenty-first.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "What was Gutenberg's key contribution to printing technology?", options: ["A He invented movable type for the first time in history.", "B He integrated several technologies into a practical system.", "C He discovered a new method of papermaking.", "D He trained scribes to work more efficiently."], correctAnswer: "B", explanation: "The passage says 'Gutenberg's genius lay not in a single invention but in the integration of several technologies.'" },
        { number: 2, type: "multiple_choice", text: "How many volumes had been printed in Europe by 1500?", options: ["A Approximately two million", "B Approximately ten million", "C Approximately twenty million", "D Approximately fifty million"], correctAnswer: "C", explanation: "The passage states 'an estimated twenty million volumes had been printed in Europe.'" },
        { number: 3, type: "multiple_choice", text: "According to the passage, how did the printing press contribute to the Protestant Reformation?", options: ["A It allowed Luther to translate the Bible into German.", "B It enabled Luther's arguments to spread rapidly to millions.", "C It provided funding for Luther's church.", "D It replaced the handwritten papal decrees."], correctAnswer: "B", explanation: "The passage says the press 'enabled Luther's arguments to reach millions within weeks.'" },
        { number: 4, type: "multiple_choice", text: "What criticism of the printing press does the passage mention?", options: ["A It caused widespread unemployment among scribes.", "B It was too expensive for ordinary people.", "C It spread propaganda and misinformation alongside knowledge.", "D It favoured Latin over vernacular languages."], correctAnswer: "C", explanation: "The passage states 'It facilitated the spread of propaganda, misinformation, and inflammatory rhetoric.'" },
        { number: 5, type: "true_false_not_given", text: "Movable type was first invented in Europe by Gutenberg.", correctAnswer: "FALSE", explanation: "The passage states 'the Chinese inventor Bi Sheng created movable type from baked clay around 1040 CE.'" },
        { number: 6, type: "true_false_not_given", text: "Gutenberg used an alloy of lead, tin, and antimony to cast his type characters.", correctAnswer: "TRUE", explanation: "The passage states 'a durable alloy of lead, tin, and antimony.'" },
        { number: 7, type: "true_false_not_given", text: "The Gutenberg Bible was the first book ever printed.", correctAnswer: "NOT GIVEN", explanation: "The passage calls it Gutenberg's 'first major project' but does not claim it was the first book ever printed." },
        { number: 8, type: "true_false_not_given", text: "Approximately 180 copies of the Gutenberg Bible were produced.", correctAnswer: "TRUE", explanation: "The passage states 'approximately 180 copies were produced.'" },
        { number: 9, type: "true_false_not_given", text: "The printing press led directly to the abolition of monarchy in Europe.", correctAnswer: "NOT GIVEN", explanation: "The passage does not make this claim." },
        { number: 10, type: "true_false_not_given", text: "Gutenberg became extremely wealthy from his invention.", correctAnswer: "NOT GIVEN", explanation: "The passage does not discuss Gutenberg's personal financial outcome." },
        { number: 11, type: "true_false_not_given", text: "The printing press helped standardise European languages.", correctAnswer: "TRUE", explanation: "The passage states 'The printing press also catalysed the standardisation of languages.'" },
        { number: 12, type: "true_false_not_given", text: "Before the printing press, most Europeans had access to at least one book.", correctAnswer: "FALSE", explanation: "The passage says 'The average medieval European lived and died without ever encountering a book.'" },
        { number: 13, type: "true_false_not_given", text: "Bi Sheng's movable type was made from metal.", correctAnswer: "FALSE", explanation: "The passage states Bi Sheng 'created movable type from baked clay.'" },
      ],
    },
    {
      title: "Urban Heat Islands",
      text: `A. The urban heat island (UHI) effect is a well-documented climatic phenomenon in which cities experience significantly higher temperatures than their surrounding rural areas. Temperature differentials of two to five degrees Celsius are common, and in extreme cases, urban centres can be up to twelve degrees warmer than nearby countryside during calm, clear nights. As urbanisation continues to accelerate globally — with projections suggesting that nearly seventy per cent of the world's population will live in cities by 2050 — understanding and mitigating the UHI effect has become an urgent priority for public health, energy policy, and urban planning.

B. The causes of urban heat islands are multifaceted. The replacement of natural vegetation and permeable soil with impervious surfaces such as asphalt, concrete, and roofing materials fundamentally alters the thermal properties of the landscape. These materials absorb and store solar radiation far more efficiently than vegetation or soil, releasing accumulated heat slowly throughout the night — a process that prevents the nocturnal cooling that occurs naturally in rural environments. Dark-coloured surfaces, such as conventional asphalt roads, can reach temperatures of sixty to seventy degrees Celsius on a sunny summer day.

C. The geometry of urban areas compounds the problem. Tall buildings arranged in narrow street canyons trap reflected solar radiation through multiple reflections between surfaces, a process known as the canyon effect. These same structures block wind flow, reducing the convective cooling that ventilates open landscapes. Additionally, the waste heat generated by vehicles, air conditioning systems, industrial processes, and even human metabolism contributes to elevated urban temperatures. In dense cities during summer, anthropogenic heat can account for a substantial proportion of the total urban energy balance.

D. The health consequences of the UHI effect are serious and disproportionately affect vulnerable populations. Heat-related illnesses, including heat exhaustion, heatstroke, and cardiovascular complications, increase sharply during extreme heat events. The elderly, young children, outdoor workers, and people with pre-existing medical conditions are particularly at risk. Research has demonstrated that urban heat islands amplify the severity of heatwaves, contributing to excess mortality. During the devastating European heatwave of 2003, which claimed an estimated seventy thousand lives, urban populations suffered disproportionately compared with their rural counterparts.

E. Energy consumption rises in lockstep with urban temperatures. For every one-degree Celsius increase in summer temperatures, electricity demand for cooling rises by approximately two to four per cent. This increased demand strains electrical grids, raises energy costs for consumers, and drives additional fossil fuel combustion, which in turn generates more greenhouse gases and exacerbates climate change — creating a vicious feedback loop. The Lawrence Berkeley National Laboratory in the United States estimated that the UHI effect costs American cities approximately one billion dollars annually in additional energy expenditure.

F. A range of mitigation strategies has been developed to combat urban heat islands. Cool roofs, which use highly reflective materials to bounce solar radiation back into the atmosphere rather than absorbing it, can reduce roof surface temperatures by up to thirty degrees Celsius. Cool pavements employ similar reflective or permeable materials for roads and walkways. Green roofs — rooftops covered with soil and vegetation — provide insulation, absorb rainwater, and cool the surrounding air through evapotranspiration.

G. Urban forestry and the expansion of green spaces represent perhaps the most effective long-term strategy. Trees provide shade that directly reduces surface and air temperatures, while the process of evapotranspiration — in which plants absorb water through their roots and release it as vapour through their leaves — cools the ambient air in a manner analogous to natural air conditioning. Studies have shown that neighbourhoods with mature tree canopy cover can be three to five degrees cooler than treeless areas within the same city. Parks, green corridors, and urban wetlands further enhance cooling while delivering co-benefits for biodiversity, mental health, and air quality.

H. Integrated urban planning that considers thermal performance alongside traditional design criteria offers the most promising path forward. Cities including Singapore, Melbourne, and Medellín have implemented comprehensive heat mitigation plans that combine cool surfaces, urban greening, water features, and building design guidelines. As climate change drives temperatures higher worldwide, the importance of such strategies will only grow, making the management of urban heat islands a defining challenge of twenty-first-century urbanism.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Section A", options: ["I. Multiple factors creating elevated city temperatures", "II. The growing significance of urban overheating", "III. Structural characteristics that trap heat in cities", "IV. Health risks from excessive urban temperatures", "V. The economic cost of cooling overheated cities", "VI. Reflective and vegetative surface solutions", "VII. Trees and parks as natural cooling systems", "VIII. Comprehensive city-wide approaches to heat reduction"], correctAnswer: "II", explanation: "Section A introduces the UHI effect and its growing urgency." },
        { number: 15, type: "matching_headings", text: "Section B", options: ["I. Multiple factors creating elevated city temperatures", "II. The growing significance of urban overheating", "III. Structural characteristics that trap heat in cities", "IV. Health risks from excessive urban temperatures", "V. The economic cost of cooling overheated cities", "VI. Reflective and vegetative surface solutions", "VII. Trees and parks as natural cooling systems", "VIII. Comprehensive city-wide approaches to heat reduction"], correctAnswer: "I", explanation: "Section B discusses the various causes of UHI including surface materials." },
        { number: 16, type: "matching_headings", text: "Section C", options: ["I. Multiple factors creating elevated city temperatures", "II. The growing significance of urban overheating", "III. Structural characteristics that trap heat in cities", "IV. Health risks from excessive urban temperatures", "V. The economic cost of cooling overheated cities", "VI. Reflective and vegetative surface solutions", "VII. Trees and parks as natural cooling systems", "VIII. Comprehensive city-wide approaches to heat reduction"], correctAnswer: "III", explanation: "Section C discusses building geometry and the canyon effect." },
        { number: 17, type: "matching_headings", text: "Section D", options: ["I. Multiple factors creating elevated city temperatures", "II. The growing significance of urban overheating", "III. Structural characteristics that trap heat in cities", "IV. Health risks from excessive urban temperatures", "V. The economic cost of cooling overheated cities", "VI. Reflective and vegetative surface solutions", "VII. Trees and parks as natural cooling systems", "VIII. Comprehensive city-wide approaches to heat reduction"], correctAnswer: "IV", explanation: "Section D discusses health consequences of UHI." },
        { number: 18, type: "matching_headings", text: "Section E", options: ["I. Multiple factors creating elevated city temperatures", "II. The growing significance of urban overheating", "III. Structural characteristics that trap heat in cities", "IV. Health risks from excessive urban temperatures", "V. The economic cost of cooling overheated cities", "VI. Reflective and vegetative surface solutions", "VII. Trees and parks as natural cooling systems", "VIII. Comprehensive city-wide approaches to heat reduction"], correctAnswer: "V", explanation: "Section E discusses energy consumption and costs." },
        { number: 19, type: "matching_headings", text: "Section G", options: ["I. Multiple factors creating elevated city temperatures", "II. The growing significance of urban overheating", "III. Structural characteristics that trap heat in cities", "IV. Health risks from excessive urban temperatures", "V. The economic cost of cooling overheated cities", "VI. Reflective and vegetative surface solutions", "VII. Trees and parks as natural cooling systems", "VIII. Comprehensive city-wide approaches to heat reduction"], correctAnswer: "VII", explanation: "Section G discusses trees, evapotranspiration, and green spaces." },
        { number: 20, type: "summary_completion", text: "Urban areas can be up to __(20)__ degrees warmer than rural areas during calm, clear nights.", correctAnswer: "twelve", explanation: "The passage states 'up to twelve degrees warmer.'" },
        { number: 21, type: "summary_completion", text: "Dark asphalt roads can reach surface temperatures of __(21)__ to seventy degrees Celsius.", correctAnswer: "sixty", explanation: "The passage states 'sixty to seventy degrees Celsius.'" },
        { number: 22, type: "summary_completion", text: "The European heatwave of 2003 claimed an estimated __(22)__ thousand lives.", correctAnswer: "seventy", explanation: "The passage states 'an estimated seventy thousand lives.'" },
        { number: 23, type: "summary_completion", text: "Cool roofs can reduce roof surface temperatures by up to __(23)__ degrees Celsius.", correctAnswer: "thirty", explanation: "The passage states 'reduce roof surface temperatures by up to thirty degrees Celsius.'" },
        { number: 24, type: "summary_completion", text: "The UHI effect costs American cities approximately one __(24)__ dollars annually.", correctAnswer: "billion", explanation: "The passage states 'approximately one billion dollars annually.'" },
        { number: 25, type: "summary_completion", text: "Neighbourhoods with mature tree cover can be __(25)__ to five degrees cooler than treeless areas.", correctAnswer: "three", explanation: "The passage states 'three to five degrees cooler.'" },
        { number: 26, type: "summary_completion", text: "The process by which plants release water vapour through their leaves is called __(26)__.", correctAnswer: "evapotranspiration", explanation: "The passage defines this process as 'evapotranspiration.'" },
      ],
    },
    {
      title: "AI in Education",
      text: `The integration of artificial intelligence into education represents a paradigm shift in how knowledge is delivered, assessed, and personalised. From adaptive learning platforms that tailor content to individual students' needs to AI-powered assessment tools that provide instant feedback, the technology is reshaping classrooms and lecture halls worldwide. Yet the deployment of AI in education also raises profound questions about equity, privacy, the role of teachers, and the very purpose of learning.

A. Adaptive learning systems represent perhaps the most mature application of AI in education. These platforms use machine learning algorithms to analyse student performance data in real time, identifying knowledge gaps, predicting areas of difficulty, and adjusting the sequence, pace, and difficulty of instructional content accordingly. A student struggling with algebraic equations, for example, might receive additional practice problems, alternative explanations, and targeted hints, while a peer who has mastered the concept advances to more challenging material. Research conducted by the Bill & Melinda Gates Foundation found that students using adaptive platforms demonstrated learning gains equivalent to approximately two additional months of instruction per academic year compared with peers in traditional classrooms.

B. Automated assessment and feedback constitute another rapidly expanding application. Natural language processing (NLP) algorithms can now evaluate written essays with reasonable accuracy, assessing coherence, argumentation, vocabulary, and grammatical correctness. Systems such as Turnitin's Feedback Studio and Educational Testing Service's e-rater are used by millions of students globally. While these tools cannot fully replicate the nuanced judgement of an experienced human marker — particularly in evaluating creativity, originality, and critical thinking — they provide valuable formative feedback that helps students improve their writing iteratively without waiting days or weeks for teacher responses.

C. AI-powered tutoring systems, sometimes called intelligent tutoring systems (ITS), aim to replicate the benefits of one-on-one human tutoring at scale. Carnegie Learning's MATHia platform, for instance, models each student's cognitive state and provides personalised guidance through mathematical problem-solving processes. Research by the RAND Corporation found that students using ITS in mathematics outperformed control groups by a statistically significant margin, though the effect sizes varied depending on implementation quality and teacher support.

D. Language learning has been transformed by AI applications. Platforms such as Duolingo employ machine learning to optimise vocabulary review schedules using spaced repetition algorithms, adapt lesson difficulty to individual performance, and generate realistic conversational practice through AI chatbots. Speech recognition technology enables pronunciation assessment and correction, providing learners with feedback that was previously available only from human instructors. The democratisation of language learning through AI-powered applications has enabled millions of people in developing countries to access instruction in English and other languages at minimal cost.

E. The use of AI in education raises significant ethical concerns. Student data privacy is paramount: adaptive learning systems collect vast quantities of information about learners' performance, behaviour, and even emotional states, creating detailed digital profiles that could be misused. The European Union's General Data Protection Regulation (GDPR) and the United States' Family Educational Rights and Privacy Act (FERPA) provide frameworks for data protection, but enforcement remains inconsistent, and many AI education products operate in regulatory grey areas.

F. Algorithmic bias presents another challenge. If the data used to train AI educational systems reflects existing inequalities — for example, if training datasets underrepresent certain demographic groups — the resulting algorithms may perpetuate or amplify those inequalities. Students from disadvantaged backgrounds, non-native speakers, and those with learning disabilities may receive less effective instruction if AI systems are not carefully designed and validated across diverse populations.

G. The impact of AI on the teaching profession itself is a subject of intense debate. Optimists argue that AI will liberate teachers from routine tasks — grading, attendance tracking, content delivery — freeing them to focus on mentoring, creative instruction, and the social-emotional development of students. Sceptics warn that cost-conscious administrators may use AI as a justification for reducing teaching staff, degrading the human relationships that are central to effective education. The reality will likely depend on policy decisions and institutional cultures rather than the technology itself.

H. Looking ahead, the convergence of AI with other technologies — virtual reality, augmented reality, and brain-computer interfaces — promises even more dramatic transformations. Immersive virtual environments could enable students to explore historical events, conduct virtual science experiments, or practice surgical procedures in safe, controlled settings. While such applications remain largely experimental, they suggest that the relationship between AI and education will continue to evolve in ways that are difficult to predict but impossible to ignore.`,
      questions: [
        { number: 27, type: "matching_information", text: "An example of AI being used to assess student essays", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "B", explanation: "Section B discusses NLP algorithms evaluating written essays and mentions Turnitin and e-rater." },
        { number: 28, type: "matching_information", text: "A discussion of how AI might affect teacher employment", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "G", explanation: "Section G discusses the debate about AI's impact on the teaching profession." },
        { number: 29, type: "matching_information", text: "Evidence that adaptive learning produces measurable academic improvement", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "A", explanation: "Section A cites the Gates Foundation finding of two additional months of learning gains." },
        { number: 30, type: "matching_information", text: "Concerns about discrimination in AI training data", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "F", explanation: "Section F discusses algorithmic bias and underrepresentation of demographic groups." },
        { number: 31, type: "matching_information", text: "The use of virtual environments for educational purposes", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "H", explanation: "Section H discusses VR, AR, and immersive virtual environments for education." },
        { number: 32, type: "matching_information", text: "Legal frameworks governing student data collection", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "E", explanation: "Section E discusses GDPR and FERPA." },
        { number: 33, type: "sentence_completion", text: "Adaptive learning platforms demonstrated gains equivalent to approximately __(33)__ additional months of instruction.", correctAnswer: "two", explanation: "The passage states 'approximately two additional months of instruction per academic year.'" },
        { number: 34, type: "sentence_completion", text: "Carnegie Learning's __(34)__ platform provides personalised mathematics tutoring.", correctAnswer: "MATHia", explanation: "The passage names 'Carnegie Learning's MATHia platform.'" },
        { number: 35, type: "sentence_completion", text: "Duolingo uses spaced __(35)__ algorithms to optimise vocabulary review.", correctAnswer: "repetition", explanation: "The passage mentions 'spaced repetition algorithms.'" },
        { number: 36, type: "sentence_completion", text: "The RAND Corporation found that students using ITS outperformed control groups by a statistically __(36)__ margin.", correctAnswer: "significant", explanation: "The passage states 'a statistically significant margin.'" },
        { number: 37, type: "sentence_completion", text: "AI systems collect detailed digital __(37)__ about learners that could be misused.", correctAnswer: "profiles", explanation: "The passage mentions 'creating detailed digital profiles that could be misused.'" },
        { number: 38, type: "sentence_completion", text: "The European Union's data protection regulation is known by the abbreviation __(38)__.", correctAnswer: "GDPR", explanation: "The passage refers to 'the European Union's General Data Protection Regulation (GDPR).'" },
        { number: 39, type: "sentence_completion", text: "ITS stands for intelligent __(39)__ systems.", correctAnswer: "tutoring", explanation: "The passage defines ITS as 'intelligent tutoring systems.'" },
        { number: 40, type: "sentence_completion", text: "Brain-computer __(40)__ are mentioned as a future technology converging with AI in education.", correctAnswer: "interfaces", explanation: "The passage mentions 'brain-computer interfaces.'" },
      ],
    },
  ],
};
