import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_59: ReadingTest = {
  id: 59,
  passages: [
    {
      title: "The History of the Tortoise",
      text: `The tortoise is one of the most ancient and enduring creatures on Earth, with a lineage stretching back over 200 million years to the Triassic period — a time when dinosaurs were just beginning to dominate the planet. Unlike many of their contemporaries, tortoises and their close relatives, the turtles, survived the mass extinction event that wiped out the non-avian dinosaurs approximately 66 million years ago and have persisted through dramatic shifts in climate, geography, and ecology to become one of the most widely distributed groups of reptiles alive today. The study of tortoises offers insights into evolution, longevity, conservation, and humanity's complex and often troubled relationship with the natural world.

Tortoises belong to the order Testudines and the family Testudinidae, which comprises approximately 49 living species distributed across every continent except Antarctica and Australia. They are distinguished from other turtles by their exclusively terrestrial habits — unlike sea turtles and freshwater turtles, tortoises live entirely on land — and by their characteristically high-domed shells, sturdy columnar legs, and herbivorous diets. The tortoise shell, composed of approximately 60 bones fused together and covered by plates called scutes made of keratin (the same protein found in human fingernails), is one of the most remarkable defensive structures in the animal kingdom. Unlike the popular misconception, a tortoise cannot leave its shell — the shell is an integral part of its skeleton, fused to the spine and ribcage.

The giant tortoises of the Galápagos Islands and the Aldabra Atoll in the Indian Ocean are the most famous members of the family and among the most iconic animals in the world. Galápagos giant tortoises can weigh over 400 kilograms and live for more than 100 years, with some individuals estimated to have reached ages exceeding 175 years. Charles Darwin's observations of the distinct shell shapes of giant tortoises on different Galápagos islands — some with dome-shaped shells adapted to grazing on low vegetation, others with saddle-shaped shells that allowed them to reach higher plants — contributed to the development of his theory of evolution by natural selection. The Aldabra giant tortoise, native to the Aldabra Atoll in the Seychelles, is similarly long-lived and can weigh up to 250 kilograms. One famous individual, Adwaita, an Aldabra tortoise that lived at the Alipore Zoological Gardens in Kolkata, India, reportedly reached an age of approximately 255 years before dying in 2006, though this estimate has not been independently verified.

Tortoises are remarkably well adapted for survival. Their slow metabolism enables them to survive for long periods without food or water — desert-dwelling species such as the Mojave desert tortoise can store water in their bladders and survive for up to a year without drinking. Their shells provide exceptional protection against predators, and their low energy requirements mean that they can thrive in environments too harsh or resource-poor for many other vertebrates. Tortoises are ectothermic (cold-blooded), regulating their body temperature through behavioural thermoregulation — basking in the sun to warm up and retreating to shade or burrows to cool down.

Despite their remarkable adaptations, tortoises are among the most threatened groups of vertebrates on the planet. According to the International Union for Conservation of Nature (IUCN), more than half of all tortoise species are classified as threatened with extinction. The primary threats include habitat destruction caused by agriculture, urbanisation, and infrastructure development; illegal collection for the pet trade and traditional medicine; predation by introduced species such as rats, pigs, and dogs, which destroy eggs and kill juveniles; and climate change, which is altering the temperature-dependent sex determination of many tortoise species — a mechanism in which the temperature of the nest during incubation determines whether hatchlings develop as male or female.

Conservation efforts for tortoises have achieved notable successes. The Galápagos giant tortoise population, which had declined from an estimated 250,000 in the sixteenth century to approximately 3,000 by the 1970s due to hunting, habitat destruction, and predation by introduced animals, has recovered to approximately 20,000 to 25,000 individuals through captive breeding programmes, habitat restoration, and the removal of invasive species. The most famous conservation success story involves Lonesome George, the last known individual of the Pinta Island tortoise subspecies, who lived at the Charles Darwin Research Station on the Galápagos from 1972 until his death in 2012. Although efforts to breed George were unsuccessful and his subspecies is now considered extinct, his story focused global attention on tortoise conservation and the broader biodiversity crisis. Today, organisations such as the Turtle Survival Alliance and the Galápagos Conservancy continue to work to protect tortoise species and their habitats around the world.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "How old is the tortoise lineage according to the passage?", options: ["A. Approximately 66 million years", "B. Approximately 100 million years", "C. Over 200 million years", "D. Over 300 million years"], correctAnswer: "C", explanation: "The passage says 'a lineage stretching back over 200 million years.'" },
        { number: 2, type: "multiple_choice", text: "How many living tortoise species exist?", options: ["A. Approximately 29", "B. Approximately 39", "C. Approximately 49", "D. Approximately 69"], correctAnswer: "C", explanation: "The passage says 'approximately 49 living species.'" },
        { number: 3, type: "multiple_choice", text: "What contributed to Darwin's theory of evolution?", options: ["A. The diet of marine iguanas", "B. The distinct shell shapes of tortoises on different islands", "C. The colour patterns on tortoise shells", "D. The migration patterns of sea turtles"], correctAnswer: "B", explanation: "The passage says Darwin observed 'the distinct shell shapes of giant tortoises on different Galápagos islands.'" },
        { number: 4, type: "multiple_choice", text: "What mechanism determines the sex of tortoise hatchlings?", options: ["A. Genetic determination at fertilisation", "B. The size of the egg", "C. Temperature of the nest during incubation", "D. The diet of the mother"], correctAnswer: "C", explanation: "The passage says 'temperature-dependent sex determination' where 'the temperature of the nest during incubation determines whether hatchlings develop as male or female.'" },
        { number: 5, type: "true_false_not_given", text: "A tortoise can leave its shell if threatened.", correctAnswer: "FALSE", explanation: "The passage says 'a tortoise cannot leave its shell — the shell is an integral part of its skeleton.'" },
        { number: 6, type: "true_false_not_given", text: "Galápagos giant tortoises can weigh over 400 kilograms.", correctAnswer: "TRUE", explanation: "The passage says 'can weigh over 400 kilograms.'" },
        { number: 7, type: "true_false_not_given", text: "Adwaita's age of 255 years has been independently verified.", correctAnswer: "FALSE", explanation: "The passage says 'this estimate has not been independently verified.'" },
        { number: 8, type: "true_false_not_given", text: "The Mojave desert tortoise can survive for up to a year without drinking.", correctAnswer: "TRUE", explanation: "The passage says 'survive for up to a year without drinking.'" },
        { number: 9, type: "true_false_not_given", text: "More than 75 percent of tortoise species are threatened with extinction.", correctAnswer: "FALSE", explanation: "The passage says 'more than half' — not 75 percent." },
        { number: 10, type: "true_false_not_given", text: "Lonesome George successfully bred before his death.", correctAnswer: "FALSE", explanation: "The passage says 'efforts to breed George were unsuccessful.'" },
        { number: 11, type: "true_false_not_given", text: "Tortoises are found on every continent.", correctAnswer: "FALSE", explanation: "The passage says they are found 'across every continent except Antarctica and Australia.'" },
        { number: 12, type: "true_false_not_given", text: "The tortoise shell is made up of approximately 60 bones.", correctAnswer: "TRUE", explanation: "The passage says 'composed of approximately 60 bones fused together.'" },
        { number: 13, type: "true_false_not_given", text: "The Galápagos population has recovered to over 30,000 individuals.", correctAnswer: "FALSE", explanation: "The passage says 'approximately 20,000 to 25,000 individuals.'" },
      ],
    },
    {
      title: "Tea and the Industrial Revolution",
      text: `A. Tea is one of the most widely consumed beverages in the world, drunk by billions of people in an extraordinary variety of cultures and traditions. Yet tea's significance extends far beyond its role as a daily refreshment. Historians have increasingly recognised that tea played a pivotal role in one of the most transformative events in human history — the Industrial Revolution — by contributing to public health, labour productivity, social organisation, and international trade in ways that helped to create the modern industrialised world.

B. The story of tea's arrival in Britain begins in the seventeenth century. Portuguese and Dutch traders were among the first Europeans to encounter tea in East Asia, and the Portuguese princess Catherine of Braganza is credited with popularising tea drinking at the English court after her marriage to King Charles II in 1662. Initially an expensive luxury consumed exclusively by the aristocracy, tea gradually became more affordable as trade volumes increased and the British East India Company established a dominant position in the tea trade during the eighteenth century. By the late 1700s, tea had become the national drink of Britain, consumed by all social classes, from wealthy landowners to factory workers and domestic servants.

C. The relationship between tea and the Industrial Revolution is most clearly visible in the domain of public health. Before tea became widely available, the primary beverages consumed by the working classes in Britain were beer and ale — partly because fermented drinks were safer than the contaminated water available in most towns and cities, which was frequently polluted by human and animal waste. Tea required boiling water, which effectively killed waterborne pathogens such as cholera, typhoid, and dysentery, even though the scientific basis for this effect was not understood until the germ theory of disease was established by Louis Pasteur and Robert Koch in the late nineteenth century. The widespread adoption of tea drinking therefore contributed to a significant reduction in waterborne disease among the urban population, improving overall health, reducing mortality rates, and increasing the productive capacity of the labour force.

D. Tea also provided a direct physiological stimulus to industrial productivity. Caffeine, the principal active compound in tea, is a central nervous system stimulant that enhances alertness, concentration, and endurance — precisely the cognitive and physical qualities demanded by the long, repetitive, and often monotonous work of early industrial factories. Historians have noted that tea breaks became an institutionalised feature of factory life in Britain during the nineteenth century, providing workers with both a stimulant and a moment of rest that helped to sustain attention and productivity over shifts that frequently lasted twelve to fourteen hours. The sugar that was commonly added to tea provided an additional source of quick-release energy, complementing the calories from workers' often meagre and nutritionally inadequate diets.

E. The economic dimensions of the tea trade were immense and had profound geopolitical consequences. Britain's enormous appetite for tea created a massive trade deficit with China, which was the world's sole source of tea until the mid-nineteenth century. The Chinese government demanded payment in silver, draining British reserves and creating a persistent balance-of-payments problem. To reverse this imbalance, the British East India Company began exporting opium grown in British India to China — a trade that the Chinese government attempted to suppress, leading to the Opium Wars of 1839–1842 and 1856–1860. Britain's military victories in these conflicts forced China to open its ports to foreign trade, cede Hong Kong, and accept the continued importation of opium — events that profoundly shaped the political and economic trajectory of both nations and contributed to what Chinese historians call the "Century of Humiliation."

F. The British eventually broke China's monopoly on tea production by smuggling tea plants and seeds out of China and establishing large-scale tea plantations in India and Ceylon (present-day Sri Lanka) in the mid-nineteenth century. Robert Fortune, a Scottish botanist employed by the East India Company, made a series of covert journeys into China's tea-growing regions in the late 1840s and early 1850s, disguising himself as a Chinese merchant and collecting thousands of tea plants, seeds, and detailed knowledge of cultivation and processing techniques. The establishment of tea plantations in Assam, Darjeeling, and Ceylon transformed the global tea industry, shifting production from China to the British Empire and creating new agricultural economies that persist to this day. By 1900, India had surpassed China as the world's largest tea producer, and the British Empire controlled the majority of global tea production and trade.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Paragraph B", options: ["i. Tea's arrival and spread in Britain", "ii. How tea improved workers' health", "iii. The caffeine advantage for factory workers", "iv. Breaking China's tea monopoly", "v. War and the global tea trade", "vi. Tea's cultural significance worldwide", "vii. The economic cost of tea imports", "viii. Modern tea consumption patterns"], correctAnswer: "i", explanation: "Paragraph B traces tea's journey from Portuguese traders to becoming Britain's national drink." },
        { number: 15, type: "matching_headings", text: "Paragraph C", options: ["i. Tea's arrival and spread in Britain", "ii. How tea improved workers' health", "iii. The caffeine advantage for factory workers", "iv. Breaking China's tea monopoly", "v. War and the global tea trade", "vi. Tea's cultural significance worldwide", "vii. The economic cost of tea imports", "viii. Modern tea consumption patterns"], correctAnswer: "ii", explanation: "Paragraph C explains how boiling water for tea reduced waterborne disease." },
        { number: 16, type: "matching_headings", text: "Paragraph D", options: ["i. Tea's arrival and spread in Britain", "ii. How tea improved workers' health", "iii. The caffeine advantage for factory workers", "iv. Breaking China's tea monopoly", "v. War and the global tea trade", "vi. Tea's cultural significance worldwide", "vii. The economic cost of tea imports", "viii. Modern tea consumption patterns"], correctAnswer: "iii", explanation: "Paragraph D discusses caffeine's effects on alertness and industrial productivity." },
        { number: 17, type: "matching_headings", text: "Paragraph E", options: ["i. Tea's arrival and spread in Britain", "ii. How tea improved workers' health", "iii. The caffeine advantage for factory workers", "iv. Breaking China's tea monopoly", "v. War and the global tea trade", "vi. Tea's cultural significance worldwide", "vii. The economic cost of tea imports", "viii. Modern tea consumption patterns"], correctAnswer: "v", explanation: "Paragraph E discusses the Opium Wars caused by the tea trade imbalance." },
        { number: 18, type: "matching_headings", text: "Paragraph F", options: ["i. Tea's arrival and spread in Britain", "ii. How tea improved workers' health", "iii. The caffeine advantage for factory workers", "iv. Breaking China's tea monopoly", "v. War and the global tea trade", "vi. Tea's cultural significance worldwide", "vii. The economic cost of tea imports", "viii. Modern tea consumption patterns"], correctAnswer: "iv", explanation: "Paragraph F describes how Robert Fortune smuggled tea plants and established Indian plantations." },
        { number: 19, type: "table_completion", text: "Catherine of Braganza married King Charles II in _______.", correctAnswer: "1662", explanation: "The passage says 'her marriage to King Charles II in 1662.'" },
        { number: 20, type: "table_completion", text: "The first Opium War took place from 1839 to _______.", correctAnswer: "1842", explanation: "The passage says 'the Opium Wars of 1839–1842.'" },
        { number: 21, type: "table_completion", text: "Robert Fortune disguised himself as a _______ merchant.", correctAnswer: "Chinese", explanation: "The passage says 'disguising himself as a Chinese merchant.'" },
        { number: 22, type: "table_completion", text: "Tea plantations were established in Assam, Darjeeling, and _______.", correctAnswer: "Ceylon", explanation: "The passage says 'Assam, Darjeeling, and Ceylon.'" },
        { number: 23, type: "table_completion", text: "By 1900, _______ had surpassed China as the world's largest tea producer.", correctAnswer: "India", explanation: "The passage says 'India had surpassed China.'" },
        { number: 24, type: "table_completion", text: "Factory shifts in early industrial Britain frequently lasted _______ to fourteen hours.", correctAnswer: "twelve", explanation: "The passage says 'shifts that frequently lasted twelve to fourteen hours.'" },
        { number: 25, type: "table_completion", text: "Germ theory of disease was established by Louis Pasteur and Robert _______.", correctAnswer: "Koch", explanation: "The passage says 'Louis Pasteur and Robert Koch.'" },
        { number: 26, type: "table_completion", text: "The _______ East India Company dominated the tea trade.", correctAnswer: "British", explanation: "The passage says 'the British East India Company.'" },
      ],
    },
    {
      title: "Serendipity: The Accidental Scientists",
      text: `Some of the most important discoveries in the history of science have been made not through deliberate, systematic research but through chance, accident, and the fortunate intersection of preparation and opportunity — a phenomenon commonly known as serendipity. The word itself was coined in 1754 by the English writer Horace Walpole, who derived it from a Persian fairy tale called "The Three Princes of Serendip," in which the protagonists "were always making discoveries, by accidents and sagacity, of things which they were not in quest of." Scientific serendipity reminds us that discovery is often unpredictable and that the capacity to recognise the significance of an unexpected observation is as important as the ability to design and execute a controlled experiment.

Perhaps the most famous example of scientific serendipity is Alexander Fleming's discovery of penicillin in 1928. Fleming, a Scottish bacteriologist working at St Mary's Hospital in London, returned from a holiday to find that a culture plate of Staphylococcus bacteria had been contaminated by a mould — later identified as Penicillium notatum. Rather than discarding the contaminated plate, Fleming noticed that the bacteria surrounding the mould had been killed, forming a clear zone of inhibition. He recognised the potential significance of this observation and published his findings, though it was not until the 1940s that Howard Florey and Ernst Chain at the University of Oxford developed methods for mass-producing penicillin, transforming it into the world's first widely available antibiotic and saving millions of lives during and after World War II. Fleming, Florey, and Chain shared the Nobel Prize in Physiology or Medicine in 1945.

Wilhelm Röntgen's discovery of X-rays in 1895 was similarly accidental. Röntgen, a German physicist, was experimenting with cathode rays in his laboratory at the University of Würzburg when he noticed that a fluorescent screen across the room was glowing, even though it was shielded from direct exposure to the cathode ray tube. Investigating further, Röntgen discovered that a previously unknown type of radiation — which he called "X-rays" because of their mysterious nature — was passing through solid objects and causing the screen to fluoresce. Within weeks, Röntgen had produced the first X-ray image of the human body — a photograph of his wife's hand showing the bones and her wedding ring — and his discovery revolutionised medical diagnostics forever. Röntgen received the first Nobel Prize in Physics in 1901.

The discovery of the microwave oven is a more recent example of serendipity in action. In 1945, Percy Spencer, an American engineer working for the Raytheon Corporation, was testing a magnetron — a device that generates microwave radiation for radar systems — when he noticed that a chocolate bar in his pocket had melted. Intrigued, Spencer placed popcorn kernels near the magnetron and watched as they popped. He then experimented with an egg, which promptly exploded. Spencer recognised the cooking potential of microwave radiation and worked with Raytheon to develop the first commercial microwave oven, the Radarange, which was introduced in 1947. Early models were nearly six feet tall, weighed over 300 kilograms, and cost approximately $5,000 — equivalent to over $60,000 today. It was not until the 1960s and 1970s that technological improvements and cost reductions made microwave ovens affordable for household use, and today they are found in approximately 90 percent of American kitchens.

Viagra, one of the best-selling pharmaceutical products in history, is another product of serendipity. In the late 1980s, researchers at the pharmaceutical company Pfizer were conducting clinical trials of a compound called sildenafil citrate as a potential treatment for angina pectoris — chest pain caused by reduced blood flow to the heart. The drug proved disappointing as an angina treatment but produced an unexpected side effect: male trial participants reported sustained improvements in erectile function. Pfizer pivoted its research programme, conducted new clinical trials, and in 1998 received approval from the US Food and Drug Administration to market sildenafil under the brand name Viagra as a treatment for erectile dysfunction. The drug generated over $1.9 billion in global sales in its peak year and has been prescribed to tens of millions of men worldwide.

The recurring pattern in these and many other cases of scientific serendipity is not pure luck but what the French scientist Louis Pasteur described as "chance favouring the prepared mind." Fleming's training as a bacteriologist enabled him to recognise the significance of a contaminated culture plate. Röntgen's expertise in physics equipped him to investigate the mysterious glow on a fluorescent screen. Spencer's knowledge of engineering led him to connect the melted chocolate bar with the microwave radiation from the magnetron. In each case, the accidental observation was the catalyst, but the scientist's expertise, curiosity, and willingness to pursue the unexpected were essential for transforming an accident into a world-changing discovery. As the history of science demonstrates repeatedly, the most important discoveries are often the ones that nobody planned to make.`,
      questions: [
        { number: 27, type: "matching_information", text: "A description of a discovery made while testing radar equipment", options: ["Paragraph 1", "Paragraph 2", "Paragraph 3", "Paragraph 4", "Paragraph 5", "Paragraph 6"], correctAnswer: "Paragraph 4", explanation: "Paragraph 4 describes Percy Spencer's microwave oven discovery while testing a magnetron for radar." },
        { number: 28, type: "matching_information", text: "The origin of the word 'serendipity'", options: ["Paragraph 1", "Paragraph 2", "Paragraph 3", "Paragraph 4", "Paragraph 5", "Paragraph 6"], correctAnswer: "Paragraph 1", explanation: "Paragraph 1 explains Horace Walpole coined the word in 1754 from a Persian fairy tale." },
        { number: 29, type: "matching_information", text: "A drug that was originally developed for a different medical condition", options: ["Paragraph 1", "Paragraph 2", "Paragraph 3", "Paragraph 4", "Paragraph 5", "Paragraph 6"], correctAnswer: "Paragraph 5", explanation: "Paragraph 5 describes Viagra being developed originally for angina." },
        { number: 30, type: "matching_information", text: "A Pasteur quote about the nature of discovery", options: ["Paragraph 1", "Paragraph 2", "Paragraph 3", "Paragraph 4", "Paragraph 5", "Paragraph 6"], correctAnswer: "Paragraph 6", explanation: "Paragraph 6 contains Pasteur's quote about 'chance favouring the prepared mind.'" },
        { number: 31, type: "matching_information", text: "How a contaminated laboratory plate led to a life-saving medicine", options: ["Paragraph 1", "Paragraph 2", "Paragraph 3", "Paragraph 4", "Paragraph 5", "Paragraph 6"], correctAnswer: "Paragraph 2", explanation: "Paragraph 2 describes Fleming's discovery of penicillin from a contaminated plate." },
        { number: 32, type: "flow_chart_completion", text: "Fleming returned from holiday and found a plate contaminated by a _______ identified as Penicillium notatum.", correctAnswer: "mould", explanation: "The passage says 'a culture plate had been contaminated by a mould — later identified as Penicillium notatum.'" },
        { number: 33, type: "flow_chart_completion", text: "Bacteria surrounding the mould had been killed, forming a clear zone of _______.", correctAnswer: "inhibition", explanation: "The passage says 'forming a clear zone of inhibition.'" },
        { number: 34, type: "flow_chart_completion", text: "Florey and Chain at the University of _______ developed methods for mass-producing penicillin.", correctAnswer: "Oxford", explanation: "The passage says 'Howard Florey and Ernst Chain at the University of Oxford.'" },
        { number: 35, type: "flow_chart_completion", text: "Röntgen noticed a _______ screen glowing across the room despite being shielded.", correctAnswer: "fluorescent", explanation: "The passage says 'a fluorescent screen across the room was glowing.'" },
        { number: 36, type: "sentence_completion", text: "Horace Walpole coined the word serendipity in _______.", correctAnswer: "1754", explanation: "The passage says 'coined in 1754.'" },
        { number: 37, type: "sentence_completion", text: "Röntgen received the first Nobel Prize in _______ in 1901.", correctAnswer: "Physics", explanation: "The passage says 'the first Nobel Prize in Physics in 1901.'" },
        { number: 38, type: "sentence_completion", text: "The first commercial microwave oven was called the _______.", correctAnswer: "Radarange", explanation: "The passage says 'the Radarange, which was introduced in 1947.'" },
        { number: 39, type: "sentence_completion", text: "Viagra was approved by the FDA in _______.", correctAnswer: "1998", explanation: "The passage says 'in 1998 received approval.'" },
        { number: 40, type: "sentence_completion", text: "Viagra generated over $_______ billion in global sales in its peak year.", correctAnswer: "1.9", explanation: "The passage says 'over $1.9 billion in global sales in its peak year.'" },
      ],
    },
  ],
};
