import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_56: ReadingTest = {
  id: 56,
  passages: [
    {
      title: "The Psychology of Color",
      text: `Colour is so deeply embedded in human experience that most people rarely pause to consider its profound influence on thought, emotion, and behaviour. Yet scientific research over the past century has revealed that colour perception is far more than a passive sensory process — it actively shapes mood, decision-making, consumer behaviour, and even physical performance. The psychology of colour, a field that bridges neuroscience, marketing, design, and clinical psychology, has become one of the most practically influential areas of behavioural research.

The human eye can distinguish approximately ten million different colours, thanks to three types of cone cells in the retina that respond to short (blue), medium (green), and long (red) wavelengths of light. Signals from these cones are processed in the visual cortex and integrated with information from memory, context, and emotion to produce the subjective experience of colour. This processing is not purely objective: cultural associations, personal experiences, and even language can influence how a colour is perceived and what emotions it evokes.

Red is perhaps the most extensively studied colour in psychological research. Studies have consistently found that red increases physiological arousal — raising heart rate, blood pressure, and skin conductance — and is associated with urgency, danger, passion, and dominance. In competitive sports, a landmark 2005 study published in Nature found that contestants wearing red won significantly more bouts in combat sports at the Athens Olympics than those wearing blue, even after controlling for skill level. The researchers hypothesised that red may signal dominance and aggression, subtly intimidating opponents. In consumer contexts, red is widely used to convey urgency and stimulate impulse purchasing: sale signs, clearance banners, and fast-food logos frequently employ red for this reason.

Blue, by contrast, is generally associated with calmness, trust, and intellectual focus. Research has shown that blue environments can lower heart rate and blood pressure and promote creative thinking. A 2009 study at the University of British Columbia found that participants performing creative tasks in blue-coloured environments generated twice as many creative outputs as those in red environments, while red-environment participants performed better on tasks requiring attention to detail. These findings suggest that colour affects not just mood but the type of cognitive processing people engage in.

Green is strongly associated with nature, health, and restoration. Environmental psychologists have documented the "green effect" — the phenomenon whereby exposure to green natural environments reduces stress, improves mood, and enhances cognitive function. Hospital patients with views of green spaces have been shown to recover faster and require less pain medication than those with views of buildings or walls. In marketing, green is extensively used to signal environmental friendliness, organic production, and health-conscious products. However, research suggests that consumers are becoming increasingly sceptical of "greenwashing" — the practice of using green imagery to imply environmental credentials that products do not genuinely possess.

Yellow is typically perceived as the most attention-grabbing colour, which explains its use in warning signs, taxis, and highlighter pens. However, prolonged exposure to bright yellow has been associated with increased anxiety and agitation in some studies. Orange combines the energy of red with the cheerfulness of yellow and is commonly used in marketing to convey enthusiasm, affordability, and approachability. Black conveys sophistication, luxury, and authority, and is the dominant colour in high-end branding, from fashion houses to premium electronics. White is associated with purity, simplicity, and cleanliness across many Western cultures, though in several East Asian traditions, white is the colour of mourning.

The practical applications of colour psychology are vast. Interior designers use warm colours (reds, oranges, yellows) to create stimulating, sociable environments and cool colours (blues, greens, purples) to promote relaxation and concentration. Educators have experimented with classroom colour schemes to enhance learning outcomes. Therapists have explored chromotherapy — the use of coloured light to influence mood and well-being — though the evidence base for this practice remains limited. In digital design, the colour of a website button can significantly affect click-through rates: one widely cited A/B test found that changing a call-to-action button from green to red increased conversions by 21 percent.

Despite these findings, colour psychology is not without its critics. Sceptics argue that many popular claims about colour effects are overgeneralised or based on small, unreplicated studies. Cultural variation in colour associations is substantial: while white represents purity in many Western cultures, it symbolises death in parts of Asia; red signifies luck and prosperity in China but danger in Western contexts. Individual variation — shaped by personal history, aesthetic preferences, and even colour vision differences — further complicates attempts to establish universal colour-emotion mappings. The most rigorous researchers in the field acknowledge that colour effects are real but context-dependent, moderated by culture, individual differences, and the specific task or environment in question.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "According to the passage, what does the human eye use to distinguish colours?", options: ["A. Rod cells in the retina", "B. Three types of cone cells in the retina", "C. Signals from the optic nerve only", "D. A single type of photoreceptor"], correctAnswer: "B", explanation: "The passage states 'three types of cone cells in the retina that respond to short (blue), medium (green), and long (red) wavelengths of light.'" },
        { number: 2, type: "multiple_choice", text: "What did the 2005 Nature study find about the colour red in sports?", options: ["A. Red uniforms distracted referees", "B. Contestants wearing red won more bouts in combat sports", "C. Red made athletes slower but stronger", "D. There was no significant effect of colour"], correctAnswer: "B", explanation: "The passage says 'contestants wearing red won significantly more bouts in combat sports at the Athens Olympics.'" },
        { number: 3, type: "multiple_choice", text: "What did the University of British Columbia study find?", options: ["A. Blue environments hindered all types of thinking", "B. Red environments were better for creative tasks", "C. Blue environments helped creativity while red helped detail tasks", "D. Colour had no effect on cognitive tasks"], correctAnswer: "C", explanation: "The passage says blue participants 'generated twice as many creative outputs' while 'red-environment participants performed better on tasks requiring attention to detail.'" },
        { number: 4, type: "multiple_choice", text: "What is 'greenwashing' as described in the passage?", options: ["A. Painting products green to make them more attractive", "B. Using green imagery to falsely imply environmental credentials", "C. A government policy on environmental advertising", "D. A technique for cleaning products naturally"], correctAnswer: "B", explanation: "The passage defines greenwashing as 'using green imagery to imply environmental credentials that products do not genuinely possess.'" },
        { number: 5, type: "true_false_not_given", text: "The human eye can distinguish approximately ten million colours.", correctAnswer: "TRUE", explanation: "The passage says 'The human eye can distinguish approximately ten million different colours.'" },
        { number: 6, type: "true_false_not_given", text: "Blue environments raise heart rate and blood pressure.", correctAnswer: "FALSE", explanation: "The passage says blue environments 'can lower heart rate and blood pressure.'" },
        { number: 7, type: "true_false_not_given", text: "Yellow is used in warning signs because it grabs attention.", correctAnswer: "TRUE", explanation: "The passage says yellow 'is typically perceived as the most attention-grabbing colour, which explains its use in warning signs.'" },
        { number: 8, type: "true_false_not_given", text: "Chromotherapy has a strong evidence base in clinical settings.", correctAnswer: "FALSE", explanation: "The passage says 'the evidence base for this practice remains limited.'" },
        { number: 9, type: "true_false_not_given", text: "More people prefer blue to any other colour worldwide.", correctAnswer: "NOT GIVEN", explanation: "The passage does not discuss global colour preferences." },
        { number: 10, type: "sentence_completion", text: "Red is widely used in sale signs because it conveys _______ and stimulates impulse purchasing.", correctAnswer: "urgency", explanation: "The passage says 'red is widely used to convey urgency and stimulate impulse purchasing.'" },
        { number: 11, type: "sentence_completion", text: "Hospital patients with views of green spaces recover faster and require less pain _______.", correctAnswer: "medication", explanation: "The passage states they 'require less pain medication.'" },
        { number: 12, type: "sentence_completion", text: "In several East Asian traditions, white is the colour of _______.", correctAnswer: "mourning", explanation: "The passage says 'in several East Asian traditions, white is the colour of mourning.'" },
        { number: 13, type: "sentence_completion", text: "Changing a call-to-action button from green to red increased conversions by _______ percent.", correctAnswer: "21", explanation: "The passage says 'increased conversions by 21 percent.'" },
      ],
    },
    {
      title: "Tourism Trends in Europe",
      text: `A. Europe has long been the world's most visited continent, attracting hundreds of millions of international tourists each year with its extraordinary diversity of cultures, landscapes, historical monuments, and culinary traditions. According to the United Nations World Tourism Organization (UNWTO), Europe received approximately 713 million international tourist arrivals in 2019 — representing more than half of all global tourism — generating an estimated $570 billion in revenue. Tourism is a vital component of many European economies, accounting for more than 10 percent of GDP in countries such as Greece, Portugal, Croatia, and Spain, and supporting millions of jobs in hospitality, transport, retail, and cultural industries.

B. The geography of European tourism has shifted significantly over the past two decades. While traditional destinations such as France, Spain, and Italy continue to dominate international arrival statistics, a growing number of travellers are seeking alternatives to crowded hotspots. Countries in Central and Eastern Europe — including Poland, the Czech Republic, Romania, and the Baltic states — have experienced rapid growth in visitor numbers, driven by improved air connectivity, competitive pricing, and growing awareness of their rich cultural heritage. Georgia, Albania, and North Macedonia have emerged as some of the fastest-growing tourism destinations in Europe, attracting adventurous travellers drawn by unspoiled landscapes, authentic cultural experiences, and exceptional value for money.

C. One of the most significant trends in European tourism is the rise of sustainable and responsible travel. Increasing awareness of the environmental and social impacts of mass tourism has led both consumers and policymakers to seek more balanced approaches. The concept of "overtourism" — the phenomenon whereby popular destinations receive visitor numbers that exceed their capacity to absorb them without damage to the environment, infrastructure, or residents' quality of life — has become a major concern. Cities such as Venice, Barcelona, Dubrovnik, and Amsterdam have introduced measures to manage tourist flows, including visitor caps, tourist taxes, restrictions on short-term rental platforms like Airbnb, and bans on new hotels in certain areas. The European Commission has identified sustainable tourism as a strategic priority and has funded initiatives to support the development of less-visited destinations and promote off-season travel.

D. The COVID-19 pandemic, which devastated the European tourism industry in 2020 and 2021, accelerated several pre-existing trends. Domestic tourism surged as international borders closed and travellers explored their own countries. Rural and nature-based tourism experienced significant growth, as consumers sought open-air environments perceived as safer than crowded urban attractions. Digital transformation accelerated: contactless check-in, digital health passes, virtual tours, and AI-powered personalisation became standard features of the tourist experience. The pandemic also prompted a fundamental reassessment of the economic model of tourism in many European destinations, with growing recognition that dependence on high-volume, low-margin mass tourism creates vulnerabilities and that a more diversified, higher-value approach may be more resilient in the long term.

E. Cultural tourism remains the dominant segment of European travel, with UNESCO World Heritage Sites, museums, festivals, and gastronomic experiences among the most powerful draws. Europe is home to more than 450 UNESCO World Heritage Sites — nearly half the global total — spanning ancient monuments, medieval cities, industrial landscapes, and natural wonders. The growing popularity of food and wine tourism has transformed regions such as Tuscany, Bordeaux, the Basque Country, and the Algarve into culinary pilgrimage destinations. Music festivals, from Glastonbury in England to Sziget in Hungary and Primavera Sound in Barcelona, attract millions of visitors annually and generate substantial economic activity in their host cities and regions.

F. Looking ahead, the future of European tourism is likely to be shaped by several converging forces: climate change, which may alter travel patterns as Mediterranean summers become uncomfortably hot; demographic shifts, as an ageing population in Europe's key source markets drives demand for accessible, health-oriented travel experiences; technological innovation, including virtual reality, artificial intelligence, and blockchain-based travel services; and evolving consumer values, with younger travellers placing greater emphasis on authenticity, sustainability, and experiential travel over traditional sightseeing. The challenge for European destinations will be to balance economic opportunity with environmental stewardship and community well-being, ensuring that tourism remains a force for cultural exchange and mutual understanding rather than a source of congestion, commodification, and environmental degradation.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Paragraph A", options: ["i. Managing the problem of too many visitors", "ii. Europe's position as a global tourism leader", "iii. New destinations gaining popularity", "iv. The pandemic's lasting effects on tourism", "v. Cultural attractions driving European travel", "vi. Future challenges and opportunities", "vii. Sustainable tourism policies", "viii. The rise of budget airlines"], correctAnswer: "ii", explanation: "Paragraph A presents Europe's dominant position with 713 million arrivals and $570 billion revenue." },
        { number: 15, type: "matching_headings", text: "Paragraph B", options: ["i. Managing the problem of too many visitors", "ii. Europe's position as a global tourism leader", "iii. New destinations gaining popularity", "iv. The pandemic's lasting effects on tourism", "v. Cultural attractions driving European travel", "vi. Future challenges and opportunities", "vii. Sustainable tourism policies", "viii. The rise of budget airlines"], correctAnswer: "iii", explanation: "Paragraph B discusses the shift toward Central/Eastern Europe and emerging destinations." },
        { number: 16, type: "matching_headings", text: "Paragraph C", options: ["i. Managing the problem of too many visitors", "ii. Europe's position as a global tourism leader", "iii. New destinations gaining popularity", "iv. The pandemic's lasting effects on tourism", "v. Cultural attractions driving European travel", "vi. Future challenges and opportunities", "vii. Sustainable tourism policies", "viii. The rise of budget airlines"], correctAnswer: "i", explanation: "Paragraph C focuses on overtourism and measures to manage visitor numbers." },
        { number: 17, type: "matching_headings", text: "Paragraph D", options: ["i. Managing the problem of too many visitors", "ii. Europe's position as a global tourism leader", "iii. New destinations gaining popularity", "iv. The pandemic's lasting effects on tourism", "v. Cultural attractions driving European travel", "vi. Future challenges and opportunities", "vii. Sustainable tourism policies", "viii. The rise of budget airlines"], correctAnswer: "iv", explanation: "Paragraph D describes COVID-19's impact and resulting changes in tourism." },
        { number: 18, type: "matching_headings", text: "Paragraph E", options: ["i. Managing the problem of too many visitors", "ii. Europe's position as a global tourism leader", "iii. New destinations gaining popularity", "iv. The pandemic's lasting effects on tourism", "v. Cultural attractions driving European travel", "vi. Future challenges and opportunities", "vii. Sustainable tourism policies", "viii. The rise of budget airlines"], correctAnswer: "v", explanation: "Paragraph E discusses UNESCO sites, food tourism, and music festivals." },
        { number: 19, type: "matching_headings", text: "Paragraph F", options: ["i. Managing the problem of too many visitors", "ii. Europe's position as a global tourism leader", "iii. New destinations gaining popularity", "iv. The pandemic's lasting effects on tourism", "v. Cultural attractions driving European travel", "vi. Future challenges and opportunities", "vii. Sustainable tourism policies", "viii. The rise of budget airlines"], correctAnswer: "vi", explanation: "Paragraph F discusses climate change, demographics, technology, and evolving values shaping future tourism." },
        { number: 20, type: "summary_completion", text: "Europe received approximately _______ million international tourist arrivals in 2019.", correctAnswer: "713", explanation: "The passage states 'approximately 713 million international tourist arrivals in 2019.'" },
        { number: 21, type: "summary_completion", text: "European tourism generated an estimated $_______ billion in revenue in 2019.", correctAnswer: "570", explanation: "The passage says 'generating an estimated $570 billion in revenue.'" },
        { number: 22, type: "summary_completion", text: "Europe has more than _______ UNESCO World Heritage Sites.", correctAnswer: "450", explanation: "The passage says 'more than 450 UNESCO World Heritage Sites.'" },
        { number: 23, type: "short_answer", text: "What term describes destinations receiving more visitors than they can absorb?", correctAnswer: "overtourism", explanation: "The passage defines this as 'overtourism.'" },
        { number: 24, type: "short_answer", text: "Name one city that has introduced visitor caps to manage tourism.", correctAnswer: "Venice", explanation: "The passage lists Venice, Barcelona, Dubrovnik, and Amsterdam. Any one is acceptable." },
        { number: 25, type: "short_answer", text: "What type of tourism surged when international borders closed during COVID-19?", correctAnswer: "domestic tourism", explanation: "The passage says 'Domestic tourism surged as international borders closed.'" },
        { number: 26, type: "short_answer", text: "What short-term rental platform is mentioned as being restricted in some cities?", correctAnswer: "Airbnb", explanation: "The passage mentions 'restrictions on short-term rental platforms like Airbnb.'" },
      ],
    },
    {
      title: "Genetic Engineering and CRISPR Technology",
      text: `The ability to precisely edit the genetic code of living organisms represents one of the most consequential scientific advances in human history. While genetic modification techniques have existed in various forms since the 1970s, the development of CRISPR-Cas9 — a revolutionary gene-editing tool derived from the natural immune systems of bacteria — has transformed the field, making genetic engineering faster, cheaper, more precise, and more accessible than ever before. Since its first demonstration as a gene-editing tool in 2012, CRISPR has reshaped medicine, agriculture, biotechnology, and the fundamental biological sciences, raising both extraordinary possibilities and profound ethical questions.

CRISPR stands for Clustered Regularly Interspaced Short Palindromic Repeats — sequences of DNA found in bacteria that form part of an ancient immune defence mechanism against viral infections. When a bacterium survives a viral attack, it incorporates fragments of the virus's DNA into its own genome between these repeat sequences, creating a molecular "memory" of the infection. If the same virus attacks again, the bacterium produces RNA molecules that match the stored viral DNA sequences and guides a protein called Cas9 to locate and cut the matching DNA, thereby neutralising the threat. In 2012, researchers Jennifer Doudna and Emmanuelle Charpentier demonstrated that this natural system could be reprogrammed to cut any specific DNA sequence in any organism, effectively creating a universal, programmable molecular scissors. Their discovery earned them the Nobel Prize in Chemistry in 2020.

The medical applications of CRISPR are among the most promising and intensely researched. In December 2023, the UK became the first country to approve a CRISPR-based therapy — Casgevy — for the treatment of sickle cell disease and transfusion-dependent beta thalassemia, two serious inherited blood disorders caused by mutations in the gene encoding haemoglobin. The treatment works by editing patients' own bone marrow stem cells to reactivate production of foetal haemoglobin, a form of the protein that is normally switched off after birth but can compensate for the defective adult haemoglobin. Clinical trials showed that the vast majority of treated patients achieved freedom from the painful vaso-occlusive crises that characterise sickle cell disease and from the need for regular blood transfusions in beta thalassemia.

Beyond blood disorders, CRISPR is being investigated as a potential treatment for a wide range of genetic diseases, including cystic fibrosis, Huntington's disease, Duchenne muscular dystrophy, and certain forms of inherited blindness. Researchers are also exploring the use of CRISPR to enhance the effectiveness of cancer immunotherapy — a treatment approach in which the patient's own immune cells are engineered to recognise and destroy cancer cells. In 2020, a team at the University of Pennsylvania used CRISPR to edit three genes in T-cells taken from cancer patients, removing a natural "off switch" that tumours exploit to evade immune attack. The edited cells were then infused back into the patients, where they persisted for months and showed enhanced anti-tumour activity.

Agricultural applications of CRISPR have advanced rapidly. Unlike traditional genetic modification, which typically involves inserting foreign DNA from another species into a crop's genome, CRISPR can make precise changes to a plant's own genes — mimicking mutations that could occur naturally but achieving in months what conventional breeding might take decades to accomplish. CRISPR-edited crops developed so far include disease-resistant wheat, drought-tolerant maize, high-yield rice, non-browning mushrooms, and tomatoes with enhanced nutritional content. In 2021, Japan approved the commercial sale of CRISPR-edited tomatoes containing elevated levels of gamma-aminobutyric acid (GABA), a compound associated with reduced blood pressure. Regulatory approaches to CRISPR-edited crops vary significantly between countries: the United States generally does not regulate gene-edited crops that could have been produced through conventional breeding, while the European Union currently treats all gene-edited organisms under its strict GMO regulations — a position that many scientists and agricultural organisations have argued is disproportionate and counterproductive.

The most ethically contentious application of CRISPR is human germline editing — changes made to embryos, eggs, or sperm that would be inherited by future generations. In November 2018, Chinese scientist He Jiankui shocked the scientific community by announcing that he had used CRISPR to edit the genomes of twin girls to make them resistant to HIV infection. The experiment was widely condemned as reckless, premature, and ethically unacceptable: the long-term consequences of the edits are unknown, the procedure was performed without adequate oversight, and the informed consent process for the parents was deemed inadequate. He Jiankui was subsequently convicted and imprisoned in China. In response, the World Health Organization established an expert advisory committee on human genome editing, and leading scientific organisations have called for a moratorium on clinical applications of germline editing until safety, efficacy, and ethical governance frameworks are firmly established. The fundamental question — whether humanity should permanently alter the genetic heritage of future generations, and if so, under what circumstances and with what safeguards — remains one of the most important and unresolved ethical debates of our time.`,
      questions: [
        { number: 27, type: "matching_information", text: "A description of how bacteria naturally defend against viruses", options: ["Paragraph 1", "Paragraph 2", "Paragraph 3", "Paragraph 4", "Paragraph 5", "Paragraph 6"], correctAnswer: "Paragraph 2", explanation: "Paragraph 2 explains the CRISPR bacterial immune defence mechanism." },
        { number: 28, type: "matching_information", text: "An example of a controversial human gene-editing experiment", options: ["Paragraph 1", "Paragraph 2", "Paragraph 3", "Paragraph 4", "Paragraph 5", "Paragraph 6"], correctAnswer: "Paragraph 6", explanation: "Paragraph 6 describes He Jiankui's controversial germline editing of twin girls." },
        { number: 29, type: "matching_information", text: "A reference to using CRISPR to improve cancer treatment", options: ["Paragraph 1", "Paragraph 2", "Paragraph 3", "Paragraph 4", "Paragraph 5", "Paragraph 6"], correctAnswer: "Paragraph 4", explanation: "Paragraph 4 discusses CRISPR-enhanced cancer immunotherapy at the University of Pennsylvania." },
        { number: 30, type: "matching_information", text: "Information about differences in how countries regulate gene-edited crops", options: ["Paragraph 1", "Paragraph 2", "Paragraph 3", "Paragraph 4", "Paragraph 5", "Paragraph 6"], correctAnswer: "Paragraph 5", explanation: "Paragraph 5 compares US and EU regulatory approaches to CRISPR-edited crops." },
        { number: 31, type: "matching_information", text: "Details of the first approved CRISPR medical treatment", options: ["Paragraph 1", "Paragraph 2", "Paragraph 3", "Paragraph 4", "Paragraph 5", "Paragraph 6"], correctAnswer: "Paragraph 3", explanation: "Paragraph 3 describes the UK's approval of Casgevy for sickle cell disease." },
        { number: 32, type: "flow_chart_completion", text: "A bacterium survives a viral attack and stores fragments of the virus's _______ in its genome.", correctAnswer: "DNA", explanation: "The passage says the bacterium 'incorporates fragments of the virus's DNA into its own genome.'" },
        { number: 33, type: "flow_chart_completion", text: "If the same virus returns, the bacterium produces _______ molecules matching the stored sequences.", correctAnswer: "RNA", explanation: "The passage says 'the bacterium produces RNA molecules that match the stored viral DNA sequences.'" },
        { number: 34, type: "flow_chart_completion", text: "A protein called _______ is guided to locate and cut the matching DNA.", correctAnswer: "Cas9", explanation: "The passage identifies the protein as 'Cas9.'" },
        { number: 35, type: "multiple_choice", text: "What did Doudna and Charpentier demonstrate in 2012?", options: ["A. That CRISPR could only work in bacteria", "B. That CRISPR could be reprogrammed to cut any DNA sequence in any organism", "C. That gene editing was too dangerous for clinical use", "D. That Cas9 was ineffective against viruses"], correctAnswer: "B", explanation: "The passage says they 'demonstrated that this natural system could be reprogrammed to cut any specific DNA sequence in any organism.'" },
        { number: 36, type: "multiple_choice", text: "How does the Casgevy treatment work?", options: ["A. By inserting foreign DNA into the patient", "B. By reactivating foetal haemoglobin production", "C. By removing all defective genes permanently", "D. By replacing the patient's entire bone marrow"], correctAnswer: "B", explanation: "The passage says it works 'by editing patients' own bone marrow stem cells to reactivate production of foetal haemoglobin.'" },
        { number: 37, type: "multiple_choice", text: "What was unique about the CRISPR-edited tomatoes approved in Japan?", options: ["A. They could grow without sunlight", "B. They contained elevated levels of GABA", "C. They were resistant to all diseases", "D. They required no water to grow"], correctAnswer: "B", explanation: "The passage says 'tomatoes containing elevated levels of gamma-aminobutyric acid (GABA).'" },
        { number: 38, type: "multiple_choice", text: "Why was He Jiankui's experiment condemned?", options: ["A. It was too expensive to replicate", "B. It only worked on animal cells", "C. It was performed without adequate oversight and with unknown long-term consequences", "D. The results were never published"], correctAnswer: "C", explanation: "The passage says it was 'reckless, premature, and ethically unacceptable' with 'unknown long-term consequences' and 'without adequate oversight.'" },
        { number: 39, type: "multiple_choice", text: "What recognition did Doudna and Charpentier receive?", options: ["A. The Nobel Prize in Medicine in 2018", "B. The Nobel Prize in Chemistry in 2020", "C. The Nobel Prize in Physics in 2012", "D. A joint award from the WHO"], correctAnswer: "B", explanation: "The passage says 'Their discovery earned them the Nobel Prize in Chemistry in 2020.'" },
        { number: 40, type: "multiple_choice", text: "What did the University of Pennsylvania team do with CRISPR in 2020?", options: ["A. Created disease-resistant wheat", "B. Edited three genes in T-cells to fight cancer", "C. Developed a vaccine for sickle cell disease", "D. Approved the first CRISPR crop for sale"], correctAnswer: "B", explanation: "The passage says 'a team at the University of Pennsylvania used CRISPR to edit three genes in T-cells taken from cancer patients.'" },
      ],
    },
  ],
};
