import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_43: ReadingTest = {
  id: 43,
  passages: [
    {
      title: "History of Astronomy",
      text: `Astronomy is arguably the oldest of the natural sciences, born from humanity's innate fascination with the night sky. For tens of thousands of years, people have gazed upward, charting the movements of the sun, moon, planets, and stars, and weaving what they observed into calendars, mythologies, and systems of navigation.

The earliest known astronomical records come from ancient Mesopotamia, where Babylonian priests meticulously documented celestial events on clay tablets as early as 1800 BCE. They identified the five planets visible to the naked eye — Mercury, Venus, Mars, Jupiter, and Saturn — and tracked their movements against the background of fixed stars. Babylonian astronomers developed mathematical models to predict lunar eclipses and compiled the MUL.APIN, a compendium of star catalogues and astronomical procedures that remained influential for over a millennium.

Ancient Egypt aligned monumental architecture with celestial phenomena: the Great Pyramid of Giza, for example, is oriented to the cardinal points with an accuracy of better than one-twelfth of a degree, and its internal shafts point toward stars that were significant in Egyptian religion. The annual flooding of the Nile, upon which Egyptian agriculture depended, was predicted by observing the heliacal rising of Sirius, the brightest star in the night sky.

Greek astronomers transformed the discipline from observational record-keeping into a theoretical science. Aristarchus of Samos, in the third century BCE, proposed the revolutionary idea that the Earth revolves around the Sun — a heliocentric model that was rejected in favour of the geocentric system formalised by Claudius Ptolemy around 150 CE. Ptolemy's Almagest, a mathematical treatise that modelled planetary motions using complex systems of epicycles and deferents, remained the authoritative astronomical text for over 1,400 years. Hipparchus, working in the second century BCE, compiled the first comprehensive Western star catalogue, listing the positions and brightness of approximately 850 stars, and discovered the precession of the equinoxes.

The Copernican Revolution, initiated by Nicolaus Copernicus's De Revolutionibus Orbium Coelestium in 1543, restored the heliocentric model and set in motion a fundamental restructuring of astronomical thought. Johannes Kepler refined the model by demonstrating that planetary orbits are elliptical rather than circular, and Galileo Galilei, using a telescope he improved in 1609, observed the moons of Jupiter, the phases of Venus, and the craters of the Moon — observations that provided decisive evidence against the Ptolemaic system.

Isaac Newton's Principia Mathematica, published in 1687, unified terrestrial and celestial mechanics by showing that the same force — gravity — governs the fall of an apple and the orbit of a planet. Newtonian mechanics remained unchallenged until 1915, when Albert Einstein's general theory of relativity reconceived gravity as the curvature of space-time caused by mass and energy, providing explanations for phenomena — the precession of Mercury's orbit, the bending of light by massive objects — that Newtonian physics could not fully account for.

The twentieth century witnessed an explosion of discovery. Edwin Hubble demonstrated in 1929 that the universe is expanding, laying the observational foundation for the Big Bang theory. Radio telescopes, X-ray satellites, and space-based observatories such as the Hubble Space Telescope and the James Webb Space Telescope have revealed a universe of astonishing scale and complexity: billions of galaxies, each containing hundreds of billions of stars, many orbited by planets. The discovery of exoplanets — planets orbiting stars other than the Sun — has become one of astronomy's most dynamic fields, with more than 5,500 confirmed exoplanets catalogued by 2024.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "What did Babylonian astronomers use to record celestial events?", options: ["A Papyrus scrolls", "B Clay tablets", "C Stone monuments", "D Metal plates"], correctAnswer: "B", explanation: "The passage says they 'documented celestial events on clay tablets.'" },
        { number: 2, type: "multiple_choice", text: "Who first proposed a heliocentric model in ancient times?", options: ["A Ptolemy", "B Hipparchus", "C Aristarchus of Samos", "D Copernicus"], correctAnswer: "C", explanation: "The passage says 'Aristarchus of Samos... proposed the revolutionary idea that the Earth revolves around the Sun.'" },
        { number: 3, type: "multiple_choice", text: "What shape did Kepler demonstrate for planetary orbits?", options: ["A Circular", "B Elliptical", "C Spiral", "D Parabolic"], correctAnswer: "B", explanation: "The passage says 'planetary orbits are elliptical rather than circular.'" },
        { number: 4, type: "multiple_choice", text: "How many exoplanets had been confirmed by 2024?", options: ["A Over 2,000", "B Over 3,500", "C Over 5,500", "D Over 10,000"], correctAnswer: "C", explanation: "The passage says 'more than 5,500 confirmed exoplanets catalogued by 2024.'" },
        { number: 5, type: "sentence_completion", text: "The MUL.APIN was a compendium of star catalogues compiled by __(5)__ astronomers.", correctAnswer: "Babylonian", explanation: "The passage says Babylonian astronomers 'compiled the MUL.APIN.'" },
        { number: 6, type: "sentence_completion", text: "The annual flooding of the Nile was predicted by observing the heliacal rising of __(6)__.", correctAnswer: "Sirius", explanation: "The passage says 'the heliacal rising of Sirius.'" },
        { number: 7, type: "sentence_completion", text: "Ptolemy's __(7)__ remained the authoritative text for over 1,400 years.", correctAnswer: "Almagest", explanation: "The passage says 'Ptolemy's Almagest... remained the authoritative astronomical text.'" },
        { number: 8, type: "sentence_completion", text: "Hipparchus catalogued approximately __(8)__ stars.", correctAnswer: "850", explanation: "The passage says 'approximately 850 stars.'" },
        { number: 9, type: "sentence_completion", text: "Galileo improved a __(9)__ in 1609 to make astronomical observations.", correctAnswer: "telescope", explanation: "The passage says 'using a telescope he improved in 1609.'" },
        { number: 10, type: "sentence_completion", text: "Newton published Principia Mathematica in __(10)__.", correctAnswer: "1687", explanation: "The passage says 'published in 1687.'" },
        { number: 11, type: "sentence_completion", text: "Einstein's general theory of relativity described gravity as the curvature of __(11)__.", correctAnswer: "space-time", explanation: "The passage says 'gravity as the curvature of space-time.'" },
        { number: 12, type: "sentence_completion", text: "Edwin Hubble demonstrated in 1929 that the universe is __(12)__.", correctAnswer: "expanding", explanation: "The passage says 'the universe is expanding.'" },
        { number: 13, type: "sentence_completion", text: "The Great Pyramid is oriented to the cardinal points with accuracy better than one-__(13)__ of a degree.", correctAnswer: "twelfth", explanation: "The passage says 'better than one-twelfth of a degree.'" },
      ],
    },
    {
      title: "Water Conservation",
      text: `A. Water is essential to all life on Earth, yet freshwater — the type humans, animals, and most plants depend on — constitutes only about 2.5 per cent of the planet's total water supply. Of that small fraction, roughly seventy per cent is locked in glaciers and ice caps, and much of the remainder lies in deep underground aquifers that are difficult or expensive to access. The water available for immediate human use — in rivers, lakes, and shallow aquifers — represents less than one per cent of all freshwater, making it one of the most precious and finite resources on Earth.

B. Global demand for freshwater has increased by roughly one per cent per year over the past four decades, driven by population growth, rising living standards, and expanding agriculture and industry. The United Nations estimates that by 2025, 1.8 billion people will live in regions experiencing absolute water scarcity, and two-thirds of the world's population could be living under water-stressed conditions. Climate change is exacerbating the problem: shifting rainfall patterns, shrinking glaciers, and more frequent droughts are reducing water availability in many of the world's most populated regions.

C. Agriculture is by far the largest consumer of freshwater, accounting for approximately seventy per cent of global withdrawals. Much of this water is used for irrigation, and in many regions, traditional irrigation methods — flooding fields or running water through open channels — waste enormous quantities through evaporation and seepage. Drip irrigation, which delivers water directly to the root zone of plants through a network of pipes and emitters, can reduce water use by thirty to seventy per cent compared with flood irrigation. Israel, a pioneer in drip-irrigation technology, now irrigates more than seventy-five per cent of its farmland using this method and has become a major exporter of water-management expertise.

D. Urban water conservation offers significant savings. Leaking pipes are a major source of waste: in many cities, thirty per cent or more of treated water is lost to leaks before it reaches consumers. London's Victorian-era water mains lose approximately 630 million litres per day. Smart water networks, which use sensors, data analytics, and machine learning to detect leaks and optimise pressure, are being deployed in cities from Singapore to São Paulo. At the household level, low-flow taps, dual-flush toilets, and water-efficient appliances can reduce domestic water consumption by up to forty per cent.

E. Water recycling and desalination are expanding the supply side of the equation. Treated wastewater can be purified to potable standards and returned to the drinking-water supply — a process known as direct potable reuse. Windhoek, the capital of Namibia, has been recycling wastewater for drinking since 1968, and Singapore's NEWater programme supplies up to forty per cent of the city-state's water needs using purified reclaimed water. Desalination, the process of removing salt from seawater, provides freshwater in arid coastal regions: Saudi Arabia, the United Arab Emirates, and Israel operate some of the world's largest desalination plants. However, desalination is energy-intensive, and the disposal of concentrated brine — the salty by-product — poses environmental challenges.

F. Rainwater harvesting, one of the oldest water-conservation techniques, is experiencing a revival. In India, traditional systems such as stepwells and johads (earthen dams) captured and stored monsoon rainfall for centuries before falling into disrepair. Modern rainwater-harvesting systems, installed on rooftops and in urban landscapes, collect precipitation for non-potable uses such as garden irrigation, toilet flushing, and car washing. In some regions, collected rainwater is filtered and treated for drinking. Australia, Germany, and several US states have introduced incentives or mandates for rainwater harvesting in new buildings.

G. Protecting natural water sources is equally important. Wetlands, which act as natural sponges, absorb floodwater, filter pollutants, and recharge groundwater supplies. Yet more than thirty-five per cent of the world's wetlands have been lost since 1970, drained for agriculture or urban development. Reforestation of watersheds helps regulate water flow, reduce erosion, and maintain water quality. New York City famously chose to invest in protecting the Catskill Mountains watershed rather than building a $10 billion filtration plant, demonstrating that nature-based solutions can be both effective and cost-efficient.

H. Ultimately, addressing the global water crisis requires a combination of technological innovation, policy reform, and behavioural change. Pricing water to reflect its true value, investing in infrastructure, and educating the public about conservation are all essential. Water, unlike oil or gas, has no substitute; ensuring its availability for future generations is one of the defining challenges of the twenty-first century.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Section A", options: ["I. Agriculture's water footprint", "II. The scarcity of accessible freshwater", "III. Growing global water demand", "IV. Reducing waste in city water systems", "V. Technologies for creating new water supplies", "VI. Reviving traditional water collection", "VII. The importance of natural water ecosystems", "VIII. Addressing the water crisis comprehensively"], correctAnswer: "II", explanation: "Section A discusses how little freshwater is available for human use." },
        { number: 15, type: "matching_headings", text: "Section B", options: ["I. Agriculture's water footprint", "II. The scarcity of accessible freshwater", "III. Growing global water demand", "IV. Reducing waste in city water systems", "V. Technologies for creating new water supplies", "VI. Reviving traditional water collection", "VII. The importance of natural water ecosystems", "VIII. Addressing the water crisis comprehensively"], correctAnswer: "III", explanation: "Section B discusses increasing global water demand." },
        { number: 16, type: "matching_headings", text: "Section C", options: ["I. Agriculture's water footprint", "II. The scarcity of accessible freshwater", "III. Growing global water demand", "IV. Reducing waste in city water systems", "V. Technologies for creating new water supplies", "VI. Reviving traditional water collection", "VII. The importance of natural water ecosystems", "VIII. Addressing the water crisis comprehensively"], correctAnswer: "I", explanation: "Section C discusses agriculture as the largest freshwater consumer." },
        { number: 17, type: "matching_headings", text: "Section D", options: ["I. Agriculture's water footprint", "II. The scarcity of accessible freshwater", "III. Growing global water demand", "IV. Reducing waste in city water systems", "V. Technologies for creating new water supplies", "VI. Reviving traditional water collection", "VII. The importance of natural water ecosystems", "VIII. Addressing the water crisis comprehensively"], correctAnswer: "IV", explanation: "Section D discusses urban water conservation and leak reduction." },
        { number: 18, type: "matching_headings", text: "Section E", options: ["I. Agriculture's water footprint", "II. The scarcity of accessible freshwater", "III. Growing global water demand", "IV. Reducing waste in city water systems", "V. Technologies for creating new water supplies", "VI. Reviving traditional water collection", "VII. The importance of natural water ecosystems", "VIII. Addressing the water crisis comprehensively"], correctAnswer: "V", explanation: "Section E discusses water recycling and desalination." },
        { number: 19, type: "matching_headings", text: "Section F", options: ["I. Agriculture's water footprint", "II. The scarcity of accessible freshwater", "III. Growing global water demand", "IV. Reducing waste in city water systems", "V. Technologies for creating new water supplies", "VI. Reviving traditional water collection", "VII. The importance of natural water ecosystems", "VIII. Addressing the water crisis comprehensively"], correctAnswer: "VI", explanation: "Section F discusses rainwater harvesting." },
        { number: 20, type: "table_completion", text: "Freshwater constitutes only about __(20)__ per cent of Earth's total water.", correctAnswer: "2.5", explanation: "The passage says 'only about 2.5 per cent.'" },
        { number: 21, type: "table_completion", text: "Agriculture accounts for approximately __(21)__ per cent of global freshwater withdrawals.", correctAnswer: "seventy", explanation: "The passage says 'approximately seventy per cent.'" },
        { number: 22, type: "table_completion", text: "London's water mains lose approximately __(22)__ million litres per day.", correctAnswer: "630", explanation: "The passage says 'approximately 630 million litres per day.'" },
        { number: 23, type: "table_completion", text: "Singapore's NEWater supplies up to __(23)__ per cent of the city's water needs.", correctAnswer: "forty", explanation: "The passage says 'up to forty per cent.'" },
        { number: 24, type: "table_completion", text: "More than __(24)__ per cent of the world's wetlands have been lost since 1970.", correctAnswer: "thirty-five", explanation: "The passage says 'more than thirty-five per cent.'" },
        { number: 25, type: "table_completion", text: "Israel irrigates more than __(25)__ per cent of its farmland using drip irrigation.", correctAnswer: "seventy-five", explanation: "The passage says 'more than seventy-five per cent.'" },
        { number: 26, type: "table_completion", text: "New York chose watershed protection instead of building a $__(26)__ billion filtration plant.", correctAnswer: "10", explanation: "The passage says 'a $10 billion filtration plant.'" },
      ],
    },
    {
      title: "Autonomous Robots",
      text: `Autonomous robots — machines capable of performing tasks in unstructured environments without continuous human control — have progressed from laboratory curiosities to practical tools deployed across a widening range of industries. Unlike traditional industrial robots, which follow pre-programmed routines in carefully controlled factory settings, autonomous robots must perceive their surroundings, make decisions, and adapt to changing conditions in real time. This requires the integration of advanced sensors, artificial intelligence, and sophisticated mechanical systems, a combination that has become feasible only in the past decade thanks to rapid improvements in computing power, machine learning, and sensor technology.

In logistics and warehousing, autonomous mobile robots (AMRs) navigate complex environments using lidar, cameras, and simultaneous localisation and mapping (SLAM) algorithms. Unlike automated guided vehicles (AGVs), which follow fixed paths marked by magnetic strips or embedded wires, AMRs can dynamically plan and adjust their routes in response to obstacles, changes in layout, and varying workloads. Companies such as Locus Robotics and 6 River Systems deploy fleets of AMRs that work alongside human pickers in fulfilment centres, increasing productivity by an estimated two to three times while reducing walking distances for workers.

Agricultural robots are addressing labour shortages and sustainability challenges in farming. Autonomous tractors, guided by GPS and computer vision, can plough, seed, and spray crops with centimetre-level precision, reducing fuel consumption, chemical use, and soil compaction. Harvesting robots, equipped with cameras and machine-learning algorithms, can identify ripe fruit, assess quality, and pick produce without bruising it — tasks that have traditionally required human dexterity. Companies such as Agrobot (strawberries), Abundant Robotics (apples), and Dogtooth Technologies (soft fruits) are developing or deploying autonomous harvesters, although the technology remains challenging for delicate or irregularly shaped crops.

Underwater autonomous vehicles (AUVs) are transforming ocean science and offshore industry. AUVs can survey the seabed, inspect underwater infrastructure, collect environmental data, and map coral reefs at depths and durations far beyond the capacity of human divers. The Boaty McBoatface AUV, operated by the National Oceanography Centre in the United Kingdom, has conducted missions beneath Antarctic ice shelves, collecting data on ocean currents and temperature that are critical for climate models. In the oil and gas industry, resident AUVs stationed permanently on the seabed near subsea installations perform routine inspections, reducing the need for costly surface vessels and human dive teams.

Search-and-rescue robots are being developed for disaster response. Snake-like robots can navigate through collapsed rubble too narrow or unstable for humans, locating trapped survivors using thermal cameras and microphones. Aerial drones equipped with infrared sensors can rapidly survey disaster zones, identifying heat signatures that indicate the presence of survivors. In 2023, following major earthquakes in Turkey, autonomous drones were deployed to map damaged areas and guide rescue teams, demonstrating the technology's growing operational maturity.

In healthcare, autonomous robots assist with surgery, rehabilitation, and logistics. Surgical robots such as the da Vinci system allow surgeons to perform minimally invasive procedures with greater precision and control than manual techniques. Rehabilitation robots provide consistent, programmable physical therapy for patients recovering from strokes or orthopaedic injuries. Hospital logistics robots transport medications, meals, and laboratory specimens through corridors and elevators, freeing nursing staff to focus on patient care. During the COVID-19 pandemic, robots were used to deliver food and supplies to quarantined patients, reducing the risk of infection for healthcare workers.

The ethical and regulatory dimensions of autonomous robotics are receiving increasing attention. Questions about liability — who is responsible when an autonomous robot causes harm — remain unresolved in most jurisdictions. Concerns about job displacement, particularly in sectors such as logistics and agriculture, are prompting discussions about retraining, social safety nets, and the equitable distribution of productivity gains. Privacy issues arise when robots equipped with cameras and sensors operate in public or domestic spaces. Developing robust safety standards, transparent AI decision-making, and inclusive governance frameworks will be essential as autonomous robots become an increasingly pervasive feature of daily life.`,
      questions: [
        { number: 27, type: "multiple_choice", text: "How do AMRs differ from AGVs?", options: ["A AMRs are cheaper to manufacture", "B AMRs can dynamically plan routes while AGVs follow fixed paths", "C AMRs are only used in factories", "D AMRs require continuous human control"], correctAnswer: "B", explanation: "The passage says AMRs 'can dynamically plan and adjust their routes' unlike AGVs which 'follow fixed paths.'" },
        { number: 28, type: "multiple_choice", text: "What has Boaty McBoatface done?", options: ["A Harvested crops autonomously", "B Inspected oil platforms", "C Collected data beneath Antarctic ice shelves", "D Performed search-and-rescue operations"], correctAnswer: "C", explanation: "The passage says it 'has conducted missions beneath Antarctic ice shelves, collecting data.'" },
        { number: 29, type: "multiple_choice", text: "What type of robots were used in Turkey after the 2023 earthquakes?", options: ["A Surgical robots", "B Snake-like rubble robots", "C Autonomous drones", "D Agricultural robots"], correctAnswer: "C", explanation: "The passage says 'autonomous drones were deployed to map damaged areas.'" },
        { number: 30, type: "multiple_choice", text: "What does the da Vinci system assist with?", options: ["A Agricultural harvesting", "B Underwater exploration", "C Minimally invasive surgery", "D Warehouse logistics"], correctAnswer: "C", explanation: "The passage says 'Surgical robots such as the da Vinci system allow surgeons to perform minimally invasive procedures.'" },
        { number: 31, type: "short_answer", text: "What technology do AMRs use for navigation alongside lidar and cameras?", correctAnswer: "SLAM algorithms", explanation: "The passage says 'using lidar, cameras, and simultaneous localisation and mapping (SLAM) algorithms.'" },
        { number: 32, type: "short_answer", text: "By how much do AMRs increase productivity in fulfilment centres?", correctAnswer: "two to three times", explanation: "The passage says 'increasing productivity by an estimated two to three times.'" },
        { number: 33, type: "short_answer", text: "What guides autonomous tractors?", correctAnswer: "GPS and computer vision", explanation: "The passage says 'guided by GPS and computer vision.'" },
        { number: 34, type: "short_answer", text: "What do snake-like search-and-rescue robots use to locate survivors?", correctAnswer: "thermal cameras and microphones", explanation: "The passage says 'locating trapped survivors using thermal cameras and microphones.'" },
        { number: 35, type: "short_answer", text: "What items do hospital logistics robots transport?", correctAnswer: "medications, meals, and laboratory specimens", explanation: "The passage says 'transport medications, meals, and laboratory specimens.'" },
        { number: 36, type: "short_answer", text: "What unresolved legal question does the passage highlight about autonomous robots?", correctAnswer: "liability", explanation: "The passage says 'Questions about liability... remain unresolved.'" },
        { number: 37, type: "short_answer", text: "What were robots used for during the COVID-19 pandemic in hospitals?", correctAnswer: "delivering food and supplies to quarantined patients", explanation: "The passage says 'robots were used to deliver food and supplies to quarantined patients.'" },
        { number: 38, type: "short_answer", text: "What do resident AUVs in the oil industry reduce the need for?", correctAnswer: "costly surface vessels and human dive teams", explanation: "The passage says 'reducing the need for costly surface vessels and human dive teams.'" },
        { number: 39, type: "short_answer", text: "What challenge remains for harvesting robots with delicate crops?", correctAnswer: "delicate or irregularly shaped crops", explanation: "The passage says 'the technology remains challenging for delicate or irregularly shaped crops.'" },
        { number: 40, type: "short_answer", text: "What do aerial drones use to identify survivors in disaster zones?", correctAnswer: "infrared sensors", explanation: "The passage says 'equipped with infrared sensors.'" },
      ],
    },
  ],
};
