import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_31: ReadingTest = {
  id: 31,
  passages: [
    {
      title: "History of Navigation",
      text: `The ability to navigate — to determine one's position and plot a course to a desired destination — has been essential to human exploration, trade, and survival for millennia. From the earliest seafarers who followed coastlines and read the stars to the satellite-based systems that guide modern travellers with metre-level precision, the history of navigation is a story of ingenuity driven by necessity.

The oldest navigational methods relied on celestial observation. Polynesian voyagers, who colonised islands scattered across the vast Pacific Ocean beginning around 1500 BCE, developed an extraordinarily sophisticated system of wayfinding that used the positions of stars, the patterns of ocean swells, the behaviour of seabirds, and the colour of clouds to navigate thousands of kilometres of open ocean without instruments. In the Mediterranean, Phoenician sailors used the North Star (Polaris) as a fixed reference point, enabling reliable north-south orientation during night voyages.

The magnetic compass, one of the most consequential navigational inventions, originated in China during the Han Dynasty (206 BCE–220 CE), where magnetised lodestones were initially used for geomancy and divination. By the eleventh century, Chinese mariners were using magnetic compasses for maritime navigation, and the technology reached Europe by the twelfth century, probably through Arab intermediaries. The compass liberated sailors from dependence on clear skies, enabling navigation in overcast conditions and during extended ocean crossings.

The Age of Exploration in the fifteenth and sixteenth centuries demanded more precise navigational tools. The astrolabe, an ancient instrument refined by Islamic astronomers, allowed navigators to measure the altitude of celestial bodies above the horizon, from which latitude could be calculated. The cross-staff and later the backstaff served similar purposes with varying degrees of accuracy. However, determining longitude — one's east-west position — remained an intractable problem that plagued navigators for centuries and caused countless shipwrecks.

The longitude problem was finally solved by John Harrison, an English clockmaker who devoted his life to building marine chronometers sufficiently accurate to keep time at sea. Since the Earth rotates fifteen degrees per hour, comparing local solar time with the time at a known reference meridian (Greenwich) yields the observer's longitude. Harrison's fourth chronometer, tested on a voyage to Jamaica in 1761, lost only five seconds over eighty-one days — a revolutionary achievement that transformed oceanic navigation.

The nineteenth and twentieth centuries brought further innovations. The sextant, which replaced earlier altitude-measuring instruments, remained the primary tool of celestial navigation until the mid-twentieth century. Radio navigation systems, beginning with radio direction finding in the early 1900s and evolving through LORAN (Long Range Navigation) and Omega, provided electronic position fixing that supplemented and gradually replaced celestial methods.

The Global Positioning System (GPS), developed by the United States Department of Defense and fully operational by 1995, represents the current pinnacle of navigational technology. A constellation of at least twenty-four satellites orbiting the Earth transmits precisely timed signals that GPS receivers use to calculate their position anywhere on the planet with accuracy typically within a few metres. GPS has become so ubiquitous that it underpins not only personal navigation but also aviation, shipping, precision agriculture, emergency services, and the synchronisation of global telecommunications networks. The European Galileo, Russian GLONASS, and Chinese BeiDou systems provide complementary global coverage, reducing dependence on any single system.

Despite the convenience of satellite navigation, concerns have emerged about over-reliance on electronic systems. GPS signals are vulnerable to jamming, spoofing, and solar interference, and several incidents involving ships and aircraft navigating into danger due to GPS errors have highlighted the continued importance of traditional navigational skills. Naval academies have reintroduced celestial navigation training, and experts advocate maintaining competence in non-electronic methods as a critical backup.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "How did Polynesian voyagers navigate the Pacific Ocean?", options: ["A Using magnetic compasses imported from China", "B By following written maps passed down through generations", "C Using stars, ocean swells, seabirds, and cloud patterns", "D By staying within sight of coastlines at all times"], correctAnswer: "C", explanation: "The passage describes their system using 'positions of stars, patterns of ocean swells, behaviour of seabirds, and colour of clouds.'" },
        { number: 2, type: "multiple_choice", text: "What was the original use of magnetised lodestones in China?", options: ["A Maritime navigation", "B Military strategy", "C Geomancy and divination", "D Architectural planning"], correctAnswer: "C", explanation: "The passage states lodestones 'were initially used for geomancy and divination.'" },
        { number: 3, type: "multiple_choice", text: "How does GPS calculate a user's position?", options: ["A By measuring magnetic field variations", "B By using precisely timed satellite signals", "C By triangulating radio tower signals", "D By comparing star positions to a database"], correctAnswer: "B", explanation: "The passage says GPS 'transmits precisely timed signals that GPS receivers use to calculate their position.'" },
        { number: 4, type: "multiple_choice", text: "Why have naval academies reintroduced celestial navigation training?", options: ["A Because GPS satellites are being decommissioned", "B Because celestial navigation is more accurate than GPS", "C Because GPS is vulnerable to jamming and errors", "D Because international law requires it"], correctAnswer: "C", explanation: "The passage discusses GPS vulnerability to 'jamming, spoofing, and solar interference.'" },
        { number: 5, type: "true_false_not_given", text: "The magnetic compass reached Europe through Arab intermediaries.", correctAnswer: "TRUE", explanation: "The passage says the technology 'reached Europe by the twelfth century, probably through Arab intermediaries.'" },
        { number: 6, type: "true_false_not_given", text: "The astrolabe was invented by European navigators during the Age of Exploration.", correctAnswer: "FALSE", explanation: "The passage describes it as 'an ancient instrument refined by Islamic astronomers.'" },
        { number: 7, type: "true_false_not_given", text: "Harrison's fourth chronometer lost only five seconds over eighty-one days.", correctAnswer: "TRUE", explanation: "The passage states exactly this." },
        { number: 8, type: "true_false_not_given", text: "GPS was originally developed for commercial aviation purposes.", correctAnswer: "FALSE", explanation: "The passage says it was 'developed by the United States Department of Defense.'" },
        { number: 9, type: "true_false_not_given", text: "The Phoenicians were the first civilisation to use celestial navigation.", correctAnswer: "NOT GIVEN", explanation: "The passage mentions Phoenician use of Polaris but does not claim they were the first." },
        { number: 10, type: "true_false_not_given", text: "LORAN is still widely used for maritime navigation today.", correctAnswer: "NOT GIVEN", explanation: "The passage mentions LORAN historically but does not state its current status." },
        { number: 11, type: "true_false_not_given", text: "GPS became fully operational in 1995.", correctAnswer: "TRUE", explanation: "The passage states GPS was 'fully operational by 1995.'" },
        { number: 12, type: "true_false_not_given", text: "The BeiDou system was developed by Japan.", correctAnswer: "FALSE", explanation: "The passage identifies BeiDou as 'Chinese.'" },
        { number: 13, type: "true_false_not_given", text: "At least twenty-four satellites make up the GPS constellation.", correctAnswer: "TRUE", explanation: "The passage states 'at least twenty-four satellites.'" },
      ],
    },
    {
      title: "Endangered Species",
      text: `A. The current rate of species extinction is estimated to be one hundred to one thousand times higher than the natural background rate, leading many scientists to describe the present era as the sixth mass extinction in Earth's history. Unlike previous mass extinctions, which were triggered by asteroid impacts, volcanic eruptions, or natural climate shifts, the current crisis is driven almost entirely by human activity. Habitat destruction, overexploitation, pollution, invasive species, and climate change are pushing thousands of species toward the brink of disappearance.

B. Habitat loss is the single greatest threat to global biodiversity. The conversion of forests, wetlands, grasslands, and coral reefs into agricultural land, urban areas, and infrastructure eliminates the ecosystems upon which species depend for food, shelter, and reproduction. Tropical deforestation is particularly devastating, given that tropical forests harbour an estimated fifty to seventy-five per cent of all terrestrial species despite covering only six per cent of the Earth's land surface. Fragmentation of remaining habitat into isolated patches further imperils species by reducing genetic diversity and limiting access to resources.

C. Overexploitation — the harvesting of wildlife at rates exceeding their capacity to reproduce — threatens numerous species. Commercial fishing has depleted many marine fish stocks to critical levels; the International Union for Conservation of Nature (IUCN) estimates that over one-third of shark and ray species are threatened with extinction due to overfishing. The illegal wildlife trade, worth an estimated twenty billion dollars annually, drives the poaching of elephants for ivory, rhinoceroses for horn, and pangolins for scales, pushing these iconic species toward extinction despite international prohibitions.

D. Climate change is emerging as an increasingly dominant threat to biodiversity. Rising temperatures alter habitats faster than many species can adapt or migrate. Polar bears depend on sea ice for hunting seals, yet Arctic sea ice extent has declined by approximately thirteen per cent per decade since satellite measurements began in 1979. Coral reefs, which support roughly twenty-five per cent of marine species, are experiencing mass bleaching events with increasing frequency. Mountain-dwelling species are being forced to higher elevations, where habitat area diminishes progressively — a phenomenon scientists describe as being pushed toward an "escalator to extinction."

E. Invasive species represent another major threat. Species introduced to new environments, whether deliberately or accidentally, can outcompete, prey upon, or transmit diseases to native species that have no evolutionary defences against them. The brown tree snake, accidentally introduced to Guam after World War II, has driven the extinction of most of the island's native forest birds. The chytrid fungus, spread globally through the international amphibian trade, has caused dramatic population declines in over five hundred amphibian species and the presumed extinction of at least ninety.

F. Conservation strategies operate at multiple scales. Protected areas — national parks, wildlife reserves, and marine sanctuaries — form the backbone of global conservation efforts, currently covering approximately fifteen per cent of terrestrial and eight per cent of marine environments. The Convention on Biological Diversity's target of protecting thirty per cent of land and ocean by 2030 has gained widespread political support. However, the effectiveness of protected areas depends critically on adequate funding, enforcement, and community engagement.

G. Captive breeding and reintroduction programmes have achieved notable successes. The California condor, reduced to just twenty-two individuals in 1987, has been bred in captivity and reintroduced to the wild, with the population now exceeding five hundred. The Arabian oryx, declared extinct in the wild in 1972, was similarly rescued through captive breeding and now roams freely in protected reserves across the Arabian Peninsula. These programmes are resource-intensive and cannot substitute for habitat preservation, but they provide a critical safety net for species on the edge of extinction.

H. Genetic technologies offer new tools for conservation. Environmental DNA (eDNA) sampling enables scientists to detect the presence of rare species by analysing trace genetic material in water or soil samples, revolutionising biodiversity monitoring. Gene banking preserves the genetic material of threatened species for potential future use, while emerging gene-editing technologies raise the theoretical possibility of de-extinction — bringing back species that have already disappeared. However, de-extinction remains controversial and technically challenging, and most conservation biologists argue that preventing extinction in the first place is far more effective and ethical.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Section A", options: ["I. The primary cause of species decline worldwide", "II. An unprecedented wave of species loss", "III. Unsustainable harvesting of wildlife", "IV. Shifting climates and vulnerable species", "V. Foreign species disrupting native ecosystems", "VI. Protecting land and sea for wildlife", "VII. Breeding programmes that saved species from extinction", "VIII. New scientific tools for conservation"], correctAnswer: "II", explanation: "Section A describes the current mass extinction crisis." },
        { number: 15, type: "matching_headings", text: "Section B", options: ["I. The primary cause of species decline worldwide", "II. An unprecedented wave of species loss", "III. Unsustainable harvesting of wildlife", "IV. Shifting climates and vulnerable species", "V. Foreign species disrupting native ecosystems", "VI. Protecting land and sea for wildlife", "VII. Breeding programmes that saved species from extinction", "VIII. New scientific tools for conservation"], correctAnswer: "I", explanation: "Section B discusses habitat loss as the greatest threat." },
        { number: 16, type: "matching_headings", text: "Section C", options: ["I. The primary cause of species decline worldwide", "II. An unprecedented wave of species loss", "III. Unsustainable harvesting of wildlife", "IV. Shifting climates and vulnerable species", "V. Foreign species disrupting native ecosystems", "VI. Protecting land and sea for wildlife", "VII. Breeding programmes that saved species from extinction", "VIII. New scientific tools for conservation"], correctAnswer: "III", explanation: "Section C discusses overexploitation and wildlife trade." },
        { number: 17, type: "matching_headings", text: "Section D", options: ["I. The primary cause of species decline worldwide", "II. An unprecedented wave of species loss", "III. Unsustainable harvesting of wildlife", "IV. Shifting climates and vulnerable species", "V. Foreign species disrupting native ecosystems", "VI. Protecting land and sea for wildlife", "VII. Breeding programmes that saved species from extinction", "VIII. New scientific tools for conservation"], correctAnswer: "IV", explanation: "Section D discusses climate change impacts on species." },
        { number: 18, type: "matching_headings", text: "Section E", options: ["I. The primary cause of species decline worldwide", "II. An unprecedented wave of species loss", "III. Unsustainable harvesting of wildlife", "IV. Shifting climates and vulnerable species", "V. Foreign species disrupting native ecosystems", "VI. Protecting land and sea for wildlife", "VII. Breeding programmes that saved species from extinction", "VIII. New scientific tools for conservation"], correctAnswer: "V", explanation: "Section E discusses invasive species." },
        { number: 19, type: "matching_headings", text: "Section G", options: ["I. The primary cause of species decline worldwide", "II. An unprecedented wave of species loss", "III. Unsustainable harvesting of wildlife", "IV. Shifting climates and vulnerable species", "V. Foreign species disrupting native ecosystems", "VI. Protecting land and sea for wildlife", "VII. Breeding programmes that saved species from extinction", "VIII. New scientific tools for conservation"], correctAnswer: "VII", explanation: "Section G discusses captive breeding successes." },
        { number: 20, type: "table_completion", text: "The illegal wildlife trade is worth an estimated __(20)__ billion dollars annually.", correctAnswer: "twenty", explanation: "The passage states 'twenty billion dollars annually.'" },
        { number: 21, type: "table_completion", text: "Arctic sea ice has declined by approximately __(21)__ per cent per decade.", correctAnswer: "thirteen", explanation: "The passage states 'approximately thirteen per cent per decade.'" },
        { number: 22, type: "table_completion", text: "The California condor population was reduced to just __(22)__ individuals in 1987.", correctAnswer: "twenty-two", explanation: "The passage states 'just twenty-two individuals in 1987.'" },
        { number: 23, type: "table_completion", text: "Protected areas currently cover approximately __(23)__ per cent of terrestrial environments.", correctAnswer: "fifteen", explanation: "The passage states 'approximately fifteen per cent of terrestrial.'" },
        { number: 24, type: "short_answer", text: "What snake species caused the extinction of most native forest birds on Guam?", correctAnswer: "brown tree snake", explanation: "The passage names 'The brown tree snake.'" },
        { number: 25, type: "short_answer", text: "What fungus has caused dramatic population declines in amphibian species?", correctAnswer: "chytrid fungus", explanation: "The passage mentions 'The chytrid fungus.'" },
        { number: 26, type: "short_answer", text: "What technique analyses trace genetic material in water or soil to detect rare species?", correctAnswer: "eDNA sampling", explanation: "The passage describes 'Environmental DNA (eDNA) sampling.'" },
      ],
    },
    {
      title: "Biotechnology in Medicine",
      text: `Biotechnology — the application of biological systems and organisms to develop products and technologies — has revolutionised medicine over the past half-century, enabling treatments and diagnostics that were previously inconceivable. From genetically engineered insulin to gene therapy and mRNA vaccines, biotechnological innovations are extending human lifespans, improving quality of life, and offering hope for conditions once considered untreatable.

A. The modern biotechnology era began in 1973, when Stanley Cohen and Herbert Boyer developed recombinant DNA technology — a method for combining genetic material from different organisms. This breakthrough enabled the production of human proteins in bacterial cells, leading to the first commercially available biotechnology product: synthetic human insulin, marketed by Genentech and Eli Lilly in 1982. Before recombinant insulin, diabetic patients relied on insulin extracted from pig and cow pancreases, which sometimes caused allergic reactions. Today, virtually all insulin worldwide is produced using recombinant DNA technology, ensuring a safe and virtually unlimited supply.

B. Monoclonal antibodies represent one of the most successful classes of biotechnology-derived medicines. These laboratory-produced molecules are designed to bind to specific targets on cells or proteins, enabling precisely targeted therapies. Herceptin (trastuzumab), developed for HER2-positive breast cancer, exemplifies the power of this approach: by targeting a specific receptor overexpressed on cancer cells, it significantly improves survival rates while minimising damage to healthy tissue. The monoclonal antibody market exceeded $200 billion annually by 2022, with applications spanning oncology, autoimmune diseases, and infectious diseases.

C. Gene therapy aims to treat disease by modifying the genetic material within a patient's cells. The concept is straightforward: if a disease is caused by a defective gene, replacing or correcting that gene should cure the disease. Early clinical trials in the 1990s were marred by serious adverse events, including the death of patient Jesse Gelsinger in 1999, which prompted a period of intense regulatory scrutiny and public scepticism. However, persistent research has yielded remarkable successes. Luxturna, approved in 2017, restores vision in patients with a rare inherited form of blindness by delivering a functional copy of the RPE65 gene directly to retinal cells. Zolgensma, approved in 2019, treats spinal muscular atrophy — a devastating childhood disease — with a single intravenous infusion, at a list price of approximately $2.1 million, making it one of the most expensive medicines ever marketed.

D. The CRISPR-Cas9 gene-editing system, adapted from a natural bacterial immune defence mechanism, has transformed genetic research since its development as a genome-editing tool in 2012 by Jennifer Doudna and Emmanuelle Charpentier. CRISPR enables scientists to make precise changes to DNA sequences with unprecedented ease and affordability. In December 2023, the first CRISPR-based therapy — Casgevy, for sickle cell disease and beta-thalassemia — received regulatory approval in the United Kingdom and the United States, marking a historic milestone. CRISPR is also being explored for treating cancer, HIV, and hereditary conditions, though concerns about off-target edits and germline modifications remain subjects of intense ethical debate.

E. The COVID-19 pandemic dramatically accelerated the development of mRNA vaccine technology. Messenger RNA vaccines, developed by Pfizer-BioNTech and Moderna, instruct human cells to produce a harmless viral protein that triggers an immune response, providing protection against infection. The speed of their development — from viral genome sequencing to emergency use authorisation in under eleven months — was unprecedented in the history of vaccinology. The success of mRNA vaccines has opened the door to applications beyond infectious disease, including personalised cancer vaccines that are tailored to the specific mutations present in an individual patient's tumour.

F. Regenerative medicine, encompassing stem cell therapies and tissue engineering, seeks to repair or replace damaged tissues and organs. Induced pluripotent stem cells (iPSCs), created by reprogramming adult cells to an embryonic-like state, avoid the ethical controversies associated with embryonic stem cells while offering similar therapeutic potential. Researchers have used iPSCs to generate functional heart cells, liver cells, and neurons in the laboratory, and clinical trials are underway for conditions including Parkinson's disease, macular degeneration, and heart failure. Three-dimensional bioprinting technology, which deposits layers of living cells to construct tissue structures, holds the long-term promise of producing transplantable organs on demand.

G. Diagnostic biotechnology has advanced in parallel with therapeutic applications. Polymerase chain reaction (PCR), invented by Kary Mullis in 1983, amplifies tiny quantities of DNA to detectable levels, enabling the diagnosis of genetic diseases, infectious agents, and forensic identification. Next-generation sequencing (NGS) technologies have reduced the cost of sequencing a complete human genome from approximately $3 billion for the Human Genome Project to under $200 today, enabling the emergence of precision medicine — an approach that tailors treatment decisions to individual genetic profiles.

H. The ethical, regulatory, and economic challenges facing medical biotechnology are substantial. Access to expensive biotechnology treatments remains deeply inequitable, with many innovations available only in wealthy nations. The prospect of human germline editing — making heritable genetic changes that would be passed to future generations — raises profound questions about consent, eugenics, and the boundaries of medical intervention. Navigating these challenges will require robust international regulatory frameworks, transparent public dialogue, and a commitment to ensuring that the benefits of biotechnology are shared broadly across humanity.`,
      questions: [
        { number: 27, type: "matching_information", text: "The development of the first commercially available biotechnology medicine", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "A", explanation: "Section A discusses recombinant human insulin, the first biotech product." },
        { number: 28, type: "matching_information", text: "A gene-editing therapy approved for a blood disorder", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "D", explanation: "Section D discusses Casgevy for sickle cell disease." },
        { number: 29, type: "matching_information", text: "The use of reprogrammed adult cells to avoid ethical controversies", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "F", explanation: "Section F discusses iPSCs." },
        { number: 30, type: "matching_information", text: "A discussion of the high cost of biotechnology treatments and global inequality", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "H", explanation: "Section H discusses access inequality." },
        { number: 31, type: "matching_information", text: "The dramatic reduction in the cost of sequencing a human genome", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "G", explanation: "Section G discusses genome sequencing costs falling from $3 billion to under $200." },
        { number: 32, type: "matching_information", text: "A cancer treatment that targets specific receptors on tumour cells", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "B", explanation: "Section B discusses Herceptin targeting HER2 receptors." },
        { number: 33, type: "multiple_choice", text: "What was the first biotechnology product to be commercially available?", options: ["A Monoclonal antibodies", "B mRNA vaccines", "C Synthetic human insulin", "D CRISPR-based therapy"], correctAnswer: "C", explanation: "The passage says synthetic human insulin was 'the first commercially available biotechnology product.'" },
        { number: 34, type: "multiple_choice", text: "Why did gene therapy face setbacks in the 1990s?", options: ["A The technology was too expensive.", "B Serious adverse events occurred, including a patient death.", "C No suitable diseases were identified for treatment.", "D Governments banned all gene therapy research."], correctAnswer: "B", explanation: "The passage mentions 'serious adverse events, including the death of patient Jesse Gelsinger.'" },
        { number: 35, type: "multiple_choice", text: "How do mRNA vaccines work?", options: ["A They inject weakened viruses into the body.", "B They instruct cells to produce a viral protein that triggers immunity.", "C They directly kill virus particles in the bloodstream.", "D They modify the patient's DNA permanently."], correctAnswer: "B", explanation: "The passage states mRNA vaccines 'instruct human cells to produce a harmless viral protein that triggers an immune response.'" },
        { number: 36, type: "multiple_choice", text: "What is the current cost of sequencing a complete human genome?", options: ["A Approximately $3 billion", "B Approximately $10,000", "C Under $200", "D Approximately $2.1 million"], correctAnswer: "C", explanation: "The passage states 'under $200 today.'" },
        { number: 37, type: "sentence_completion", text: "CRISPR-Cas9 was developed as a genome-editing tool in 2012 by Jennifer Doudna and Emmanuelle __(37)__.", correctAnswer: "Charpentier", explanation: "The passage names 'Emmanuelle Charpentier.'" },
        { number: 38, type: "sentence_completion", text: "Zolgensma treats spinal muscular atrophy at a list price of approximately $__(38)__ million.", correctAnswer: "2.1", explanation: "The passage states 'approximately $2.1 million.'" },
        { number: 39, type: "sentence_completion", text: "PCR was invented by Kary __(39)__ in 1983.", correctAnswer: "Mullis", explanation: "The passage names 'Kary Mullis.'" },
        { number: 40, type: "sentence_completion", text: "Three-dimensional __(40)__ technology deposits layers of living cells to construct tissue structures.", correctAnswer: "bioprinting", explanation: "The passage mentions 'Three-dimensional bioprinting technology.'" },
      ],
    },
  ],
};
