import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_44: ReadingTest = {
  id: 44,
  passages: [
    {
      title: "Ancient Civilizations",
      text: `The emergence of complex civilisations is one of the most remarkable developments in human history. Beginning around 3500 BCE, independent societies in different parts of the world made the transition from small, nomadic bands to large, settled communities with specialised labour, monumental architecture, writing systems, and centralised governance. This transformation, often called the Urban Revolution, occurred not once but multiple times, in the river valleys of Mesopotamia, Egypt, the Indus, and China, as well as in Mesoamerica and the Andes.

Mesopotamia, located between the Tigris and Euphrates rivers in present-day Iraq, is widely regarded as the cradle of civilisation. By 3500 BCE, the Sumerians had established city-states such as Ur, Uruk, and Eridu, each centred on a monumental temple complex known as a ziggurat. Sumerian society was stratified into priests, warriors, merchants, artisans, and farmers, and its economy was organised around a system of centralised redistribution managed by temple administrators. The Sumerians invented cuneiform, one of the earliest writing systems, initially as a tool for recording economic transactions but eventually adapted for literature, law, and science. The Epic of Gilgamesh, composed in cuneiform around 2100 BCE, is the oldest known work of literary fiction.

Ancient Egypt developed along the narrow, fertile floodplain of the Nile River. The annual inundation of the Nile deposited nutrient-rich silt that sustained intensive agriculture, enabling a relatively small geographical area to support a large and prosperous population. Egyptian civilisation was characterised by extraordinary continuity: the pharaonic system of divine kingship endured for more than three thousand years, from the unification of Upper and Lower Egypt around 3100 BCE to the Roman conquest in 30 BCE. The construction of the pyramids at Giza — the largest of which, the Great Pyramid of Khufu, originally stood 146 metres tall and was built from approximately 2.3 million limestone blocks — remains one of the most impressive feats of ancient engineering.

The Indus Valley Civilisation, also known as the Harappan civilisation, flourished from approximately 2600 to 1900 BCE across a vast area of present-day Pakistan and northwestern India. Its two largest cities, Mohenjo-daro and Harappa, were remarkable for their urban planning: streets were laid out in a grid pattern, houses were built of standardised fired bricks, and an advanced drainage system carried wastewater from individual homes to covered street drains. The Indus script, found on thousands of seals and tablets, has never been deciphered, leaving many aspects of Harappan culture — including its political organisation and religious beliefs — shrouded in mystery.

Ancient Chinese civilisation emerged along the Yellow River during the Shang dynasty, roughly 1600 to 1046 BCE. The Shang are notable for their mastery of bronze casting, their use of oracle bones for divination, and their development of an early form of Chinese writing. The subsequent Zhou dynasty introduced the concept of the Mandate of Heaven, a philosophical justification for dynastic rule that profoundly influenced Chinese political thought for over two millennia.

In Mesoamerica, the Olmec civilisation, which flourished from approximately 1500 to 400 BCE along the Gulf Coast of present-day Mexico, is often considered the mother culture of later Mesoamerican societies. The Olmec are known for their colossal stone heads — massive basalt sculptures weighing up to fifty tonnes — and for innovations in writing, calendar systems, and ceremonial architecture that influenced the Maya and Aztec civilisations. The Maya, whose classical period lasted from roughly 250 to 900 CE, developed a fully phonetic writing system, a sophisticated mathematical notation including the concept of zero, and astronomical observations of extraordinary precision.

These early civilisations, despite developing independently and often in isolation from one another, share striking similarities: the management of water resources, the construction of monumental buildings, the invention of writing, the codification of law, and the emergence of social hierarchies. These parallels suggest that certain organisational responses to the challenges of large-scale settled life may be universal features of human social evolution.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "What is Mesopotamia widely regarded as?", options: ["A The largest ancient empire", "B The cradle of civilisation", "C The birthplace of democracy", "D The origin of agriculture"], correctAnswer: "B", explanation: "The passage says Mesopotamia 'is widely regarded as the cradle of civilisation.'" },
        { number: 2, type: "multiple_choice", text: "What is the oldest known work of literary fiction?", options: ["A The Iliad", "B The Book of the Dead", "C The Epic of Gilgamesh", "D The Vedas"], correctAnswer: "C", explanation: "The passage says 'The Epic of Gilgamesh... is the oldest known work of literary fiction.'" },
        { number: 3, type: "multiple_choice", text: "What is notable about the cities of the Indus Valley Civilisation?", options: ["A Their massive pyramids", "B Their grid-pattern streets and drainage systems", "C Their use of bronze weapons", "D Their extensive libraries"], correctAnswer: "B", explanation: "The passage describes 'streets laid out in a grid pattern' and 'an advanced drainage system.'" },
        { number: 4, type: "multiple_choice", text: "What concept did the Zhou dynasty introduce?", options: ["A Cuneiform writing", "B The ziggurat", "C The Mandate of Heaven", "D Oracle bone divination"], correctAnswer: "C", explanation: "The passage says 'The subsequent Zhou dynasty introduced the concept of the Mandate of Heaven.'" },
        { number: 5, type: "true_false_not_given", text: "The Sumerians invented cuneiform primarily for literary purposes.", correctAnswer: "FALSE", explanation: "The passage says cuneiform was 'initially as a tool for recording economic transactions.'" },
        { number: 6, type: "true_false_not_given", text: "The Great Pyramid of Khufu was built from approximately 2.3 million blocks.", correctAnswer: "TRUE", explanation: "The passage says 'approximately 2.3 million limestone blocks.'" },
        { number: 7, type: "true_false_not_given", text: "The Indus script has been fully deciphered.", correctAnswer: "FALSE", explanation: "The passage says the Indus script 'has never been deciphered.'" },
        { number: 8, type: "true_false_not_given", text: "The Shang dynasty mastered iron casting.", correctAnswer: "FALSE", explanation: "The passage says 'mastery of bronze casting,' not iron." },
        { number: 9, type: "true_false_not_given", text: "The Olmec colossal heads weigh up to fifty tonnes.", correctAnswer: "TRUE", explanation: "The passage says 'weighing up to fifty tonnes.'" },
        { number: 10, type: "true_false_not_given", text: "The Maya developed a fully phonetic writing system.", correctAnswer: "TRUE", explanation: "The passage says the Maya 'developed a fully phonetic writing system.'" },
        { number: 11, type: "true_false_not_given", text: "The Roman conquest of Egypt occurred in 30 CE.", correctAnswer: "FALSE", explanation: "The passage says '30 BCE,' not CE." },
        { number: 12, type: "true_false_not_given", text: "The Olmec influenced the Inca civilisation.", correctAnswer: "NOT GIVEN", explanation: "The passage mentions Olmec influencing Maya and Aztec, not Inca." },
        { number: 13, type: "true_false_not_given", text: "All early civilisations developed writing systems.", correctAnswer: "TRUE", explanation: "The passage says they share 'the invention of writing' as a common feature." },
      ],
    },
    {
      title: "Global Warming Effects",
      text: `A. The Earth's average surface temperature has risen by approximately 1.1 degrees Celsius since the pre-industrial era, driven primarily by the burning of fossil fuels, deforestation, and industrial agriculture. This seemingly modest figure masks dramatic regional variations and belies the severity of the changes already under way. The Arctic, for instance, is warming at roughly four times the global average, and the consequences — melting sea ice, thawing permafrost, and collapsing ice sheets — are cascading through ecosystems and communities around the world.

B. Rising temperatures are accelerating the melting of the world's ice. The Greenland Ice Sheet is losing mass at an average rate of approximately 280 billion tonnes per year, and the Antarctic Ice Sheet is losing roughly 150 billion tonnes per year. Mountain glaciers, which provide freshwater to billions of people, are retreating on every continent. The Himalayan glaciers, which feed rivers such as the Ganges, Indus, and Brahmaputra, could lose up to two-thirds of their volume by 2100 if global emissions are not sharply reduced, threatening the water supply of approximately 1.6 billion people.

C. Sea-level rise is one of the most consequential effects of global warming. As ice sheets and glaciers melt and ocean water expands due to thermal expansion, global mean sea level has risen by approximately twenty centimetres since 1900 and is currently rising at roughly 3.7 millimetres per year — a rate that is accelerating. The Intergovernmental Panel on Climate Change (IPCC) projects that sea levels could rise by forty-three to eighty-four centimetres by 2100 under high-emission scenarios, inundating low-lying coastal areas, displacing millions of people, and threatening critical infrastructure in cities from Miami to Mumbai to Shanghai.

D. Extreme weather events are becoming more frequent and more severe. Heatwaves that were once-in-fifty-year events are now occurring roughly once every decade, and their intensity is increasing. The European heatwave of 2023 was attributed to climate change by multiple attribution studies and caused more than 60,000 excess deaths. Heavy rainfall events have intensified because a warmer atmosphere holds approximately seven per cent more moisture for each degree of warming, increasing the risk of flash floods and landslides. Tropical cyclones, while not necessarily more frequent, are producing stronger winds and heavier rainfall as sea-surface temperatures rise.

E. Ecosystems are under profound stress. Coral reefs, which support approximately twenty-five per cent of all marine species, are experiencing mass bleaching events with increasing regularity. The Great Barrier Reef has suffered five mass bleaching events since 2016. On land, forests are being weakened by drought and heat stress, making them more vulnerable to wildfires and insect outbreaks. The boreal forests of Canada and Siberia experienced record-breaking wildfire seasons in 2023, releasing vast quantities of carbon dioxide that further amplify global warming — a dangerous feedback loop.

F. Agriculture is being affected in complex ways. While higher carbon dioxide concentrations can enhance photosynthesis and boost crop yields in some regions, the negative effects of warming — increased drought, heat stress during critical growth stages, and the proliferation of pests and diseases — generally outweigh the benefits. The IPCC estimates that global crop yields have already been reduced by approximately five per cent relative to what they would have been without climate change, and further warming is projected to reduce yields of staple crops such as wheat, rice, and maize by up to twenty-five per cent by mid-century.

G. Human health is directly threatened. In addition to the immediate dangers of heatwaves and extreme weather, warming temperatures are expanding the geographic range of disease-carrying insects. Mosquitoes capable of transmitting dengue fever, once confined to tropical regions, are now established in parts of southern Europe, and the altitude ceiling for malaria transmission in East African highlands is rising by approximately 6.5 metres per year. Air quality is worsening as higher temperatures increase ground-level ozone formation and wildfire smoke episodes become more frequent and prolonged.

H. Addressing global warming requires urgent and coordinated action on multiple fronts: rapid reduction of greenhouse-gas emissions through the transition to renewable energy, electrification of transport, and protection of forests; adaptation measures to protect vulnerable communities and infrastructure; and investment in technologies such as carbon capture and storage. The Paris Agreement, adopted in 2015, commits signatory nations to limiting warming to well below two degrees and pursuing efforts to limit it to 1.5 degrees. Meeting this goal will require transformative changes in energy systems, land use, and consumption patterns within the coming decade.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Section A", options: ["I. Rising sea levels", "II. The scale of global temperature increase", "III. Effects on food production", "IV. Health impacts of warming", "V. Loss of ice worldwide", "VI. Increasing extreme weather", "VII. Damage to natural ecosystems", "VIII. Actions needed to limit warming"], correctAnswer: "II", explanation: "Section A discusses the 1.1°C rise and regional variations." },
        { number: 15, type: "matching_headings", text: "Section B", options: ["I. Rising sea levels", "II. The scale of global temperature increase", "III. Effects on food production", "IV. Health impacts of warming", "V. Loss of ice worldwide", "VI. Increasing extreme weather", "VII. Damage to natural ecosystems", "VIII. Actions needed to limit warming"], correctAnswer: "V", explanation: "Section B discusses melting ice sheets and glaciers." },
        { number: 16, type: "matching_headings", text: "Section C", options: ["I. Rising sea levels", "II. The scale of global temperature increase", "III. Effects on food production", "IV. Health impacts of warming", "V. Loss of ice worldwide", "VI. Increasing extreme weather", "VII. Damage to natural ecosystems", "VIII. Actions needed to limit warming"], correctAnswer: "I", explanation: "Section C discusses sea-level rise." },
        { number: 17, type: "matching_headings", text: "Section D", options: ["I. Rising sea levels", "II. The scale of global temperature increase", "III. Effects on food production", "IV. Health impacts of warming", "V. Loss of ice worldwide", "VI. Increasing extreme weather", "VII. Damage to natural ecosystems", "VIII. Actions needed to limit warming"], correctAnswer: "VI", explanation: "Section D discusses extreme weather events." },
        { number: 18, type: "matching_headings", text: "Section E", options: ["I. Rising sea levels", "II. The scale of global temperature increase", "III. Effects on food production", "IV. Health impacts of warming", "V. Loss of ice worldwide", "VI. Increasing extreme weather", "VII. Damage to natural ecosystems", "VIII. Actions needed to limit warming"], correctAnswer: "VII", explanation: "Section E discusses ecosystem stress." },
        { number: 19, type: "matching_headings", text: "Section F", options: ["I. Rising sea levels", "II. The scale of global temperature increase", "III. Effects on food production", "IV. Health impacts of warming", "V. Loss of ice worldwide", "VI. Increasing extreme weather", "VII. Damage to natural ecosystems", "VIII. Actions needed to limit warming"], correctAnswer: "III", explanation: "Section F discusses agricultural impacts." },
        { number: 20, type: "summary_completion", text: "Earth's temperature has risen by approximately __(20)__ degrees Celsius since pre-industrial times.", correctAnswer: "1.1", explanation: "The passage says 'approximately 1.1 degrees Celsius.'" },
        { number: 21, type: "summary_completion", text: "The Greenland Ice Sheet loses approximately __(21)__ billion tonnes of mass per year.", correctAnswer: "280", explanation: "The passage says 'approximately 280 billion tonnes per year.'" },
        { number: 22, type: "summary_completion", text: "Sea level has risen by approximately __(22)__ centimetres since 1900.", correctAnswer: "twenty", explanation: "The passage says 'approximately twenty centimetres since 1900.'" },
        { number: 23, type: "summary_completion", text: "A warmer atmosphere holds approximately __(23)__ per cent more moisture per degree of warming.", correctAnswer: "seven", explanation: "The passage says 'approximately seven per cent more moisture.'" },
        { number: 24, type: "summary_completion", text: "Global crop yields have been reduced by approximately __(24)__ per cent due to climate change.", correctAnswer: "five", explanation: "The passage says 'reduced by approximately five per cent.'" },
        { number: 25, type: "summary_completion", text: "The altitude ceiling for malaria transmission is rising by approximately __(25)__ metres per year.", correctAnswer: "6.5", explanation: "The passage says 'approximately 6.5 metres per year.'" },
        { number: 26, type: "summary_completion", text: "The Paris Agreement was adopted in __(26)__.", correctAnswer: "2015", explanation: "The passage says 'adopted in 2015.'" },
      ],
    },
    {
      title: "Smart Cities",
      text: `The concept of the smart city has gained significant traction in the early twenty-first century as urban populations grow, resources become scarcer, and digital technologies offer new tools for managing the complexity of metropolitan life. At its core, a smart city uses information and communication technology (ICT), the Internet of Things (IoT), and data analytics to improve the efficiency of urban services, enhance the quality of life for residents, and reduce environmental impact.

A. Transportation is one of the most visible domains of smart-city innovation. Intelligent traffic management systems use real-time data from sensors, cameras, and connected vehicles to optimise signal timing, reduce congestion, and improve safety. Pittsburgh's Surtrac system, for example, uses AI to coordinate traffic signals across the city, reducing travel times by twenty-five per cent and vehicle emissions by twenty-one per cent. Smart parking systems guide drivers to available spaces using sensors embedded in the road surface, reducing the time spent circling for parking — which studies estimate accounts for roughly thirty per cent of urban traffic in some cities.

B. Energy management is another priority. Smart grids use digital communication to detect and react to changes in electricity demand, integrating renewable energy sources, battery storage, and electric-vehicle charging to balance supply and demand in real time. Barcelona has installed smart streetlights that dim automatically when no pedestrians are detected, reducing energy consumption by thirty per cent. Building management systems equipped with IoT sensors monitor temperature, lighting, and occupancy, adjusting heating, ventilation, and air conditioning (HVAC) systems to minimise energy waste.

C. Waste management has been transformed by smart technology. Sensor-equipped bins monitor fill levels and transmit data to a central platform that optimises collection routes, reducing the number of truck journeys and the associated fuel consumption and emissions. Seoul, South Korea, has introduced pay-as-you-throw systems using smart bins that weigh waste and charge residents accordingly, an approach that has reduced household waste generation by approximately thirty per cent. In some cities, underground pneumatic waste-collection systems transport refuse through networks of pipes to central processing points, eliminating the need for kerbside collection entirely.

D. Public safety applications include smart surveillance systems that use computer vision and machine learning to detect unusual behaviour, identify suspects, and alert emergency services. Predictive policing algorithms analyse crime data to forecast when and where offences are likely to occur, enabling more efficient deployment of officers. Critics, however, raise concerns about civil liberties, racial profiling, and the potential for mass surveillance in a smart city environment.

E. Healthcare delivery in smart cities benefits from telemedicine platforms, wearable health monitors, and AI-driven diagnostic tools. Remote patient monitoring allows individuals with chronic conditions to transmit vital signs — blood pressure, blood glucose, heart rate — to healthcare providers from home, reducing the need for hospital visits and enabling early intervention when readings indicate deterioration. Singapore's Smart Health TeleRehab programme, for example, uses video consultations and wearable sensors to deliver physiotherapy remotely, improving access for elderly and mobility-impaired residents.

F. Governance and citizen engagement are enhanced by digital platforms that enable residents to report problems, participate in planning decisions, and access public services online. Estonia, often cited as the world's most digitally advanced nation, offers virtually all government services electronically, from voting and tax filing to business registration and healthcare records. The e-Residency programme allows entrepreneurs anywhere in the world to establish and manage an EU-based company remotely.

G. The implementation of smart-city technologies raises important challenges. The digital divide — the gap between those who have access to technology and those who do not — risks creating a two-tier city in which the benefits of smart services accrue primarily to affluent, tech-savvy residents. Cybersecurity is a critical concern: interconnected urban systems present attractive targets for hackers, and a successful attack on a city's power grid, water supply, or traffic management system could have catastrophic consequences. Data governance — who collects, owns, and has access to the vast quantities of data generated by smart-city systems — must be addressed transparently to maintain public trust.

H. Despite these challenges, the momentum behind smart-city development is strong. The global smart-city market was valued at approximately $500 billion in 2022 and is projected to exceed $1 trillion by 2028. Cities from Copenhagen to Kigali are deploying smart technologies tailored to their specific needs and resources, demonstrating that the smart-city concept is adaptable to a wide range of economic, cultural, and climatic contexts. The ultimate measure of a smart city's success, however, will be not the sophistication of its technology but the wellbeing of its residents.`,
      questions: [
        { number: 27, type: "matching_information", text: "An AI system that has reduced travel times and emissions in a US city", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "A", explanation: "Paragraph A discusses Pittsburgh's Surtrac system." },
        { number: 28, type: "matching_information", text: "Concerns about surveillance and civil liberties", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "D", explanation: "Paragraph D raises concerns about civil liberties and mass surveillance." },
        { number: 29, type: "matching_information", text: "A country offering virtually all government services electronically", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "F", explanation: "Paragraph F discusses Estonia's digital governance." },
        { number: 30, type: "matching_information", text: "The risk of cyber attacks on urban infrastructure", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "G", explanation: "Paragraph G discusses cybersecurity concerns." },
        { number: 31, type: "matching_information", text: "Streetlights that adjust based on pedestrian presence", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "B", explanation: "Paragraph B mentions Barcelona's smart streetlights." },
        { number: 32, type: "matching_information", text: "A system that charges residents based on the weight of their waste", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "C", explanation: "Paragraph C discusses Seoul's pay-as-you-throw smart bins." },
        { number: 33, type: "flow_chart_completion", text: "Pittsburgh's Surtrac system reduced travel times by __(33)__ per cent.", correctAnswer: "twenty-five", explanation: "The passage says 'reducing travel times by twenty-five per cent.'" },
        { number: 34, type: "flow_chart_completion", text: "Barcelona's smart streetlights reduced energy consumption by __(34)__ per cent.", correctAnswer: "thirty", explanation: "The passage says 'reducing energy consumption by thirty per cent.'" },
        { number: 35, type: "flow_chart_completion", text: "Seoul's smart bins reduced household waste by approximately __(35)__ per cent.", correctAnswer: "thirty", explanation: "The passage says 'reduced household waste generation by approximately thirty per cent.'" },
        { number: 36, type: "flow_chart_completion", text: "The global smart-city market was valued at approximately $__(36)__ billion in 2022.", correctAnswer: "500", explanation: "The passage says 'approximately $500 billion in 2022.'" },
        { number: 37, type: "flow_chart_completion", text: "The market is projected to exceed $__(37)__ trillion by 2028.", correctAnswer: "1", explanation: "The passage says 'exceed $1 trillion by 2028.'" },
        { number: 38, type: "flow_chart_completion", text: "Smart parking studies show parking search accounts for roughly __(38)__ per cent of urban traffic.", correctAnswer: "thirty", explanation: "The passage says 'roughly thirty per cent of urban traffic.'" },
        { number: 39, type: "flow_chart_completion", text: "Singapore's TeleRehab programme uses video consultations and wearable __(39)__.", correctAnswer: "sensors", explanation: "The passage says 'video consultations and wearable sensors.'" },
        { number: 40, type: "flow_chart_completion", text: "Surtrac reduced vehicle emissions by __(40)__ per cent.", correctAnswer: "twenty-one", explanation: "The passage says 'vehicle emissions by twenty-one per cent.'" },
      ],
    },
  ],
};
