import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_11: ReadingTest = {
  id: 11,
  passages: [
    {
      title: "The Development of Libraries",
      text: `Libraries are among the oldest and most enduring institutions of human civilisation, serving as repositories of knowledge, centres of learning, and symbols of cultural achievement. The history of libraries stretches back over four millennia, and their evolution mirrors the broader development of writing, literacy, education, and technology across successive eras of human history.

The earliest known libraries were established in the ancient Near East. The most famous of these was the Library of Ashurbanipal, created in the seventh century BCE in the Assyrian capital of Nineveh, in what is now northern Iraq. King Ashurbanipal, an unusually literate ruler for his time, assembled a collection of over 30,000 clay tablets inscribed with cuneiform script, covering subjects ranging from literature and history to medicine, astronomy, and law. The collection included the Epic of Gilgamesh, one of the oldest works of literature in existence. The tablets were systematically catalogued and arranged by subject — an early form of library organisation that foreshadowed practices still used today.

In the classical world, the most celebrated library was the Great Library of Alexandria, founded in the third century BCE under the patronage of the Ptolemaic dynasty in Egypt. The Library of Alexandria aspired to collect copies of every book in the known world, and at its peak is believed to have housed between 400,000 and 700,000 scrolls. It was not merely a storehouse of texts but an active research institution, attached to the Mouseion (Museum), where scholars from across the Mediterranean world gathered to study, debate, and advance knowledge in fields such as mathematics, geography, astronomy, and medicine. The library's eventual destruction — the precise circumstances and date of which remain subjects of scholarly debate — is often cited as one of the greatest losses in intellectual history.

During the medieval period in Europe, libraries were predominantly maintained by religious institutions. Monasteries served as the primary centres of literacy and learning, and monastic scribes painstakingly copied manuscripts by hand, preserving classical texts that might otherwise have been lost during the upheavals that followed the fall of the Western Roman Empire. The Benedictine Rule, established by Saint Benedict of Nursia in the sixth century, required monks to spend several hours each day reading, which necessitated the maintenance of substantial book collections. Notable monastic libraries included those at Monte Cassino in Italy, Saint Gall in Switzerland, and Lindisfarne in England.

In the Islamic world, a parallel tradition of library development flourished during the Golden Age of Islam (roughly the eighth to fourteenth centuries). The House of Wisdom (Bayt al-Hikma) in Baghdad, established during the Abbasid caliphate in the ninth century, was one of the foremost centres of learning in the medieval world. Scholars at the House of Wisdom translated Greek, Persian, Indian, and Chinese texts into Arabic, making them accessible to a wider audience and adding original contributions in fields such as algebra, optics, and medicine. Libraries attached to mosques and madrasas spread throughout the Islamic world, from Córdoba in Spain to Samarkand in Central Asia.

The invention of the printing press by Johannes Gutenberg around 1440 transformed the nature of libraries by making books far cheaper and more widely available. The number of books in existence exploded: it is estimated that more books were produced in the fifty years following Gutenberg's invention than had been created by hand in the previous thousand years. Libraries grew rapidly in size and shifted from being exclusive preserves of the clergy and aristocracy to institutions serving a broader segment of society. The establishment of national libraries — such as the Bibliothèque nationale de France (founded 1461) and the British Museum Library (1753, now the British Library) — reflected the growing recognition of libraries as instruments of national culture and public education.

The concept of the free public library, open to all citizens regardless of wealth or social status, is a relatively modern development. Although some earlier libraries had been open to the public, the modern public library movement gained momentum in the mid-nineteenth century, particularly in Britain and the United States. The British Public Libraries Act of 1850 empowered local authorities to establish free libraries funded by taxation. In the United States, the industrialist Andrew Carnegie donated over $56 million between 1883 and 1929 to fund the construction of more than 2,500 public library buildings across the English-speaking world, fundamentally shaping the landscape of public library provision.

Today, libraries face both challenges and opportunities in the digital age. The rise of the internet and electronic publishing has transformed the way people access information, leading some commentators to question whether physical libraries remain relevant. Yet library usage statistics tell a different story: public libraries in many countries continue to attract millions of visitors each year, offering not only access to books but also digital resources, community programmes, educational workshops, and spaces for social interaction. Modern libraries are evolving into multi-purpose community hubs, embracing technology while maintaining their core mission of providing equitable access to information and knowledge for all.`,
      questions: [
        { number: 1, type: "true_false_not_given", text: "The Library of Ashurbanipal contained more than 50,000 clay tablets.", correctAnswer: "FALSE", explanation: "The passage states the collection comprised 'over 30,000 clay tablets,' not more than 50,000." },
        { number: 2, type: "true_false_not_given", text: "The tablets in Ashurbanipal's library were organised by subject.", correctAnswer: "TRUE", explanation: "The passage says 'The tablets were systematically catalogued and arranged by subject.'" },
        { number: 3, type: "true_false_not_given", text: "The Library of Alexandria was the largest building in ancient Egypt.", correctAnswer: "NOT GIVEN", explanation: "The passage does not make any claim about the physical size of the building." },
        { number: 4, type: "true_false_not_given", text: "Historians agree on exactly how the Library of Alexandria was destroyed.", correctAnswer: "FALSE", explanation: "The passage says 'the precise circumstances and date of which remain subjects of scholarly debate.'" },
        { number: 5, type: "true_false_not_given", text: "The Benedictine Rule required monks to spend time reading each day.", correctAnswer: "TRUE", explanation: "The passage states 'the Benedictine Rule required monks to spend several hours each day reading.'" },
        { number: 6, type: "true_false_not_given", text: "The House of Wisdom was larger than the Library of Alexandria.", correctAnswer: "NOT GIVEN", explanation: "The passage does not compare the sizes of these two institutions." },
        { number: 7, type: "true_false_not_given", text: "Gutenberg's printing press was invented before 1450.", correctAnswer: "TRUE", explanation: "The passage says the press was invented 'around 1440,' which is before 1450." },
        { number: 8, type: "sentence_completion", text: "The Library of Ashurbanipal was located in the Assyrian capital of _______.", correctAnswer: "Nineveh", explanation: "The passage states it was 'in the Assyrian capital of Nineveh.'" },
        { number: 9, type: "sentence_completion", text: "The Library of Alexandria is believed to have housed between 400,000 and _______ scrolls.", correctAnswer: "700,000", explanation: "The passage says 'between 400,000 and 700,000 scrolls.'" },
        { number: 10, type: "sentence_completion", text: "The Library of Alexandria was attached to an institution called the _______.", correctAnswer: "Mouseion", explanation: "The passage mentions 'attached to the Mouseion (Museum).'" },
        { number: 11, type: "sentence_completion", text: "The House of Wisdom was established during the _______ caliphate.", correctAnswer: "Abbasid", explanation: "The passage says 'established during the Abbasid caliphate.'" },
        { number: 12, type: "sentence_completion", text: "Andrew Carnegie funded the construction of more than _______ public library buildings.", correctAnswer: "2,500", explanation: "The passage states 'more than 2,500 public library buildings.'" },
        { number: 13, type: "sentence_completion", text: "The British Public Libraries Act of _______ allowed local authorities to create free libraries.", correctAnswer: "1850", explanation: "The passage mentions 'The British Public Libraries Act of 1850.'" },
      ],
    },
    {
      title: "Sustainable Agriculture",
      text: `A. The global food system faces a monumental challenge: feeding a population projected to reach nearly 10 billion by 2050 while simultaneously reducing agriculture's environmental footprint. Agriculture is responsible for approximately 26 percent of global greenhouse gas emissions, occupies about 50 percent of the world's habitable land, and accounts for 70 percent of freshwater withdrawals. The intensification of farming since the mid-twentieth century — often referred to as the Green Revolution — dramatically increased crop yields through the use of high-yielding varieties, synthetic fertilisers, chemical pesticides, and mechanised irrigation. However, these gains have come at a significant environmental cost, including soil degradation, water pollution, biodiversity loss, and the depletion of natural resources.

B. Organic farming is one of the most widely recognised approaches to sustainable agriculture. Organic systems prohibit the use of synthetic fertilisers, chemical pesticides, genetically modified organisms (GMOs), and growth hormones in livestock production. Instead, organic farmers rely on crop rotation, composting, biological pest control, and the use of natural fertilisers such as manure and bone meal to maintain soil fertility and manage pests. Proponents argue that organic farming improves soil health, enhances biodiversity, and reduces pollution of waterways. Critics, however, point out that organic yields are typically 20 to 25 percent lower than conventional yields, raising questions about whether organic methods can produce enough food to feed the world's growing population without requiring significantly more land.

C. Precision agriculture uses digital technologies to optimise crop production while minimising waste and environmental impact. GPS-guided tractors, drones, satellite imagery, and soil sensors enable farmers to monitor field conditions at a granular level, applying fertilisers, pesticides, and water precisely where and when they are needed. This targeted approach — sometimes described as "the right input, in the right amount, at the right time, in the right place" — can reduce fertiliser use by 15 to 20 percent and water consumption by up to 30 percent, while maintaining or even increasing yields. Machine learning algorithms are increasingly used to analyse the vast quantities of data generated by precision farming systems, providing actionable insights that help farmers make better decisions.

D. Agroforestry — the deliberate integration of trees and shrubs into crop and livestock farming systems — is gaining recognition as a strategy that can simultaneously enhance productivity, sequester carbon, and improve ecosystem resilience. In tropical regions, shade-grown coffee and cacao plantations, where crops are cultivated beneath a canopy of native trees, support significantly higher levels of biodiversity than sun-grown monocultures. In temperate regions, alley cropping — planting rows of trees between strips of annual crops — can reduce soil erosion, improve water retention, provide habitat for beneficial insects, and generate additional income from timber, fruit, or nut production. The IPCC has identified agroforestry as one of the most cost-effective land-based strategies for mitigating climate change.

E. Vertical farming and controlled environment agriculture (CEA) represent a radically different approach to food production, growing crops indoors in stacked layers under artificial lighting and precisely controlled temperature, humidity, and nutrient conditions. Vertical farms can produce crops year-round, independent of weather and season, using up to 95 percent less water and 99 percent less land than conventional field agriculture. Because crops are grown in sealed, sterile environments, pesticides are unnecessary. Leafy greens, herbs, and strawberries are currently the most commercially viable crops for vertical farming, though research is under way to extend the range of crops that can be grown economically in these systems. The primary challenge facing the vertical farming industry is its high energy consumption, particularly for artificial lighting, which makes it economically viable mainly in regions with low electricity costs or abundant renewable energy.

F. Regenerative agriculture goes beyond sustainability to actively restore degraded soils and ecosystems. Core practices include no-till or minimum-till farming, which avoids disturbing the soil structure; cover cropping, which involves planting non-commercial crops to protect and enrich the soil between growing seasons; and the integration of livestock into cropping systems through managed rotational grazing, which mimics natural grassland ecosystems. Advocates of regenerative agriculture argue that healthy soils can sequester significant quantities of atmospheric carbon, potentially turning farmland from a source of emissions into a carbon sink. Major food companies, including General Mills, Danone, and Nestlé, have committed to sourcing an increasing proportion of their ingredients from farms practising regenerative methods, signalling a growing commercial interest in this approach.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Paragraph B", options: ["i. Growing crops indoors in controlled environments", "ii. Farming without synthetic chemicals", "iii. Using technology to target farm inputs precisely", "iv. Combining trees with crop production", "v. The environmental cost of modern farming", "vi. Restoring degraded farmland through soil-focused practices", "vii. The role of artificial intelligence in agriculture", "viii. International policies on sustainable food production"], correctAnswer: "ii", explanation: "Paragraph B describes organic farming which prohibits synthetic fertilisers and chemical pesticides." },
        { number: 15, type: "matching_headings", text: "Paragraph C", options: ["i. Growing crops indoors in controlled environments", "ii. Farming without synthetic chemicals", "iii. Using technology to target farm inputs precisely", "iv. Combining trees with crop production", "v. The environmental cost of modern farming", "vi. Restoring degraded farmland through soil-focused practices", "vii. The role of artificial intelligence in agriculture", "viii. International policies on sustainable food production"], correctAnswer: "iii", explanation: "Paragraph C describes precision agriculture using GPS, drones, and sensors to optimise inputs." },
        { number: 16, type: "matching_headings", text: "Paragraph D", options: ["i. Growing crops indoors in controlled environments", "ii. Farming without synthetic chemicals", "iii. Using technology to target farm inputs precisely", "iv. Combining trees with crop production", "v. The environmental cost of modern farming", "vi. Restoring degraded farmland through soil-focused practices", "vii. The role of artificial intelligence in agriculture", "viii. International policies on sustainable food production"], correctAnswer: "iv", explanation: "Paragraph D describes agroforestry — integrating trees and shrubs into farming systems." },
        { number: 17, type: "matching_headings", text: "Paragraph E", options: ["i. Growing crops indoors in controlled environments", "ii. Farming without synthetic chemicals", "iii. Using technology to target farm inputs precisely", "iv. Combining trees with crop production", "v. The environmental cost of modern farming", "vi. Restoring degraded farmland through soil-focused practices", "vii. The role of artificial intelligence in agriculture", "viii. International policies on sustainable food production"], correctAnswer: "i", explanation: "Paragraph E discusses vertical farming and controlled environment agriculture." },
        { number: 18, type: "matching_headings", text: "Paragraph F", options: ["i. Growing crops indoors in controlled environments", "ii. Farming without synthetic chemicals", "iii. Using technology to target farm inputs precisely", "iv. Combining trees with crop production", "v. The environmental cost of modern farming", "vi. Restoring degraded farmland through soil-focused practices", "vii. The role of artificial intelligence in agriculture", "viii. International policies on sustainable food production"], correctAnswer: "vi", explanation: "Paragraph F describes regenerative agriculture focused on restoring soils." },
        { number: 19, type: "table_completion", text: "Agriculture is responsible for approximately _______ percent of global greenhouse gas emissions.", correctAnswer: "26", explanation: "Paragraph A states 'approximately 26 percent of global greenhouse gas emissions.'" },
        { number: 20, type: "table_completion", text: "Organic yields are typically _______ to 25 percent lower than conventional yields.", correctAnswer: "20", explanation: "The passage says 'organic yields are typically 20 to 25 percent lower.'" },
        { number: 21, type: "table_completion", text: "Precision agriculture can reduce fertiliser use by _______ to 20 percent.", correctAnswer: "15", explanation: "The passage states 'reduce fertiliser use by 15 to 20 percent.'" },
        { number: 22, type: "table_completion", text: "Precision agriculture can reduce water consumption by up to _______ percent.", correctAnswer: "30", explanation: "The passage says 'water consumption by up to 30 percent.'" },
        { number: 23, type: "table_completion", text: "Vertical farms can use up to _______ percent less water than conventional agriculture.", correctAnswer: "95", explanation: "The passage states 'up to 95 percent less water.'" },
        { number: 24, type: "table_completion", text: "Vertical farms use _______ percent less land than field agriculture.", correctAnswer: "99", explanation: "The passage says '99 percent less land.'" },
        { number: 25, type: "table_completion", text: "Agriculture occupies about _______ percent of the world's habitable land.", correctAnswer: "50", explanation: "Paragraph A states 'occupies about 50 percent of the world's habitable land.'" },
        { number: 26, type: "table_completion", text: "Agriculture accounts for _______ percent of global freshwater withdrawals.", correctAnswer: "70", explanation: "Paragraph A states 'accounts for 70 percent of freshwater withdrawals.'" },
      ],
    },
    {
      title: "Biotechnology Advances",
      text: `Biotechnology — the application of biological systems, living organisms, or their derivatives to develop products and processes for specific use — has emerged as one of the most transformative fields of science and technology in the twenty-first century. From the development of life-saving medicines and diagnostic tools to the engineering of crops that can withstand drought and disease, biotechnology is reshaping industries and offering solutions to some of humanity's most pressing challenges.

A. The sequencing of the human genome, completed in 2003 after thirteen years of international collaboration, was a landmark achievement that laid the foundation for a revolution in personalised medicine. The Human Genome Project identified approximately 20,500 protein-coding genes and mapped the three billion base pairs that make up human DNA. This knowledge has enabled scientists to identify genetic variants associated with diseases such as cancer, diabetes, Alzheimer's, and heart disease, paving the way for diagnostic tests that can assess an individual's risk of developing specific conditions. Pharmacogenomics — the study of how genes affect a person's response to drugs — is enabling doctors to prescribe medications tailored to a patient's genetic profile, improving efficacy and reducing adverse side effects. The cost of sequencing a human genome has plummeted from approximately $2.7 billion for the original project to under $200 today, making genomic analysis increasingly accessible.

B. CRISPR-Cas9, a gene-editing technology discovered in 2012, has revolutionised the ability of scientists to modify DNA with unprecedented precision, speed, and affordability. CRISPR (Clustered Regularly Interspaced Short Palindromic Repeats) is based on a natural defence mechanism used by bacteria to protect themselves against viral infections. Scientists have adapted this system to target specific sequences of DNA in any organism and cut, delete, replace, or insert genetic material with extraordinary accuracy. In medicine, CRISPR is being used in clinical trials to treat genetic disorders such as sickle cell disease and beta-thalassaemia, with early results showing remarkable success. In agriculture, CRISPR has been used to develop crop varieties with enhanced nutritional content, improved resistance to pests and diseases, and greater tolerance to environmental stresses such as drought and salinity.

C. Monoclonal antibody therapy represents one of the most significant advances in modern medicine. Monoclonal antibodies are laboratory-produced molecules engineered to mimic the immune system's ability to target and neutralise specific pathogens, cancer cells, or disease-causing proteins. Since the approval of the first therapeutic monoclonal antibody in 1986, the field has grown rapidly, with over 100 monoclonal antibody drugs now approved for clinical use worldwide. Applications include the treatment of cancers (such as breast cancer and lymphoma), autoimmune diseases (such as rheumatoid arthritis and Crohn's disease), and infectious diseases. During the COVID-19 pandemic, monoclonal antibody treatments were developed and deployed with unprecedented speed, demonstrating the potential of this technology for rapid response to emerging health threats.

D. Industrial biotechnology, sometimes called "white biotechnology," applies biological processes to manufacturing and industrial operations as alternatives to conventional chemical processes. Enzymes — biological catalysts derived from microorganisms — are used in a vast range of industrial applications, from producing biofuels and biodegradable plastics to processing textiles, paper, and food products. Bioplastics, produced from renewable biological sources such as corn starch, sugarcane, and cellulose rather than petroleum, offer a potential solution to the global plastic pollution crisis. The global bioplastics market is projected to grow from approximately 2.2 million tonnes in 2022 to 6.3 million tonnes by 2027. Synthetic biology — the design and construction of new biological parts, devices, and systems — is pushing the boundaries further, enabling the creation of microorganisms engineered to produce chemicals, fuels, and materials that would be difficult or impossible to manufacture through traditional chemistry.

E. Agricultural biotechnology has the potential to address critical food security challenges by developing crops that are more productive, nutritious, and resilient. Genetically modified (GM) crops, which have been commercially grown since 1996, now cover approximately 190 million hectares worldwide — roughly 12 percent of global cropland. The most widely grown GM crops are soybeans, maize, cotton, and canola, engineered primarily for herbicide tolerance and insect resistance. More recently, biofortified crops — varieties enhanced with essential vitamins and minerals — have been developed to combat nutritional deficiencies in developing countries. Golden Rice, engineered to produce beta-carotene (a precursor to vitamin A), aims to address vitamin A deficiency, which affects an estimated 250 million preschool children worldwide and is a leading cause of preventable childhood blindness.

F. Despite its enormous potential, biotechnology raises significant ethical, regulatory, and societal questions. The ability to edit the human genome has sparked intense debate about the moral boundaries of genetic modification, particularly regarding germline editing — changes to DNA that can be inherited by future generations. In 2018, the announcement by a Chinese scientist that he had created the world's first gene-edited babies provoked widespread condemnation from the scientific community and led to calls for an international moratorium on human germline editing. Concerns about the environmental impact of genetically modified organisms, the equitable distribution of biotechnological benefits, intellectual property rights over biological innovations, and the potential for misuse of powerful biological technologies such as synthetic biology all demand careful governance and public dialogue.`,
      questions: [
        { number: 27, type: "matching_information", text: "The creation of gene-edited human embryos and the ethical controversy it caused", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "F", explanation: "Paragraph F mentions the Chinese scientist who 'created the world's first gene-edited babies' and the resulting condemnation." },
        { number: 28, type: "matching_information", text: "The use of biological processes as alternatives to chemical manufacturing", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "D", explanation: "Paragraph D describes industrial biotechnology applying 'biological processes to manufacturing.'" },
        { number: 29, type: "matching_information", text: "A technology adapted from bacteria's natural defence against viruses", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "B", explanation: "Paragraph B explains CRISPR is 'based on a natural defence mechanism used by bacteria to protect themselves against viral infections.'" },
        { number: 30, type: "matching_information", text: "Crops engineered to contain additional vitamins and minerals", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "E", explanation: "Paragraph E discusses biofortified crops and Golden Rice engineered to produce beta-carotene." },
        { number: 31, type: "matching_information", text: "The dramatic reduction in the cost of mapping human DNA", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "A", explanation: "Paragraph A states the cost 'has plummeted from approximately $2.7 billion to under $200 today.'" },
        { number: 32, type: "multiple_choice", text: "The Human Genome Project identified approximately", options: ["A 3 billion protein-coding genes.", "B 20,500 protein-coding genes.", "C 200,000 protein-coding genes.", "D 2.7 million protein-coding genes."], correctAnswer: "B", explanation: "The passage states 'identified approximately 20,500 protein-coding genes.'" },
        { number: 33, type: "multiple_choice", text: "CRISPR-Cas9 has been used in clinical trials to treat", options: ["A diabetes and heart disease.", "B Alzheimer's disease and cancer.", "C sickle cell disease and beta-thalassaemia.", "D rheumatoid arthritis and Crohn's disease."], correctAnswer: "C", explanation: "The passage says CRISPR is used 'to treat genetic disorders such as sickle cell disease and beta-thalassaemia.'" },
        { number: 34, type: "multiple_choice", text: "The global bioplastics market is projected to reach approximately", options: ["A 2.2 million tonnes by 2025.", "B 4.5 million tonnes by 2027.", "C 6.3 million tonnes by 2027.", "D 10 million tonnes by 2030."], correctAnswer: "C", explanation: "The passage states growth 'to 6.3 million tonnes by 2027.'" },
        { number: 35, type: "multiple_choice", text: "Golden Rice was developed primarily to address", options: ["A protein deficiency in adults.", "B iron deficiency in pregnant women.", "C vitamin A deficiency in children.", "D calcium deficiency in the elderly."], correctAnswer: "C", explanation: "The passage says Golden Rice 'aims to address vitamin A deficiency, which affects an estimated 250 million preschool children.'" },
        { number: 36, type: "short_answer", text: "In what year was the Human Genome Project completed?", correctAnswer: "2003", explanation: "The passage states 'completed in 2003.'" },
        { number: 37, type: "short_answer", text: "How many monoclonal antibody drugs are currently approved for clinical use?", correctAnswer: "over 100", explanation: "The passage states 'over 100 monoclonal antibody drugs now approved.'" },
        { number: 38, type: "short_answer", text: "How many hectares of GM crops are grown worldwide?", correctAnswer: "190 million", explanation: "The passage says 'approximately 190 million hectares worldwide.'" },
        { number: 39, type: "short_answer", text: "What does the term 'pharmacogenomics' study?", correctAnswer: "how genes affect a person's response to drugs", explanation: "The passage defines it as 'the study of how genes affect a person's response to drugs.'" },
        { number: 40, type: "short_answer", text: "In what year was the first therapeutic monoclonal antibody approved?", correctAnswer: "1986", explanation: "The passage states 'the approval of the first therapeutic monoclonal antibody in 1986.'" },
      ],
    },
  ],
};
