import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_39: ReadingTest = {
  id: 39,
  passages: [
    {
      title: "History of Mathematics",
      text: `Mathematics is often described as the language of the universe, a system of abstract reasoning that underpins science, technology, economics, and daily life. Its origins stretch back at least five thousand years, to the river civilisations of Mesopotamia and Egypt, where practical needs — measuring land, tracking astronomical cycles, managing trade — gave rise to the first systematic approaches to counting, measuring, and calculating.

The ancient Sumerians of Mesopotamia, writing on clay tablets around 3000 BCE, developed a base-60 (sexagesimal) number system that survives today in our division of the hour into sixty minutes and the circle into 360 degrees. They compiled multiplication tables, solved quadratic equations, and devised algorithms for calculating areas and volumes. The Babylonians, who succeeded the Sumerians, refined these techniques and produced remarkably accurate astronomical tables that predicted lunar eclipses centuries in advance.

In Egypt, mathematics served primarily architectural and administrative purposes. The Rhind Papyrus, dating to around 1650 BCE, contains eighty-four problems and solutions covering arithmetic, algebra, and geometry, including methods for calculating the volume of a truncated pyramid — a skill essential for the construction of the great monuments of the Nile valley. Egyptian mathematics was pragmatic rather than abstract: problems were expressed not in general terms but as specific worked examples.

Ancient Greece marked a turning point. Greek mathematicians, beginning with Thales of Miletus in the sixth century BCE, insisted on deductive proof — the logical derivation of conclusions from axioms and previously proven statements. This emphasis on rigour transformed mathematics from a collection of useful techniques into a formal intellectual discipline. Euclid's Elements, compiled around 300 BCE, organised the geometry of the ancient world into a systematic framework of definitions, postulates, and theorems that remained the standard textbook for more than two millennia. Archimedes calculated the value of pi to unprecedented accuracy and developed methods for determining areas and volumes that anticipated integral calculus by nearly two thousand years.

Following the decline of Greece and Rome, the centre of mathematical innovation shifted eastward. Indian mathematicians made contributions of world-changing significance: the concept of zero as both a placeholder and a number in its own right, the decimal place-value system, and early work on infinite series. Brahmagupta, writing in the seventh century CE, established rules for arithmetic operations involving zero and negative numbers. These ideas were transmitted to the Islamic world, where scholars such as al-Khwarizmi — whose name gives us the word algorithm — developed algebra as a distinct branch of mathematics. Al-Khwarizmi's treatise Al-Kitab al-Mukhtasar fi Hisab al-Jabr wal-Muqabala, written around 820 CE, provided systematic methods for solving linear and quadratic equations and became the foundational text of the discipline.

The European Renaissance saw the rediscovery of Greek and Islamic mathematical texts and a surge of new discoveries. In the seventeenth century, René Descartes united algebra and geometry by introducing coordinate systems, enabling geometric shapes to be described by equations. Isaac Newton and Gottfried Wilhelm Leibniz, working independently, invented calculus in the late seventeenth century, providing the mathematical tools needed to describe motion, change, and the physical laws of the universe.

The nineteenth and twentieth centuries witnessed an explosion of new branches: non-Euclidean geometry, set theory, abstract algebra, topology, and mathematical logic. These developments not only deepened understanding of the foundations of mathematics but also proved indispensable to modern physics, computer science, and engineering. Alan Turing's theoretical work on computability in the 1930s laid the conceptual groundwork for the digital computer, and today mathematics is embedded in technologies from encryption to machine learning.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "What number system did the ancient Sumerians develop?", options: ["A Base-10", "B Base-12", "C Base-60", "D Base-100"], correctAnswer: "C", explanation: "The passage says the Sumerians 'developed a base-60 (sexagesimal) number system.'" },
        { number: 2, type: "multiple_choice", text: "What does the Rhind Papyrus contain?", options: ["A Religious hymns", "B 84 mathematical problems and solutions", "C Architectural blueprints", "D Astronomical observations"], correctAnswer: "B", explanation: "The passage says it 'contains eighty-four problems and solutions.'" },
        { number: 3, type: "multiple_choice", text: "Who is credited with insisting on deductive proof in mathematics?", options: ["A The Babylonians", "B Egyptian architects", "C Greek mathematicians beginning with Thales", "D Indian scholars"], correctAnswer: "C", explanation: "The passage says 'Greek mathematicians, beginning with Thales of Miletus... insisted on deductive proof.'" },
        { number: 4, type: "multiple_choice", text: "What does the word 'algorithm' derive from?", options: ["A Euclid's Elements", "B The name al-Khwarizmi", "C Brahmagupta's treatise", "D The Rhind Papyrus"], correctAnswer: "B", explanation: "The passage says 'al-Khwarizmi — whose name gives us the word algorithm.'" },
        { number: 5, type: "sentence_completion", text: "The Babylonians produced astronomical tables that predicted __(5)__ eclipses.", correctAnswer: "lunar", explanation: "The passage says they 'predicted lunar eclipses centuries in advance.'" },
        { number: 6, type: "sentence_completion", text: "Euclid's Elements remained the standard textbook for more than __(6)__ millennia.", correctAnswer: "two", explanation: "The passage says 'more than two millennia.'" },
        { number: 7, type: "sentence_completion", text: "Archimedes developed methods that anticipated integral __(7)__ by nearly two thousand years.", correctAnswer: "calculus", explanation: "The passage says 'anticipated integral calculus.'" },
        { number: 8, type: "sentence_completion", text: "Indian mathematicians introduced the concept of __(8)__ as both a placeholder and a number.", correctAnswer: "zero", explanation: "The passage says 'the concept of zero as both a placeholder and a number.'" },
        { number: 9, type: "sentence_completion", text: "René Descartes united algebra and geometry by introducing __(9)__ systems.", correctAnswer: "coordinate", explanation: "The passage says 'introducing coordinate systems.'" },
        { number: 10, type: "sentence_completion", text: "Newton and Leibniz invented __(10)__ in the late seventeenth century.", correctAnswer: "calculus", explanation: "The passage says they 'invented calculus in the late seventeenth century.'" },
        { number: 11, type: "sentence_completion", text: "Alan Turing's work on computability laid the groundwork for the digital __(11)__.", correctAnswer: "computer", explanation: "The passage says it 'laid the conceptual groundwork for the digital computer.'" },
        { number: 12, type: "sentence_completion", text: "Al-Khwarizmi's treatise provided methods for solving linear and __(12)__ equations.", correctAnswer: "quadratic", explanation: "The passage says 'solving linear and quadratic equations.'" },
        { number: 13, type: "sentence_completion", text: "Egyptian mathematics was __(13)__ rather than abstract.", correctAnswer: "pragmatic", explanation: "The passage says 'Egyptian mathematics was pragmatic rather than abstract.'" },
      ],
    },
    {
      title: "Effects of Deforestation",
      text: `A. Forests cover approximately thirty-one per cent of the Earth's land surface and are among the most biologically diverse ecosystems on the planet. They harbour an estimated eighty per cent of terrestrial animal and plant species, regulate water cycles, stabilise soils, and absorb vast quantities of carbon dioxide from the atmosphere. Yet deforestation — the permanent removal of forest cover — continues at an alarming rate. The Food and Agriculture Organization of the United Nations estimates that approximately ten million hectares of forest are lost each year, an area roughly the size of South Korea.

B. The causes of deforestation vary by region but share common economic drivers. In tropical countries, the leading cause is agricultural expansion: forests are cleared to create cropland or pasture for livestock. Soybean cultivation in Brazil, palm-oil plantations in Indonesia and Malaysia, and cattle ranching across Latin America are responsible for the majority of tropical forest loss. Logging, both legal and illegal, is another significant factor, as is the extraction of minerals, oil, and gas. In some regions, infrastructure development — roads, dams, and urban sprawl — fragments forests and opens previously inaccessible areas to further exploitation.

C. The environmental consequences of deforestation are profound and far-reaching. Trees are natural carbon sinks: a mature forest absorbs more carbon dioxide than it releases, helping to regulate the Earth's climate. When forests are cleared and burned, the stored carbon is released into the atmosphere as CO2, contributing to global warming. Deforestation is estimated to account for approximately ten to fifteen per cent of annual global greenhouse-gas emissions — a share comparable to that of the entire global transport sector.

D. Deforestation also disrupts water cycles. Trees draw water from the soil through their roots and release it into the atmosphere through transpiration, a process that generates moisture, forms clouds, and sustains rainfall patterns. When large areas of forest are removed, regional rainfall can decline significantly, leading to drier conditions and, in extreme cases, desertification. The Amazon rainforest, often called the lungs of the Earth, is thought to generate as much as half of its own rainfall through transpiration; scientists warn that continued deforestation could push the Amazon past a tipping point beyond which it would transition irreversibly from forest to savanna.

E. Soil erosion is another major consequence. Tree roots bind soil particles together and slow the movement of water across the landscape. Without this anchoring effect, heavy rains wash topsoil into rivers and streams, degrading water quality, silting reservoirs, and reducing the fertility of agricultural land. In mountainous regions, deforestation increases the risk of landslides, which can be catastrophic for communities living downstream.

F. The loss of biodiversity associated with deforestation is incalculable. Tropical forests, which are being cleared at the fastest rate, are home to an extraordinary concentration of species, many of which have not yet been scientifically described. When a forest is destroyed, the species that depend on it — from insects and fungi to birds and primates — may face extinction. The International Union for Conservation of Nature lists habitat loss, driven primarily by deforestation, as the greatest threat to endangered species worldwide.

G. Efforts to combat deforestation take many forms. Protected areas and national parks restrict logging and land conversion within their boundaries, though enforcement can be weak in countries with limited resources. Reforestation and afforestation programmes aim to restore degraded land by planting trees, although newly planted forests lack the biodiversity and carbon-storage capacity of old-growth forests. International initiatives such as REDD+ (Reducing Emissions from Deforestation and Forest Degradation) provide financial incentives for developing countries to preserve their forests. Consumer pressure is also playing a role: certification schemes such as the Forest Stewardship Council (FSC) enable buyers to choose products sourced from sustainably managed forests.

H. Ultimately, halting deforestation will require addressing its root economic causes. As long as clearing forest is more profitable than preserving it, deforestation will continue. Policies that assign economic value to the services forests provide — carbon storage, water regulation, biodiversity conservation — and that support sustainable livelihoods for forest-dependent communities are essential if the world's remaining forests are to be saved.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Section A", options: ["I. Impact on global carbon emissions", "II. Forests: extent and annual losses", "III. Economic roots of forest clearance", "IV. Disruption to rainfall patterns", "V. Strategies to reduce deforestation", "VI. Loss of plant and animal species", "VII. The problem of soil degradation", "VIII. The need for economic reform"], correctAnswer: "II", explanation: "Section A presents the extent of forests and the rate of deforestation." },
        { number: 15, type: "matching_headings", text: "Section B", options: ["I. Impact on global carbon emissions", "II. Forests: extent and annual losses", "III. Economic roots of forest clearance", "IV. Disruption to rainfall patterns", "V. Strategies to reduce deforestation", "VI. Loss of plant and animal species", "VII. The problem of soil degradation", "VIII. The need for economic reform"], correctAnswer: "III", explanation: "Section B discusses the economic causes of deforestation." },
        { number: 16, type: "matching_headings", text: "Section C", options: ["I. Impact on global carbon emissions", "II. Forests: extent and annual losses", "III. Economic roots of forest clearance", "IV. Disruption to rainfall patterns", "V. Strategies to reduce deforestation", "VI. Loss of plant and animal species", "VII. The problem of soil degradation", "VIII. The need for economic reform"], correctAnswer: "I", explanation: "Section C discusses carbon release and greenhouse-gas emissions." },
        { number: 17, type: "matching_headings", text: "Section D", options: ["I. Impact on global carbon emissions", "II. Forests: extent and annual losses", "III. Economic roots of forest clearance", "IV. Disruption to rainfall patterns", "V. Strategies to reduce deforestation", "VI. Loss of plant and animal species", "VII. The problem of soil degradation", "VIII. The need for economic reform"], correctAnswer: "IV", explanation: "Section D discusses water cycles and rainfall disruption." },
        { number: 18, type: "matching_headings", text: "Section E", options: ["I. Impact on global carbon emissions", "II. Forests: extent and annual losses", "III. Economic roots of forest clearance", "IV. Disruption to rainfall patterns", "V. Strategies to reduce deforestation", "VI. Loss of plant and animal species", "VII. The problem of soil degradation", "VIII. The need for economic reform"], correctAnswer: "VII", explanation: "Section E discusses soil erosion." },
        { number: 19, type: "matching_headings", text: "Section F", options: ["I. Impact on global carbon emissions", "II. Forests: extent and annual losses", "III. Economic roots of forest clearance", "IV. Disruption to rainfall patterns", "V. Strategies to reduce deforestation", "VI. Loss of plant and animal species", "VII. The problem of soil degradation", "VIII. The need for economic reform"], correctAnswer: "VI", explanation: "Section F discusses biodiversity loss." },
        { number: 20, type: "table_completion", text: "Approximately __(20)__ million hectares of forest are lost each year.", correctAnswer: "ten", explanation: "The passage says 'approximately ten million hectares.'" },
        { number: 21, type: "table_completion", text: "Deforestation accounts for approximately __(21)__ to fifteen per cent of global emissions.", correctAnswer: "ten", explanation: "The passage says 'approximately ten to fifteen per cent.'" },
        { number: 22, type: "table_completion", text: "The Amazon generates as much as __(22)__ of its own rainfall through transpiration.", correctAnswer: "half", explanation: "The passage says 'as much as half of its own rainfall.'" },
        { number: 23, type: "table_completion", text: "The __(23)__ lists habitat loss as the greatest threat to endangered species.", correctAnswer: "IUCN", explanation: "The passage refers to 'The International Union for Conservation of Nature' (IUCN)." },
        { number: 24, type: "table_completion", text: "REDD+ provides __(24)__ incentives for developing countries to preserve forests.", correctAnswer: "financial", explanation: "The passage says 'provide financial incentives.'" },
        { number: 25, type: "table_completion", text: "The FSC enables buyers to choose products from __(25)__ managed forests.", correctAnswer: "sustainably", explanation: "The passage says 'sustainably managed forests.'" },
        { number: 26, type: "table_completion", text: "Forests harbour approximately __(26)__ per cent of terrestrial species.", correctAnswer: "eighty", explanation: "The passage says 'an estimated eighty per cent of terrestrial animal and plant species.'" },
      ],
    },
    {
      title: "Renewable Energy Technologies",
      text: `The global energy landscape is undergoing a transformation that many analysts describe as the most significant since the Industrial Revolution. Driven by falling costs, supportive government policies, and growing concern about climate change, renewable energy sources — solar, wind, hydroelectric, geothermal, and biomass — are displacing fossil fuels at an accelerating pace. In 2023, renewables accounted for more than thirty per cent of global electricity generation for the first time, and the International Energy Agency projects that this share will exceed fifty per cent by 2030.

Solar photovoltaic (PV) technology has experienced the most dramatic cost reduction. The price of solar panels has fallen by more than ninety per cent since 2010, making solar electricity cheaper than coal or natural gas in most parts of the world. China dominates global solar manufacturing, producing roughly eighty per cent of the world's PV panels, and has installed more solar capacity than any other country. India, the United States, and several European nations are also expanding rapidly. Utility-scale solar farms in sunny regions can now generate electricity for as little as two US cents per kilowatt-hour, a figure that was unimaginable a decade ago.

Wind power has followed a similar trajectory. Modern wind turbines are engineering marvels: the largest offshore models stand more than 260 metres tall and can generate fifteen megawatts of power, enough to supply approximately 13,000 homes. Offshore wind farms, located in shallow coastal waters or on floating platforms in deeper seas, benefit from stronger, more consistent winds than their onshore counterparts and avoid many of the land-use conflicts that can delay onshore projects. The United Kingdom, Denmark, and the Netherlands are leaders in offshore wind, and the sector is expanding rapidly in the United States, Japan, and South Korea.

Energy storage is widely regarded as the critical enabler of a renewable-dominated grid. Because solar and wind generation fluctuate with weather and time of day, grid operators need reliable storage systems to balance supply and demand. Lithium-ion batteries, the same technology used in electric vehicles, are currently the dominant storage solution. Battery costs have fallen by approximately ninety per cent since 2010, and large-scale battery installations — such as the Hornsdale Power Reserve in South Australia, which can store 194 megawatt-hours of energy — are proving their value by stabilising grids and reducing reliance on fossil-fuel peaker plants.

Alternative storage technologies are also emerging. Pumped hydroelectric storage, which accounts for more than ninety per cent of global energy storage capacity, uses surplus electricity to pump water uphill into a reservoir; when demand rises, the water flows back downhill through turbines to generate power. Green hydrogen, produced by using renewable electricity to split water molecules through electrolysis, can store energy for weeks or months and be used in industrial processes, heavy transport, and power generation. Compressed-air energy storage and gravity-based systems are at earlier stages of development but could diversify the storage portfolio in coming decades.

The integration of renewables into existing energy systems presents challenges beyond storage. Electricity grids designed for large, centralised fossil-fuel power stations must be adapted to accommodate millions of distributed solar panels and wind turbines. This requires investment in transmission infrastructure, smart-grid technologies, and demand-response systems that encourage consumers to shift electricity use to periods of high renewable output. Regulatory frameworks, too, must evolve: many electricity markets were designed around dispatchable fossil-fuel generation and are poorly suited to variable renewable sources.

Despite these challenges, the momentum behind renewable energy appears irreversible. Global investment in clean energy reached $1.8 trillion in 2023, exceeding investment in fossil fuels for the first time. Major economies — the European Union, the United States, China, and India — have all set ambitious renewable-energy targets, and the private sector is increasingly committing to one-hundred-per-cent renewable electricity. The transition will not be without disruption: fossil-fuel workers and communities will need support, and critical minerals such as lithium, cobalt, and rare-earth elements must be sourced responsibly. But the direction of travel is clear, and the pace of change is accelerating.`,
      questions: [
        { number: 27, type: "true_false_not_given", text: "Renewables accounted for more than thirty per cent of global electricity generation for the first time in 2023.", correctAnswer: "TRUE", explanation: "The passage says 'In 2023, renewables accounted for more than thirty per cent... for the first time.'" },
        { number: 28, type: "true_false_not_given", text: "Solar panel prices have fallen by more than eighty per cent since 2010.", correctAnswer: "FALSE", explanation: "The passage says prices have fallen by 'more than ninety per cent since 2010.'" },
        { number: 29, type: "true_false_not_given", text: "India produces more solar panels than China.", correctAnswer: "FALSE", explanation: "The passage says China produces 'roughly eighty per cent of the world's PV panels.'" },
        { number: 30, type: "true_false_not_given", text: "The largest offshore wind turbines can generate fifteen megawatts of power.", correctAnswer: "TRUE", explanation: "The passage says they 'can generate fifteen megawatts of power.'" },
        { number: 31, type: "true_false_not_given", text: "Battery costs have fallen by approximately seventy per cent since 2010.", correctAnswer: "FALSE", explanation: "The passage says 'approximately ninety per cent since 2010.'" },
        { number: 32, type: "true_false_not_given", text: "France is a leader in offshore wind energy.", correctAnswer: "NOT GIVEN", explanation: "The passage mentions the UK, Denmark, and the Netherlands but not France." },
        { number: 33, type: "true_false_not_given", text: "Global investment in clean energy reached $1.8 trillion in 2023.", correctAnswer: "TRUE", explanation: "The passage states 'Global investment in clean energy reached $1.8 trillion in 2023.'" },
        { number: 34, type: "short_answer", text: "What is the cheapest cost per kilowatt-hour that utility-scale solar farms can achieve?", correctAnswer: "two US cents", explanation: "The passage says 'as little as two US cents per kilowatt-hour.'" },
        { number: 35, type: "short_answer", text: "What is the name of the large-scale battery installation in South Australia?", correctAnswer: "Hornsdale Power Reserve", explanation: "The passage mentions 'the Hornsdale Power Reserve in South Australia.'" },
        { number: 36, type: "short_answer", text: "What process is used to produce green hydrogen?", correctAnswer: "electrolysis", explanation: "The passage says green hydrogen is produced 'through electrolysis.'" },
        { number: 37, type: "short_answer", text: "What type of storage accounts for more than ninety per cent of global energy storage capacity?", correctAnswer: "pumped hydroelectric", explanation: "The passage says 'Pumped hydroelectric storage... accounts for more than ninety per cent.'" },
        { number: 38, type: "short_answer", text: "How many homes can the largest offshore wind turbine supply?", correctAnswer: "13,000", explanation: "The passage says 'enough to supply approximately 13,000 homes.'" },
        { number: 39, type: "short_answer", text: "What systems encourage consumers to shift electricity use to periods of high renewable output?", correctAnswer: "demand-response", explanation: "The passage mentions 'demand-response systems.'" },
        { number: 40, type: "short_answer", text: "How much energy can the Hornsdale Power Reserve store?", correctAnswer: "194 megawatt-hours", explanation: "The passage says 'store 194 megawatt-hours of energy.'" },
      ],
    },
  ],
};
