import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_27: ReadingTest = {
  id: 27,
  passages: [
    {
      title: "The Silk Road",
      text: `The Silk Road was not a single highway but a vast network of interconnected trade routes that linked the civilisations of East Asia with those of Central Asia, the Middle East, and Europe for nearly two millennia. Stretching more than six thousand kilometres across some of the most forbidding terrain on Earth — scorching deserts, towering mountain passes, and windswept steppes — these routes facilitated not only the exchange of goods but also the transmission of ideas, religions, technologies, and diseases that profoundly shaped world history.

The origins of trans-Eurasian trade predate the term "Silk Road," which was coined by the German geographer Ferdinand von Richthofen in 1877. Archaeological evidence suggests that jade from the Tarim Basin reached China as early as 5000 BCE, while lapis lazuli from Afghanistan adorned Mesopotamian artefacts by the third millennium BCE. However, it was the Chinese Han Dynasty's diplomatic missions to Central Asia in the second century BCE, led by the envoy Zhang Qian, that opened systematic overland trade. Zhang Qian's journeys, initially intended to forge military alliances against nomadic Xiongnu raiders, instead revealed lucrative commercial opportunities that the Han court eagerly exploited.

Chinese silk was the most celebrated commodity travelling westward along these routes, prized in Rome for its lustrous texture and commanding prices equivalent to its weight in gold. Yet silk was merely one of thousands of traded goods. Spices, gemstones, glassware, metalwork, ivory, and woollen textiles moved in both directions. From China came paper, gunpowder, and porcelain; from the West came horses, grapevines, and new crops such as sesame and coriander. The economic significance of this trade was immense, enriching the oasis cities — Samarkand, Bukhara, Kashgar, and Dunhuang — that served as vital intermediary hubs.

Beyond material goods, the Silk Road was arguably even more important as a conduit for cultural and intellectual exchange. Buddhism spread from India to China along these routes beginning in the first century CE, eventually reaching Korea and Japan. Islam expanded eastward through Central Asian trade networks from the seventh century onward. Christianity, Zoroastrianism, and Manichaeism also found adherents far from their lands of origin. Artistic styles blended at crossroads cities, producing hybrid traditions such as Gandharan sculpture, which fused Hellenistic and Buddhist aesthetics.

Scientific and technological knowledge flowed along the same pathways. The Chinese inventions of papermaking, printing, the compass, and gunpowder gradually diffused westward, transforming European civilisation. Conversely, mathematical concepts including the Indian numeral system and the concept of zero reached the Islamic world and eventually Europe via Silk Road intermediaries. Medical knowledge, astronomical observations, and agricultural techniques were similarly shared, contributing to intellectual advancement across multiple civilisations.

The Silk Road was not without its dangers. Bandits preyed upon caravans, and travellers faced extreme weather, dehydration, and disease. The caravanserais — fortified roadside inns spaced at intervals of roughly a day's journey — provided essential shelter, food, and security. Political instability along portions of the route periodically disrupted trade, while the devastating spread of the Black Death in the fourteenth century, which travelled along Silk Road networks from Central Asia to Europe, demonstrated the dark side of interconnectedness.

Maritime trade routes gradually superseded overland Silk Road commerce from the fifteenth century onward, as European maritime powers developed faster and cheaper shipping capabilities. The Portuguese discovery of a sea route to India in 1498 and the subsequent expansion of oceanic trade networks diminished the economic importance of the traditional land routes. Nevertheless, the legacy of the Silk Road endures in the cultural, religious, and genetic diversity of the regions it connected, and in the twenty-first century the concept has been revived through China's Belt and Road Initiative, a massive infrastructure programme aimed at recreating historic trade links across Eurasia and beyond.`,
      questions: [
        { number: 1, type: "true_false_not_given", text: "The term 'Silk Road' was invented by a Chinese historian.", correctAnswer: "FALSE", explanation: "The passage states it was coined by 'the German geographer Ferdinand von Richthofen.'" },
        { number: 2, type: "true_false_not_given", text: "Zhang Qian's original purpose was to establish trade routes.", correctAnswer: "FALSE", explanation: "His missions were 'initially intended to forge military alliances against nomadic Xiongnu raiders.'" },
        { number: 3, type: "true_false_not_given", text: "Silk was the only commodity traded along the Silk Road.", correctAnswer: "FALSE", explanation: "The passage says 'silk was merely one of thousands of traded goods.'" },
        { number: 4, type: "true_false_not_given", text: "Buddhism reached Japan via Silk Road trade networks.", correctAnswer: "TRUE", explanation: "The passage states Buddhism spread from India to China and 'eventually reaching Korea and Japan.'" },
        { number: 5, type: "true_false_not_given", text: "Caravanserais were located approximately two days' journey apart.", correctAnswer: "FALSE", explanation: "The passage says they were 'spaced at intervals of roughly a day's journey.'" },
        { number: 6, type: "true_false_not_given", text: "The Black Death originated in Europe before spreading to Asia.", correctAnswer: "FALSE", explanation: "The passage says it 'travelled along Silk Road networks from Central Asia to Europe.'" },
        { number: 7, type: "true_false_not_given", text: "The Belt and Road Initiative has been universally welcomed by all nations.", correctAnswer: "NOT GIVEN", explanation: "The passage mentions the initiative but does not discuss international reactions to it." },
        { number: 8, type: "sentence_completion", text: "In ancient Rome, Chinese silk commanded prices equivalent to its weight in __(8)__.", correctAnswer: "gold", explanation: "The passage states silk was 'commanding prices equivalent to its weight in gold.'" },
        { number: 9, type: "sentence_completion", text: "Gandharan sculpture is an example of a __(9)__ tradition combining Greek and Buddhist styles.", correctAnswer: "hybrid", explanation: "The passage describes 'hybrid traditions such as Gandharan sculpture.'" },
        { number: 10, type: "sentence_completion", text: "The Indian numeral system and the concept of __(10)__ reached Europe via Silk Road intermediaries.", correctAnswer: "zero", explanation: "The passage mentions 'the Indian numeral system and the concept of zero.'" },
        { number: 11, type: "sentence_completion", text: "The Portuguese discovered a sea route to __(11)__ in 1498.", correctAnswer: "India", explanation: "The passage states 'The Portuguese discovery of a sea route to India in 1498.'" },
        { number: 12, type: "sentence_completion", text: "Travellers along the Silk Road faced dangers including bandits, extreme weather, dehydration, and __(12)__.", correctAnswer: "disease", explanation: "The passage lists 'extreme weather, dehydration, and disease.'" },
        { number: 13, type: "sentence_completion", text: "Jade from the Tarim Basin reached China as early as __(13)__ BCE.", correctAnswer: "5000", explanation: "The passage states 'jade from the Tarim Basin reached China as early as 5000 BCE.'" },
      ],
    },
    {
      title: "Coral Reefs",
      text: `A. Coral reefs are among the most biologically diverse ecosystems on the planet, rivalling tropical rainforests in the variety of species they support. Though they cover less than one per cent of the ocean floor, coral reefs are home to approximately twenty-five per cent of all marine species, including more than four thousand species of fish, eight hundred species of hard coral, and countless invertebrates, algae, and microorganisms. Often called the "rainforests of the sea," these structures provide critical ecosystem services that extend far beyond their immediate boundaries.

B. The foundation of every coral reef is the coral polyp, a tiny soft-bodied animal related to sea anemones and jellyfish. Most reef-building corals contain symbiotic algae called zooxanthellae within their tissues. These microscopic photosynthetic organisms provide up to ninety per cent of the coral's energy requirements through photosynthesis, while the coral supplies the algae with shelter and the nutrients they need. This mutualistic relationship is the engine that drives reef growth, enabling corals to secrete calcium carbonate skeletons that accumulate over centuries and millennia into massive reef structures.

C. Coral reefs deliver enormous economic value to human communities. The World Resources Institute estimates that reefs provide goods and services worth approximately $375 billion annually worldwide. Fisheries dependent on coral reefs supply protein to hundreds of millions of people, particularly in developing tropical nations. Reef tourism generates billions in revenue; countries such as Australia, the Maldives, and Belize depend heavily on reef-related tourism for their national economies. Additionally, coral reef structures serve as natural breakwaters, absorbing up to ninety-seven per cent of wave energy and protecting coastlines from storm surges, erosion, and flooding.

D. Despite their ecological and economic importance, coral reefs face unprecedented threats. Rising ocean temperatures driven by climate change trigger coral bleaching — a stress response in which corals expel their symbiotic zooxanthellae, turning white and becoming vulnerable to starvation and disease. The global bleaching events of 2016 and 2017 affected over seventy per cent of the world's reef systems, with the Great Barrier Reef losing approximately half of its shallow-water corals in just two years. If global temperatures rise more than 1.5 degrees Celsius above pre-industrial levels, scientists project that seventy to ninety per cent of existing coral reefs could disappear.

E. Ocean acidification compounds the threat. As seawater absorbs increasing amounts of atmospheric carbon dioxide, its pH decreases, reducing the concentration of carbonate ions that corals need to build their calcium carbonate skeletons. Laboratory studies demonstrate that acidification slows coral growth rates by up to fifty per cent and weakens existing reef structures, making them more susceptible to storm damage and bioerosion. Pollution from agricultural runoff, including fertilisers and pesticides, further degrades water quality, promoting harmful algal blooms that smother corals and block sunlight.

F. Overfishing disrupts the delicate ecological balance of reef systems. The removal of herbivorous fish species such as parrotfish and surgeonfish allows algae to proliferate unchecked, outcompeting corals for space and light. Destructive fishing practices — including the use of dynamite and cyanide — cause direct physical damage to reef structures that can take decades to recover. In Southeast Asia, where many reefs are under intense fishing pressure, an estimated eighty-eight per cent of coral reefs are classified as threatened.

G. Conservation efforts are intensifying worldwide. Marine protected areas (MPAs), when well-managed and enforced, have demonstrated significant success in allowing degraded reefs to recover. Coral restoration projects, involving the cultivation of heat-resistant coral fragments in underwater nurseries and their transplantation onto damaged reefs, are scaling up across the Caribbean and the Indo-Pacific. Scientists are also investigating assisted evolution — selectively breeding corals that demonstrate natural heat tolerance — as a strategy for developing reef populations capable of withstanding warmer oceans.

H. Ultimately, the survival of coral reefs depends on addressing the root causes of climate change. Without substantial reductions in greenhouse gas emissions, even the most ambitious local conservation measures will prove insufficient. International agreements such as the Paris Agreement represent essential frameworks for collective action, but their targets must be met with genuine political commitment and accelerated implementation if the world's coral reefs are to persist for future generations.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Section A", options: ["I. The biological basis of reef construction", "II. Remarkable biodiversity in a small area", "III. Financial contributions of reef ecosystems", "IV. The bleaching crisis and temperature rise", "V. Chemical changes in ocean water", "VI. Fishing pressures on reef ecology", "VII. Active efforts to protect and restore reefs", "VIII. The necessity of global climate action", "IX. The future of coral reef tourism"], correctAnswer: "II", explanation: "Section A discusses the extraordinary biodiversity of coral reefs." },
        { number: 15, type: "matching_headings", text: "Section B", options: ["I. The biological basis of reef construction", "II. Remarkable biodiversity in a small area", "III. Financial contributions of reef ecosystems", "IV. The bleaching crisis and temperature rise", "V. Chemical changes in ocean water", "VI. Fishing pressures on reef ecology", "VII. Active efforts to protect and restore reefs", "VIII. The necessity of global climate action", "IX. The future of coral reef tourism"], correctAnswer: "I", explanation: "Section B explains coral polyps, zooxanthellae, and reef construction." },
        { number: 16, type: "matching_headings", text: "Section C", options: ["I. The biological basis of reef construction", "II. Remarkable biodiversity in a small area", "III. Financial contributions of reef ecosystems", "IV. The bleaching crisis and temperature rise", "V. Chemical changes in ocean water", "VI. Fishing pressures on reef ecology", "VII. Active efforts to protect and restore reefs", "VIII. The necessity of global climate action", "IX. The future of coral reef tourism"], correctAnswer: "III", explanation: "Section C discusses the economic value of coral reefs." },
        { number: 17, type: "matching_headings", text: "Section D", options: ["I. The biological basis of reef construction", "II. Remarkable biodiversity in a small area", "III. Financial contributions of reef ecosystems", "IV. The bleaching crisis and temperature rise", "V. Chemical changes in ocean water", "VI. Fishing pressures on reef ecology", "VII. Active efforts to protect and restore reefs", "VIII. The necessity of global climate action", "IX. The future of coral reef tourism"], correctAnswer: "IV", explanation: "Section D discusses coral bleaching from rising temperatures." },
        { number: 18, type: "matching_headings", text: "Section E", options: ["I. The biological basis of reef construction", "II. Remarkable biodiversity in a small area", "III. Financial contributions of reef ecosystems", "IV. The bleaching crisis and temperature rise", "V. Chemical changes in ocean water", "VI. Fishing pressures on reef ecology", "VII. Active efforts to protect and restore reefs", "VIII. The necessity of global climate action", "IX. The future of coral reef tourism"], correctAnswer: "V", explanation: "Section E discusses ocean acidification and reduced pH." },
        { number: 19, type: "matching_headings", text: "Section F", options: ["I. The biological basis of reef construction", "II. Remarkable biodiversity in a small area", "III. Financial contributions of reef ecosystems", "IV. The bleaching crisis and temperature rise", "V. Chemical changes in ocean water", "VI. Fishing pressures on reef ecology", "VII. Active efforts to protect and restore reefs", "VIII. The necessity of global climate action", "IX. The future of coral reef tourism"], correctAnswer: "VI", explanation: "Section F discusses the effects of overfishing on reefs." },
        { number: 20, type: "table_completion", text: "Zooxanthellae provide up to __(20)__ per cent of the coral's energy.", correctAnswer: "ninety", explanation: "The passage states 'up to ninety per cent of the coral's energy requirements.'" },
        { number: 21, type: "table_completion", text: "Coral reefs provide goods and services worth approximately $__(21)__ billion annually.", correctAnswer: "375", explanation: "The passage states 'approximately $375 billion annually worldwide.'" },
        { number: 22, type: "table_completion", text: "Reef structures absorb up to __(22)__ per cent of wave energy.", correctAnswer: "ninety-seven", explanation: "The passage says 'absorbing up to ninety-seven per cent of wave energy.'" },
        { number: 23, type: "table_completion", text: "In Southeast Asia, approximately __(23)__ per cent of coral reefs are classified as threatened.", correctAnswer: "eighty-eight", explanation: "The passage states 'an estimated eighty-eight per cent of coral reefs are classified as threatened.'" },
        { number: 24, type: "short_answer", text: "What is the scientific term for the symbiotic algae that live within coral tissues?", correctAnswer: "zooxanthellae", explanation: "The passage refers to 'symbiotic algae called zooxanthellae.'" },
        { number: 25, type: "short_answer", text: "What do corals expel during a bleaching event?", correctAnswer: "zooxanthellae", explanation: "The passage says corals 'expel their symbiotic zooxanthellae.'" },
        { number: 26, type: "short_answer", text: "What strategy involves selectively breeding heat-tolerant corals?", correctAnswer: "assisted evolution", explanation: "The passage mentions 'assisted evolution — selectively breeding corals that demonstrate natural heat tolerance.'" },
      ],
    },
    {
      title: "Electric Cars and the Future",
      text: `The automotive industry stands at the threshold of its most significant transformation since Henry Ford introduced the moving assembly line in 1913. Electric vehicles (EVs), once dismissed as impractical curiosities, are now central to the strategies of every major automaker, driven by tightening emissions regulations, falling battery costs, and shifting consumer preferences. The transition from internal combustion engines to electric powertrains promises to reshape not only transportation but also energy systems, urban planning, and geopolitical dynamics.

A. The history of electric vehicles is longer than most people realise. In the 1830s, Scottish inventor Robert Anderson built one of the first crude electric carriages, and by the 1900s, electric cars outsold gasoline-powered vehicles in the United States. However, the mass production of affordable gasoline cars, the discovery of cheap Texas crude oil, and the development of extensive road networks favoured internal combustion, and electric vehicles virtually disappeared from the market for most of the twentieth century.

B. The modern EV revival began in earnest with the launch of the Tesla Roadster in 2008, which demonstrated that electric cars could be desirable, high-performance vehicles rather than slow, utilitarian machines. Tesla's subsequent models — the Model S, Model X, Model 3, and Model Y — progressively expanded the market, proving that EVs could compete with conventional cars on range, comfort, and driving experience. Established automakers including Volkswagen, General Motors, Ford, and Hyundai have since committed billions to electrification, with many pledging to phase out internal combustion engines entirely within one to two decades.

C. Battery technology lies at the heart of the EV revolution. Lithium-ion batteries, which power the vast majority of current electric vehicles, have seen dramatic improvements in energy density and cost. Between 2010 and 2023, the average cost of a lithium-ion battery pack fell from approximately $1,100 per kilowatt-hour to around $140, a decline of nearly ninety per cent. This cost reduction has been the single most important factor in making EVs competitive with gasoline cars on purchase price. Next-generation technologies, including solid-state batteries and lithium-iron-phosphate (LFP) chemistries, promise further improvements in safety, longevity, and affordability.

D. Charging infrastructure remains one of the most significant barriers to mass EV adoption. While home charging serves the needs of many EV owners, the availability of fast public charging stations is critical for long-distance travel and for the approximately thirty per cent of drivers who lack access to home charging. Governments and private companies are investing heavily in expanding charging networks; the European Union, for instance, mandates the installation of fast chargers every sixty kilometres along major highways. Ultra-fast chargers capable of delivering three hundred kilometres of range in fifteen minutes are becoming increasingly common, narrowing the convenience gap between electric and gasoline refuelling.

E. The environmental benefits of electric vehicles depend significantly on the electricity sources used to charge them. In regions where the grid is powered predominantly by renewable energy, EVs produce dramatically fewer lifecycle greenhouse gas emissions than combustion vehicles. Even in areas reliant on fossil-fuel generation, EVs typically produce lower emissions due to the superior efficiency of electric motors, which convert approximately ninety per cent of electrical energy to motion compared with roughly thirty per cent for internal combustion engines. However, the mining and processing of battery materials — lithium, cobalt, nickel, and manganese — raise legitimate environmental and ethical concerns that the industry must address through responsible sourcing and improved recycling technologies.

F. The rise of electric vehicles has profound implications for energy systems. Widespread EV adoption will substantially increase electricity demand, requiring significant investment in generation capacity and grid infrastructure. However, EV batteries also represent a potential resource: vehicle-to-grid (V2G) technology enables parked electric vehicles to feed stored energy back into the grid during periods of peak demand, effectively functioning as distributed energy storage. This capability could prove invaluable for integrating intermittent renewable energy sources such as wind and solar power.

G. Geopolitically, the transition to electric mobility is redrawing the map of energy dependence. Countries that currently rely on oil imports stand to benefit from reduced exposure to volatile petroleum markets, while nations rich in battery minerals — particularly Australia, Chile, the Democratic Republic of Congo, and China — are gaining strategic importance. China currently dominates the global EV supply chain, controlling a majority of lithium-ion battery manufacturing capacity and rare earth mineral processing. Western governments are responding with industrial policies aimed at developing domestic battery production and diversifying mineral supply chains.

H. The pace of the electric transition continues to accelerate. Global EV sales exceeded ten million units in 2022 and are projected to reach forty million by 2030. While challenges remain — including charging infrastructure, battery recycling, mineral supply constraints, and the affordability of entry-level models — the direction of travel is clear. The internal combustion engine, which dominated personal transportation for over a century, is approaching the end of its era.`,
      questions: [
        { number: 27, type: "multiple_choice", text: "According to the passage, what happened to electric cars at the beginning of the twentieth century?", options: ["A They became the dominant form of transport.", "B They outsold gasoline cars in the US.", "C They were banned by governments.", "D They were used only for commercial purposes."], correctAnswer: "B", explanation: "The passage states 'by the 1900s, electric cars outsold gasoline-powered vehicles in the United States.'" },
        { number: 28, type: "multiple_choice", text: "What does the passage identify as the most important factor in making EVs price-competitive?", options: ["A Government subsidies", "B Improvements in vehicle design", "C The reduction in battery costs", "D Consumer demand for green technology"], correctAnswer: "C", explanation: "The passage states 'This cost reduction has been the single most important factor.'" },
        { number: 29, type: "multiple_choice", text: "What is vehicle-to-grid (V2G) technology?", options: ["A A system for tracking electric vehicle locations", "B A method for EVs to supply energy back to the power grid", "C A charging standard for ultra-fast chargers", "D A type of battery management system"], correctAnswer: "B", explanation: "The passage describes V2G as enabling 'parked electric vehicles to feed stored energy back into the grid.'" },
        { number: 30, type: "multiple_choice", text: "Which country dominates the global EV supply chain according to the passage?", options: ["A Australia", "B The United States", "C Germany", "D China"], correctAnswer: "D", explanation: "The passage states 'China currently dominates the global EV supply chain.'" },
        { number: 31, type: "flow_chart_completion", text: "In 2010, the average battery cost was approximately $__(31)__ per kilowatt-hour.", correctAnswer: "1,100", explanation: "The passage states 'approximately $1,100 per kilowatt-hour.'" },
        { number: 32, type: "flow_chart_completion", text: "By 2023, battery costs had fallen to around $__(32)__ per kilowatt-hour.", correctAnswer: "140", explanation: "The passage states 'around $140.'" },
        { number: 33, type: "flow_chart_completion", text: "Ultra-fast chargers can deliver __(33)__ kilometres of range in fifteen minutes.", correctAnswer: "three hundred", explanation: "The passage mentions 'three hundred kilometres of range in fifteen minutes.'" },
        { number: 34, type: "flow_chart_completion", text: "Global EV sales exceeded __(34)__ million units in 2022.", correctAnswer: "ten", explanation: "The passage states 'Global EV sales exceeded ten million units in 2022.'" },
        { number: 35, type: "sentence_completion", text: "Electric motors convert approximately __(35)__ per cent of electrical energy to motion.", correctAnswer: "ninety", explanation: "The passage states 'approximately ninety per cent of electrical energy to motion.'" },
        { number: 36, type: "sentence_completion", text: "The modern EV revival began with the launch of the Tesla __(36)__ in 2008.", correctAnswer: "Roadster", explanation: "The passage mentions 'the launch of the Tesla Roadster in 2008.'" },
        { number: 37, type: "sentence_completion", text: "The EU mandates fast chargers every __(37)__ kilometres along major highways.", correctAnswer: "sixty", explanation: "The passage states 'every sixty kilometres along major highways.'" },
        { number: 38, type: "sentence_completion", text: "Scottish inventor Robert __(38)__ built one of the first electric carriages in the 1830s.", correctAnswer: "Anderson", explanation: "The passage names 'Scottish inventor Robert Anderson.'" },
        { number: 39, type: "sentence_completion", text: "EV sales are projected to reach __(39)__ million by 2030.", correctAnswer: "forty", explanation: "The passage states 'projected to reach forty million by 2030.'" },
        { number: 40, type: "sentence_completion", text: "Internal combustion engines convert roughly __(40)__ per cent of energy to motion.", correctAnswer: "thirty", explanation: "The passage states 'roughly thirty per cent for internal combustion engines.'" },
      ],
    },
  ],
};
