import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_12: ReadingTest = {
  id: 12,
  passages: [
    {
      title: "Early Railway Systems",
      text: `The development of railway systems in the early nineteenth century represented one of the most transformative technological achievements in human history, fundamentally altering patterns of trade, travel, urbanisation, and social interaction across the industrialising world. The railway did not emerge from a single moment of invention but rather evolved through a series of incremental innovations spanning several decades.

The concept of using rails to guide wheeled vehicles predates the steam locomotive by several centuries. Wooden wagonways were used in German mines as early as the sixteenth century to transport ore, and by the seventeenth century similar systems had been adopted in English coal mines, where horses pulled wagons along wooden — and later iron — tracks. These primitive railways, known as tramways, significantly reduced the friction involved in moving heavy loads, enabling a single horse to haul far more material than it could on an ordinary road.

The critical breakthrough came with the development of the steam locomotive. Richard Trevithick, a Cornish engineer, built the world's first steam-powered railway locomotive in 1804, which hauled ten tonnes of iron and seventy passengers along a tramway in South Wales. However, Trevithick's engine was too heavy for the brittle cast-iron rails of the period, which frequently cracked under its weight. It was George Stephenson, a self-educated colliery engineer from Northumberland, who made the steam railway commercially viable. Stephenson's Locomotion No. 1 inaugurated the Stockton and Darlington Railway in 1825, the world's first public railway to use steam locomotion for the transport of both goods and passengers. Five years later, Stephenson's Rocket won the Rainhill Trials, a competition to select a locomotive for the Liverpool and Manchester Railway — the first inter-city railway in the world, which opened in 1830.

The Liverpool and Manchester Railway was a commercial and engineering triumph that demonstrated the enormous potential of rail transport. It carried both passengers and freight, operated to a fixed timetable, and charged fares for travel — establishing the fundamental business model that railways would follow for generations. The railway's success triggered a wave of railway construction across Britain, a phenomenon that became known as "railway mania." By 1850, over 10,000 kilometres of track had been laid in Britain, and the railway network connected virtually every major city and industrial centre in the country.

The impact of railways on British society was profound and far-reaching. Railways dramatically reduced the time and cost of transporting goods, enabling manufacturers to reach distant markets and consumers to access a wider range of products. They stimulated the growth of industries such as coal, iron, and steel, which supplied the materials for track, locomotives, and rolling stock. Railways also transformed personal mobility: for the first time, ordinary working people could travel significant distances quickly and affordably. The railway excursion — a cheap, organised trip to the seaside or countryside — became a popular form of leisure, and seaside towns such as Brighton, Blackpool, and Scarborough grew rapidly as a result.

Railways also had a standardising effect on British life. Before the railway age, each town kept its own local time, based on the position of the sun. The need for a coordinated railway timetable led to the adoption of Greenwich Mean Time as a national standard in 1847, replacing the patchwork of local times that had previously prevailed. The railways also contributed to the standardisation of the English language, as people from different regions mixed more freely, and to the emergence of a national press, as newspapers printed in London could be distributed across the country within hours.

The success of the British railway model was quickly replicated across the world. The first railway in continental Europe opened between Brussels and Mechelen in Belgium in 1835. In the United States, railway construction proceeded at a frenetic pace: by 1860, the country had over 48,000 kilometres of track, and the completion of the Transcontinental Railroad in 1869, linking the Atlantic and Pacific coasts, was celebrated as one of the greatest engineering achievements of the century. Railways also played a critical role in the colonisation and economic development of India, Canada, Australia, and numerous African countries, where they were built primarily to facilitate the extraction and export of natural resources.

The legacy of the early railway systems endures to this day. The principles of railway engineering, operations, and management developed in the nineteenth century remain the foundation of modern rail transport, and the high-speed trains of the twenty-first century — capable of travelling at over 350 kilometres per hour — are the direct descendants of Stephenson's pioneering locomotives.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "The earliest forms of railway were used primarily for", options: ["A transporting passengers between cities.", "B moving materials in mining operations.", "C carrying military supplies.", "D connecting ports to inland towns."], correctAnswer: "B", explanation: "The passage says wooden wagonways 'were used in German mines' and English coal mines to transport ore and materials." },
        { number: 2, type: "multiple_choice", text: "Richard Trevithick's locomotive was not commercially successful because", options: ["A it was too slow for practical use.", "B the rails were too fragile to support its weight.", "C there was no demand for steam transport.", "D the government refused to fund railway development."], correctAnswer: "B", explanation: "The passage states Trevithick's engine was 'too heavy for the brittle cast-iron rails of the period, which frequently cracked.'" },
        { number: 3, type: "multiple_choice", text: "The Liverpool and Manchester Railway was significant because it", options: ["A was the first railway in the world.", "B used electric-powered locomotives.", "C established the basic business model for railways.", "D was funded entirely by the British government."], correctAnswer: "C", explanation: "The passage says it 'charged fares for travel — establishing the fundamental business model that railways would follow for generations.'" },
        { number: 4, type: "multiple_choice", text: "The adoption of Greenwich Mean Time was driven by", options: ["A international diplomatic agreements.", "B the need for coordinated railway timetables.", "C advances in clock-making technology.", "D the requirements of the British Navy."], correctAnswer: "B", explanation: "The passage states 'The need for a coordinated railway timetable led to the adoption of Greenwich Mean Time.'" },
        { number: 5, type: "multiple_choice", text: "According to the passage, railways in colonised countries were built mainly to", options: ["A benefit local populations.", "B support military operations.", "C facilitate the export of natural resources.", "D encourage tourism."], correctAnswer: "C", explanation: "The passage says railways were 'built primarily to facilitate the extraction and export of natural resources.'" },
        { number: 6, type: "true_false_not_given", text: "Wooden wagonways were first used in English mines.", correctAnswer: "FALSE", explanation: "The passage says they were used 'in German mines as early as the sixteenth century' before English adoption." },
        { number: 7, type: "true_false_not_given", text: "George Stephenson had a university engineering degree.", correctAnswer: "FALSE", explanation: "The passage describes Stephenson as 'a self-educated colliery engineer.'" },
        { number: 8, type: "true_false_not_given", text: "The Stockton and Darlington Railway opened in 1825.", correctAnswer: "TRUE", explanation: "The passage states 'inaugurated the Stockton and Darlington Railway in 1825.'" },
        { number: 9, type: "true_false_not_given", text: "By 1850, Britain had over 10,000 kilometres of railway track.", correctAnswer: "TRUE", explanation: "The passage says 'By 1850, over 10,000 kilometres of track had been laid in Britain.'" },
        { number: 10, type: "true_false_not_given", text: "The Rainhill Trials were held in Liverpool.", correctAnswer: "NOT GIVEN", explanation: "The passage mentions the Rainhill Trials but does not specify where exactly they were held." },
        { number: 11, type: "true_false_not_given", text: "The first continental European railway opened in France.", correctAnswer: "FALSE", explanation: "The passage states 'The first railway in continental Europe opened between Brussels and Mechelen in Belgium.'" },
        { number: 12, type: "true_false_not_given", text: "The US Transcontinental Railroad was completed before 1870.", correctAnswer: "TRUE", explanation: "The passage says 'the completion of the Transcontinental Railroad in 1869.'" },
        { number: 13, type: "true_false_not_given", text: "Modern high-speed trains can exceed 400 kilometres per hour.", correctAnswer: "NOT GIVEN", explanation: "The passage says 'over 350 kilometres per hour' but does not state they exceed 400." },
      ],
    },
    {
      title: "Urban Population Growth",
      text: `A. The growth of urban populations is one of the most significant demographic trends of the modern era. For the first time in human history, more than half the world's population now lives in cities — a threshold crossed in 2007. The United Nations projects that by 2050, approximately 68 percent of the global population will be urban, with virtually all of the net growth occurring in developing countries, particularly in Africa and Asia. This unprecedented wave of urbanisation presents both enormous opportunities and daunting challenges for governments, urban planners, and the billions of people whose lives it will shape.

B. The pace and scale of urban growth vary dramatically across regions. In sub-Saharan Africa, cities are growing at an average annual rate of over 4 percent, driven by high birth rates and rural-to-urban migration. Lagos, Nigeria's commercial capital, has grown from approximately 1.4 million inhabitants in 1970 to over 15 million today, and is projected to become one of the world's largest cities by mid-century. In contrast, many cities in Europe and East Asia are experiencing population decline or stagnation, as low birth rates and ageing demographics reduce the number of working-age residents. Cities such as Shrinking cities like Leipzig in Germany and many municipalities across rural Japan face the challenge of maintaining infrastructure and services for dwindling populations.

C. Urbanisation has historically been associated with economic development. Cities offer concentrations of labour, capital, and infrastructure that enable higher levels of productivity and innovation than rural areas. Urban workers typically earn higher wages and have access to better healthcare, education, and social services. The "agglomeration economies" generated by dense urban environments — where firms benefit from proximity to suppliers, customers, and competitors, and where knowledge and ideas spread rapidly through face-to-face interaction — are a key driver of economic growth. The World Bank estimates that cities generate over 80 percent of global GDP, despite occupying only about 3 percent of the Earth's land surface.

D. However, rapid and unplanned urban growth often produces significant social and environmental problems. In many developing-world cities, a substantial proportion of the urban population lives in informal settlements — also known as slums — characterised by overcrowding, inadequate sanitation, unreliable water supply, and insecure land tenure. The United Nations estimates that over one billion people currently live in slum conditions worldwide, a figure projected to rise to 1.6 billion by 2030 if current trends continue. The lack of formal housing, employment, and basic services in these settlements creates conditions that perpetuate poverty, ill health, and social exclusion.

E. The environmental footprint of cities is substantial and growing. Urban areas are responsible for approximately 75 percent of global energy consumption and 70 percent of carbon dioxide emissions. The expansion of cities into surrounding rural and natural areas — a process known as urban sprawl — consumes agricultural land, fragments wildlife habitats, and increases dependence on private car transport, further exacerbating greenhouse gas emissions and air pollution. Water management is another critical challenge: many rapidly growing cities face severe water stress, while inadequate drainage and stormwater management systems increase vulnerability to flooding, particularly as climate change intensifies rainfall patterns.

F. Addressing the challenges of urban population growth requires a multifaceted approach that combines investment in infrastructure, progressive urban planning, inclusive governance, and technological innovation. Transit-oriented development — designing neighbourhoods around high-capacity public transport corridors — can reduce car dependence, lower emissions, and promote more compact, walkable urban forms. Green building standards and energy-efficient construction techniques can significantly reduce the carbon footprint of the built environment. Digital technologies, including smart traffic management systems, intelligent waste collection, and data-driven urban planning tools, are enabling cities to operate more efficiently and responsively. Above all, ensuring that the benefits of urbanisation are shared equitably — reaching the poorest and most marginalised urban residents — will be essential for building cities that are not only economically productive but also socially just and environmentally sustainable.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Paragraph B", options: ["i. The link between cities and economic productivity", "ii. Regional variations in urban growth rates", "iii. Strategies for managing urban expansion", "iv. The environmental impact of growing cities", "v. The global shift towards urban living", "vi. Living conditions in informal urban settlements", "vii. The historical origins of urbanisation", "viii. Competition between cities for investment"], correctAnswer: "ii", explanation: "Paragraph B contrasts rapid growth in Africa with decline in Europe and East Asia — regional variations." },
        { number: 15, type: "matching_headings", text: "Paragraph C", options: ["i. The link between cities and economic productivity", "ii. Regional variations in urban growth rates", "iii. Strategies for managing urban expansion", "iv. The environmental impact of growing cities", "v. The global shift towards urban living", "vi. Living conditions in informal urban settlements", "vii. The historical origins of urbanisation", "viii. Competition between cities for investment"], correctAnswer: "i", explanation: "Paragraph C discusses agglomeration economies and cities generating 80% of global GDP." },
        { number: 16, type: "matching_headings", text: "Paragraph D", options: ["i. The link between cities and economic productivity", "ii. Regional variations in urban growth rates", "iii. Strategies for managing urban expansion", "iv. The environmental impact of growing cities", "v. The global shift towards urban living", "vi. Living conditions in informal urban settlements", "vii. The historical origins of urbanisation", "viii. Competition between cities for investment"], correctAnswer: "vi", explanation: "Paragraph D discusses slums, overcrowding, and inadequate sanitation." },
        { number: 17, type: "matching_headings", text: "Paragraph E", options: ["i. The link between cities and economic productivity", "ii. Regional variations in urban growth rates", "iii. Strategies for managing urban expansion", "iv. The environmental impact of growing cities", "v. The global shift towards urban living", "vi. Living conditions in informal urban settlements", "vii. The historical origins of urbanisation", "viii. Competition between cities for investment"], correctAnswer: "iv", explanation: "Paragraph E discusses energy consumption, CO2 emissions, urban sprawl, and water stress." },
        { number: 18, type: "matching_headings", text: "Paragraph F", options: ["i. The link between cities and economic productivity", "ii. Regional variations in urban growth rates", "iii. Strategies for managing urban expansion", "iv. The environmental impact of growing cities", "v. The global shift towards urban living", "vi. Living conditions in informal urban settlements", "vii. The historical origins of urbanisation", "viii. Competition between cities for investment"], correctAnswer: "iii", explanation: "Paragraph F discusses transit-oriented development, green building, and digital technologies as strategies." },
        { number: 19, type: "summary_completion", text: "The majority of the world's population became urban dwellers in the year _______.", correctAnswer: "2007", explanation: "The passage states the threshold was 'crossed in 2007.'" },
        { number: 20, type: "summary_completion", text: "By 2050, approximately _______ percent of people will live in cities.", correctAnswer: "68", explanation: "The passage says 'approximately 68 percent of the global population will be urban.'" },
        { number: 21, type: "summary_completion", text: "Cities in sub-Saharan Africa are growing at over _______ percent annually.", correctAnswer: "4", explanation: "The passage states 'cities are growing at an average annual rate of over 4 percent.'" },
        { number: 22, type: "summary_completion", text: "Lagos had approximately _______ million inhabitants in 1970.", correctAnswer: "1.4", explanation: "The passage says Lagos 'has grown from approximately 1.4 million inhabitants in 1970.'" },
        { number: 23, type: "summary_completion", text: "Cities generate over _______ percent of global GDP.", correctAnswer: "80", explanation: "The passage states 'cities generate over 80 percent of global GDP.'" },
        { number: 24, type: "summary_completion", text: "Over one _______ people currently live in slum conditions worldwide.", correctAnswer: "billion", explanation: "The passage says 'over one billion people currently live in slum conditions.'" },
        { number: 25, type: "summary_completion", text: "Urban areas are responsible for approximately _______ percent of global energy consumption.", correctAnswer: "75", explanation: "The passage states 'approximately 75 percent of global energy consumption.'" },
        { number: 26, type: "summary_completion", text: "Cities produce approximately _______ percent of global carbon dioxide emissions.", correctAnswer: "70", explanation: "The passage says '70 percent of carbon dioxide emissions.'" },
      ],
    },
    {
      title: "Artificial Intelligence in Education",
      text: `The integration of artificial intelligence into education is transforming the way students learn, teachers teach, and educational institutions operate. From intelligent tutoring systems that adapt to individual learning needs to AI-powered tools that automate administrative tasks, the potential applications of AI in education are vast and rapidly expanding. However, this technological revolution also raises important questions about equity, privacy, the role of teachers, and the nature of learning itself.

A. Adaptive learning platforms represent one of the most developed applications of AI in education. These systems use machine learning algorithms to analyse a student's performance in real time — tracking which questions they answer correctly, how long they spend on each task, which topics they struggle with, and how their understanding evolves over time. Based on this analysis, the platform dynamically adjusts the difficulty, pace, and content of instruction to match the individual student's needs, providing additional practice and explanation where understanding is weak and accelerating through material that has already been mastered. Research suggests that adaptive learning can improve student outcomes by 20 to 30 percent compared with traditional one-size-fits-all instruction, particularly for students who are significantly ahead of or behind the average level of their class.

B. AI-powered assessment and feedback tools are reducing the burden of routine marking on teachers while providing students with faster, more detailed feedback on their work. Natural language processing (NLP) algorithms can evaluate written essays, providing scores and comments on aspects such as grammar, coherence, argument structure, and use of evidence. Automated coding assessors can test student programs against predefined criteria, identifying errors and suggesting improvements. While AI assessment tools are not yet sophisticated enough to replace human judgement entirely — particularly for evaluating creativity, critical thinking, and nuanced argumentation — they can handle a significant proportion of routine assessment tasks, freeing teachers to focus on higher-order pedagogical activities such as mentoring, discussion facilitation, and curriculum design.

C. Virtual teaching assistants and chatbots powered by large language models are being deployed in universities and online learning platforms to provide 24/7 support to students. These AI assistants can answer frequently asked questions about course content, deadlines, and administrative procedures; explain concepts in multiple ways; generate practice questions and quizzes; and even engage in Socratic-style dialogues that encourage deeper thinking. Georgia Institute of Technology famously deployed an AI teaching assistant named "Jill Watson" in an online course, and many students did not realise they were interacting with a machine until informed at the end of the semester. The ability of AI assistants to provide immediate, personalised support at any time of day is particularly valuable in large courses and online learning environments where individual access to human instructors is limited.

D. Learning analytics — the collection, analysis, and reporting of data about learners and their contexts — is enabling educational institutions to identify at-risk students and intervene proactively. By analysing patterns in student engagement data — such as login frequency, time spent on learning materials, assignment submission patterns, and participation in discussion forums — AI systems can predict which students are likely to fail or drop out with considerable accuracy. Early warning systems based on learning analytics have been shown to reduce dropout rates by up to 15 percent in some institutions. However, the extensive collection of student data raises significant privacy concerns, and institutions must navigate complex ethical and legal frameworks governing data protection, consent, and the transparency of algorithmic decision-making.

E. The role of the teacher in an AI-enhanced educational environment is a subject of ongoing debate. Some commentators have predicted that AI will eventually replace teachers altogether, rendering the traditional classroom obsolete. Most education researchers, however, argue that AI is far more likely to augment rather than replace human teachers. The aspects of teaching that are most difficult for AI to replicate — building relationships with students, inspiring motivation and curiosity, modelling ethical reasoning, managing classroom dynamics, and providing emotional support — are precisely those that research identifies as most critical to effective learning. The most promising vision of AI in education is one in which technology handles routine, data-intensive tasks while teachers are liberated to focus on the uniquely human dimensions of their profession.

F. Access and equity remain critical concerns as AI becomes more prevalent in education. The benefits of AI-powered educational tools are disproportionately available to well-resourced schools and students in wealthy countries, potentially widening existing educational inequalities rather than narrowing them. Students in low-income communities and developing nations often lack the hardware, internet connectivity, and digital literacy skills needed to benefit from AI-based learning platforms. Furthermore, AI systems trained predominantly on data from Western, English-speaking populations may perform poorly when applied to diverse cultural and linguistic contexts. Ensuring that AI in education serves as a force for inclusion rather than exclusion will require deliberate policy interventions, investment in digital infrastructure, and the development of AI tools that are sensitive to the needs of diverse learner populations.`,
      questions: [
        { number: 27, type: "matching_information", text: "The risk that AI in education may increase inequality between rich and poor students", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "F", explanation: "Paragraph F discusses how AI benefits are 'disproportionately available to well-resourced schools' and may widen inequalities." },
        { number: 28, type: "matching_information", text: "An AI teaching assistant that students mistook for a human", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "C", explanation: "Paragraph C describes Georgia Tech's 'Jill Watson' where 'many students did not realise they were interacting with a machine.'" },
        { number: 29, type: "matching_information", text: "The use of data to predict which students might fail a course", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "D", explanation: "Paragraph D discusses learning analytics predicting 'which students are likely to fail or drop out.'" },
        { number: 30, type: "matching_information", text: "The qualities of teaching that AI cannot easily replicate", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "E", explanation: "Paragraph E lists relationship-building, motivation, ethical reasoning, and emotional support as difficult for AI." },
        { number: 31, type: "matching_information", text: "Software that adjusts lesson difficulty based on a student's real-time performance", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "A", explanation: "Paragraph A describes adaptive learning platforms that 'dynamically adjusts the difficulty, pace, and content.'" },
        { number: 32, type: "sentence_completion", text: "Adaptive learning can improve student outcomes by _______ to 30 percent.", correctAnswer: "20", explanation: "The passage states 'improve student outcomes by 20 to 30 percent.'" },
        { number: 33, type: "sentence_completion", text: "NLP algorithms can evaluate essays for grammar, coherence, argument structure, and use of _______.", correctAnswer: "evidence", explanation: "The passage lists 'grammar, coherence, argument structure, and use of evidence.'" },
        { number: 34, type: "sentence_completion", text: "Georgia Tech's AI assistant was named _______.", correctAnswer: "Jill Watson", explanation: "The passage names the assistant 'Jill Watson.'" },
        { number: 35, type: "sentence_completion", text: "Learning analytics early warning systems have reduced dropout rates by up to _______ percent.", correctAnswer: "15", explanation: "The passage says 'reduce dropout rates by up to 15 percent.'" },
        { number: 36, type: "sentence_completion", text: "Most researchers believe AI will _______ teachers rather than replace them.", correctAnswer: "augment", explanation: "The passage states 'AI is far more likely to augment rather than replace human teachers.'" },
        { number: 37, type: "sentence_completion", text: "AI systems trained on Western data may perform poorly in diverse cultural and _______ contexts.", correctAnswer: "linguistic", explanation: "The passage says 'diverse cultural and linguistic contexts.'" },
        { number: 38, type: "sentence_completion", text: "AI chatbots can engage students in _______-style dialogues to encourage deeper thinking.", correctAnswer: "Socratic", explanation: "The passage mentions 'Socratic-style dialogues.'" },
        { number: 39, type: "sentence_completion", text: "Teachers freed by AI can focus on mentoring, discussion facilitation, and curriculum _______.", correctAnswer: "design", explanation: "The passage lists 'mentoring, discussion facilitation, and curriculum design.'" },
        { number: 40, type: "sentence_completion", text: "The collection of student data raises significant _______ concerns in educational settings.", correctAnswer: "privacy", explanation: "The passage states 'the extensive collection of student data raises significant privacy concerns.'" },
      ],
    },
  ],
};
