import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_46: ReadingTest = {
  id: 46,
  passages: [
    {
      title: "Stepwells and Ancient Water Systems",
      text: `Throughout much of South Asia, access to water has been a defining concern for millennia. Among the most remarkable responses to this challenge are stepwells — architectural structures that combine practical water management with ornate beauty. Found primarily in western India, stepwells, known locally as "vav" or "baoli," were built as early as the third millennium BCE, though the most celebrated examples date from medieval times. These subterranean marvels descend deep into the earth, reaching the water table through elaborate staircases that double as gathering spaces, temples, and even marketplaces.

The earliest stepwells were simple pits with rudimentary steps carved into rock. Over centuries, they evolved into sophisticated feats of engineering. The Rani ki Vav in Patan, Gujarat — now a UNESCO World Heritage Site — exemplifies this progression. Commissioned around 1063 CE by Queen Udayamati in memory of her husband, it extends over sixty metres in length and descends through seven levels of intricately carved galleries adorned with more than five hundred sculptures. At the lowest level, water still pools in the well shaft, demonstrating the enduring ingenuity of its creators.

Stepwells served multiple functions beyond mere water storage. In regions where summer temperatures routinely exceed forty-five degrees Celsius, they offered a naturally cool refuge. The subterranean chambers could be ten to fifteen degrees cooler than the surface, providing relief to travellers and locals alike. Many stepwells contained small shrines or prayer niches, integrating spiritual life with the daily routine of water collection. Women, who traditionally bore the responsibility of fetching water, often gathered in these spaces, making stepwells informal centres of social interaction.

The engineering behind stepwells addressed a fundamental hydrological challenge: the dramatic seasonal fluctuation of the water table. During monsoon months, groundwater levels could rise by several metres, submerging the lower galleries. Builders accounted for this by designing multiple levels, ensuring that at least some steps remained accessible year-round. The deepest chambers were equipped with sluice gates and channels that regulated water flow, preventing erosion while directing overflow to nearby agricultural fields.

Beyond the Indian subcontinent, other civilisations devised equally inventive water management systems. The qanats of ancient Persia — underground channels that transported water from mountain aquifers to lowland settlements — represent a parallel tradition. Developed around 1000 BCE, qanats employed a series of vertical shafts connected by gently sloping tunnels, relying entirely on gravity for water transport. Some qanats extended over seventy kilometres, sustaining entire cities in otherwise arid landscapes. The technology spread westward to North Africa and eastward to China along trade routes.

Roman aqueducts, though more visually dramatic, operated on similar principles. By the first century CE, Rome's eleven aqueducts delivered approximately one million cubic metres of water daily. The Pont du Gard in southern France, standing nearly fifty metres high, carried water across the Gardon valley for over four centuries. Yet unlike stepwells, which were designed for community access, Roman aqueducts served a centralised urban infrastructure, feeding public baths, fountains, and private estates.

The decline of stepwells began during British colonial rule in the nineteenth century. Colonial administrators, viewing the structures as breeding grounds for disease, filled many in or capped them with modern plumbing. By the mid-twentieth century, thousands of stepwells across India had fallen into disrepair. In recent decades, however, a revival movement has gained momentum. Conservation organisations have restored dozens of stepwells, and several Indian states now classify them as protected heritage sites. Architects and urban planners have even begun incorporating stepwell-inspired designs into contemporary buildings, recognising their passive cooling potential as an alternative to energy-intensive air conditioning.

Today, as climate change intensifies water scarcity in many parts of the world, ancient water management systems offer instructive models. The principles underlying stepwells, qanats, and aqueducts — gravity-fed distribution, seasonal water storage, and community-centred access — resonate with modern sustainability goals. Researchers at institutions across South Asia are studying these systems not merely as historical curiosities but as blueprints for resilient water infrastructure in an uncertain future.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "According to the passage, the earliest stepwells were", options: ["A. elaborately decorated structures", "B. simple pits with basic steps", "C. used exclusively for religious purposes", "D. built alongside Roman aqueducts"], correctAnswer: "B", explanation: "The passage states 'The earliest stepwells were simple pits with rudimentary steps carved into rock.'" },
        { number: 2, type: "multiple_choice", text: "The Rani ki Vav was built to", options: ["A. store water for the entire city", "B. serve as a marketplace", "C. commemorate a queen's husband", "D. demonstrate Roman engineering techniques"], correctAnswer: "C", explanation: "The passage states it was 'Commissioned around 1063 CE by Queen Udayamati in memory of her husband.'" },
        { number: 3, type: "multiple_choice", text: "What advantage did stepwells offer during hot weather?", options: ["A. They provided flowing water for bathing", "B. They were significantly cooler underground", "C. They generated electricity for cooling", "D. They reflected sunlight away from settlements"], correctAnswer: "B", explanation: "The passage notes subterranean chambers 'could be ten to fifteen degrees cooler than the surface.'" },
        { number: 4, type: "multiple_choice", text: "Persian qanats relied on which principle to transport water?", options: ["A. Mechanical pumps", "B. Steam pressure", "C. Gravity", "D. Wind power"], correctAnswer: "C", explanation: "The passage says qanats relied 'entirely on gravity for water transport.'" },
        { number: 5, type: "true_false_not_given", text: "Stepwells were found mainly in eastern India.", correctAnswer: "FALSE", explanation: "The passage says they are 'Found primarily in western India.'" },
        { number: 6, type: "true_false_not_given", text: "The Rani ki Vav contains more than five hundred sculptures.", correctAnswer: "TRUE", explanation: "The passage directly states it is 'adorned with more than five hundred sculptures.'" },
        { number: 7, type: "true_false_not_given", text: "Roman aqueducts were designed primarily for community-level access.", correctAnswer: "FALSE", explanation: "The passage says 'unlike stepwells, which were designed for community access, Roman aqueducts served a centralised urban infrastructure.'" },
        { number: 8, type: "true_false_not_given", text: "Qanat technology originated in Egypt.", correctAnswer: "NOT GIVEN", explanation: "The passage says qanats were from 'ancient Persia' and spread to North Africa and China, but does not mention Egypt as the origin." },
        { number: 9, type: "true_false_not_given", text: "Some Indian states now classify stepwells as protected heritage sites.", correctAnswer: "TRUE", explanation: "The passage states 'several Indian states now classify them as protected heritage sites.'" },
        { number: 10, type: "sentence_completion", text: "During monsoon months, groundwater levels could rise by several metres, submerging the lower ________.", correctAnswer: "galleries", explanation: "The passage says 'submerging the lower galleries.'" },
        { number: 11, type: "sentence_completion", text: "Women who fetched water used stepwells as informal centres of ________.", correctAnswer: "social interaction", explanation: "The passage says 'making stepwells informal centres of social interaction.'" },
        { number: 12, type: "sentence_completion", text: "Colonial administrators believed stepwells were breeding grounds for ________.", correctAnswer: "disease", explanation: "The passage says colonial administrators viewed them 'as breeding grounds for disease.'" },
        { number: 13, type: "sentence_completion", text: "Architects now recognise stepwells' passive ________ potential as an alternative to air conditioning.", correctAnswer: "cooling", explanation: "The passage mentions 'their passive cooling potential as an alternative to energy-intensive air conditioning.'" }
      ]
    },
    {
      title: "Urban Transportation Evolution",
      text: `A. The way people move through cities has undergone dramatic transformations over the past two centuries. From horse-drawn carriages to electric scooters, urban transportation reflects broader patterns of technological innovation, economic development, and social change. Understanding this evolution is essential for designing the sustainable mobility systems that twenty-first-century cities require.

B. The first major revolution in urban transport came with the introduction of horse-drawn omnibuses in Paris during the 1820s. These public vehicles followed fixed routes and charged affordable fares, making mobility accessible beyond the wealthy. By the mid-nineteenth century, omnibus services had spread to London, New York, and other major cities. However, the reliance on horses created significant problems: manure accumulation, animal welfare concerns, and the sheer space required for stabling thousands of animals within city limits.

C. The development of street railways — initially horse-drawn, then electrified — represented the next leap forward. San Francisco's cable cars, introduced in 1873, used underground cables to haul carriages up the city's steep hills. Electric trams followed in the 1880s, with Richmond, Virginia, operating the first successful commercial electric streetcar system in 1888. These systems dramatically expanded the geographic reach of cities, enabling workers to live further from their places of employment and giving rise to the first suburban communities.

D. The arrival of the automobile in the early twentieth century reshaped urban landscapes profoundly. Henry Ford's assembly-line production methods made cars affordable for middle-class families, and by the 1920s, American cities were already adapting their infrastructure to accommodate motor vehicles. Roads were widened, parking lots constructed, and entire neighbourhoods demolished to make way for highways. This car-centric planning philosophy dominated urban development for decades, particularly in North America and Australia.

E. Public transit systems evolved in parallel. The London Underground, which opened in 1863, was the world's first underground railway. Other cities followed: Budapest in 1896, Paris in 1900, New York in 1904. These metro systems moved vast numbers of people efficiently beneath congested streets. Yet investment in public transport often lagged behind road construction, especially after World War II, when governments in many countries prioritised highway building as a driver of economic growth.

F. The late twentieth century brought growing awareness of the environmental and social costs of car dependency. Traffic congestion, air pollution, road accidents, and the isolation of car-dependent suburbs prompted a reassessment of urban transport priorities. Cities such as Curitiba in Brazil pioneered bus rapid transit (BRT) systems that offered metro-like service at a fraction of the cost. Bogotá's TransMilenio, launched in 2000, demonstrated that BRT could transform mobility in developing-world cities.

G. Today, urban transportation is entering another period of rapid change. Ride-hailing services, electric vehicles, autonomous driving technology, and micro-mobility options like e-bikes and e-scooters are reshaping how people navigate cities. Many urban planners now advocate for "multimodal" transport networks that integrate multiple forms of transit into seamless journeys. The concept of "mobility as a service" (MaaS) envisions smartphone apps that allow users to plan, book, and pay for trips combining buses, trains, bikes, and ride-shares in a single interface.

H. Perhaps the most significant trend is the growing emphasis on reducing car use altogether. Cities across Europe — including Oslo, Barcelona, and Paris — are reclaiming street space from vehicles and dedicating it to pedestrians, cyclists, and green spaces. Paris's ambitious "15-minute city" concept aims to ensure that all essential services are accessible within a short walk or cycle from any residence. These initiatives reflect a broader recognition that sustainable urban transport is not merely a technical challenge but a question of how cities choose to allocate their most valuable resource: public space.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Paragraph B", options: ["i. The dominance of the private car", "ii. Horse-drawn public transport emerges", "iii. Underground railways change cities", "iv. Modern alternatives to car ownership", "v. Environmental costs prompt rethinking", "vi. Electric trams extend city boundaries", "vii. A new vision for urban space", "viii. Bus rapid transit in the developing world", "ix. Integrating multiple transport modes"], correctAnswer: "ii", explanation: "Paragraph B discusses the introduction of horse-drawn omnibuses in Paris." },
        { number: 15, type: "matching_headings", text: "Paragraph D", options: ["i. The dominance of the private car", "ii. Horse-drawn public transport emerges", "iii. Underground railways change cities", "iv. Modern alternatives to car ownership", "v. Environmental costs prompt rethinking", "vi. Electric trams extend city boundaries", "vii. A new vision for urban space", "viii. Bus rapid transit in the developing world", "ix. Integrating multiple transport modes"], correctAnswer: "i", explanation: "Paragraph D describes how the automobile reshaped urban landscapes." },
        { number: 16, type: "matching_headings", text: "Paragraph F", options: ["i. The dominance of the private car", "ii. Horse-drawn public transport emerges", "iii. Underground railways change cities", "iv. Modern alternatives to car ownership", "v. Environmental costs prompt rethinking", "vi. Electric trams extend city boundaries", "vii. A new vision for urban space", "viii. Bus rapid transit in the developing world", "ix. Integrating multiple transport modes"], correctAnswer: "v", explanation: "Paragraph F discusses environmental and social costs of car dependency." },
        { number: 17, type: "matching_headings", text: "Paragraph H", options: ["i. The dominance of the private car", "ii. Horse-drawn public transport emerges", "iii. Underground railways change cities", "iv. Modern alternatives to car ownership", "v. Environmental costs prompt rethinking", "vi. Electric trams extend city boundaries", "vii. A new vision for urban space", "viii. Bus rapid transit in the developing world", "ix. Integrating multiple transport modes"], correctAnswer: "vii", explanation: "Paragraph H discusses reclaiming street space and the 15-minute city concept." },
        { number: 18, type: "summary_completion", text: "Horse-drawn omnibuses were first introduced in ________ in the 1820s.", correctAnswer: "Paris", explanation: "The passage states omnibuses were introduced 'in Paris during the 1820s.'" },
        { number: 19, type: "summary_completion", text: "The first commercial electric streetcar system operated in Richmond, ________.", correctAnswer: "Virginia", explanation: "The passage says 'Richmond, Virginia, operating the first successful commercial electric streetcar system.'" },
        { number: 20, type: "summary_completion", text: "Ford's assembly-line methods made cars affordable for ________ families.", correctAnswer: "middle-class", explanation: "The passage states Ford's methods 'made cars affordable for middle-class families.'" },
        { number: 21, type: "summary_completion", text: "The concept of MaaS envisions ________ apps for planning integrated journeys.", correctAnswer: "smartphone", explanation: "The passage says MaaS 'envisions smartphone apps that allow users to plan, book, and pay for trips.'" },
        { number: 22, type: "short_answer", text: "What was the first underground railway in the world?", correctAnswer: "London Underground", explanation: "The passage states 'The London Underground, which opened in 1863, was the world's first underground railway.'" },
        { number: 23, type: "short_answer", text: "Which Brazilian city pioneered bus rapid transit systems?", correctAnswer: "Curitiba", explanation: "The passage says 'Cities such as Curitiba in Brazil pioneered bus rapid transit (BRT) systems.'" },
        { number: 24, type: "short_answer", text: "What does Paris's '15-minute city' concept aim to ensure?", correctAnswer: "essential services are accessible", explanation: "The passage says the concept 'aims to ensure that all essential services are accessible within a short walk or cycle.'" },
        { number: 25, type: "short_answer", text: "In which year was Bogotá's TransMilenio launched?", correctAnswer: "2000", explanation: "The passage states 'Bogotá's TransMilenio, launched in 2000.'" },
        { number: 26, type: "short_answer", text: "What problem did horse-drawn transport create through animal waste?", correctAnswer: "manure accumulation", explanation: "The passage mentions 'manure accumulation' as a significant problem." }
      ]
    },
    {
      title: "Renewable Energy and Economics",
      text: `A. The transition from fossil fuels to renewable energy sources has become one of the defining economic challenges and opportunities of the twenty-first century. While environmental arguments for clean energy are well established, the economic dimensions of this transition — its costs, benefits, disruptions, and distributional effects — are complex and often contentious. Understanding the interplay between renewable energy and economics is critical for policymakers, businesses, and communities navigating this transformation.

B. The most dramatic economic story in renewable energy has been the plummeting cost of solar photovoltaic (PV) technology. Between 2010 and 2023, the levelised cost of electricity from utility-scale solar fell by approximately 89 per cent. This decline was driven by manufacturing scale, technological improvements in cell efficiency, and fierce competition among producers — primarily in China, which now manufactures over 80 per cent of the world's solar panels. Wind energy has followed a similar trajectory, with onshore wind costs dropping by around 70 per cent over the same period.

C. These cost reductions have made renewables competitive with — and often cheaper than — new fossil fuel generation in most markets. The International Renewable Energy Agency (IRENA) reported that in 2022, 86 per cent of newly commissioned renewable capacity had lower costs than new fossil fuel plants. This economic competitiveness has attracted enormous investment: global renewable energy investment exceeded $500 billion annually by 2023, surpassing fossil fuel investment for the first time.

D. However, the economics of renewable energy extend beyond generation costs. Integrating variable sources like solar and wind into electricity grids requires substantial investment in transmission infrastructure, energy storage, and grid management systems. Battery storage costs have fallen dramatically — lithium-ion battery prices dropped by 97 per cent between 1991 and 2023 — but deploying storage at the scale needed to balance intermittent generation remains expensive. Grid operators must also invest in sophisticated forecasting and demand-response technologies to maintain system reliability.

E. The employment effects of the energy transition are significant and uneven. The renewable energy sector employed approximately 13.7 million people worldwide in 2022, according to IRENA. Solar PV was the largest employer, followed by bioenergy and hydropower. Many of these jobs are in manufacturing, installation, and maintenance — activities that can be distributed across regions. Yet the transition also threatens livelihoods in fossil fuel industries. Coal mining communities in Appalachia, oil workers in the North Sea, and gas extraction workers in Russia face economic dislocation as demand for their products declines.

F. Governments have responded with various policy instruments to manage this transition. Feed-in tariffs, which guarantee renewable generators a fixed price for their electricity, were instrumental in driving early adoption in Germany and Spain. Renewable portfolio standards require utilities to source a minimum percentage of their power from clean sources. Carbon pricing mechanisms — including emissions trading systems and carbon taxes — aim to internalise the environmental costs of fossil fuels, making renewables more competitive by comparison.

G. The geopolitical implications of the energy transition are equally profound. Countries rich in fossil fuels — Saudi Arabia, Russia, Nigeria — face the prospect of declining export revenues as global demand shifts. Conversely, nations with abundant renewable resources or manufacturing capacity stand to benefit. China's dominance in solar panel and battery production has given it significant strategic leverage. The European Union's push for energy independence, accelerated by the conflict in Ukraine, has further intensified investment in domestic renewable capacity.

H. Critics of rapid renewable deployment raise legitimate concerns. The mining of lithium, cobalt, and rare earth elements essential for batteries and wind turbines creates its own environmental and social problems, including habitat destruction and exploitative labour practices in some producing countries. The visual impact of wind farms and the land requirements of solar installations provoke opposition in affected communities. Moreover, the intermittency of solar and wind generation means that backup capacity — often gas-fired — must be maintained, adding to system costs.

I. Despite these challenges, the economic momentum behind renewable energy appears irreversible. The combination of falling costs, climate policy commitments, and growing consumer demand has created a self-reinforcing cycle of investment and innovation. Energy economists increasingly view the transition not as a burden but as an industrial opportunity comparable to the digital revolution — one that will reshape labour markets, trade patterns, and geopolitical alignments for decades to come.`,
      questions: [
        { number: 27, type: "matching_information", text: "A discussion of the negative environmental impacts of materials used in renewable technology", options: ["A", "B", "C", "D", "E", "F", "G", "H", "I"], correctAnswer: "H", explanation: "Paragraph H discusses mining of lithium, cobalt, and rare earth elements and associated environmental problems." },
        { number: 28, type: "matching_information", text: "Statistics on global employment in the renewable energy sector", options: ["A", "B", "C", "D", "E", "F", "G", "H", "I"], correctAnswer: "E", explanation: "Paragraph E provides employment statistics — 13.7 million people in 2022." },
        { number: 29, type: "matching_information", text: "A comparison of renewable energy investment with fossil fuel investment", options: ["A", "B", "C", "D", "E", "F", "G", "H", "I"], correctAnswer: "C", explanation: "Paragraph C states renewable investment exceeded $500 billion, surpassing fossil fuel investment." },
        { number: 30, type: "matching_information", text: "The influence of a European conflict on energy policy", options: ["A", "B", "C", "D", "E", "F", "G", "H", "I"], correctAnswer: "G", explanation: "Paragraph G mentions the conflict in Ukraine accelerating EU investment in renewables." },
        { number: 31, type: "flow_chart_completion", text: "Solar PV costs fell by approximately ________ per cent between 2010 and 2023.", correctAnswer: "89", explanation: "The passage states costs fell 'by approximately 89 per cent.'" },
        { number: 32, type: "flow_chart_completion", text: "Cost reductions were driven by manufacturing scale, cell efficiency improvements, and ________ among producers.", correctAnswer: "competition", explanation: "The passage mentions 'fierce competition among producers.'" },
        { number: 33, type: "flow_chart_completion", text: "Lithium-ion battery prices dropped by ________ per cent between 1991 and 2023.", correctAnswer: "97", explanation: "The passage states battery prices 'dropped by 97 per cent.'" },
        { number: 34, type: "flow_chart_completion", text: "Feed-in tariffs were instrumental in driving early adoption in Germany and ________.", correctAnswer: "Spain", explanation: "The passage says feed-in tariffs drove adoption 'in Germany and Spain.'" },
        { number: 35, type: "multiple_choice", text: "Which country manufactures over 80% of the world's solar panels?", options: ["A. Germany", "B. United States", "C. China", "D. Japan"], correctAnswer: "C", explanation: "The passage states China 'now manufactures over 80 per cent of the world's solar panels.'" },
        { number: 36, type: "multiple_choice", text: "According to IRENA, what percentage of new renewable capacity in 2022 was cheaper than fossil fuels?", options: ["A. 70 per cent", "B. 80 per cent", "C. 86 per cent", "D. 89 per cent"], correctAnswer: "C", explanation: "The passage says '86 per cent of newly commissioned renewable capacity had lower costs.'" },
        { number: 37, type: "multiple_choice", text: "Which was the largest employer in the renewable energy sector?", options: ["A. Wind energy", "B. Hydropower", "C. Bioenergy", "D. Solar PV"], correctAnswer: "D", explanation: "The passage states 'Solar PV was the largest employer.'" },
        { number: 38, type: "multiple_choice", text: "Energy economists increasingly compare the energy transition to", options: ["A. the agricultural revolution", "B. the digital revolution", "C. the industrial revolution of the 18th century", "D. the space race"], correctAnswer: "B", explanation: "The passage says economists view it as 'an industrial opportunity comparable to the digital revolution.'" },
        { number: 39, type: "sentence_completion", text: "Carbon pricing mechanisms aim to ________ the environmental costs of fossil fuels.", correctAnswer: "internalise", explanation: "The passage says carbon pricing aims 'to internalise the environmental costs of fossil fuels.'" },
        { number: 40, type: "sentence_completion", text: "The intermittency of solar and wind means that ________ capacity must be maintained.", correctAnswer: "backup", explanation: "The passage states 'backup capacity — often gas-fired — must be maintained.'" }
      ]
    }
  ]
};
