import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_32: ReadingTest = {
  id: 32,
  passages: [
    {
      title: "History of Exploration",
      text: `Human exploration — the deliberate journey into the unknown — has shaped civilisations, redrawn maps, and forged connections between distant peoples for thousands of years. From ancient maritime expeditions along unfamiliar coastlines to the modern conquest of space, the impulse to explore has been driven by a complex mixture of curiosity, ambition, economic interest, and geopolitical rivalry.

Among the earliest recorded explorers were the Phoenicians, seafaring traders based in present-day Lebanon who established commercial networks across the Mediterranean by 1000 BCE. Phoenician sailors are believed to have circumnavigated Africa around 600 BCE under the sponsorship of the Egyptian pharaoh Necho II — a voyage of approximately two years that predated European attempts by two millennia. Greek explorers, including Pytheas of Massalia, ventured into the Atlantic in the fourth century BCE, reaching Britain and possibly Iceland, and providing the first descriptions of Arctic phenomena such as the midnight sun.

The Viking Age (c. 793–1066 CE) produced some of history's most remarkable feats of exploration. Norse sailors, navigating by sun, stars, and coastal landmarks in sturdy longships, colonised Iceland, established settlements in Greenland, and reached North America around 1000 CE — nearly five centuries before Christopher Columbus. The archaeological site at L'Anse aux Meadows in Newfoundland, Canada, provides definitive evidence of Norse presence in the Americas.

The European Age of Discovery, spanning the fifteenth to seventeenth centuries, transformed global geography and commerce. Portuguese navigators, supported by Prince Henry the Navigator, systematically explored the West African coast, eventually reaching India when Vasco da Gama completed his epochal voyage in 1498. Christopher Columbus's transatlantic crossing in 1492, undertaken in search of a western route to Asia, instead brought Europeans into contact with the Americas. Ferdinand Magellan's expedition (1519–1522) completed the first circumnavigation of the globe, though Magellan himself was killed in the Philippines and it was his lieutenant, Juan Sebastián Elcano, who brought the surviving crew home.

These voyages had profound and often devastating consequences for indigenous peoples. European colonisation brought diseases — smallpox, measles, influenza — to populations with no prior immunity, causing demographic catastrophes that killed an estimated ninety per cent of the indigenous population in parts of the Americas. The exploitation of resources and peoples, including the transatlantic slave trade, left legacies of suffering that persist to the present day.

The nineteenth century shifted the focus of exploration toward the Earth's remaining unmapped regions: the interiors of Africa, the polar ice caps, and the depths of the oceans. David Livingstone and Henry Morton Stanley explored the African interior, mapping river systems and lakes. The race to reach the poles captivated public imagination; Roald Amundsen's Norwegian expedition reached the South Pole in December 1911, narrowly preceding the ill-fated British expedition led by Robert Falcon Scott.

The twentieth century extended human exploration beyond the planet itself. The Soviet Union's launch of Sputnik in 1957 inaugurated the Space Age, followed by Yuri Gagarin's orbit of the Earth in 1961. The Apollo 11 mission in 1969, which landed Neil Armstrong and Buzz Aldrin on the Moon, remains perhaps the single most iconic achievement in the history of exploration. Unmanned probes have since visited every planet in the solar system, while the Hubble and James Webb Space Telescopes have peered billions of light-years into the cosmos.

Today, exploration continues in domains ranging from the deep ocean to outer space. Private companies such as SpaceX and Blue Origin are developing reusable rockets and planning missions to Mars, while deep-sea submersibles are revealing ecosystems in abyssal trenches that were previously unknown to science. The human drive to explore — to discover what lies beyond the next horizon — shows no sign of diminishing.`,
      questions: [
        { number: 1, type: "true_false_not_given", text: "The Phoenicians circumnavigated Africa before any European explorer.", correctAnswer: "TRUE", explanation: "The passage says their voyage 'predated European attempts by two millennia.'" },
        { number: 2, type: "true_false_not_given", text: "Pytheas of Massalia reached North America.", correctAnswer: "FALSE", explanation: "The passage says Pytheas 'reached Britain and possibly Iceland' — not North America." },
        { number: 3, type: "true_false_not_given", text: "Norse sailors used magnetic compasses for navigation.", correctAnswer: "NOT GIVEN", explanation: "The passage says they navigated 'by sun, stars, and coastal landmarks' but does not mention compasses." },
        { number: 4, type: "true_false_not_given", text: "Columbus intended to find a western route to Asia.", correctAnswer: "TRUE", explanation: "The passage says his crossing was 'undertaken in search of a western route to Asia.'" },
        { number: 5, type: "true_false_not_given", text: "Magellan completed the first circumnavigation of the globe.", correctAnswer: "FALSE", explanation: "The passage says 'Magellan himself was killed' and Elcano completed the voyage." },
        { number: 6, type: "true_false_not_given", text: "European diseases killed approximately ninety per cent of indigenous populations in parts of the Americas.", correctAnswer: "TRUE", explanation: "The passage states exactly this." },
        { number: 7, type: "true_false_not_given", text: "Amundsen reached the South Pole in 1911.", correctAnswer: "TRUE", explanation: "The passage states 'Amundsen's Norwegian expedition reached the South Pole in December 1911.'" },
        { number: 8, type: "sentence_completion", text: "The archaeological site at L'Anse aux Meadows is located in __(8)__, Canada.", correctAnswer: "Newfoundland", explanation: "The passage names 'Newfoundland, Canada.'" },
        { number: 9, type: "sentence_completion", text: "Vasco da Gama reached __(9)__ in 1498.", correctAnswer: "India", explanation: "The passage says 'reaching India when Vasco da Gama completed his epochal voyage in 1498.'" },
        { number: 10, type: "sentence_completion", text: "Magellan's lieutenant, Juan Sebastián __(10)__, brought the surviving crew home.", correctAnswer: "Elcano", explanation: "The passage names 'Juan Sebastián Elcano.'" },
        { number: 11, type: "sentence_completion", text: "The Soviet Union launched __(11)__ in 1957, inaugurating the Space Age.", correctAnswer: "Sputnik", explanation: "The passage names 'Sputnik.'" },
        { number: 12, type: "sentence_completion", text: "Yuri __(12)__ was the first human to orbit the Earth.", correctAnswer: "Gagarin", explanation: "The passage names 'Yuri Gagarin.'" },
        { number: 13, type: "sentence_completion", text: "Neil Armstrong and Buzz __(13)__ landed on the Moon during the Apollo 11 mission.", correctAnswer: "Aldrin", explanation: "The passage names 'Buzz Aldrin.'" },
      ],
    },
    {
      title: "Urban Transport Systems",
      text: `A. Urban transportation systems are the circulatory networks of modern cities, moving millions of people daily between homes, workplaces, schools, and commercial centres. The design and efficiency of these systems profoundly influence urban form, economic productivity, social equity, and environmental sustainability. As cities worldwide contend with growing populations, worsening congestion, and the imperative to reduce carbon emissions, the transformation of urban transport has become one of the defining challenges of the twenty-first century.

B. The private automobile, which dominated urban transport planning throughout the second half of the twentieth century, has generated enormous costs alongside its undeniable convenience. Traffic congestion costs the global economy an estimated $1 trillion annually in lost productivity, wasted fuel, and delayed freight movement. Road transport accounts for approximately fifteen per cent of global CO₂ emissions, while air pollution from vehicle exhaust contributes to an estimated 4.2 million premature deaths worldwide each year. The spatial demands of car-oriented development — wide roads, expansive parking facilities, suburban sprawl — have consumed vast areas of land and created urban environments hostile to pedestrians and cyclists.

C. Mass transit systems — metro railways, light rail, bus rapid transit (BRT), and commuter rail — offer significantly higher passenger capacity and lower per-capita emissions than private cars. The London Underground, opened in 1863, was the world's first underground railway and carries approximately 1.35 billion passengers annually. Modern metro systems in cities such as Tokyo, Seoul, and Singapore achieve extraordinary efficiency, with trains arriving at intervals of ninety seconds during peak hours. Bus rapid transit, pioneered by Curitiba, Brazil, in 1974, provides metro-like service at a fraction of the construction cost by using dedicated lanes, pre-paid boarding, and level platform access.

D. Active transportation — walking and cycling — is experiencing a renaissance in cities worldwide. Protected cycling infrastructure, exemplified by the comprehensive networks in Copenhagen and Amsterdam, has demonstrated that significant modal shifts from cars to bicycles are achievable when safe, convenient infrastructure is provided. Copenhagen's cycling mode share exceeds forty per cent for commuting trips, reducing congestion, emissions, and healthcare costs simultaneously. Bike-sharing systems, which numbered over 1,600 worldwide by 2020, have further facilitated urban cycling by providing convenient short-term bicycle access.

E. Ride-hailing and shared mobility services have disrupted traditional urban transport models since the emergence of companies like Uber and Lyft in the early 2010s. These platforms use smartphone applications to connect passengers with drivers, offering door-to-door convenience that conventional transit struggles to match. However, research suggests that ride-hailing services may increase rather than decrease total vehicle kilometres travelled, as they attract passengers who would otherwise have used public transit, walked, or cycled. The integration of ride-hailing with public transit — as feeder services for first-and-last-mile connections — offers a more sustainable model.

F. Electric and autonomous vehicles promise further disruption. The electrification of bus fleets is advancing rapidly; Shenzhen, China, became the first major city to operate an entirely electric bus fleet in 2017, with over 16,000 battery-electric buses replacing diesel vehicles. Autonomous vehicle technology, while not yet mature enough for widespread deployment, could eventually transform urban transport by improving safety, reducing labour costs, and enabling new service models such as autonomous shared shuttles operating on flexible routes.

G. Urban freight logistics, often overlooked in transport planning, generate significant congestion and emissions. E-commerce growth has dramatically increased urban delivery volumes, with delivery vans now accounting for a growing share of urban traffic. Solutions under development include cargo bikes for last-mile deliveries in dense urban cores, consolidation centres on city peripheries, and delivery time-window restrictions. Drone delivery, though still experimental in most contexts, could reduce road-based freight traffic in certain applications.

H. Integrated transport planning that coordinates multiple modes — rail, bus, cycling, walking, and shared services — into a seamless network offers the most promising path to sustainable urban mobility. Mobility-as-a-Service (MaaS) platforms, which allow users to plan, book, and pay for multimodal journeys through a single application, are being piloted in cities including Helsinki, Vienna, and Singapore. The goal is a transport system in which the private car becomes one option among many rather than the default choice, enabling cities that are more liveable, equitable, and environmentally responsible.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Section A", options: ["I. The hidden costs of car-dependent cities", "II. Transport as the lifeblood of urban life", "III. High-capacity public transit options", "IV. The return of human-powered mobility", "V. App-based transport and its mixed effects", "VI. Electrification and driverless technology", "VII. Moving goods efficiently within cities", "VIII. Connecting all modes into one system"], correctAnswer: "II", explanation: "Section A introduces urban transport as essential to modern cities." },
        { number: 15, type: "matching_headings", text: "Section B", options: ["I. The hidden costs of car-dependent cities", "II. Transport as the lifeblood of urban life", "III. High-capacity public transit options", "IV. The return of human-powered mobility", "V. App-based transport and its mixed effects", "VI. Electrification and driverless technology", "VII. Moving goods efficiently within cities", "VIII. Connecting all modes into one system"], correctAnswer: "I", explanation: "Section B discusses the costs of automobile dominance." },
        { number: 16, type: "matching_headings", text: "Section C", options: ["I. The hidden costs of car-dependent cities", "II. Transport as the lifeblood of urban life", "III. High-capacity public transit options", "IV. The return of human-powered mobility", "V. App-based transport and its mixed effects", "VI. Electrification and driverless technology", "VII. Moving goods efficiently within cities", "VIII. Connecting all modes into one system"], correctAnswer: "III", explanation: "Section C discusses metro, BRT, and commuter rail systems." },
        { number: 17, type: "matching_headings", text: "Section D", options: ["I. The hidden costs of car-dependent cities", "II. Transport as the lifeblood of urban life", "III. High-capacity public transit options", "IV. The return of human-powered mobility", "V. App-based transport and its mixed effects", "VI. Electrification and driverless technology", "VII. Moving goods efficiently within cities", "VIII. Connecting all modes into one system"], correctAnswer: "IV", explanation: "Section D discusses walking and cycling renaissance." },
        { number: 18, type: "matching_headings", text: "Section E", options: ["I. The hidden costs of car-dependent cities", "II. Transport as the lifeblood of urban life", "III. High-capacity public transit options", "IV. The return of human-powered mobility", "V. App-based transport and its mixed effects", "VI. Electrification and driverless technology", "VII. Moving goods efficiently within cities", "VIII. Connecting all modes into one system"], correctAnswer: "V", explanation: "Section E discusses ride-hailing services." },
        { number: 19, type: "matching_headings", text: "Section F", options: ["I. The hidden costs of car-dependent cities", "II. Transport as the lifeblood of urban life", "III. High-capacity public transit options", "IV. The return of human-powered mobility", "V. App-based transport and its mixed effects", "VI. Electrification and driverless technology", "VII. Moving goods efficiently within cities", "VIII. Connecting all modes into one system"], correctAnswer: "VI", explanation: "Section F discusses electric buses and autonomous vehicles." },
        { number: 20, type: "summary_completion", text: "Traffic congestion costs the global economy an estimated $__(20)__ trillion annually.", correctAnswer: "1", explanation: "The passage states '$1 trillion annually.'" },
        { number: 21, type: "summary_completion", text: "Road transport accounts for approximately __(21)__ per cent of global CO₂ emissions.", correctAnswer: "fifteen", explanation: "The passage states 'approximately fifteen per cent.'" },
        { number: 22, type: "summary_completion", text: "The London Underground carries approximately __(22)__ billion passengers annually.", correctAnswer: "1.35", explanation: "The passage states 'approximately 1.35 billion passengers annually.'" },
        { number: 23, type: "summary_completion", text: "Bus rapid transit was pioneered by __(23)__, Brazil, in 1974.", correctAnswer: "Curitiba", explanation: "The passage states 'Curitiba, Brazil, in 1974.'" },
        { number: 24, type: "summary_completion", text: "Copenhagen's cycling mode share exceeds __(24)__ per cent for commuting trips.", correctAnswer: "forty", explanation: "The passage states 'exceeds forty per cent.'" },
        { number: 25, type: "summary_completion", text: "Shenzhen operates over __(25)__ battery-electric buses.", correctAnswer: "16,000", explanation: "The passage states 'over 16,000 battery-electric buses.'" },
        { number: 26, type: "summary_completion", text: "Air pollution from vehicles contributes to approximately __(26)__ million premature deaths annually.", correctAnswer: "4.2", explanation: "The passage states '4.2 million premature deaths.'" },
      ],
    },
    {
      title: "3D Printing in Industry",
      text: `Three-dimensional printing, also known as additive manufacturing, has evolved from a rapid prototyping tool into a transformative production technology with applications spanning aerospace, healthcare, automotive, construction, and consumer goods. By building objects layer by layer from digital designs, 3D printing offers capabilities that are fundamentally impossible with traditional subtractive or formative manufacturing methods.

A. The origins of 3D printing date to the 1980s, when Charles Hull invented stereolithography (SLA) — a process that uses an ultraviolet laser to cure liquid photopolymer resin into solid shapes, one thin layer at a time. Hull patented the technology in 1986 and founded the company 3D Systems to commercialise it. Other additive manufacturing technologies followed: selective laser sintering (SLS), which fuses powdered materials using a laser; fused deposition modelling (FDM), which extrudes heated thermoplastic filament; and electron beam melting (EBM), which uses an electron beam to fuse metal powder in a vacuum.

B. The aerospace industry was among the first to adopt 3D printing for production applications, driven by the technology's ability to produce lightweight, geometrically complex components that would be impossible or prohibitively expensive to manufacture conventionally. GE Aviation's LEAP engine fuel nozzle, introduced in 2015, consolidated twenty separate parts into a single 3D-printed component, reducing weight by twenty-five per cent and improving durability fivefold. Boeing, Airbus, and SpaceX all use 3D-printed components in their aircraft and rockets, with SpaceX's Raptor engine containing over one hundred additively manufactured parts.

C. Medical applications of 3D printing have expanded dramatically. Patient-specific surgical guides, printed from CT or MRI scan data, enable surgeons to plan and rehearse complex procedures with unprecedented precision. Custom prosthetics and orthotics can be produced at a fraction of the cost and time of traditional methods, transforming access to these devices in developing countries. Dental aligners, hearing aids, and cranial implants are now routinely manufactured using 3D printing. Bioprinting — the deposition of living cells in three-dimensional structures — represents the frontier of medical 3D printing, with researchers successfully printing functional tissue constructs including skin grafts, cartilage, and blood vessel networks.

D. The construction industry is exploring 3D printing as a means of addressing housing shortages and reducing construction costs. Large-scale concrete printers can fabricate the structural walls of a house in as little as twenty-four hours, using significantly less material and labour than conventional construction. ICON, a Texas-based company, has printed homes in both the United States and Mexico, including a community of fifty 3D-printed homes in Austin. Dubai has established a target of having twenty-five per cent of all new buildings constructed using 3D printing technology by 2030.

E. The automotive sector uses 3D printing extensively for prototyping, tooling, and increasingly for end-use parts. BMW produces over 300,000 3D-printed parts annually, including components for its i8 Roadster and customised interior elements. Local Motors demonstrated the potential for larger-scale automotive printing with the Strati, a car whose body was 3D-printed from carbon-fibre-reinforced thermoplastic in approximately forty-four hours. Formula One teams rely on 3D printing to produce aerodynamic testing components rapidly, enabling faster development cycles.

F. Supply chain transformation represents one of the most strategically significant implications of 3D printing. Traditional manufacturing requires large factories, extensive tooling, and global supply chains that ship components across continents for assembly. Additive manufacturing enables distributed production — parts can be printed on demand, close to the point of use, from digital files transmitted electronically. This capability reduces inventory costs, shortens lead times, and enhances supply chain resilience. The U.S. military has deployed 3D printers on aircraft carriers and at forward operating bases to produce replacement parts in the field, reducing dependence on lengthy logistics chains.

G. Despite its advantages, 3D printing faces limitations. Build speeds remain slower than mass production methods for high-volume applications. Material costs are often higher than those for conventional manufacturing inputs. Quality assurance and certification of 3D-printed parts, particularly for safety-critical applications in aerospace and medicine, require rigorous testing protocols that are still being standardised. The resolution and surface finish of printed parts may necessitate post-processing steps that add time and cost.

H. The convergence of 3D printing with artificial intelligence, robotics, and advanced materials promises to accelerate the technology's capabilities. AI-driven generative design algorithms create optimised geometries that maximise strength while minimising material usage — shapes that only additive manufacturing can produce. Multi-material printing systems capable of depositing different materials within a single build are expanding the functional complexity of printed objects. As these technologies mature, 3D printing is likely to shift from a complement to traditional manufacturing into a primary production method for an increasing range of applications.`,
      questions: [
        { number: 27, type: "matching_information", text: "The use of 3D printing to produce housing at reduced cost and time", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "D", explanation: "Section D discusses 3D-printed construction and housing." },
        { number: 28, type: "matching_information", text: "The military use of 3D printers in remote locations", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "F", explanation: "Section F mentions military deployment of 3D printers on carriers and bases." },
        { number: 29, type: "matching_information", text: "Current limitations and quality concerns of 3D printing", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "G", explanation: "Section G discusses speed, cost, and certification limitations." },
        { number: 30, type: "matching_information", text: "A specific aerospace component that consolidated twenty parts into one", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "B", explanation: "Section B discusses GE Aviation's LEAP engine fuel nozzle." },
        { number: 31, type: "matching_information", text: "The printing of living cells in three-dimensional structures", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "C", explanation: "Section C discusses bioprinting." },
        { number: 32, type: "matching_information", text: "The invention of the first 3D printing technology", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "A", explanation: "Section A discusses Charles Hull's invention of stereolithography." },
        { number: 33, type: "flow_chart_completion", text: "Charles Hull patented stereolithography in __(33)__.", correctAnswer: "1986", explanation: "The passage states 'Hull patented the technology in 1986.'" },
        { number: 34, type: "flow_chart_completion", text: "GE Aviation's fuel nozzle reduced weight by __(34)__ per cent.", correctAnswer: "twenty-five", explanation: "The passage states 'reducing weight by twenty-five per cent.'" },
        { number: 35, type: "flow_chart_completion", text: "ICON has printed a community of __(35)__ homes in Austin.", correctAnswer: "fifty", explanation: "The passage states 'fifty 3D-printed homes in Austin.'" },
        { number: 36, type: "flow_chart_completion", text: "BMW produces over __(36)__ 3D-printed parts annually.", correctAnswer: "300,000", explanation: "The passage states 'over 300,000 3D-printed parts annually.'" },
        { number: 37, type: "flow_chart_completion", text: "Dubai aims to have __(37)__ per cent of new buildings 3D-printed by 2030.", correctAnswer: "twenty-five", explanation: "The passage states 'twenty-five per cent.'" },
        { number: 38, type: "flow_chart_completion", text: "The Strati car body was 3D-printed in approximately __(38)__ hours.", correctAnswer: "forty-four", explanation: "The passage states 'approximately forty-four hours.'" },
        { number: 39, type: "flow_chart_completion", text: "SpaceX's Raptor engine contains over __(39)__ additively manufactured parts.", correctAnswer: "one hundred", explanation: "The passage states 'over one hundred additively manufactured parts.'" },
        { number: 40, type: "flow_chart_completion", text: "Large-scale concrete printers can fabricate house walls in as little as __(40)__ hours.", correctAnswer: "twenty-four", explanation: "The passage states 'as little as twenty-four hours.'" },
      ],
    },
  ],
};
