import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_30: ReadingTest = {
  id: 30,
  passages: [
    {
      title: "The History of Music",
      text: `Music is one of the most ancient and universal forms of human expression, predating written language and present in every known culture. Archaeological evidence suggests that early humans were making music at least forty thousand years ago, as demonstrated by the discovery of bone flutes in caves in present-day Germany. From these primitive beginnings, music has evolved through countless traditions and innovations into the extraordinarily diverse art form we know today.

The earliest musical traditions were almost certainly vocal, as the human voice requires no manufactured instrument. Rhythmic chanting and singing likely accompanied religious ceremonies, communal gatherings, and daily labour in prehistoric societies. Percussion instruments — drums fashioned from hollowed logs and animal skins — were among the first manufactured instruments, followed by wind instruments carved from bone, reed, and wood. Stringed instruments appeared somewhat later, with lyres and harps depicted in Sumerian art dating to approximately 3000 BCE.

Ancient civilisations developed sophisticated musical systems. The Greeks, who regarded music as both an art and a branch of mathematics, identified the mathematical relationships between musical intervals — an insight attributed to Pythagoras, who reportedly discovered that harmonious sounds corresponded to simple numerical ratios. Greek modes — scales with distinctive patterns of intervals — influenced Western music theory for millennia. In China, the Imperial court standardised a system of twelve pitch pipes as early as the Zhou Dynasty (c. 1046–256 BCE), establishing a framework that remains foundational in Chinese music.

The medieval period in Europe saw the development of musical notation, one of the most consequential innovations in the history of music. Before notation, music was transmitted exclusively through oral tradition, limiting its complexity and geographic reach. Guido d'Arezzo, an eleventh-century Italian monk, developed the staff notation system and the sol-fa syllables (do, re, mi, fa, sol, la) that enabled musicians to read and reproduce music they had never heard. This breakthrough made possible the preservation and dissemination of increasingly complex compositions, from Gregorian chant to elaborate polyphonic works.

The Renaissance and Baroque periods witnessed an explosion of musical creativity. Polyphonic composition — the art of combining multiple independent melodic lines — reached its apex in the works of composers such as Palestrina and Bach. The development of new instruments, including the violin family and keyboard instruments such as the harpsichord and organ, expanded the tonal palette available to composers. Opera, which combined music, drama, poetry, and visual spectacle, emerged in late sixteenth-century Italy and rapidly spread across Europe.

The Classical and Romantic periods of the eighteenth and nineteenth centuries brought fundamental changes in musical structure, expression, and social context. Composers such as Mozart, Beethoven, and Brahms developed sophisticated formal structures — the sonata, the symphony, the concerto — that balanced intellectual rigour with emotional depth. Beethoven, in particular, expanded the expressive range of orchestral music, bridging the Classical and Romantic eras. The Romantic period saw music become increasingly programmatic, seeking to evoke landscapes, narratives, and emotional states with unprecedented intensity.

The twentieth century shattered established conventions. Composers such as Stravinsky, Schoenberg, and John Cage challenged tonal harmony, rhythmic regularity, and the very definition of music itself. Simultaneously, popular music genres — jazz, blues, rock and roll, and their descendants — emerged from African American traditions and came to dominate global musical culture. The invention of recording technology by Thomas Edison in 1877 and the subsequent development of radio, television, and digital media transformed music from a live, ephemeral experience into a commodity that could be mass-produced, distributed, and consumed anywhere in the world.

The digital revolution of the late twentieth and early twenty-first centuries has further democratised music creation and distribution. Digital audio workstations enable individuals to produce professional-quality recordings in their bedrooms, while streaming platforms such as Spotify and Apple Music provide instant access to catalogues of over one hundred million songs. Artificial intelligence is now being used to compose music, analyse listener preferences, and generate personalised playlists. Whether these developments enrich or impoverish the art of music remains a subject of vigorous debate, but the centrality of music to human experience seems assured.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "What is the earliest archaeological evidence of music-making mentioned in the passage?", options: ["A Cave paintings depicting musicians", "B Bone flutes found in Germany", "C Sumerian lyres from 3000 BCE", "D Chinese pitch pipes from the Zhou Dynasty"], correctAnswer: "B", explanation: "The passage mentions 'bone flutes in caves in present-day Germany' dating to forty thousand years ago." },
        { number: 2, type: "multiple_choice", text: "Who is credited with developing the staff notation system?", options: ["A Pythagoras", "B Thomas Edison", "C Guido d'Arezzo", "D Johann Sebastian Bach"], correctAnswer: "C", explanation: "The passage states 'Guido d'Arezzo, an eleventh-century Italian monk, developed the staff notation system.'" },
        { number: 3, type: "multiple_choice", text: "According to the passage, what made musical notation so important?", options: ["A It allowed music to be sold commercially.", "B It enabled the preservation and spread of complex compositions.", "C It replaced the need for musical instruments.", "D It standardised all global musical traditions."], correctAnswer: "B", explanation: "The passage says notation 'made possible the preservation and dissemination of increasingly complex compositions.'" },
        { number: 4, type: "multiple_choice", text: "What impact did recording technology have on music?", options: ["A It ended live musical performance.", "B It transformed music into a mass-produced commodity.", "C It improved the quality of orchestral performances.", "D It reduced the diversity of musical genres."], correctAnswer: "B", explanation: "The passage says recording transformed music 'into a commodity that could be mass-produced, distributed, and consumed anywhere.'" },
        { number: 5, type: "sentence_completion", text: "Early humans were making music at least __(5)__ thousand years ago.", correctAnswer: "forty", explanation: "The passage states 'at least forty thousand years ago.'" },
        { number: 6, type: "sentence_completion", text: "Pythagoras discovered that harmonious sounds corresponded to simple numerical __(6)__.", correctAnswer: "ratios", explanation: "The passage mentions 'simple numerical ratios.'" },
        { number: 7, type: "sentence_completion", text: "Opera emerged in late sixteenth-century __(7)__ and spread across Europe.", correctAnswer: "Italy", explanation: "The passage says opera 'emerged in late sixteenth-century Italy.'" },
        { number: 8, type: "sentence_completion", text: "Guido d'Arezzo developed the sol-fa syllables: do, re, mi, fa, sol, and __(8)__.", correctAnswer: "la", explanation: "The passage lists 'do, re, mi, fa, sol, la.'" },
        { number: 9, type: "sentence_completion", text: "Thomas Edison invented recording technology in __(9)__.", correctAnswer: "1877", explanation: "The passage states 'the invention of recording technology by Thomas Edison in 1877.'" },
        { number: 10, type: "sentence_completion", text: "Streaming platforms now provide access to over one hundred __(10)__ songs.", correctAnswer: "million", explanation: "The passage says 'catalogues of over one hundred million songs.'" },
        { number: 11, type: "sentence_completion", text: "Lyres and harps are depicted in __(11)__ art from approximately 3000 BCE.", correctAnswer: "Sumerian", explanation: "The passage says 'lyres and harps depicted in Sumerian art.'" },
        { number: 12, type: "sentence_completion", text: "The Chinese Imperial court standardised twelve pitch pipes during the __(12)__ Dynasty.", correctAnswer: "Zhou", explanation: "The passage mentions 'the Zhou Dynasty.'" },
        { number: 13, type: "sentence_completion", text: "Beethoven is noted for bridging the Classical and __(13)__ eras.", correctAnswer: "Romantic", explanation: "The passage says Beethoven 'bridging the Classical and Romantic eras.'" },
      ],
    },
    {
      title: "Plastic Pollution Solutions",
      text: `A. Plastic pollution has become one of the defining environmental crises of the twenty-first century. Since the mass production of synthetic plastics began in the 1950s, humanity has produced an estimated 8.3 billion tonnes of plastic, of which approximately 6.3 billion tonnes have become waste. Only nine per cent of all plastic ever produced has been recycled, twelve per cent has been incinerated, and the remaining seventy-nine per cent has accumulated in landfills or the natural environment — rivers, oceans, soils, and even the atmosphere.

B. The scale of marine plastic pollution is staggering. An estimated eight million tonnes of plastic enter the world's oceans annually, where it fragments into ever-smaller particles but does not biodegrade for centuries. Five enormous gyres of accumulated plastic debris have formed in the world's oceans, the largest being the Great Pacific Garbage Patch, which covers an area roughly three times the size of France. Marine animals ingest plastic or become entangled in it; an estimated one hundred thousand marine mammals and one million seabirds die from plastic-related causes each year.

C. Microplastics — particles smaller than five millimetres — have emerged as a particularly insidious form of pollution. Generated by the breakdown of larger plastic items, the shedding of synthetic textile fibres during laundry, and the wear of vehicle tyres, microplastics have been detected in virtually every environment on Earth, from Arctic sea ice to deep ocean sediments, from mountain air to human bloodstreams. The health implications of human exposure to microplastics remain under investigation, but preliminary research suggests potential risks including inflammation, cellular damage, and the transport of harmful chemical additives into biological tissues.

D. Reducing plastic pollution requires action across the entire lifecycle of plastic products. Upstream solutions focus on reducing the production and consumption of single-use plastics. Over one hundred and twenty countries have implemented some form of ban or levy on single-use plastic bags, and many jurisdictions are extending restrictions to straws, cutlery, food containers, and packaging. Extended Producer Responsibility (EPR) schemes shift the financial and logistical burden of waste management from municipalities to manufacturers, incentivising the design of products that are easier to recycle or reuse.

E. Innovation in materials science offers promising alternatives to conventional petroleum-based plastics. Bioplastics, derived from renewable feedstocks such as corn starch, sugarcane, and cellulose, can match the performance characteristics of traditional plastics for many applications while offering improved end-of-life options. Polylactic acid (PLA), for instance, is compostable under industrial conditions and is already widely used in food packaging and disposable tableware. However, bioplastics are not a panacea: many require specific composting conditions to break down, may compete with food crops for agricultural land, and can contaminate conventional recycling streams if not properly sorted.

F. Advanced recycling technologies are addressing the limitations of traditional mechanical recycling, which can process only certain plastic types and produces progressively lower-quality material with each cycle. Chemical recycling, also known as feedstock recycling, breaks plastic polymers down into their constituent monomers, which can then be repolymerised into virgin-quality plastic. Pyrolysis converts mixed plastic waste into synthetic oils that can serve as fuel or chemical feedstock. While these technologies remain more expensive than mechanical recycling and face questions about energy consumption and scalability, they offer the potential to process plastic waste streams that currently have no viable recycling pathway.

G. Cleanup initiatives, while valuable for addressing existing pollution, cannot solve the problem alone. The Ocean Cleanup project, founded by Dutch inventor Boyan Slat, has developed autonomous systems designed to collect plastic debris from ocean gyres and intercept it in rivers before it reaches the sea. Community-based coastal cleanups engage millions of volunteers worldwide, raising awareness while removing tonnes of waste from beaches and waterways. However, experts emphasise that cleanup efforts must be complemented by fundamental changes in production, consumption, and waste management systems to prevent continued accumulation.

H. A circular economy approach, in which materials are continuously cycled through use, recovery, and regeneration rather than following the linear "take-make-dispose" model, represents the most comprehensive framework for addressing plastic pollution. This vision requires collaboration across industries, governments, and civil society, supported by innovation in product design, business models, and consumer behaviour. While the transition to a circular economy for plastics will be complex and gradual, the urgency of the pollution crisis demands that it begin immediately and accelerate rapidly.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Section A", options: ["I. The extent of ocean contamination", "II. A global waste crisis in numbers", "III. The invisible threat of tiny particles", "IV. Reducing consumption at the source", "V. Plant-based alternatives to conventional plastic", "VI. Breaking down plastic at the molecular level", "VII. Removing existing pollution from the environment", "VIII. A systemic approach to eliminating plastic waste"], correctAnswer: "II", explanation: "Section A provides statistics on global plastic production and waste." },
        { number: 15, type: "matching_headings", text: "Section B", options: ["I. The extent of ocean contamination", "II. A global waste crisis in numbers", "III. The invisible threat of tiny particles", "IV. Reducing consumption at the source", "V. Plant-based alternatives to conventional plastic", "VI. Breaking down plastic at the molecular level", "VII. Removing existing pollution from the environment", "VIII. A systemic approach to eliminating plastic waste"], correctAnswer: "I", explanation: "Section B discusses marine plastic pollution and ocean gyres." },
        { number: 16, type: "matching_headings", text: "Section C", options: ["I. The extent of ocean contamination", "II. A global waste crisis in numbers", "III. The invisible threat of tiny particles", "IV. Reducing consumption at the source", "V. Plant-based alternatives to conventional plastic", "VI. Breaking down plastic at the molecular level", "VII. Removing existing pollution from the environment", "VIII. A systemic approach to eliminating plastic waste"], correctAnswer: "III", explanation: "Section C discusses microplastics." },
        { number: 17, type: "matching_headings", text: "Section D", options: ["I. The extent of ocean contamination", "II. A global waste crisis in numbers", "III. The invisible threat of tiny particles", "IV. Reducing consumption at the source", "V. Plant-based alternatives to conventional plastic", "VI. Breaking down plastic at the molecular level", "VII. Removing existing pollution from the environment", "VIII. A systemic approach to eliminating plastic waste"], correctAnswer: "IV", explanation: "Section D discusses bans, levies, and EPR schemes." },
        { number: 18, type: "matching_headings", text: "Section F", options: ["I. The extent of ocean contamination", "II. A global waste crisis in numbers", "III. The invisible threat of tiny particles", "IV. Reducing consumption at the source", "V. Plant-based alternatives to conventional plastic", "VI. Breaking down plastic at the molecular level", "VII. Removing existing pollution from the environment", "VIII. A systemic approach to eliminating plastic waste"], correctAnswer: "VI", explanation: "Section F discusses chemical recycling and pyrolysis." },
        { number: 19, type: "matching_headings", text: "Section H", options: ["I. The extent of ocean contamination", "II. A global waste crisis in numbers", "III. The invisible threat of tiny particles", "IV. Reducing consumption at the source", "V. Plant-based alternatives to conventional plastic", "VI. Breaking down plastic at the molecular level", "VII. Removing existing pollution from the environment", "VIII. A systemic approach to eliminating plastic waste"], correctAnswer: "VIII", explanation: "Section H discusses the circular economy framework." },
        { number: 20, type: "summary_completion", text: "Only __(20)__ per cent of all plastic ever produced has been recycled.", correctAnswer: "nine", explanation: "The passage states 'Only nine per cent.'" },
        { number: 21, type: "summary_completion", text: "An estimated __(21)__ million tonnes of plastic enter the oceans each year.", correctAnswer: "eight", explanation: "The passage states 'eight million tonnes.'" },
        { number: 22, type: "summary_completion", text: "The Great Pacific Garbage Patch covers an area roughly three times the size of __(22)__.", correctAnswer: "France", explanation: "The passage says 'roughly three times the size of France.'" },
        { number: 23, type: "summary_completion", text: "Microplastics are defined as particles smaller than __(23)__ millimetres.", correctAnswer: "five", explanation: "The passage states 'particles smaller than five millimetres.'" },
        { number: 24, type: "summary_completion", text: "Over __(24)__ countries have implemented bans or levies on single-use plastic bags.", correctAnswer: "one hundred and twenty", explanation: "The passage states 'Over one hundred and twenty countries.'" },
        { number: 25, type: "summary_completion", text: "Polylactic acid is derived from renewable feedstocks and is __(25)__ under industrial conditions.", correctAnswer: "compostable", explanation: "The passage states PLA 'is compostable under industrial conditions.'" },
        { number: 26, type: "summary_completion", text: "The Ocean Cleanup project was founded by Dutch inventor Boyan __(26)__.", correctAnswer: "Slat", explanation: "The passage names 'Dutch inventor Boyan Slat.'" },
      ],
    },
    {
      title: "Renewable Energy Innovations",
      text: `The global transition from fossil fuels to renewable energy sources represents one of the most significant industrial transformations in human history. Driven by the urgent need to mitigate climate change, reduce air pollution, and enhance energy security, investment in renewable energy technologies has surged over the past two decades, fundamentally altering the economics and politics of the global energy system.

A. Solar photovoltaic (PV) technology has experienced the most dramatic cost reductions of any energy technology in history. The price of solar panels has fallen by approximately ninety per cent since 2010, making solar the cheapest source of electricity ever produced in many regions. This cost decline, driven by manufacturing scale, technological improvements, and competitive market dynamics, has spurred explosive growth: global installed solar capacity exceeded one terawatt in 2022 and is projected to triple by 2030. Perovskite solar cells, a next-generation technology currently under intensive development, promise even higher efficiencies and lower manufacturing costs, with the potential for flexible, lightweight panels that can be applied to building surfaces, vehicles, and portable devices.

B. Wind energy has undergone a parallel transformation. Modern wind turbines, with rotor diameters exceeding 150 metres and tower heights approaching 200 metres, capture wind energy with efficiencies undreamt of a generation ago. Offshore wind farms, situated in waters where wind speeds are higher and more consistent, are expanding rapidly. The Hornsea projects off the English coast, among the world's largest offshore wind installations, demonstrate the viability of gigawatt-scale offshore wind generation. Floating wind turbines, anchored to the seabed by cables rather than fixed foundations, are opening up deep-water locations previously inaccessible to offshore wind development.

C. Energy storage is widely recognised as the key enabling technology for a renewable-powered grid. Because solar and wind generation are inherently intermittent — dependent on weather conditions and time of day — effective storage solutions are essential to ensure reliable electricity supply. Lithium-ion batteries dominate the current storage market, with utility-scale battery installations growing rapidly worldwide. However, alternative storage technologies are also advancing. Flow batteries, which store energy in liquid electrolytes, offer advantages for long-duration storage. Compressed air energy storage (CAES) uses excess renewable electricity to compress air in underground caverns, releasing it to drive turbines during periods of high demand. Green hydrogen — produced by using renewable electricity to split water molecules through electrolysis — offers a versatile energy carrier that can be stored, transported, and used in industrial processes, heavy transport, and power generation.

D. The electrification of transportation is accelerating the integration of renewable energy into the broader economy. Electric vehicles charged from renewable grids produce near-zero lifecycle emissions, while vehicle-to-grid technology allows EV batteries to serve as distributed storage resources. Electric buses, trucks, and even short-haul aircraft are under development or already in commercial operation, extending decarbonisation beyond passenger cars.

E. The integration of artificial intelligence and digital technologies is enhancing the efficiency and reliability of renewable energy systems. Machine learning algorithms predict wind and solar output with increasing accuracy, enabling grid operators to balance supply and demand more effectively. Smart grids — electricity networks that use digital communication to detect and respond to local changes in usage and generation — facilitate the integration of distributed renewable resources such as rooftop solar panels and household batteries. Blockchain technology is being explored for peer-to-peer energy trading, allowing prosumers (consumers who also produce energy) to sell surplus solar electricity directly to their neighbours.

F. Despite remarkable progress, significant challenges remain. The intermittency of solar and wind necessitates not only storage but also grid flexibility, including demand response programmes and upgraded transmission infrastructure to move renewable electricity from generation sites to population centres. The supply chains for critical minerals — lithium, cobalt, rare earth elements — are concentrated in a small number of countries, creating geopolitical vulnerabilities. Environmental concerns associated with mining, land use for large-scale solar and wind installations, and the eventual recycling of solar panels and wind turbine blades require careful management.

G. Policy frameworks play a decisive role in accelerating or impeding the renewable energy transition. Feed-in tariffs, renewable portfolio standards, carbon pricing mechanisms, and direct subsidies have all proven effective in stimulating renewable deployment, though their design and implementation vary widely across jurisdictions. The Inflation Reduction Act in the United States, the European Green Deal, and China's aggressive manufacturing and deployment targets collectively signal a global policy consensus that the transition to renewable energy is not merely desirable but economically and strategically imperative.

H. The pace of change in the renewable energy sector continues to exceed even optimistic forecasts. Technologies once considered experimental — floating wind, perovskite solar, green hydrogen — are advancing toward commercial viability more rapidly than mainstream projections anticipated. While the transition will inevitably encounter obstacles, setbacks, and political resistance, the direction of the global energy system is increasingly clear: the age of fossil fuel dominance is drawing to a close, and the era of renewable energy has begun.`,
      questions: [
        { number: 27, type: "matching_information", text: "A discussion of the role of government policies in promoting renewables", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "G", explanation: "Section G discusses various policy frameworks for renewable energy." },
        { number: 28, type: "matching_information", text: "An explanation of how AI improves renewable energy management", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "E", explanation: "Section E discusses AI, machine learning, and smart grids." },
        { number: 29, type: "matching_information", text: "Details about different types of energy storage technologies", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "C", explanation: "Section C discusses lithium-ion batteries, flow batteries, CAES, and green hydrogen." },
        { number: 30, type: "matching_information", text: "A mention of environmental concerns related to renewable energy", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "F", explanation: "Section F discusses mining, land use, and recycling concerns." },
        { number: 31, type: "matching_information", text: "Information about the declining cost of solar energy", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "A", explanation: "Section A discusses the ninety per cent price reduction in solar panels." },
        { number: 32, type: "matching_information", text: "A reference to offshore wind farm projects", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "B", explanation: "Section B mentions the Hornsea projects and floating wind turbines." },
        { number: 33, type: "flow_chart_completion", text: "Solar panel prices have fallen by approximately __(33)__ per cent since 2010.", correctAnswer: "ninety", explanation: "The passage states 'approximately ninety per cent since 2010.'" },
        { number: 34, type: "flow_chart_completion", text: "Global solar capacity exceeded one __(34)__ in 2022.", correctAnswer: "terawatt", explanation: "The passage states 'exceeded one terawatt in 2022.'" },
        { number: 35, type: "flow_chart_completion", text: "Modern wind turbines have rotor diameters exceeding __(35)__ metres.", correctAnswer: "150", explanation: "The passage says 'rotor diameters exceeding 150 metres.'" },
        { number: 36, type: "flow_chart_completion", text: "Green hydrogen is produced by splitting water molecules through __(36)__.", correctAnswer: "electrolysis", explanation: "The passage mentions 'electrolysis.'" },
        { number: 37, type: "flow_chart_completion", text: "Compressed air energy storage uses underground __(37)__ to store compressed air.", correctAnswer: "caverns", explanation: "The passage says 'compress air in underground caverns.'" },
        { number: 38, type: "flow_chart_completion", text: "__(38)__ technology enables peer-to-peer energy trading.", correctAnswer: "Blockchain", explanation: "The passage mentions 'Blockchain technology is being explored for peer-to-peer energy trading.'" },
        { number: 39, type: "flow_chart_completion", text: "Floating wind turbines are anchored to the seabed by __(39)__.", correctAnswer: "cables", explanation: "The passage says 'anchored to the seabed by cables.'" },
        { number: 40, type: "flow_chart_completion", text: "__(40)__ solar cells are a next-generation technology promising higher efficiencies.", correctAnswer: "Perovskite", explanation: "The passage names 'Perovskite solar cells.'" },
      ],
    },
  ],
};
