import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_57: ReadingTest = {
  id: 57,
  passages: [
    {
      title: "The History of Refrigeration",
      text: `The ability to preserve food by keeping it cold is so fundamental to modern life that it is difficult to imagine a world without refrigeration. Yet mechanical refrigeration is a relatively recent invention, dating back less than two hundred years, and its development involved a long chain of scientific discoveries, engineering innovations, and social transformations that reshaped agriculture, commerce, diet, and public health on a global scale.

For thousands of years, the only methods available for cooling and preserving food were natural ones: storing food in caves, cellars, or underground pits where temperatures remained relatively constant; packing it in snow or ice harvested from frozen lakes and rivers during winter; and using evaporative cooling, in which water evaporating from the surface of a porous container draws heat from its contents. The ancient Persians constructed yakhchāls — large, domed ice houses made of thick mud-brick walls — that could store ice harvested in winter for use throughout the hot summer months. The Romans transported snow from mountain peaks to the cities to cool drinks and preserve food for banquets. In the eighteenth and nineteenth centuries, the ice trade became a major commercial enterprise, particularly in the United States, where ice harvested from New England lakes was shipped as far as India and Australia.

The scientific foundations of mechanical refrigeration were laid in the eighteenth century, when scientists began to understand the relationship between pressure, volume, and temperature in gases. In 1748, Scottish physician William Cullen demonstrated the first known artificial refrigeration at the University of Glasgow by creating a partial vacuum over a container of diethyl ether, causing it to boil and absorb heat from the surrounding air — producing a small amount of ice in the process. However, Cullen's experiment had no practical application at the time. The first practical refrigeration machine was built by American inventor Jacob Perkins in 1834, using a closed cycle of vapour compression — the same fundamental principle used in most refrigerators and air conditioners today. Perkins's machine compressed ether gas into a liquid, then allowed it to expand and evaporate, absorbing heat in the process and producing a continuous cooling effect.

The commercialisation of refrigeration proceeded slowly at first. In the 1850s and 1860s, Australian and French engineers developed ice-making machines for the brewing and meat-packing industries. James Harrison, a Scottish-born journalist and engineer working in Australia, built one of the first commercial ice-making machines in 1854 and used refrigeration technology to establish a frozen meat export trade. The introduction of refrigerated railway cars in the United States in the 1870s — pioneered by Gustavus Swift for transporting beef from the Chicago stockyards to eastern cities — revolutionised the American meat industry and fundamentally altered the geography of food production and consumption. Refrigerated ships, first used successfully in the 1880s to transport frozen lamb from New Zealand and Argentina to Britain, opened global markets for perishable agricultural products and transformed the economies of exporting nations.

The domestic refrigerator, which would ultimately have the most profound impact on everyday life, did not become widely available until the 1920s and 1930s. Early household refrigerators used toxic or flammable refrigerants — including ammonia, methyl chloride, and sulphur dioxide — that posed serious safety risks. A series of fatal accidents involving methyl chloride leaks in the 1920s prompted a search for safer alternatives, leading to the development of chlorofluorocarbons (CFCs), marketed under the brand name Freon, by Thomas Midgley Jr. and his team at General Motors in 1930. CFCs were non-toxic, non-flammable, and highly effective refrigerants, and their introduction made domestic refrigerators safe enough for mass adoption. By 1944, approximately 85 percent of American households owned a refrigerator. However, it was not until the 1980s that scientists discovered that CFCs were destroying the Earth's ozone layer, leading to the Montreal Protocol of 1987 — an international agreement to phase out CFC production that is widely regarded as one of the most successful environmental treaties in history.

Modern refrigeration technology continues to evolve. Contemporary refrigerators use hydrofluorocarbons (HFCs) or natural refrigerants such as propane and isobutane, which do not damage the ozone layer but in some cases contribute to greenhouse gas emissions. Research into magnetic refrigeration, thermoelectric cooling, and elastocaloric systems promises to deliver more energy-efficient and environmentally friendly alternatives in the coming decades. The global cold chain — the network of refrigerated production, storage, and distribution facilities that enables fresh food, vaccines, and pharmaceuticals to reach consumers worldwide — now represents a multi-trillion-dollar industry and is considered essential infrastructure for food security and public health in the twenty-first century.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "What were yakhchāls?", options: ["A. Underground rivers used for cooling", "B. Persian domed ice houses made of mud-brick", "C. Roman snow-collecting devices", "D. Early electric cooling systems"], correctAnswer: "B", explanation: "The passage describes yakhchāls as 'large, domed ice houses made of thick mud-brick walls.'" },
        { number: 2, type: "multiple_choice", text: "Who demonstrated the first known artificial refrigeration?", options: ["A. Jacob Perkins", "B. Thomas Midgley Jr.", "C. William Cullen", "D. Gustavus Swift"], correctAnswer: "C", explanation: "The passage says 'William Cullen demonstrated the first known artificial refrigeration at the University of Glasgow.'" },
        { number: 3, type: "multiple_choice", text: "What principle does Jacob Perkins's 1834 machine use?", options: ["A. Evaporative cooling", "B. Magnetic refrigeration", "C. Vapour compression", "D. Thermoelectric cooling"], correctAnswer: "C", explanation: "The passage says Perkins used 'a closed cycle of vapour compression.'" },
        { number: 4, type: "multiple_choice", text: "Why were CFCs eventually phased out?", options: ["A. They were too expensive to produce", "B. They were found to be flammable", "C. They were destroying the ozone layer", "D. They caused refrigerators to malfunction"], correctAnswer: "C", explanation: "The passage says 'scientists discovered that CFCs were destroying the Earth's ozone layer.'" },
        { number: 5, type: "true_false_not_given", text: "Cullen's 1748 experiment had immediate practical applications.", correctAnswer: "FALSE", explanation: "The passage says 'Cullen's experiment had no practical application at the time.'" },
        { number: 6, type: "true_false_not_given", text: "James Harrison was originally from Scotland.", correctAnswer: "TRUE", explanation: "The passage describes him as 'a Scottish-born journalist and engineer.'" },
        { number: 7, type: "true_false_not_given", text: "Refrigerated ships were first used in the 1870s.", correctAnswer: "FALSE", explanation: "The passage says 'Refrigerated ships, first used successfully in the 1880s.'" },
        { number: 8, type: "true_false_not_given", text: "By 1944, approximately 85 percent of American households owned a refrigerator.", correctAnswer: "TRUE", explanation: "The passage states 'By 1944, approximately 85 percent of American households owned a refrigerator.'" },
        { number: 9, type: "true_false_not_given", text: "Thomas Midgley Jr. won a Nobel Prize for his work on CFCs.", correctAnswer: "NOT GIVEN", explanation: "The passage does not mention any Nobel Prize for Midgley." },
        { number: 10, type: "true_false_not_given", text: "Gustavus Swift pioneered refrigerated railway cars for transporting beef.", correctAnswer: "TRUE", explanation: "The passage says refrigerated railway cars were 'pioneered by Gustavus Swift for transporting beef.'" },
        { number: 11, type: "true_false_not_given", text: "The Montreal Protocol was signed in 1989.", correctAnswer: "FALSE", explanation: "The passage says 'the Montreal Protocol of 1987.'" },
        { number: 12, type: "true_false_not_given", text: "Magnetic refrigeration is already widely used in households.", correctAnswer: "NOT GIVEN", explanation: "The passage mentions magnetic refrigeration as a future research area but does not say it is widely used." },
        { number: 13, type: "true_false_not_given", text: "Early household refrigerators used ammonia as a refrigerant.", correctAnswer: "TRUE", explanation: "The passage says 'Early household refrigerators used toxic or flammable refrigerants — including ammonia.'" },
      ],
    },
    {
      title: "The Innovation of Grocery Stores",
      text: `A. The modern grocery store — a brightly lit, climate-controlled space stocked with thousands of products organised into clearly labelled aisles — is so familiar that it seems almost timeless. Yet the concept of self-service food shopping is barely a century old, and the evolution of the grocery store from a small, counter-service shop to a vast supermarket reflects fundamental changes in technology, consumer behaviour, urban planning, and the global food supply chain.

B. For most of recorded history, food was purchased from specialised merchants: bakers, butchers, fishmongers, greengrocers, and dairymen each sold their own category of products from dedicated shops or market stalls. The general store, which sold a wider variety of goods including non-perishable foods, household supplies, and hardware, became a fixture of rural communities in the eighteenth and nineteenth centuries. In these traditional retail formats, customers did not handle merchandise directly. Instead, they presented their orders to a clerk behind a counter, who retrieved the items from shelves or storerooms, weighed bulk goods, and packaged purchases by hand. This labour-intensive process was slow, limited the number of customers a store could serve, and gave shopkeepers significant control over product recommendations and pricing.

C. The self-service revolution began in September 1916, when Clarence Saunders opened the first Piggly Wiggly store in Memphis, Tennessee. Saunders's radical innovation was to allow customers to walk through the store, select products directly from open shelves, and bring their purchases to a checkout counter at the exit. He patented the self-service concept and designed his stores with carefully planned layouts that channelled customers past as many products as possible — an early application of what would later become the science of retail design. The Piggly Wiggly model reduced labour costs, increased the volume of customers that could be served, and — crucially — shifted purchasing decisions from the shopkeeper to the consumer, creating the foundation for modern brand marketing and product packaging.

D. The supermarket, as distinct from the self-service grocery store, emerged during the Great Depression of the 1930s. The first store generally credited as a true supermarket was King Kullen, which opened in a former garage in the Jamaica neighbourhood of Queens, New York, in August 1930. King Kullen operated on the principle of high volume and low profit margins, offering a vast selection of products at prices significantly below those of traditional grocery stores. Its success inspired rapid imitation, and by 1934 there were approximately 94 supermarkets operating across the United States. The supermarket model was ideally suited to the post-war suburban expansion of the 1950s and 1960s, as car-owning families in newly built suburbs sought convenient, one-stop shopping experiences with ample parking.

E. Technological innovation has continuously reshaped the grocery industry. The introduction of the barcode and electronic scanner in the 1970s — the first product scanned was a pack of Wrigley's Juicy Fruit chewing gum at a Marsh Supermarket in Troy, Ohio, on 26 June 1974 — dramatically improved inventory management, pricing accuracy, and checkout speed. Computerised supply chain management systems, introduced in the 1980s and 1990s, enabled just-in-time delivery and reduced waste. Loyalty card programmes, launched by chains such as Tesco in the UK in 1995, generated vast databases of consumer purchasing data that transformed marketing, product development, and store layout optimisation. Refrigeration and cold chain logistics, meanwhile, made it possible to stock fresh produce, dairy, and frozen foods sourced from around the world year-round.

F. The twenty-first century has brought a new wave of disruption to the grocery sector. Online grocery shopping, once a niche service, was accelerated dramatically by the COVID-19 pandemic: in the UK, the online share of grocery sales rose from approximately 7 percent in early 2020 to over 15 percent by mid-2021. Automated fulfilment centres, such as those operated by Ocado in the UK and used by Kroger in the United States, use thousands of robots to pick and pack online orders with extraordinary speed and accuracy. Amazon's acquisition of Whole Foods in 2017 and the launch of Amazon Fresh and Amazon Go stores — which use computer vision and sensor technology to allow customers to shop without traditional checkout — signalled the entry of technology giants into the grocery market and foreshadowed a future in which artificial intelligence, automation, and data analytics play an even larger role in how food reaches consumers.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Paragraph B", options: ["i. The digital transformation of grocery retail", "ii. The birth of the supermarket during economic hardship", "iii. Traditional methods of food retailing", "iv. How technology improved store operations", "v. The first self-service grocery store", "vi. A brief history of grocery stores", "vii. The rise of loyalty programmes", "viii. Online shopping changes everything"], correctAnswer: "iii", explanation: "Paragraph B describes the traditional counter-service model with specialised merchants and clerks." },
        { number: 15, type: "matching_headings", text: "Paragraph C", options: ["i. The digital transformation of grocery retail", "ii. The birth of the supermarket during economic hardship", "iii. Traditional methods of food retailing", "iv. How technology improved store operations", "v. The first self-service grocery store", "vi. A brief history of grocery stores", "vii. The rise of loyalty programmes", "viii. Online shopping changes everything"], correctAnswer: "v", explanation: "Paragraph C describes Clarence Saunders opening the first self-service Piggly Wiggly store." },
        { number: 16, type: "matching_headings", text: "Paragraph D", options: ["i. The digital transformation of grocery retail", "ii. The birth of the supermarket during economic hardship", "iii. Traditional methods of food retailing", "iv. How technology improved store operations", "v. The first self-service grocery store", "vi. A brief history of grocery stores", "vii. The rise of loyalty programmes", "viii. Online shopping changes everything"], correctAnswer: "ii", explanation: "Paragraph D describes King Kullen opening during the Great Depression." },
        { number: 17, type: "matching_headings", text: "Paragraph E", options: ["i. The digital transformation of grocery retail", "ii. The birth of the supermarket during economic hardship", "iii. Traditional methods of food retailing", "iv. How technology improved store operations", "v. The first self-service grocery store", "vi. A brief history of grocery stores", "vii. The rise of loyalty programmes", "viii. Online shopping changes everything"], correctAnswer: "iv", explanation: "Paragraph E discusses barcodes, supply chain systems, loyalty cards, and cold chain logistics." },
        { number: 18, type: "matching_headings", text: "Paragraph F", options: ["i. The digital transformation of grocery retail", "ii. The birth of the supermarket during economic hardship", "iii. Traditional methods of food retailing", "iv. How technology improved store operations", "v. The first self-service grocery store", "vi. A brief history of grocery stores", "vii. The rise of loyalty programmes", "viii. Online shopping changes everything"], correctAnswer: "i", explanation: "Paragraph F discusses online shopping, automated fulfilment, and Amazon's entry into groceries." },
        { number: 19, type: "table_completion", text: "Clarence Saunders opened the first Piggly Wiggly store in _______, Tennessee.", correctAnswer: "Memphis", explanation: "The passage says 'in Memphis, Tennessee.'" },
        { number: 20, type: "table_completion", text: "King Kullen opened in August _______ in Queens, New York.", correctAnswer: "1930", explanation: "The passage says it opened 'in August 1930.'" },
        { number: 21, type: "table_completion", text: "The first barcode-scanned product was a pack of Wrigley's _______ chewing gum.", correctAnswer: "Juicy Fruit", explanation: "The passage says 'Wrigley's Juicy Fruit chewing gum.'" },
        { number: 22, type: "table_completion", text: "Tesco launched its loyalty card programme in _______.", correctAnswer: "1995", explanation: "The passage says 'Tesco in the UK in 1995.'" },
        { number: 23, type: "table_completion", text: "By 1934, there were approximately _______ supermarkets in the United States.", correctAnswer: "94", explanation: "The passage says 'approximately 94 supermarkets.'" },
        { number: 24, type: "table_completion", text: "Amazon acquired _______ in 2017.", correctAnswer: "Whole Foods", explanation: "The passage says 'Amazon's acquisition of Whole Foods in 2017.'" },
        { number: 25, type: "table_completion", text: "UK online grocery sales rose from 7 percent to over _______ percent by mid-2021.", correctAnswer: "15", explanation: "The passage says 'over 15 percent by mid-2021.'" },
        { number: 26, type: "table_completion", text: "The first barcode scan took place on 26 June _______.", correctAnswer: "1974", explanation: "The passage says 'on 26 June 1974.'" },
      ],
    },
    {
      title: "Climate Change and Polar Research",
      text: `The polar regions — the Arctic in the north and Antarctica in the south — are among the most extreme and least inhabited environments on Earth, yet they play a disproportionately important role in regulating the global climate system. These vast expanses of ice, snow, and frigid ocean exert a profound influence on atmospheric circulation, ocean currents, sea levels, and the global carbon cycle. As the planet warms in response to rising greenhouse gas concentrations, the polar regions are changing faster than almost any other part of the Earth, and scientific research in these remote and inhospitable environments has become critical to understanding the trajectory and consequences of climate change.

The Arctic is warming approximately four times faster than the global average — a phenomenon known as Arctic amplification. This accelerated warming is driven primarily by the ice-albedo feedback mechanism: as rising temperatures cause sea ice to melt, the dark ocean water that is exposed absorbs far more solar radiation than the reflective ice surface it replaces, further raising temperatures and accelerating ice loss in a self-reinforcing cycle. The extent of Arctic sea ice in September — its annual minimum — has declined by approximately 13 percent per decade since satellite observations began in 1979, and the thickness of the remaining ice has also decreased substantially. Some climate models project that the Arctic Ocean could experience ice-free summers by the 2040s or 2050s, with profound consequences for marine ecosystems, indigenous communities, shipping routes, and geopolitical dynamics.

Antarctica holds approximately 26.5 million cubic kilometres of ice — enough to raise global sea levels by approximately 58 metres if it were all to melt. While the interior of the East Antarctic Ice Sheet remains relatively stable, the West Antarctic Ice Sheet and the Antarctic Peninsula are losing ice at accelerating rates. The Thwaites Glacier in West Antarctica, nicknamed the "Doomsday Glacier" because of its potential to trigger catastrophic sea-level rise, has been the subject of intensive international research. The glacier, which is roughly the size of Britain, is being undermined from below by warming ocean water that is melting its grounding line — the point where the glacier rests on the seabed. If the Thwaites Glacier were to collapse entirely, it could raise global sea levels by approximately 65 centimetres, and its collapse could destabilise neighbouring glaciers, potentially contributing an additional 2 to 3 metres of sea-level rise over subsequent centuries.

Polar research stations and expeditions provide essential data for understanding climate change. Ice cores — cylindrical samples drilled from ice sheets and glaciers — contain trapped air bubbles that preserve a record of atmospheric composition stretching back hundreds of thousands of years. Analysis of ice cores from Antarctica and Greenland has revealed the intimate relationship between greenhouse gas concentrations and temperature over eight glacial cycles spanning approximately 800,000 years. The current atmospheric concentration of carbon dioxide — approximately 421 parts per million as of 2023 — is higher than at any point in at least the past 800,000 years and likely the past several million years.

Permafrost — permanently frozen ground found across much of the Arctic — represents another critical concern. Arctic permafrost contains an estimated 1,500 billion tonnes of organic carbon — roughly twice the amount currently present in the atmosphere. As the Arctic warms, permafrost is thawing at increasing rates, releasing carbon dioxide and methane — a greenhouse gas approximately 80 times more potent than carbon dioxide over a 20-year period — into the atmosphere. This process creates another dangerous feedback loop: warming causes permafrost to thaw, which releases greenhouse gases, which causes further warming. Scientists estimate that permafrost thaw could release between 30 and 150 billion tonnes of carbon by 2100, depending on the rate of warming, which would significantly amplify the warming already caused by human fossil fuel emissions.

International cooperation is essential for polar research, and a network of treaties and institutions governs scientific activity in both polar regions. The Antarctic Treaty System, established in 1959 and now signed by 54 countries, designates Antarctica as a continent devoted to peace and science, prohibiting military activity, mineral mining, and nuclear testing. The Arctic Council, founded in 1996, brings together the eight Arctic states and indigenous peoples' organisations to address environmental protection, sustainable development, and scientific research in the Arctic. However, rising geopolitical tensions — driven by competition over newly accessible shipping routes, mineral and hydrocarbon resources exposed by melting ice, and strategic military positioning — threaten to undermine the spirit of international scientific cooperation that has characterised polar research for decades.`,
      questions: [
        { number: 27, type: "matching_information", text: "An explanation of why the Arctic warms faster than the global average", options: ["Paragraph 1", "Paragraph 2", "Paragraph 3", "Paragraph 4", "Paragraph 5", "Paragraph 6"], correctAnswer: "Paragraph 2", explanation: "Paragraph 2 explains Arctic amplification and the ice-albedo feedback mechanism." },
        { number: 28, type: "matching_information", text: "A description of the carbon stored in frozen ground", options: ["Paragraph 1", "Paragraph 2", "Paragraph 3", "Paragraph 4", "Paragraph 5", "Paragraph 6"], correctAnswer: "Paragraph 5", explanation: "Paragraph 5 discusses permafrost containing 1,500 billion tonnes of carbon." },
        { number: 29, type: "matching_information", text: "Information about a glacier that could cause major sea-level rise", options: ["Paragraph 1", "Paragraph 2", "Paragraph 3", "Paragraph 4", "Paragraph 5", "Paragraph 6"], correctAnswer: "Paragraph 3", explanation: "Paragraph 3 describes the Thwaites 'Doomsday Glacier' and its potential impact." },
        { number: 30, type: "matching_information", text: "Details of international treaties governing polar research", options: ["Paragraph 1", "Paragraph 2", "Paragraph 3", "Paragraph 4", "Paragraph 5", "Paragraph 6"], correctAnswer: "Paragraph 6", explanation: "Paragraph 6 discusses the Antarctic Treaty System and Arctic Council." },
        { number: 31, type: "matching_information", text: "How ancient air samples provide a record of past atmospheric conditions", options: ["Paragraph 1", "Paragraph 2", "Paragraph 3", "Paragraph 4", "Paragraph 5", "Paragraph 6"], correctAnswer: "Paragraph 4", explanation: "Paragraph 4 describes ice cores containing trapped air bubbles preserving atmospheric records." },
        { number: 32, type: "sentence_completion", text: "The Arctic is warming approximately _______ times faster than the global average.", correctAnswer: "four", explanation: "The passage says 'approximately four times faster.'" },
        { number: 33, type: "sentence_completion", text: "Arctic sea ice extent has declined by approximately _______ percent per decade since 1979.", correctAnswer: "13", explanation: "The passage says 'approximately 13 percent per decade.'" },
        { number: 34, type: "sentence_completion", text: "Antarctica holds approximately 26.5 million cubic kilometres of _______.", correctAnswer: "ice", explanation: "The passage says 'approximately 26.5 million cubic kilometres of ice.'" },
        { number: 35, type: "sentence_completion", text: "The Thwaites Glacier is roughly the size of _______.", correctAnswer: "Britain", explanation: "The passage says it is 'roughly the size of Britain.'" },
        { number: 36, type: "sentence_completion", text: "The Antarctic Treaty System was established in _______.", correctAnswer: "1959", explanation: "The passage says 'established in 1959.'" },
        { number: 37, type: "short_answer", text: "What is the nickname given to the Thwaites Glacier?", correctAnswer: "Doomsday Glacier", explanation: "The passage says it is 'nicknamed the \"Doomsday Glacier.\"'" },
        { number: 38, type: "short_answer", text: "What is the current atmospheric concentration of CO₂ as of 2023?", correctAnswer: "approximately 421 parts per million", explanation: "The passage says 'approximately 421 parts per million as of 2023.'" },
        { number: 39, type: "short_answer", text: "How much carbon does Arctic permafrost contain?", correctAnswer: "1,500 billion tonnes", explanation: "The passage says 'an estimated 1,500 billion tonnes of organic carbon.'" },
        { number: 40, type: "short_answer", text: "In what year was the Arctic Council founded?", correctAnswer: "1996", explanation: "The passage says 'The Arctic Council, founded in 1996.'" },
      ],
    },
  ],
};
