import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_7: ReadingTest = {
  id: 7,
  passages: [
    {
      title: "Ancient Farming Techniques",
      text: `The development of agriculture approximately 10,000 years ago marked one of the most significant turning points in human history. Before farming, humans lived as hunter-gatherers, moving from place to place in search of wild plants and animals. The transition to settled agriculture — often referred to as the Neolithic Revolution — enabled the establishment of permanent settlements, population growth, and the eventual rise of complex civilisations. Yet the farming techniques developed by ancient peoples were far more sophisticated than is commonly assumed, and many of these methods continue to inform modern agricultural practice.

One of the earliest and most widespread ancient farming techniques was slash-and-burn agriculture, also known as swidden farming. This method involved clearing a patch of forest or grassland by cutting down vegetation and setting it alight. The resulting ash enriched the soil with nutrients, particularly potassium and phosphorus, creating fertile ground for planting crops. After several growing seasons, when soil fertility declined, farmers would move to a new area and repeat the process, allowing the original plot to regenerate naturally over a period of years or decades. Slash-and-burn agriculture is still practised today in parts of Southeast Asia, Central Africa, and South America, though its sustainability depends heavily on population density and the length of fallow periods.

In the arid regions of the Middle East and North Africa, ancient farmers developed sophisticated irrigation systems to channel water from rivers and springs to their fields. The Sumerians of Mesopotamia, who inhabited the land between the Tigris and Euphrates rivers around 4000 BCE, constructed elaborate networks of canals, levees, and reservoirs to manage the seasonal flooding of these rivers and distribute water to crops. These irrigation systems enabled the cultivation of wheat, barley, and other cereals in an otherwise inhospitable landscape, supporting dense populations and the world's first cities. However, centuries of irrigation without adequate drainage led to the gradual accumulation of salt in the soil — a process known as salinisation — which eventually reduced crop yields and contributed to the decline of Sumerian civilisation.

In Mesoamerica, the Aztecs developed a remarkable agricultural system known as chinampas, or "floating gardens." These were artificial islands constructed in the shallow lakes of the Valley of Mexico by layering aquatic vegetation, mud, and soil on top of a framework of wooden stakes and woven reeds. The chinampas were extraordinarily productive, yielding up to seven harvests per year, thanks to the constant supply of water and nutrients from the surrounding lake. Canals between the islands allowed farmers to travel by canoe, transporting crops and supplies. At the height of the Aztec Empire in the fifteenth century, the chinampa system supported a population of over 200,000 in the capital city of Tenochtitlán, making it one of the largest cities in the world at that time.

In the Andean highlands of South America, the Inca civilisation employed a system of terraced farming to cultivate steep mountain slopes. By carving flat platforms into the hillsides and supporting them with stone retaining walls, the Inca created level planting surfaces that reduced soil erosion and maximised the use of limited arable land. An ingenious irrigation network channelled water from mountain streams through a series of canals and aqueducts to each terrace level. The Inca also developed a technique of freeze-drying potatoes — known as chuño — by exposing them to the cold night air at high altitude and then trampling them to remove moisture, enabling long-term storage and transportation of food supplies.

Ancient Chinese agriculture, meanwhile, was characterised by intensive cultivation and careful management of soil fertility. As early as the Han Dynasty (206 BCE–220 CE), Chinese farmers practised crop rotation and green manuring — ploughing nitrogen-fixing plants such as clover and vetch into the soil to restore fertility. Rice paddy farming, which involved flooding fields to create shallow pools of standing water, was perfected in southern China and eventually spread throughout East and Southeast Asia. Paddy fields not only provided ideal growing conditions for rice but also supported aquaculture, as farmers raised fish in the flooded paddies, creating an integrated food production system.

These ancient farming techniques demonstrate the ingenuity and ecological awareness of early agricultural societies. Far from being primitive, many of these methods represented elegant solutions to the challenges of food production in diverse environments. As modern agriculture faces growing pressure from climate change, soil degradation, and water scarcity, there is renewed interest in the lessons that ancient farming practices can offer for building more sustainable food systems in the twenty-first century.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "The Neolithic Revolution is described as significant primarily because it", options: ["A led to the extinction of wild animal species.", "B enabled permanent settlements and population growth.", "C introduced metal tools to farming communities.", "D caused the spread of diseases among early humans."], correctAnswer: "B", explanation: "The passage states the transition to agriculture 'enabled the establishment of permanent settlements, population growth, and the eventual rise of complex civilisations.'" },
        { number: 2, type: "multiple_choice", text: "According to the passage, slash-and-burn agriculture", options: ["A was used exclusively in ancient times.", "B destroyed soil permanently.", "C is still practised in some regions today.", "D was developed by the Sumerians."], correctAnswer: "C", explanation: "The passage states slash-and-burn 'is still practised today in parts of Southeast Asia, Central Africa, and South America.'" },
        { number: 3, type: "multiple_choice", text: "The decline of Sumerian civilisation was partly attributed to", options: ["A a lack of available river water.", "B invasion by neighbouring peoples.", "C the accumulation of salt in agricultural soil.", "D the abandonment of canal systems."], correctAnswer: "C", explanation: "The passage says salinisation 'eventually reduced crop yields and contributed to the decline of Sumerian civilisation.'" },
        { number: 4, type: "multiple_choice", text: "Chinampas were productive because they", options: ["A were built on naturally fertile volcanic soil.", "B received continuous water and nutrients from the lake.", "C were irrigated using advanced pumping technology.", "D benefited from a tropical climate with heavy rainfall."], correctAnswer: "B", explanation: "The passage states chinampas yielded up to seven harvests 'thanks to the constant supply of water and nutrients from the surrounding lake.'" },
        { number: 5, type: "multiple_choice", text: "The passage suggests that ancient farming techniques were", options: ["A generally inferior to modern methods.", "B more destructive than commonly believed.", "C surprisingly sophisticated and still relevant.", "D only effective in tropical climates."], correctAnswer: "C", explanation: "The passage says ancient techniques 'were far more sophisticated than is commonly assumed' and notes 'renewed interest in the lessons that ancient farming practices can offer.'" },
        { number: 6, type: "sentence_completion", text: "In slash-and-burn agriculture, ash from burned vegetation enriched the soil with potassium and _______.", correctAnswer: "phosphorus", explanation: "The passage states the ash 'enriched the soil with nutrients, particularly potassium and phosphorus.'" },
        { number: 7, type: "sentence_completion", text: "The Sumerians built canals, levees, and _______ to manage river flooding.", correctAnswer: "reservoirs", explanation: "The passage mentions 'elaborate networks of canals, levees, and reservoirs.'" },
        { number: 8, type: "sentence_completion", text: "Chinampas were constructed using wooden stakes, woven reeds, aquatic vegetation, mud, and _______.", correctAnswer: "soil", explanation: "The passage describes 'layering aquatic vegetation, mud, and soil on top of a framework of wooden stakes and woven reeds.'" },
        { number: 9, type: "sentence_completion", text: "At its peak, Tenochtitlán had a population of over _______.", correctAnswer: "200,000", explanation: "The passage states 'a population of over 200,000 in the capital city of Tenochtitlán.'" },
        { number: 10, type: "sentence_completion", text: "Inca terraces were supported by stone _______ walls.", correctAnswer: "retaining", explanation: "The passage describes 'supporting them with stone retaining walls.'" },
        { number: 11, type: "sentence_completion", text: "The Inca preserved potatoes through a freeze-drying technique known as _______.", correctAnswer: "chuño", explanation: "The passage introduces 'a technique of freeze-drying potatoes — known as chuño.'" },
        { number: 12, type: "sentence_completion", text: "Chinese farmers restored soil fertility by ploughing ______-fixing plants into the soil.", correctAnswer: "nitrogen", explanation: "The passage mentions 'ploughing nitrogen-fixing plants such as clover and vetch into the soil.'" },
        { number: 13, type: "sentence_completion", text: "Rice paddy farmers in China also raised _______ in flooded fields to create an integrated food system.", correctAnswer: "fish", explanation: "The passage states 'farmers raised fish in the flooded paddies.'" },
      ],
    },
    {
      title: "Coral Reef Ecosystems",
      text: `A. Coral reefs are among the most biologically diverse and economically valuable ecosystems on Earth. Often called the "rainforests of the sea," they cover less than one percent of the ocean floor yet support approximately 25 percent of all known marine species. The structural complexity of coral reefs provides habitat for an astonishing array of organisms, from microscopic algae and invertebrates to large predatory fish, sea turtles, and sharks. Beyond their ecological significance, coral reefs provide essential services to human communities, including coastal protection from storms and erosion, support for commercial and subsistence fisheries, and income from tourism and recreation.

B. The foundation of every coral reef is built by tiny animals called coral polyps, which belong to the phylum Cnidaria — the same group that includes jellyfish and sea anemones. Each polyp secretes a hard skeleton of calcium carbonate (limestone) around its base, and over time, successive generations of polyps build upon the skeletons of their predecessors, gradually constructing the massive limestone structures that form the reef framework. Most reef-building corals have a symbiotic relationship with microscopic algae known as zooxanthellae, which live within the coral tissue. The zooxanthellae photosynthesise sunlight to produce sugars, providing up to 90 percent of the coral's energy needs. In return, the coral provides the algae with shelter and access to nutrients. This partnership is the engine that drives the extraordinary productivity of coral reef ecosystems.

C. Coral reefs are classified into three main types based on their structure and relationship to adjacent landmasses. Fringing reefs grow directly from the shoreline, forming a narrow band of coral along the coast. Barrier reefs develop further offshore, separated from the mainland by a wide, deep lagoon; the most famous example is Australia's Great Barrier Reef, which stretches over 2,300 kilometres along the northeast coast of Queensland. Atolls are ring-shaped reefs that encircle a central lagoon, typically forming around volcanic islands that have gradually subsided beneath the ocean surface. Charles Darwin first proposed this theory of atoll formation during his voyage on HMS Beagle in the 1830s, and subsequent geological research has largely confirmed his hypothesis.

D. Despite their importance, coral reefs worldwide are under severe and increasing threat from a combination of local and global pressures. Overfishing disrupts the delicate balance of reef food webs, removing herbivorous fish that keep algae in check and allowing algae to overgrow and smother corals. Destructive fishing practices, such as the use of dynamite and cyanide, directly damage reef structures. Coastal development and agricultural runoff introduce sediment, nutrients, and pollutants into reef waters, reducing water clarity, promoting harmful algal blooms, and introducing pathogens that cause coral disease. Plastic pollution, which has reached every corner of the ocean, poses additional risks, as corals can ingest microplastics or become entangled in larger debris.

E. The single greatest threat to coral reefs, however, is climate change. Rising ocean temperatures driven by the accumulation of greenhouse gases in the atmosphere cause a phenomenon known as coral bleaching. When water temperatures exceed a threshold — typically just one to two degrees Celsius above the normal summer maximum — corals expel their symbiotic zooxanthellae, losing both their colour and their primary source of energy. If elevated temperatures persist for more than a few weeks, the corals starve and die. Mass bleaching events have become increasingly frequent and severe since the late 1990s. The global bleaching event of 2016–2017, driven by a powerful El Niño combined with long-term warming, affected over 70 percent of the world's coral reefs and killed an estimated 30 percent of the coral on the Great Barrier Reef alone.

F. Ocean acidification — the gradual decrease in seawater pH caused by the absorption of excess atmospheric carbon dioxide — represents another climate-related threat. As seawater becomes more acidic, it reduces the availability of carbonate ions that corals need to build their limestone skeletons, slowing reef growth and making existing structures more vulnerable to erosion. Laboratory and field studies suggest that if current trends continue, many reef environments could become chemically inhospitable to coral growth by the middle of the twenty-first century.

G. Efforts to protect and restore coral reefs are being pursued on multiple fronts. Marine protected areas (MPAs) have been established in many reef regions to limit fishing, diving, and other human activities. Coral gardening and reef restoration projects involve growing coral fragments in underwater nurseries and transplanting them onto degraded reefs. Scientists are also investigating the potential for "assisted evolution" — selectively breeding heat-tolerant coral strains or using genetic techniques to enhance resilience. However, conservationists emphasise that local management measures alone will be insufficient without decisive global action to reduce greenhouse gas emissions and limit warming to 1.5 degrees Celsius above pre-industrial levels, as called for in the Paris Agreement.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Paragraph B", options: ["i. Classification of reef structures", "ii. The biological foundation of coral reefs", "iii. Strategies for reef conservation", "iv. Climate-driven coral bleaching", "v. Local human threats to reefs", "vi. The ecological and economic value of reefs", "vii. The impact of ocean chemistry changes", "viii. Darwin's theory of reef development"], correctAnswer: "ii", explanation: "Paragraph B describes coral polyps, calcium carbonate skeletons, and the symbiotic relationship with zooxanthellae — the biological foundation." },
        { number: 15, type: "matching_headings", text: "Paragraph C", options: ["i. Classification of reef structures", "ii. The biological foundation of coral reefs", "iii. Strategies for reef conservation", "iv. Climate-driven coral bleaching", "v. Local human threats to reefs", "vi. The ecological and economic value of reefs", "vii. The impact of ocean chemistry changes", "viii. Darwin's theory of reef development"], correctAnswer: "i", explanation: "Paragraph C describes fringing reefs, barrier reefs, and atolls — a classification of reef types." },
        { number: 16, type: "matching_headings", text: "Paragraph D", options: ["i. Classification of reef structures", "ii. The biological foundation of coral reefs", "iii. Strategies for reef conservation", "iv. Climate-driven coral bleaching", "v. Local human threats to reefs", "vi. The ecological and economic value of reefs", "vii. The impact of ocean chemistry changes", "viii. Darwin's theory of reef development"], correctAnswer: "v", explanation: "Paragraph D discusses overfishing, destructive practices, runoff, and pollution — local human threats." },
        { number: 17, type: "matching_headings", text: "Paragraph E", options: ["i. Classification of reef structures", "ii. The biological foundation of coral reefs", "iii. Strategies for reef conservation", "iv. Climate-driven coral bleaching", "v. Local human threats to reefs", "vi. The ecological and economic value of reefs", "vii. The impact of ocean chemistry changes", "viii. Darwin's theory of reef development"], correctAnswer: "iv", explanation: "Paragraph E focuses on coral bleaching caused by rising ocean temperatures." },
        { number: 18, type: "matching_headings", text: "Paragraph F", options: ["i. Classification of reef structures", "ii. The biological foundation of coral reefs", "iii. Strategies for reef conservation", "iv. Climate-driven coral bleaching", "v. Local human threats to reefs", "vi. The ecological and economic value of reefs", "vii. The impact of ocean chemistry changes", "viii. Darwin's theory of reef development"], correctAnswer: "vii", explanation: "Paragraph F discusses ocean acidification and reduced carbonate ion availability." },
        { number: 19, type: "matching_headings", text: "Paragraph G", options: ["i. Classification of reef structures", "ii. The biological foundation of coral reefs", "iii. Strategies for reef conservation", "iv. Climate-driven coral bleaching", "v. Local human threats to reefs", "vi. The ecological and economic value of reefs", "vii. The impact of ocean chemistry changes", "viii. Darwin's theory of reef development"], correctAnswer: "iii", explanation: "Paragraph G discusses MPAs, coral gardening, assisted evolution, and emissions reduction." },
        { number: 20, type: "table_completion", text: "Zooxanthellae provide up to _______ percent of the coral's energy.", correctAnswer: "90", explanation: "The passage states zooxanthellae provide 'up to 90 percent of the coral's energy needs.'" },
        { number: 21, type: "table_completion", text: "Coral polyps secrete skeletons made of calcium _______.", correctAnswer: "carbonate", explanation: "The passage says each polyp 'secretes a hard skeleton of calcium carbonate.'" },
        { number: 22, type: "table_completion", text: "The Great Barrier Reef stretches over _______ kilometres.", correctAnswer: "2,300", explanation: "The passage states it 'stretches over 2,300 kilometres.'" },
        { number: 23, type: "table_completion", text: "Coral bleaching occurs when water temperature exceeds the normal maximum by _______ to two degrees.", correctAnswer: "one", explanation: "The passage says 'just one to two degrees Celsius above the normal summer maximum.'" },
        { number: 24, type: "table_completion", text: "The 2016–2017 bleaching event killed approximately _______ percent of coral on the Great Barrier Reef.", correctAnswer: "30", explanation: "The passage states 'killed an estimated 30 percent of the coral on the Great Barrier Reef.'" },
        { number: 25, type: "table_completion", text: "Charles Darwin proposed his theory of atoll formation during his voyage on HMS _______.", correctAnswer: "Beagle", explanation: "The passage mentions 'his voyage on HMS Beagle in the 1830s.'" },
        { number: 26, type: "table_completion", text: "The Paris Agreement calls for limiting warming to _______ degrees Celsius above pre-industrial levels.", correctAnswer: "1.5", explanation: "The passage mentions 'limit warming to 1.5 degrees Celsius above pre-industrial levels.'" },
      ],
    },
    {
      title: "Renewable Energy Innovations",
      text: `The global energy landscape is undergoing a profound transformation as nations seek to reduce their dependence on fossil fuels and transition to cleaner, renewable sources of power. Driven by concerns about climate change, air pollution, energy security, and the finite nature of oil, coal, and natural gas reserves, governments, businesses, and researchers around the world are investing heavily in technologies that harness energy from the sun, wind, water, and other sustainable sources. While renewable energy currently accounts for approximately 30 percent of global electricity generation, rapid technological advances and declining costs suggest that this share is poised to grow substantially in the coming decades.

A. Solar photovoltaic (PV) technology has experienced perhaps the most dramatic cost reduction of any energy technology in history. The price of solar panels has fallen by over 99 percent since the mid-1970s and by approximately 90 percent in the past decade alone. This plunge in costs, driven by manufacturing scale, improved cell efficiency, and intense market competition, has made solar power the cheapest source of new electricity generation in most parts of the world. Innovations continue to push the boundaries of solar technology. Perovskite solar cells, which use a class of synthetic crystalline materials as the light-absorbing layer, have achieved laboratory efficiencies approaching those of traditional silicon cells at potentially much lower manufacturing costs. Bifacial panels, which capture sunlight on both sides, and building-integrated photovoltaics (BIPV), which incorporate solar cells directly into building facades and windows, represent further avenues for expanding solar energy deployment.

B. Wind energy has also undergone a remarkable evolution. Modern wind turbines are vastly more powerful and efficient than the small machines installed in the 1980s. The latest offshore wind turbines stand over 260 metres tall — taller than most skyscrapers — with rotor diameters exceeding 220 metres and individual generating capacities of 15 megawatts or more. Floating offshore wind platforms, which can be deployed in deep waters where fixed-foundation turbines are impractical, are emerging as a particularly promising technology. Countries with deep continental shelves, such as Japan, South Korea, and Norway, are investing heavily in floating wind projects. Onshore, advances in blade design, materials science, and digital monitoring systems have enabled wind farms to operate more efficiently and in a wider range of wind conditions than ever before.

C. Energy storage is widely regarded as the critical enabling technology for a high-renewables electricity system. Because solar and wind power are intermittent — they generate electricity only when the sun shines or the wind blows — effective storage is needed to balance supply and demand and ensure grid reliability. Lithium-ion batteries, which dominate the current storage market, have seen costs fall by nearly 90 percent over the past decade, making grid-scale battery installations increasingly economically viable. However, researchers are exploring a range of alternative storage technologies that could offer advantages in terms of cost, duration, or scalability. These include solid-state batteries, which replace the liquid electrolyte with a solid material for improved safety and energy density; flow batteries, which store energy in liquid electrolyte tanks and can be scaled simply by increasing tank size; and green hydrogen, produced by using renewable electricity to split water into hydrogen and oxygen through electrolysis, which can be stored, transported, and used as a fuel or industrial feedstock.

D. The integration of artificial intelligence and digital technologies into energy systems is accelerating the pace of the renewable energy transition. Smart grids use sensors, communication networks, and AI algorithms to monitor and manage electricity flows in real time, optimising the balance between supply and demand and enabling the seamless integration of distributed renewable energy sources such as rooftop solar panels and small wind turbines. Machine learning models are being used to improve weather forecasting — a critical input for predicting solar and wind output — and to optimise the maintenance schedules of renewable energy assets, reducing downtime and extending equipment lifetimes. Blockchain technology is also being explored as a means of enabling peer-to-peer energy trading, allowing households and businesses with rooftop solar panels to sell surplus electricity directly to their neighbours.

E. Despite the rapid progress, significant challenges remain on the path to a fully renewable energy system. The extraction of raw materials for batteries and solar panels — including lithium, cobalt, nickel, and rare earth elements — raises environmental and ethical concerns, particularly in regions where mining operations cause deforestation, water pollution, or exploit vulnerable labour forces. The intermittency of renewable sources, while increasingly manageable through storage and smart grid technologies, still poses reliability challenges during extended periods of low wind and sunshine, sometimes referred to as "dunkelflaute" (a German term meaning "dark doldrums"). Furthermore, upgrading and expanding electricity transmission infrastructure to connect remote renewable energy sites with urban demand centres requires enormous capital investment and can face significant planning and permitting delays. Addressing these challenges will be essential if renewable energy is to fulfil its potential as the foundation of a sustainable global energy system.`,
      questions: [
        { number: 27, type: "matching_information", text: "The use of blockchain for energy trading between individuals", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E"], correctAnswer: "D", explanation: "Paragraph D mentions 'Blockchain technology is also being explored as a means of enabling peer-to-peer energy trading.'" },
        { number: 28, type: "matching_information", text: "Environmental concerns associated with mining for renewable energy components", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E"], correctAnswer: "E", explanation: "Paragraph E discusses concerns about extraction of lithium, cobalt, and rare earth elements." },
        { number: 29, type: "matching_information", text: "A technology that enables wind power generation in deep ocean waters", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E"], correctAnswer: "B", explanation: "Paragraph B discusses 'floating offshore wind platforms' for 'deep waters.'" },
        { number: 30, type: "matching_information", text: "The dramatic historical decline in solar panel prices", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E"], correctAnswer: "A", explanation: "Paragraph A states solar panel prices have 'fallen by over 99 percent since the mid-1970s.'" },
        { number: 31, type: "matching_information", text: "A storage method that uses water-splitting to produce fuel", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E"], correctAnswer: "C", explanation: "Paragraph C describes 'green hydrogen, produced by using renewable electricity to split water.'" },
        { number: 32, type: "multiple_choice", text: "According to the passage, perovskite solar cells are significant because they", options: ["A are already cheaper than all alternatives.", "B could match silicon efficiency at lower cost.", "C have replaced silicon cells in commercial use.", "D were developed exclusively for building integration."], correctAnswer: "B", explanation: "The passage states perovskite cells 'have achieved laboratory efficiencies approaching those of traditional silicon cells at potentially much lower manufacturing costs.'" },
        { number: 33, type: "multiple_choice", text: "The term 'dunkelflaute' refers to", options: ["A a type of renewable energy storage.", "B a German method of solar panel manufacturing.", "C extended periods with low wind and sunshine.", "D the cost of upgrading transmission infrastructure."], correctAnswer: "C", explanation: "The passage defines dunkelflaute as 'extended periods of low wind and sunshine.'" },
        { number: 34, type: "multiple_choice", text: "The latest offshore wind turbines can generate", options: ["A up to 5 megawatts each.", "B over 10 but less than 15 megawatts each.", "C 15 megawatts or more each.", "D over 50 megawatts each."], correctAnswer: "C", explanation: "The passage states 'individual generating capacities of 15 megawatts or more.'" },
        { number: 35, type: "short_answer", text: "What percentage of global electricity generation currently comes from renewable sources?", correctAnswer: "30 percent", explanation: "The passage states 'renewable energy currently accounts for approximately 30 percent of global electricity generation.'" },
        { number: 36, type: "short_answer", text: "What type of battery dominates the current energy storage market?", correctAnswer: "lithium-ion", explanation: "The passage says 'Lithium-ion batteries dominate the current storage market.'" },
        { number: 37, type: "short_answer", text: "What do flow batteries use to store energy?", correctAnswer: "liquid electrolyte", explanation: "The passage describes flow batteries as storing 'energy in liquid electrolyte tanks.'" },
        { number: 38, type: "short_answer", text: "How tall are the latest offshore wind turbines?", correctAnswer: "over 260 metres", explanation: "The passage states 'The latest offshore wind turbines stand over 260 metres tall.'" },
        { number: 39, type: "short_answer", text: "What technology is used to improve weather forecasting for renewable energy prediction?", correctAnswer: "machine learning", explanation: "The passage mentions 'Machine learning models are being used to improve weather forecasting.'" },
        { number: 40, type: "short_answer", text: "Name one country mentioned as investing in floating offshore wind projects.", correctAnswer: "Japan", explanation: "The passage mentions 'Japan, South Korea, and Norway' as investors. Any one is acceptable." },
      ],
    },
  ],
};
