import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_52: ReadingTest = {
  id: 52,
  passages: [
    {
      title: "History of Mechanical Innovation",
      text: `Throughout history, mechanical innovation has been the engine of human progress. From the simple lever to the complex internal combustion engine, each breakthrough in mechanical engineering has expanded the boundaries of what human societies can achieve. The story of mechanical innovation is not merely a chronicle of inventions but a narrative of how human ingenuity has repeatedly transformed the relationship between people and the physical world.

The six classical simple machines — the lever, wheel and axle, pulley, inclined plane, wedge, and screw — were identified and described by ancient Greek and Roman engineers. Archimedes of Syracuse, working in the third century BCE, provided the first mathematical analysis of lever mechanics and reportedly declared, "Give me a place to stand, and I shall move the Earth." These simple machines, which amplify force or change its direction, remain the fundamental building blocks of all mechanical devices.

The waterwheel, developed independently in several ancient civilisations, harnessed the kinetic energy of flowing water to perform mechanical work. Roman watermills ground grain on an industrial scale, with the Barbegal aqueduct and mill complex in southern France operating sixteen overshot waterwheels capable of producing enough flour to feed 12,500 people daily. By the medieval period, waterwheel technology had been adapted for a remarkable variety of applications: fulling cloth, sawing wood, hammering iron, and operating bellows for furnaces.

The mechanical clock, emerging in thirteenth-century Europe, represented a qualitative leap in mechanical complexity. Its escapement mechanism — which converted the continuous pull of a falling weight into a controlled oscillation — was arguably the first mechanical feedback system, anticipating cybernetic principles by seven centuries. The clock also established the concept of interchangeable precision components, as clockmakers developed standardised techniques for cutting gears and fitting bearings.

The steam engine, developed through the contributions of Thomas Newcomen, James Watt, and others in the eighteenth century, was the first practical device for converting heat energy into continuous mechanical motion. Watt's crucial innovation — the separate condenser, patented in 1769 — dramatically improved efficiency by preventing the repeated heating and cooling of the main cylinder. The steam engine powered the Industrial Revolution, driving factories, railways, and steamships that transformed global commerce and society.

The internal combustion engine, which burns fuel inside the engine rather than in an external furnace, enabled a new generation of portable power sources. Nikolaus Otto developed the four-stroke cycle in 1876, establishing the operating principle used by most petrol engines to this day. Rudolf Diesel patented his compression-ignition engine in 1893, offering greater efficiency at the cost of greater weight and complexity. These engines made automobiles, aircraft, and motorised agricultural equipment possible.

The twentieth century brought electronic and digital technologies that transformed mechanical systems from passive devices into intelligent ones. Computer numerical control (CNC) machining, introduced in the 1950s, enabled automated precision manufacturing. Industrial robots, first deployed in automobile factories in the 1960s, could perform welding, painting, and assembly tasks with consistency unmatched by human workers. Today, the integration of sensors, microprocessors, and artificial intelligence into mechanical systems is creating a new category of "smart machines" that can monitor their own condition, adapt to changing requirements, and learn from experience.

The frontier of mechanical innovation now encompasses fields that would have been inconceivable to earlier generations. Micro-electromechanical systems (MEMS) — devices with components measured in micrometres — enable technologies from smartphone accelerometers to medical implants. Soft robotics, inspired by biological organisms, uses flexible materials to create machines capable of safe interaction with humans and navigation through confined spaces. These developments suggest that the story of mechanical innovation is far from complete.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "How many classical simple machines were identified by ancient engineers?", options: ["A. Four", "B. Five", "C. Six", "D. Eight"], correctAnswer: "C", explanation: "The passage says 'The six classical simple machines.'" },
        { number: 2, type: "multiple_choice", text: "The Barbegal mill complex could produce flour for approximately", options: ["A. 5,000 people", "B. 10,000 people", "C. 12,500 people", "D. 20,000 people"], correctAnswer: "C", explanation: "The passage states 'enough flour to feed 12,500 people daily.'" },
        { number: 3, type: "multiple_choice", text: "What was James Watt's crucial innovation?", options: ["A. The four-stroke cycle", "B. The separate condenser", "C. Computer numerical control", "D. The escapement mechanism"], correctAnswer: "B", explanation: "The passage says 'Watt's crucial innovation — the separate condenser.'" },
        { number: 4, type: "multiple_choice", text: "Industrial robots were first deployed in", options: ["A. the 1940s", "B. the 1950s", "C. the 1960s", "D. the 1970s"], correctAnswer: "C", explanation: "The passage says 'first deployed in automobile factories in the 1960s.'" },
        { number: 5, type: "true_false_not_given", text: "Archimedes lived in the third century BCE.", correctAnswer: "TRUE", explanation: "The passage states 'working in the third century BCE.'" },
        { number: 6, type: "true_false_not_given", text: "The mechanical clock's escapement was the first electronic feedback system.", correctAnswer: "FALSE", explanation: "The passage says it was 'the first mechanical feedback system,' not electronic." },
        { number: 7, type: "true_false_not_given", text: "Rudolf Diesel's engine offered greater efficiency than Otto's.", correctAnswer: "TRUE", explanation: "The passage says the diesel engine offered 'greater efficiency at the cost of greater weight.'" },
        { number: 8, type: "true_false_not_given", text: "Watt patented the separate condenser in 1769.", correctAnswer: "TRUE", explanation: "The passage states 'patented in 1769.'" },
        { number: 9, type: "true_false_not_given", text: "MEMS components are measured in nanometres.", correctAnswer: "FALSE", explanation: "The passage says 'components measured in micrometres.'" },
        { number: 10, type: "true_false_not_given", text: "Soft robotics was invented by Archimedes.", correctAnswer: "NOT GIVEN", explanation: "The passage does not attribute soft robotics to Archimedes." },
        { number: 11, type: "true_false_not_given", text: "CNC machining was introduced in the 1950s.", correctAnswer: "TRUE", explanation: "The passage directly states this." },
        { number: 12, type: "true_false_not_given", text: "The waterwheel was developed in only one ancient civilisation.", correctAnswer: "FALSE", explanation: "The passage says it was 'developed independently in several ancient civilisations.'" },
        { number: 13, type: "true_false_not_given", text: "Nikolaus Otto developed the four-stroke cycle in 1876.", correctAnswer: "TRUE", explanation: "The passage directly states this." }
      ]
    },
    {
      title: "Oceanic Changes and Pollution",
      text: `A. The world's oceans are undergoing changes of a magnitude not seen in millions of years. Rising temperatures, increasing acidity, declining oxygen levels, and pervasive pollution are transforming marine environments in ways that threaten biodiversity, fisheries, and the livelihoods of billions of people who depend on the sea. Understanding these changes — their causes, mechanisms, and consequences — is essential for developing effective responses.

B. Ocean warming is the most direct consequence of climate change in the marine environment. The oceans have absorbed over ninety per cent of the excess heat trapped by greenhouse gases since 1970, raising average sea surface temperatures by approximately 0.9 degrees Celsius. This warming is not uniform: the Arctic Ocean is heating at roughly four times the global average, driving accelerated sea ice loss. Warmer waters expand, contributing to sea level rise, and alter ocean circulation patterns that influence weather systems worldwide.

C. Ocean acidification — often called "the other CO2 problem" — results from the absorption of atmospheric carbon dioxide by seawater. When CO2 dissolves in water, it forms carbonic acid, lowering the pH of the ocean. Since the beginning of the industrial era, ocean pH has decreased by approximately 0.1 units, representing a thirty per cent increase in acidity. This chemical shift threatens organisms that build calcium carbonate shells and skeletons, including corals, molluscs, and certain plankton species that form the base of marine food webs.

D. Deoxygenation — the loss of dissolved oxygen from ocean waters — is an emerging threat that receives less public attention than warming or acidification but may be equally consequential. Ocean oxygen levels have declined by approximately two per cent globally since 1960, with larger decreases in coastal areas and the deep ocean. Oxygen minimum zones, where levels are too low to support most marine life, have expanded by several million square kilometres. The causes include warming (warm water holds less dissolved oxygen), increased nutrient runoff that fuels algal blooms, and changes in ocean circulation.

E. Plastic pollution has become one of the most visible environmental problems facing the oceans. An estimated eight million tonnes of plastic waste enter the oceans annually, accumulating in vast patches like the Great Pacific Garbage Patch, which covers an area roughly three times the size of France. Microplastics — fragments smaller than five millimetres — have been found in every ocean, from surface waters to the deepest trenches, and in the tissues of marine organisms from plankton to whales. These particles can carry toxic chemicals and may affect the reproductive systems and feeding behaviour of marine animals.

F. Chemical pollution extends far beyond plastics. Agricultural runoff carrying pesticides and fertilisers creates coastal dead zones where excessive nutrient loads trigger algal blooms that consume all available oxygen. The Gulf of Mexico dead zone, fuelled by nutrient runoff from the Mississippi River basin, covered approximately 16,400 square kilometres in 2023. Industrial chemicals including mercury, lead, and persistent organic pollutants accumulate in marine food chains through bioaccumulation, reaching concentrations in top predators — tuna, swordfish, marine mammals — that pose risks to human consumers.

G. Noise pollution from shipping, construction, and military sonar represents an often-overlooked threat to marine life. Many marine species — particularly whales, dolphins, and fish — rely on sound for communication, navigation, and hunting. Anthropogenic noise can mask these signals, cause stress and behavioural changes, and in extreme cases cause physical injury. The doubling of commercial shipping traffic since 1990 has significantly increased ambient noise levels in many ocean regions.

H. International efforts to address ocean pollution have achieved some successes but face enormous challenges. The London Convention and its Protocol regulate the dumping of waste at sea. Regional agreements address pollution in specific ocean basins. The UN Global Plastics Treaty, under negotiation since 2022, aims to create a binding international framework to reduce plastic pollution across the full lifecycle of plastics. Yet enforcement remains weak, monitoring is inadequate, and the sheer scale of the problem — compounded by growing populations and consumption — continues to outpace remediation efforts.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Paragraph B", options: ["i. International responses to ocean pollution", "ii. The warming seas", "iii. Chemical contamination of food chains", "iv. Plastics in every ocean", "v. The silent threat of ocean noise", "vi. Declining oxygen levels", "vii. Acid seas", "viii. Overview of oceanic crisis"], correctAnswer: "ii", explanation: "Paragraph B discusses ocean warming." },
        { number: 15, type: "matching_headings", text: "Paragraph C", options: ["i. International responses to ocean pollution", "ii. The warming seas", "iii. Chemical contamination of food chains", "iv. Plastics in every ocean", "v. The silent threat of ocean noise", "vi. Declining oxygen levels", "vii. Acid seas", "viii. Overview of oceanic crisis"], correctAnswer: "vii", explanation: "Paragraph C discusses ocean acidification." },
        { number: 16, type: "matching_headings", text: "Paragraph E", options: ["i. International responses to ocean pollution", "ii. The warming seas", "iii. Chemical contamination of food chains", "iv. Plastics in every ocean", "v. The silent threat of ocean noise", "vi. Declining oxygen levels", "vii. Acid seas", "viii. Overview of oceanic crisis"], correctAnswer: "iv", explanation: "Paragraph E discusses plastic pollution." },
        { number: 17, type: "matching_headings", text: "Paragraph G", options: ["i. International responses to ocean pollution", "ii. The warming seas", "iii. Chemical contamination of food chains", "iv. Plastics in every ocean", "v. The silent threat of ocean noise", "vi. Declining oxygen levels", "vii. Acid seas", "viii. Overview of oceanic crisis"], correctAnswer: "v", explanation: "Paragraph G discusses noise pollution." },
        { number: 18, type: "summary_completion", text: "The oceans have absorbed over ________ per cent of excess heat since 1970.", correctAnswer: "ninety", explanation: "The passage states 'over ninety per cent.'" },
        { number: 19, type: "summary_completion", text: "Ocean pH has decreased by approximately ________ units since industrialisation.", correctAnswer: "0.1", explanation: "The passage says 'approximately 0.1 units.'" },
        { number: 20, type: "summary_completion", text: "Approximately ________ million tonnes of plastic enter the oceans annually.", correctAnswer: "eight", explanation: "The passage says 'An estimated eight million tonnes.'" },
        { number: 21, type: "summary_completion", text: "The Great Pacific Garbage Patch is roughly ________ times the size of France.", correctAnswer: "three", explanation: "The passage says 'roughly three times the size of France.'" },
        { number: 22, type: "table_completion", text: "Ocean oxygen levels have declined by approximately ________ per cent since 1960.", correctAnswer: "two", explanation: "The passage says 'approximately two per cent.'" },
        { number: 23, type: "table_completion", text: "The Gulf of Mexico dead zone covered approximately ________ square kilometres in 2023.", correctAnswer: "16,400", explanation: "The passage states 'approximately 16,400 square kilometres.'" },
        { number: 24, type: "table_completion", text: "Commercial shipping traffic has ________ since 1990.", correctAnswer: "doubled", explanation: "The passage says 'The doubling of commercial shipping traffic since 1990.'" },
        { number: 25, type: "table_completion", text: "Microplastics are fragments smaller than ________ millimetres.", correctAnswer: "five", explanation: "The passage says 'fragments smaller than five millimetres.'" },
        { number: 26, type: "table_completion", text: "The Arctic Ocean is heating at roughly ________ times the global average.", correctAnswer: "four", explanation: "The passage says 'roughly four times the global average.'" }
      ]
    },
    {
      title: "Future of Science and Human Life",
      text: `A. The pace of scientific discovery is accelerating in ways that could fundamentally alter human existence within the coming decades. Advances in genomics, neuroscience, artificial intelligence, and materials science are converging to create possibilities that were recently confined to science fiction. While these developments promise enormous benefits — from curing genetic diseases to extending healthy lifespans — they also raise profound ethical, social, and philosophical questions about the nature of humanity itself.

B. Gene editing technologies, particularly CRISPR-Cas9, have made it possible to modify DNA with unprecedented precision, speed, and affordability. Since its development as a gene editing tool in 2012, CRISPR has been used to correct genetic mutations in human embryos, create disease-resistant crops, and develop new approaches to treating cancer and inherited disorders. In 2020, Jennifer Doudna and Emmanuelle Charpentier received the Nobel Prize in Chemistry for their work on CRISPR. Clinical trials are underway for CRISPR-based treatments for sickle cell disease, beta thalassemia, and certain forms of blindness.

C. The controversial birth of gene-edited babies in China in 2018 — when scientist He Jiankui used CRISPR to modify embryos in an attempt to confer HIV resistance — demonstrated both the power and the dangers of the technology. The experiment was widely condemned by the scientific community for its reckless disregard for safety and ethics. It highlighted the absence of adequate international governance frameworks for human germline editing — changes that would be inherited by future generations.

D. Neuroscience is approaching the ability to interface directly with the human brain. Brain-computer interfaces (BCIs), which translate neural signals into digital commands, have enabled paralysed patients to control robotic limbs, type on computers, and even communicate through synthesised speech. Elon Musk's Neuralink company implanted its first brain chip in a human patient in 2024, aiming to restore communication and mobility for people with severe neurological conditions. The long-term vision — enhancing cognitive capabilities in healthy individuals — raises questions about equity, identity, and what it means to be human.

E. Longevity science has moved from the fringes of research to the scientific mainstream. Studies in model organisms have identified genetic and pharmacological interventions that significantly extend healthy lifespan. The drug metformin, originally developed for type 2 diabetes, is being tested in a major clinical trial — the TAME (Targeting Aging with Metformin) study — for its potential to delay age-related diseases. Senolytics, drugs that selectively eliminate senescent cells (damaged cells that accumulate with age and drive inflammation), have shown promising results in animal studies and early human trials.

F. Artificial intelligence is accelerating scientific discovery itself. AI systems have predicted protein structures that eluded researchers for decades — DeepMind's AlphaFold predicted the structures of virtually all known proteins in 2022. AI-driven drug discovery platforms can screen millions of candidate molecules in days rather than years. Machine learning algorithms identify patterns in astronomical data, climate models, and genomic datasets that would be impossible for human researchers to detect.

G. Materials science is producing substances with properties engineered at the atomic level. Graphene — a single layer of carbon atoms arranged in a hexagonal lattice — is two hundred times stronger than steel yet incredibly light and flexible. Metamaterials, designed with structures not found in nature, can manipulate light, sound, and electromagnetic waves in novel ways, with potential applications ranging from invisibility cloaking to ultra-efficient antennas. Self-healing materials that repair damage autonomously could extend the lifespan of infrastructure, vehicles, and electronic devices.

H. The convergence of these scientific frontiers creates possibilities — and risks — that are genuinely unprecedented. A future in which genetic diseases are eliminated, cognitive abilities enhanced, lifespans dramatically extended, and intelligent machines collaborate with enhanced humans is no longer purely speculative. Yet such a future also raises the spectre of deepened inequality, loss of human agency, and unforeseen consequences from intervening in complex biological and ecological systems. The choices societies make about how to govern these technologies will be among the most consequential decisions in human history.`,
      questions: [
        { number: 27, type: "matching_information", text: "A controversial experiment involving human embryo modification", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "C", explanation: "Paragraph C discusses He Jiankui's gene-edited babies." },
        { number: 28, type: "matching_information", text: "AI systems predicting protein structures", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "F", explanation: "Paragraph F discusses AlphaFold predicting protein structures." },
        { number: 29, type: "matching_information", text: "Materials stronger than steel engineered at the atomic level", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "G", explanation: "Paragraph G discusses graphene being 200 times stronger than steel." },
        { number: 30, type: "matching_information", text: "Drugs that eliminate damaged cells associated with ageing", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "E", explanation: "Paragraph E discusses senolytics." },
        { number: 31, type: "flow_chart_completion", text: "CRISPR-Cas9 was developed as a gene editing tool in ________.", correctAnswer: "2012", explanation: "The passage says 'since its development as a gene editing tool in 2012.'" },
        { number: 32, type: "flow_chart_completion", text: "Doudna and Charpentier received the Nobel Prize in ________.", correctAnswer: "Chemistry", explanation: "The passage says 'the Nobel Prize in Chemistry.'" },
        { number: 33, type: "flow_chart_completion", text: "Neuralink implanted its first brain chip in a human in ________.", correctAnswer: "2024", explanation: "The passage says 'implanted its first brain chip in a human patient in 2024.'" },
        { number: 34, type: "flow_chart_completion", text: "AlphaFold predicted structures of virtually all known proteins in ________.", correctAnswer: "2022", explanation: "The passage says 'predicted the structures of virtually all known proteins in 2022.'" },
        { number: 35, type: "short_answer", text: "What does TAME stand for?", correctAnswer: "Targeting Aging with Metformin", explanation: "The passage provides the full name." },
        { number: 36, type: "short_answer", text: "How many times stronger than steel is graphene?", correctAnswer: "two hundred times", explanation: "The passage says 'two hundred times stronger than steel.'" },
        { number: 37, type: "short_answer", text: "What are materials designed with structures not found in nature called?", correctAnswer: "metamaterials", explanation: "The passage defines metamaterials." },
        { number: 38, type: "short_answer", text: "What disease was metformin originally developed for?", correctAnswer: "type 2 diabetes", explanation: "The passage says 'originally developed for type 2 diabetes.'" },
        { number: 39, type: "short_answer", text: "What can brain-computer interfaces enable paralysed patients to control?", correctAnswer: "robotic limbs", explanation: "The passage says BCIs 'have enabled paralysed patients to control robotic limbs.'" },
        { number: 40, type: "short_answer", text: "What did He Jiankui attempt to confer through gene editing?", correctAnswer: "HIV resistance", explanation: "The passage says he aimed 'to confer HIV resistance.'" }
      ]
    }
  ]
};
