import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_6: ReadingTest = {
  id: 6,
  passages: [
    {
      title: "The History of Glass Making",
      text: `Glass is one of the most versatile materials ever created by humankind, yet its origins remain partially shrouded in mystery. The earliest known glass objects date back to around 3500 BCE and were discovered in regions of Mesopotamia and ancient Egypt. These primitive glass items — mainly beads and small decorative pieces — were likely produced as a byproduct of metalworking or ceramic glazing, rather than through any deliberate attempt to manufacture glass itself.

The Roman historian Pliny the Elder recorded a popular legend about glass's accidental discovery. According to his account, Phoenician merchants travelling along the coast of modern-day Lebanon stopped to prepare a meal on a sandy beach. Unable to find stones to support their cooking pots, they used lumps of natron — a naturally occurring mineral — from their cargo instead. When the natron combined with the sand under the intense heat of the fire, a translucent liquid formed, which cooled into glass. While most historians regard this story as apocryphal, it does reflect the basic chemistry of glass production: the fusion of silica (sand) with an alkali flux at high temperatures.

By around 1500 BCE, glass manufacturing had become a more deliberate and sophisticated craft in Egypt and Mesopotamia. Artisans developed the core-forming technique, in which molten glass was wrapped around a clay or dung core to create hollow vessels such as bottles and jars. These objects were highly prized and often reserved for royalty and the wealthy elite. The colours were achieved by adding metallic oxides — cobalt for blue, manganese for purple, and copper for green — a practice that demonstrated considerable chemical knowledge for the period.

The single greatest revolution in glass making came with the invention of glassblowing, which occurred in the Syro-Palestinian region around the first century BCE. This technique involved gathering molten glass on the end of a long hollow pipe and inflating it into a bubble, which could then be shaped using tools, gravity, and moulds. Glassblowing dramatically reduced the time and skill required to produce glass vessels, transforming glass from a luxury commodity into an everyday material accessible to ordinary Roman citizens. Workshops sprang up across the Roman Empire, and glass became widely used for tableware, storage containers, windows, and even jewellery.

Following the fall of the Western Roman Empire in the fifth century CE, the centre of glassmaking expertise shifted eastward to the Byzantine Empire and the Islamic world. Islamic artisans developed new decorative techniques, including gilding, enamelling, and the cutting of intricate geometric patterns into glass surfaces. Meanwhile, in northern Europe, glassmakers in regions such as the Rhineland continued to produce glass using wood-ash as a flux instead of the soda used in the Mediterranean. This so-called "forest glass" had a distinctive greenish tint and was typically less refined than its southern counterparts.

Venice emerged as Europe's dominant glassmaking centre during the medieval period. By the thirteenth century, the Venetian government had ordered all glassmakers to relocate to the island of Murano, ostensibly to reduce the fire risk posed by their furnaces but also to protect the secrets of their craft. Murano's glassmakers developed cristallo, an exceptionally clear and thin glass that became the envy of Europe. They also perfected millefiori (thousand flowers) and lattimo (milk glass) techniques, producing objects of extraordinary beauty and commanding premium prices across the continent.

The next major advance came in seventeenth-century England, where George Ravenscroft developed lead crystal glass by adding lead oxide to the traditional glass mixture. This produced a heavier, more brilliant glass with superior light-refracting properties, making it ideal for fine drinking glasses and chandeliers. Lead crystal quickly became the preferred material for high-quality tableware throughout Europe.

The Industrial Revolution of the eighteenth and nineteenth centuries transformed glass from a craft product into an industrial commodity. Mechanical processes for pressing, rolling, and drawing glass were developed, enabling the mass production of flat glass for windows, bottles for food and beverage packaging, and scientific instruments such as lenses and laboratory equipment. The invention of the Siemens regenerative furnace in the 1850s dramatically improved energy efficiency and enabled continuous production.

In the twentieth century, the float glass process, invented by Sir Alastair Pilkington in 1959, revolutionised the production of flat glass. By floating molten glass on a bed of molten tin, Pilkington's method produced perfectly flat, uniform sheets of glass without the need for grinding or polishing. Today, the float process accounts for the vast majority of flat glass produced worldwide. Modern glass technology continues to evolve, with innovations such as self-cleaning coatings, smart glass that changes opacity electronically, and ultra-thin flexible glass for use in electronic displays, ensuring that this ancient material remains at the forefront of technological progress.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "The earliest glass objects were most likely created", options: ["A as part of a deliberate manufacturing process.", "B as an unintentional result of other crafts.", "C by Phoenician merchants on a beach.", "D exclusively for scientific purposes."], correctAnswer: "B", explanation: "The passage states the earliest glass items 'were likely produced as a byproduct of metalworking or ceramic glazing, rather than through any deliberate attempt.'" },
        { number: 2, type: "multiple_choice", text: "According to the passage, Pliny the Elder's account of glass discovery is", options: ["A scientifically proven.", "B widely accepted by historians.", "C considered unlikely but chemically plausible.", "D completely fictional with no basis in fact."], correctAnswer: "C", explanation: "The passage says most historians regard the story as 'apocryphal' but notes 'it does reflect the basic chemistry of glass production.'" },
        { number: 3, type: "multiple_choice", text: "The core-forming technique involved", options: ["A blowing glass through a hollow pipe.", "B wrapping molten glass around a shaped core.", "C pressing glass into flat sheets.", "D floating glass on molten tin."], correctAnswer: "B", explanation: "The passage describes core-forming as wrapping 'molten glass around a clay or dung core to create hollow vessels.'" },
        { number: 4, type: "multiple_choice", text: "What was the main effect of the invention of glassblowing?", options: ["A It improved the colour range of glass.", "B It made glass production faster and more affordable.", "C It shifted glassmaking to northern Europe.", "D It eliminated the need for metallic oxides."], correctAnswer: "B", explanation: "Glassblowing 'dramatically reduced the time and skill required' and transformed glass 'from a luxury commodity into an everyday material.'" },
        { number: 5, type: "multiple_choice", text: "Venetian glassmakers were moved to Murano", options: ["A to be closer to raw materials.", "B solely to prevent fires in Venice.", "C partly to safeguard trade secrets.", "D because Murano had better furnaces."], correctAnswer: "C", explanation: "The passage says the move was 'ostensibly to reduce fire risk' but 'also to protect the secrets of their craft.'" },
        { number: 6, type: "multiple_choice", text: "Lead crystal glass was valued primarily for its", options: ["A lightweight structure.", "B ability to resist heat.", "C superior optical brilliance.", "D low production cost."], correctAnswer: "C", explanation: "Lead crystal had 'superior light-refracting properties, making it ideal for fine drinking glasses and chandeliers.'" },
        { number: 7, type: "true_false_not_given", text: "Glass beads from 3500 BCE have been found in China.", correctAnswer: "NOT GIVEN", explanation: "The passage mentions Mesopotamia and ancient Egypt but does not mention China." },
        { number: 8, type: "true_false_not_given", text: "Cobalt was used to produce blue-coloured glass in ancient Egypt.", correctAnswer: "TRUE", explanation: "The passage states 'cobalt for blue' when describing the metallic oxides used by Egyptian and Mesopotamian artisans." },
        { number: 9, type: "true_false_not_given", text: "Glassblowing was invented in Rome.", correctAnswer: "FALSE", explanation: "The passage states glassblowing was invented 'in the Syro-Palestinian region,' not in Rome." },
        { number: 10, type: "true_false_not_given", text: "Islamic glassmakers were the first to use enamelling techniques.", correctAnswer: "NOT GIVEN", explanation: "The passage mentions Islamic artisans 'developed' enamelling but does not say they were the first ever to use it." },
        { number: 11, type: "true_false_not_given", text: "Forest glass was generally of higher quality than Mediterranean glass.", correctAnswer: "FALSE", explanation: "The passage says forest glass 'was typically less refined than its southern counterparts.'" },
        { number: 12, type: "true_false_not_given", text: "The Siemens furnace allowed glass to be produced continuously.", correctAnswer: "TRUE", explanation: "The passage states the Siemens furnace 'enabled continuous production.'" },
        { number: 13, type: "true_false_not_given", text: "The float glass process was patented before the Second World War.", correctAnswer: "FALSE", explanation: "The float glass process was 'invented by Sir Alastair Pilkington in 1959,' which is after WWII." },
      ],
    },
    {
      title: "Urban Green Spaces",
      text: `A. The rapid expansion of cities across the globe has brought numerous benefits — economic growth, cultural dynamism, and improved infrastructure — but it has also created significant challenges for the health and well-being of urban populations. One response to these challenges has been a renewed focus on urban green spaces: parks, gardens, tree-lined streets, green roofs, and other areas of vegetation within the built environment. Research over the past three decades has consistently demonstrated that access to green spaces is associated with a wide range of physical, mental, and social benefits for city dwellers.

B. The physical health advantages of urban green spaces are perhaps the most extensively documented. Studies have shown that people who live near parks and gardens are more likely to engage in physical activity, including walking, jogging, cycling, and outdoor sports. A landmark study published in The Lancet in 2008 found that populations living in the greenest areas had significantly lower rates of cardiovascular disease and respiratory illness compared with those in the least green areas, even after controlling for factors such as income, education, and smoking. Green spaces also help to mitigate the urban heat island effect — the phenomenon whereby cities are several degrees warmer than surrounding rural areas — by providing shade and releasing moisture through evapotranspiration.

C. The mental health benefits of exposure to nature in urban settings have attracted growing attention from researchers and policymakers alike. A study conducted by the University of Exeter in 2019 found that people who spent at least 120 minutes per week in natural environments reported significantly higher levels of well-being and life satisfaction than those who did not. Other research has linked regular access to green spaces with reduced levels of cortisol (the stress hormone), lower rates of depression and anxiety, and improved cognitive function, particularly in children. The Japanese practice of shinrin-yoku, or "forest bathing," which involves mindful immersion in a wooded environment, has been shown to produce measurable reductions in blood pressure, heart rate, and stress hormones.

D. Beyond individual health outcomes, urban green spaces play an important role in fostering social cohesion and community engagement. Parks and gardens serve as communal gathering places where people of different ages, backgrounds, and socioeconomic groups can interact. Community gardens, in particular, have been found to strengthen neighbourhood bonds, reduce crime rates, and provide opportunities for intercultural exchange. Research by Sullivan and colleagues at the University of Illinois demonstrated that public housing residents with access to green common areas reported stronger social ties with neighbours, a greater sense of safety, and lower levels of aggression than those whose surroundings were barren.

E. Urban green spaces also deliver significant environmental services to cities. Trees and vegetation absorb carbon dioxide and other pollutants from the atmosphere, helping to improve air quality. Green infrastructure — including rain gardens, bioswales, and permeable surfaces — can reduce stormwater runoff and lower the risk of urban flooding. Biodiversity is another benefit: even relatively small urban parks can support a surprising variety of plant and animal species, providing habitat corridors that connect fragmented ecosystems across metropolitan regions. A study in the city of Sheffield, England, found that domestic gardens alone contained over 1,000 species of plants, supporting a rich community of insects, birds, and small mammals.

F. Despite the well-documented benefits, access to urban green spaces is far from equitable. Research consistently shows that lower-income and minority communities have less access to quality green spaces than wealthier, predominantly white neighbourhoods — a disparity sometimes referred to as "green gentrification" or "environmental injustice." When investment in new parks does occur in disadvantaged areas, it can paradoxically lead to rising property values and rents, displacing the very communities the improvements were intended to serve. Addressing this tension requires careful planning, community involvement, and policies that protect affordable housing alongside green space development.

G. Looking ahead, urban planners and architects are exploring innovative approaches to integrating nature into city design. Vertical forests — residential towers covered in trees and shrubs — have been constructed in Milan and are planned for cities in China, the Netherlands, and elsewhere. Singapore has embraced the concept of a "city in a garden," incorporating extensive rooftop gardens, elevated walkways through forest canopy, and nature reserves into its urban fabric. Meanwhile, the concept of the "15-minute city," in which all essential services are accessible within a short walk or cycle ride, typically incorporates significant green infrastructure as a core design principle. These developments suggest that the role of nature in urban life is likely to grow rather than diminish in the coming decades.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Paragraph B", options: ["i. The unequal distribution of green spaces", "ii. Physical health improvements linked to green areas", "iii. New architectural concepts incorporating nature", "iv. The psychological impact of natural environments", "v. Environmental functions of urban vegetation", "vi. The role of green spaces in building communities", "vii. An overview of the challenges facing modern cities", "viii. Financial benefits of investing in parks"], correctAnswer: "ii", explanation: "Paragraph B focuses on 'physical health advantages of urban green spaces' including lower cardiovascular disease and the heat island effect." },
        { number: 15, type: "matching_headings", text: "Paragraph C", options: ["i. The unequal distribution of green spaces", "ii. Physical health improvements linked to green areas", "iii. New architectural concepts incorporating nature", "iv. The psychological impact of natural environments", "v. Environmental functions of urban vegetation", "vi. The role of green spaces in building communities", "vii. An overview of the challenges facing modern cities", "viii. Financial benefits of investing in parks"], correctAnswer: "iv", explanation: "Paragraph C discusses mental health benefits — stress reduction, depression, anxiety, and cognitive function." },
        { number: 16, type: "matching_headings", text: "Paragraph D", options: ["i. The unequal distribution of green spaces", "ii. Physical health improvements linked to green areas", "iii. New architectural concepts incorporating nature", "iv. The psychological impact of natural environments", "v. Environmental functions of urban vegetation", "vi. The role of green spaces in building communities", "vii. An overview of the challenges facing modern cities", "viii. Financial benefits of investing in parks"], correctAnswer: "vi", explanation: "Paragraph D discusses social cohesion, community engagement, and neighbourhood bonds." },
        { number: 17, type: "matching_headings", text: "Paragraph E", options: ["i. The unequal distribution of green spaces", "ii. Physical health improvements linked to green areas", "iii. New architectural concepts incorporating nature", "iv. The psychological impact of natural environments", "v. Environmental functions of urban vegetation", "vi. The role of green spaces in building communities", "vii. An overview of the challenges facing modern cities", "viii. Financial benefits of investing in parks"], correctAnswer: "v", explanation: "Paragraph E describes how trees absorb CO2, green infrastructure reduces flooding, and parks support biodiversity." },
        { number: 18, type: "matching_headings", text: "Paragraph F", options: ["i. The unequal distribution of green spaces", "ii. Physical health improvements linked to green areas", "iii. New architectural concepts incorporating nature", "iv. The psychological impact of natural environments", "v. Environmental functions of urban vegetation", "vi. The role of green spaces in building communities", "vii. An overview of the challenges facing modern cities", "viii. Financial benefits of investing in parks"], correctAnswer: "i", explanation: "Paragraph F discusses inequitable access, disparities in green space availability, and green gentrification." },
        { number: 19, type: "matching_headings", text: "Paragraph G", options: ["i. The unequal distribution of green spaces", "ii. Physical health improvements linked to green areas", "iii. New architectural concepts incorporating nature", "iv. The psychological impact of natural environments", "v. Environmental functions of urban vegetation", "vi. The role of green spaces in building communities", "vii. An overview of the challenges facing modern cities", "viii. Financial benefits of investing in parks"], correctAnswer: "iii", explanation: "Paragraph G discusses vertical forests, Singapore's city-in-a-garden concept, and the 15-minute city." },
        { number: 20, type: "summary_completion", text: "Research has shown that living near green areas is associated with increased _______ activity among residents.", correctAnswer: "physical", explanation: "Paragraph B states people near parks 'are more likely to engage in physical activity.'" },
        { number: 21, type: "summary_completion", text: "Green spaces help reduce the urban heat island effect through shade and _______.", correctAnswer: "evapotranspiration", explanation: "The passage states green spaces provide shade 'and releasing moisture through evapotranspiration.'" },
        { number: 22, type: "summary_completion", text: "Spending at least 120 minutes per week in nature was linked to higher levels of _______ and life satisfaction.", correctAnswer: "well-being", explanation: "The Exeter study found people 'reported significantly higher levels of well-being and life satisfaction.'" },
        { number: 23, type: "summary_completion", text: "The Japanese practice of shinrin-yoku involves mindful immersion in a _______ environment.", correctAnswer: "wooded", explanation: "The passage defines shinrin-yoku as 'mindful immersion in a wooded environment.'" },
        { number: 24, type: "summary_completion", text: "Community gardens have been found to reduce crime rates and provide opportunities for _______ exchange.", correctAnswer: "intercultural", explanation: "The passage states community gardens 'provide opportunities for intercultural exchange.'" },
        { number: 25, type: "summary_completion", text: "Green infrastructure such as rain gardens can reduce stormwater _______ in cities.", correctAnswer: "runoff", explanation: "The passage says green infrastructure 'can reduce stormwater runoff.'" },
        { number: 26, type: "summary_completion", text: "Investment in parks in disadvantaged areas can lead to rising property values and _______, displacing communities.", correctAnswer: "rents", explanation: "The passage states it 'can paradoxically lead to rising property values and rents, displacing the very communities.'" },
      ],
    },
    {
      title: "The Future of Artificial Intelligence",
      text: `Artificial intelligence has progressed from a theoretical curiosity discussed in university laboratories to a transformative force reshaping industries, governments, and daily life across the globe. The term "artificial intelligence" was first coined by computer scientist John McCarthy in 1956 at a conference at Dartmouth College, where a small group of researchers proposed that "every aspect of learning or any other feature of intelligence can in principle be so precisely described that a machine can be made to simulate it." Seven decades later, that ambitious vision has been partially realised in ways that even its founders could scarcely have imagined.

A. The current wave of AI advancement is driven primarily by deep learning, a subset of machine learning that uses artificial neural networks loosely inspired by the structure of the human brain. These networks consist of layers of interconnected nodes that process information in a hierarchical manner, progressively extracting higher-level features from raw data. The availability of vast datasets, combined with exponential increases in computing power — particularly through graphics processing units (GPUs) — has enabled deep learning systems to achieve remarkable performance in tasks such as image recognition, natural language processing, and strategic game playing. In 2016, Google DeepMind's AlphaGo program defeated the world champion of Go, a board game of extraordinary complexity, marking a milestone that many AI researchers had not expected to occur for another decade.

B. One of the most visible applications of AI in recent years has been in the field of natural language processing (NLP). Large language models such as OpenAI's GPT series and Google's BERT have demonstrated an unprecedented ability to generate coherent text, translate between languages, summarise documents, and answer questions. These models are trained on enormous corpora of text from the internet and other sources, enabling them to learn patterns of language use at a statistical level. However, critics point out that such models do not truly "understand" language in the way that humans do; they are sophisticated pattern-matching systems that can produce plausible but sometimes factually incorrect or biased outputs, a phenomenon known as "hallucination."

C. In healthcare, AI is beginning to deliver on its promise to improve diagnosis, treatment planning, and drug discovery. Machine learning algorithms have been shown to match or outperform human radiologists in detecting certain cancers from medical images, including breast cancer in mammograms and lung cancer in CT scans. AI systems are also being used to predict which patients are at highest risk of developing specific conditions, enabling earlier intervention. In pharmaceutical research, AI-driven platforms can screen millions of molecular compounds in a fraction of the time required by traditional methods, potentially accelerating the development of new drugs and vaccines. However, regulatory frameworks for AI in medicine remain in their infancy, and concerns about data privacy, algorithmic bias, and the "black box" nature of many AI systems present significant barriers to widespread clinical adoption.

D. The economic implications of AI are the subject of intense debate among economists, policymakers, and business leaders. Some analysts predict that AI will create a new era of productivity growth, generating trillions of dollars in economic value by automating routine tasks, optimising supply chains, and enabling entirely new products and services. A widely cited report by McKinsey Global Institute estimated that AI could contribute up to $13 trillion to the global economy by 2030. However, others warn that the displacement of workers by AI-powered automation could exacerbate inequality, particularly for those in low-skilled or routine occupations. A study by researchers at Oxford University suggested that up to 47 percent of jobs in the United States were at risk of automation within the next two decades.

E. The ethical dimensions of AI development have moved to the forefront of public discourse. Issues such as algorithmic bias — where AI systems perpetuate or amplify existing social prejudices embedded in training data — have attracted widespread attention. Facial recognition technology, for instance, has been shown to exhibit significantly higher error rates for women and people of colour than for white men, raising serious concerns about fairness and civil liberties. The use of AI in autonomous weapons systems, surveillance, and social media manipulation has prompted calls for international regulation. In response, numerous organisations and governments have published ethical guidelines and principles for AI development, though enforcing these standards across national boundaries remains a formidable challenge.

F. Looking further into the future, some researchers are pursuing the development of artificial general intelligence (AGI) — AI systems that possess human-level cognitive abilities across a broad range of tasks, rather than excelling only in narrow, specific domains. While AGI remains a distant and uncertain prospect, its potential implications are profound. Proponents argue that AGI could help solve humanity's most pressing challenges, from climate change to disease eradication. Sceptics, however, warn of existential risks if superintelligent systems are developed without adequate safety measures and alignment with human values. The debate over AGI highlights a fundamental tension in AI research: the desire to push the boundaries of what machines can do, balanced against the need to ensure that technological progress serves the broader interests of humanity.`,
      questions: [
        { number: 27, type: "matching_information", text: "A comparison between AI performance and that of medical professionals", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "C", explanation: "Paragraph C states AI algorithms 'match or outperform human radiologists.'" },
        { number: 28, type: "matching_information", text: "The percentage of jobs potentially affected by automation", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "D", explanation: "Paragraph D mentions the Oxford study suggesting '47 percent of jobs' at risk." },
        { number: 29, type: "matching_information", text: "The origin of the term 'artificial intelligence'", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "A", explanation: "The introductory text before paragraph A mentions John McCarthy coining the term in 1956. Since the intro leads into Paragraph A, A is the closest match." },
        { number: 30, type: "matching_information", text: "Errors in AI systems related to demographic characteristics", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "E", explanation: "Paragraph E discusses facial recognition exhibiting 'higher error rates for women and people of colour.'" },
        { number: 31, type: "matching_information", text: "A significant achievement in an AI system playing a board game", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "A", explanation: "Paragraph A describes AlphaGo defeating the world champion of Go." },
        { number: 32, type: "sentence_completion", text: "Deep learning networks process information in a _______ manner through layers of nodes.", correctAnswer: "hierarchical", explanation: "The passage states these networks 'process information in a hierarchical manner.'" },
        { number: 33, type: "sentence_completion", text: "Large language models can produce factually incorrect outputs, a problem known as _______.", correctAnswer: "hallucination", explanation: "The passage defines producing 'plausible but sometimes factually incorrect' outputs as 'hallucination.'" },
        { number: 34, type: "sentence_completion", text: "AI-driven platforms in pharmaceutical research can screen millions of molecular _______ rapidly.", correctAnswer: "compounds", explanation: "The passage says AI 'can screen millions of molecular compounds in a fraction of the time.'" },
        { number: 35, type: "sentence_completion", text: "McKinsey estimated AI could contribute up to $13 _______ to the global economy by 2030.", correctAnswer: "trillion", explanation: "The passage mentions 'up to $13 trillion to the global economy by 2030.'" },
        { number: 36, type: "sentence_completion", text: "Algorithmic bias occurs when AI systems perpetuate prejudices embedded in _______ data.", correctAnswer: "training", explanation: "The passage describes 'existing social prejudices embedded in training data.'" },
        { number: 37, type: "short_answer", text: "What type of processing units enabled the rapid advancement of deep learning?", correctAnswer: "GPUs", explanation: "The passage mentions 'graphics processing units (GPUs)' as key enablers." },
        { number: 38, type: "short_answer", text: "In what year did AlphaGo defeat the world champion of Go?", correctAnswer: "2016", explanation: "The passage states 'In 2016, Google DeepMind's AlphaGo program defeated the world champion.'" },
        { number: 39, type: "short_answer", text: "What term describes AI systems with human-level cognitive abilities across broad tasks?", correctAnswer: "artificial general intelligence", explanation: "The passage defines AGI as 'AI systems that possess human-level cognitive abilities across a broad range of tasks.'" },
        { number: 40, type: "short_answer", text: "What two types of cancer detection are mentioned as areas where AI matches human performance?", correctAnswer: "breast cancer and lung cancer", explanation: "The passage mentions 'breast cancer in mammograms and lung cancer in CT scans.'" },
      ],
    },
  ],
};
