import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_50: ReadingTest = {
  id: 50,
  passages: [
    {
      title: "Education and Learning Methods",
      text: `The way societies educate their young has evolved dramatically over the centuries, reflecting changing beliefs about the nature of learning, the purpose of education, and the skills required for economic and social participation. From the tutorial methods of ancient Greece to the standardised testing regimes of the twenty-first century, educational practice has been shaped by philosophical ideas, technological developments, and economic imperatives.

In ancient Athens, education was the preserve of free male citizens and centred on the development of the whole person — body, mind, and character. Physical training in the gymnasium was complemented by instruction in music, poetry, and rhetoric. The Socratic method, attributed to the philosopher Socrates, emphasised questioning and dialogue rather than passive absorption of information. Students were challenged to examine their assumptions, define their terms, and construct logical arguments. This approach, which prioritises critical thinking over rote memorisation, remains influential in contemporary pedagogy, particularly in law schools and philosophy departments.

The medieval European university system, which emerged in the twelfth and thirteenth centuries, introduced a more formalised structure. Institutions such as the University of Bologna (founded in 1088) and the University of Oxford (established around 1096) organised knowledge into faculties — theology, law, medicine, and the liberal arts — and awarded degrees based on examinations and disputations. The lecture format, in which a professor reads and comments on an authoritative text while students take notes, became the dominant instructional method and persists to this day.

The Prussian education model of the early nineteenth century profoundly influenced the development of mass public education worldwide. Prussia introduced compulsory schooling for all children, standardised curricula, trained professional teachers, and organised students into age-graded classes. This system was designed to produce literate, disciplined citizens capable of serving in the military and the emerging industrial workforce. Its efficiency was widely admired, and variants were adopted across Europe, North America, and eventually much of the world. Critics, however, argue that the Prussian model's emphasis on obedience, uniformity, and passive learning stifles creativity and individual development.

The twentieth century saw a proliferation of alternative educational philosophies. Maria Montessori developed a method based on self-directed activity, hands-on learning, and collaborative play, allowing children to make creative choices in their learning while teachers serve as guides rather than lecturers. John Dewey championed experiential education, arguing that learning is most effective when it is connected to real-world problems and democratic participation. In Finland, a comprehensive reform of the education system in the 1970s eliminated streaming, reduced standardised testing, and gave teachers substantial professional autonomy. Finnish students consistently rank among the highest performers in international assessments, challenging the assumption that rigorous testing drives achievement.

The digital revolution has introduced new possibilities and challenges. Massive Open Online Courses (MOOCs), introduced around 2012, promised to democratise access to university-level education by offering free courses from elite institutions to anyone with an internet connection. While enrolment numbers were impressive — some courses attracted hundreds of thousands of students — completion rates remained low, typically below ten per cent. This experience highlighted the importance of structured support, social interaction, and accountability in sustaining learning motivation.

More recent developments in educational technology include adaptive learning platforms that use artificial intelligence to personalise instruction, virtual reality simulations that enable immersive experiential learning, and gamification techniques that apply game design elements to educational activities. These innovations hold considerable promise, but their effectiveness depends on thoughtful implementation, adequate teacher training, and equitable access to technology.

The COVID-19 pandemic forced an unprecedented global experiment in remote learning. Schools and universities worldwide shifted to online instruction virtually overnight. The results were mixed: while some students thrived with the flexibility of remote learning, many others — particularly those from disadvantaged backgrounds lacking reliable internet access, quiet study spaces, or parental support — fell significantly behind. The pandemic exposed and exacerbated pre-existing educational inequalities, reinforcing the argument that technology alone cannot solve systemic problems in education.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "The Socratic method is characterised by", options: ["A. memorisation of key texts", "B. questioning and dialogue", "C. physical training and music", "D. standardised testing"], correctAnswer: "B", explanation: "The passage says the Socratic method 'emphasised questioning and dialogue.'" },
        { number: 2, type: "multiple_choice", text: "The University of Bologna was founded in", options: ["A. 1088", "B. 1096", "C. 1200", "D. 1300"], correctAnswer: "A", explanation: "The passage states 'University of Bologna (founded in 1088).'" },
        { number: 3, type: "multiple_choice", text: "Which country's education model emphasised obedience and uniformity?", options: ["A. Finland", "B. France", "C. Prussia", "D. Ancient Greece"], correctAnswer: "C", explanation: "The passage describes the Prussian model as emphasising 'obedience, uniformity, and passive learning.'" },
        { number: 4, type: "multiple_choice", text: "MOOC completion rates were typically", options: ["A. above 50 per cent", "B. around 30 per cent", "C. below 10 per cent", "D. exactly 25 per cent"], correctAnswer: "C", explanation: "The passage says 'completion rates remained low, typically below ten per cent.'" },
        { number: 5, type: "true_false_not_given", text: "In ancient Athens, education was available to all citizens including women.", correctAnswer: "FALSE", explanation: "The passage says education 'was the preserve of free male citizens.'" },
        { number: 6, type: "true_false_not_given", text: "The lecture format originated in medieval European universities.", correctAnswer: "TRUE", explanation: "The passage says the lecture format 'became the dominant instructional method' in medieval universities." },
        { number: 7, type: "true_false_not_given", text: "Finland eliminated standardised testing entirely.", correctAnswer: "NOT GIVEN", explanation: "The passage says Finland 'reduced standardised testing' but not that it was eliminated entirely." },
        { number: 8, type: "true_false_not_given", text: "Maria Montessori believed teachers should primarily lecture to students.", correctAnswer: "FALSE", explanation: "The passage says teachers 'serve as guides rather than lecturers.'" },
        { number: 9, type: "true_false_not_given", text: "The COVID-19 pandemic exposed pre-existing educational inequalities.", correctAnswer: "TRUE", explanation: "The passage directly states this." },
        { number: 10, type: "true_false_not_given", text: "John Dewey advocated for separating education from real-world problems.", correctAnswer: "FALSE", explanation: "The passage says Dewey argued learning is most effective 'when connected to real-world problems.'" },
        { number: 11, type: "true_false_not_given", text: "MOOCs were first introduced around 2012.", correctAnswer: "TRUE", explanation: "The passage states 'introduced around 2012.'" },
        { number: 12, type: "true_false_not_given", text: "Virtual reality is already used in most schools worldwide.", correctAnswer: "NOT GIVEN", explanation: "The passage mentions VR as a recent development but does not claim widespread use." },
        { number: 13, type: "true_false_not_given", text: "Finnish students consistently rank among the highest in international assessments.", correctAnswer: "TRUE", explanation: "The passage directly states this." }
      ]
    },
    {
      title: "Urbanization Patterns",
      text: `A. The movement of populations from rural areas to cities is one of the most significant demographic trends in human history. In 1800, only three per cent of the world's population lived in urban areas. By 2008, that figure had crossed fifty per cent for the first time, and by 2050, the United Nations projects that nearly seventy per cent of humanity will reside in cities. This dramatic shift — urbanisation — has profound implications for economic development, environmental sustainability, public health, and social organisation.

B. The earliest cities emerged in Mesopotamia around 4000 BCE, followed by urban centres in Egypt, the Indus Valley, and China. These ancient cities were typically small by modern standards — the population of Ur at its peak was perhaps 65,000 — but they represented a revolutionary form of social organisation. Cities concentrated population, specialised labour, and political authority in ways that villages could not, enabling the development of writing, monumental architecture, and complex administrative systems.

C. Industrialisation triggered the first wave of mass urbanisation. In Britain, the proportion of the population living in urban areas rose from approximately twenty per cent in 1800 to nearly eighty per cent by 1900. Factories drew workers from the countryside with the promise of wages, and new transportation technologies — railways and tramways — enabled cities to expand geographically. However, rapid urbanisation also created severe problems: overcrowding, inadequate sanitation, air and water pollution, and the spread of infectious diseases like cholera and tuberculosis.

D. The twentieth century saw urbanisation accelerate in the developing world. Cities like São Paulo, Lagos, Mumbai, and Shanghai grew at extraordinary rates, driven by rural-to-urban migration, natural population increase, and the expansion of manufacturing and service economies. By 2023, there were over thirty megacities — metropolitan areas with populations exceeding ten million — compared to just two (New York and Tokyo) in 1950. The growth of these urban agglomerations has been accompanied by the expansion of informal settlements, where millions live without adequate housing, clean water, or sanitation.

E. Urban planners have responded to the challenges of rapid urbanisation with a variety of approaches. The "garden city" movement, pioneered by Ebenezer Howard in 1898, proposed self-contained communities surrounded by green belts, combining the advantages of urban and rural living. Le Corbusier's "Radiant City" concept of the 1930s envisioned high-rise residential towers set in open parkland, separating living, working, and recreational zones. More recently, the "new urbanism" movement has advocated for compact, walkable, mixed-use neighbourhoods that reduce car dependency and promote social interaction.

F. The environmental impact of urbanisation is complex. Cities are responsible for approximately seventy per cent of global carbon dioxide emissions, driven by energy consumption in buildings, transportation, and industry. Urban heat islands — areas where temperatures are significantly higher than surrounding rural areas due to the concentration of heat-absorbing surfaces — exacerbate energy demand for cooling. However, dense urban living can also be more environmentally efficient than suburban sprawl: per capita energy consumption and carbon emissions tend to be lower in compact cities with good public transit than in car-dependent suburbs.

G. The concept of the "smart city" has emerged as a response to contemporary urban challenges. Smart cities use digital technology — sensors, data analytics, and connected infrastructure — to optimise the delivery of services including transportation, energy, water management, and public safety. Barcelona, Singapore, and Copenhagen are frequently cited as examples. Critics, however, warn that smart city initiatives can prioritise technological solutions over citizen participation, exacerbate surveillance, and divert resources from more fundamental problems like affordable housing and social services.

H. The future of urbanisation will be shaped by forces including climate change, demographic ageing, migration, and technological innovation. Cities in low-lying coastal areas face existential threats from rising sea levels. Ageing populations in developed countries will require urban environments adapted to the needs of older residents. Migration — both within and between countries — will continue to drive urban growth in some regions while depopulating others. How cities respond to these challenges will determine the quality of life for the majority of humanity in the coming decades.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Paragraph C", options: ["i. Technology-driven urban management", "ii. The first cities", "iii. Industrialisation and urban growth", "iv. Environmental paradoxes of cities", "v. Urban planning responses", "vi. Megacities and informal settlements", "vii. Uncertain urban futures", "viii. Digital solutions for city problems"], correctAnswer: "iii", explanation: "Paragraph C discusses how industrialisation triggered mass urbanisation in Britain." },
        { number: 15, type: "matching_headings", text: "Paragraph D", options: ["i. Technology-driven urban management", "ii. The first cities", "iii. Industrialisation and urban growth", "iv. Environmental paradoxes of cities", "v. Urban planning responses", "vi. Megacities and informal settlements", "vii. Uncertain urban futures", "viii. Digital solutions for city problems"], correctAnswer: "vi", explanation: "Paragraph D discusses megacities and informal settlements in the developing world." },
        { number: 16, type: "matching_headings", text: "Paragraph F", options: ["i. Technology-driven urban management", "ii. The first cities", "iii. Industrialisation and urban growth", "iv. Environmental paradoxes of cities", "v. Urban planning responses", "vi. Megacities and informal settlements", "vii. Uncertain urban futures", "viii. Digital solutions for city problems"], correctAnswer: "iv", explanation: "Paragraph F discusses both the negative emissions and the efficiency benefits of dense cities." },
        { number: 17, type: "matching_headings", text: "Paragraph G", options: ["i. Technology-driven urban management", "ii. The first cities", "iii. Industrialisation and urban growth", "iv. Environmental paradoxes of cities", "v. Urban planning responses", "vi. Megacities and informal settlements", "vii. Uncertain urban futures", "viii. Digital solutions for city problems"], correctAnswer: "i", explanation: "Paragraph G discusses smart cities using digital technology." },
        { number: 18, type: "summary_completion", text: "In 1800, only ________ per cent of the world's population lived in urban areas.", correctAnswer: "three", explanation: "The passage states 'only three per cent.'" },
        { number: 19, type: "summary_completion", text: "By 2050, the UN projects nearly ________ per cent of humanity will live in cities.", correctAnswer: "seventy", explanation: "The passage says 'nearly seventy per cent.'" },
        { number: 20, type: "summary_completion", text: "Cities produce approximately ________ per cent of global CO2 emissions.", correctAnswer: "seventy", explanation: "The passage states 'approximately seventy per cent of global carbon dioxide emissions.'" },
        { number: 21, type: "summary_completion", text: "By 2023, there were over ________ megacities worldwide.", correctAnswer: "thirty", explanation: "The passage says 'over thirty megacities.'" },
        { number: 22, type: "summary_completion", text: "The garden city movement was pioneered by Ebenezer Howard in ________.", correctAnswer: "1898", explanation: "The passage states 'pioneered by Ebenezer Howard in 1898.'" },
        { number: 23, type: "summary_completion", text: "The population of ancient Ur at its peak was perhaps ________.", correctAnswer: "65,000", explanation: "The passage says 'the population of Ur at its peak was perhaps 65,000.'" },
        { number: 24, type: "summary_completion", text: "In 1950, there were only ________ megacities: New York and Tokyo.", correctAnswer: "two", explanation: "The passage says 'just two (New York and Tokyo) in 1950.'" },
        { number: 25, type: "summary_completion", text: "Le Corbusier's concept envisioned high-rise towers set in open ________.", correctAnswer: "parkland", explanation: "The passage says 'high-rise residential towers set in open parkland.'" },
        { number: 26, type: "summary_completion", text: "Britain's urban population rose from twenty per cent to nearly ________ per cent between 1800 and 1900.", correctAnswer: "eighty", explanation: "The passage states 'nearly eighty per cent by 1900.'" }
      ]
    },
    {
      title: "Climate Change and Agriculture",
      text: `A. Agriculture is both a contributor to and a victim of climate change. The sector accounts for approximately ten to twelve per cent of global greenhouse gas emissions through livestock methane production, rice paddies, synthetic fertiliser use, and land-use changes including deforestation. Simultaneously, agriculture is acutely vulnerable to the effects of a changing climate — rising temperatures, altered precipitation patterns, increased frequency of extreme weather events, and shifting pest and disease distributions all threaten food production systems worldwide.

B. The impact of climate change on crop yields varies by region and crop type. In tropical and subtropical regions, where temperatures are already near the upper limits of crop tolerance, further warming is expected to reduce yields of staple crops including wheat, rice, and maize. A comprehensive meta-analysis published in 2014 estimated that each degree Celsius of warming would reduce global wheat yields by approximately six per cent, rice yields by 3.2 per cent, and maize yields by 7.4 per cent. In contrast, some high-latitude regions may experience modest yield increases as growing seasons lengthen and previously marginal land becomes cultivable.

C. Water availability is a critical mediating factor. Agriculture accounts for approximately seventy per cent of global freshwater withdrawals, and changes in precipitation patterns directly affect irrigation-dependent farming systems. Glacier retreat in mountain regions — the Himalayas, the Andes, and the Alps — threatens the water supply for hundreds of millions of people downstream. Groundwater depletion, already a serious problem in regions like the North China Plain and the Ogallala Aquifer in the United States, is being exacerbated by increasing demand for irrigation in hotter, drier conditions.

D. Extreme weather events pose perhaps the greatest short-term threat to agricultural production. Droughts, floods, heat waves, and storms can devastate crops over large areas within days. The European heat wave of 2003, which killed tens of thousands of people, also reduced crop production by an estimated thirty per cent in affected regions. The increasing frequency and intensity of such events — a well-documented consequence of climate change — makes agricultural planning more difficult and increases the financial risks faced by farmers.

E. Livestock production is particularly sensitive to heat stress. Dairy cows, for example, show reduced milk production when temperatures exceed approximately 25 degrees Celsius. Heat stress also affects animal fertility, growth rates, and susceptibility to disease. The livestock sector faces additional pressures from growing societal concern about its environmental footprint — beef production, in particular, is associated with high levels of methane emissions and land use. These factors are driving interest in alternative protein sources including plant-based meat substitutes and cultured meat grown from animal cells in laboratory settings.

F. Agricultural adaptation strategies encompass both technological and management-based approaches. Crop breeding programmes are developing heat-tolerant and drought-resistant varieties using both conventional breeding techniques and genetic modification. Conservation agriculture — which emphasises minimum soil disturbance, permanent soil cover, and crop rotation — improves soil health and water retention, building resilience to climate variability. Precision agriculture technologies, including GPS-guided machinery, drone-based crop monitoring, and sensor-driven irrigation systems, enable more efficient use of inputs and reduce waste.

G. Agroforestry — the integration of trees into farming systems — offers multiple climate benefits. Trees provide shade that reduces heat stress on crops and livestock, improve soil structure through root networks and leaf litter, and sequester carbon from the atmosphere. In sub-Saharan Africa, the practice of planting nitrogen-fixing trees alongside food crops has been shown to double or triple maize yields while reducing the need for synthetic fertilisers. Agroforestry systems can also provide additional income sources through timber, fruit, and fodder production.

H. The intersection of climate change and agriculture raises profound questions about food security. The United Nations estimates that global food production must increase by approximately sixty per cent by 2050 to feed a projected population of nearly ten billion. Achieving this while simultaneously reducing agriculture's greenhouse gas emissions and adapting to a changing climate represents one of the greatest challenges facing humanity. Solutions will require coordinated action across science, policy, and practice — from developing climate-resilient crop varieties to reforming agricultural subsidies and reducing food waste, which currently accounts for roughly one-third of all food produced globally.`,
      questions: [
        { number: 27, type: "matching_information", text: "The impact of heat on dairy cow productivity", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "E", explanation: "Paragraph E discusses how dairy cows show reduced milk production in heat." },
        { number: 28, type: "matching_information", text: "The benefits of planting trees alongside crops", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "G", explanation: "Paragraph G discusses agroforestry benefits." },
        { number: 29, type: "matching_information", text: "Projected yield reductions per degree of warming", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "B", explanation: "Paragraph B provides the meta-analysis figures." },
        { number: 30, type: "matching_information", text: "The proportion of global freshwater used by agriculture", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "C", explanation: "Paragraph C states agriculture uses 'approximately seventy per cent of global freshwater withdrawals.'" },
        { number: 31, type: "flow_chart_completion", text: "Agriculture accounts for ________ to twelve per cent of global greenhouse gas emissions.", correctAnswer: "ten", explanation: "The passage says 'approximately ten to twelve per cent.'" },
        { number: 32, type: "flow_chart_completion", text: "Each degree of warming reduces global wheat yields by approximately ________ per cent.", correctAnswer: "six", explanation: "The passage states 'approximately six per cent.'" },
        { number: 33, type: "flow_chart_completion", text: "The 2003 European heat wave reduced crop production by an estimated ________ per cent.", correctAnswer: "thirty", explanation: "The passage says 'reduced crop production by an estimated thirty per cent.'" },
        { number: 34, type: "flow_chart_completion", text: "Global food production must increase by approximately ________ per cent by 2050.", correctAnswer: "sixty", explanation: "The passage states 'approximately sixty per cent by 2050.'" },
        { number: 35, type: "short_answer", text: "What proportion of all food produced globally is wasted?", correctAnswer: "one-third", explanation: "The passage says 'roughly one-third of all food produced globally.'" },
        { number: 36, type: "short_answer", text: "What type of agriculture emphasises minimum soil disturbance?", correctAnswer: "conservation agriculture", explanation: "The passage defines conservation agriculture." },
        { number: 37, type: "short_answer", text: "Name two alternative protein sources mentioned in the passage.", correctAnswer: "plant-based meat substitutes and cultured meat", explanation: "The passage mentions both." },
        { number: 38, type: "short_answer", text: "In sub-Saharan Africa, what type of trees are planted alongside food crops?", correctAnswer: "nitrogen-fixing trees", explanation: "The passage says 'planting nitrogen-fixing trees alongside food crops.'" },
        { number: 39, type: "short_answer", text: "What is the projected global population by 2050?", correctAnswer: "ten billion", explanation: "The passage says 'a projected population of nearly ten billion.'" },
        { number: 40, type: "short_answer", text: "At what temperature do dairy cows begin showing reduced milk production?", correctAnswer: "25 degrees Celsius", explanation: "The passage says 'when temperatures exceed approximately 25 degrees Celsius.'" }
      ]
    }
  ]
};
