import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_13: ReadingTest = {
  id: 13,
  passages: [
    {
      title: "Ancient Architecture",
      text: `The architectural achievements of ancient civilisations continue to inspire wonder and admiration thousands of years after their construction. From the pyramids of Egypt to the temples of Greece, the amphitheatres of Rome to the stupas of India, ancient builders demonstrated extraordinary ingenuity, mathematical precision, and artistic vision — often working without the benefit of modern materials, machinery, or engineering theory. Understanding how these structures were designed and built remains one of the most fascinating fields of archaeological and engineering research.

The Great Pyramid of Giza, constructed around 2560 BCE during the reign of Pharaoh Khufu, is perhaps the most iconic example of ancient architectural achievement. Standing 146 metres tall when originally completed, it was the tallest structure in the world for nearly 4,000 years. The pyramid was built from approximately 2.3 million limestone blocks, each weighing an average of 2.5 tonnes, with some granite blocks in the interior chambers weighing up to 80 tonnes. The precision of its construction is remarkable: the base is level to within just 2.1 centimetres across its entire 230-metre length, and the four sides are aligned to the cardinal compass points with an accuracy of less than one-twelfth of a degree. Despite centuries of study, the exact methods used to quarry, transport, and lift these massive stones remain subjects of scholarly debate, though most experts believe that ramps, levers, and a large, well-organised workforce were the primary means.

Greek architecture, which reached its zenith during the fifth century BCE, introduced principles of proportion, symmetry, and aesthetic refinement that have profoundly influenced Western architectural tradition. The Parthenon, built on the Acropolis of Athens between 447 and 432 BCE as a temple dedicated to the goddess Athena, is widely regarded as the finest example of Doric architecture. Its designers, Ictinus and Callicrates, incorporated subtle optical refinements to counteract visual distortions: the columns lean slightly inward, the stylobate (the platform on which the columns stand) curves gently upward at the centre, and the corner columns are slightly thicker than those in the middle. These adjustments, invisible to the casual observer, create an impression of perfect regularity and harmony that has captivated architects and artists for over two millennia.

Roman architecture built upon Greek foundations but introduced revolutionary structural innovations that vastly expanded the scale and complexity of what could be built. The Romans perfected the use of the arch, the vault, and the dome — structural forms that distribute weight more efficiently than the flat lintels used by the Greeks — and developed concrete (opus caementicium), a building material of extraordinary versatility and strength. The Pantheon, completed around 125 CE under Emperor Hadrian, showcases Roman engineering at its most ambitious: its unreinforced concrete dome, spanning 43.3 metres, remained the largest dome in the world for over 1,300 years and continues to be the largest unreinforced concrete dome ever built. The Colosseum, completed in 80 CE, could seat over 50,000 spectators and featured a sophisticated system of underground tunnels, mechanical lifts, and retractable awnings that demonstrated the Romans' mastery of logistics and engineering.

In South and Southeast Asia, ancient architects created structures of great complexity and spiritual significance. The temple complex of Angkor Wat in Cambodia, built in the early twelfth century by King Suryavarman II, is the largest religious monument in the world, covering an area of approximately 162 hectares. Originally dedicated to the Hindu god Vishnu, it was later converted to a Buddhist temple. Angkor Wat's design represents a symbolic model of the Hindu universe, with the central tower representing Mount Meru, the home of the gods, surrounded by concentric galleries and a vast moat symbolising the cosmic ocean. The temple's sandstone walls are covered with over 1,200 square metres of intricate bas-relief carvings depicting mythological scenes and historical events.

The architectural legacy of ancient civilisations extends far beyond individual monuments. Ancient builders developed techniques and principles — load distribution, material science, hydraulic engineering, modular construction, and aesthetic proportion — that continue to inform architectural practice today. The study of ancient architecture also provides invaluable insights into the social organisation, religious beliefs, economic resources, and technological capabilities of the civilisations that produced these extraordinary structures.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "The Great Pyramid of Giza was the tallest structure in the world for approximately", options: ["A 1,000 years.", "B 2,000 years.", "C 4,000 years.", "D 5,000 years."], correctAnswer: "C", explanation: "The passage states it was the tallest 'for nearly 4,000 years.'" },
        { number: 2, type: "multiple_choice", text: "The alignment of the Great Pyramid's sides to compass points is accurate to within", options: ["A one degree.", "B one-twelfth of a degree.", "C one-hundredth of a degree.", "D ten degrees."], correctAnswer: "B", explanation: "The passage says 'with an accuracy of less than one-twelfth of a degree.'" },
        { number: 3, type: "multiple_choice", text: "The optical refinements in the Parthenon were designed to", options: ["A make the building appear larger than it was.", "B compensate for visual distortions.", "C demonstrate Greek mathematical superiority.", "D reduce construction costs."], correctAnswer: "B", explanation: "The passage says designers 'incorporated subtle optical refinements to counteract visual distortions.'" },
        { number: 4, type: "multiple_choice", text: "The Romans' key structural innovation compared to the Greeks was", options: ["A the use of marble columns.", "B the development of flat lintels.", "C the perfection of arches, vaults, and domes.", "D the introduction of wooden roof frames."], correctAnswer: "C", explanation: "The passage says Romans 'perfected the use of the arch, the vault, and the dome.'" },
        { number: 5, type: "multiple_choice", text: "Angkor Wat's central tower symbolises", options: ["A the power of the Khmer Empire.", "B the cosmic ocean.", "C Mount Meru, home of the gods.", "D the Buddha's path to enlightenment."], correctAnswer: "C", explanation: "The passage states 'the central tower representing Mount Meru, the home of the gods.'" },
        { number: 6, type: "sentence_completion", text: "The Great Pyramid was built from approximately _______ million limestone blocks.", correctAnswer: "2.3", explanation: "The passage says 'approximately 2.3 million limestone blocks.'" },
        { number: 7, type: "sentence_completion", text: "Each limestone block weighed an average of _______ tonnes.", correctAnswer: "2.5", explanation: "The passage states 'each weighing an average of 2.5 tonnes.'" },
        { number: 8, type: "sentence_completion", text: "The Parthenon was built between 447 and _______ BCE.", correctAnswer: "432", explanation: "The passage says 'built on the Acropolis of Athens between 447 and 432 BCE.'" },
        { number: 9, type: "sentence_completion", text: "The Pantheon's dome spans _______ metres.", correctAnswer: "43.3", explanation: "The passage states 'spanning 43.3 metres.'" },
        { number: 10, type: "sentence_completion", text: "The Colosseum could seat over _______ spectators.", correctAnswer: "50,000", explanation: "The passage says 'could seat over 50,000 spectators.'" },
        { number: 11, type: "sentence_completion", text: "Angkor Wat covers an area of approximately _______ hectares.", correctAnswer: "162", explanation: "The passage states 'covering an area of approximately 162 hectares.'" },
        { number: 12, type: "sentence_completion", text: "Angkor Wat was originally dedicated to the Hindu god _______.", correctAnswer: "Vishnu", explanation: "The passage says 'Originally dedicated to the Hindu god Vishnu.'" },
        { number: 13, type: "sentence_completion", text: "The walls of Angkor Wat have over _______ square metres of bas-relief carvings.", correctAnswer: "1,200", explanation: "The passage states 'over 1,200 square metres of intricate bas-relief carvings.'" },
      ],
    },
    {
      title: "Ocean Pollution",
      text: `A. The world's oceans, covering approximately 71 percent of the Earth's surface and containing 97 percent of all water on the planet, are under unprecedented pressure from human activities. Ocean pollution — the introduction of harmful substances and energy into marine environments — has escalated dramatically over the past century, threatening marine ecosystems, biodiversity, human health, and the livelihoods of hundreds of millions of people who depend on the sea for food and income.

B. Plastic pollution has become the most visible and widely discussed form of ocean contamination. An estimated 8 to 12 million tonnes of plastic waste enter the oceans every year, a figure equivalent to dumping a truckload of plastic into the sea every minute. Once in the ocean, plastic debris can persist for hundreds of years, gradually breaking down into ever-smaller fragments known as microplastics — particles less than 5 millimetres in diameter. Microplastics have been found in every part of the marine environment, from surface waters to the deepest ocean trenches, and in the bodies of organisms ranging from zooplankton to whales. Recent research has detected microplastics in human blood, breast milk, and lung tissue, raising concerns about potential health effects that are not yet fully understood.

C. Chemical pollution of the oceans takes many forms. Agricultural runoff carrying synthetic fertilisers, particularly nitrogen and phosphorus, is a major cause of eutrophication — the excessive enrichment of water with nutrients, which stimulates algal blooms that deplete oxygen levels and create so-called "dead zones" where most marine life cannot survive. The number of oceanic dead zones has doubled approximately every decade since the 1960s, with over 700 identified worldwide. Industrial discharges introduce heavy metals such as mercury, lead, and cadmium into marine environments, where they accumulate in the food chain through a process called bioaccumulation, reaching their highest concentrations in top predators such as tuna, swordfish, and marine mammals. Oil spills, while dramatic and devastating when they occur, actually represent a relatively small proportion of total oil entering the oceans; chronic sources such as urban runoff, shipping operations, and natural seepage account for the majority.

D. Noise pollution is an often-overlooked but increasingly serious threat to marine life. The underwater environment, which marine animals have evolved to navigate using sound, has become significantly noisier over the past century due to shipping traffic, seismic surveys for oil and gas exploration, military sonar exercises, and offshore construction activities. Ambient ocean noise levels have doubled roughly every decade since the 1960s. Noise pollution can cause physiological stress, behavioural changes, hearing damage, and in extreme cases mass strandings in marine mammals such as whales and dolphins, which rely on echolocation and vocalisations for navigation, foraging, and communication. Fish and invertebrates are also affected: studies have shown that noise can disrupt the settlement behaviour of coral reef fish larvae and reduce the feeding rates of crabs.

E. The impact of ocean pollution on marine ecosystems is compounded by its interaction with other environmental stressors, particularly climate change and ocean acidification. Warmer ocean temperatures reduce the ability of water to hold dissolved oxygen, exacerbating dead zones and stressing temperature-sensitive organisms such as corals. Ocean acidification — caused by the absorption of excess atmospheric CO2 — weakens the shells and skeletons of molluscs, crustaceans, and reef-building corals, making them more vulnerable to pollution-related damage. The cumulative effect of multiple stressors acting simultaneously is often greater than the sum of their individual impacts, a phenomenon known as synergistic interaction.

F. Addressing ocean pollution requires coordinated action at local, national, and international levels. The United Nations Environment Programme (UNEP) has identified ocean pollution as a priority issue, and several international agreements — including the London Convention on ocean dumping, the MARPOL Convention on ship-generated pollution, and the recently negotiated Global Plastics Treaty — provide frameworks for regulation and enforcement. At the national level, policies to reduce single-use plastics, improve wastewater treatment, regulate agricultural runoff, and designate marine protected areas are being implemented with varying degrees of success. Technological innovations, including ocean cleanup devices, biodegradable packaging materials, and advanced wastewater treatment systems, offer promising solutions, but ultimately reducing ocean pollution will require fundamental changes in production and consumption patterns across the global economy.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Paragraph B", options: ["i. The underwater sound crisis", "ii. International and national responses to ocean pollution", "iii. The scale of plastic contamination in the seas", "iv. Combined effects of pollution and climate change", "v. Chemical contaminants and their accumulation", "vi. The overall threat to marine environments", "vii. Sources of heavy metal contamination only", "viii. Micro-sized particles in human tissues"], correctAnswer: "iii", explanation: "Paragraph B focuses on plastic pollution statistics, microplastics distribution, and their presence throughout the ocean." },
        { number: 15, type: "matching_headings", text: "Paragraph C", options: ["i. The underwater sound crisis", "ii. International and national responses to ocean pollution", "iii. The scale of plastic contamination in the seas", "iv. Combined effects of pollution and climate change", "v. Chemical contaminants and their accumulation", "vi. The overall threat to marine environments", "vii. Sources of heavy metal contamination only", "viii. Micro-sized particles in human tissues"], correctAnswer: "v", explanation: "Paragraph C discusses fertiliser runoff, eutrophication, heavy metals, bioaccumulation, and oil." },
        { number: 16, type: "matching_headings", text: "Paragraph D", options: ["i. The underwater sound crisis", "ii. International and national responses to ocean pollution", "iii. The scale of plastic contamination in the seas", "iv. Combined effects of pollution and climate change", "v. Chemical contaminants and their accumulation", "vi. The overall threat to marine environments", "vii. Sources of heavy metal contamination only", "viii. Micro-sized particles in human tissues"], correctAnswer: "i", explanation: "Paragraph D discusses noise from shipping, sonar, and construction affecting marine animals." },
        { number: 17, type: "matching_headings", text: "Paragraph E", options: ["i. The underwater sound crisis", "ii. International and national responses to ocean pollution", "iii. The scale of plastic contamination in the seas", "iv. Combined effects of pollution and climate change", "v. Chemical contaminants and their accumulation", "vi. The overall threat to marine environments", "vii. Sources of heavy metal contamination only", "viii. Micro-sized particles in human tissues"], correctAnswer: "iv", explanation: "Paragraph E discusses how pollution interacts with climate change and ocean acidification — synergistic effects." },
        { number: 18, type: "matching_headings", text: "Paragraph F", options: ["i. The underwater sound crisis", "ii. International and national responses to ocean pollution", "iii. The scale of plastic contamination in the seas", "iv. Combined effects of pollution and climate change", "v. Chemical contaminants and their accumulation", "vi. The overall threat to marine environments", "vii. Sources of heavy metal contamination only", "viii. Micro-sized particles in human tissues"], correctAnswer: "ii", explanation: "Paragraph F discusses UNEP, international conventions, national policies, and technological solutions." },
        { number: 19, type: "table_completion", text: "An estimated _______ to 12 million tonnes of plastic enter the oceans annually.", correctAnswer: "8", explanation: "The passage says 'An estimated 8 to 12 million tonnes.'" },
        { number: 20, type: "table_completion", text: "Microplastics are defined as particles less than _______ millimetres in diameter.", correctAnswer: "5", explanation: "The passage defines microplastics as 'particles less than 5 millimetres.'" },
        { number: 21, type: "table_completion", text: "Over _______ oceanic dead zones have been identified worldwide.", correctAnswer: "700", explanation: "The passage states 'over 700 identified worldwide.'" },
        { number: 22, type: "table_completion", text: "Ambient ocean noise levels have doubled roughly every _______ since the 1960s.", correctAnswer: "decade", explanation: "The passage says noise levels 'have doubled roughly every decade since the 1960s.'" },
        { number: 23, type: "table_completion", text: "The process by which heavy metals reach high concentrations in top predators is called _______.", correctAnswer: "bioaccumulation", explanation: "The passage describes 'a process called bioaccumulation.'" },
        { number: 24, type: "table_completion", text: "The phenomenon where multiple stressors produce effects greater than their sum is called _______ interaction.", correctAnswer: "synergistic", explanation: "The passage defines this as 'synergistic interaction.'" },
        { number: 25, type: "table_completion", text: "Oceans cover approximately _______ percent of the Earth's surface.", correctAnswer: "71", explanation: "The passage states 'covering approximately 71 percent of the Earth's surface.'" },
        { number: 26, type: "table_completion", text: "Oceans contain _______ percent of all water on the planet.", correctAnswer: "97", explanation: "The passage says 'containing 97 percent of all water.'" },
      ],
    },
    {
      title: "The Future of Transportation",
      text: `Transportation systems are on the brink of a revolution that promises to be as transformative as the shift from horse-drawn carriages to automobiles over a century ago. Advances in electrification, autonomous driving, shared mobility, and hyperloop technology are converging to reshape how people and goods move within and between cities, with profound implications for urban planning, energy consumption, environmental sustainability, and economic productivity.

A. Electric vehicles (EVs) are at the forefront of the transportation transformation. Global EV sales exceeded 10 million units in 2022, representing approximately 14 percent of all new car sales, up from just 1 percent five years earlier. This rapid growth has been driven by falling battery costs, government incentives, tightening emissions regulations, and growing consumer awareness of environmental issues. China leads the global EV market, accounting for nearly 60 percent of worldwide sales, followed by Europe and the United States. The transition from internal combustion engines to electric drivetrains is not limited to passenger cars: electric buses are being deployed in cities around the world, electric trucks are entering commercial service, and electric aircraft prototypes are undergoing flight testing. The International Energy Agency (IEA) projects that EVs could account for over 60 percent of new car sales globally by 2030 under current policy trajectories.

B. Autonomous vehicle (AV) technology — the development of cars, trucks, and buses capable of driving themselves without human intervention — represents another potentially disruptive force in transportation. AV technology relies on a combination of sensors (including cameras, lidar, and radar), detailed digital maps, and AI algorithms that enable vehicles to perceive their surroundings, predict the behaviour of other road users, and make real-time driving decisions. Companies including Waymo, Cruise, and Baidu have launched commercial autonomous taxi (robotaxi) services in select cities, though these operations remain geographically limited and subject to regulatory restrictions. The Society of Automotive Engineers (SAE) defines six levels of driving automation, from Level 0 (no automation) to Level 5 (full automation in all conditions). Most commercially available vehicles with autonomous features currently operate at Level 2 or 3, and the timeline for widespread Level 5 autonomy remains uncertain and heavily debated.

C. Shared mobility services — including ride-hailing (Uber, Lyft, Didi), car-sharing, bike-sharing, and e-scooter rental — are reshaping urban transportation by offering alternatives to private car ownership. Proponents argue that shared mobility, particularly when combined with electrification and autonomy, could dramatically reduce the number of vehicles on city streets, decrease traffic congestion, lower emissions, and free up the vast amounts of urban land currently devoted to parking. Studies suggest that a single shared autonomous vehicle could replace between 5 and 15 privately owned cars, depending on the density and design of the service network. However, critics note that in practice, ride-hailing services have in some cities increased overall vehicle kilometres travelled and added to congestion, particularly when they attract riders away from public transport rather than from private cars.

D. Hyperloop technology, first proposed by Elon Musk in 2013, envisions passenger pods travelling through near-vacuum tubes at speeds of up to 1,200 kilometres per hour — faster than commercial aircraft. The low-pressure environment within the tube would virtually eliminate air resistance, while magnetic levitation or air bearings would eliminate friction between the pod and the track, enabling extremely high speeds with relatively low energy consumption. Several companies, including Virgin Hyperloop and Hyperloop Transportation Technologies (HTT), have conducted prototype testing and feasibility studies, though no commercial hyperloop system has yet been built. Proponents argue that hyperloop could connect cities separated by hundreds of kilometres in minutes, transforming regional economies and reducing the need for short-haul air travel. Sceptics question whether the technology can be made safe, affordable, and scalable, noting the enormous infrastructure costs and engineering challenges involved in constructing and maintaining hundreds of kilometres of sealed, evacuated tubes.

E. Urban air mobility (UAM) — the use of electric vertical take-off and landing (eVTOL) aircraft for passenger transport within and between cities — is another emerging transportation concept that has attracted billions of dollars in investment. Companies including Joby Aviation, Lilium, and Archer Aviation are developing eVTOL aircraft designed to carry between two and six passengers over distances of 50 to 250 kilometres at speeds of 200 to 300 kilometres per hour. These aircraft, often described as "flying taxis" or "air taxis," would operate from rooftop vertiports and ground-level landing pads, bypassing surface-level traffic congestion entirely. The first commercial UAM services are expected to launch in the mid-2020s, with Dubai, Los Angeles, and Singapore among the cities positioning themselves as early adopters. However, significant challenges remain, including air traffic management, noise regulations, safety certification, public acceptance, and the need to develop the physical infrastructure — vertiports, charging stations, and maintenance facilities — required to support large-scale operations.

F. The convergence of these technologies — electrification, autonomy, sharing, and new transport modes — has the potential to create a fundamentally different transportation system from the one that exists today. The concept of "Mobility as a Service" (MaaS), which integrates multiple transport options into a single digital platform, enabling users to plan, book, and pay for door-to-door journeys combining trains, buses, ride-hailing, bikes, and scooters, is already being piloted in cities such as Helsinki, Vienna, and Singapore. If realised at scale, MaaS could reduce private car ownership, improve transport efficiency, and make urban mobility more accessible and equitable. However, achieving this vision will require not only continued technological progress but also supportive regulation, public investment in infrastructure, and thoughtful planning to ensure that the benefits of the transportation revolution are shared broadly across society.`,
      questions: [
        { number: 27, type: "matching_information", text: "A digital platform that combines multiple forms of transport into one journey", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "F", explanation: "Paragraph F describes 'Mobility as a Service (MaaS)' integrating multiple transport options." },
        { number: 28, type: "matching_information", text: "The concern that ride-hailing may actually worsen traffic conditions", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "C", explanation: "Paragraph C notes ride-hailing 'in some cities increased overall vehicle kilometres travelled and added to congestion.'" },
        { number: 29, type: "matching_information", text: "Aircraft designed to take off and land vertically in urban areas", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "E", explanation: "Paragraph E describes eVTOL aircraft for urban air mobility." },
        { number: 30, type: "matching_information", text: "A classification system with six levels of driving automation", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "B", explanation: "Paragraph B mentions the SAE's 'six levels of driving automation, from Level 0 to Level 5.'" },
        { number: 31, type: "matching_information", text: "Transport pods that would travel in near-vacuum conditions", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "D", explanation: "Paragraph D describes hyperloop pods 'travelling through near-vacuum tubes.'" },
        { number: 32, type: "multiple_choice", text: "Global EV sales in 2022 represented approximately", options: ["A 1 percent of new car sales.", "B 10 percent of new car sales.", "C 14 percent of new car sales.", "D 60 percent of new car sales."], correctAnswer: "C", explanation: "The passage states 'approximately 14 percent of all new car sales.'" },
        { number: 33, type: "multiple_choice", text: "A single shared autonomous vehicle could potentially replace", options: ["A 2 to 5 privately owned cars.", "B 5 to 15 privately owned cars.", "C 15 to 30 privately owned cars.", "D over 50 privately owned cars."], correctAnswer: "B", explanation: "The passage says 'could replace between 5 and 15 privately owned cars.'" },
        { number: 34, type: "multiple_choice", text: "Hyperloop pods are proposed to travel at up to", options: ["A 500 kilometres per hour.", "B 800 kilometres per hour.", "C 1,200 kilometres per hour.", "D 2,000 kilometres per hour."], correctAnswer: "C", explanation: "The passage states 'speeds of up to 1,200 kilometres per hour.'" },
        { number: 35, type: "short_answer", text: "Which country accounts for nearly 60 percent of global EV sales?", correctAnswer: "China", explanation: "The passage says 'China leads the global EV market, accounting for nearly 60 percent.'" },
        { number: 36, type: "short_answer", text: "What three sensor types do autonomous vehicles use?", correctAnswer: "cameras, lidar, and radar", explanation: "The passage lists 'cameras, lidar, and radar.'" },
        { number: 37, type: "short_answer", text: "In what year was the hyperloop concept first proposed?", correctAnswer: "2013", explanation: "The passage states 'first proposed by Elon Musk in 2013.'" },
        { number: 38, type: "short_answer", text: "How many passengers are eVTOL aircraft designed to carry?", correctAnswer: "two to six", explanation: "The passage says 'carry between two and six passengers.'" },
        { number: 39, type: "short_answer", text: "What does the abbreviation MaaS stand for?", correctAnswer: "Mobility as a Service", explanation: "The passage defines it as 'Mobility as a Service.'" },
        { number: 40, type: "short_answer", text: "Name one city where MaaS is already being piloted.", correctAnswer: "Helsinki", explanation: "The passage lists 'Helsinki, Vienna, and Singapore.' Any one is acceptable." },
      ],
    },
  ],
};
