import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_14: ReadingTest = {
  id: 14,
  passages: [
    {
      title: "The Development of Maps",
      text: `Maps are among the most ancient and enduring tools of human civilisation. Long before written language became widespread, humans drew representations of their surroundings on cave walls, clay tablets, and animal skins, seeking to record, communicate, and make sense of the spatial world around them. The history of cartography — the science and art of map-making — is a story of evolving technologies, changing worldviews, and the persistent human desire to understand and control geographical space.

The oldest known maps date back to approximately 2300 BCE. A clay tablet discovered in the ruins of the ancient Babylonian city of Ga-Sur (modern Yorghan Tepe in Iraq) depicts a river valley flanked by mountains, with cardinal directions indicated by inscribed circles. The Babylonians also produced the earliest known world map — the Imago Mundi — around 600 BCE, which depicted Babylon at the centre of a flat, circular Earth surrounded by an ocean and mysterious islands at the edges. While geographically inaccurate by modern standards, these early maps reveal sophisticated spatial thinking and a desire to represent the known world in a systematic way.

Greek scholars made profound contributions to cartography by applying mathematical and astronomical principles to map-making. Eratosthenes of Cyrene, working in the third century BCE, calculated the circumference of the Earth with remarkable accuracy — his estimate of approximately 40,000 kilometres was within two percent of the true value. He also introduced a system of latitude and longitude lines, creating a grid that enabled positions to be described with mathematical precision. Claudius Ptolemy, working in Alexandria in the second century CE, compiled his Geography (Geographia), a monumental work that included instructions for constructing map projections and coordinates for some 8,000 locations. Ptolemy's work, though it contained significant errors — most notably his underestimation of the Earth's circumference, which centuries later encouraged Columbus to believe that Asia could be reached by sailing westward — remained the most influential cartographic reference in Europe for over a thousand years.

During the medieval period in Europe, cartography was heavily influenced by religious cosmology. Mappa mundi — large, ornate world maps produced in monasteries — depicted Jerusalem at the centre of the world, with Asia at the top, Europe at the bottom left, and Africa at the bottom right. These maps were not intended as practical navigation aids but rather as visual encyclopaedias of biblical history, mythology, and geographical knowledge. The most famous surviving example, the Hereford Mappa Mundi (circa 1300), measures 1.58 metres by 1.33 metres and contains over 500 illustrations of cities, biblical events, plants, animals, and mythical creatures.

The Age of Exploration in the fifteenth and sixteenth centuries transformed cartography from a largely theoretical and artistic endeavour into a practical science driven by the needs of navigation and commerce. Portuguese and Spanish navigators charted the coastlines of Africa, Asia, and the Americas with increasing accuracy, and their observations were compiled into increasingly detailed sea charts known as portolan charts. The Flemish cartographer Gerardus Mercator introduced his famous projection in 1569, which represented the curved surface of the Earth on a flat sheet by progressively stretching latitudes away from the equator. The Mercator projection distorts the relative size of landmasses — making Greenland appear as large as Africa, for example — but it preserves angular relationships, making it invaluable for maritime navigation because a straight line on a Mercator map corresponds to a constant compass bearing.

The nineteenth and twentieth centuries saw the development of systematic national surveys, aerial photography, and eventually satellite remote sensing, which revolutionised the accuracy and scope of cartographic data. The launch of Landsat 1 in 1972 inaugurated the era of continuous satellite observation of the Earth's surface, providing detailed imagery that could be used for mapping, environmental monitoring, agriculture, and urban planning. The Global Positioning System (GPS), originally developed for military purposes in the 1970s and made available to civilians in the 1980s, enabled precise location determination anywhere on Earth, transforming not only cartography but also transportation, logistics, and personal navigation.

Today, digital mapping platforms such as Google Maps and OpenStreetMap have democratised access to geographical information on an unprecedented scale. Billions of people carry detailed, interactive maps in their pockets, capable of providing real-time navigation, traffic updates, satellite imagery, and street-level photography. Geographic Information Systems (GIS) enable the layering and analysis of multiple spatial datasets, supporting decision-making in fields as diverse as public health, disaster response, environmental conservation, and commercial real estate. The evolution of maps from clay tablets to satellite-powered digital platforms reflects not only advances in technology but also the enduring centrality of spatial thinking in human civilisation.`,
      questions: [
        { number: 1, type: "true_false_not_given", text: "The oldest known maps are approximately 4,000 years old.", correctAnswer: "TRUE", explanation: "The passage says maps date 'back to approximately 2300 BCE,' which is roughly 4,300 years ago — approximately 4,000." },
        { number: 2, type: "true_false_not_given", text: "The Babylonian Imago Mundi accurately represented the shape of the Earth.", correctAnswer: "FALSE", explanation: "The passage says it depicted 'a flat, circular Earth' and was 'geographically inaccurate by modern standards.'" },
        { number: 3, type: "true_false_not_given", text: "Eratosthenes' calculation of the Earth's circumference was within five percent of the true value.", correctAnswer: "FALSE", explanation: "The passage states it was 'within two percent of the true value,' which is more accurate than five percent." },
        { number: 4, type: "true_false_not_given", text: "Ptolemy's Geography contained coordinates for over 10,000 locations.", correctAnswer: "FALSE", explanation: "The passage says 'coordinates for some 8,000 locations,' not over 10,000." },
        { number: 5, type: "true_false_not_given", text: "Columbus used Ptolemy's underestimation of the Earth's size to justify his voyage.", correctAnswer: "TRUE", explanation: "The passage says Ptolemy's underestimation 'encouraged Columbus to believe that Asia could be reached by sailing westward.'" },
        { number: 6, type: "true_false_not_given", text: "The Hereford Mappa Mundi is kept in a museum in London.", correctAnswer: "NOT GIVEN", explanation: "The passage describes the map but does not specify its current location." },
        { number: 7, type: "true_false_not_given", text: "GPS was initially developed for civilian use.", correctAnswer: "FALSE", explanation: "The passage says GPS was 'originally developed for military purposes.'" },
        { number: 8, type: "sentence_completion", text: "The Babylonian world map depicted _______ at the centre of the Earth.", correctAnswer: "Babylon", explanation: "The passage says it 'depicted Babylon at the centre.'" },
        { number: 9, type: "sentence_completion", text: "Eratosthenes estimated the Earth's circumference at approximately _______ kilometres.", correctAnswer: "40,000", explanation: "The passage says 'approximately 40,000 kilometres.'" },
        { number: 10, type: "sentence_completion", text: "Medieval mappa mundi placed _______ at the centre of the world.", correctAnswer: "Jerusalem", explanation: "The passage says 'depicted Jerusalem at the centre of the world.'" },
        { number: 11, type: "sentence_completion", text: "The Mercator projection was introduced in _______.", correctAnswer: "1569", explanation: "The passage states 'introduced his famous projection in 1569.'" },
        { number: 12, type: "sentence_completion", text: "The first Landsat satellite was launched in _______.", correctAnswer: "1972", explanation: "The passage says 'The launch of Landsat 1 in 1972.'" },
        { number: 13, type: "sentence_completion", text: "The Hereford Mappa Mundi measures 1.58 metres by _______ metres.", correctAnswer: "1.33", explanation: "The passage states 'measures 1.58 metres by 1.33 metres.'" },
      ],
    },
    {
      title: "Desert Ecosystems",
      text: `A. Deserts are among the most extreme environments on Earth, characterised by very low precipitation — typically less than 250 millimetres per year — and wide temperature fluctuations that can range from scorching daytime highs of over 50 degrees Celsius to near-freezing conditions at night. Despite their harsh conditions, deserts are far from lifeless. They support a remarkable diversity of specially adapted plants, animals, and microorganisms, and play important roles in global climate regulation, carbon cycling, and the livelihoods of millions of people.

B. Deserts cover approximately one-third of the Earth's land surface, making them the largest terrestrial biome. They are classified into four main types based on the primary cause of their aridity. Subtropical deserts, such as the Sahara and the Arabian Desert, form in zones of high atmospheric pressure around 30 degrees latitude, where descending dry air suppresses cloud formation and rainfall. Rain shadow deserts, such as the Gobi Desert in Mongolia, occur on the leeward side of mountain ranges that block moisture-laden winds. Coastal deserts, like the Atacama in Chile — the driest desert on Earth, with some weather stations recording no rainfall for decades — are formed when cold ocean currents cool the air, reducing its capacity to hold moisture. Polar deserts, including parts of Antarctica and the Arctic, receive very little precipitation despite being extremely cold, because the air is too cold to hold significant moisture.

C. The plants and animals that inhabit deserts have evolved an extraordinary range of adaptations to survive in conditions of extreme heat, aridity, and nutrient scarcity. Many desert plants, such as cacti and succulents, store water in specialised tissues, while others have developed deep root systems that can reach underground water sources tens of metres below the surface. Xerophytic plants reduce water loss through features such as small or waxy leaves, sunken stomata, and the ability to photosynthesise using CAM (Crassulacean Acid Metabolism) — a process that allows them to open their stomata at night, when temperatures are lower and humidity is higher, rather than during the day. Desert animals have evolved behavioural and physiological adaptations including nocturnality (being active at night to avoid daytime heat), burrowing, estivation (entering a dormant state during hot, dry periods), and highly efficient kidneys that produce concentrated urine, minimising water loss.

D. The soils of desert ecosystems, though often dismissed as barren, contain a hidden world of biological activity. Biological soil crusts — thin layers of cyanobacteria, algae, fungi, lichens, and mosses that form on the soil surface — play a critical ecological role in many desert environments. These crusts stabilise the soil against wind and water erosion, fix atmospheric nitrogen, contribute organic carbon, and influence water infiltration. In some desert ecosystems, biological soil crusts can take decades or even centuries to develop fully, and they are highly vulnerable to disturbance from livestock grazing, off-road vehicles, and human foot traffic. The destruction of biological soil crusts can trigger accelerated soil erosion and desertification, with consequences that may be irreversible on human timescales.

E. Deserts are increasingly recognised for their potential role in renewable energy production. The vast, sparsely populated areas of desert receive some of the highest levels of solar radiation on Earth, making them ideal locations for large-scale solar energy installations. The Sahara alone receives enough solar energy in approximately six hours to meet the world's electricity needs for an entire year. Several major solar energy projects have been developed in desert regions, including the Noor-Ouarzazate solar complex in Morocco — one of the world's largest concentrated solar power (CSP) plants — and extensive photovoltaic installations in the deserts of China, India, and the southwestern United States. However, large-scale desert solar projects also raise environmental concerns, including habitat disruption, water use for panel cleaning, and the potential alteration of local climate patterns through changes in surface reflectivity (albedo).

F. Desertification — the degradation of drylands caused by climate change, unsustainable agriculture, overgrazing, and deforestation — is one of the most serious environmental threats facing the world today. The United Nations Convention to Combat Desertification (UNCCD) estimates that approximately 12 million hectares of productive land are lost to desertification every year, affecting the livelihoods of over 1.5 billion people, predominantly in Africa and Asia. The Great Green Wall initiative, launched by the African Union in 2007, aims to combat desertification across the Sahel region by restoring 100 million hectares of degraded land through tree planting, sustainable agriculture, and community development. As of 2023, approximately 18 million hectares have been restored, demonstrating that with sustained effort, the process of desertification can be slowed and even reversed.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Paragraph B", options: ["i. Renewable energy potential of desert regions", "ii. Types and geographical distribution of deserts", "iii. The threat of land degradation in dry areas", "iv. Survival strategies of desert organisms", "v. The hidden biology of desert soils", "vi. Defining characteristics of desert environments", "vii. Water conservation techniques in desert agriculture", "viii. Human settlement patterns in arid regions"], correctAnswer: "ii", explanation: "Paragraph B classifies deserts into four types — subtropical, rain shadow, coastal, and polar." },
        { number: 15, type: "matching_headings", text: "Paragraph C", options: ["i. Renewable energy potential of desert regions", "ii. Types and geographical distribution of deserts", "iii. The threat of land degradation in dry areas", "iv. Survival strategies of desert organisms", "v. The hidden biology of desert soils", "vi. Defining characteristics of desert environments", "vii. Water conservation techniques in desert agriculture", "viii. Human settlement patterns in arid regions"], correctAnswer: "iv", explanation: "Paragraph C describes plant and animal adaptations including water storage, CAM, nocturnality, and burrowing." },
        { number: 16, type: "matching_headings", text: "Paragraph D", options: ["i. Renewable energy potential of desert regions", "ii. Types and geographical distribution of deserts", "iii. The threat of land degradation in dry areas", "iv. Survival strategies of desert organisms", "v. The hidden biology of desert soils", "vi. Defining characteristics of desert environments", "vii. Water conservation techniques in desert agriculture", "viii. Human settlement patterns in arid regions"], correctAnswer: "v", explanation: "Paragraph D describes biological soil crusts and their ecological functions." },
        { number: 17, type: "matching_headings", text: "Paragraph E", options: ["i. Renewable energy potential of desert regions", "ii. Types and geographical distribution of deserts", "iii. The threat of land degradation in dry areas", "iv. Survival strategies of desert organisms", "v. The hidden biology of desert soils", "vi. Defining characteristics of desert environments", "vii. Water conservation techniques in desert agriculture", "viii. Human settlement patterns in arid regions"], correctAnswer: "i", explanation: "Paragraph E discusses solar energy potential and major solar installations in deserts." },
        { number: 18, type: "matching_headings", text: "Paragraph F", options: ["i. Renewable energy potential of desert regions", "ii. Types and geographical distribution of deserts", "iii. The threat of land degradation in dry areas", "iv. Survival strategies of desert organisms", "v. The hidden biology of desert soils", "vi. Defining characteristics of desert environments", "vii. Water conservation techniques in desert agriculture", "viii. Human settlement patterns in arid regions"], correctAnswer: "iii", explanation: "Paragraph F discusses desertification, land loss, and the Great Green Wall initiative." },
        { number: 19, type: "summary_completion", text: "Deserts receive less than _______ millimetres of precipitation per year.", correctAnswer: "250", explanation: "The passage states 'typically less than 250 millimetres per year.'" },
        { number: 20, type: "summary_completion", text: "Deserts cover approximately one-_______ of the Earth's land surface.", correctAnswer: "third", explanation: "The passage says 'approximately one-third of the Earth's land surface.'" },
        { number: 21, type: "summary_completion", text: "The Atacama is the _______ desert on Earth.", correctAnswer: "driest", explanation: "The passage describes it as 'the driest desert on Earth.'" },
        { number: 22, type: "summary_completion", text: "CAM photosynthesis allows plants to open their stomata at _______ instead of during the day.", correctAnswer: "night", explanation: "The passage says CAM allows plants to 'open their stomata at night.'" },
        { number: 23, type: "summary_completion", text: "Approximately _______ million hectares of productive land are lost to desertification annually.", correctAnswer: "12", explanation: "The passage states 'approximately 12 million hectares.'" },
        { number: 24, type: "summary_completion", text: "Desertification affects the livelihoods of over _______ billion people.", correctAnswer: "1.5", explanation: "The passage says 'affecting the livelihoods of over 1.5 billion people.'" },
        { number: 25, type: "summary_completion", text: "The Great Green Wall aims to restore _______ million hectares of degraded land.", correctAnswer: "100", explanation: "The passage states 'restoring 100 million hectares.'" },
        { number: 26, type: "summary_completion", text: "As of 2023, approximately _______ million hectares have been restored by the Great Green Wall.", correctAnswer: "18", explanation: "The passage says 'approximately 18 million hectares have been restored.'" },
      ],
    },
    {
      title: "Smart Cities and Technology",
      text: `The concept of the "smart city" — an urban environment that uses digital technology, data analytics, and connected infrastructure to improve the quality of life for its residents, enhance sustainability, and optimise the efficiency of city operations — has moved from futuristic vision to practical reality in cities around the world. Driven by rapid advances in the Internet of Things (IoT), artificial intelligence, 5G connectivity, and cloud computing, smart city initiatives are addressing challenges ranging from traffic congestion and air pollution to energy management, public safety, and citizen engagement.

A. Smart transportation systems represent one of the most visible and impactful applications of smart city technology. Intelligent traffic management systems use networks of sensors, cameras, and AI algorithms to monitor traffic flows in real time and adjust signal timing dynamically to reduce congestion and improve journey times. In Pittsburgh, USA, an AI-powered traffic signal system called Surtrac has reduced travel times by 25 percent and idling time by over 40 percent at equipped intersections. Smart parking systems guide drivers directly to available spaces using sensor data and mobile apps, reducing the estimated 30 percent of urban traffic that consists of vehicles circling in search of parking. Integrated public transport platforms provide real-time information on bus, train, and metro services, enabling passengers to plan journeys and respond to disruptions more effectively.

B. Smart energy management is a cornerstone of sustainable urban development. Smart grids use advanced metering infrastructure (AMI), sensors, and analytics to monitor electricity generation, distribution, and consumption across the city in real time, enabling utilities to balance supply and demand, detect faults, and integrate renewable energy sources more effectively. Smart street lighting systems, which use LED technology combined with motion sensors and dimming controls, can reduce energy consumption for lighting by 50 to 70 percent compared with conventional systems. Building energy management systems (BEMS) use IoT sensors to monitor and control heating, ventilation, air conditioning, and lighting in commercial and public buildings, optimising energy use based on occupancy patterns, weather conditions, and electricity prices.

C. Environmental monitoring and management are increasingly important functions of smart city platforms. Networks of low-cost air quality sensors deployed across urban areas provide granular, real-time data on concentrations of pollutants such as particulate matter (PM2.5 and PM10), nitrogen dioxide, and ozone, enabling city authorities to identify pollution hotspots and take targeted action. Smart waste management systems use sensors installed in waste bins to monitor fill levels, optimising collection routes and schedules to reduce fuel consumption, vehicle emissions, and operational costs. Water quality monitoring systems can detect contamination events in real time, enabling rapid response to protect public health.

D. Public safety and emergency response are areas where smart city technology is delivering tangible benefits. Predictive policing algorithms analyse historical crime data, weather patterns, event schedules, and other variables to identify areas at higher risk of criminal activity, enabling police to allocate resources more effectively. Gunshot detection systems, such as ShotSpotter, use networks of acoustic sensors to detect, locate, and report gunfire within seconds, reducing response times significantly. Integrated emergency management platforms coordinate the response of police, fire, and medical services to major incidents, using real-time data from sensors, cameras, CCTV, and social media to provide situational awareness and facilitate decision-making.

E. Citizen engagement and participatory governance are essential dimensions of the smart city concept. Digital platforms that enable residents to report problems (such as potholes, broken street lights, or fly-tipping), participate in planning consultations, and provide feedback on public services are enhancing the responsiveness and accountability of city administrations. Participatory budgeting platforms, which allow citizens to vote on how a portion of the municipal budget is spent, have been adopted in cities including Paris, New York, and Lisbon, fostering a greater sense of civic ownership and democratic participation. Open data initiatives — making government datasets freely available for public use — enable researchers, entrepreneurs, and civic organisations to develop innovative applications and hold authorities to account.

F. Despite the promise of smart cities, significant challenges and criticisms have emerged. Privacy concerns are paramount: the extensive surveillance infrastructure required for many smart city applications — including cameras, sensors, and data collection platforms — raises serious questions about the balance between efficiency and individual freedom. Cybersecurity vulnerabilities in connected infrastructure could be exploited by hackers to disrupt critical services such as water supply, electricity, and transportation. The risk of a "digital divide" — where the benefits of smart city technology accrue primarily to tech-savvy, affluent residents while marginalising older, poorer, or less digitally literate populations — must be addressed through inclusive design and targeted support. Finally, the enormous cost of implementing smart city infrastructure, coupled with the difficulty of measuring its return on investment, means that many cities, particularly in the developing world, may struggle to adopt these technologies at scale.`,
      questions: [
        { number: 27, type: "matching_information", text: "Technology that detects and locates gunfire using sound sensors", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "D", explanation: "Paragraph D describes 'ShotSpotter' using 'acoustic sensors to detect, locate, and report gunfire.'" },
        { number: 28, type: "matching_information", text: "Concerns about surveillance and individual privacy in smart cities", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "F", explanation: "Paragraph F discusses privacy, surveillance infrastructure, and the balance with individual freedom." },
        { number: 29, type: "matching_information", text: "Platforms that allow citizens to decide how public money is spent", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "E", explanation: "Paragraph E describes 'Participatory budgeting platforms' where 'citizens vote on how a portion of the municipal budget is spent.'" },
        { number: 30, type: "matching_information", text: "Sensors in waste bins that optimise collection schedules", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "C", explanation: "Paragraph C discusses 'sensors installed in waste bins to monitor fill levels, optimising collection routes.'" },
        { number: 31, type: "matching_information", text: "An AI system that reduced travel times by 25 percent", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "A", explanation: "Paragraph A describes Surtrac which 'has reduced travel times by 25 percent.'" },
        { number: 32, type: "flow_chart_completion", text: "Smart traffic systems use sensors, cameras, and AI to monitor traffic _______ in real time.", correctAnswer: "flows", explanation: "The passage says systems 'monitor traffic flows in real time.'" },
        { number: 33, type: "flow_chart_completion", text: "Approximately _______ percent of urban traffic consists of vehicles searching for parking.", correctAnswer: "30", explanation: "The passage mentions 'the estimated 30 percent of urban traffic.'" },
        { number: 34, type: "flow_chart_completion", text: "Smart street lighting can reduce energy consumption by _______ to 70 percent.", correctAnswer: "50", explanation: "The passage states 'reduce energy consumption for lighting by 50 to 70 percent.'" },
        { number: 35, type: "flow_chart_completion", text: "Air quality sensors measure pollutants such as PM2.5, PM10, nitrogen dioxide, and _______.", correctAnswer: "ozone", explanation: "The passage lists 'particulate matter (PM2.5 and PM10), nitrogen dioxide, and ozone.'" },
        { number: 36, type: "flow_chart_completion", text: "Pittsburgh's AI traffic system is called _______.", correctAnswer: "Surtrac", explanation: "The passage names the system 'Surtrac.'" },
        { number: 37, type: "flow_chart_completion", text: "Building energy management systems optimise energy based on occupancy, weather, and electricity _______.", correctAnswer: "prices", explanation: "The passage says 'based on occupancy patterns, weather conditions, and electricity prices.'" },
        { number: 38, type: "flow_chart_completion", text: "The Surtrac system reduced vehicle idling time by over _______ percent.", correctAnswer: "40", explanation: "The passage states 'idling time by over 40 percent.'" },
        { number: 39, type: "flow_chart_completion", text: "Predictive policing algorithms analyse crime data, weather, and event _______ to identify risk areas.", correctAnswer: "schedules", explanation: "The passage mentions 'historical crime data, weather patterns, event schedules.'" },
        { number: 40, type: "flow_chart_completion", text: "Open _______ initiatives make government datasets freely available for public use.", correctAnswer: "data", explanation: "The passage says 'Open data initiatives — making government datasets freely available.'" },
      ],
    },
  ],
};
