import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_29: ReadingTest = {
  id: 29,
  passages: [
    {
      title: "History of Mathematics",
      text: `Mathematics, often described as the universal language of science, has evolved over thousands of years from simple counting and measurement into an extraordinarily sophisticated discipline that underpins virtually every aspect of modern life. Its history is a narrative of human ingenuity, cultural exchange, and intellectual breakthroughs that span civilisations and continents.

The earliest mathematical activity emerged from practical necessity. Ancient Sumerian and Babylonian civilisations, flourishing in Mesopotamia from approximately 3500 BCE, developed numeral systems to manage agricultural production, trade, and taxation. The Babylonians employed a base-60 (sexagesimal) number system whose legacy persists today in our division of hours into sixty minutes and circles into 360 degrees. Clay tablets dating to around 1800 BCE reveal that Babylonian mathematicians could solve quadratic equations, calculate square roots, and had compiled extensive tables of reciprocals and multiplication.

Ancient Egypt contributed its own mathematical traditions, documented in remarkable papyri such as the Rhind Papyrus (c. 1650 BCE), which contains eighty-four problems covering arithmetic, geometry, and elementary algebra. Egyptian mathematics was predominantly practical, oriented toward land surveying after the annual Nile floods, architectural calculations for pyramid construction, and the management of granaries. Their methods, while effective, were largely empirical rather than theoretical, relying on specific numerical examples rather than abstract proofs.

It was in ancient Greece that mathematics underwent its most profound transformation, shifting from a collection of practical techniques to a deductive science grounded in logical proof. Thales of Miletus (c. 624–546 BCE) is traditionally credited with introducing the concept of mathematical proof, while Pythagoras and his followers explored the relationships between numbers and geometric forms, famously demonstrating the theorem that bears his name. Euclid's Elements, compiled around 300 BCE in Alexandria, systematised geometry into a rigorous axiomatic framework that remained the standard textbook for over two thousand years — arguably the most influential mathematics text ever written.

The contributions of Archimedes (c. 287–212 BCE) were extraordinary in both scope and depth. He calculated the value of pi with remarkable accuracy, determined the volumes and surface areas of spheres and cylinders, and developed methods of calculation that anticipated integral calculus by nearly two millennia. His work on the principle of buoyancy and the mechanics of levers demonstrated the power of mathematical reasoning applied to physical problems.

Following the decline of Greek civilisation, the centre of mathematical innovation shifted to the Islamic world. Scholars working in Baghdad's House of Wisdom during the eighth and ninth centuries translated and preserved Greek mathematical texts that might otherwise have been lost. More importantly, they made original contributions of lasting significance. Muhammad ibn Musa al-Khwarizmi, whose name gives us the word "algorithm," wrote a treatise on al-jabr (algebra) around 820 CE that systematised methods for solving linear and quadratic equations. Omar Khayyam extended algebraic methods to cubic equations, while other scholars developed spherical trigonometry essential for astronomical calculations and the determination of prayer times.

The transmission of Islamic mathematical knowledge to medieval Europe, facilitated by translations undertaken in centres such as Toledo and Sicily, catalysed the European mathematical renaissance. Leonardo of Pisa, known as Fibonacci, introduced Hindu-Arabic numerals to a European audience through his Liber Abaci (1202), gradually displacing the cumbersome Roman numeral system and transforming commercial arithmetic.

The seventeenth century witnessed an explosion of mathematical creativity in Europe. René Descartes unified algebra and geometry through his invention of coordinate geometry, while Pierre de Fermat and Blaise Pascal laid the foundations of probability theory. Most consequentially, Isaac Newton and Gottfried Wilhelm Leibniz independently developed calculus — a mathematical framework for analysing change and motion that became the essential tool of physics, engineering, and economics.

Modern mathematics has expanded into realms of abstraction that would astonish its ancient practitioners. Set theory, topology, abstract algebra, mathematical logic, and statistics have opened new fields of inquiry, while applied mathematics drives advances in cryptography, artificial intelligence, climate modelling, and financial engineering. The story of mathematics is far from complete; each generation discovers new problems, new methods, and new connections that enrich this most enduring of human intellectual traditions.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "What number system did the Babylonians use?", options: ["A Base-10", "B Base-12", "C Base-60", "D Base-20"], correctAnswer: "C", explanation: "The passage states the Babylonians 'employed a base-60 (sexagesimal) number system.'" },
        { number: 2, type: "multiple_choice", text: "What was the primary focus of ancient Egyptian mathematics?", options: ["A Theoretical proof and abstraction", "B Practical applications such as surveying and construction", "C Pure number theory", "D Astronomical calculations"], correctAnswer: "B", explanation: "The passage says Egyptian mathematics was 'predominantly practical, oriented toward land surveying... architectural calculations... and the management of granaries.'" },
        { number: 3, type: "multiple_choice", text: "According to the passage, what was the most significant contribution of ancient Greek mathematics?", options: ["A The development of the base-60 number system", "B The compilation of multiplication tables", "C The shift to deductive reasoning and logical proof", "D The invention of calculus"], correctAnswer: "C", explanation: "The passage states mathematics in Greece shifted 'from a collection of practical techniques to a deductive science grounded in logical proof.'" },
        { number: 4, type: "multiple_choice", text: "Who independently developed calculus?", options: ["A Descartes and Fermat", "B Newton and Leibniz", "C Euclid and Archimedes", "D Fibonacci and al-Khwarizmi"], correctAnswer: "B", explanation: "The passage states 'Isaac Newton and Gottfried Wilhelm Leibniz independently developed calculus.'" },
        { number: 5, type: "sentence_completion", text: "The Rhind Papyrus dates to approximately __(5)__ BCE.", correctAnswer: "1650", explanation: "The passage states 'the Rhind Papyrus (c. 1650 BCE).'" },
        { number: 6, type: "sentence_completion", text: "Euclid's __(6)__ systematised geometry into an axiomatic framework.", correctAnswer: "Elements", explanation: "The passage names 'Euclid's Elements.'" },
        { number: 7, type: "sentence_completion", text: "Al-Khwarizmi's name gives us the modern word __(7)__.", correctAnswer: "algorithm", explanation: "The passage says 'whose name gives us the word \"algorithm.\"'" },
        { number: 8, type: "sentence_completion", text: "Fibonacci introduced Hindu-Arabic numerals to Europe through his book __(8)__.", correctAnswer: "Liber Abaci", explanation: "The passage names 'his Liber Abaci (1202).'" },
        { number: 9, type: "sentence_completion", text: "Archimedes' work on buoyancy and __(9)__ demonstrated the power of mathematical reasoning.", correctAnswer: "levers", explanation: "The passage mentions 'the principle of buoyancy and the mechanics of levers.'" },
        { number: 10, type: "sentence_completion", text: "René Descartes unified algebra and geometry by inventing __(10)__ geometry.", correctAnswer: "coordinate", explanation: "The passage mentions 'his invention of coordinate geometry.'" },
        { number: 11, type: "sentence_completion", text: "Omar Khayyam extended algebraic methods to __(11)__ equations.", correctAnswer: "cubic", explanation: "The passage states 'Omar Khayyam extended algebraic methods to cubic equations.'" },
        { number: 12, type: "sentence_completion", text: "Translations of Islamic mathematical texts into Latin were undertaken in centres such as Toledo and __(12)__.", correctAnswer: "Sicily", explanation: "The passage mentions 'centres such as Toledo and Sicily.'" },
        { number: 13, type: "sentence_completion", text: "Fermat and Pascal laid the foundations of __(13)__ theory.", correctAnswer: "probability", explanation: "The passage states 'Fermat and Blaise Pascal laid the foundations of probability theory.'" },
      ],
    },
    {
      title: "Deforestation Effects",
      text: `A. Deforestation — the large-scale removal of forest cover — represents one of the most pressing environmental challenges of the modern era. Each year, approximately ten million hectares of forest are lost globally, an area roughly equivalent to the size of South Korea. While deforestation rates have slowed somewhat from their peak in the 1990s, the ongoing destruction of forests continues to generate far-reaching consequences for climate, biodiversity, water systems, and human communities.

B. The primary drivers of deforestation vary by region but share a common economic logic: forests are cleared to make way for activities perceived as more immediately profitable. In tropical regions, agricultural expansion is the dominant cause, accounting for approximately eighty per cent of forest loss. Cattle ranching in the Brazilian Amazon, palm oil plantations in Southeast Asia, and soy cultivation in South America have converted vast tracts of primary forest into commodity production zones. Logging, both legal and illegal, mining operations, and infrastructure development account for much of the remainder.

C. The climatic consequences of deforestation are severe. Forests act as carbon sinks, absorbing approximately 2.6 billion tonnes of carbon dioxide annually — roughly thirty per cent of human fossil fuel emissions. When trees are felled and burned, the carbon stored in their biomass is released back into the atmosphere, contributing to global warming. Tropical deforestation alone is estimated to account for eight to ten per cent of global greenhouse gas emissions, making it a larger source of emissions than the entire global transportation sector in some estimates.

D. Biodiversity loss is perhaps the most irreversible consequence of deforestation. Tropical forests, which occupy approximately six per cent of the Earth's land surface, harbour more than half of all terrestrial species. The destruction of these habitats drives species toward extinction at rates estimated to be one hundred to one thousand times higher than natural background rates. Many species lost to deforestation have never been scientifically described, meaning their potential contributions to medicine, agriculture, and biotechnology are lost permanently.

E. Deforestation profoundly disrupts hydrological cycles. Forest canopies intercept rainfall, slowing its descent and allowing gradual infiltration into the soil, which replenishes groundwater reserves and maintains steady stream flows. When forests are removed, rainfall hits bare soil directly, increasing surface runoff, soil erosion, and the frequency of flooding downstream. Simultaneously, reduced evapotranspiration from deforested areas decreases regional rainfall, potentially triggering long-term drying trends. The Amazon basin, where forests generate approximately half of their own rainfall through moisture recycling, is considered particularly vulnerable to a deforestation-driven tipping point beyond which the ecosystem could transition irreversibly from forest to savanna.

F. Indigenous and forest-dependent communities suffer disproportionately from deforestation. An estimated 1.6 billion people depend on forests for food, fuel, medicine, and livelihoods. Deforestation displaces communities, destroys traditional food sources, degrades water quality, and undermines cultural practices that have sustained indigenous peoples for generations. The rights of indigenous land stewards are increasingly recognised as central to effective forest conservation, as studies consistently demonstrate that indigenous-managed territories experience lower deforestation rates than surrounding areas.

G. Efforts to combat deforestation operate at multiple scales. International initiatives such as REDD+ (Reducing Emissions from Deforestation and Forest Degradation) aim to provide financial incentives for developing countries to preserve their forests. Corporate supply chain commitments, certification schemes such as the Forest Stewardship Council (FSC), and consumer awareness campaigns seek to reduce demand for products linked to deforestation. National policies, including Brazil's Forest Code and Indonesia's moratorium on new palm oil concessions, have achieved notable though uneven results.

H. Reforestation and afforestation programmes offer a complementary strategy. China's "Great Green Wall" programme, which aims to plant billions of trees across northern China to combat desertification, is the largest such initiative in history. However, critics caution that monoculture tree plantations do not replicate the ecological complexity of natural forests and may deliver fewer benefits for biodiversity and carbon storage. The most effective restoration approaches prioritise natural regeneration and the re-establishment of diverse native ecosystems rather than simple tree-planting campaigns.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Section A", options: ["I. Economic motivations behind forest clearance", "II. The scale and urgency of global forest loss", "III. Forests as regulators of the global carbon cycle", "IV. Extinction risks from habitat destruction", "V. Disruption of rainfall patterns and water systems", "VI. The human cost of forest destruction", "VII. International and corporate conservation strategies", "VIII. Restoring lost forest cover"], correctAnswer: "II", explanation: "Section A introduces the scale and urgency of deforestation." },
        { number: 15, type: "matching_headings", text: "Section B", options: ["I. Economic motivations behind forest clearance", "II. The scale and urgency of global forest loss", "III. Forests as regulators of the global carbon cycle", "IV. Extinction risks from habitat destruction", "V. Disruption of rainfall patterns and water systems", "VI. The human cost of forest destruction", "VII. International and corporate conservation strategies", "VIII. Restoring lost forest cover"], correctAnswer: "I", explanation: "Section B discusses the economic drivers of deforestation." },
        { number: 16, type: "matching_headings", text: "Section C", options: ["I. Economic motivations behind forest clearance", "II. The scale and urgency of global forest loss", "III. Forests as regulators of the global carbon cycle", "IV. Extinction risks from habitat destruction", "V. Disruption of rainfall patterns and water systems", "VI. The human cost of forest destruction", "VII. International and corporate conservation strategies", "VIII. Restoring lost forest cover"], correctAnswer: "III", explanation: "Section C discusses forests as carbon sinks." },
        { number: 17, type: "matching_headings", text: "Section D", options: ["I. Economic motivations behind forest clearance", "II. The scale and urgency of global forest loss", "III. Forests as regulators of the global carbon cycle", "IV. Extinction risks from habitat destruction", "V. Disruption of rainfall patterns and water systems", "VI. The human cost of forest destruction", "VII. International and corporate conservation strategies", "VIII. Restoring lost forest cover"], correctAnswer: "IV", explanation: "Section D discusses biodiversity loss and species extinction." },
        { number: 18, type: "matching_headings", text: "Section E", options: ["I. Economic motivations behind forest clearance", "II. The scale and urgency of global forest loss", "III. Forests as regulators of the global carbon cycle", "IV. Extinction risks from habitat destruction", "V. Disruption of rainfall patterns and water systems", "VI. The human cost of forest destruction", "VII. International and corporate conservation strategies", "VIII. Restoring lost forest cover"], correctAnswer: "V", explanation: "Section E discusses hydrological cycles and water systems." },
        { number: 19, type: "matching_headings", text: "Section F", options: ["I. Economic motivations behind forest clearance", "II. The scale and urgency of global forest loss", "III. Forests as regulators of the global carbon cycle", "IV. Extinction risks from habitat destruction", "V. Disruption of rainfall patterns and water systems", "VI. The human cost of forest destruction", "VII. International and corporate conservation strategies", "VIII. Restoring lost forest cover"], correctAnswer: "VI", explanation: "Section F discusses the impact on indigenous communities." },
        { number: 20, type: "table_completion", text: "Approximately __(20)__ million hectares of forest are lost each year.", correctAnswer: "ten", explanation: "The passage states 'approximately ten million hectares.'" },
        { number: 21, type: "table_completion", text: "Agricultural expansion accounts for approximately __(21)__ per cent of tropical forest loss.", correctAnswer: "eighty", explanation: "The passage states 'approximately eighty per cent of forest loss.'" },
        { number: 22, type: "table_completion", text: "Forests absorb approximately __(22)__ billion tonnes of CO₂ annually.", correctAnswer: "2.6", explanation: "The passage states 'approximately 2.6 billion tonnes.'" },
        { number: 23, type: "table_completion", text: "Tropical forests harbour more than __(23)__ of all terrestrial species.", correctAnswer: "half", explanation: "The passage says 'more than half of all terrestrial species.'" },
        { number: 24, type: "table_completion", text: "An estimated __(24)__ billion people depend on forests for their livelihoods.", correctAnswer: "1.6", explanation: "The passage states 'An estimated 1.6 billion people.'" },
        { number: 25, type: "table_completion", text: "The Amazon generates approximately __(25)__ of its own rainfall through moisture recycling.", correctAnswer: "half", explanation: "The passage says 'approximately half of their own rainfall.'" },
        { number: 26, type: "table_completion", text: "Species extinction rates are estimated to be __(26)__ to one thousand times higher than natural rates.", correctAnswer: "one hundred", explanation: "The passage states 'one hundred to one thousand times higher.'" },
      ],
    },
    {
      title: "Drone Technology",
      text: `Unmanned aerial vehicles (UAVs), commonly known as drones, have evolved from specialised military tools into versatile platforms with applications spanning agriculture, logistics, emergency response, environmental monitoring, filmmaking, and infrastructure inspection. The rapid proliferation of drone technology, driven by advances in miniaturisation, battery capacity, sensor technology, and artificial intelligence, is transforming industries and creating new economic opportunities while simultaneously raising complex regulatory, safety, and privacy questions.

The military origins of modern drone technology trace back to the mid-twentieth century. Early remotely piloted aircraft were used primarily for reconnaissance and target practice. The development of the MQ-1 Predator by General Atomics in the 1990s marked a turning point, introducing a medium-altitude, long-endurance platform capable of carrying cameras and, eventually, weapons. The Predator and its successors became central tools of military operations in Afghanistan, Iraq, and elsewhere, generating both tactical advantages and ethical controversy regarding the use of lethal force by remote control.

Commercial and civilian drone applications have expanded exponentially since the early 2010s. In agriculture, drones equipped with multispectral cameras and sensors can survey vast areas of farmland, identifying crop health issues, water stress, pest infestations, and nutrient deficiencies with a precision impossible from the ground. This data enables precision agriculture practices that reduce chemical inputs, conserve water, and increase yields. Studies suggest that agricultural drones can reduce pesticide use by up to thirty per cent while improving crop monitoring efficiency by a factor of five.

The logistics industry is investing heavily in drone delivery. Companies including Amazon, Google's Wing, and UPS Flight Forward are developing and testing systems capable of delivering packages directly to consumers' homes. Rwanda and Ghana have pioneered the use of medical delivery drones, with the company Zipline operating a nationwide network that delivers blood products, vaccines, and essential medicines to remote health clinics within minutes of an order being placed. These systems have demonstrated particular value in regions where road infrastructure is poor or weather conditions make ground transport unreliable.

Emergency response is another domain where drones are proving transformative. Following natural disasters, drones can rapidly survey damaged areas, locate survivors, and assess infrastructure damage, providing critical information to rescue teams when time is of the essence. Thermal imaging cameras mounted on drones can detect body heat signatures beneath rubble, while drones equipped with loudspeakers can communicate with stranded individuals in inaccessible locations. Fire departments increasingly use drones to monitor wildfire progression, map fire perimeters, and identify hotspots that might reignite.

Environmental monitoring benefits enormously from drone capabilities. Marine biologists use drones to survey whale populations and monitor coastal erosion without disturbing wildlife. Forestry agencies employ drones to map forest cover, detect illegal logging, and even plant trees — specialised seed-dispersal drones can distribute thousands of seed pods per day across deforested areas. Anti-poaching units in African wildlife reserves use drones equipped with night-vision cameras to detect and deter poachers operating under cover of darkness.

Infrastructure inspection represents a rapidly growing commercial application. Drones can inspect bridges, power lines, wind turbines, oil rigs, and building facades more quickly, cheaply, and safely than human inspectors, who would otherwise need to work at dangerous heights or in confined spaces. Utility companies report that drone inspections reduce costs by up to fifty per cent while improving the detection rate of faults and damage.

The regulatory landscape for drones continues to evolve as authorities balance innovation against safety and privacy concerns. Most jurisdictions require commercial drone operators to obtain licences and adhere to restrictions on flight altitude, proximity to airports, and operations over populated areas. The integration of drones into shared airspace alongside manned aircraft remains one of the most significant technical and regulatory challenges. Unmanned traffic management (UTM) systems, designed to coordinate large numbers of simultaneous drone flights in urban environments, are under development in several countries.

Privacy concerns have intensified as drone capabilities expand. The ability of camera-equipped drones to observe private property and public spaces from above has prompted calls for stronger legal protections. Several jurisdictions have enacted specific drone privacy legislation, while others rely on existing laws related to surveillance, trespass, and harassment. Striking the right balance between enabling beneficial applications and protecting individual privacy will be a defining challenge as drone technology continues to mature and proliferate.`,
      questions: [
        { number: 27, type: "true_false_not_given", text: "The MQ-1 Predator was the first drone ever built.", correctAnswer: "FALSE", explanation: "The passage says 'Early remotely piloted aircraft were used primarily for reconnaissance' before the Predator, which 'marked a turning point.'" },
        { number: 28, type: "true_false_not_given", text: "Agricultural drones can reduce pesticide use by up to thirty per cent.", correctAnswer: "TRUE", explanation: "The passage states 'agricultural drones can reduce pesticide use by up to thirty per cent.'" },
        { number: 29, type: "true_false_not_given", text: "Amazon has already launched a nationwide drone delivery service in the United States.", correctAnswer: "NOT GIVEN", explanation: "The passage says Amazon is 'developing and testing' systems but does not say it has launched a nationwide service." },
        { number: 30, type: "true_false_not_given", text: "Zipline operates medical delivery drones in Rwanda and Ghana.", correctAnswer: "TRUE", explanation: "The passage states 'Rwanda and Ghana have pioneered the use of medical delivery drones, with the company Zipline operating.'" },
        { number: 31, type: "true_false_not_given", text: "Drone inspections of infrastructure cost more than traditional human inspections.", correctAnswer: "FALSE", explanation: "The passage says 'drone inspections reduce costs by up to fifty per cent.'" },
        { number: 32, type: "true_false_not_given", text: "All countries require commercial drone operators to hold a licence.", correctAnswer: "NOT GIVEN", explanation: "The passage says 'Most jurisdictions require' licences, not all." },
        { number: 33, type: "true_false_not_given", text: "Seed-dispersal drones can distribute thousands of seed pods per day.", correctAnswer: "TRUE", explanation: "The passage states 'specialised seed-dispersal drones can distribute thousands of seed pods per day.'" },
        { number: 34, type: "short_answer", text: "What type of camera enables drones to detect survivors beneath rubble?", correctAnswer: "thermal imaging", explanation: "The passage mentions 'Thermal imaging cameras mounted on drones can detect body heat signatures beneath rubble.'" },
        { number: 35, type: "short_answer", text: "What acronym is used for systems designed to coordinate drone flights in urban areas?", correctAnswer: "UTM", explanation: "The passage defines 'Unmanned traffic management (UTM) systems.'" },
        { number: 36, type: "short_answer", text: "What company developed the MQ-1 Predator?", correctAnswer: "General Atomics", explanation: "The passage states 'the MQ-1 Predator by General Atomics.'" },
        { number: 37, type: "short_answer", text: "By what factor do drones improve crop monitoring efficiency?", correctAnswer: "five", explanation: "The passage says 'improving crop monitoring efficiency by a factor of five.'" },
        { number: 38, type: "short_answer", text: "What percentage cost reduction do utility companies report from drone inspections?", correctAnswer: "fifty per cent", explanation: "The passage states 'reduce costs by up to fifty per cent.'" },
        { number: 39, type: "short_answer", text: "What do anti-poaching drones use to detect poachers at night?", correctAnswer: "night-vision cameras", explanation: "The passage mentions 'drones equipped with night-vision cameras.'" },
        { number: 40, type: "short_answer", text: "What items does Zipline deliver to remote health clinics?", correctAnswer: "blood products, vaccines, and medicines", explanation: "The passage says Zipline 'delivers blood products, vaccines, and essential medicines.'" },
      ],
    },
  ],
};
