import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_58: ReadingTest = {
  id: 58,
  passages: [
    {
      title: "The Story of the Thylacine (Tasmanian Tiger)",
      text: `The thylacine, commonly known as the Tasmanian tiger or Tasmanian wolf, was one of the most extraordinary and tragically doomed predators in the history of modern zoology. A large, carnivorous marsupial with a distinctive pattern of dark stripes across its tawny back and rump, the thylacine was the largest known carnivorous marsupial of modern times and the sole surviving member of its family, Thylacinidae, at the time of European settlement of Australia. Its extinction in the twentieth century — driven by human persecution, habitat destruction, and disease — has become one of the most powerful cautionary tales in the history of conservation.

The thylacine's evolutionary history stretches back millions of years. Fossil evidence indicates that thylacinids first appeared in the Miocene epoch, approximately 23 million years ago, and that various species of the family once ranged across mainland Australia, New Guinea, and Tasmania. On the Australian mainland, thylacines gradually declined and are believed to have become extinct approximately 3,000 years ago — a decline that coincided with the spread of the dingo, a placental carnivore introduced to Australia by human settlers from Southeast Asia. The dingo, which never reached Tasmania due to the flooding of the land bridge that had connected Tasmania to the mainland approximately 10,000 years earlier, likely outcompeted the thylacine for prey and territory on the mainland. In Tasmania, isolated from dingoes, thylacines remained the island's apex predator until the arrival of European settlers in 1803.

The thylacine was a remarkable example of convergent evolution — the process by which unrelated species independently evolve similar traits in response to similar environmental pressures. Although the thylacine was a marsupial, more closely related to kangaroos and wombats than to any placental carnivore, it bore a striking superficial resemblance to a medium-sized dog or wolf. It had a long, stiff tail, powerful jaws capable of opening to an extraordinary gape of approximately 80 degrees, and a body structure adapted for pursuit predation. Adult thylacines typically measured 100 to 130 centimetres in body length, with an additional tail of 50 to 65 centimetres, and weighed between 20 and 30 kilograms. Females possessed a rear-opening pouch, in which they carried and nursed their young — typically two to four joeys per litter.

European settlers in Tasmania quickly came into conflict with the thylacine. Sheep farming became the dominant agricultural industry in the colony, and thylacines were blamed — often without strong evidence — for livestock kills. From the 1830s onwards, private bounties were offered for dead thylacines, and in 1888 the Tasmanian government introduced an official bounty scheme, paying one pound per adult thylacine and ten shillings per juvenile. Between 1888 and 1909, when the government bounty was withdrawn, 2,184 bounties were paid. In addition to direct hunting, thylacines suffered from habitat loss as forests were cleared for farming and from competition with introduced species, particularly dogs. An epidemic disease — possibly distemper, introduced through contact with domestic dogs — may also have contributed to the species' decline, though direct evidence for this hypothesis remains limited.

By the early twentieth century, thylacines had become extremely rare. The last confirmed killing of a wild thylacine occurred in 1930, when a farmer named Wilfred Batty shot one that he found near his chicken coop in the northeast of Tasmania. The last known surviving thylacine — a male sometimes referred to as "Benjamin," though this name is not historically confirmed — died on 7 September 1936 at the Hobart Zoo, reportedly from exposure after being locked out of its sheltered sleeping quarters on a cold night. Footage of this last thylacine, pacing restlessly in its enclosure, has become one of the most iconic and poignant images in the history of conservation. The thylacine was not officially declared extinct by the Tasmanian government until 1986 — fifty years after the last confirmed individual died.

Despite its official extinction, the thylacine continues to generate public fascination and scientific interest. Unconfirmed sightings are reported regularly in Tasmania, though none has been substantiated by physical evidence. In 2017, researchers at the University of Melbourne announced a project to sequence the complete genome of the thylacine from preserved museum specimens, raising the theoretical possibility of de-extinction — the resurrection of an extinct species using advanced genetic engineering techniques such as CRISPR. While the technical, ecological, and ethical challenges of thylacine de-extinction are immense, the project has reignited debate about whether and how humanity should attempt to undo the extinctions it has caused.`,
      questions: [
        { number: 1, type: "true_false_not_given", text: "The thylacine was a placental mammal.", correctAnswer: "FALSE", explanation: "The passage says the thylacine was 'a large, carnivorous marsupial.'" },
        { number: 2, type: "true_false_not_given", text: "Thylacines on mainland Australia became extinct about 3,000 years ago.", correctAnswer: "TRUE", explanation: "The passage says they 'are believed to have become extinct approximately 3,000 years ago.'" },
        { number: 3, type: "true_false_not_given", text: "Dingoes were introduced to Australia by Indigenous Australians.", correctAnswer: "NOT GIVEN", explanation: "The passage says dingoes were 'introduced to Australia by human settlers from Southeast Asia' but does not specify Indigenous Australians." },
        { number: 4, type: "true_false_not_given", text: "The thylacine could open its jaws to approximately 80 degrees.", correctAnswer: "TRUE", explanation: "The passage says 'jaws capable of opening to an extraordinary gape of approximately 80 degrees.'" },
        { number: 5, type: "true_false_not_given", text: "The government bounty scheme ran from 1888 to 1912.", correctAnswer: "FALSE", explanation: "The passage says 'between 1888 and 1909, when the government bounty was withdrawn.'" },
        { number: 6, type: "true_false_not_given", text: "The last known thylacine in the Hobart Zoo was definitely named Benjamin.", correctAnswer: "FALSE", explanation: "The passage says it was 'sometimes referred to as \"Benjamin,\" though this name is not historically confirmed.'" },
        { number: 7, type: "true_false_not_given", text: "The thylacine was officially declared extinct in 1936.", correctAnswer: "FALSE", explanation: "The passage says it 'was not officially declared extinct by the Tasmanian government until 1986.'" },
        { number: 8, type: "sentence_completion", text: "Thylacinids first appeared approximately _______ million years ago.", correctAnswer: "23", explanation: "The passage says 'approximately 23 million years ago.'" },
        { number: 9, type: "sentence_completion", text: "The land bridge connecting Tasmania to the mainland flooded approximately _______ years ago.", correctAnswer: "10,000", explanation: "The passage says 'approximately 10,000 years earlier.'" },
        { number: 10, type: "sentence_completion", text: "Between 1888 and 1909, a total of _______ bounties were paid.", correctAnswer: "2,184", explanation: "The passage says '2,184 bounties were paid.'" },
        { number: 11, type: "sentence_completion", text: "The last thylacine died on 7 September _______ at the Hobart Zoo.", correctAnswer: "1936", explanation: "The passage says 'died on 7 September 1936.'" },
        { number: 12, type: "sentence_completion", text: "Adult thylacines weighed between 20 and _______ kilograms.", correctAnswer: "30", explanation: "The passage says 'weighed between 20 and 30 kilograms.'" },
        { number: 13, type: "sentence_completion", text: "Researchers at the University of _______ announced a thylacine genome sequencing project.", correctAnswer: "Melbourne", explanation: "The passage says 'researchers at the University of Melbourne.'" },
      ],
    },
    {
      title: "Why Finland's Schools Are Successful",
      text: `A. Finland's education system has attracted global attention and admiration since the country's students began achieving consistently outstanding results in the Programme for International Student Assessment (PISA), an influential series of international tests administered every three years by the Organisation for Economic Co-operation and Development (OECD). Finnish fifteen-year-olds have ranked among the highest-performing students in the world in reading, mathematics, and science across multiple PISA cycles, and Finland regularly appears near the top of international education rankings. What makes Finland's success especially remarkable is that it has been achieved not through rigorous testing, long school hours, or intense academic pressure, but through an approach that emphasises equity, teacher quality, student well-being, and trust.

B. One of the most distinctive features of the Finnish education system is the extraordinarily high status and rigorous training of its teachers. Teaching is one of the most prestigious and sought-after professions in Finland: only approximately 10 percent of applicants to primary teacher training programmes are accepted, making entry more competitive than admission to law or medicine. All teachers in Finland are required to hold a master's degree, and teacher education programmes combine deep subject knowledge with extensive training in pedagogy, research methodology, and classroom practice. Once qualified, Finnish teachers enjoy a high degree of professional autonomy: there is no system of national standardised testing, no school inspections, and no teacher performance rankings. Teachers are trusted to design their own curricula within a broad national framework, select their own teaching methods, and assess their students using their own professional judgement.

C. Finnish schools operate on a model of minimal standardised testing and maximal pedagogical freedom. Students take no national examinations until the matriculation exam at the end of upper secondary school, at approximately age 18. Before that point, assessment is conducted by classroom teachers through a combination of formative methods — including observation, self-assessment, peer feedback, and portfolio-based evaluation — rather than high-stakes testing. Finland does not publish school league tables or rankings, and there is no culture of schools competing with one another for students or results. The rationale is that excessive testing narrows the curriculum, increases stress, and diverts time and resources from teaching and learning.

D. Equity is a foundational principle of the Finnish education system. Finland has no private schools in any meaningful sense: approximately 98 percent of students attend publicly funded comprehensive schools, and all schools follow the same national curriculum framework. There is no academic selection or streaming before the age of 16, and students of all ability levels learn together in mixed-ability classes. Schools receive funding on a per-student basis, with additional resources allocated to schools serving disadvantaged communities. Special education support is embedded within mainstream schools rather than provided in separate institutions: approximately 30 percent of Finnish students receive some form of individual learning support during their school years, and early intervention is a core principle of the system.

E. The Finnish school day is notably shorter than in most other high-performing countries. Primary school students typically attend school for approximately four to five hours per day, and homework loads are among the lightest in the developed world. The Finnish approach is based on research showing that children learn more effectively when they have adequate time for rest, play, and creative activities. Finnish schools typically provide 15-minute breaks between lessons, during which students are encouraged to play outdoors regardless of weather conditions. Physical education, arts, music, and handicrafts are considered core subjects rather than optional extras, reflecting a holistic educational philosophy that values the development of the whole child — socially, emotionally, and physically — rather than focusing narrowly on academic achievement.

F. Finland's educational success has not been without its challenges. In recent PISA cycles, Finnish scores have declined slightly from their peak levels of the early 2000s, though they remain well above the OECD average. Some educators have attributed this decline to the increasing influence of digital technology on students' reading habits and attention spans, while others point to growing socioeconomic inequality — driven partly by immigration — as a factor. Finland is also grappling with how to prepare students for a rapidly changing labour market, with ongoing curriculum reforms emphasising transversal competencies such as critical thinking, entrepreneurship, digital literacy, and sustainability. Despite these challenges, Finland's education system continues to serve as a powerful demonstration that academic excellence and student well-being need not be in conflict — and that trust, equity, and teacher quality can achieve what testing and competition alone cannot.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Paragraph A", options: ["i. A shorter school day with more play", "ii. Finland's remarkable international test results", "iii. The challenge of maintaining high standards", "iv. Assessment without standardised testing", "v. Equal education for all students", "vi. Why Finnish teachers are exceptional", "vii. The role of private schools", "viii. Declining performance concerns"], correctAnswer: "ii", explanation: "Paragraph A introduces Finland's outstanding PISA results and global recognition." },
        { number: 15, type: "matching_headings", text: "Paragraph B", options: ["i. A shorter school day with more play", "ii. Finland's remarkable international test results", "iii. The challenge of maintaining high standards", "iv. Assessment without standardised testing", "v. Equal education for all students", "vi. Why Finnish teachers are exceptional", "vii. The role of private schools", "viii. Declining performance concerns"], correctAnswer: "vi", explanation: "Paragraph B focuses on teacher prestige, training, and autonomy." },
        { number: 16, type: "matching_headings", text: "Paragraph C", options: ["i. A shorter school day with more play", "ii. Finland's remarkable international test results", "iii. The challenge of maintaining high standards", "iv. Assessment without standardised testing", "v. Equal education for all students", "vi. Why Finnish teachers are exceptional", "vii. The role of private schools", "viii. Declining performance concerns"], correctAnswer: "iv", explanation: "Paragraph C describes how Finland avoids standardised testing and school rankings." },
        { number: 17, type: "matching_headings", text: "Paragraph D", options: ["i. A shorter school day with more play", "ii. Finland's remarkable international test results", "iii. The challenge of maintaining high standards", "iv. Assessment without standardised testing", "v. Equal education for all students", "vi. Why Finnish teachers are exceptional", "vii. The role of private schools", "viii. Declining performance concerns"], correctAnswer: "v", explanation: "Paragraph D discusses equity: no private schools, mixed-ability classes, and support for all." },
        { number: 18, type: "matching_headings", text: "Paragraph E", options: ["i. A shorter school day with more play", "ii. Finland's remarkable international test results", "iii. The challenge of maintaining high standards", "iv. Assessment without standardised testing", "v. Equal education for all students", "vi. Why Finnish teachers are exceptional", "vii. The role of private schools", "viii. Declining performance concerns"], correctAnswer: "i", explanation: "Paragraph E describes short school days, light homework, and emphasis on play and breaks." },
        { number: 19, type: "matching_headings", text: "Paragraph F", options: ["i. A shorter school day with more play", "ii. Finland's remarkable international test results", "iii. The challenge of maintaining high standards", "iv. Assessment without standardised testing", "v. Equal education for all students", "vi. Why Finnish teachers are exceptional", "vii. The role of private schools", "viii. Declining performance concerns"], correctAnswer: "iii", explanation: "Paragraph F discusses declining scores and ongoing challenges." },
        { number: 20, type: "summary_completion", text: "Only approximately _______ percent of applicants are accepted to Finnish primary teacher training programmes.", correctAnswer: "10", explanation: "The passage says 'only approximately 10 percent of applicants.'" },
        { number: 21, type: "summary_completion", text: "All Finnish teachers must hold a _______ degree.", correctAnswer: "master's", explanation: "The passage says 'required to hold a master's degree.'" },
        { number: 22, type: "summary_completion", text: "Approximately _______ percent of Finnish students attend publicly funded comprehensive schools.", correctAnswer: "98", explanation: "The passage says 'approximately 98 percent.'" },
        { number: 23, type: "summary_completion", text: "Approximately _______ percent of Finnish students receive some form of individual learning support.", correctAnswer: "30", explanation: "The passage says 'approximately 30 percent.'" },
        { number: 24, type: "summary_completion", text: "Finnish primary school students typically attend school for four to _______ hours per day.", correctAnswer: "five", explanation: "The passage says 'approximately four to five hours per day.'" },
        { number: 25, type: "summary_completion", text: "Students take 15-minute _______ between lessons, often playing outdoors.", correctAnswer: "breaks", explanation: "The passage says 'Finnish schools typically provide 15-minute breaks between lessons.'" },
        { number: 26, type: "summary_completion", text: "The matriculation exam is taken at approximately age _______.", correctAnswer: "18", explanation: "The passage says 'at approximately age 18.'" },
      ],
    },
    {
      title: "The Persuaders: Advertising Psychology",
      text: `Advertising is one of the most pervasive and influential forces in modern culture, shaping not only consumer behaviour but also social norms, aspirations, and self-perception. The global advertising industry generated an estimated $780 billion in revenue in 2022, and the average person in an industrialised country is exposed to thousands of advertising messages every day — on television, radio, social media, websites, billboards, packaging, and even in the design of retail environments. Behind these messages lies a sophisticated body of psychological research that advertisers use to capture attention, create desire, build brand loyalty, and ultimately influence purchasing decisions.

The foundations of advertising psychology were laid in the early twentieth century, when pioneering researchers began applying principles from behavioural psychology to commercial persuasion. John B. Watson, the founder of behaviourism, left academia to join the J. Walter Thompson advertising agency in 1921, where he applied his theories of conditioned responses to develop campaigns that associated products with powerful emotional stimuli. Watson argued that advertising should appeal to three fundamental emotions — love, fear, and rage — rather than to rational product attributes. His approach, which emphasised emotional manipulation over factual information, established a paradigm that continues to dominate advertising practice more than a century later.

Modern advertising draws heavily on cognitive psychology and behavioural economics to exploit systematic biases in human decision-making. One of the most widely used principles is social proof — the tendency for people to adopt behaviours or choices that they perceive as popular or endorsed by others. Testimonials, celebrity endorsements, user reviews, and "best-seller" labels all leverage social proof to reduce perceived risk and encourage purchase. The scarcity principle — the observation that people assign higher value to items that appear to be limited in availability — drives the ubiquitous use of phrases such as "limited edition," "while stocks last," and "only 3 left in stock." Anchoring, another cognitive bias, is exploited when retailers display a high "original" price next to a lower "sale" price, causing consumers to perceive the discounted price as a bargain regardless of the product's actual value.

The rise of digital advertising has transformed the industry's ability to target, personalise, and measure the effectiveness of advertising messages. Online platforms such as Google and Meta collect vast quantities of data about users' browsing behaviour, search queries, social connections, location, purchasing history, and demographic characteristics, enabling advertisers to deliver precisely targeted messages to specific audience segments. Programmatic advertising — the automated buying and selling of ad space through real-time auctions that occur in milliseconds — now accounts for the majority of digital display advertising. Retargeting — the practice of showing advertisements for products that a consumer has previously viewed or added to an online shopping cart — exploits the mere exposure effect, a well-documented psychological phenomenon whereby repeated exposure to a stimulus increases familiarity and liking.

The ethical dimensions of advertising psychology have generated intense debate. Critics argue that persuasive advertising techniques exploit cognitive vulnerabilities, manipulate emotions, promote materialism, and contribute to a range of social harms including body image disorders, childhood obesity, and consumer debt. Advertising directed at children is particularly contentious: research has shown that children under the age of eight generally lack the cognitive ability to recognise persuasive intent and are therefore especially susceptible to advertising influence. Several countries, including Sweden, Norway, and Quebec in Canada, have imposed restrictions or outright bans on advertising directed at young children. The spread of "native advertising" and "influencer marketing" — in which promotional content is designed to resemble editorial content or personal recommendations — has raised further concerns about transparency and the blurring of boundaries between advertising and independent information.

Defenders of advertising argue that it serves essential economic and social functions. Advertising funds the majority of free media content — including journalism, search engines, social media platforms, and entertainment — that consumers rely on daily. It provides information that helps consumers make informed choices, promotes competition that drives down prices and stimulates innovation, and supports employment across a vast ecosystem of creative, media, and technology industries. The challenge for regulators, industry bodies, and society at large is to balance the legitimate commercial and informational functions of advertising with the need to protect consumers — particularly vulnerable populations — from manipulation, deception, and harm.`,
      questions: [
        { number: 27, type: "matching_information", text: "Information about restrictions on advertising to children in specific countries", options: ["Paragraph 1", "Paragraph 2", "Paragraph 3", "Paragraph 4", "Paragraph 5", "Paragraph 6"], correctAnswer: "Paragraph 5", explanation: "Paragraph 5 mentions Sweden, Norway, and Quebec banning ads directed at young children." },
        { number: 28, type: "matching_information", text: "A description of how emotional manipulation became a dominant advertising approach", options: ["Paragraph 1", "Paragraph 2", "Paragraph 3", "Paragraph 4", "Paragraph 5", "Paragraph 6"], correctAnswer: "Paragraph 2", explanation: "Paragraph 2 describes John B. Watson's emotional approach to advertising." },
        { number: 29, type: "matching_information", text: "An explanation of how online platforms use data to deliver targeted ads", options: ["Paragraph 1", "Paragraph 2", "Paragraph 3", "Paragraph 4", "Paragraph 5", "Paragraph 6"], correctAnswer: "Paragraph 4", explanation: "Paragraph 4 discusses Google, Meta, programmatic advertising, and retargeting." },
        { number: 30, type: "matching_information", text: "Arguments that advertising provides economic benefits to society", options: ["Paragraph 1", "Paragraph 2", "Paragraph 3", "Paragraph 4", "Paragraph 5", "Paragraph 6"], correctAnswer: "Paragraph 6", explanation: "Paragraph 6 discusses advertising's role in funding media and promoting competition." },
        { number: 31, type: "matching_information", text: "The use of cognitive biases such as social proof and scarcity in advertising", options: ["Paragraph 1", "Paragraph 2", "Paragraph 3", "Paragraph 4", "Paragraph 5", "Paragraph 6"], correctAnswer: "Paragraph 3", explanation: "Paragraph 3 describes social proof, scarcity principle, and anchoring." },
        { number: 32, type: "multiple_choice", text: "What three emotions did Watson believe advertising should target?", options: ["A. Joy, sadness, and surprise", "B. Love, fear, and rage", "C. Curiosity, pride, and guilt", "D. Excitement, boredom, and satisfaction"], correctAnswer: "B", explanation: "The passage says Watson argued advertising should appeal to 'love, fear, and rage.'" },
        { number: 33, type: "multiple_choice", text: "What is the 'mere exposure effect'?", options: ["A. People avoid things they see too often", "B. Repeated exposure to something increases familiarity and liking", "C. First impressions are always the strongest", "D. Consumers only buy products they have physically touched"], correctAnswer: "B", explanation: "The passage defines it as 'repeated exposure to a stimulus increases familiarity and liking.'" },
        { number: 34, type: "multiple_choice", text: "How much revenue did the global advertising industry generate in 2022?", options: ["A. $580 billion", "B. $680 billion", "C. $780 billion", "D. $880 billion"], correctAnswer: "C", explanation: "The passage says 'an estimated $780 billion in revenue in 2022.'" },
        { number: 35, type: "multiple_choice", text: "At what age can children generally recognise persuasive intent in advertising?", options: ["A. Under 5 years old", "B. Under 8 years old", "C. Under 12 years old", "D. Under 16 years old"], correctAnswer: "B", explanation: "The passage says 'children under the age of eight generally lack the cognitive ability to recognise persuasive intent.'" },
        { number: 36, type: "short_answer", text: "Which advertising agency did John B. Watson join in 1921?", correctAnswer: "J. Walter Thompson", explanation: "The passage says he joined 'the J. Walter Thompson advertising agency.'" },
        { number: 37, type: "short_answer", text: "What is the term for ads that resemble editorial content or personal recommendations?", correctAnswer: "native advertising", explanation: "The passage refers to 'native advertising' and 'influencer marketing.'" },
        { number: 38, type: "short_answer", text: "What term describes the automated buying and selling of ad space through real-time auctions?", correctAnswer: "programmatic advertising", explanation: "The passage defines this as 'Programmatic advertising.'" },
        { number: 39, type: "short_answer", text: "What cognitive bias is exploited by displaying a high original price next to a lower sale price?", correctAnswer: "anchoring", explanation: "The passage says 'Anchoring... is exploited when retailers display a high \"original\" price next to a lower \"sale\" price.'" },
        { number: 40, type: "short_answer", text: "What advertising practice involves showing ads for products a consumer has previously viewed?", correctAnswer: "retargeting", explanation: "The passage defines 'Retargeting — the practice of showing advertisements for products that a consumer has previously viewed.'" },
      ],
    },
  ],
};
