import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_16: ReadingTest = {
  id: 16,
  passages: [
    {
      title: "The History of Musical Instruments",
      text: `Music is one of the oldest and most universal forms of human expression, and the instruments through which it is produced have evolved continuously over tens of thousands of years. Archaeological discoveries, historical records, and surviving artefacts together reveal a rich and complex story of technological innovation, cultural exchange, and artistic creativity that spans every continent and civilisation.

The earliest known musical instruments are bone flutes discovered in caves in present-day Germany and Slovenia, dating back approximately 40,000 years to the Upper Palaeolithic period. These flutes, carved from the wing bones of large birds and the ivory of mammoths, feature carefully spaced finger holes that indicate a deliberate attempt to produce specific pitches — evidence that early humans possessed a sophisticated understanding of musical scales. The discovery of these instruments alongside cave paintings and carved figurines suggests that music was an integral part of the cultural and spiritual life of prehistoric communities.

Percussion instruments are believed to be even older than flutes, though they are harder to identify in the archaeological record because they were often made from perishable materials such as wood, animal skins, and gourds. Drums, rattles, and scrapers appear in virtually every ancient culture, serving roles in religious ceremonies, warfare, communication, and social gatherings. The frame drum — a shallow, single-headed drum held in one hand and struck with the other — is depicted in Mesopotamian art dating to approximately 3000 BCE and remains one of the most widespread percussion instruments in the world today.

Stringed instruments first appeared in the ancient civilisations of Mesopotamia and Egypt around 2500 BCE. The lyre, a U-shaped frame with strings stretched between two arms and a crossbar, was one of the most important instruments in Sumerian, Babylonian, Greek, and Roman music. The Royal Tombs of Ur in modern-day Iraq yielded elaborately decorated lyres dating to approximately 2600 BCE, some adorned with gold and lapis lazuli, indicating that these instruments held considerable cultural and ceremonial significance. The harp, a related instrument in which the strings run at an angle from the soundboard rather than parallel to it, was widely used in ancient Egypt and is depicted in numerous tomb paintings.

Wind instruments diversified significantly during the classical and medieval periods. The ancient Greeks developed the aulos, a double-reeded instrument similar to the modern oboe, which was a central feature of dramatic performances, athletic competitions, and religious rituals. The Romans adopted and adapted Greek instruments, adding brass instruments such as the tuba (a long, straight trumpet) and the cornu (a curved horn) for military signalling and ceremonial occasions. In medieval Europe, the development of the pipe organ — an instrument that produces sound by forcing air through a series of tuned pipes — represented a major feat of engineering and became closely associated with Christian worship.

The development of keyboard instruments from the fourteenth century onwards marked a new chapter in musical history. The clavichord and harpsichord, both of which produce sound by striking or plucking strings activated by a keyboard mechanism, became popular in Renaissance and Baroque Europe. The invention of the pianoforte (piano) by the Italian instrument maker Bartolomeo Cristofori around 1700 was a revolutionary advance: unlike the harpsichord, the piano could vary the volume of each note depending on how hard the key was struck, enabling a new level of dynamic expression. The piano rapidly became the dominant instrument of Western classical music and remains one of the most widely played instruments in the world.

The nineteenth and twentieth centuries saw the development of entirely new families of instruments driven by advances in materials science and manufacturing technology. Adolphe Sax invented the saxophone in the 1840s, creating a hybrid instrument with a brass body and a single-reed mouthpiece that combined the projection of a brass instrument with the agility of a woodwind. The electric guitar, developed in the 1930s, used electromagnetic pickups to convert string vibrations into electrical signals that could be amplified, opening the door to the explosive growth of rock, blues, and popular music in the second half of the twentieth century.

The digital revolution has added yet another dimension to the evolution of musical instruments. Electronic synthesisers, first developed in the 1960s and 1970s, generate sound entirely through electronic circuits, enabling the creation of an infinite range of tones, textures, and effects. Modern digital audio workstations (DAWs) and MIDI controllers have blurred the boundary between instrument and recording studio, empowering musicians to compose, perform, and produce music using software tools that would have been inconceivable to earlier generations.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "The bone flutes found in Germany and Slovenia are significant because they", options: ["A are the oldest objects ever discovered in Europe.", "B show that early humans understood musical pitch.", "C were used exclusively for religious ceremonies.", "D prove that prehistoric humans could read music."], correctAnswer: "B", explanation: "The passage says the finger holes 'indicate a deliberate attempt to produce specific pitches' showing 'sophisticated understanding of musical scales.'" },
        { number: 2, type: "multiple_choice", text: "Percussion instruments are difficult to find archaeologically because", options: ["A ancient peoples did not value them.", "B they were too small to survive.", "C they were often made from materials that decay.", "D they were deliberately destroyed after use."], correctAnswer: "C", explanation: "The passage says they 'were often made from perishable materials such as wood, animal skins, and gourds.'" },
        { number: 3, type: "multiple_choice", text: "The lyres found at the Royal Tombs of Ur suggest that", options: ["A the Sumerians invented stringed instruments.", "B lyres were only played by royalty.", "C these instruments had important cultural significance.", "D Sumerian music was more advanced than Egyptian music."], correctAnswer: "C", explanation: "The passage says the elaborate decoration indicates 'considerable cultural and ceremonial significance.'" },
        { number: 4, type: "multiple_choice", text: "The piano was revolutionary compared to the harpsichord because it could", options: ["A produce a wider range of notes.", "B vary the volume of individual notes.", "C be played more quickly.", "D be manufactured more cheaply."], correctAnswer: "B", explanation: "The passage says 'the piano could vary the volume of each note depending on how hard the key was struck.'" },
        { number: 5, type: "multiple_choice", text: "The saxophone is described as a hybrid instrument because it combines features of", options: ["A string and wind instruments.", "B brass and woodwind instruments.", "C keyboard and percussion instruments.", "D electronic and acoustic instruments."], correctAnswer: "B", explanation: "The passage describes it as having 'a brass body and a single-reed mouthpiece' combining brass projection with woodwind agility." },
        { number: 6, type: "sentence_completion", text: "The earliest bone flutes date back approximately _______ years.", correctAnswer: "40,000", explanation: "The passage states 'dating back approximately 40,000 years.'" },
        { number: 7, type: "sentence_completion", text: "The frame drum is depicted in Mesopotamian art from approximately _______ BCE.", correctAnswer: "3000", explanation: "The passage says 'depicted in Mesopotamian art dating to approximately 3000 BCE.'" },
        { number: 8, type: "sentence_completion", text: "Stringed instruments first appeared around _______ BCE.", correctAnswer: "2500", explanation: "The passage states 'around 2500 BCE.'" },
        { number: 9, type: "sentence_completion", text: "The Greek aulos was similar to the modern _______.", correctAnswer: "oboe", explanation: "The passage describes it as 'similar to the modern oboe.'" },
        { number: 10, type: "sentence_completion", text: "The pianoforte was invented by _______ around 1700.", correctAnswer: "Bartolomeo Cristofori", explanation: "The passage names 'the Italian instrument maker Bartolomeo Cristofori.'" },
        { number: 11, type: "sentence_completion", text: "The saxophone was invented by Adolphe Sax in the _______.", correctAnswer: "1840s", explanation: "The passage says 'Adolphe Sax invented the saxophone in the 1840s.'" },
        { number: 12, type: "sentence_completion", text: "The electric guitar used electromagnetic _______ to convert string vibrations into electrical signals.", correctAnswer: "pickups", explanation: "The passage mentions 'electromagnetic pickups to convert string vibrations.'" },
        { number: 13, type: "sentence_completion", text: "Electronic synthesisers were first developed in the 1960s and _______.", correctAnswer: "1970s", explanation: "The passage says 'first developed in the 1960s and 1970s.'" },
      ],
    },
    {
      title: "Global Water Resources",
      text: `A. Water is fundamental to all life on Earth, yet its availability as a resource for human use is far more limited than most people realise. Although approximately 71 percent of the Earth's surface is covered by water, 97.5 percent of this is saltwater in the oceans, leaving just 2.5 percent as freshwater. Of that freshwater, approximately 69 percent is locked in glaciers and ice caps, and a further 30 percent exists as groundwater, much of it at depths that are difficult or expensive to access. Only about 1 percent of the world's freshwater — less than 0.01 percent of all water on Earth — is readily available in rivers, lakes, and shallow aquifers for human consumption, agriculture, and industry.

B. The distribution of freshwater resources across the globe is profoundly unequal. Brazil, Russia, Canada, the United States, and China together possess approximately 40 percent of the world's renewable freshwater, while many of the world's most populous regions — including the Middle East, North Africa, and parts of South Asia — face chronic water scarcity. Water scarcity is conventionally defined as the availability of less than 1,000 cubic metres of renewable freshwater per person per year. By this measure, approximately 2.3 billion people currently live in water-stressed countries, and the United Nations projects that by 2050, more than half the world's population could face severe water stress due to the combined effects of population growth, economic development, and climate change.

C. Agriculture is by far the largest consumer of freshwater resources globally, accounting for approximately 70 percent of all withdrawals. Irrigation is essential for food production in many parts of the world, particularly in arid and semi-arid regions where rainfall alone is insufficient to sustain crops. However, much irrigation water is used inefficiently: flood irrigation, in which fields are simply inundated with water, remains common in many developing countries despite wasting up to 50 percent of the water applied through evaporation, runoff, and deep percolation. More efficient technologies such as drip irrigation, which delivers water directly to plant roots through a network of tubes and emitters, can reduce water use by 30 to 60 percent while maintaining or increasing crop yields.

D. Groundwater — water stored beneath the Earth's surface in porous rock formations known as aquifers — is the primary source of freshwater for approximately 2.5 billion people worldwide. In many regions, groundwater is being extracted at rates far exceeding natural recharge, leading to falling water tables, land subsidence, and the depletion of aquifers that took thousands of years to fill. The Ogallala Aquifer in the central United States, one of the world's largest, has declined by more than 30 metres in some areas since large-scale irrigation began in the 1950s. In India, which is the world's largest user of groundwater, an estimated 60 percent of districts face critical or over-exploited groundwater conditions. The depletion of groundwater reserves threatens both food security and the long-term viability of communities that depend on wells for their water supply.

E. Climate change is intensifying the challenges facing global water resources in multiple ways. Rising temperatures increase evaporation rates, reducing soil moisture and water availability in many regions. Changes in precipitation patterns are making wet regions wetter and dry regions drier, exacerbating existing inequalities in water distribution. The melting of glaciers — which serve as natural water storage systems, releasing meltwater during dry summer months — threatens the water supply of hundreds of millions of people in regions such as the Himalayas, the Andes, and Central Asia. More frequent and intense droughts, punctuated by episodes of extreme flooding, are straining water management infrastructure and increasing the risk of humanitarian crises.

F. Addressing the global water challenge requires a comprehensive approach that combines technological innovation, institutional reform, and behavioural change. Investments in water-efficient technologies — including drip irrigation, smart metering, leak detection systems, and wastewater recycling — can significantly reduce demand. Desalination of seawater, though energy-intensive, is becoming increasingly cost-effective and is already a major source of freshwater in countries such as Israel, Saudi Arabia, and Singapore. Equally important are improvements in water governance: establishing clear water rights, pricing water to reflect its true cost, strengthening regulatory institutions, and ensuring that the needs of the poorest and most vulnerable communities are prioritised. International cooperation on shared river basins and transboundary aquifers is essential to prevent conflicts and ensure equitable access to this most vital of resources.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Paragraph B", options: ["i. The impact of rising temperatures on water availability", "ii. Unequal global distribution of freshwater", "iii. Solutions for the water crisis", "iv. Agriculture's dominant role in water consumption", "v. The limited nature of available freshwater", "vi. Declining underground water reserves", "vii. Water pricing and market mechanisms", "viii. Conflicts over shared water resources"], correctAnswer: "ii", explanation: "Paragraph B discusses the unequal distribution of freshwater, naming countries with most resources and those facing scarcity." },
        { number: 15, type: "matching_headings", text: "Paragraph C", options: ["i. The impact of rising temperatures on water availability", "ii. Unequal global distribution of freshwater", "iii. Solutions for the water crisis", "iv. Agriculture's dominant role in water consumption", "v. The limited nature of available freshwater", "vi. Declining underground water reserves", "vii. Water pricing and market mechanisms", "viii. Conflicts over shared water resources"], correctAnswer: "iv", explanation: "Paragraph C focuses on agriculture using 70% of freshwater and irrigation efficiency." },
        { number: 16, type: "matching_headings", text: "Paragraph D", options: ["i. The impact of rising temperatures on water availability", "ii. Unequal global distribution of freshwater", "iii. Solutions for the water crisis", "iv. Agriculture's dominant role in water consumption", "v. The limited nature of available freshwater", "vi. Declining underground water reserves", "vii. Water pricing and market mechanisms", "viii. Conflicts over shared water resources"], correctAnswer: "vi", explanation: "Paragraph D discusses groundwater depletion, the Ogallala Aquifer, and India's over-exploited conditions." },
        { number: 17, type: "matching_headings", text: "Paragraph E", options: ["i. The impact of rising temperatures on water availability", "ii. Unequal global distribution of freshwater", "iii. Solutions for the water crisis", "iv. Agriculture's dominant role in water consumption", "v. The limited nature of available freshwater", "vi. Declining underground water reserves", "vii. Water pricing and market mechanisms", "viii. Conflicts over shared water resources"], correctAnswer: "i", explanation: "Paragraph E discusses how climate change intensifies water challenges through rising temperatures and glacier melt." },
        { number: 18, type: "matching_headings", text: "Paragraph F", options: ["i. The impact of rising temperatures on water availability", "ii. Unequal global distribution of freshwater", "iii. Solutions for the water crisis", "iv. Agriculture's dominant role in water consumption", "v. The limited nature of available freshwater", "vi. Declining underground water reserves", "vii. Water pricing and market mechanisms", "viii. Conflicts over shared water resources"], correctAnswer: "iii", explanation: "Paragraph F discusses technological, institutional, and governance solutions." },
        { number: 19, type: "summary_completion", text: "Saltwater makes up _______ percent of all water on Earth.", correctAnswer: "97.5", explanation: "The passage states '97.5 percent of this is saltwater.'" },
        { number: 20, type: "summary_completion", text: "Approximately _______ percent of freshwater is trapped in glaciers and ice caps.", correctAnswer: "69", explanation: "The passage says 'approximately 69 percent is locked in glaciers and ice caps.'" },
        { number: 21, type: "summary_completion", text: "Water scarcity is defined as less than _______ cubic metres per person per year.", correctAnswer: "1,000", explanation: "The passage defines it as 'less than 1,000 cubic metres.'" },
        { number: 22, type: "summary_completion", text: "Approximately _______ billion people currently live in water-stressed countries.", correctAnswer: "2.3", explanation: "The passage says 'approximately 2.3 billion people.'" },
        { number: 23, type: "summary_completion", text: "Flood irrigation can waste up to _______ percent of water applied.", correctAnswer: "50", explanation: "The passage says 'wasting up to 50 percent.'" },
        { number: 24, type: "summary_completion", text: "Drip irrigation can reduce water use by _______ to 60 percent.", correctAnswer: "30", explanation: "The passage states 'reduce water use by 30 to 60 percent.'" },
        { number: 25, type: "summary_completion", text: "The Ogallala Aquifer has declined by more than _______ metres in some areas.", correctAnswer: "30", explanation: "The passage says 'declined by more than 30 metres.'" },
        { number: 26, type: "summary_completion", text: "In India, an estimated _______ percent of districts face critical groundwater conditions.", correctAnswer: "60", explanation: "The passage states 'an estimated 60 percent of districts.'" },
      ],
    },
    {
      title: "Artificial Intelligence in Medicine",
      text: `The application of artificial intelligence to medicine is one of the most promising and rapidly developing areas of healthcare innovation. AI technologies — encompassing machine learning, deep learning, natural language processing, computer vision, and robotics — are being deployed across the full spectrum of medical practice, from disease prevention and diagnosis to treatment planning, drug discovery, and health system management. While the potential benefits are enormous, the integration of AI into clinical practice also raises important challenges related to safety, regulation, equity, and the evolving role of healthcare professionals.

A. Medical imaging is widely regarded as the field where AI has made the most significant clinical impact to date. Deep learning algorithms trained on millions of medical images have demonstrated the ability to detect and classify abnormalities in radiographs, CT scans, MRI images, and pathology slides with accuracy comparable to — and in some cases exceeding — that of experienced human specialists. In dermatology, AI systems have matched board-certified dermatologists in distinguishing malignant melanomas from benign skin lesions using photographs. In ophthalmology, Google Health's AI system for detecting diabetic retinopathy — a leading cause of blindness — has achieved sensitivity and specificity rates above 90 percent in clinical trials and has been approved for autonomous screening (without human oversight) in Thailand and India, where the shortage of trained ophthalmologists is acute.

B. Clinical decision support systems (CDSS) powered by AI are helping physicians make more informed diagnostic and treatment decisions. These systems analyse patient data — including medical history, laboratory results, imaging findings, genetic information, and published medical literature — to generate probabilistic assessments of diagnoses and recommend evidence-based treatment options. IBM's Watson for Oncology, one of the most publicised CDSS platforms, was designed to recommend cancer treatment protocols by analysing patient records against thousands of published studies and clinical guidelines. However, Watson for Oncology also illustrated the challenges of deploying AI in clinical settings: studies revealed that the system sometimes generated recommendations that conflicted with expert opinion, and its adoption was hindered by limited training data from non-Western populations and a lack of transparency in its reasoning processes.

C. Drug discovery is an area where AI is expected to deliver transformative results by dramatically reducing the time and cost of developing new therapies. The traditional drug development process — from initial target identification to regulatory approval — typically takes 10 to 15 years and costs an average of $2.6 billion. AI-powered platforms can screen billions of molecular compounds, predict their interactions with biological targets, and identify promising drug candidates in a fraction of the time required by conventional methods. In 2020, Insilico Medicine used its AI platform to identify a novel drug candidate for idiopathic pulmonary fibrosis in just 18 months — a process that would typically take four to five years. AlphaFold, developed by Google DeepMind, has predicted the three-dimensional structures of virtually all known proteins, providing researchers with an invaluable resource for understanding disease mechanisms and designing targeted therapies.

D. AI-powered remote monitoring and telemedicine systems are expanding access to healthcare, particularly in underserved and rural communities. Wearable devices equipped with sensors can continuously monitor vital signs such as heart rate, blood oxygen levels, blood pressure, and electrocardiogram (ECG) patterns, alerting patients and healthcare providers to abnormalities in real time. AI algorithms can analyse data from these devices to detect early signs of conditions such as atrial fibrillation, sleep apnoea, and diabetic emergencies, enabling timely intervention before symptoms become critical. During the COVID-19 pandemic, AI-enhanced telemedicine platforms saw explosive growth, enabling millions of patients to receive consultations, prescriptions, and follow-up care remotely, reducing pressure on overwhelmed hospital systems.

E. The ethical and regulatory landscape of AI in medicine is complex and evolving. Questions of algorithmic bias are particularly pressing: AI systems trained predominantly on data from specific demographic groups may perform less accurately for patients of different ethnicities, genders, or age groups, potentially exacerbating existing health disparities. A widely cited study published in Science in 2019 found that a commercial algorithm used by US hospitals to allocate healthcare resources systematically underestimated the health needs of Black patients, affecting an estimated 70 million patient records. Transparency and explainability — the ability to understand how an AI system arrives at its recommendations — are critical for building trust among clinicians and patients, yet many deep learning models operate as "black boxes" whose internal reasoning processes are opaque. Regulatory bodies such as the US Food and Drug Administration (FDA) and the European Medicines Agency (EMA) are developing new frameworks for evaluating and approving AI-based medical devices, but the pace of innovation continues to outstrip the pace of regulation.`,
      questions: [
        { number: 27, type: "matching_information", text: "An AI system approved for use without human supervision in screening patients", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E"], correctAnswer: "A", explanation: "Paragraph A describes Google Health's diabetic retinopathy system approved 'for autonomous screening (without human oversight).'" },
        { number: 28, type: "matching_information", text: "An algorithm found to systematically disadvantage patients of a particular racial group", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E"], correctAnswer: "E", explanation: "Paragraph E describes the Science study finding an algorithm 'systematically underestimated the health needs of Black patients.'" },
        { number: 29, type: "matching_information", text: "A platform that generated treatment recommendations sometimes conflicting with expert opinion", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E"], correctAnswer: "B", explanation: "Paragraph B describes Watson for Oncology generating 'recommendations that conflicted with expert opinion.'" },
        { number: 30, type: "matching_information", text: "An AI system that predicted the structures of nearly all known proteins", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E"], correctAnswer: "C", explanation: "Paragraph C describes AlphaFold predicting 'the three-dimensional structures of virtually all known proteins.'" },
        { number: 31, type: "matching_information", text: "Devices that continuously track patients' vital signs and alert providers to problems", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E"], correctAnswer: "D", explanation: "Paragraph D describes wearable devices monitoring vital signs and 'alerting patients and healthcare providers.'" },
        { number: 32, type: "multiple_choice", text: "In dermatology, AI systems have been shown to", options: ["A replace dermatologists entirely.", "B match specialists in identifying melanomas.", "C detect skin conditions that humans cannot see.", "D work only with laboratory-quality images."], correctAnswer: "B", explanation: "The passage says AI systems 'matched board-certified dermatologists in distinguishing malignant melanomas.'" },
        { number: 33, type: "multiple_choice", text: "The traditional drug development process typically costs", options: ["A $260 million.", "B $1 billion.", "C $2.6 billion.", "D $10 billion."], correctAnswer: "C", explanation: "The passage states it 'costs an average of $2.6 billion.'" },
        { number: 34, type: "multiple_choice", text: "Insilico Medicine's AI platform identified a drug candidate in", options: ["A 6 months.", "B 18 months.", "C 3 years.", "D 5 years."], correctAnswer: "B", explanation: "The passage says 'in just 18 months.'" },
        { number: 35, type: "multiple_choice", text: "The biased healthcare algorithm affected an estimated", options: ["A 7 million patient records.", "B 17 million patient records.", "C 70 million patient records.", "D 700 million patient records."], correctAnswer: "C", explanation: "The passage states 'affecting an estimated 70 million patient records.'" },
        { number: 36, type: "multiple_choice", text: "A key challenge with deep learning models in medicine is that they", options: ["A require too much electricity to operate.", "B can only process text data.", "C function as 'black boxes' with opaque reasoning.", "D are too slow for real-time clinical use."], correctAnswer: "C", explanation: "The passage says many models 'operate as \"black boxes\" whose internal reasoning processes are opaque.'" },
        { number: 37, type: "multiple_choice", text: "Google Health's diabetic retinopathy system achieved sensitivity rates of", options: ["A above 70 percent.", "B above 80 percent.", "C above 90 percent.", "D 100 percent."], correctAnswer: "C", explanation: "The passage states 'sensitivity and specificity rates above 90 percent.'" },
        { number: 38, type: "multiple_choice", text: "The traditional drug development timeline is typically", options: ["A 3 to 5 years.", "B 5 to 8 years.", "C 10 to 15 years.", "D 20 to 25 years."], correctAnswer: "C", explanation: "The passage says it 'typically takes 10 to 15 years.'" },
        { number: 39, type: "multiple_choice", text: "During COVID-19, AI-enhanced telemedicine helped by", options: ["A replacing all in-person hospital visits.", "B enabling remote consultations for millions.", "C eliminating the need for prescriptions.", "D training new doctors online."], correctAnswer: "B", explanation: "The passage says platforms 'enabling millions of patients to receive consultations remotely.'" },
        { number: 40, type: "multiple_choice", text: "Which regulatory body is mentioned as developing frameworks for AI medical devices?", options: ["A World Health Organization.", "B US Centers for Disease Control.", "C US Food and Drug Administration.", "D International Medical Association."], correctAnswer: "C", explanation: "The passage mentions 'the US Food and Drug Administration (FDA).'" },
      ],
    },
  ],
};
