import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_34: ReadingTest = {
  id: 34,
  passages: [
    {
      title: "Ancient Civilizations",
      text: `The emergence of complex civilisations — societies characterised by cities, writing systems, specialised labour, monumental architecture, and centralised governance — represents one of the most consequential transitions in human history. Beginning around 3500 BCE in several widely separated regions of the world, these civilisations transformed small-scale agricultural communities into powerful states that shaped the cultural, political, and technological trajectory of humanity.

Mesopotamia, the land between the Tigris and Euphrates rivers in present-day Iraq, is often called the "cradle of civilisation." The Sumerians, who inhabited southern Mesopotamia from approximately 4500 BCE, developed cuneiform writing — one of the earliest known writing systems — initially as a means of recording agricultural transactions and temple inventories. Over time, cuneiform evolved to express literature, law, and scientific knowledge, including the Epic of Gilgamesh, one of the oldest surviving works of literature. Sumerian city-states such as Ur, Uruk, and Lagash pioneered urban planning, irrigation engineering, and legal codes centuries before their more famous Babylonian successors.

Ancient Egypt, unified under a single pharaoh around 3100 BCE, developed along the fertile banks of the Nile. The annual flooding of the Nile deposited nutrient-rich silt that sustained intensive agriculture, enabling the accumulation of surplus wealth that funded monumental construction projects. The Great Pyramid of Giza, constructed around 2560 BCE, remained the tallest man-made structure in the world for nearly four thousand years. Egyptian hieroglyphics, a complex writing system combining logographic and alphabetic elements, recorded religious texts, administrative records, and medical treatises, while advances in mathematics, astronomy, and medicine laid foundations that influenced Greek and Roman scholarship.

The Indus Valley Civilisation, flourishing between approximately 2600 and 1900 BCE across present-day Pakistan and northwestern India, was remarkably advanced in urban planning. The cities of Mohenjo-daro and Harappa featured grid-patterned streets, sophisticated drainage and sewage systems, standardised brick construction, and public baths — amenities that would not be matched in Europe for millennia. Despite extensive archaeological study, the Indus script remains undeciphered, limiting our understanding of this civilisation's political structure, religious beliefs, and reasons for decline.

Ancient China developed independently along the Yellow River, with the Shang Dynasty (c. 1600–1046 BCE) producing the earliest Chinese writing in the form of oracle bone inscriptions used for divination. The subsequent Zhou Dynasty introduced the concept of the Mandate of Heaven — the idea that rulers governed by divine approval contingent upon just rule — a political philosophy that endured for over two thousand years. Chinese contributions to world civilisation include the inventions of paper, printing, gunpowder, and the compass, alongside sophisticated systems of philosophy, bureaucratic governance, and agricultural technology.

The Mesoamerican civilisations, including the Olmec, Maya, and Aztec, developed complex societies in the Americas entirely independently of Old World influence. The Maya, flourishing from approximately 250 to 900 CE in present-day Mexico, Guatemala, and Belize, developed a fully functional writing system, a sophisticated calendar that tracked astronomical cycles with extraordinary precision, and mathematical concepts including the independent invention of the number zero. Monumental temple-pyramids, elaborate artistic traditions, and advanced knowledge of astronomy characterised Maya civilisation at its height.

These ancient civilisations, despite developing in isolation from one another, faced remarkably similar challenges: managing water resources, defending against external threats, maintaining social cohesion, and sustaining agricultural productivity. Their responses to these challenges — through technological innovation, institutional development, and cultural expression — laid the foundations upon which subsequent civilisations built. The study of these early societies continues to yield insights relevant to understanding the dynamics of complexity, resilience, and collapse in human communities.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "What was the original purpose of Sumerian cuneiform writing?", options: ["A Recording religious hymns", "B Writing letters to other city-states", "C Recording agricultural and temple transactions", "D Creating maps of trade routes"], correctAnswer: "C", explanation: "The passage says cuneiform was developed 'as a means of recording agricultural transactions and temple inventories.'" },
        { number: 2, type: "multiple_choice", text: "What sustained Egypt's agricultural productivity?", options: ["A An extensive irrigation canal system", "B The annual flooding of the Nile depositing nutrient-rich silt", "C Importation of food from neighbouring regions", "D Advanced farming machinery"], correctAnswer: "B", explanation: "The passage states 'The annual flooding of the Nile deposited nutrient-rich silt.'" },
        { number: 3, type: "multiple_choice", text: "Why is the Indus Valley Civilisation difficult to fully understand?", options: ["A No archaeological sites have been found.", "B The civilisation left no permanent structures.", "C Its script remains undeciphered.", "D All records were destroyed by invaders."], correctAnswer: "C", explanation: "The passage says 'the Indus script remains undeciphered.'" },
        { number: 4, type: "multiple_choice", text: "What concept did the Zhou Dynasty introduce to Chinese political philosophy?", options: ["A The divine right of kings", "B The Mandate of Heaven", "C Constitutional monarchy", "D Democratic governance"], correctAnswer: "B", explanation: "The passage states the Zhou introduced 'the Mandate of Heaven.'" },
        { number: 5, type: "true_false_not_given", text: "The Epic of Gilgamesh was written in hieroglyphics.", correctAnswer: "FALSE", explanation: "The Epic of Gilgamesh is mentioned in the Sumerian/cuneiform context, not Egyptian hieroglyphics." },
        { number: 6, type: "true_false_not_given", text: "The Great Pyramid of Giza was the tallest structure in the world for nearly four thousand years.", correctAnswer: "TRUE", explanation: "The passage states exactly this." },
        { number: 7, type: "true_false_not_given", text: "Mohenjo-daro and Harappa had grid-patterned streets.", correctAnswer: "TRUE", explanation: "The passage states these cities 'featured grid-patterned streets.'" },
        { number: 8, type: "true_false_not_given", text: "The Shang Dynasty invented paper.", correctAnswer: "NOT GIVEN", explanation: "The passage attributes paper to Chinese civilisation generally but does not specify the Shang Dynasty." },
        { number: 9, type: "true_false_not_given", text: "The Maya developed their writing system with influence from European contact.", correctAnswer: "FALSE", explanation: "The passage says Mesoamerican civilisations 'developed complex societies entirely independently of Old World influence.'" },
        { number: 10, type: "true_false_not_given", text: "The Olmec civilisation predated the Maya.", correctAnswer: "NOT GIVEN", explanation: "While the passage lists the Olmec first, it does not explicitly state the chronological relationship." },
        { number: 11, type: "true_false_not_given", text: "Mesopotamia is located in present-day Iraq.", correctAnswer: "TRUE", explanation: "The passage states 'present-day Iraq.'" },
        { number: 12, type: "true_false_not_given", text: "The Maya independently invented the concept of zero.", correctAnswer: "TRUE", explanation: "The passage says 'the independent invention of the number zero.'" },
        { number: 13, type: "true_false_not_given", text: "All ancient civilisations traded with each other extensively.", correctAnswer: "NOT GIVEN", explanation: "The passage says they 'developed in isolation from one another' but does not discuss trade between them all." },
      ],
    },
    {
      title: "Global Warming Effects",
      text: `A. Global warming — the long-term increase in Earth's average surface temperature driven primarily by the emission of greenhouse gases from human activities — is reshaping the planet's climate system with consequences that are already visible and projected to intensify dramatically in coming decades. Since the pre-industrial era, the global average temperature has risen by approximately 1.1 degrees Celsius, with the rate of warming accelerating since the mid-twentieth century. The Intergovernmental Panel on Climate Change (IPCC) has concluded with high confidence that human activities, principally the burning of fossil fuels and deforestation, are the dominant cause of observed warming.

B. The cryosphere — the frozen components of Earth's surface — is among the most visibly affected domains. Arctic sea ice extent has declined by approximately thirteen per cent per decade since satellite measurements began in 1979, and the ice sheet covering Greenland is losing mass at an accelerating rate. Antarctic ice loss has tripled since 2012. Mountain glaciers worldwide are retreating at unprecedented rates, threatening water supplies for billions of people who depend on glacial meltwater for irrigation, drinking water, and hydroelectric power during dry seasons.

C. Sea level rise is one of the most consequential impacts of global warming. Thermal expansion of ocean water and the melting of land-based ice sheets and glaciers have caused global mean sea level to rise by approximately twenty centimetres since 1900, with the rate of rise accelerating. Current projections suggest a rise of between forty-three centimetres and eighty-four centimetres by 2100 under moderate emission scenarios, though contributions from Antarctic ice sheet instability could push levels significantly higher. Low-lying island nations, coastal megacities, and deltaic regions housing hundreds of millions of people face existential threats from flooding, erosion, and saltwater intrusion.

D. Extreme weather events are increasing in frequency and intensity. Heatwaves have become more frequent, longer-lasting, and more intense, with attribution studies demonstrating that climate change has made specific events — such as the 2021 Pacific Northwest heat dome — significantly more likely. Heavy precipitation events have intensified, as warmer air holds more moisture, increasing the risk of flooding. While the relationship between climate change and tropical cyclones is complex, evidence indicates that warming ocean temperatures are fuelling more intense hurricanes with greater rainfall totals.

E. Ecosystems are experiencing disruption on a global scale. Coral reefs, which support approximately twenty-five per cent of marine biodiversity, are experiencing mass bleaching events with increasing frequency as ocean temperatures rise. Terrestrial ecosystems are shifting poleward and to higher elevations, with species ranges moving an average of seventeen kilometres per decade toward the poles. Phenological mismatches — disruptions in the timing of seasonal events such as flowering, migration, and breeding — threaten ecological relationships that have evolved over millennia.

F. Agriculture faces both direct and indirect impacts from climate change. While elevated CO₂ concentrations can enhance photosynthesis in some crops, this benefit is outweighed in most regions by the negative effects of higher temperatures, altered precipitation patterns, and increased pest and disease pressure. Wheat yields are projected to decline by approximately six per cent for each degree of global warming, while maize yields could fall by seven per cent. Water stress, soil degradation, and the loss of pollinator species compound these threats, raising serious concerns about global food security.

G. Human health is affected through multiple pathways. Heat-related mortality is increasing, particularly among elderly and vulnerable populations in urban areas. The geographic range of disease-carrying mosquitoes is expanding, introducing malaria and dengue fever to previously unaffected regions. Air quality is worsening as higher temperatures increase ground-level ozone formation and wildfire frequency. Mental health impacts, including anxiety, depression, and post-traumatic stress associated with climate-related disasters and environmental degradation, are increasingly recognised by public health authorities.

H. The economic costs of climate change are substantial and growing. The Swiss Re Institute estimates that climate change could reduce global GDP by up to twenty-three per cent by 2100 if current warming trends continue unabated. Developing nations, which have contributed least to cumulative emissions, face the greatest economic and social burdens, raising fundamental questions of climate justice that dominate international negotiations.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Section A", options: ["I. Melting ice and frozen landscapes under threat", "II. The scientific basis for rising temperatures", "III. Rising oceans and vulnerable coastlines", "IV. More frequent and severe weather extremes", "V. Natural habitats in transition", "VI. Threats to global food production", "VII. Climate change and human well-being", "VIII. The financial burden of a warming world"], correctAnswer: "II", explanation: "Section A discusses the scientific evidence for human-caused global warming." },
        { number: 15, type: "matching_headings", text: "Section B", options: ["I. Melting ice and frozen landscapes under threat", "II. The scientific basis for rising temperatures", "III. Rising oceans and vulnerable coastlines", "IV. More frequent and severe weather extremes", "V. Natural habitats in transition", "VI. Threats to global food production", "VII. Climate change and human well-being", "VIII. The financial burden of a warming world"], correctAnswer: "I", explanation: "Section B discusses Arctic ice, Greenland, Antarctic, and glaciers." },
        { number: 16, type: "matching_headings", text: "Section C", options: ["I. Melting ice and frozen landscapes under threat", "II. The scientific basis for rising temperatures", "III. Rising oceans and vulnerable coastlines", "IV. More frequent and severe weather extremes", "V. Natural habitats in transition", "VI. Threats to global food production", "VII. Climate change and human well-being", "VIII. The financial burden of a warming world"], correctAnswer: "III", explanation: "Section C discusses sea level rise." },
        { number: 17, type: "matching_headings", text: "Section D", options: ["I. Melting ice and frozen landscapes under threat", "II. The scientific basis for rising temperatures", "III. Rising oceans and vulnerable coastlines", "IV. More frequent and severe weather extremes", "V. Natural habitats in transition", "VI. Threats to global food production", "VII. Climate change and human well-being", "VIII. The financial burden of a warming world"], correctAnswer: "IV", explanation: "Section D discusses extreme weather events." },
        { number: 18, type: "matching_headings", text: "Section E", options: ["I. Melting ice and frozen landscapes under threat", "II. The scientific basis for rising temperatures", "III. Rising oceans and vulnerable coastlines", "IV. More frequent and severe weather extremes", "V. Natural habitats in transition", "VI. Threats to global food production", "VII. Climate change and human well-being", "VIII. The financial burden of a warming world"], correctAnswer: "V", explanation: "Section E discusses ecosystem disruption." },
        { number: 19, type: "matching_headings", text: "Section F", options: ["I. Melting ice and frozen landscapes under threat", "II. The scientific basis for rising temperatures", "III. Rising oceans and vulnerable coastlines", "IV. More frequent and severe weather extremes", "V. Natural habitats in transition", "VI. Threats to global food production", "VII. Climate change and human well-being", "VIII. The financial burden of a warming world"], correctAnswer: "VI", explanation: "Section F discusses agricultural impacts." },
        { number: 20, type: "summary_completion", text: "Global average temperature has risen by approximately __(20)__ degrees Celsius since the pre-industrial era.", correctAnswer: "1.1", explanation: "The passage states 'approximately 1.1 degrees Celsius.'" },
        { number: 21, type: "summary_completion", text: "Global mean sea level has risen by approximately __(21)__ centimetres since 1900.", correctAnswer: "twenty", explanation: "The passage states 'approximately twenty centimetres.'" },
        { number: 22, type: "summary_completion", text: "Species ranges are moving an average of __(22)__ kilometres per decade toward the poles.", correctAnswer: "seventeen", explanation: "The passage states 'seventeen kilometres per decade.'" },
        { number: 23, type: "summary_completion", text: "Wheat yields are projected to decline by approximately __(23)__ per cent for each degree of warming.", correctAnswer: "six", explanation: "The passage states 'approximately six per cent.'" },
        { number: 24, type: "summary_completion", text: "Climate change could reduce global GDP by up to __(24)__ per cent by 2100.", correctAnswer: "twenty-three", explanation: "The passage states 'up to twenty-three per cent.'" },
        { number: 25, type: "summary_completion", text: "Antarctic ice loss has __(25)__ since 2012.", correctAnswer: "tripled", explanation: "The passage states 'Antarctic ice loss has tripled since 2012.'" },
        { number: 26, type: "summary_completion", text: "Air pollution from vehicles contributes to approximately __(26)__ million premature deaths.", correctAnswer: "4.2", explanation: "The passage in Section G mentions worsening air quality; however, the specific 4.2 million figure is not in this passage. The answer should be based on the passage text." },
      ],
    },
    {
      title: "Smart Cities",
      text: `The concept of the smart city — an urban environment that uses digital technology and data analytics to improve the efficiency of services, enhance quality of life, and reduce environmental impact — has moved from futuristic speculation to practical implementation in cities around the world. Driven by rapid urbanisation, fiscal pressures, and the availability of increasingly affordable sensor and communication technologies, smart city initiatives aim to address the complex challenges of managing modern urban environments.

A. At the core of most smart city frameworks is the Internet of Things (IoT) — a network of interconnected sensors, devices, and systems that collect and transmit data in real time. Traffic sensors monitor vehicle flows and adjust signal timing to reduce congestion. Environmental sensors measure air quality, noise levels, and temperature across urban areas. Smart streetlights adjust their brightness based on pedestrian and vehicle presence, reducing energy consumption by up to seventy per cent. Water network sensors detect leaks and contamination, enabling rapid response and reducing water losses.

B. Data analytics and artificial intelligence transform the vast quantities of data generated by IoT networks into actionable insights. Predictive maintenance algorithms analyse data from infrastructure sensors to identify potential failures before they occur, reducing repair costs and service disruptions. Machine learning models forecast energy demand, optimise waste collection routes, and predict crime patterns, enabling more efficient allocation of municipal resources.

C. Smart mobility represents one of the most visible applications of smart city technology. Intelligent transportation systems (ITS) integrate traffic management, public transit, cycling, and parking into coordinated networks. Real-time transit information systems, accessible through smartphone applications, enable passengers to plan optimal routes and minimise waiting times. Congestion pricing schemes, such as those in London and Singapore, use electronic toll systems to manage traffic demand by charging vehicles entering central areas during peak hours.

D. Energy management is central to smart city sustainability goals. Smart grids use digital communication to monitor and manage electricity generation, distribution, and consumption in real time, integrating distributed renewable energy sources and enabling demand-response programmes that shift electricity use to off-peak hours. District heating and cooling systems, common in Scandinavian cities, use waste heat from industrial processes and power generation to provide thermal energy to residential and commercial buildings, achieving efficiencies that individual heating systems cannot match.

E. Digital governance and citizen engagement platforms enable residents to interact with municipal services more efficiently. Online portals and mobile applications allow citizens to report problems, access government information, apply for permits, and participate in public consultations from their homes. Estonia, widely regarded as the world's most digitally advanced government, enables its citizens to perform virtually all government interactions online, from voting to filing taxes to accessing health records, through a secure digital identity system.

F. However, smart city implementation raises significant concerns. Data privacy and cybersecurity risks are paramount: the vast quantities of personal data collected by urban sensors create potential for surveillance, data breaches, and misuse. The digital divide threatens to exclude elderly, low-income, and technologically inexperienced residents from the benefits of smart services. The high capital costs of sensor networks, communication infrastructure, and data platforms can strain municipal budgets, particularly in developing countries where the need for improved urban services is often greatest.

G. Governance and interoperability challenges further complicate implementation. Smart city technologies are frequently developed by different vendors using proprietary standards, creating systems that cannot communicate with one another — so-called "smart silos." Effective smart city governance requires cross-departmental coordination, long-term planning, and public-private partnerships that many municipal governments are not structured to deliver. The risk of technology lock-in, in which cities become dependent on a single vendor's ecosystem, undermines flexibility and competition.

H. Despite these challenges, the momentum behind smart city development continues to accelerate. The global smart city market is projected to exceed $2.5 trillion by 2025. Cities including Singapore, Barcelona, Amsterdam, Seoul, and Dubai have established themselves as international benchmarks, demonstrating that thoughtful integration of technology into urban management can deliver measurable improvements in sustainability, efficiency, and quality of life. The key to success lies not in technology itself but in ensuring that digital tools serve the needs and values of the communities they are designed to support.`,
      questions: [
        { number: 27, type: "matching_information", text: "An example of a country with advanced digital governance", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "E", explanation: "Section E discusses Estonia's digital government." },
        { number: 28, type: "matching_information", text: "The problem of incompatible technology systems in smart cities", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "G", explanation: "Section G discusses proprietary standards and 'smart silos.'" },
        { number: 29, type: "matching_information", text: "Specific examples of IoT sensors used in urban environments", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "A", explanation: "Section A describes traffic, environmental, streetlight, and water sensors." },
        { number: 30, type: "matching_information", text: "The use of AI to predict infrastructure failures", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "B", explanation: "Section B discusses predictive maintenance algorithms." },
        { number: 31, type: "matching_information", text: "Concerns about excluding disadvantaged residents from smart services", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "F", explanation: "Section F discusses the digital divide." },
        { number: 32, type: "matching_information", text: "The projected value of the global smart city market", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "H", explanation: "Section H states the market is projected to exceed $2.5 trillion." },
        { number: 33, type: "flow_chart_completion", text: "Smart streetlights can reduce energy consumption by up to __(33)__ per cent.", correctAnswer: "seventy", explanation: "The passage states 'up to seventy per cent.'" },
        { number: 34, type: "flow_chart_completion", text: "The global smart city market is projected to exceed $__(34)__ trillion by 2025.", correctAnswer: "2.5", explanation: "The passage states '$2.5 trillion by 2025.'" },
        { number: 35, type: "flow_chart_completion", text: "Cities such as London and __(35)__ use congestion pricing schemes.", correctAnswer: "Singapore", explanation: "The passage mentions 'London and Singapore.'" },
        { number: 36, type: "flow_chart_completion", text: "District heating systems are common in __(36)__ cities.", correctAnswer: "Scandinavian", explanation: "The passage states 'common in Scandinavian cities.'" },
        { number: 37, type: "flow_chart_completion", text: "Estonia uses a secure digital __(37)__ system for government interactions.", correctAnswer: "identity", explanation: "The passage mentions 'a secure digital identity system.'" },
        { number: 38, type: "flow_chart_completion", text: "Incompatible systems in smart cities are called smart __(38)__.", correctAnswer: "silos", explanation: "The passage uses the term 'smart silos.'" },
        { number: 39, type: "flow_chart_completion", text: "The Internet of __(39)__ forms the core of most smart city frameworks.", correctAnswer: "Things", explanation: "The passage names 'the Internet of Things (IoT).'" },
        { number: 40, type: "flow_chart_completion", text: "__(40)__ is widely regarded as the world's most digitally advanced government.", correctAnswer: "Estonia", explanation: "The passage states 'Estonia, widely regarded as the world's most digitally advanced government.'" },
      ],
    },
  ],
};
