import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_26: ReadingTest = {
  id: 26,
  passages: [
    {
      title: "History of Clocks and Timekeeping",
      text: `The measurement of time has been a fundamental concern for human civilisations since antiquity. Early societies relied upon natural phenomena — the rising and setting of the sun, the phases of the moon, and the changing of seasons — to structure their daily lives. However, as communities grew more complex, the need for finer divisions of time became pressing, leading to the invention of increasingly sophisticated timekeeping devices.

Among the earliest instruments were sundials, which appeared in ancient Egypt around 1500 BCE. These devices cast a shadow onto a calibrated surface, allowing observers to track the sun's movement across the sky. While effective during daylight hours, sundials were rendered useless at night or on overcast days, a limitation that spurred the development of alternative technologies. Water clocks, known as clepsydrae, emerged as a solution. Used in Babylon, Egypt, and China, these devices measured time by the regulated flow of water from one vessel to another. The Greeks refined the clepsydra considerably, with the engineer Ctesibius of Alexandria creating an elaborate version around 270 BCE that incorporated gears and a dial to display hours.

The medieval period witnessed the introduction of mechanical clocks in Europe, a development that would revolutionise timekeeping. The earliest mechanical clocks appeared in monasteries during the thirteenth century, driven by the need to regulate prayer times. These devices used a verge-and-foliot escapement mechanism — a system of interlocking gears controlled by a weighted oscillator — to divide time into equal intervals. By the fourteenth century, large public clocks adorned cathedrals and town halls across Europe, becoming symbols of civic pride and technological achievement.

The accuracy of mechanical clocks improved dramatically with Christiaan Huygens' invention of the pendulum clock in 1656. By exploiting the regular oscillation of a swinging pendulum, Huygens reduced timekeeping errors from approximately fifteen minutes per day to roughly fifteen seconds. This breakthrough had profound implications for navigation, astronomy, and scientific research. The subsequent development of the spring-driven balance wheel by Robert Hooke further miniaturised clockwork, making portable watches feasible for the first time.

The eighteenth century brought the marine chronometer, developed by the English carpenter John Harrison. Navigators at sea had long struggled to determine longitude accurately, a problem that caused countless shipwrecks. Harrison's chronometers, refined over four decades, maintained remarkable precision despite the pitching and rolling of ships, effectively solving the longitude problem. His achievement earned him — after considerable controversy — the substantial prize offered by the British Board of Longitude.

The twentieth century ushered in entirely new paradigms of timekeeping. Quartz clocks, introduced commercially in the 1930s, used the piezoelectric vibrations of a quartz crystal to regulate time with unprecedented accuracy, losing only a few seconds per month. By the 1970s, affordable quartz watches had disrupted the traditional Swiss watchmaking industry in what became known as the "Quartz Crisis."

The current pinnacle of timekeeping technology is the atomic clock, first developed at the National Physical Laboratory in England in 1955. Atomic clocks measure the electromagnetic radiation emitted by caesium-133 atoms as they transition between energy levels, achieving accuracy to within one second over millions of years. The Global Positioning System (GPS), international financial markets, and modern telecommunications all depend on the extraordinary precision of atomic timekeeping. Today, optical lattice clocks promise even greater accuracy, potentially redefining the very second itself.

Throughout history, the quest for precise timekeeping has driven technological innovation and reshaped human society. From the sundials of ancient Egypt to the atomic clocks of the modern era, each advance in chronometry has expanded humanity's ability to coordinate activities, navigate the globe, and understand the natural world.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "What limitation of sundials led to the development of water clocks?", options: ["A They were too expensive to produce.", "B They could not function without sunlight.", "C They were inaccurate during summer months.", "D They required constant maintenance."], correctAnswer: "B", explanation: "The passage states sundials 'were rendered useless at night or on overcast days.'" },
        { number: 2, type: "multiple_choice", text: "According to the passage, what was the primary motivation for developing mechanical clocks in monasteries?", options: ["A To impress visiting dignitaries", "B To coordinate trade schedules", "C To regulate times of prayer", "D To advance scientific research"], correctAnswer: "C", explanation: "The passage states they were 'driven by the need to regulate prayer times.'" },
        { number: 3, type: "multiple_choice", text: "What impact did Huygens' pendulum clock have on timekeeping accuracy?", options: ["A It eliminated errors entirely.", "B It reduced errors from fifteen minutes to fifteen seconds per day.", "C It halved the existing error rate.", "D It improved accuracy only for maritime use."], correctAnswer: "B", explanation: "The passage states Huygens 'reduced timekeeping errors from approximately fifteen minutes per day to roughly fifteen seconds.'" },
        { number: 4, type: "multiple_choice", text: "What event is referred to as the 'Quartz Crisis'?", options: ["A A global shortage of quartz minerals", "B The disruption of the Swiss watchmaking industry by quartz watches", "C The failure of early quartz clocks in laboratory settings", "D A dispute between competing quartz manufacturers"], correctAnswer: "B", explanation: "The passage describes how affordable quartz watches 'disrupted the traditional Swiss watchmaking industry.'" },
        { number: 5, type: "true_false_not_given", text: "Water clocks were used exclusively in ancient Egypt.", correctAnswer: "FALSE", explanation: "The passage states they were 'Used in Babylon, Egypt, and China.'" },
        { number: 6, type: "true_false_not_given", text: "Ctesibius of Alexandria improved the design of the water clock.", correctAnswer: "TRUE", explanation: "The passage says 'the engineer Ctesibius of Alexandria creating an elaborate version around 270 BCE.'" },
        { number: 7, type: "true_false_not_given", text: "The verge-and-foliot mechanism was invented in China before reaching Europe.", correctAnswer: "NOT GIVEN", explanation: "The passage does not mention the origin of the verge-and-foliot mechanism in China." },
        { number: 8, type: "true_false_not_given", text: "John Harrison received the Board of Longitude prize without any dispute.", correctAnswer: "FALSE", explanation: "The passage says he earned it 'after considerable controversy.'" },
        { number: 9, type: "true_false_not_given", text: "Quartz clocks were first used in military applications.", correctAnswer: "NOT GIVEN", explanation: "The passage mentions they were 'introduced commercially' but does not mention military use." },
        { number: 10, type: "sentence_completion", text: "Early Egyptian sundials worked by casting a __(10)__ onto a calibrated surface.", correctAnswer: "shadow", explanation: "The passage states sundials 'cast a shadow onto a calibrated surface.'" },
        { number: 11, type: "sentence_completion", text: "Robert Hooke's spring-driven balance wheel made portable __(11)__ possible for the first time.", correctAnswer: "watches", explanation: "The passage says it made 'portable watches feasible for the first time.'" },
        { number: 12, type: "sentence_completion", text: "The first atomic clock was developed at the National Physical Laboratory in __(12)__.", correctAnswer: "England", explanation: "The passage states 'first developed at the National Physical Laboratory in England in 1955.'" },
        { number: 13, type: "sentence_completion", text: "Atomic clocks measure electromagnetic radiation emitted by __(13)__ atoms.", correctAnswer: "caesium-133", explanation: "The passage says they 'measure the electromagnetic radiation emitted by caesium-133 atoms.'" },
      ],
    },
    {
      title: "Sustainable Architecture",
      text: `A. The built environment is responsible for approximately forty per cent of global energy consumption and a comparable share of carbon dioxide emissions. As awareness of climate change has intensified, architects, engineers, and policymakers have turned their attention to sustainable architecture — an approach that seeks to minimise the environmental impact of buildings throughout their entire lifecycle, from construction through operation to eventual demolition.

B. The concept of designing in harmony with the environment is not entirely new. Vernacular architecture around the world has long incorporated passive strategies suited to local climates. Middle Eastern wind towers, for example, channel prevailing breezes into interior spaces, providing natural ventilation without mechanical cooling. Similarly, the thick adobe walls of traditional desert dwellings absorb heat during the day and release it slowly at night, moderating indoor temperatures. Modern sustainable architecture builds upon these time-tested principles while integrating contemporary materials and digital technologies.

C. One of the central tenets of sustainable design is energy efficiency. High-performance insulation, triple-glazed windows, and airtight building envelopes dramatically reduce the energy needed for heating and cooling. The Passivhaus standard, developed in Germany in the early 1990s, mandates that buildings consume no more than fifteen kilowatt-hours per square metre annually for space heating — roughly ninety per cent less than a conventional structure. Thousands of Passivhaus-certified buildings now exist across Europe, North America, and Asia, demonstrating that extreme energy efficiency is technically and economically viable.

D. Beyond reducing energy demand, sustainable architecture increasingly emphasises on-site renewable energy generation. Photovoltaic panels integrated into roofs and facades convert sunlight directly into electricity, while small-scale wind turbines and ground-source heat pumps supplement the energy supply. Net-zero energy buildings — structures that generate as much energy as they consume over the course of a year — have transitioned from experimental prototypes to mainstream construction projects. The Bullitt Center in Seattle, often described as the greenest commercial building in the world, produces all its energy through rooftop solar panels and captures rainwater for all its water needs.

E. Material selection represents another critical dimension of sustainable architecture. The production of conventional building materials, particularly concrete and steel, is extraordinarily carbon-intensive. Concrete alone accounts for roughly eight per cent of global CO₂ emissions. In response, architects are exploring alternatives such as cross-laminated timber (CLT), which sequesters carbon rather than releasing it, and recycled or bio-based materials including hempcrete, rammed earth, and mycelium composites. Life-cycle assessment tools now enable designers to quantify the embodied carbon of different material choices, facilitating informed decision-making.

F. Water management has emerged as an equally important consideration. Green roofs and permeable paving reduce stormwater runoff, while greywater recycling systems treat and reuse water from sinks and showers for non-potable purposes such as toilet flushing and irrigation. Rainwater harvesting, once considered niche, is now a standard feature of many sustainable developments, particularly in water-scarce regions.

G. The social dimension of sustainable architecture extends beyond environmental performance. Biophilic design, which incorporates natural elements such as daylight, vegetation, and natural materials into the built environment, has been shown to improve occupant well-being, productivity, and cognitive function. Studies conducted in offices, hospitals, and schools consistently demonstrate that access to natural light and greenery reduces stress, accelerates healing, and enhances learning outcomes. As the evidence base grows, biophilic principles are being incorporated into building certification systems such as WELL and LEED.

H. Despite significant progress, barriers to widespread adoption remain. Higher upfront costs — though typically offset by lower operating expenses over a building's lifetime — deter many developers. Regulatory frameworks in some jurisdictions lag behind technological capabilities, while a shortage of skilled professionals limits the pace of implementation. Addressing these challenges will require coordinated action from governments, industry bodies, and educational institutions to align incentives, update building codes, and expand training programmes.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Section A", options: ["I. Historical precedents for climate-responsive building", "II. The environmental burden of the construction industry", "III. Achieving extreme reductions in heating energy", "IV. Generating power where it is consumed", "V. Choosing low-carbon construction materials", "VI. Managing water within sustainable developments", "VII. Benefits of nature-inspired interior environments", "VIII. Obstacles to mainstream sustainable construction", "IX. The role of digital technology in modern architecture"], correctAnswer: "II", explanation: "Section A discusses the environmental impact of the built environment." },
        { number: 15, type: "matching_headings", text: "Section B", options: ["I. Historical precedents for climate-responsive building", "II. The environmental burden of the construction industry", "III. Achieving extreme reductions in heating energy", "IV. Generating power where it is consumed", "V. Choosing low-carbon construction materials", "VI. Managing water within sustainable developments", "VII. Benefits of nature-inspired interior environments", "VIII. Obstacles to mainstream sustainable construction", "IX. The role of digital technology in modern architecture"], correctAnswer: "I", explanation: "Section B discusses vernacular architecture and historical passive strategies." },
        { number: 16, type: "matching_headings", text: "Section C", options: ["I. Historical precedents for climate-responsive building", "II. The environmental burden of the construction industry", "III. Achieving extreme reductions in heating energy", "IV. Generating power where it is consumed", "V. Choosing low-carbon construction materials", "VI. Managing water within sustainable developments", "VII. Benefits of nature-inspired interior environments", "VIII. Obstacles to mainstream sustainable construction", "IX. The role of digital technology in modern architecture"], correctAnswer: "III", explanation: "Section C discusses the Passivhaus standard and energy efficiency." },
        { number: 17, type: "matching_headings", text: "Section D", options: ["I. Historical precedents for climate-responsive building", "II. The environmental burden of the construction industry", "III. Achieving extreme reductions in heating energy", "IV. Generating power where it is consumed", "V. Choosing low-carbon construction materials", "VI. Managing water within sustainable developments", "VII. Benefits of nature-inspired interior environments", "VIII. Obstacles to mainstream sustainable construction", "IX. The role of digital technology in modern architecture"], correctAnswer: "IV", explanation: "Section D discusses on-site renewable energy generation." },
        { number: 18, type: "matching_headings", text: "Section E", options: ["I. Historical precedents for climate-responsive building", "II. The environmental burden of the construction industry", "III. Achieving extreme reductions in heating energy", "IV. Generating power where it is consumed", "V. Choosing low-carbon construction materials", "VI. Managing water within sustainable developments", "VII. Benefits of nature-inspired interior environments", "VIII. Obstacles to mainstream sustainable construction", "IX. The role of digital technology in modern architecture"], correctAnswer: "V", explanation: "Section E discusses material selection and low-carbon alternatives." },
        { number: 19, type: "matching_headings", text: "Section G", options: ["I. Historical precedents for climate-responsive building", "II. The environmental burden of the construction industry", "III. Achieving extreme reductions in heating energy", "IV. Generating power where it is consumed", "V. Choosing low-carbon construction materials", "VI. Managing water within sustainable developments", "VII. Benefits of nature-inspired interior environments", "VIII. Obstacles to mainstream sustainable construction", "IX. The role of digital technology in modern architecture"], correctAnswer: "VII", explanation: "Section G discusses biophilic design and well-being." },
        { number: 20, type: "summary_completion", text: "The Passivhaus standard requires buildings to use no more than fifteen kilowatt-hours per square metre annually for space __(20)__.", correctAnswer: "heating", explanation: "The passage states buildings consume this amount 'for space heating.'" },
        { number: 21, type: "summary_completion", text: "Concrete production is responsible for approximately eight per cent of global __(21)__ emissions.", correctAnswer: "CO₂", explanation: "The passage says 'Concrete alone accounts for roughly eight per cent of global CO₂ emissions.'" },
        { number: 22, type: "summary_completion", text: "Cross-laminated timber is beneficial because it __(22)__ carbon rather than releasing it.", correctAnswer: "sequesters", explanation: "The passage states CLT 'sequesters carbon rather than releasing it.'" },
        { number: 23, type: "summary_completion", text: "Biophilic design incorporates natural elements such as daylight, vegetation, and natural __(23)__ into buildings.", correctAnswer: "materials", explanation: "The passage states it 'incorporates natural elements such as daylight, vegetation, and natural materials.'" },
        { number: 24, type: "short_answer", text: "What type of traditional structure uses prevailing breezes to cool interior spaces naturally?", correctAnswer: "wind towers", explanation: "The passage mentions 'Middle Eastern wind towers' that 'channel prevailing breezes into interior spaces.'" },
        { number: 25, type: "short_answer", text: "Which building in Seattle is considered one of the greenest commercial buildings in the world?", correctAnswer: "The Bullitt Center", explanation: "The passage calls 'The Bullitt Center in Seattle' the 'greenest commercial building in the world.'" },
        { number: 26, type: "short_answer", text: "What type of assessment tool helps designers compare the carbon impact of different building materials?", correctAnswer: "Life-cycle assessment", explanation: "The passage mentions 'Life-cycle assessment tools now enable designers to quantify the embodied carbon.'" },
      ],
    },
    {
      title: "Quantum Computing",
      text: `Quantum computing represents one of the most ambitious frontiers in modern technology, promising to solve problems that are fundamentally beyond the reach of even the most powerful classical supercomputers. While conventional computers process information using binary digits, or bits, which exist in one of two definite states — zero or one — quantum computers exploit the strange properties of quantum mechanics to process information in radically different ways.

A. The foundational concept underlying quantum computing is the quantum bit, or qubit. Unlike a classical bit, a qubit can exist in a superposition of both zero and one simultaneously, a phenomenon rooted in the wave-like nature of subatomic particles. When multiple qubits are combined, the number of states they can represent grows exponentially: while ten classical bits can encode only one of 1,024 possible values at any moment, ten qubits can represent all 1,024 simultaneously. This exponential scaling is what gives quantum computers their extraordinary theoretical power.

B. Closely linked to superposition is entanglement, a peculiar quantum phenomenon in which two or more qubits become correlated in such a way that the state of one instantly influences the state of another, regardless of the physical distance separating them. Albert Einstein famously dismissed entanglement as "spooky action at a distance," yet decades of experimental evidence have confirmed its reality. In quantum computing, entanglement enables qubits to work in concert, vastly increasing computational efficiency for certain classes of problems.

C. Quantum algorithms have been devised to exploit these properties for practical advantage. Peter Shor's algorithm, published in 1994, demonstrated that a sufficiently powerful quantum computer could factor large numbers exponentially faster than any known classical algorithm — a capability with profound implications for cryptography, since most modern encryption relies on the difficulty of factoring large primes. Lov Grover's search algorithm, meanwhile, provides a quadratic speed-up for searching unsorted databases, reducing the number of required operations from N to the square root of N.

D. Translating theoretical promise into working hardware has proved enormously challenging. Qubits are extraordinarily fragile; even minute interactions with their environment — a process called decoherence — cause them to lose their quantum properties and behave like ordinary bits. Maintaining qubits in a coherent state requires extreme isolation, often involving temperatures close to absolute zero (approximately minus 273 degrees Celsius) and sophisticated error-correction protocols. Current quantum processors, containing anywhere from a few dozen to over one thousand qubits, remain "noisy," meaning their error rates limit the complexity of computations they can perform reliably.

E. Despite these limitations, significant progress has been made. In 2019, Google's Sycamore processor performed a specific calculation in roughly 200 seconds that the company claimed would take the most powerful classical supercomputer approximately 10,000 years — a milestone termed "quantum supremacy." While the practical utility of that particular calculation was limited, the demonstration validated the fundamental principle that quantum devices can outperform classical machines on certain tasks. IBM, meanwhile, has pursued a strategy of incremental scaling, unveiling processors with steadily increasing qubit counts and improved coherence times.

F. The potential applications of mature quantum computing span numerous fields. In pharmaceutical research, quantum simulations could model molecular interactions with unprecedented accuracy, dramatically accelerating drug discovery. In materials science, they could enable the design of novel superconductors, catalysts, and battery materials. Financial institutions are exploring quantum algorithms for portfolio optimisation and risk analysis, while logistics companies investigate applications in supply chain management and route planning.

G. Quantum computing also poses challenges to existing security infrastructure. The ability to break widely used encryption protocols has prompted the development of post-quantum cryptography — new mathematical frameworks designed to resist quantum attacks. The United States National Institute of Standards and Technology (NIST) began standardising post-quantum cryptographic algorithms in 2022, and governments worldwide are assessing the timeline for transitioning their digital infrastructure.

H. The race to build practical, large-scale quantum computers involves governments, technology corporations, and academic institutions around the globe. Billions of dollars in investment have flowed into quantum research, with the United States, China, and the European Union all establishing major national programmes. While experts disagree on whether fault-tolerant, general-purpose quantum computers will arrive within a decade or require several more, there is broad consensus that quantum technology will eventually transform computing, science, and society in ways comparable to the digital revolution of the twentieth century.`,
      questions: [
        { number: 27, type: "matching_information", text: "A description of the physical conditions required to maintain qubits", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "D", explanation: "Section D discusses temperatures close to absolute zero and isolation requirements." },
        { number: 28, type: "matching_information", text: "An example of a quantum computer outperforming a classical supercomputer", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "E", explanation: "Section E discusses Google's Sycamore processor achieving 'quantum supremacy.'" },
        { number: 29, type: "matching_information", text: "A reference to Einstein's view on a quantum phenomenon", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "B", explanation: "Section B mentions Einstein dismissing entanglement as 'spooky action at a distance.'" },
        { number: 30, type: "matching_information", text: "Details of international investment in quantum technology", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "H", explanation: "Section H discusses billions in investment from the US, China, and EU." },
        { number: 31, type: "matching_information", text: "The potential impact of quantum computing on the pharmaceutical industry", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "F", explanation: "Section F discusses quantum simulations accelerating drug discovery." },
        { number: 32, type: "matching_information", text: "The development of new encryption methods to counter quantum threats", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "G", explanation: "Section G discusses post-quantum cryptography and NIST standardisation." },
        { number: 33, type: "multiple_choice", text: "What is the key advantage of qubits over classical bits?", options: ["A They are physically smaller.", "B They can represent multiple states simultaneously.", "C They consume less energy.", "D They are easier to manufacture."], correctAnswer: "B", explanation: "The passage explains qubits can exist in 'superposition of both zero and one simultaneously.'" },
        { number: 34, type: "multiple_choice", text: "What is the significance of Shor's algorithm?", options: ["A It can search databases more efficiently.", "B It enables quantum error correction.", "C It can factor large numbers exponentially faster than classical methods.", "D It solves the decoherence problem."], correctAnswer: "C", explanation: "The passage states Shor's algorithm 'could factor large numbers exponentially faster than any known classical algorithm.'" },
        { number: 35, type: "multiple_choice", text: "What does the term 'quantum supremacy' refer to?", options: ["A The dominance of one country in quantum research", "B A quantum device outperforming classical computers on a specific task", "C The theoretical maximum speed of a quantum processor", "D The replacement of all classical computers by quantum machines"], correctAnswer: "B", explanation: "The passage describes it as the milestone where quantum devices 'outperform classical machines on certain tasks.'" },
        { number: 36, type: "multiple_choice", text: "According to the passage, what is the main obstacle to building reliable quantum computers?", options: ["A The high cost of qubit manufacturing", "B The lack of qualified researchers", "C The fragility of qubits and decoherence", "D The absence of useful algorithms"], correctAnswer: "C", explanation: "The passage describes qubits as 'extraordinarily fragile' and discusses decoherence." },
        { number: 37, type: "sentence_completion", text: "The process by which qubits lose their quantum properties through environmental interaction is called __(37)__.", correctAnswer: "decoherence", explanation: "The passage defines this process as 'decoherence.'" },
        { number: 38, type: "sentence_completion", text: "Google's __(38)__ processor achieved the quantum supremacy milestone in 2019.", correctAnswer: "Sycamore", explanation: "The passage names 'Google's Sycamore processor.'" },
        { number: 39, type: "sentence_completion", text: "Grover's algorithm reduces the number of search operations from N to the __(39)__ of N.", correctAnswer: "square root", explanation: "The passage states it reduces operations 'from N to the square root of N.'" },
        { number: 40, type: "sentence_completion", text: "NIST began standardising post-quantum cryptographic algorithms in __(40)__.", correctAnswer: "2022", explanation: "The passage states 'NIST began standardising post-quantum cryptographic algorithms in 2022.'" },
      ],
    },
  ],
};
