import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_36: ReadingTest = {
  id: 36,
  passages: [
    {
      title: "The History of Bridges",
      text: `Bridges are among the oldest and most essential structures in human civilisation, enabling communities to cross natural obstacles such as rivers, valleys, and gorges. The earliest bridges were simple constructions — fallen logs or flat stones laid across streams — yet even these rudimentary crossings transformed the way people traded, travelled, and interacted. Archaeological evidence suggests that deliberately placed stone slabs were used as bridges in parts of Asia and the Mediterranean as early as 1600 BCE, and by 600 BCE the ancient Greeks were building elegant stone-arch bridges that still inspire modern engineers.

The Romans elevated bridge engineering to an art form. Combining the semicircular arch with a newly perfected material, hydraulic concrete, they erected structures of unprecedented scale and durability. The Pont du Gard aqueduct bridge in southern France, completed around 19 BCE, rises nearly 50 metres above the Gardon River and stretches 275 metres in length. Its three tiers of arches were constructed without mortar; the precisely cut limestone blocks are held together solely by friction and gravity. Several Roman bridges, including the Pons Fabricius in Rome, remain in daily use more than two thousand years after their completion — a testament to the sophistication of Roman engineering.

After the fall of the Roman Empire, bridge-building in Europe entered a period of relative stagnation. The knowledge of hydraulic concrete was lost, and many stone bridges built during the medieval period were narrower, less stable, and prone to collapse during floods. Nevertheless, the Middle Ages produced notable innovations: the pointed arch, borrowed from Islamic architecture, allowed bridge builders to construct wider spans with less material, and fortified bridges such as the Pont Valentré in Cahors, France, combined military defence with transportation.

The Industrial Revolution brought iron and, later, steel, transforming bridge construction irrevocably. Abraham Darby III's Iron Bridge, erected in 1779 across the River Severn in Shropshire, England, was the world's first major bridge built entirely of cast iron. At 30 metres in length, it demonstrated that metal could replace stone as the primary structural material. Within a century, engineers were exploiting wrought iron and steel to build suspension bridges of extraordinary length. John Roebling's Brooklyn Bridge, completed in 1883, used steel-wire cables to span 486 metres across New York's East River, an achievement that captivated the public imagination and opened an era of long-span bridge design.

The twentieth century witnessed the rise of reinforced and pre-stressed concrete bridges, cable-stayed designs, and computer-aided engineering. France's Millau Viaduct, completed in 2004, carries a motorway across the Tarn Valley at a maximum height of 343 metres, making its tallest pylon higher than the Eiffel Tower. Its cable-stayed design distributes loads efficiently, permitting a slender, elegant deck that seems almost to float above the mist-filled valley. Meanwhile, China has become the world's most prolific bridge-building nation: between 2000 and 2020, Chinese engineers completed more than 500,000 highway bridges, including the Danyang–Kunshan Grand Bridge, which, at 164.8 kilometres, is the longest bridge ever built.

Modern bridge engineering increasingly emphasises sustainability and resilience. Engineers now use high-performance concrete containing industrial by-products such as fly ash and silica fume, which reduce both the carbon footprint and material cost. Sensors embedded within bridge decks monitor stress, vibration, and temperature in real time, enabling predictive maintenance that can extend a bridge's service life by decades. Some experimental designs even incorporate self-healing concrete, in which dormant bacteria are activated by rainwater infiltrating cracks, producing limestone that seals the damage autonomously.

Despite these advances, the fundamental challenge of bridge engineering remains unchanged: to span a gap safely, economically, and, ideally, beautifully. Whether fashioned from stone slabs, iron arches, steel cables, or smart concrete, every bridge embodies the same human impulse — to connect what geography has divided.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "What material did the Romans combine with the semicircular arch?", options: ["A Wrought iron", "B Hydraulic concrete", "C Reinforced steel", "D Limestone mortar"], correctAnswer: "B", explanation: "The passage states the Romans combined the semicircular arch with 'a newly perfected material, hydraulic concrete.'" },
        { number: 2, type: "multiple_choice", text: "What holds the blocks of the Pont du Gard together?", options: ["A Mortar and adhesive", "B Iron clamps", "C Friction and gravity", "D Hydraulic concrete"], correctAnswer: "C", explanation: "The passage says the blocks 'are held together solely by friction and gravity.'" },
        { number: 3, type: "multiple_choice", text: "Which bridge was the first major structure built entirely of cast iron?", options: ["A Brooklyn Bridge", "B Pont du Gard", "C Millau Viaduct", "D Iron Bridge"], correctAnswer: "D", explanation: "The passage identifies Abraham Darby III's Iron Bridge as 'the world's first major bridge built entirely of cast iron.'" },
        { number: 4, type: "multiple_choice", text: "What is the longest bridge ever built according to the passage?", options: ["A Millau Viaduct", "B Brooklyn Bridge", "C Danyang–Kunshan Grand Bridge", "D Pont Valentré"], correctAnswer: "C", explanation: "The passage states the Danyang–Kunshan Grand Bridge 'at 164.8 kilometres, is the longest bridge ever built.'" },
        { number: 5, type: "true_false_not_given", text: "The earliest bridges were constructed using advanced engineering techniques.", correctAnswer: "FALSE", explanation: "The passage describes the earliest bridges as 'simple constructions — fallen logs or flat stones.'" },
        { number: 6, type: "true_false_not_given", text: "The Pons Fabricius in Rome is no longer used today.", correctAnswer: "FALSE", explanation: "The passage states it 'remain[s] in daily use more than two thousand years after their completion.'" },
        { number: 7, type: "true_false_not_given", text: "The pointed arch used in medieval bridges was influenced by Islamic architecture.", correctAnswer: "TRUE", explanation: "The passage says 'the pointed arch, borrowed from Islamic architecture.'" },
        { number: 8, type: "true_false_not_given", text: "The Brooklyn Bridge was completed before the Iron Bridge.", correctAnswer: "FALSE", explanation: "The Iron Bridge was erected in 1779; the Brooklyn Bridge was completed in 1883." },
        { number: 9, type: "true_false_not_given", text: "The Millau Viaduct was designed by a Chinese engineering firm.", correctAnswer: "NOT GIVEN", explanation: "The passage does not mention who designed the Millau Viaduct." },
        { number: 10, type: "sentence_completion", text: "The Iron Bridge demonstrated that __(10)__ could replace stone as the primary structural material.", correctAnswer: "metal", explanation: "The passage says it 'demonstrated that metal could replace stone.'" },
        { number: 11, type: "sentence_completion", text: "The Brooklyn Bridge used steel-wire cables to span __(11)__ metres across the East River.", correctAnswer: "486", explanation: "The passage states it used 'steel-wire cables to span 486 metres.'" },
        { number: 12, type: "sentence_completion", text: "Self-healing concrete uses dormant __(12)__ that are activated by rainwater.", correctAnswer: "bacteria", explanation: "The passage says 'dormant bacteria are activated by rainwater infiltrating cracks.'" },
        { number: 13, type: "sentence_completion", text: "Sensors embedded in bridge decks enable __(13)__ maintenance that extends service life.", correctAnswer: "predictive", explanation: "The passage says 'enabling predictive maintenance that can extend a bridge's service life.'" },
      ],
    },
    {
      title: "Urban Farming Techniques",
      text: `A. The growth of cities has historically meant the decline of local food production. As urban populations swell, farmland at the periphery is swallowed by housing developments and commercial zones, pushing agriculture further from the people who depend on it. In recent decades, however, a counter-movement has emerged: urban farming, the practice of cultivating food within or very close to city boundaries. Advocates argue that urban agriculture can shorten supply chains, reduce transport emissions, and improve food security for vulnerable communities.

B. One of the simplest forms of urban farming is the community garden, in which residents of a neighbourhood share a plot of land for growing vegetables, herbs, and fruit. Community gardens have existed for over a century — they proliferated during both World Wars as 'victory gardens' — but they experienced a revival in the 1990s as part of the broader environmental movement. Studies show that community gardeners consume significantly more fresh produce than their non-gardening neighbours and report higher levels of physical activity and mental wellbeing.

C. Rooftop farming takes the concept upward. Flat-roofed commercial buildings, warehouses, and residential blocks can be retrofitted with lightweight soil beds or hydroponic systems. Brooklyn Grange, established in New York in 2010, operates more than two acres of rooftop vegetable farms across several buildings and produces over 50,000 pounds of organically grown food per year. Rooftop farms also provide ancillary benefits: they insulate buildings, reducing heating and cooling costs; they absorb rainwater, alleviating pressure on storm drains; and they create green space in otherwise concrete-dominated landscapes.

D. Vertical farming represents a more technology-intensive approach. In a vertical farm, crops are grown indoors in stacked layers, typically using hydroponics or aeroponics, under carefully controlled artificial lighting. Because the growing environment is sealed from the outside, vertical farms use no pesticides and require roughly ninety-five per cent less water than conventional field agriculture. The trade-off is energy: maintaining lighting, climate control, and nutrient-delivery systems demands significant electricity, although advances in LED technology and renewable energy are steadily reducing costs.

E. Aquaponics combines fish farming with soilless plant cultivation in a symbiotic loop. Fish waste provides nitrogen-rich fertiliser for plants, while the plants filter and clean the water before it is returned to the fish tanks. A well-designed aquaponic system can produce both protein and vegetables with minimal external inputs. Several commercial aquaponic operations now supply restaurants and farmers' markets in cities such as Milwaukee, Berlin, and Melbourne.

F. Critics of urban farming point to its limited scale. Even the most productive rooftop farm cannot match the output of a conventional rural operation, and vertical farms remain expensive to build and operate. Furthermore, urban land values make large-scale city farming economically challenging. Proponents counter that urban agriculture need not replace rural farming but can supplement it, particularly for perishable goods such as salad greens, herbs, and soft fruits that lose quality during long-distance transport.

G. Governments in several countries have begun to support urban agriculture through policy incentives. Singapore, which imports more than ninety per cent of its food, has committed to producing thirty per cent of its nutritional needs domestically by 2030, largely through vertical farms. Paris has mandated that new commercial buildings include rooftop gardens or solar panels, and Detroit has rezoned thousands of vacant lots for agricultural use. Such policies reflect a growing recognition that food production should be integrated into urban planning rather than treated as exclusively rural.

H. Looking ahead, advances in biotechnology, data analytics, and automation promise to make urban farming more efficient and affordable. Robotic harvesters, AI-driven climate optimisation, and gene-edited crops tailored for indoor cultivation are all under active development. If these technologies mature as expected, urban farming could evolve from a niche movement into a significant component of the global food system.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Section A", options: ["I. Financial barriers to city agriculture", "II. The resurgence of growing food in cities", "III. Government measures to encourage urban food production", "IV. A water-efficient indoor growing method", "V. Combining animal and plant cultivation", "VI. Community-level food growing and its benefits", "VII. The potential of future farming technologies", "VIII. Farming on building rooftops", "IX. Limitations of urban food production"], correctAnswer: "II", explanation: "Section A introduces urban farming as a counter-movement to declining local food production." },
        { number: 15, type: "matching_headings", text: "Section B", options: ["I. Financial barriers to city agriculture", "II. The resurgence of growing food in cities", "III. Government measures to encourage urban food production", "IV. A water-efficient indoor growing method", "V. Combining animal and plant cultivation", "VI. Community-level food growing and its benefits", "VII. The potential of future farming technologies", "VIII. Farming on building rooftops", "IX. Limitations of urban food production"], correctAnswer: "VI", explanation: "Section B discusses community gardens and their benefits." },
        { number: 16, type: "matching_headings", text: "Section C", options: ["I. Financial barriers to city agriculture", "II. The resurgence of growing food in cities", "III. Government measures to encourage urban food production", "IV. A water-efficient indoor growing method", "V. Combining animal and plant cultivation", "VI. Community-level food growing and its benefits", "VII. The potential of future farming technologies", "VIII. Farming on building rooftops", "IX. Limitations of urban food production"], correctAnswer: "VIII", explanation: "Section C discusses rooftop farming." },
        { number: 17, type: "matching_headings", text: "Section D", options: ["I. Financial barriers to city agriculture", "II. The resurgence of growing food in cities", "III. Government measures to encourage urban food production", "IV. A water-efficient indoor growing method", "V. Combining animal and plant cultivation", "VI. Community-level food growing and its benefits", "VII. The potential of future farming technologies", "VIII. Farming on building rooftops", "IX. Limitations of urban food production"], correctAnswer: "IV", explanation: "Section D describes vertical farming which uses 95% less water." },
        { number: 18, type: "matching_headings", text: "Section E", options: ["I. Financial barriers to city agriculture", "II. The resurgence of growing food in cities", "III. Government measures to encourage urban food production", "IV. A water-efficient indoor growing method", "V. Combining animal and plant cultivation", "VI. Community-level food growing and its benefits", "VII. The potential of future farming technologies", "VIII. Farming on building rooftops", "IX. Limitations of urban food production"], correctAnswer: "V", explanation: "Section E discusses aquaponics combining fish and plant cultivation." },
        { number: 19, type: "matching_headings", text: "Section F", options: ["I. Financial barriers to city agriculture", "II. The resurgence of growing food in cities", "III. Government measures to encourage urban food production", "IV. A water-efficient indoor growing method", "V. Combining animal and plant cultivation", "VI. Community-level food growing and its benefits", "VII. The potential of future farming technologies", "VIII. Farming on building rooftops", "IX. Limitations of urban food production"], correctAnswer: "IX", explanation: "Section F discusses criticisms and limitations of urban farming." },
        { number: 20, type: "summary_completion", text: "Brooklyn Grange produces over 50,000 pounds of __(20)__ grown food each year.", correctAnswer: "organically", explanation: "The passage says it produces 'over 50,000 pounds of organically grown food per year.'" },
        { number: 21, type: "summary_completion", text: "Vertical farms use roughly ninety-five per cent less __(21)__ than conventional agriculture.", correctAnswer: "water", explanation: "The passage states vertical farms 'require roughly ninety-five per cent less water.'" },
        { number: 22, type: "summary_completion", text: "In aquaponic systems, fish __(22)__ provides nitrogen-rich fertiliser for plants.", correctAnswer: "waste", explanation: "The passage says 'fish waste provides nitrogen-rich fertiliser for plants.'" },
        { number: 23, type: "summary_completion", text: "Singapore aims to produce thirty per cent of its nutritional needs __(23)__ by 2030.", correctAnswer: "domestically", explanation: "The passage says Singapore has committed to 'producing thirty per cent of its nutritional needs domestically by 2030.'" },
        { number: 24, type: "short_answer", text: "What type of gardens proliferated during both World Wars?", correctAnswer: "victory gardens", explanation: "The passage says they 'proliferated during both World Wars as victory gardens.'" },
        { number: 25, type: "short_answer", text: "What is the main trade-off of vertical farming?", correctAnswer: "energy", explanation: "The passage says 'the trade-off is energy.'" },
        { number: 26, type: "short_answer", text: "Which city has rezoned vacant lots for agricultural use?", correctAnswer: "Detroit", explanation: "The passage states 'Detroit has rezoned thousands of vacant lots for agricultural use.'" },
      ],
    },
    {
      title: "Artificial Intelligence in Business",
      text: `The integration of artificial intelligence into the corporate world has accelerated dramatically since 2015, driven by advances in machine learning, the availability of vast data sets, and a sharp decrease in computing costs. Once confined to research laboratories and technology companies, AI now permeates sectors as diverse as finance, healthcare, manufacturing, retail, and logistics. A 2023 survey by McKinsey found that sixty-five per cent of organisations regularly use AI in at least one business function, nearly double the figure reported in 2017.

A. In finance, AI algorithms analyse market data at speeds no human trader could match. High-frequency trading firms deploy neural networks that identify fleeting price discrepancies across global exchanges and execute thousands of trades per second. Banks use natural-language processing to scan regulatory documents, contracts, and news feeds, flagging compliance risks and potential fraud in real time. Credit-scoring models trained on non-traditional data — mobile-phone usage patterns, utility-payment histories, and even social-media activity — have expanded access to loans in developing economies where conventional credit records are scarce.

B. Manufacturing has embraced AI primarily through predictive maintenance and quality control. Sensors on production lines collect continuous streams of data — vibration frequencies, temperature readings, power consumption — which machine-learning models analyse to predict equipment failures before they occur. General Electric, for example, claims that AI-driven predictive maintenance has reduced unplanned downtime in its aviation division by up to twenty per cent. In quality control, computer-vision systems inspect products at superhuman speed and accuracy, detecting microscopic defects that would escape the human eye.

C. Retail and e-commerce companies use AI to personalise the shopping experience. Recommendation engines, pioneered by Amazon and Netflix, analyse browsing history, purchase records, and demographic data to suggest products a customer is likely to buy. Dynamic pricing algorithms adjust prices in real time based on demand, competitor pricing, and inventory levels. Chatbots powered by large language models now handle a significant share of customer-service interactions, resolving routine queries instantly and escalating complex issues to human agents.

D. Despite its benefits, the adoption of AI in business raises significant ethical and social concerns. Algorithmic bias is one of the most widely discussed issues: if training data reflects historical inequalities — for example, if past hiring decisions favoured men over women — the resulting AI model may perpetuate or even amplify those biases. Several high-profile cases have illustrated this risk, including a recruitment tool developed by a major technology company that was found to systematically downgrade applications from women.

E. Job displacement is another pressing concern. The World Economic Forum estimated in 2020 that AI and automation would eliminate eighty-five million jobs globally by 2025 but create ninety-seven million new roles. Critics argue that the new jobs often require advanced technical skills that displaced workers may lack, potentially widening income inequality. Governments and educational institutions are therefore under pressure to invest in retraining programmes that equip workers with the competencies demanded by an AI-driven economy.

F. Data privacy presents a further challenge. AI systems are data-hungry; the more information they consume, the more accurate their predictions become. This creates an incentive for companies to collect and retain vast quantities of personal data, raising the risk of breaches and misuse. The European Union's General Data Protection Regulation (GDPR), introduced in 2018, imposes strict rules on data collection, storage, and processing, and has inspired similar legislation in Brazil, India, and several US states.

G. Looking forward, generative AI — exemplified by models such as GPT-4 and its successors — promises to transform business operations even further. These models can draft reports, generate marketing copy, write software code, and synthesise research, tasks that previously required substantial human effort. Early adopters report productivity gains of twenty to forty per cent in knowledge work. However, concerns about accuracy, intellectual-property rights, and the environmental cost of training large models remain unresolved, suggesting that the relationship between AI and business will continue to evolve in complex and sometimes unpredictable ways.`,
      questions: [
        { number: 27, type: "matching_information", text: "A description of how AI helps detect product flaws", options: ["A", "B", "C", "D", "E", "F", "G"], correctAnswer: "B", explanation: "Paragraph B discusses computer-vision systems detecting 'microscopic defects.'" },
        { number: 28, type: "matching_information", text: "An example of AI perpetuating gender discrimination", options: ["A", "B", "C", "D", "E", "F", "G"], correctAnswer: "D", explanation: "Paragraph D mentions a recruitment tool that 'systematically downgrade applications from women.'" },
        { number: 29, type: "matching_information", text: "Reference to legislation governing data use", options: ["A", "B", "C", "D", "E", "F", "G"], correctAnswer: "F", explanation: "Paragraph F discusses the GDPR and similar legislation." },
        { number: 30, type: "matching_information", text: "Mention of AI expanding financial services in poorer countries", options: ["A", "B", "C", "D", "E", "F", "G"], correctAnswer: "A", explanation: "Paragraph A discusses credit-scoring models that 'expanded access to loans in developing economies.'" },
        { number: 31, type: "matching_information", text: "The prediction that AI will create more jobs than it destroys", options: ["A", "B", "C", "D", "E", "F", "G"], correctAnswer: "E", explanation: "Paragraph E cites the World Economic Forum's estimate of 85 million jobs lost but 97 million created." },
        { number: 32, type: "matching_information", text: "Examples of tasks generative AI can perform", options: ["A", "B", "C", "D", "E", "F", "G"], correctAnswer: "G", explanation: "Paragraph G lists drafting reports, generating marketing copy, writing code, and synthesising research." },
        { number: 33, type: "multiple_choice", text: "According to the 2023 McKinsey survey, what percentage of organisations regularly use AI?", options: ["A 35 per cent", "B 50 per cent", "C 65 per cent", "D 80 per cent"], correctAnswer: "C", explanation: "The passage states 'sixty-five per cent of organisations regularly use AI.'" },
        { number: 34, type: "multiple_choice", text: "What has General Electric achieved through AI-driven predictive maintenance?", options: ["A Increased production speed by 30%", "B Reduced unplanned downtime by up to 20%", "C Eliminated all equipment failures", "D Replaced human maintenance workers entirely"], correctAnswer: "B", explanation: "The passage says AI-driven predictive maintenance 'reduced unplanned downtime... by up to twenty per cent.'" },
        { number: 35, type: "multiple_choice", text: "What is one concern about generative AI mentioned in the passage?", options: ["A It cannot generate useful content", "B It requires no computing resources", "C It raises issues about accuracy and intellectual-property rights", "D It has been banned by most governments"], correctAnswer: "C", explanation: "The passage mentions 'concerns about accuracy, intellectual-property rights, and the environmental cost.'" },
        { number: 36, type: "multiple_choice", text: "Dynamic pricing algorithms adjust prices based on all of the following EXCEPT:", options: ["A Demand levels", "B Competitor pricing", "C Weather conditions", "D Inventory levels"], correctAnswer: "C", explanation: "The passage mentions demand, competitor pricing, and inventory levels but not weather conditions." },
        { number: 37, type: "sentence_completion", text: "High-frequency trading firms use neural networks to identify fleeting price __(37)__ across global exchanges.", correctAnswer: "discrepancies", explanation: "The passage says they 'identify fleeting price discrepancies.'" },
        { number: 38, type: "sentence_completion", text: "Recommendation engines analyse browsing history, purchase records, and __(38)__ data.", correctAnswer: "demographic", explanation: "The passage mentions 'browsing history, purchase records, and demographic data.'" },
        { number: 39, type: "sentence_completion", text: "Critics argue new AI-created jobs may widen income __(39)__.", correctAnswer: "inequality", explanation: "The passage says it could be 'potentially widening income inequality.'" },
        { number: 40, type: "sentence_completion", text: "Early adopters of generative AI report productivity gains of __(40)__ to forty per cent.", correctAnswer: "twenty", explanation: "The passage says 'productivity gains of twenty to forty per cent.'" },
      ],
    },
  ],
};
