import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_53: ReadingTest = {
  id: 53,
  passages: [
    {
      title: "Global Health Advancements",
      text: `The twentieth and twenty-first centuries have witnessed extraordinary advances in global health, transforming diseases that once killed millions into manageable or even eradicated conditions. Vaccination programmes, antibiotic development, improved sanitation, and public health infrastructure have collectively raised global life expectancy from approximately thirty-one years in 1900 to over seventy-three years today. Yet significant challenges remain, and the distribution of health improvements across populations remains profoundly unequal.

The eradication of smallpox, declared by the World Health Organization in 1980, stands as perhaps the greatest achievement in the history of public health. Smallpox, caused by the variola virus, had killed an estimated 300 million people in the twentieth century alone before an intensive global vaccination campaign, coordinated by the WHO beginning in 1967, eliminated the disease entirely. The success of the smallpox campaign demonstrated that coordinated international action could overcome even the most devastating infectious diseases.

Polio eradication efforts, launched by the Global Polio Eradication Initiative in 1988, have reduced cases by over ninety-nine per cent. Wild poliovirus now circulates in only two countries — Afghanistan and Pakistan — compared to 125 countries when the initiative began. The campaign has relied on oral polio vaccine, which is inexpensive, easy to administer, and does not require trained medical personnel — advantages that have enabled mass vaccination in some of the world's most challenging environments.

The HIV/AIDS pandemic, which emerged in the 1980s and has killed over forty million people worldwide, prompted one of the most rapid and consequential medical research efforts in history. The development of antiretroviral therapy (ART) in the mid-1990s transformed HIV from a death sentence into a manageable chronic condition. By 2023, approximately thirty million people were receiving ART globally — though an estimated nine million HIV-positive individuals still lacked access to treatment, primarily in sub-Saharan Africa.

The COVID-19 pandemic, caused by the SARS-CoV-2 virus, presented an unprecedented challenge to global health systems. The disease, first identified in late 2019, spread to every country within months, causing over six million recorded deaths by 2023. However, the pandemic also demonstrated remarkable scientific capability: multiple effective vaccines were developed and authorised within twelve months of the virus being sequenced — a process that had previously taken a decade or more. The mRNA vaccine technology used by Pfizer-BioNTech and Moderna represented a platform with potential applications against cancer, malaria, and other diseases.

Antimicrobial resistance (AMR) represents one of the most serious threats to future global health. The overuse and misuse of antibiotics in human medicine and animal agriculture have accelerated the evolution of resistant bacteria. The WHO has identified AMR as one of the top ten global public health threats. A 2022 study published in The Lancet estimated that bacterial AMR was directly responsible for approximately 1.27 million deaths in 2019 and contributed to nearly five million deaths overall.

Non-communicable diseases (NCDs) — including cardiovascular disease, cancer, diabetes, and chronic respiratory conditions — now account for approximately seventy-one per cent of all deaths globally. These diseases are driven by risk factors including tobacco use, physical inactivity, unhealthy diets, and harmful alcohol consumption. While NCDs have traditionally been associated with wealthy countries, they are now the leading cause of death in low- and middle-income countries as well, driven by urbanisation, dietary changes, and ageing populations.

Mental health has emerged as a critical component of global health discourse. The WHO estimates that approximately 970 million people worldwide lived with a mental disorder in 2019. Depression is the leading cause of disability globally, and suicide claims over 700,000 lives annually. Despite this burden, mental health services remain severely underfunded: low-income countries allocate less than one per cent of their health budgets to mental health, and globally there are fewer than one mental health professional per 10,000 people.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "When was smallpox officially declared eradicated?", options: ["A. 1967", "B. 1975", "C. 1980", "D. 1988"], correctAnswer: "C", explanation: "The passage states 'declared by the World Health Organization in 1980.'" },
        { number: 2, type: "multiple_choice", text: "How many countries still have wild poliovirus circulation?", options: ["A. One", "B. Two", "C. Five", "D. Ten"], correctAnswer: "B", explanation: "The passage says 'only two countries — Afghanistan and Pakistan.'" },
        { number: 3, type: "multiple_choice", text: "What proportion of global deaths do NCDs account for?", options: ["A. Fifty per cent", "B. Sixty per cent", "C. Seventy-one per cent", "D. Eighty per cent"], correctAnswer: "C", explanation: "The passage states 'approximately seventy-one per cent of all deaths globally.'" },
        { number: 4, type: "multiple_choice", text: "Approximately how many people lived with a mental disorder in 2019?", options: ["A. 500 million", "B. 700 million", "C. 970 million", "D. 1.2 billion"], correctAnswer: "C", explanation: "The passage says 'approximately 970 million people.'" },
        { number: 5, type: "true_false_not_given", text: "Global life expectancy was approximately thirty-one years in 1900.", correctAnswer: "TRUE", explanation: "The passage directly states this." },
        { number: 6, type: "true_false_not_given", text: "Smallpox killed an estimated 300 million people in the nineteenth century.", correctAnswer: "FALSE", explanation: "The passage says 'in the twentieth century alone.'" },
        { number: 7, type: "true_false_not_given", text: "Antiretroviral therapy was developed in the mid-1990s.", correctAnswer: "TRUE", explanation: "The passage directly states this." },
        { number: 8, type: "true_false_not_given", text: "COVID-19 vaccines took over five years to develop.", correctAnswer: "FALSE", explanation: "The passage says vaccines were developed 'within twelve months.'" },
        { number: 9, type: "true_false_not_given", text: "AMR was directly responsible for approximately 1.27 million deaths in 2019.", correctAnswer: "TRUE", explanation: "The passage directly states this." },
        { number: 10, type: "true_false_not_given", text: "mRNA vaccine technology was first used for malaria vaccines.", correctAnswer: "NOT GIVEN", explanation: "The passage says mRNA has 'potential applications against cancer, malaria' but does not say it was first used for malaria." },
        { number: 11, type: "true_false_not_given", text: "Depression is the leading cause of disability globally.", correctAnswer: "TRUE", explanation: "The passage directly states this." },
        { number: 12, type: "true_false_not_given", text: "Low-income countries allocate more than five per cent of health budgets to mental health.", correctAnswer: "FALSE", explanation: "The passage says they allocate 'less than one per cent.'" },
        { number: 13, type: "true_false_not_given", text: "By 2023, approximately thirty million people were receiving ART.", correctAnswer: "TRUE", explanation: "The passage directly states this." }
      ]
    },
    {
      title: "Population Growth and Cities",
      text: `A. The relationship between population growth and urbanisation is one of the most consequential dynamics shaping the twenty-first century. The world's population, which stood at approximately 2.5 billion in 1950, reached eight billion in 2022 and is projected to peak at approximately 10.4 billion around 2080. This growth is occurring overwhelmingly in urban areas, particularly in Africa and Asia, where cities are expanding at rates that strain infrastructure, governance, and environmental systems.

B. The demographic transition — the shift from high birth and death rates to low birth and death rates that accompanies economic development — is the fundamental framework for understanding population change. In pre-industrial societies, high fertility was necessary to compensate for high infant and child mortality. As public health improvements, better nutrition, and medical advances reduced mortality, populations grew rapidly until fertility rates also declined in response to urbanisation, education (particularly of women), and access to contraception.

C. Sub-Saharan Africa is the region experiencing the most rapid population growth. Its population is projected to nearly double from approximately 1.2 billion in 2023 to over 2.1 billion by 2050. Fertility rates in the region remain significantly higher than the global average — approximately 4.6 births per woman compared to the global average of 2.3. Nigeria alone is projected to become the world's third most populous country by 2050, with an estimated population of approximately 375 million.

D. The urbanisation of growing populations creates both opportunities and challenges. Cities generate approximately eighty per cent of global GDP and serve as centres of innovation, education, and cultural exchange. Urban economies offer higher wages and more diverse employment opportunities than rural areas, which explains the powerful pull of rural-to-urban migration. However, rapid urban growth often outpaces the development of housing, transportation, water supply, sanitation, and other essential infrastructure.

E. Informal settlements — known by various names including slums, favelas, and shantytowns — house approximately one billion people worldwide, primarily in the cities of developing countries. These settlements typically lack secure land tenure, adequate housing, clean water, and sanitation services. Residents face elevated risks of disease, flooding, and violence. Yet informal settlements also demonstrate remarkable resilience and entrepreneurship, with residents creating businesses, community organisations, and social networks that provide essential services in the absence of government provision.

F. Urban planning approaches in the developing world are evolving in response to these challenges. Rather than demolishing informal settlements — a practice that displaces vulnerable populations and destroys social networks — many cities now pursue upgrading strategies that improve infrastructure within existing communities. Medellín in Colombia has become a celebrated model, investing in public transportation, libraries, and parks in previously marginalised neighbourhoods. Kigali in Rwanda has implemented ambitious urban planning that combines density with green infrastructure.

G. Demographic ageing presents a contrasting challenge in many developed countries. Japan, where over twenty-nine per cent of the population is aged sixty-five or older, faces labour shortages, rising healthcare costs, and the fiscal pressure of supporting a growing proportion of retirees with a shrinking working-age population. Similar trends are emerging in South Korea, Germany, Italy, and China — where decades of the one-child policy have produced a rapidly ageing demographic structure.

H. Migration — both internal and international — connects population dynamics with urbanisation in complex ways. Rural-to-urban migration drives city growth in developing countries. International migration, while representing only about 3.6 per cent of the global population, has significant demographic effects in both sending and receiving countries. Remittances from international migrants totalled approximately $656 billion in 2022, exceeding foreign direct investment flows to many developing countries and providing a crucial income source for millions of families.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Paragraph C", options: ["i. Planning for growing cities", "ii. Migration and its effects", "iii. The ageing challenge", "iv. Africa's population surge", "v. Informal settlements and resilience", "vi. Economic power of cities", "vii. Understanding demographic change", "viii. Urban opportunities and strains"], correctAnswer: "iv", explanation: "Paragraph C discusses sub-Saharan Africa's rapid population growth." },
        { number: 15, type: "matching_headings", text: "Paragraph E", options: ["i. Planning for growing cities", "ii. Migration and its effects", "iii. The ageing challenge", "iv. Africa's population surge", "v. Informal settlements and resilience", "vi. Economic power of cities", "vii. Understanding demographic change", "viii. Urban opportunities and strains"], correctAnswer: "v", explanation: "Paragraph E discusses informal settlements." },
        { number: 16, type: "matching_headings", text: "Paragraph G", options: ["i. Planning for growing cities", "ii. Migration and its effects", "iii. The ageing challenge", "iv. Africa's population surge", "v. Informal settlements and resilience", "vi. Economic power of cities", "vii. Understanding demographic change", "viii. Urban opportunities and strains"], correctAnswer: "iii", explanation: "Paragraph G discusses demographic ageing in Japan and other countries." },
        { number: 17, type: "matching_headings", text: "Paragraph H", options: ["i. Planning for growing cities", "ii. Migration and its effects", "iii. The ageing challenge", "iv. Africa's population surge", "v. Informal settlements and resilience", "vi. Economic power of cities", "vii. Understanding demographic change", "viii. Urban opportunities and strains"], correctAnswer: "ii", explanation: "Paragraph H discusses migration's demographic effects." },
        { number: 18, type: "summary_completion", text: "The world's population reached ________ billion in 2022.", correctAnswer: "eight", explanation: "The passage states 'reached eight billion in 2022.'" },
        { number: 19, type: "summary_completion", text: "Global population is projected to peak at approximately ________ billion.", correctAnswer: "10.4", explanation: "The passage says 'approximately 10.4 billion around 2080.'" },
        { number: 20, type: "summary_completion", text: "Cities generate approximately ________ per cent of global GDP.", correctAnswer: "eighty", explanation: "The passage states this directly." },
        { number: 21, type: "summary_completion", text: "Approximately ________ billion people live in informal settlements worldwide.", correctAnswer: "one", explanation: "The passage says 'approximately one billion people.'" },
        { number: 22, type: "summary_completion", text: "Remittances from international migrants totalled approximately $________ billion in 2022.", correctAnswer: "656", explanation: "The passage says '$656 billion in 2022.'" },
        { number: 23, type: "summary_completion", text: "In Japan, over ________ per cent of the population is aged 65 or older.", correctAnswer: "twenty-nine", explanation: "The passage says 'over twenty-nine per cent.'" },
        { number: 24, type: "summary_completion", text: "Nigeria is projected to have a population of approximately ________ million by 2050.", correctAnswer: "375", explanation: "The passage says 'approximately 375 million.'" },
        { number: 25, type: "summary_completion", text: "Sub-Saharan Africa's fertility rate is approximately ________ births per woman.", correctAnswer: "4.6", explanation: "The passage says 'approximately 4.6 births per woman.'" },
        { number: 26, type: "summary_completion", text: "International migrants represent about ________ per cent of the global population.", correctAnswer: "3.6", explanation: "The passage says 'about 3.6 per cent.'" }
      ]
    },
    {
      title: "Robotics in Modern Industry",
      text: `A. Industrial robotics has evolved from a niche manufacturing technology into a transformative force reshaping production processes across virtually every sector of the global economy. The International Federation of Robotics (IFR) reported that the global stock of operational industrial robots reached approximately 3.9 million units in 2022, with annual installations exceeding 500,000 units for the first time. This rapid growth reflects falling costs, improving capabilities, and growing recognition of the productivity and quality advantages that robotic automation delivers.

B. The automotive industry remains the largest single user of industrial robots, accounting for approximately thirty per cent of global installations. Robots perform welding, painting, assembly, and quality inspection tasks with precision and consistency that exceed human capabilities. A modern automotive plant may deploy hundreds of robots working in coordinated sequences, with cycle times measured in seconds. The industry's early adoption of robotics in the 1960s and 1970s — pioneered by companies like General Motors and Toyota — established manufacturing practices and safety standards that other sectors have subsequently adopted.

C. Electronics manufacturing has emerged as the fastest-growing market for industrial robots, driven by the precision requirements of producing smartphones, semiconductors, and other miniaturised devices. Assembly tasks that require placing components accurate to within micrometres are beyond the capabilities of even the most skilled human workers. The electronics sector now rivals automotive as the largest consumer of industrial robots in several countries, particularly in Asia.

D. The food and beverage industry, traditionally characterised by manual labour, is rapidly automating. Robots now sort, package, palletise, and even prepare food products. The COVID-19 pandemic accelerated this trend by highlighting the vulnerability of workforces to disease outbreaks. Meat processing plants, where workers operate in close proximity in cold, damp conditions, proved particularly susceptible to infection clusters, prompting significant investment in robotic alternatives.

E. Collaborative robots represent the fastest-growing segment of the industrial robotics market. Unlike traditional industrial robots, which operate behind safety fences to protect human workers, cobots are designed to work safely in direct contact with people. They typically feature force-limiting sensors, rounded edges, and low operating speeds that minimise injury risk. Cobots are particularly attractive for small and medium-sized enterprises (SMEs) that lack the capital, space, or technical expertise for traditional robotic installations. Their relatively low cost — typically $20,000 to $50,000 — and ease of programming make robotic automation accessible to businesses that previously could not justify the investment.

F. Artificial intelligence is dramatically expanding the capabilities of industrial robots. Machine vision systems enable robots to identify and manipulate objects of varying shapes, sizes, and orientations — a task that traditional programmed robots could not handle. Reinforcement learning allows robots to improve their performance through trial and error, developing optimal strategies for tasks like bin picking and assembly. Digital twins — virtual replicas of physical robotic systems — enable engineers to simulate, test, and optimise production processes before implementing them on the factory floor.

G. The geographic distribution of industrial robots reveals significant disparities. South Korea has the highest robot density in the world, with approximately 1,012 robots per 10,000 manufacturing employees in 2022. Singapore, Japan, and Germany also rank among the most automated economies. China, while having a lower robot density, is the world's largest market for new installations, accounting for over fifty per cent of global robot orders. Many developing countries, by contrast, have robot densities below ten per 10,000 employees.

H. The social implications of industrial robotics extend beyond employment effects. Robotic automation can improve workplace safety by removing humans from dangerous environments. It can enhance product quality and consistency, reducing waste and recalls. However, the benefits of robotics-driven productivity gains have not always been shared equitably: in many countries, the economic gains from automation have disproportionately accrued to capital owners and highly skilled workers, contributing to wage stagnation and inequality among less-skilled workers.`,
      questions: [
        { number: 27, type: "matching_information", text: "The impact of a pandemic on food industry automation", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "D", explanation: "Paragraph D discusses how COVID-19 accelerated automation in food processing." },
        { number: 28, type: "matching_information", text: "Countries with the highest robot density", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "G", explanation: "Paragraph G provides robot density statistics by country." },
        { number: 29, type: "matching_information", text: "The cost and accessibility of collaborative robots", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "E", explanation: "Paragraph E discusses cobot costs of $20,000-$50,000." },
        { number: 30, type: "matching_information", text: "The use of virtual replicas to test robotic systems", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "F", explanation: "Paragraph F discusses digital twins." },
        { number: 31, type: "flow_chart_completion", text: "The global stock of industrial robots reached approximately ________ million units in 2022.", correctAnswer: "3.9", explanation: "The passage says 'approximately 3.9 million units.'" },
        { number: 32, type: "flow_chart_completion", text: "The automotive industry accounts for approximately ________ per cent of global robot installations.", correctAnswer: "thirty", explanation: "The passage says 'approximately thirty per cent.'" },
        { number: 33, type: "flow_chart_completion", text: "South Korea has approximately ________ robots per 10,000 manufacturing employees.", correctAnswer: "1,012", explanation: "The passage states 'approximately 1,012 robots per 10,000.'" },
        { number: 34, type: "flow_chart_completion", text: "China accounts for over ________ per cent of global robot orders.", correctAnswer: "fifty", explanation: "The passage says 'over fifty per cent of global robot orders.'" },
        { number: 35, type: "short_answer", text: "What type of robots can work safely in direct contact with humans?", correctAnswer: "collaborative robots/cobots", explanation: "The passage describes cobots as designed to work safely with people." },
        { number: 36, type: "short_answer", text: "What is the typical cost range for a collaborative robot?", correctAnswer: "$20,000 to $50,000", explanation: "The passage states this price range." },
        { number: 37, type: "short_answer", text: "What technology allows robots to improve through trial and error?", correctAnswer: "reinforcement learning", explanation: "The passage says 'Reinforcement learning allows robots to improve their performance through trial and error.'" },
        { number: 38, type: "short_answer", text: "Which industry was the first major adopter of industrial robots?", correctAnswer: "automotive industry", explanation: "The passage says the automotive industry's 'early adoption of robotics in the 1960s and 1970s.'" },
        { number: 39, type: "short_answer", text: "What do machine vision systems enable robots to do?", correctAnswer: "identify and manipulate objects", explanation: "The passage says vision systems 'enable robots to identify and manipulate objects.'" },
        { number: 40, type: "short_answer", text: "What are virtual replicas of physical robotic systems called?", correctAnswer: "digital twins", explanation: "The passage defines 'Digital twins — virtual replicas of physical robotic systems.'" }
      ]
    }
  ]
};
