import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_54: ReadingTest = {
  id: 54,
  passages: [
    {
      title: "Ancient Trade Routes",
      text: `The exchange of goods between distant communities is as old as civilisation itself. Long before the establishment of formal trade agreements or international organisations, ancient peoples developed extensive networks for the movement of commodities, ideas, and technologies across vast distances. These trade routes shaped the economic, cultural, and political landscapes of the ancient world in ways that continue to resonate today.

The obsidian trade of the Neolithic period represents one of the earliest examples of long-distance commerce. Obsidian, a volcanic glass prized for its razor-sharp edges, was sourced from a limited number of volcanic sites in Anatolia (modern Turkey), the Aegean islands, and parts of East Africa. Archaeological evidence shows that obsidian from Anatolian sources was traded across distances exceeding 800 kilometres by the seventh millennium BCE, reaching communities throughout the Fertile Crescent. The systematic nature of this trade suggests the existence of established exchange networks and possibly specialised traders.

The Incense Route, connecting the Arabian Peninsula with the Mediterranean world, was one of the most lucrative trade corridors of antiquity. Frankincense and myrrh — aromatic resins used in religious ceremonies, medicine, and embalming — were harvested in present-day Oman and Yemen and transported overland through the Arabian Desert to markets in Egypt, Greece, and Rome. The journey covered approximately 2,400 kilometres and could take several months. The kingdoms of Saba (Sheba), Qataban, and Nabataea grew wealthy by controlling segments of this route, imposing tolls and providing services to caravans.

The Maritime Spice Route, linking Southeast Asia with the Middle East and eventually Europe, facilitated the trade in pepper, cinnamon, cloves, and nutmeg that drove much of pre-modern global commerce. Arab and Indian sailors navigated the Indian Ocean using monsoon winds, establishing trading posts along the coasts of India, East Africa, and Southeast Asia. The port of Muziris on India's Malabar Coast served as a major hub, where Roman merchants exchanged gold for pepper and other spices. Excavations at the site have uncovered Roman coins, amphorae, and other artefacts confirming the scale of this commerce.

The Trans-Saharan trade routes connected sub-Saharan Africa with North Africa and the Mediterranean world across one of the planet's most forbidding landscapes. Camel caravans — sometimes numbering thousands of animals — transported gold, salt, ivory, and enslaved people across the desert. The city of Timbuktu, situated at the junction of the Niger River and the southern edge of the Sahara, became a legendary trading centre and seat of Islamic scholarship. At its peak in the fourteenth century, the Malian Empire, which controlled much of the trans-Saharan trade, was among the wealthiest polities in the world. Mansa Musa's pilgrimage to Mecca in 1324, during which he reportedly distributed so much gold that he depressed prices in Cairo, remains one of history's most vivid illustrations of trans-Saharan wealth.

The Amber Road, connecting the Baltic Sea region with the Mediterranean, facilitated the trade of Baltic amber — fossilised tree resin valued for jewellery and decorative objects — to Greek and Roman markets. Archaeological discoveries of Baltic amber in Mycenaean graves dating to the sixteenth century BCE demonstrate the antiquity of this trade. The route passed through Germanic and Celtic territories, fostering cultural contacts that influenced artistic styles and technological exchange across Europe.

The Tin Route linked Cornwall in southwestern England with Mediterranean bronze-working centres during the Bronze Age. Tin, essential for alloying with copper to produce bronze, was relatively rare in the ancient world. Phoenician and later Greek traders sailed to Cornwall — known to them as the "Cassiterides" or Tin Islands — to obtain this strategic resource. The tin trade illustrates how the demand for specific raw materials could drive maritime exploration and establish commercial relationships spanning thousands of kilometres.

These ancient trade routes were far more than commercial corridors. They served as conduits for the transmission of religions, languages, technologies, and diseases. They created zones of cultural interaction and conflict, shaped political alliances and rivalries, and laid the foundations for the interconnected global economy that exists today.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "What was obsidian valued for in the Neolithic period?", options: ["A. Its decorative colours", "B. Its razor-sharp edges", "C. Its resistance to heat", "D. Its rarity as a gemstone"], correctAnswer: "B", explanation: "The passage says obsidian was 'prized for its razor-sharp edges.'" },
        { number: 2, type: "multiple_choice", text: "Which commodities were traded along the Incense Route?", options: ["A. Gold and silver", "B. Silk and spices", "C. Frankincense and myrrh", "D. Tin and copper"], correctAnswer: "C", explanation: "The passage identifies 'Frankincense and myrrh' as the commodities." },
        { number: 3, type: "multiple_choice", text: "What event demonstrated the wealth of the Malian Empire?", options: ["A. The construction of Timbuktu's libraries", "B. Mansa Musa's pilgrimage to Mecca", "C. The conquest of North Africa", "D. The founding of Cairo"], correctAnswer: "B", explanation: "The passage describes 'Mansa Musa's pilgrimage to Mecca in 1324.'" },
        { number: 4, type: "multiple_choice", text: "Why was tin from Cornwall strategically important?", options: ["A. It was used for currency", "B. It was needed to produce bronze", "C. It powered early steam engines", "D. It was used in ship construction"], correctAnswer: "B", explanation: "The passage says tin was 'essential for alloying with copper to produce bronze.'" },
        { number: 5, type: "true_false_not_given", text: "Obsidian was traded over 800 kilometres by the seventh millennium BCE.", correctAnswer: "TRUE", explanation: "The passage directly states this." },
        { number: 6, type: "true_false_not_given", text: "The Incense Route journey covered approximately 3,000 kilometres.", correctAnswer: "FALSE", explanation: "The passage says 'approximately 2,400 kilometres.'" },
        { number: 7, type: "true_false_not_given", text: "Roman coins have been found at the port of Muziris.", correctAnswer: "TRUE", explanation: "The passage says 'Excavations at the site have uncovered Roman coins.'" },
        { number: 8, type: "true_false_not_given", text: "Mansa Musa's pilgrimage took place in 1424.", correctAnswer: "FALSE", explanation: "The passage says 'in 1324.'" },
        { number: 9, type: "true_false_not_given", text: "Baltic amber has been found in Mycenaean graves.", correctAnswer: "TRUE", explanation: "The passage directly states this." },
        { number: 10, type: "true_false_not_given", text: "The Phoenicians called Cornwall the 'Gold Islands'.", correctAnswer: "FALSE", explanation: "The passage says they called it 'Cassiterides' or 'Tin Islands.'" },
        { number: 11, type: "true_false_not_given", text: "The Trans-Saharan trade included the transport of enslaved people.", correctAnswer: "TRUE", explanation: "The passage lists 'enslaved people' among goods transported." },
        { number: 12, type: "true_false_not_given", text: "Timbuktu was located on the coast of West Africa.", correctAnswer: "FALSE", explanation: "The passage says Timbuktu was 'at the junction of the Niger River and the southern edge of the Sahara.'" },
        { number: 13, type: "true_false_not_given", text: "The Amber Road exclusively traded amber for iron.", correctAnswer: "NOT GIVEN", explanation: "The passage does not mention iron being exchanged for amber." }
      ]
    },
    {
      title: "Water Resource Management",
      text: `A. Water is the most essential natural resource, yet it is increasingly scarce in many parts of the world. Approximately 2.2 billion people — nearly one in three of the global population — lack access to safely managed drinking water. Climate change, population growth, agricultural expansion, and industrial pollution are intensifying pressure on freshwater supplies, making water resource management one of the defining challenges of the twenty-first century.

B. The global water cycle distributes approximately 500,000 cubic kilometres of water through evaporation and precipitation each year. However, only about 2.5 per cent of Earth's water is freshwater, and most of this is locked in glaciers and ice caps. The accessible freshwater in rivers, lakes, and shallow aquifers represents less than one per cent of the total. This limited supply is distributed unevenly: Brazil, Russia, Canada, and the United States hold approximately forty per cent of the world's renewable freshwater resources, while regions including the Middle East, North Africa, and parts of South Asia face chronic scarcity.

C. Agriculture is by far the largest consumer of freshwater, accounting for approximately seventy per cent of global withdrawals. Irrigation has been essential for food production since ancient times, but modern large-scale irrigation systems often use water inefficiently. Flood irrigation, in which fields are simply inundated with water, can lose up to sixty per cent of applied water to evaporation and runoff. Drip irrigation systems, which deliver water directly to plant roots through networks of tubes and emitters, can reduce water use by thirty to seventy per cent while maintaining or improving crop yields.

D. Urban water management presents distinct challenges. Ageing infrastructure in many cities results in significant water losses through leaks — London's Victorian-era pipe network loses approximately twenty-four per cent of treated water before it reaches consumers. Rapid urbanisation in developing countries often outpaces the construction of water supply and sanitation infrastructure, forcing millions to rely on contaminated sources. Singapore has become a model of urban water management, developing a diversified supply strategy that includes rainwater collection, imported water, desalinated seawater, and NEWater — highly treated reclaimed water that meets drinking water standards.

E. Groundwater, which supplies approximately half of all drinking water globally, is being depleted at unsustainable rates in many regions. The Ogallala Aquifer in the central United States, one of the world's largest, has lost approximately thirty per cent of its stored water since large-scale pumping began in the 1950s. In parts of India, groundwater levels have fallen by more than twenty metres in recent decades as millions of wells extract water faster than rainfall can replenish it. Once depleted, many aquifers take centuries or millennia to recharge.

F. Desalination — the removal of salt from seawater — has become an increasingly important source of freshwater, particularly in arid coastal regions. Approximately 21,000 desalination plants operate worldwide, producing over 100 million cubic metres of freshwater daily. The Middle East relies heavily on desalination, with Saudi Arabia and the United Arab Emirates among the world's largest producers. However, desalination remains energy-intensive and expensive compared to conventional freshwater sources. The discharge of concentrated brine — a byproduct of the process — can harm marine ecosystems.

G. Integrated Water Resource Management (IWRM) has emerged as the dominant framework for addressing water challenges. IWRM promotes the coordinated development and management of water, land, and related resources to maximise economic and social welfare without compromising ecosystem sustainability. Key principles include stakeholder participation, recognition of water as an economic good, and management at the river basin level. While widely endorsed in policy documents, implementation of IWRM has proved challenging, particularly in countries with weak governance institutions.

H. The concept of "virtual water" — the water embedded in the production of goods and services — has added a new dimension to water resource analysis. Producing one kilogram of beef requires approximately 15,400 litres of water, while one kilogram of wheat requires about 1,800 litres. International trade in agricultural products effectively transfers water from water-rich producing countries to water-scarce importing countries. Understanding these virtual water flows can inform trade policy and help countries manage their water footprints more sustainably.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Paragraph B", options: ["i. Agriculture's thirst", "ii. Global water distribution", "iii. Groundwater in crisis", "iv. City water challenges", "v. Virtual water in trade", "vi. Removing salt from seawater", "vii. A framework for water governance", "viii. The water scarcity challenge"], correctAnswer: "ii", explanation: "Paragraph B discusses how freshwater is distributed globally." },
        { number: 15, type: "matching_headings", text: "Paragraph D", options: ["i. Agriculture's thirst", "ii. Global water distribution", "iii. Groundwater in crisis", "iv. City water challenges", "v. Virtual water in trade", "vi. Removing salt from seawater", "vii. A framework for water governance", "viii. The water scarcity challenge"], correctAnswer: "iv", explanation: "Paragraph D discusses urban water management." },
        { number: 16, type: "matching_headings", text: "Paragraph F", options: ["i. Agriculture's thirst", "ii. Global water distribution", "iii. Groundwater in crisis", "iv. City water challenges", "v. Virtual water in trade", "vi. Removing salt from seawater", "vii. A framework for water governance", "viii. The water scarcity challenge"], correctAnswer: "vi", explanation: "Paragraph F discusses desalination." },
        { number: 17, type: "matching_headings", text: "Paragraph H", options: ["i. Agriculture's thirst", "ii. Global water distribution", "iii. Groundwater in crisis", "iv. City water challenges", "v. Virtual water in trade", "vi. Removing salt from seawater", "vii. A framework for water governance", "viii. The water scarcity challenge"], correctAnswer: "v", explanation: "Paragraph H discusses virtual water." },
        { number: 18, type: "table_completion", text: "Approximately ________ billion people lack safely managed drinking water.", correctAnswer: "2.2", explanation: "The passage says 'Approximately 2.2 billion people.'" },
        { number: 19, type: "table_completion", text: "Only about ________ per cent of Earth's water is freshwater.", correctAnswer: "2.5", explanation: "The passage says 'only about 2.5 per cent.'" },
        { number: 20, type: "table_completion", text: "Agriculture accounts for approximately ________ per cent of global water withdrawals.", correctAnswer: "seventy", explanation: "The passage states 'approximately seventy per cent.'" },
        { number: 21, type: "table_completion", text: "London's pipe network loses approximately ________ per cent of treated water.", correctAnswer: "twenty-four", explanation: "The passage says 'approximately twenty-four per cent.'" },
        { number: 22, type: "table_completion", text: "The Ogallala Aquifer has lost approximately ________ per cent of stored water.", correctAnswer: "thirty", explanation: "The passage says 'approximately thirty per cent.'" },
        { number: 23, type: "table_completion", text: "Approximately ________ desalination plants operate worldwide.", correctAnswer: "21,000", explanation: "The passage says 'Approximately 21,000 desalination plants.'" },
        { number: 24, type: "table_completion", text: "Producing one kilogram of beef requires approximately ________ litres of water.", correctAnswer: "15,400", explanation: "The passage says 'approximately 15,400 litres.'" },
        { number: 25, type: "table_completion", text: "Drip irrigation can reduce water use by ________ to seventy per cent.", correctAnswer: "thirty", explanation: "The passage says 'thirty to seventy per cent.'" },
        { number: 26, type: "table_completion", text: "In parts of India, groundwater levels have fallen by more than ________ metres.", correctAnswer: "twenty", explanation: "The passage says 'more than twenty metres.'" }
      ]
    },
    {
      title: "Technology Revolution and Culture",
      text: `A. The relationship between technological change and cultural transformation has been a subject of scholarly inquiry since at least the Industrial Revolution. Each major wave of innovation — from the printing press to the internet — has not only altered material conditions but has also reshaped how people think, communicate, create art, and construct meaning. The current digital revolution is no exception, and its cultural consequences are still unfolding in ways that are both exhilarating and unsettling.

B. The printing press, developed by Gutenberg in the mid-fifteenth century, provides the closest historical analogy to the digital revolution's cultural impact. Before printing, knowledge was preserved and transmitted through handwritten manuscripts, limiting literacy to a small elite. The press made books affordable and widely available, democratising access to information and catalysing intellectual movements including the Renaissance, the Reformation, and the Scientific Revolution. It also standardised languages, as printed works established uniform spellings and grammars that replaced the diversity of regional dialects.

C. Photography, invented in the 1830s, fundamentally altered visual culture. For the first time, images could be produced mechanically rather than through artistic skill, raising questions about the nature of art and representation that persist to this day. The photograph's claim to objectivity — its apparent ability to capture reality directly — transformed journalism, science, and personal memory. Family photographs became cherished possessions, and photojournalism emerged as a powerful force in shaping public opinion about events from war to social reform.

D. Cinema extended photography into motion and narrative, creating the dominant entertainment medium of the twentieth century. Film studios became major cultural institutions, and movie stars achieved global fame on a scale previously impossible. Cinema also served as a vehicle for propaganda, artistic experimentation, and cross-cultural exchange. Hollywood films exported American values and consumer culture worldwide, while national cinema traditions — Italian neorealism, French New Wave, Japanese anime — reflected and shaped their respective societies.

E. Television, which achieved mass adoption in the 1950s and 1960s, brought moving images into private homes, collapsing the distance between events and audiences. Live broadcasts of events — from the Moon landing to political debates to natural disasters — created shared cultural experiences on an unprecedented scale. Television advertising transformed consumer culture by creating desires for products through sophisticated psychological techniques. Critics, from Neil Postman to Pierre Bourdieu, argued that television's emphasis on entertainment and spectacle was degrading public discourse and intellectual life.

F. The internet and social media have accelerated and intensified these cultural dynamics. User-generated content has democratised creative expression: anyone with a smartphone can publish writing, music, photography, or video to a global audience. Platforms like YouTube, TikTok, and Instagram have created new forms of celebrity, new aesthetic movements, and new modes of cultural participation. Yet this democratisation has also been accompanied by concerns about information quality, attention fragmentation, and the dominance of algorithmic curation in determining what content reaches audiences.

G. Artificial intelligence is now entering the cultural sphere with tools that generate text, images, music, and video from textual prompts. These technologies raise fundamental questions about authorship, originality, and the value of human creativity. If an AI system can produce a painting in the style of Rembrandt or compose music indistinguishable from a human composer, what does this mean for the concept of artistic creation? The debate mirrors earlier anxieties about photography displacing painting and digital music replacing live performance.

H. The cultural consequences of technological change are never purely positive or negative. Each innovation creates new possibilities for expression and connection while simultaneously disrupting established practices and institutions. The challenge for societies is to harness the creative potential of new technologies while preserving the cultural values — authenticity, craftsmanship, critical thinking, and diverse expression — that give meaning to human experience. This balancing act has been a constant throughout the history of technological change, and there is no reason to believe the current revolution will be the last to demand it.`,
      questions: [
        { number: 27, type: "matching_information", text: "The standardisation of languages through printed works", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "B", explanation: "Paragraph B discusses how printing 'standardised languages.'" },
        { number: 28, type: "matching_information", text: "Questions about authorship raised by AI-generated art", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "G", explanation: "Paragraph G discusses AI and questions about authorship and originality." },
        { number: 29, type: "matching_information", text: "The role of television in creating shared cultural experiences", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "E", explanation: "Paragraph E discusses live broadcasts creating shared cultural experiences." },
        { number: 30, type: "matching_information", text: "The impact of user-generated content on creative expression", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "F", explanation: "Paragraph F discusses how user-generated content democratised creative expression." },
        { number: 31, type: "sentence_completion", text: "Before printing, knowledge was transmitted through handwritten ________.", correctAnswer: "manuscripts", explanation: "The passage says 'handwritten manuscripts.'" },
        { number: 32, type: "sentence_completion", text: "Photography was invented in the ________.", correctAnswer: "1830s", explanation: "The passage says 'invented in the 1830s.'" },
        { number: 33, type: "sentence_completion", text: "Television achieved mass adoption in the ________ and 1960s.", correctAnswer: "1950s", explanation: "The passage says 'the 1950s and 1960s.'" },
        { number: 34, type: "sentence_completion", text: "Hollywood films exported American values and ________ culture worldwide.", correctAnswer: "consumer", explanation: "The passage says 'American values and consumer culture.'" },
        { number: 35, type: "sentence_completion", text: "Television advertising used sophisticated ________ techniques to create desires.", correctAnswer: "psychological", explanation: "The passage says 'sophisticated psychological techniques.'" },
        { number: 36, type: "short_answer", text: "Name one critic of television mentioned in the passage.", correctAnswer: "Neil Postman", explanation: "The passage mentions 'Neil Postman' and 'Pierre Bourdieu.'" },
        { number: 37, type: "short_answer", text: "What three types of content can AI tools generate from text prompts?", correctAnswer: "text, images, music", explanation: "The passage says AI generates 'text, images, music, and video.'" },
        { number: 38, type: "short_answer", text: "What historical analogy is used for the digital revolution's cultural impact?", correctAnswer: "the printing press", explanation: "The passage says the printing press 'provides the closest historical analogy.'" },
        { number: 39, type: "short_answer", text: "Name one national cinema tradition mentioned.", correctAnswer: "Italian neorealism", explanation: "The passage lists Italian neorealism, French New Wave, and Japanese anime." },
        { number: 40, type: "short_answer", text: "What does the passage say photography's claim to objectivity appeared to capture?", correctAnswer: "reality", explanation: "The passage says photography's 'apparent ability to capture reality directly.'" }
      ]
    }
  ]
};
