import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_55: ReadingTest = {
  id: 55,
  passages: [
    {
      title: "Innovation in Ophthalmology",
      text: `Ophthalmology — the branch of medicine dedicated to the diagnosis and treatment of eye disorders — has undergone a remarkable transformation over the past century. Advances in surgical techniques, diagnostic technology, and pharmaceutical treatments have restored or preserved sight for hundreds of millions of people worldwide. Yet vision impairment remains a significant global health burden, with the World Health Organization estimating that at least 2.2 billion people have a near or distance vision impairment, of whom at least one billion have conditions that could have been prevented or have yet to be addressed.

The development of intraocular lens (IOL) implantation for cataract surgery represents one of the most significant advances in ophthalmic history. Cataracts — the clouding of the eye's natural lens — are the leading cause of blindness worldwide, responsible for approximately fifty per cent of all cases. Sir Harold Ridley performed the first successful IOL implantation in 1949, after observing that fragments of acrylic plastic from aircraft canopies that lodged in the eyes of World War II pilots were tolerated by the body. Modern cataract surgery, using phacoemulsification — a technique that uses ultrasonic vibrations to break up the clouded lens before extraction — takes approximately fifteen to twenty minutes and has a success rate exceeding ninety-five per cent.

Laser technology has revolutionised the treatment of several eye conditions. LASIK (Laser-Assisted In Situ Keratomileusis), introduced in the 1990s, corrects refractive errors including myopia, hyperopia, and astigmatism by reshaping the cornea. The procedure has been performed on over forty million people worldwide. For diabetic retinopathy — a complication of diabetes that damages retinal blood vessels — laser photocoagulation can seal leaking vessels and prevent vision loss. More recently, femtosecond lasers have been applied to cataract surgery, enabling blade-free incisions with micrometer precision.

The diagnosis of eye diseases has been transformed by optical coherence tomography (OCT), introduced commercially in the mid-1990s. OCT uses light waves to capture cross-sectional images of the retina with resolution approaching five micrometres — sufficient to visualise individual cell layers. This technology enables early detection of conditions including glaucoma, macular degeneration, and diabetic retinopathy, often before symptoms appear. OCT angiography, a more recent development, can image retinal blood flow without the need for injected contrast dyes.

Anti-vascular endothelial growth factor (anti-VEGF) therapy has transformed the treatment of wet age-related macular degeneration (AMD), the leading cause of vision loss among older adults in developed countries. Before anti-VEGF drugs — including ranibizumab, bevacizumab, and aflibercept — became available in the mid-2000s, wet AMD typically led to severe, irreversible vision loss. These drugs, injected directly into the eye, inhibit the growth of abnormal blood vessels that leak fluid beneath the retina. Clinical trials demonstrated that approximately forty per cent of patients receiving anti-VEGF treatment experienced significant vision improvement, compared to virtually none with previous treatments.

Gene therapy represents the newest frontier in ophthalmology. In 2017, the US Food and Drug Administration approved Luxturna — the first gene therapy for an inherited disease — for the treatment of Leber congenital amaurosis, a rare genetic condition that causes progressive blindness. Luxturna delivers a functional copy of the RPE65 gene directly to retinal cells, enabling them to produce a protein essential for converting light into electrical signals. Clinical trials showed significant improvement in patients' ability to navigate obstacle courses in low light, demonstrating functional vision restoration.

Artificial intelligence is increasingly being applied to ophthalmic diagnosis. Deep learning algorithms trained on millions of retinal images can detect diabetic retinopathy, glaucoma, and AMD with accuracy comparable to specialist ophthalmologists. Google Health's AI system for diabetic retinopathy screening has been deployed in clinics in India and Thailand, where shortages of trained ophthalmologists limit access to screening. These AI tools have the potential to dramatically expand access to eye care in underserved populations.

Despite these advances, significant challenges remain. Globally, approximately 43 million people are blind and 295 million have moderate to severe vision impairment. The vast majority live in low- and middle-income countries where access to eye care services is limited. Addressing this burden requires not only continued technological innovation but also the development of affordable, scalable delivery models that can reach the populations most in need.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "What is the leading cause of blindness worldwide?", options: ["A. Glaucoma", "B. Cataracts", "C. Diabetic retinopathy", "D. Macular degeneration"], correctAnswer: "B", explanation: "The passage says cataracts are 'the leading cause of blindness worldwide.'" },
        { number: 2, type: "multiple_choice", text: "Who performed the first successful IOL implantation?", options: ["A. Harold Ridley", "B. Charles Kelman", "C. Jules Gonin", "D. Albrecht von Graefe"], correctAnswer: "A", explanation: "The passage says 'Sir Harold Ridley performed the first successful IOL implantation in 1949.'" },
        { number: 3, type: "multiple_choice", text: "How many people have undergone LASIK surgery worldwide?", options: ["A. Over ten million", "B. Over twenty million", "C. Over forty million", "D. Over sixty million"], correctAnswer: "C", explanation: "The passage says 'performed on over forty million people worldwide.'" },
        { number: 4, type: "multiple_choice", text: "What percentage of patients showed vision improvement with anti-VEGF treatment?", options: ["A. Twenty per cent", "B. Thirty per cent", "C. Forty per cent", "D. Fifty per cent"], correctAnswer: "C", explanation: "The passage says 'approximately forty per cent of patients.'" },
        { number: 5, type: "true_false_not_given", text: "At least 2.2 billion people have some form of vision impairment.", correctAnswer: "TRUE", explanation: "The passage directly states this WHO estimate." },
        { number: 6, type: "true_false_not_given", text: "Modern cataract surgery takes approximately one hour.", correctAnswer: "FALSE", explanation: "The passage says 'approximately fifteen to twenty minutes.'" },
        { number: 7, type: "true_false_not_given", text: "OCT was introduced commercially in the mid-1990s.", correctAnswer: "TRUE", explanation: "The passage directly states this." },
        { number: 8, type: "true_false_not_given", text: "Luxturna was the first gene therapy approved for any disease.", correctAnswer: "FALSE", explanation: "The passage says it was 'the first gene therapy for an inherited disease,' implying other gene therapies may have existed for other types." },
        { number: 9, type: "true_false_not_given", text: "Google Health's AI has been deployed in India and Thailand.", correctAnswer: "TRUE", explanation: "The passage directly states this." },
        { number: 10, type: "true_false_not_given", text: "Approximately 43 million people are blind globally.", correctAnswer: "TRUE", explanation: "The passage directly states this." },
        { number: 11, type: "true_false_not_given", text: "Anti-VEGF drugs are taken orally.", correctAnswer: "FALSE", explanation: "The passage says they are 'injected directly into the eye.'" },
        { number: 12, type: "true_false_not_given", text: "Ridley's observation about IOL materials came from studying contact lenses.", correctAnswer: "FALSE", explanation: "The passage says it came from observing 'acrylic plastic from aircraft canopies' in WWII pilots' eyes." },
        { number: 13, type: "true_false_not_given", text: "Femtosecond lasers are used exclusively for LASIK procedures.", correctAnswer: "NOT GIVEN", explanation: "The passage mentions femtosecond lasers for cataract surgery but does not say they are exclusive to any procedure." }
      ]
    },
    {
      title: "Urbanization and Infrastructure",
      text: `A. The rapid growth of cities worldwide has created unprecedented demand for infrastructure — the physical systems and facilities that enable urban life. Roads, bridges, water supply networks, sewerage systems, electricity grids, and telecommunications networks form the backbone of urban economies and determine the quality of life for billions of city dwellers. The challenge of building, maintaining, and upgrading this infrastructure is one of the most pressing issues facing cities in both developed and developing countries.

B. Infrastructure investment needs are enormous. The Global Infrastructure Hub estimates that the world must invest approximately $94 trillion in infrastructure between 2016 and 2040 to keep pace with economic growth — an average of $3.7 trillion per year. Current investment falls approximately fifteen per cent short of this requirement, creating an annual infrastructure gap of over $500 billion. The shortfall is particularly acute in developing countries, where rapid urbanisation is outpacing infrastructure construction.

C. Water and sanitation infrastructure illustrates both the progress made and the challenges remaining. Access to improved water sources has increased significantly over the past two decades, yet approximately 2.2 billion people still lack safely managed drinking water, and 4.2 billion lack safely managed sanitation. In many rapidly growing cities in Africa and Asia, water supply systems serve only a fraction of the population, forcing millions to rely on informal vendors who charge prices many times higher than utility rates.

D. Transportation infrastructure shapes urban form and economic productivity. Cities with well-developed public transit systems — Tokyo, London, Singapore — tend to be more economically productive and environmentally efficient than car-dependent cities of similar size. Investment in mass transit has surged in recent decades: China alone has built over 8,000 kilometres of metro lines since 2000, more than the rest of the world combined. Bus rapid transit systems have been adopted by over 170 cities worldwide as a cost-effective alternative to rail-based systems.

E. Energy infrastructure is undergoing a fundamental transformation driven by the shift toward renewable sources. Traditional centralised power systems — in which large power plants generate electricity that is transmitted over long distances to consumers — are being supplemented by distributed generation from rooftop solar panels, small wind turbines, and community energy projects. Smart grids, which use digital technology to monitor and manage electricity flows in real time, are enabling this transition by balancing variable renewable supply with fluctuating demand.

F. Digital infrastructure — broadband networks, data centres, and mobile telecommunications — has become as essential to modern urban life as roads and water pipes. The COVID-19 pandemic underscored this reality, as remote work, online education, and digital commerce depended entirely on reliable internet connectivity. Yet a significant digital divide persists: the International Telecommunication Union estimates that approximately 2.7 billion people worldwide still lack internet access, predominantly in low-income countries and rural areas.

G. Climate change adaptation is creating new infrastructure demands. Coastal cities must invest in sea walls, flood barriers, and drainage systems to protect against rising sea levels and more intense storms. Urban heat management requires expanded green infrastructure — parks, street trees, green roofs — to mitigate the urban heat island effect. Infrastructure designed for historical climate conditions may be inadequate for future extremes, requiring costly retrofitting or replacement.

H. Innovative financing mechanisms are emerging to address the infrastructure gap. Public-private partnerships (PPPs) leverage private capital and expertise to deliver public infrastructure projects, though they require careful structuring to ensure public accountability. Green bonds and sustainability-linked loans channel investment toward environmentally responsible projects. Multilateral development banks, including the World Bank and the Asian Infrastructure Investment Bank, provide financing for infrastructure in developing countries, often combined with technical assistance to strengthen governance and project management capacity.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Paragraph B", options: ["i. Climate-proofing cities", "ii. The scale of the investment challenge", "iii. Transport shaping cities", "iv. Digital connectivity gaps", "v. Water access progress and gaps", "vi. Energy system transformation", "vii. New ways to fund infrastructure", "viii. Defining urban infrastructure"], correctAnswer: "ii", explanation: "Paragraph B discusses the $94 trillion investment need." },
        { number: 15, type: "matching_headings", text: "Paragraph D", options: ["i. Climate-proofing cities", "ii. The scale of the investment challenge", "iii. Transport shaping cities", "iv. Digital connectivity gaps", "v. Water access progress and gaps", "vi. Energy system transformation", "vii. New ways to fund infrastructure", "viii. Defining urban infrastructure"], correctAnswer: "iii", explanation: "Paragraph D discusses transportation infrastructure shaping cities." },
        { number: 16, type: "matching_headings", text: "Paragraph F", options: ["i. Climate-proofing cities", "ii. The scale of the investment challenge", "iii. Transport shaping cities", "iv. Digital connectivity gaps", "v. Water access progress and gaps", "vi. Energy system transformation", "vii. New ways to fund infrastructure", "viii. Defining urban infrastructure"], correctAnswer: "iv", explanation: "Paragraph F discusses digital infrastructure and the digital divide." },
        { number: 17, type: "matching_headings", text: "Paragraph G", options: ["i. Climate-proofing cities", "ii. The scale of the investment challenge", "iii. Transport shaping cities", "iv. Digital connectivity gaps", "v. Water access progress and gaps", "vi. Energy system transformation", "vii. New ways to fund infrastructure", "viii. Defining urban infrastructure"], correctAnswer: "i", explanation: "Paragraph G discusses climate change adaptation infrastructure." },
        { number: 18, type: "table_completion", text: "Global infrastructure investment needed 2016-2040 is approximately $________ trillion.", correctAnswer: "94", explanation: "The passage says 'approximately $94 trillion.'" },
        { number: 19, type: "table_completion", text: "The annual infrastructure gap exceeds $________ billion.", correctAnswer: "500", explanation: "The passage says 'over $500 billion.'" },
        { number: 20, type: "table_completion", text: "Approximately ________ billion people lack safely managed sanitation.", correctAnswer: "4.2", explanation: "The passage says '4.2 billion.'" },
        { number: 21, type: "table_completion", text: "China has built over ________ kilometres of metro lines since 2000.", correctAnswer: "8,000", explanation: "The passage says 'over 8,000 kilometres.'" },
        { number: 22, type: "table_completion", text: "BRT systems have been adopted by over ________ cities worldwide.", correctAnswer: "170", explanation: "The passage says 'over 170 cities.'" },
        { number: 23, type: "table_completion", text: "Approximately ________ billion people worldwide lack internet access.", correctAnswer: "2.7", explanation: "The passage says 'approximately 2.7 billion people.'" },
        { number: 24, type: "table_completion", text: "The required annual infrastructure investment averages $________ trillion per year.", correctAnswer: "3.7", explanation: "The passage says 'an average of $3.7 trillion per year.'" },
        { number: 25, type: "table_completion", text: "Current investment falls approximately ________ per cent short of the requirement.", correctAnswer: "fifteen", explanation: "The passage says 'approximately fifteen per cent short.'" },
        { number: 26, type: "table_completion", text: "Approximately ________ billion people lack safely managed drinking water.", correctAnswer: "2.2", explanation: "The passage says 'approximately 2.2 billion people.'" }
      ]
    },
    {
      title: "History of Astronomy and Space",
      text: `A. Humanity's fascination with the night sky is as old as consciousness itself. From the earliest cave paintings depicting celestial objects to the latest images from space telescopes, the study of astronomy has continually expanded our understanding of the universe and our place within it. The history of astronomical discovery is a story of increasingly powerful instruments, revolutionary theories, and the gradual recognition that the cosmos is far vaster, older, and stranger than our ancestors could have imagined.

B. Ancient civilisations made remarkable astronomical observations without the aid of telescopes. The Babylonians, recording celestial events on clay tablets as early as 1800 BCE, identified the major planets, tracked lunar cycles, and predicted eclipses with considerable accuracy. The ancient Greeks developed geometric models of planetary motion: Eratosthenes calculated the Earth's circumference around 240 BCE with an error of less than two per cent, while Aristarchus proposed a heliocentric model of the solar system nearly eighteen centuries before Copernicus.

C. The invention of the telescope in the early seventeenth century transformed astronomy from a naked-eye discipline into an observational science of unprecedented power. Galileo Galilei's observations beginning in 1609 — the moons of Jupiter, the phases of Venus, the craters of the Moon — provided crucial evidence for the Copernican heliocentric model. Isaac Newton's reflecting telescope, developed in 1668, and his mathematical framework for gravitational mechanics established the foundations for modern astronomical science.

D. The nineteenth century brought spectroscopy — the analysis of light by wavelength — which enabled astronomers to determine the chemical composition, temperature, and motion of celestial objects without visiting them. Joseph von Fraunhofer's discovery of absorption lines in the solar spectrum in 1814 led to the identification of elements present in the Sun and other stars. The Doppler effect, applied to stellar spectra, revealed that stars and galaxies are moving relative to Earth — a finding that would prove central to understanding the expansion of the universe.

E. Edwin Hubble's observations in the 1920s revolutionised cosmology. By identifying Cepheid variable stars in the Andromeda Nebula, Hubble demonstrated in 1924 that it was a separate galaxy far beyond the Milky Way — resolving a long-standing debate about the scale of the universe. In 1929, he showed that distant galaxies are receding from Earth at speeds proportional to their distance — a relationship now known as Hubble's Law — providing the observational foundation for the Big Bang theory.

F. The Space Age, inaugurated by the launch of Sputnik in 1957, opened the cosmos to direct exploration. The Apollo 11 mission in 1969 landed humans on the Moon for the first time. Robotic probes have since visited every planet in the solar system, landed on Mars, Venus, and Saturn's moon Titan, and sent the Voyager spacecraft beyond the solar system entirely. The Hubble Space Telescope, launched in 1990, has captured images of galaxies billions of light-years away, revealing the universe's structure and evolution in unprecedented detail.

G. The James Webb Space Telescope (JWST), launched in December 2021, represents the most powerful space observatory ever built. Operating primarily in infrared wavelengths, JWST can observe objects too distant and too faint for the Hubble telescope, including the first galaxies that formed after the Big Bang. Its early observations have already challenged existing models of galaxy formation by detecting unexpectedly large and mature galaxies at very high redshifts — suggesting that galaxies formed earlier and more rapidly than previously believed.

H. The search for extraterrestrial life has become a central focus of modern astronomy. The discovery of over 5,500 exoplanets — planets orbiting stars other than the Sun — since the first confirmed detection in 1992 has demonstrated that planetary systems are common in the galaxy. Several dozen of these planets orbit within their stars' "habitable zones," where liquid water could exist on the surface. Future telescopes aim to analyse the atmospheres of these worlds for biosignatures — chemical indicators such as oxygen, methane, and water vapour that might signal the presence of life.`,
      questions: [
        { number: 27, type: "matching_information", text: "The discovery that distant galaxies are moving away from Earth", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "E", explanation: "Paragraph E discusses Hubble's observation that galaxies are receding." },
        { number: 28, type: "matching_information", text: "Early observations that supported the heliocentric model", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "C", explanation: "Paragraph C discusses Galileo's observations supporting the Copernican model." },
        { number: 29, type: "matching_information", text: "The detection of unexpectedly mature galaxies", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "G", explanation: "Paragraph G discusses JWST detecting 'unexpectedly large and mature galaxies.'" },
        { number: 30, type: "matching_information", text: "The analysis of exoplanet atmospheres for signs of life", options: ["A", "B", "C", "D", "E", "F", "G", "H"], correctAnswer: "H", explanation: "Paragraph H discusses searching for biosignatures in exoplanet atmospheres." },
        { number: 31, type: "flow_chart_completion", text: "Eratosthenes calculated Earth's circumference around ________ BCE.", correctAnswer: "240", explanation: "The passage says 'around 240 BCE.'" },
        { number: 32, type: "flow_chart_completion", text: "Galileo began telescope observations in ________.", correctAnswer: "1609", explanation: "The passage says 'beginning in 1609.'" },
        { number: 33, type: "flow_chart_completion", text: "Hubble demonstrated Andromeda was a separate galaxy in ________.", correctAnswer: "1924", explanation: "The passage says 'Hubble demonstrated in 1924.'" },
        { number: 34, type: "flow_chart_completion", text: "The James Webb Space Telescope was launched in December ________.", correctAnswer: "2021", explanation: "The passage says 'launched in December 2021.'" },
        { number: 35, type: "short_answer", text: "What was the first artificial satellite launched into space?", correctAnswer: "Sputnik", explanation: "The passage says 'the launch of Sputnik in 1957.'" },
        { number: 36, type: "short_answer", text: "How many exoplanets have been discovered since 1992?", correctAnswer: "over 5,500", explanation: "The passage says 'over 5,500 exoplanets.'" },
        { number: 37, type: "short_answer", text: "What technique allows astronomers to determine the composition of stars?", correctAnswer: "spectroscopy", explanation: "The passage says 'spectroscopy — the analysis of light by wavelength.'" },
        { number: 38, type: "short_answer", text: "What mission first landed humans on the Moon?", correctAnswer: "Apollo 11", explanation: "The passage says 'The Apollo 11 mission in 1969.'" },
        { number: 39, type: "short_answer", text: "In what wavelengths does JWST primarily operate?", correctAnswer: "infrared", explanation: "The passage says 'Operating primarily in infrared wavelengths.'" },
        { number: 40, type: "short_answer", text: "What chemical indicators might signal life on exoplanets?", correctAnswer: "oxygen, methane, and water vapour", explanation: "The passage lists 'oxygen, methane, and water vapour' as biosignatures." }
      ]
    }
  ]
};
