import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_20: ReadingTest = {
  id: 20,
  passages: [
    {
      title: "Ancient Shipbuilding",
      text: `The history of shipbuilding is a story of human ingenuity and adaptation, stretching back thousands of years to the earliest civilisations that ventured onto rivers, lakes, and seas. Ships enabled trade, exploration, warfare, migration, and cultural exchange on a scale that would have been impossible by land alone. The evolution of ship design and construction techniques reflects the changing needs, materials, and technological capabilities of successive maritime cultures.

The earliest watercraft were simple dugout canoes, hollowed from single tree trunks using stone tools and fire. Archaeological evidence suggests that dugout canoes were in use as early as 8000 BCE in various parts of the world. The Pesse canoe, discovered in the Netherlands and dated to approximately 8040 BCE, is one of the oldest known boats in existence. While dugout canoes were effective for navigating rivers and sheltered coastal waters, their size was limited by the dimensions of available trees, and they lacked the structural strength and seaworthiness needed for open-ocean voyaging.

The ancient Egyptians were among the first civilisations to build planked boats — vessels constructed from shaped wooden planks joined together to form a hull. A remarkable example is the Khufu ship, a full-sized ceremonial vessel discovered in 1954 in a sealed pit at the base of the Great Pyramid of Giza, dating to approximately 2500 BCE. The Khufu ship measures 43.6 metres in length and was constructed without nails, using a technique in which planks were lashed together with ropes threaded through mortise-and-tenon joints — a method that allowed the hull to flex slightly in the water, absorbing wave stresses. Egyptian ships sailed the Nile for trade and transport and ventured into the Red Sea and the eastern Mediterranean.

The Phoenicians, Greeks, and Romans each made significant advances in shipbuilding technology. Phoenician merchants built wide-beamed sailing vessels capable of carrying large cargoes across the Mediterranean, while their warships — long, narrow galleys powered by banks of oars — gave them naval dominance for several centuries. Greek shipbuilders developed the trireme, a warship with three tiers of oars on each side, crewed by approximately 170 rowers, which could reach speeds of up to 14 kilometres per hour in short bursts. The Romans, though initially inferior sailors, developed innovative technologies including the corvus — a boarding bridge with a heavy spike that could be dropped onto an enemy ship to lock the two vessels together, allowing Roman soldiers to fight as if on land.

The Vikings of Scandinavia were among the most accomplished shipbuilders of the medieval period. Their longships, built using the clinker technique (in which overlapping planks were riveted together from the keel upward), were light, flexible, and capable of navigating both open oceans and shallow rivers. A typical longship measured 20 to 30 metres in length and could carry 60 to 80 warriors. The shallow draught of Viking ships — as little as 50 centimetres — enabled them to land directly on beaches and navigate far upriver, giving Viking raiders and traders extraordinary mobility. The Oseberg ship, discovered in a Norwegian burial mound in 1904 and dated to approximately 820 CE, is one of the finest surviving examples of Viking shipbuilding craftsmanship.

Chinese shipbuilding reached extraordinary levels of sophistication during the Song (960–1279 CE) and Ming (1368–1644 CE) dynasties. Chinese shipbuilders were the first to develop watertight compartments — sealed sections within the hull that prevented the entire vessel from flooding if one section was breached — a safety innovation not adopted in European ships until the eighteenth century. The treasure ships of Admiral Zheng He, which sailed on seven voyages across the Indian Ocean between 1405 and 1433, were reportedly among the largest wooden vessels ever constructed, with some accounts describing ships over 120 metres long carrying crews of several hundred. While these dimensions are debated by historians, the scale and ambition of Zheng He's expeditions are beyond doubt.

The transition from wooden sailing ships to iron and steel steamships in the nineteenth century marked the most fundamental transformation in shipbuilding history. The SS Great Britain, designed by Isambard Kingdom Brunel and launched in 1843, was the first ocean-going vessel to combine an iron hull with screw propulsion, establishing the template for modern ship design. By the early twentieth century, steel-hulled steamships had grown to enormous proportions: the RMS Titanic, launched in 1912, displaced over 52,000 tonnes and could carry over 2,200 passengers and crew. Today, the largest container ships exceed 400 metres in length and can carry over 24,000 twenty-foot equivalent units (TEUs), while the largest cruise ships accommodate over 6,000 passengers — a scale of maritime engineering that the ancient shipbuilders could scarcely have imagined.`,
      questions: [
        { number: 1, type: "true_false_not_given", text: "The Pesse canoe is the oldest boat ever discovered.", correctAnswer: "NOT GIVEN", explanation: "The passage says it is 'one of the oldest known boats' but does not confirm it is the oldest." },
        { number: 2, type: "true_false_not_given", text: "Dugout canoes were suitable for open-ocean voyages.", correctAnswer: "FALSE", explanation: "The passage says they 'lacked the structural strength and seaworthiness needed for open-ocean voyaging.'" },
        { number: 3, type: "true_false_not_given", text: "The Khufu ship was built using metal nails.", correctAnswer: "FALSE", explanation: "The passage states it 'was constructed without nails.'" },
        { number: 4, type: "true_false_not_given", text: "The Khufu ship measures more than 40 metres in length.", correctAnswer: "TRUE", explanation: "The passage says it 'measures 43.6 metres in length.'" },
        { number: 5, type: "true_false_not_given", text: "Greek triremes were faster than Phoenician warships.", correctAnswer: "NOT GIVEN", explanation: "The passage gives trireme speed but does not compare it to Phoenician warship speeds." },
        { number: 6, type: "true_false_not_given", text: "Viking longships could navigate shallow rivers.", correctAnswer: "TRUE", explanation: "The passage says they were 'capable of navigating both open oceans and shallow rivers.'" },
        { number: 7, type: "true_false_not_given", text: "Watertight compartments were used in European ships before Chinese ships.", correctAnswer: "FALSE", explanation: "The passage says Chinese builders were 'the first' and Europeans didn't adopt this until the eighteenth century." },
        { number: 8, type: "sentence_completion", text: "The Pesse canoe dates to approximately _______ BCE.", correctAnswer: "8040", explanation: "The passage says 'dated to approximately 8040 BCE.'" },
        { number: 9, type: "sentence_completion", text: "The Khufu ship was discovered in _______ at the base of the Great Pyramid.", correctAnswer: "1954", explanation: "The passage states 'discovered in 1954.'" },
        { number: 10, type: "sentence_completion", text: "A Greek trireme was crewed by approximately _______ rowers.", correctAnswer: "170", explanation: "The passage says 'crewed by approximately 170 rowers.'" },
        { number: 11, type: "sentence_completion", text: "The Roman corvus was a boarding _______ with a heavy spike.", correctAnswer: "bridge", explanation: "The passage describes the corvus as 'a boarding bridge with a heavy spike.'" },
        { number: 12, type: "sentence_completion", text: "The Oseberg ship dates to approximately _______ CE.", correctAnswer: "820", explanation: "The passage says 'dated to approximately 820 CE.'" },
        { number: 13, type: "sentence_completion", text: "The SS Great Britain was designed by _______ and launched in 1843.", correctAnswer: "Isambard Kingdom Brunel", explanation: "The passage names 'Isambard Kingdom Brunel.'" },
      ],
    },
    {
      title: "Environmental Sustainability",
      text: `A. Environmental sustainability — the practice of meeting present needs without compromising the ability of future generations to meet their own needs — has become one of the defining concerns of the twenty-first century. As the global population surpasses eight billion and economic activity continues to expand, the strain on natural resources, ecosystems, and planetary systems has reached levels that many scientists describe as critical. The concept of sustainability, which integrates environmental protection with social equity and economic development, offers a framework for addressing these challenges in a holistic and balanced manner.

B. Climate change is widely regarded as the most urgent sustainability challenge facing humanity. The Intergovernmental Panel on Climate Change (IPCC) has stated that human activities — primarily the burning of fossil fuels, deforestation, and industrial processes — have caused the Earth's average surface temperature to rise by approximately 1.1 degrees Celsius above pre-industrial levels. The consequences include more frequent and severe heatwaves, droughts, floods, and storms; rising sea levels that threaten coastal communities; disruption of agricultural systems; and accelerating biodiversity loss. The Paris Agreement of 2015, signed by 196 countries, established the goal of limiting global warming to well below 2 degrees Celsius, with efforts to limit the increase to 1.5 degrees, but current national commitments remain insufficient to achieve this target.

C. The concept of the circular economy has gained significant traction as an alternative to the traditional linear model of "take, make, dispose." In a circular economy, products and materials are designed for durability, reuse, repair, remanufacturing, and recycling, minimising waste and keeping resources in productive use for as long as possible. The Ellen MacArthur Foundation estimates that transitioning to a circular economy could reduce global greenhouse gas emissions by 45 percent and generate $4.5 trillion in economic benefits by 2030. Examples of circular economy practices include product-as-a-service models (in which consumers pay for the use of a product rather than owning it), industrial symbiosis (in which the waste from one manufacturing process becomes the raw material for another), and the development of biodegradable and compostable materials as alternatives to conventional plastics.

D. Renewable energy deployment is central to the sustainability transition. Solar and wind energy are now the cheapest sources of new electricity generation in most parts of the world, and their combined share of global electricity production exceeded 12 percent in 2022. The International Renewable Energy Agency (IRENA) estimates that renewable sources could supply 90 percent of global electricity by 2050 if current investment and policy trends continue. Energy storage technologies — particularly lithium-ion batteries and emerging alternatives such as solid-state batteries and green hydrogen — are critical for managing the intermittent nature of solar and wind power and ensuring grid stability. The electrification of transport, heating, and industrial processes, powered by renewable energy, offers a pathway to deep decarbonisation of the global economy.

E. Biodiversity conservation is an integral component of environmental sustainability. The loss of species and degradation of ecosystems undermine the natural systems that provide essential services including pollination, water purification, carbon sequestration, flood regulation, and disease control. The Kunming-Montreal Global Biodiversity Framework, adopted in December 2022, committed signatory nations to protecting 30 percent of the world's land and ocean areas by 2030 and to halting and reversing biodiversity loss. Nature-based solutions — such as reforestation, wetland restoration, and sustainable land management — offer approaches that simultaneously address climate change, biodiversity loss, and human well-being. However, achieving these targets will require unprecedented levels of financing, with current biodiversity spending estimated at approximately $124 billion per year against an estimated need of $700 billion to $1 trillion.

F. Individual and collective behavioural change is increasingly recognised as essential for achieving sustainability. While technological innovation and policy reform are necessary, they are insufficient without changes in consumption patterns, dietary habits, travel behaviour, and waste practices. The food system alone accounts for approximately one-third of global greenhouse gas emissions, with livestock production — particularly beef and dairy — contributing disproportionately. Reducing food waste, shifting towards more plant-based diets, choosing sustainable transport options, and adopting energy-efficient practices in homes and workplaces are actions that individuals can take to reduce their environmental footprint. Ultimately, achieving environmental sustainability will require a fundamental transformation in the values, institutions, and economic systems that govern human interaction with the natural world.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Paragraph B", options: ["i. Rethinking waste through circular models", "ii. The role of clean energy in sustainability", "iii. The urgency of global warming", "iv. Protecting species and natural habitats", "v. The meaning and scope of sustainability", "vi. How personal choices affect the environment", "vii. International trade and sustainability", "viii. Water conservation strategies"], correctAnswer: "iii", explanation: "Paragraph B focuses on climate change, the 1.1°C rise, and the Paris Agreement." },
        { number: 15, type: "matching_headings", text: "Paragraph C", options: ["i. Rethinking waste through circular models", "ii. The role of clean energy in sustainability", "iii. The urgency of global warming", "iv. Protecting species and natural habitats", "v. The meaning and scope of sustainability", "vi. How personal choices affect the environment", "vii. International trade and sustainability", "viii. Water conservation strategies"], correctAnswer: "i", explanation: "Paragraph C describes the circular economy model — designing for reuse and recycling." },
        { number: 16, type: "matching_headings", text: "Paragraph D", options: ["i. Rethinking waste through circular models", "ii. The role of clean energy in sustainability", "iii. The urgency of global warming", "iv. Protecting species and natural habitats", "v. The meaning and scope of sustainability", "vi. How personal choices affect the environment", "vii. International trade and sustainability", "viii. Water conservation strategies"], correctAnswer: "ii", explanation: "Paragraph D discusses solar, wind, batteries, and electrification — clean energy." },
        { number: 17, type: "matching_headings", text: "Paragraph E", options: ["i. Rethinking waste through circular models", "ii. The role of clean energy in sustainability", "iii. The urgency of global warming", "iv. Protecting species and natural habitats", "v. The meaning and scope of sustainability", "vi. How personal choices affect the environment", "vii. International trade and sustainability", "viii. Water conservation strategies"], correctAnswer: "iv", explanation: "Paragraph E discusses biodiversity conservation, the 30x30 target, and nature-based solutions." },
        { number: 18, type: "matching_headings", text: "Paragraph F", options: ["i. Rethinking waste through circular models", "ii. The role of clean energy in sustainability", "iii. The urgency of global warming", "iv. Protecting species and natural habitats", "v. The meaning and scope of sustainability", "vi. How personal choices affect the environment", "vii. International trade and sustainability", "viii. Water conservation strategies"], correctAnswer: "vi", explanation: "Paragraph F discusses individual behaviour change, diet, and consumption patterns." },
        { number: 19, type: "summary_completion", text: "The Earth's temperature has risen by approximately _______ degrees above pre-industrial levels.", correctAnswer: "1.1", explanation: "The passage says 'approximately 1.1 degrees Celsius.'" },
        { number: 20, type: "summary_completion", text: "The Paris Agreement was signed by _______ countries.", correctAnswer: "196", explanation: "The passage states 'signed by 196 countries.'" },
        { number: 21, type: "summary_completion", text: "A circular economy could reduce greenhouse gas emissions by _______ percent.", correctAnswer: "45", explanation: "The passage says 'reduce global greenhouse gas emissions by 45 percent.'" },
        { number: 22, type: "summary_completion", text: "Solar and wind exceeded _______ percent of global electricity in 2022.", correctAnswer: "12", explanation: "The passage states 'exceeded 12 percent in 2022.'" },
        { number: 23, type: "summary_completion", text: "IRENA estimates renewables could supply _______ percent of electricity by 2050.", correctAnswer: "90", explanation: "The passage says 'could supply 90 percent.'" },
        { number: 24, type: "summary_completion", text: "The food system accounts for approximately one-_______ of global emissions.", correctAnswer: "third", explanation: "The passage says 'approximately one-third.'" },
        { number: 25, type: "summary_completion", text: "Current biodiversity spending is approximately $_______ billion per year.", correctAnswer: "124", explanation: "The passage states 'approximately $124 billion per year.'" },
        { number: 26, type: "summary_completion", text: "The circular economy could generate $_______ trillion in economic benefits by 2030.", correctAnswer: "4.5", explanation: "The passage says '$4.5 trillion in economic benefits.'" },
      ],
    },
    {
      title: "Future Communication Technologies",
      text: `Communication technology has undergone a series of revolutionary transformations over the past two centuries, from the telegraph and telephone to radio, television, the internet, and mobile communications. Each generation of technology has expanded the speed, reach, and richness of human communication, reshaping society, culture, and commerce in the process. As we look ahead, several emerging technologies promise to transform communication once again, creating possibilities that were once the exclusive domain of science fiction.

A. Fifth-generation (5G) mobile networks, which began commercial deployment in 2019, represent a significant leap beyond their 4G predecessors. 5G offers theoretical peak download speeds of up to 20 gigabits per second — approximately 100 times faster than 4G — along with dramatically reduced latency (the delay between sending and receiving data) of as little as one millisecond. These capabilities enable applications that were impractical on earlier networks, including real-time remote surgery, autonomous vehicle communication, immersive augmented and virtual reality experiences, and massive IoT deployments connecting billions of sensors and devices. By 2023, 5G networks had been launched in over 90 countries, and the number of 5G subscriptions had surpassed 1.5 billion. Research into sixth-generation (6G) technology, which could offer speeds 50 times faster than 5G, is already under way, with commercial deployment expected around 2030.

B. Satellite-based internet services are closing the connectivity gap for billions of people in remote, rural, and underserved regions where terrestrial broadband infrastructure is economically impractical. SpaceX's Starlink, the most advanced satellite internet constellation, comprises over 5,000 low-Earth orbit (LEO) satellites and provides broadband service to users in over 60 countries. Competing systems from Amazon (Project Kuiper) and OneWeb are at various stages of deployment. LEO satellite constellations orbit at altitudes of 350 to 1,200 kilometres — far closer to Earth than traditional geostationary satellites at 36,000 kilometres — enabling lower latency and higher bandwidth. However, the proliferation of satellite constellations has raised concerns among astronomers about light pollution and interference with ground-based telescope observations.

C. Quantum communication, based on the principles of quantum mechanics, promises to deliver communications that are theoretically unhackable. Quantum key distribution (QKD) uses the quantum properties of photons — particles of light — to create encryption keys that cannot be intercepted or copied without detection. Any attempt to eavesdrop on a quantum communication channel alters the quantum states of the photons, alerting the communicating parties to the intrusion. China has been at the forefront of quantum communication research, launching the Micius satellite in 2016 to demonstrate satellite-based QKD over distances exceeding 1,200 kilometres, and establishing a 2,000-kilometre quantum communication backbone network between Beijing and Shanghai. While practical, large-scale quantum communication networks remain years away, the technology has attracted significant government and military interest due to its potential to provide absolute security for sensitive communications.

D. Holographic communication — the ability to project realistic, three-dimensional images of people in real time — is moving from the realm of science fiction towards practical reality. Advances in display technology, spatial computing, and high-bandwidth connectivity are enabling the development of systems that can capture, transmit, and display volumetric video — three-dimensional representations of people and objects that can be viewed from any angle. Microsoft's Mesh platform and similar systems from companies such as Proto and ARHT Media are already enabling rudimentary holographic meetings and presentations. Fully immersive holographic telepresence, in which participants can see, hear, and potentially interact with life-sized 3D representations of remote individuals as if they were physically present, is expected to become commercially viable within the next decade, driven by advances in 5G/6G connectivity, AI-powered real-time rendering, and lightweight augmented reality headsets.

E. Brain-computer interfaces (BCIs), which establish direct communication pathways between the brain and external devices, represent perhaps the most radical frontier of communication technology. Current BCIs, such as those developed by Neuralink and BrainGate, use implanted electrode arrays or non-invasive sensors to detect neural signals, enabling paralysed patients to control computer cursors, robotic limbs, and communication software using thought alone. In 2023, a BCI developed by Stanford University enabled a paralysed patient to communicate at a rate of 62 words per minute — approaching the speed of natural conversation. While current BCI technology is primarily therapeutic, researchers envision a future in which BCIs could enable direct brain-to-brain communication, the instant transfer of knowledge or memories, and seamless interaction with digital environments — possibilities that raise profound ethical, philosophical, and social questions about identity, privacy, autonomy, and what it means to be human.

F. The convergence of these emerging technologies — ultra-fast networks, satellite connectivity, quantum security, holographic presence, and brain-computer interfaces — suggests that the future of communication will be characterised by unprecedented immediacy, immersion, and intimacy. The barriers of distance, language, and physical presence that have constrained human communication since the dawn of civilisation are being progressively dismantled by technology. However, as communication becomes more powerful and pervasive, ensuring that it remains equitable, secure, and aligned with human values will be one of the great challenges of the coming era.`,
      questions: [
        { number: 27, type: "matching_information", text: "A satellite used to demonstrate quantum encryption over long distances", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "C", explanation: "Paragraph C describes 'the Micius satellite' demonstrating QKD 'over distances exceeding 1,200 kilometres.'" },
        { number: 28, type: "matching_information", text: "Technology enabling a paralysed patient to communicate through thought", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "E", explanation: "Paragraph E describes BCIs enabling 'a paralysed patient to communicate at a rate of 62 words per minute.'" },
        { number: 29, type: "matching_information", text: "Concerns about satellites interfering with astronomical observations", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "B", explanation: "Paragraph B mentions concerns about 'light pollution and interference with ground-based telescope observations.'" },
        { number: 30, type: "matching_information", text: "Systems that project three-dimensional images of people for meetings", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "D", explanation: "Paragraph D describes holographic communication and platforms enabling 'holographic meetings.'" },
        { number: 31, type: "matching_information", text: "The expected commercial launch date of 6G networks", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "A", explanation: "Paragraph A states 6G 'commercial deployment expected around 2030.'" },
        { number: 32, type: "multiple_choice", text: "5G networks offer peak download speeds approximately", options: ["A 10 times faster than 4G.", "B 50 times faster than 4G.", "C 100 times faster than 4G.", "D 1,000 times faster than 4G."], correctAnswer: "C", explanation: "The passage says 'approximately 100 times faster than 4G.'" },
        { number: 33, type: "multiple_choice", text: "Starlink satellites orbit at altitudes of", options: ["A 100 to 350 kilometres.", "B 350 to 1,200 kilometres.", "C 1,200 to 5,000 kilometres.", "D 36,000 kilometres."], correctAnswer: "B", explanation: "The passage states 'altitudes of 350 to 1,200 kilometres.'" },
        { number: 34, type: "multiple_choice", text: "Quantum key distribution is significant because it", options: ["A transmits data faster than light.", "B provides theoretically unbreakable encryption.", "C eliminates the need for satellites.", "D works without electricity."], correctAnswer: "B", explanation: "The passage says quantum communication promises 'communications that are theoretically unhackable.'" },
        { number: 35, type: "multiple_choice", text: "The Stanford BCI enabled communication at", options: ["A 15 words per minute.", "B 32 words per minute.", "C 62 words per minute.", "D 120 words per minute."], correctAnswer: "C", explanation: "The passage says 'at a rate of 62 words per minute.'" },
        { number: 36, type: "multiple_choice", text: "5G networks had been launched in over how many countries by 2023?", options: ["A 30.", "B 60.", "C 90.", "D 150."], correctAnswer: "C", explanation: "The passage says 'launched in over 90 countries.'" },
        { number: 37, type: "multiple_choice", text: "The number of 5G subscriptions by 2023 had surpassed", options: ["A 500 million.", "B 1 billion.", "C 1.5 billion.", "D 3 billion."], correctAnswer: "C", explanation: "The passage states 'surpassed 1.5 billion.'" },
        { number: 38, type: "multiple_choice", text: "The China-built quantum network connects Beijing and", options: ["A Guangzhou.", "B Hong Kong.", "C Shanghai.", "D Shenzhen."], correctAnswer: "C", explanation: "The passage says 'between Beijing and Shanghai.'" },
        { number: 39, type: "multiple_choice", text: "6G is expected to be approximately how many times faster than 5G?", options: ["A 5 times.", "B 10 times.", "C 50 times.", "D 100 times."], correctAnswer: "C", explanation: "The passage says '6G technology, which could offer speeds 50 times faster than 5G.'" },
        { number: 40, type: "multiple_choice", text: "The minimum latency offered by 5G is", options: ["A 10 milliseconds.", "B 5 milliseconds.", "C 1 millisecond.", "D 0.1 milliseconds."], correctAnswer: "C", explanation: "The passage says 'latency of as little as one millisecond.'" },
      ],
    },
  ],
};
