import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_40: ReadingTest = {
  id: 40,
  passages: [
    {
      title: "History of Music Instruments",
      text: `The history of musical instruments is inseparable from the history of human culture itself. Archaeological discoveries suggest that humans have been making music for at least 40,000 years. The oldest known instruments are bone flutes found in caves in southern Germany, carved from the wing bones of vultures and the ivory of mammoths. These delicate artefacts, dating to the Upper Palaeolithic period, produce a range of notes that indicate a surprisingly sophisticated understanding of pitch and scale.

Percussion instruments are likely even older than flutes, although their perishable materials — wood, animal skins, gourds — rarely survive in the archaeological record. In many cultures, drums served not only musical but also ceremonial and communicative functions: West African talking drums, for instance, could reproduce the tonal patterns of spoken language, transmitting messages across distances of several kilometres. The frame drum, one of the most ancient and widespread percussion instruments, appears in Mesopotamian art as early as 3000 BCE and remains central to musical traditions from the Middle East to Central Asia.

Stringed instruments emerged independently in several ancient civilisations. The lyre, closely associated with ancient Greece, evolved from simpler harps developed in Mesopotamia and Egypt. The oldest surviving lyres, excavated from the Royal Cemetery of Ur in modern-day Iraq, date to approximately 2500 BCE and feature elaborate decorations of gold, lapis lazuli, and shell. In India, the veena — a plucked or bowed string instrument — has been played for more than two thousand years and is considered sacred in Hindu tradition. The development of the bow, which allows a string to vibrate continuously rather than being plucked, was a pivotal innovation: it gave rise to the rebab in the Islamic world, the erhu in China, and eventually the violin family in Renaissance Italy.

The keyboard family began with the organ, which dates back to the hydraulis, a water-powered instrument invented in the third century BCE by Ctesibius of Alexandria. Pipe organs grew in size and complexity throughout the Middle Ages, becoming fixtures of European cathedrals. The clavichord and harpsichord, both developed in the fourteenth and fifteenth centuries, offered portable alternatives. The pianoforte, invented by Bartolomeo Cristofori in Florence around 1700, represented a breakthrough: unlike the harpsichord, which plucked strings, the piano struck them with felt-covered hammers, allowing the player to control volume by varying the force of the keystroke. This dynamic capability — the ability to play both piano (soft) and forte (loud) — gave the instrument its name and made it the dominant keyboard instrument for the next three centuries.

The nineteenth century saw the invention of many instruments that remain central to Western music. Adolphe Sax patented the saxophone in 1846, creating a hybrid that combined the projection of a brass instrument with the agility of a woodwind. The modern concert flute, redesigned by Theobald Boehm in the 1840s, replaced the earlier wooden instrument with a metal tube and a system of keys that improved intonation and facilitated virtuosic playing. Brass instruments such as the trumpet and French horn were fitted with valves, extending their range and allowing them to play in any key.

The twentieth century brought electronic instruments that fundamentally altered the sonic palette. The theremin, invented by Léon Theremin in 1920, was one of the first instruments to generate sound electrically, producing ethereal tones that the player controlled by moving their hands near two antennae. Robert Moog's synthesiser, introduced commercially in the 1960s, could replicate the sounds of traditional instruments and create entirely new timbres using electronic oscillators and filters. Digital sampling technology, developed in the 1970s and 1980s, allowed musicians to record and manipulate any sound, blurring the boundary between instrument and recording studio.

Today, software instruments running on laptops and tablets enable musicians to compose, perform, and produce music with tools that would have filled an entire studio a generation ago. Yet acoustic instruments continue to thrive: orchestras, jazz ensembles, and folk musicians worldwide demonstrate that the human desire to create sound through physical interaction with wood, metal, and skin is as powerful as ever.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "What are the oldest known musical instruments?", options: ["A Drums made from animal skins", "B Bone flutes from southern Germany", "C Lyres from ancient Greece", "D Clay whistles from China"], correctAnswer: "B", explanation: "The passage says 'The oldest known instruments are bone flutes found in caves in southern Germany.'" },
        { number: 2, type: "multiple_choice", text: "What function could West African talking drums perform?", options: ["A Measuring time accurately", "B Reproducing tonal patterns of language", "C Accompanying religious rituals only", "D Producing written musical notation"], correctAnswer: "B", explanation: "The passage says talking drums 'could reproduce the tonal patterns of spoken language.'" },
        { number: 3, type: "multiple_choice", text: "What was the key innovation of Cristofori's pianoforte?", options: ["A It used plucked strings", "B It was powered by water", "C It struck strings with hammers allowing volume control", "D It used electronic oscillators"], correctAnswer: "C", explanation: "The passage says the piano 'struck them with felt-covered hammers, allowing the player to control volume.'" },
        { number: 4, type: "multiple_choice", text: "Who invented the theremin?", options: ["A Adolphe Sax", "B Robert Moog", "C Theobald Boehm", "D Léon Theremin"], correctAnswer: "D", explanation: "The passage says 'The theremin, invented by Léon Theremin in 1920.'" },
        { number: 5, type: "sentence_completion", text: "The oldest bone flutes date to the __(5)__ Palaeolithic period.", correctAnswer: "Upper", explanation: "The passage says 'dating to the Upper Palaeolithic period.'" },
        { number: 6, type: "sentence_completion", text: "The frame drum appears in Mesopotamian art as early as __(6)__ BCE.", correctAnswer: "3000", explanation: "The passage says 'as early as 3000 BCE.'" },
        { number: 7, type: "sentence_completion", text: "The oldest surviving lyres were excavated from the Royal Cemetery of __(7)__.", correctAnswer: "Ur", explanation: "The passage says 'excavated from the Royal Cemetery of Ur.'" },
        { number: 8, type: "sentence_completion", text: "The hydraulis was a __(8)__-powered instrument invented by Ctesibius.", correctAnswer: "water", explanation: "The passage says 'a water-powered instrument.'" },
        { number: 9, type: "sentence_completion", text: "The pianoforte was invented around __(9)__ in Florence.", correctAnswer: "1700", explanation: "The passage says 'around 1700.'" },
        { number: 10, type: "sentence_completion", text: "Adolphe Sax patented the saxophone in __(10)__.", correctAnswer: "1846", explanation: "The passage says 'patented the saxophone in 1846.'" },
        { number: 11, type: "sentence_completion", text: "Robert Moog's synthesiser used electronic oscillators and __(11)__.", correctAnswer: "filters", explanation: "The passage says 'using electronic oscillators and filters.'" },
        { number: 12, type: "sentence_completion", text: "Digital __(12)__ technology allowed musicians to record and manipulate any sound.", correctAnswer: "sampling", explanation: "The passage says 'Digital sampling technology.'" },
        { number: 13, type: "sentence_completion", text: "The development of the __(13)__ allowed strings to vibrate continuously rather than being plucked.", correctAnswer: "bow", explanation: "The passage says 'The development of the bow, which allows a string to vibrate continuously.'" },
      ],
    },
    {
      title: "Plastic Pollution",
      text: `A. Plastic has become one of the defining materials of the modern age. Since large-scale production began in the 1950s, approximately 8.3 billion tonnes of plastic have been manufactured worldwide, and annual production continues to rise, reaching roughly 400 million tonnes in 2022. Plastic's durability, versatility, and low cost have made it indispensable in packaging, construction, electronics, medicine, and transportation. Yet the same qualities that make plastic so useful — particularly its resistance to degradation — have turned it into one of the most pervasive and persistent pollutants on Earth.

B. The scale of plastic pollution is staggering. Of all the plastic ever produced, only about nine per cent has been recycled. Roughly twelve per cent has been incinerated, and the remaining seventy-nine per cent has accumulated in landfills or the natural environment. An estimated eight million tonnes of plastic waste enter the oceans every year, carried by rivers, blown from coastlines, or dumped directly from ships. Once in the ocean, plastic debris circulates on currents, forming vast accumulations such as the Great Pacific Garbage Patch, which covers an area estimated at 1.6 million square kilometres — more than twice the size of Texas.

C. Microplastics — fragments smaller than five millimetres — pose a particularly insidious threat. They originate from the breakdown of larger plastic items, from the washing of synthetic textiles, and from industrial processes such as the manufacture of plastic pellets. Microplastics have been detected in every environment sampled, from Arctic sea ice to deep-ocean sediments, from mountain soils to human blood. A 2022 study published in Environment International confirmed the presence of microplastic particles in human blood for the first time, raising urgent questions about potential health effects.

D. Marine wildlife is heavily affected. More than 700 marine species have been documented ingesting plastic or becoming entangled in it. Sea turtles mistake floating plastic bags for jellyfish, their primary food source. Seabirds ingest bottle caps, lighters, and fragments of fishing gear, which accumulate in their stomachs and can cause starvation. Whales have been found dead with dozens of kilogrammes of plastic in their digestive systems. Beyond direct physical harm, chemicals leaching from plastics — including phthalates, bisphenol A, and flame retardants — can disrupt endocrine systems and impair reproduction in marine organisms.

E. Several strategies are being pursued to address plastic pollution. Extended producer responsibility (EPR) schemes require manufacturers to finance the collection and recycling of the packaging they produce, creating a financial incentive to reduce plastic use and design products for recyclability. Over sixty countries have enacted bans or taxes on single-use plastic bags, and the European Union's Single-Use Plastics Directive, implemented in 2021, prohibits items such as plastic straws, cutlery, and stirrers.

F. Advances in recycling technology offer further hope. Chemical recycling, also known as advanced recycling, breaks plastic polymers down into their chemical building blocks, which can then be reassembled into new plastic of virgin quality. Unlike mechanical recycling, which degrades plastic quality with each cycle, chemical recycling can theoretically be repeated indefinitely. Several pilot plants are operating in Europe, Asia, and North America, though scaling the technology to commercial levels remains challenging and energy-intensive.

G. Biodegradable and compostable plastics represent an alternative approach. Made from plant-based feedstocks such as corn starch, sugarcane, or cellulose, these materials are designed to decompose in industrial composting facilities within weeks or months. However, critics note that biodegradable plastics do not break down readily in marine environments or conventional landfills, and that their production can compete with food crops for agricultural land. A comprehensive solution to plastic pollution will likely require a combination of reduced consumption, improved waste management, technological innovation, and international cooperation.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Section A", options: ["I. Legislative responses to plastic waste", "II. The ubiquity of plastic and its environmental cost", "III. The global scale of plastic waste", "IV. Tiny particles with large consequences", "V. New recycling methods", "VI. Impact on marine life", "VII. Plant-based alternatives to conventional plastic"], correctAnswer: "II", explanation: "Section A introduces plastic's usefulness and its pollution problem." },
        { number: 15, type: "matching_headings", text: "Section B", options: ["I. Legislative responses to plastic waste", "II. The ubiquity of plastic and its environmental cost", "III. The global scale of plastic waste", "IV. Tiny particles with large consequences", "V. New recycling methods", "VI. Impact on marine life", "VII. Plant-based alternatives to conventional plastic"], correctAnswer: "III", explanation: "Section B presents statistics on the scale of plastic pollution." },
        { number: 16, type: "matching_headings", text: "Section C", options: ["I. Legislative responses to plastic waste", "II. The ubiquity of plastic and its environmental cost", "III. The global scale of plastic waste", "IV. Tiny particles with large consequences", "V. New recycling methods", "VI. Impact on marine life", "VII. Plant-based alternatives to conventional plastic"], correctAnswer: "IV", explanation: "Section C discusses microplastics." },
        { number: 17, type: "matching_headings", text: "Section D", options: ["I. Legislative responses to plastic waste", "II. The ubiquity of plastic and its environmental cost", "III. The global scale of plastic waste", "IV. Tiny particles with large consequences", "V. New recycling methods", "VI. Impact on marine life", "VII. Plant-based alternatives to conventional plastic"], correctAnswer: "VI", explanation: "Section D discusses the impact on marine wildlife." },
        { number: 18, type: "matching_headings", text: "Section E", options: ["I. Legislative responses to plastic waste", "II. The ubiquity of plastic and its environmental cost", "III. The global scale of plastic waste", "IV. Tiny particles with large consequences", "V. New recycling methods", "VI. Impact on marine life", "VII. Plant-based alternatives to conventional plastic"], correctAnswer: "I", explanation: "Section E discusses EPR schemes and bans on single-use plastics." },
        { number: 19, type: "matching_headings", text: "Section F", options: ["I. Legislative responses to plastic waste", "II. The ubiquity of plastic and its environmental cost", "III. The global scale of plastic waste", "IV. Tiny particles with large consequences", "V. New recycling methods", "VI. Impact on marine life", "VII. Plant-based alternatives to conventional plastic"], correctAnswer: "V", explanation: "Section F discusses chemical recycling technology." },
        { number: 20, type: "summary_completion", text: "Approximately __(20)__ billion tonnes of plastic have been manufactured worldwide.", correctAnswer: "8.3", explanation: "The passage says 'approximately 8.3 billion tonnes.'" },
        { number: 21, type: "summary_completion", text: "Only about __(21)__ per cent of all plastic produced has been recycled.", correctAnswer: "nine", explanation: "The passage says 'only about nine per cent has been recycled.'" },
        { number: 22, type: "summary_completion", text: "The Great Pacific Garbage Patch covers approximately __(22)__ million square kilometres.", correctAnswer: "1.6", explanation: "The passage says '1.6 million square kilometres.'" },
        { number: 23, type: "summary_completion", text: "More than __(23)__ marine species have been documented ingesting or becoming entangled in plastic.", correctAnswer: "700", explanation: "The passage says 'More than 700 marine species.'" },
        { number: 24, type: "summary_completion", text: "Chemical recycling breaks plastic polymers into their chemical __(24)__ blocks.", correctAnswer: "building", explanation: "The passage says 'breaks plastic polymers down into their chemical building blocks.'" },
        { number: 25, type: "summary_completion", text: "Biodegradable plastics are made from plant-based __(25)__ such as corn starch.", correctAnswer: "feedstocks", explanation: "The passage says 'Made from plant-based feedstocks.'" },
        { number: 26, type: "summary_completion", text: "Over __(26)__ countries have enacted bans or taxes on single-use plastic bags.", correctAnswer: "sixty", explanation: "The passage says 'Over sixty countries.'" },
      ],
    },
    {
      title: "Nanotechnology in Medicine",
      text: `Nanotechnology — the manipulation of matter at the scale of atoms and molecules, typically between one and one hundred nanometres — is rapidly emerging as one of the most transformative forces in modern medicine. A nanometre is one billionth of a metre; to put this in perspective, a human hair is approximately 80,000 nanometres wide. At the nanoscale, materials can exhibit properties that differ dramatically from those of the same substance in bulk form: gold nanoparticles, for example, appear red rather than yellow, and carbon nanotubes are stronger than steel yet lighter than aluminium.

A. The most advanced medical application of nanotechnology to date is in drug delivery. Conventional chemotherapy drugs circulate throughout the body, killing cancer cells but also damaging healthy tissue, which causes the debilitating side effects — nausea, hair loss, immune suppression — that make treatment so difficult for patients. Nanoparticle-based drug-delivery systems aim to solve this problem by encapsulating drugs in nanoscale carriers that can be engineered to accumulate preferentially in tumour tissue. Liposomes — tiny spherical vesicles made of lipid bilayers — were among the first nanocarriers approved for clinical use: Doxil, a liposomal formulation of the chemotherapy drug doxorubicin, was approved by the US Food and Drug Administration in 1995 and has been shown to reduce cardiac toxicity compared with conventional doxorubicin.

B. More recent research has focused on targeted nanoparticles that recognise and bind to specific molecules on the surface of cancer cells. By attaching antibodies or peptides to the surface of a nanocarrier, scientists can direct the drug payload to tumour cells with remarkable precision, minimising collateral damage to surrounding tissues. Some experimental designs incorporate stimuli-responsive mechanisms: the nanocarrier releases its drug cargo only when triggered by conditions found in the tumour microenvironment, such as low pH, elevated temperature, or the presence of certain enzymes.

C. Nanotechnology is also revolutionising medical imaging. Quantum dots — semiconductor nanocrystals that emit bright, tuneable fluorescence — enable researchers to visualise biological processes at the cellular and subcellular level with unprecedented clarity. Iron oxide nanoparticles serve as contrast agents for magnetic resonance imaging (MRI), improving the detection of tumours and inflammatory lesions. Gold nanoparticles enhance the sensitivity of computed tomography (CT) scans. These nanoscale imaging agents are typically biocompatible and can be coated with targeting molecules that direct them to specific tissues, combining diagnostic and therapeutic functions in a single platform — an approach known as theranostics.

D. In regenerative medicine, nanomaterials are being used to create scaffolds that guide tissue repair and regeneration. Electrospun nanofibre meshes, for example, can mimic the extracellular matrix of natural tissue, providing a structural framework on which cells can attach, proliferate, and differentiate. Researchers have used nanofibre scaffolds to promote the healing of bone fractures, cartilage defects, and skin wounds, and early clinical trials suggest that these materials may accelerate recovery and reduce scarring.

E. Nanosensors offer the prospect of detecting diseases at their earliest stages, when treatment is most effective. Researchers have developed nanowire biosensors capable of detecting biomarkers — proteins, nucleic acids, or small molecules associated with disease — at concentrations as low as a few femtomoles per litre. Such extreme sensitivity could enable the diagnosis of cancers, infectious diseases, and neurodegenerative conditions long before symptoms appear. Point-of-care diagnostic devices incorporating nanosensors could bring laboratory-quality testing to remote clinics and resource-limited settings.

F. Despite its enormous promise, medical nanotechnology faces significant challenges. The long-term toxicity of many nanomaterials remains poorly understood: nanoparticles can cross biological barriers that larger particles cannot, including the blood-brain barrier, and their interactions with cells and organs over years or decades are largely unknown. Regulatory frameworks for nanomedicines are still evolving; the novel properties of nanomaterials do not always fit neatly into existing categories for drugs or medical devices. Manufacturing consistency is another concern: producing nanoparticles with uniform size, shape, and surface characteristics at commercial scale requires exacting quality control.

G. The field is advancing rapidly nonetheless. Global investment in nanomedicine exceeded $350 billion in 2022, and hundreds of clinical trials are under way for nanoparticle-based therapies, diagnostics, and vaccines. The mRNA COVID-19 vaccines developed by Pfizer-BioNTech and Moderna, which use lipid nanoparticles to deliver genetic instructions to cells, demonstrated the clinical potential of nanotechnology on a global scale. As manufacturing techniques improve and safety data accumulate, nanotechnology is poised to become a cornerstone of twenty-first-century medicine.`,
      questions: [
        { number: 27, type: "matching_information", text: "An example of an approved nanoparticle drug", options: ["A", "B", "C", "D", "E", "F", "G"], correctAnswer: "A", explanation: "Paragraph A mentions Doxil, approved by the FDA in 1995." },
        { number: 28, type: "matching_information", text: "Discussion of nanoparticles that release drugs only under specific conditions", options: ["A", "B", "C", "D", "E", "F", "G"], correctAnswer: "B", explanation: "Paragraph B describes stimuli-responsive nanocarriers." },
        { number: 29, type: "matching_information", text: "Use of nanomaterials to support tissue healing", options: ["A", "B", "C", "D", "E", "F", "G"], correctAnswer: "D", explanation: "Paragraph D discusses nanofibre scaffolds for tissue repair." },
        { number: 30, type: "matching_information", text: "Concerns about long-term safety of nanomaterials", options: ["A", "B", "C", "D", "E", "F", "G"], correctAnswer: "F", explanation: "Paragraph F discusses toxicity and safety challenges." },
        { number: 31, type: "matching_information", text: "Reference to COVID-19 vaccines as an example of nanotechnology", options: ["A", "B", "C", "D", "E", "F", "G"], correctAnswer: "G", explanation: "Paragraph G mentions mRNA COVID-19 vaccines using lipid nanoparticles." },
        { number: 32, type: "matching_information", text: "Detection of diseases before symptoms appear", options: ["A", "B", "C", "D", "E", "F", "G"], correctAnswer: "E", explanation: "Paragraph E discusses nanosensors detecting biomarkers before symptoms." },
        { number: 33, type: "flow_chart_completion", text: "Conventional chemotherapy drugs circulate throughout the __(33)__.", correctAnswer: "body", explanation: "The passage says drugs 'circulate throughout the body.'" },
        { number: 34, type: "flow_chart_completion", text: "Nanoparticle carriers are engineered to accumulate in __(34)__ tissue.", correctAnswer: "tumour", explanation: "The passage says 'accumulate preferentially in tumour tissue.'" },
        { number: 35, type: "flow_chart_completion", text: "Targeted nanoparticles use antibodies or __(35)__ to bind to cancer cells.", correctAnswer: "peptides", explanation: "The passage says 'attaching antibodies or peptides to the surface.'" },
        { number: 36, type: "flow_chart_completion", text: "The drug is released when triggered by conditions in the tumour __(36)__.", correctAnswer: "microenvironment", explanation: "The passage says 'triggered by conditions found in the tumour microenvironment.'" },
        { number: 37, type: "flow_chart_completion", text: "Quantum dots emit bright, tuneable __(37)__ for imaging.", correctAnswer: "fluorescence", explanation: "The passage says 'emit bright, tuneable fluorescence.'" },
        { number: 38, type: "flow_chart_completion", text: "Nanofibre meshes mimic the __(38)__ matrix of natural tissue.", correctAnswer: "extracellular", explanation: "The passage says 'mimic the extracellular matrix.'" },
        { number: 39, type: "flow_chart_completion", text: "Global investment in nanomedicine exceeded $__(39)__ billion in 2022.", correctAnswer: "350", explanation: "The passage says 'exceeded $350 billion in 2022.'" },
        { number: 40, type: "flow_chart_completion", text: "Nanoparticles can cross the blood-__(40)__ barrier.", correctAnswer: "brain", explanation: "The passage says 'including the blood-brain barrier.'" },
      ],
    },
  ],
};
