import { ReadingTest } from "./reading-tests-data";

export const READING_TEST_9: ReadingTest = {
  id: 9,
  passages: [
    {
      title: "History of Photography",
      text: `The invention of photography in the early nineteenth century transformed not only art and science but also the way human beings perceive and record the world around them. What began as a series of experiments by European chemists and inventors eventually gave rise to one of the most powerful and ubiquitous technologies in human history, one that continues to evolve in the digital age.

The story of photography begins with the camera obscura, a device known since antiquity. The camera obscura (Latin for "dark room") operates on a simple optical principle: light passing through a small hole in the wall of a darkened chamber projects an inverted image of the outside scene onto the opposite wall. Renaissance artists, including Leonardo da Vinci, used camera obscuras as drawing aids, but the device could not permanently capture the image it projected. The challenge of "fixing" an image produced by light would occupy scientists for over two centuries.

The first successful attempt to produce a permanent photographic image is generally attributed to the French inventor Joseph Nicéphore Niépce. In 1826 or 1827, Niépce placed a pewter plate coated with bitumen of Judea — a naturally occurring asphalt — inside a camera obscura aimed at the view from his workshop window. After an exposure time of approximately eight hours, the bitumen hardened where it was struck by light, while the unexposed areas could be washed away with a solvent, leaving a crude but recognisable image. Niépce called his process "heliography" (sun writing), and the resulting image, known as "View from the Window at Le Gras," is the earliest surviving photograph.

Niépce subsequently entered into a partnership with Louis-Jacques-Mandé Daguerre, a Parisian artist and showman. After Niépce's death in 1833, Daguerre continued to experiment and in 1839 announced his daguerreotype process to the French Academy of Sciences. The daguerreotype used a polished silver-coated copper plate that was sensitised with iodine vapour, exposed in a camera, and developed with mercury fumes. The result was a highly detailed, one-of-a-kind image with a mirror-like surface. The French government purchased the rights to the invention and made it freely available to the public, sparking immediate worldwide enthusiasm. Within months, daguerreotype studios had opened in cities across Europe and America.

Almost simultaneously, in England, William Henry Fox Talbot was developing a rival photographic process. Talbot's calotype (from the Greek kalos, meaning "beautiful") used paper coated with silver iodide to produce a negative image from which multiple positive prints could be made. Although calotype images lacked the fine detail of daguerreotypes, the ability to produce multiple copies from a single negative was a crucial advantage that would ultimately prove more influential. Talbot's negative-positive process became the foundation upon which virtually all subsequent photographic technology was built, until the advent of digital imaging.

The second half of the nineteenth century saw rapid improvements in photographic technology. The wet collodion process, introduced by Frederick Scott Archer in 1851, combined the detail of the daguerreotype with the reproducibility of the calotype, though it required photographers to prepare, expose, and develop their glass plate negatives on the spot, before the chemical coating dried — a considerable logistical challenge, especially for those working outdoors or in remote locations. George Eastman's introduction of flexible celluloid film and the Kodak camera in 1888 finally democratised photography, making it accessible to amateur enthusiasts with his famous marketing slogan: "You press the button, we do the rest."

The twentieth century brought colour photography, high-speed flash units, automatic exposure systems, and sophisticated lens technology. Photography became indispensable in fields as diverse as journalism, advertising, science, medicine, law enforcement, and space exploration. The Polaroid instant camera, introduced by Edwin Land in 1948, eliminated the need for external processing by producing a finished print within minutes.

The transition to digital photography, which began in earnest in the 1990s, represents the most fundamental transformation since Niépce's first heliograph. Digital cameras replace photographic film with electronic image sensors — charge-coupled devices (CCDs) or complementary metal-oxide-semiconductor (CMOS) sensors — that convert light into electrical signals, which are then processed and stored as digital files. The integration of high-quality cameras into smartphones has made photography more accessible than at any previous point in history. An estimated 1.4 trillion photographs are taken worldwide each year, a figure that would have been unimaginable to the pioneers of the medium.`,
      questions: [
        { number: 1, type: "multiple_choice", text: "The camera obscura was significant because it", options: ["A was the first device to permanently capture images.", "B demonstrated the optical principle that photography would later use.", "C was invented specifically for photographic purposes.", "D replaced traditional painting methods entirely."], correctAnswer: "B", explanation: "The camera obscura demonstrated the projection principle but 'could not permanently capture the image.'" },
        { number: 2, type: "multiple_choice", text: "Niépce's first photograph required an exposure time of approximately", options: ["A eight minutes.", "B eighty minutes.", "C eight hours.", "D eight days."], correctAnswer: "C", explanation: "The passage states 'an exposure time of approximately eight hours.'" },
        { number: 3, type: "multiple_choice", text: "The daguerreotype became widely popular because", options: ["A it was inexpensive to produce at home.", "B the French government made the process publicly available.", "C it could produce multiple copies from one image.", "D it was the first colour photographic process."], correctAnswer: "B", explanation: "The passage says 'The French government purchased the rights and made it freely available to the public.'" },
        { number: 4, type: "multiple_choice", text: "Talbot's calotype was historically more important than the daguerreotype because", options: ["A it produced sharper images.", "B it was cheaper to manufacture.", "C it allowed multiple prints from one negative.", "D it used glass plates instead of paper."], correctAnswer: "C", explanation: "The passage states the 'ability to produce multiple copies from a single negative was a crucial advantage.'" },
        { number: 5, type: "multiple_choice", text: "George Eastman's contribution to photography was primarily to", options: ["A invent the first digital camera.", "B develop colour film technology.", "C make photography accessible to ordinary people.", "D create the first photographic studio."], correctAnswer: "C", explanation: "Eastman's Kodak camera 'democratised photography, making it accessible to amateur enthusiasts.'" },
        { number: 6, type: "true_false_not_given", text: "Leonardo da Vinci invented the camera obscura.", correctAnswer: "FALSE", explanation: "The passage says the camera obscura was 'known since antiquity' and da Vinci merely 'used' it. He did not invent it." },
        { number: 7, type: "true_false_not_given", text: "Niépce's first photograph depicted a landscape.", correctAnswer: "NOT GIVEN", explanation: "The passage describes it as 'the view from his workshop window' but does not specify it as a landscape." },
        { number: 8, type: "true_false_not_given", text: "Daguerre was a scientist by profession.", correctAnswer: "FALSE", explanation: "The passage describes Daguerre as 'a Parisian artist and showman,' not a scientist." },
        { number: 9, type: "true_false_not_given", text: "The wet collodion process required glass plates to be processed before the coating dried.", correctAnswer: "TRUE", explanation: "The passage states photographers had to 'prepare, expose, and develop their glass plate negatives on the spot, before the chemical coating dried.'" },
        { number: 10, type: "true_false_not_given", text: "Kodak cameras were initially more popular in Europe than in America.", correctAnswer: "NOT GIVEN", explanation: "The passage does not compare the popularity of Kodak cameras between regions." },
        { number: 11, type: "true_false_not_given", text: "Edwin Land's Polaroid camera could produce a finished print in under five minutes.", correctAnswer: "TRUE", explanation: "The passage says it produced 'a finished print within minutes.'" },
        { number: 12, type: "true_false_not_given", text: "CMOS sensors are more expensive than CCDs.", correctAnswer: "NOT GIVEN", explanation: "The passage mentions both but does not compare their costs." },
        { number: 13, type: "true_false_not_given", text: "Over one trillion photographs are taken each year worldwide.", correctAnswer: "TRUE", explanation: "The passage states 'An estimated 1.4 trillion photographs are taken worldwide each year.'" },
      ],
    },
    {
      title: "Wildlife Conservation Programs",
      text: `A. Wildlife conservation has become one of the most urgent environmental priorities of the twenty-first century. The scale of biodiversity loss is alarming: according to the International Union for Conservation of Nature (IUCN), more than 42,000 species are currently threatened with extinction, including approximately 41 percent of amphibians, 37 percent of sharks and rays, 26 percent of mammals, and 13 percent of birds. The primary drivers of this crisis include habitat destruction, overexploitation, climate change, pollution, and the introduction of invasive species. In response, governments, conservation organisations, and local communities around the world have developed a range of programmes aimed at protecting endangered species and restoring degraded ecosystems.

B. Protected areas — national parks, wildlife reserves, marine sanctuaries, and other designated zones — form the cornerstone of global conservation strategy. As of 2023, approximately 17 percent of the world's land surface and 8 percent of ocean areas are covered by some form of legal protection. The establishment of protected areas has been instrumental in saving numerous species from extinction, including the mountain gorilla in East Africa, the Arabian oryx in the Middle East, and the Iberian lynx in Spain. However, the effectiveness of protected areas depends critically on enforcement: many parks and reserves, particularly in developing countries, suffer from inadequate funding, understaffing, and the continued threat of poaching and illegal logging.

C. Captive breeding programmes represent another important tool in the conservation arsenal. By maintaining populations of critically endangered species in zoos, wildlife centres, and specialised breeding facilities, conservationists can safeguard genetic diversity and, in some cases, reintroduce animals into the wild. One of the most celebrated success stories is that of the California condor, North America's largest flying bird, which was reduced to just 22 individuals in 1982. An intensive captive breeding programme, combined with habitat protection and the elimination of lead ammunition (a major cause of condor mortality), has increased the population to over 500, with more than 300 living in the wild. Similarly, the black-footed ferret, once declared extinct in the wild, has been bred in captivity and reintroduced to grassland habitats across the western United States.

D. Community-based conservation has emerged as a particularly effective approach in regions where local people depend directly on natural resources for their livelihoods. Rather than imposing top-down restrictions, community-based programmes seek to involve indigenous and local communities as active partners in conservation, providing economic incentives for sustainable resource management. In Namibia, the establishment of communal conservancies — areas of land managed collectively by local communities for wildlife conservation and tourism — has led to dramatic increases in wildlife populations, including elephants, lions, and black rhinoceros, while generating significant income for rural communities through tourism ventures, trophy hunting concessions, and the sale of natural products. Similar models have been adopted in Kenya, Tanzania, and parts of South America.

E. Advances in technology are providing conservationists with powerful new tools for monitoring and protecting wildlife. GPS tracking collars and satellite telemetry enable researchers to follow the movements of individual animals across vast landscapes, providing data on migration routes, habitat use, and the impact of human activities. Drones equipped with thermal imaging cameras are being used to conduct wildlife surveys, monitor protected areas for illegal activity, and even deliver medical supplies to remote field stations. Environmental DNA (eDNA) — genetic material shed by organisms into water, soil, or air — can be collected and analysed to detect the presence of rare or elusive species without the need for direct observation, revolutionising biodiversity monitoring. Artificial intelligence is being applied to analyse camera trap images, acoustic recordings, and satellite imagery, dramatically accelerating the pace at which ecological data can be processed and interpreted.

F. Despite these advances, the scale of the conservation challenge continues to outpace the resources available to address it. Global spending on biodiversity conservation is estimated at approximately $124 billion per year, but the cost of effectively conserving the world's biodiversity has been calculated at $700 billion to $1 trillion annually. Closing this funding gap will require not only increased government spending but also innovative financing mechanisms such as biodiversity credits, payment for ecosystem services schemes, and the mobilisation of private capital through green bonds and impact investing. The Kunming-Montreal Global Biodiversity Framework, adopted in December 2022, set a target of protecting 30 percent of the world's land and ocean areas by 2030 — an ambitious goal that will require unprecedented levels of political commitment, international cooperation, and financial investment.`,
      questions: [
        { number: 14, type: "matching_headings", text: "Paragraph B", options: ["i. Technological innovations in wildlife monitoring", "ii. The role of legally designated conservation zones", "iii. Financial challenges in global conservation", "iv. Breeding endangered species in controlled environments", "v. The current scale of the biodiversity crisis", "vi. Involving local populations in conservation efforts", "vii. International agreements on biodiversity targets", "viii. The economic value of wildlife tourism"], correctAnswer: "ii", explanation: "Paragraph B discusses national parks, wildlife reserves, and marine sanctuaries — legally protected zones." },
        { number: 15, type: "matching_headings", text: "Paragraph C", options: ["i. Technological innovations in wildlife monitoring", "ii. The role of legally designated conservation zones", "iii. Financial challenges in global conservation", "iv. Breeding endangered species in controlled environments", "v. The current scale of the biodiversity crisis", "vi. Involving local populations in conservation efforts", "vii. International agreements on biodiversity targets", "viii. The economic value of wildlife tourism"], correctAnswer: "iv", explanation: "Paragraph C focuses on captive breeding programmes with examples of the California condor and black-footed ferret." },
        { number: 16, type: "matching_headings", text: "Paragraph D", options: ["i. Technological innovations in wildlife monitoring", "ii. The role of legally designated conservation zones", "iii. Financial challenges in global conservation", "iv. Breeding endangered species in controlled environments", "v. The current scale of the biodiversity crisis", "vi. Involving local populations in conservation efforts", "vii. International agreements on biodiversity targets", "viii. The economic value of wildlife tourism"], correctAnswer: "vi", explanation: "Paragraph D discusses community-based conservation with local communities as partners." },
        { number: 17, type: "matching_headings", text: "Paragraph E", options: ["i. Technological innovations in wildlife monitoring", "ii. The role of legally designated conservation zones", "iii. Financial challenges in global conservation", "iv. Breeding endangered species in controlled environments", "v. The current scale of the biodiversity crisis", "vi. Involving local populations in conservation efforts", "vii. International agreements on biodiversity targets", "viii. The economic value of wildlife tourism"], correctAnswer: "i", explanation: "Paragraph E covers GPS tracking, drones, eDNA, and AI — technological innovations." },
        { number: 18, type: "matching_headings", text: "Paragraph F", options: ["i. Technological innovations in wildlife monitoring", "ii. The role of legally designated conservation zones", "iii. Financial challenges in global conservation", "iv. Breeding endangered species in controlled environments", "v. The current scale of the biodiversity crisis", "vi. Involving local populations in conservation efforts", "vii. International agreements on biodiversity targets", "viii. The economic value of wildlife tourism"], correctAnswer: "iii", explanation: "Paragraph F discusses the funding gap between current spending ($124B) and what's needed ($700B–$1T)." },
        { number: 19, type: "table_completion", text: "According to the IUCN, _______ percent of amphibians are threatened with extinction.", correctAnswer: "41", explanation: "The passage states 'approximately 41 percent of amphibians.'" },
        { number: 20, type: "table_completion", text: "As of 2023, approximately _______ percent of the world's land surface is protected.", correctAnswer: "17", explanation: "The passage states 'approximately 17 percent of the world's land surface.'" },
        { number: 21, type: "table_completion", text: "The California condor population was reduced to just _______ individuals in 1982.", correctAnswer: "22", explanation: "The passage says 'reduced to just 22 individuals in 1982.'" },
        { number: 22, type: "table_completion", text: "The current California condor population has increased to over _______.", correctAnswer: "500", explanation: "The passage states the population has increased 'to over 500.'" },
        { number: 23, type: "table_completion", text: "Global spending on biodiversity conservation is approximately $_______ billion per year.", correctAnswer: "124", explanation: "The passage states 'approximately $124 billion per year.'" },
        { number: 24, type: "table_completion", text: "The Kunming-Montreal Framework targets protecting _______ percent of land and ocean by 2030.", correctAnswer: "30", explanation: "The passage mentions the target of 'protecting 30 percent.'" },
        { number: 25, type: "table_completion", text: "The Kunming-Montreal Global Biodiversity Framework was adopted in December _______.", correctAnswer: "2022", explanation: "The passage states it was 'adopted in December 2022.'" },
        { number: 26, type: "table_completion", text: "Environmental DNA is abbreviated as _______.", correctAnswer: "eDNA", explanation: "The passage introduces 'Environmental DNA (eDNA).'" },
      ],
    },
    {
      title: "Robotics in Healthcare",
      text: `The application of robotics in healthcare represents one of the most dynamic and rapidly evolving fields at the intersection of engineering, medicine, and computer science. From surgical robots that enhance the precision and safety of complex operations to assistive devices that help patients recover mobility, robotic technologies are fundamentally transforming the way medical care is delivered.

A. Surgical robotics has been at the forefront of medical technology innovation since the introduction of the da Vinci Surgical System by Intuitive Surgical in 2000. The da Vinci system consists of a surgeon's console, a patient-side cart with four robotic arms, and a high-definition 3D vision system. The surgeon operates the robotic arms remotely, using hand controls that translate natural hand and wrist movements into precise micro-movements of the surgical instruments inside the patient's body. The system's instruments can rotate 360 degrees and articulate far beyond the natural range of the human hand, enabling surgeons to operate through tiny incisions with a level of dexterity that would be impossible with conventional laparoscopic tools. As of 2023, more than 7,500 da Vinci systems have been installed worldwide, and over 12 million procedures have been performed using the platform. Common applications include prostatectomy, hysterectomy, cardiac valve repair, and various forms of cancer surgery.

B. Beyond the operating theatre, robots are increasingly being deployed in hospital pharmacies, laboratories, and logistics systems. Pharmacy robots can accurately dispense, package, and label thousands of medication doses per hour, reducing the risk of human error in a process where mistakes can have life-threatening consequences. Autonomous mobile robots (AMRs) are used in hospitals to transport supplies, medications, laboratory specimens, and even meals along predetermined routes, freeing nursing staff to focus on direct patient care. In clinical laboratories, robotic systems automate the processing of blood and tissue samples, increasing throughput and consistency while reducing the exposure of laboratory workers to potentially hazardous biological materials.

C. Rehabilitation robotics is a rapidly growing field that aims to help patients recover motor function following stroke, spinal cord injury, traumatic brain injury, or orthopaedic surgery. Robotic exoskeletons — wearable devices that support and augment the wearer's limb movements — enable patients with lower-limb paralysis to stand and walk during therapy sessions, providing the intensive, repetitive practice that is essential for neural recovery. Companies such as Ekso Bionics, ReWalk, and Cyberdyne have developed powered exoskeletons that are now used in rehabilitation centres worldwide. Upper-limb rehabilitation robots, which guide patients through arm and hand exercises, have been shown to improve motor outcomes in stroke survivors when used as a complement to conventional physiotherapy. The key advantage of robotic rehabilitation is its ability to deliver consistent, measurable, and precisely controlled therapy sessions, enabling clinicians to track patient progress with objective data.

D. Social and companion robots are emerging as a novel approach to addressing the emotional and psychological needs of patients, particularly the elderly and those with dementia. PARO, a therapeutic robot designed to resemble a baby harp seal, was developed in Japan and has been used in nursing homes and hospitals in over 30 countries. Studies have shown that interaction with PARO can reduce stress, anxiety, and agitation in dementia patients, while improving social interaction and mood. Other companion robots, such as Pepper (developed by SoftBank Robotics), can engage patients in conversation, lead exercise programmes, provide medication reminders, and even detect emotional states through facial expression analysis and voice tone recognition. While some critics question the ethics of using robots as substitutes for human companionship, proponents argue that companion robots are a valuable supplement to, rather than a replacement for, human caregiving.

E. The integration of artificial intelligence is enabling the next generation of healthcare robots to become more autonomous, adaptive, and capable. AI-powered surgical robots are being developed that can plan and execute certain aspects of procedures independently, based on pre-operative imaging data and real-time feedback from sensors embedded in surgical instruments. Machine learning algorithms enable rehabilitation robots to adapt their assistance levels automatically, providing more support when a patient is struggling and less when they are performing well — an approach known as "assist-as-needed." Natural language processing allows social robots to engage in more natural and contextually appropriate conversations with patients, improving user acceptance and therapeutic effectiveness.

F. Despite the enormous potential of healthcare robotics, several challenges must be addressed before these technologies can achieve widespread adoption. The cost of robotic systems remains a significant barrier, particularly for hospitals in developing countries: a single da Vinci surgical system, for example, costs between $1 million and $2.5 million, with additional annual maintenance fees. Regulatory pathways for approving new robotic medical devices can be lengthy and complex. There are also important questions about liability — if a surgical robot causes harm, who bears legal responsibility: the surgeon, the hospital, or the manufacturer? Training healthcare professionals to operate and interact with robotic systems requires substantial investment in education and ongoing professional development. Finally, ensuring cybersecurity for connected robotic devices is paramount, as any vulnerability could potentially be exploited to compromise patient safety.`,
      questions: [
        { number: 27, type: "matching_information", text: "The issue of legal responsibility when robots cause harm", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "F", explanation: "Paragraph F discusses liability questions: 'if a surgical robot causes harm, who bears legal responsibility.'" },
        { number: 28, type: "matching_information", text: "Robots that provide emotional support to elderly patients", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "D", explanation: "Paragraph D discusses companion robots like PARO for elderly and dementia patients." },
        { number: 29, type: "matching_information", text: "The use of AI to adjust the level of support given during patient exercises", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "E", explanation: "Paragraph E describes the 'assist-as-needed' approach using machine learning." },
        { number: 30, type: "matching_information", text: "Robots that deliver supplies within hospitals", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "B", explanation: "Paragraph B discusses autonomous mobile robots transporting supplies and medications." },
        { number: 31, type: "matching_information", text: "The number of surgical procedures performed using a specific robotic platform", options: ["A Paragraph A", "B Paragraph B", "C Paragraph C", "D Paragraph D", "E Paragraph E", "F Paragraph F"], correctAnswer: "A", explanation: "Paragraph A states 'over 12 million procedures have been performed using the platform.'" },
        { number: 32, type: "sentence_completion", text: "The da Vinci system's instruments can rotate _______ degrees.", correctAnswer: "360", explanation: "The passage states instruments 'can rotate 360 degrees.'" },
        { number: 33, type: "sentence_completion", text: "More than _______ da Vinci systems have been installed worldwide as of 2023.", correctAnswer: "7,500", explanation: "The passage says 'more than 7,500 da Vinci systems have been installed.'" },
        { number: 34, type: "sentence_completion", text: "PARO is designed to resemble a baby harp _______.", correctAnswer: "seal", explanation: "The passage describes PARO as 'designed to resemble a baby harp seal.'" },
        { number: 35, type: "sentence_completion", text: "A single da Vinci system costs between $1 million and $_______ million.", correctAnswer: "2.5", explanation: "The passage states 'costs between $1 million and $2.5 million.'" },
        { number: 36, type: "sentence_completion", text: "The approach where robots provide more support when patients struggle is called _______.", correctAnswer: "assist-as-needed", explanation: "The passage names this approach 'assist-as-needed.'" },
        { number: 37, type: "short_answer", text: "In what year was the da Vinci Surgical System introduced?", correctAnswer: "2000", explanation: "The passage states it was introduced 'in 2000.'" },
        { number: 38, type: "short_answer", text: "Name one company that has developed powered exoskeletons for rehabilitation.", correctAnswer: "Ekso Bionics", explanation: "The passage mentions Ekso Bionics, ReWalk, and Cyberdyne. Any one is acceptable." },
        { number: 39, type: "short_answer", text: "In how many countries has PARO been used?", correctAnswer: "over 30", explanation: "The passage states PARO 'has been used in nursing homes and hospitals in over 30 countries.'" },
        { number: 40, type: "short_answer", text: "What technology allows social robots to have natural conversations with patients?", correctAnswer: "natural language processing", explanation: "The passage says 'Natural language processing allows social robots to engage in more natural conversations.'" },
      ],
    },
  ],
};
